### ISSUE TITLE
Newline character in emq.conf causing error

### ISSUE THREAD

**Issue by vidhill** [emqtt/emqttd#1000]
#### Environment

- OS: Alpine 3.4
- Erlang/OTP: 
- EMQ: 2.1.0

#### Description

*A description of the issue*

I ran into a strange issue, it is a bit of an edge case and 
I have put in a workaround but it might be worth being aware of. 

In the default emq.conf file that is a newline character at the end of the file, as here:
``` bash
cat -A emq.conf
```
![screenshot from 2017-04-14 15-32-34](https://cloud.githubusercontent.com/assets/3375475/25049016/7e59a97e-2137-11e7-9794-932f8e339963.png)

A colleague was merging my emq.conf file and somewhere along the way the newline got removed, as can be seen below:
``` bash
cat -A emq.conf
```
![screenshot from 2017-04-14 15-36-15](https://cloud.githubusercontent.com/assets/3375475/25048991/583bec8e-2137-11e7-86eb-5b91869e5b30.png)

This resulted in the EMQ process failing with an error:
```
[cont-init.d] pre: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
16:56:38.970 [error] Error generating configuration in phase transform_datatypes
16:56:38.970 [error] Error transforming datatype for: sysmon.busy_dist_port
16:56:38.970 [error] "true##--------------------------------------------------------------------" is not a valid enum value, acceptable values are: true, false
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
```
I know that that configuration file gets transformed into a 'tuple', 
I reckon that, in this case the parser that does this is failing.

**Comment by emqplus** [comment]
@vidhill  I commited a fix in emq-relx project: https://github.com/emqtt/emq-relx/commit/68001c3ba3b5290513d72eedad388b5fc053b549

The `bin/nodetool` will contact all the configuration files under `etc/` folder and translate to data/app.conf.

**Comment by vidhill** [comment]
Excellent, thanks

**Comment by dreamcatcha** [comment]
I can vouch for this still being a problem, Im using ansible with a template for the emq.conf file and if there is no newline after the last option it fails

Using emq 2.3-beta.4
