### ISSUE TITLE
Websocket Testing

### ISSUE THREAD

**Issue by satrox28** [emqtt/emqttd#1005]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP:  19
- EMQ: 2.1

#### Description
Trying to setup Websocket on EMQTTD.

I noticed that it has to run on 8083 for WS and 8084 for WSS.

May I know how can I test it. Is there any client available to test on EMQTTD. I tried to connect from MQTTBOX it's not connecting to the broker. Do I need to mention any path.

I am able to telnet to those port and it's open.

**Comment by turtleDeng** [comment]
@satrox28  http://emqtt.io/docs/v2/plugins.html#emq-dashboard-dashboard-plugin

**Comment by satrox28** [comment]
I have configured the required parameters on emq.conf.

Can you tell me how to test from browser. I am not able to find any document.

**Comment by turtleDeng** [comment]
@satrox28 
The Web Dashboard for EMQ broker. The plugin will be loaded automatically when the broker started successfully.
web browser http://localhost:18083, websocket

**Comment by satrox28** [comment]
Hi,

I am not looking for Web dashboard. I have a server installed and running on 1883, 8883, 8083 and 8084.

From external using MQTTFX I am able to connect to 1883 and 8883 ando post message and subscribe.

Similar to that I want to publish and subscribe to on port 8083 and 8084. I can see websocket port is running  on server side.

May I know how to test messages on port 8083 and 8084

Websocket and websocket SSL

**Comment by satrox28** [comment]
when i enable these 2 params, I am seeing error
#mqtt.listener.ssl.verify = verify_peer
#mqtt.listener.ssl.fail_if_no_peer_cert = true


verify return:1
139759038353112:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:s3_pkt.c:1487:SSL alert number 48
139759038353112:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:

Can you help me with this error, do EMQTT works fine with CA signed SSL on 8883 and 8043?.

**Comment by thinkbig1979** [comment]
I was also unable to connect to the server using websocket with MQTTBOX. 
Finally I figured out that I needed to set the server address to: SERVERIP:8030/mqtt
The /mqtt at the end of the address is what fixed it. Not sure why this is necessary though.

**Comment by emqplus** [comment]
@satrox28 The two-way SSL authentication will be enabled if your uncomment the 'mqtt.listener.ssl.verify' parameter.

**Comment by terry-xiaoyu** [comment]
Using SSL? If so, you need a trusted certificate instead of the default self-singed certificate. See [Websocket-Configs](http://emqtt.io/docs/v2/config.html#mqtt-websocket-ssl-listener-8084) for details.
