### ISSUE TITLE
emqttd attach can not work.

### ISSUE THREAD

**Issue by congleetea** [emqtt/emqttd#1012]
#### Environment

- OS: Ubuntu14.04
- Erlang/OTP: 19.1
- EMQ: v2.1.0

#### Description

In emq-docker, it uses /opt/emqttd/bin/emqttd foreground & to start emqttd, but when I use /opt/emqttd/bin/emqttd attach , it shows: 

`No running Erlang on pipe /tmp/erl_pipes/emqttd@127.0.0.1/erlang.pipe: No such file or directory`

even if I don't use docker, it also can not use attach.

**Comment by emqplus** [comment]
@congleetea You cannot attach the node which is started by 'bin/emqttd foreground' or 'bin/emqttd console'
