### ISSUE TITLE
Plugin development support with Elixir

### ISSUE THREAD

**Issue by s4kibs4mi** [emqtt/emqttd#1015]
#### Environment

- OS: *
- Erlang/OTP: *
- EMQ: *

#### Description
If emqttd plugins can be developed in elixir & can be used that will be helpful.

**Comment by emqplus** [comment]
@s4kibs4mi Plan to support this feature in 2.2 release.

**Comment by turtleDeng** [comment]
@s4kibs4mi  https://github.com/emqtt/emq-elixir-plugin

**Comment by emqplus** [comment]
@s4kibs4mi
