### ISSUE TITLE
Plugin emq_lua_hook does not work

### ISSUE THREAD

**Issue by michaelcplusplus** [emqtt/emqttd#1016]
#### Environment

- OS: SLES 11
- Erlang/OTP: TP 19 
- EMQ: 2.1.2

#### Description
Build emqtt broker with emq-lua-hook. All emq-lua-hook tests are passed.

Created a hook_lua directory with the following abc.lua file:
```

function on_message_publish(topic, payload, qos, retain)
    return "changed/topic", "hello", qos, retain
end

function register_hook()
    return "on_message_publish"
end
```

When starting the emq_lua_hook plugin the following error occurs in the emq console:

```
Load emq_mod_presence module successfully.
Load emq_mod_subscription module successfully.
dashboard:http listen on 0.0.0.0:30105 with 2 acceptors.
mqtt:tcp listen on 0.0.0.0:30101 with 8 acceptors.
mqtt:ssl listen on 0.0.0.0:30102 with 4 acceptors.
mqtt:ws listen on 0.0.0.0:30103 with 4 acceptors.
mqtt:wss listen on 0.0.0.0:30104 with 4 acceptors.
emqttd 2.1.2 is running now
Eshell V8.1  (abort with ^G)
(emqttd@127.0.0.1)1> 11:45:03.084 [error] Lua Hook: lua script "hook_lua/abc.lua
" register_hook() raise exception
```
Does anyone has any suggestions? Thanks.

**Comment by grutabow** [comment]
@michaelcplusplus  Official luerl does not work well with emqttd, since its luerl_scan module will not be loaded during bootstrap. This problem is fixed in the latest emq-lua-hook develop branch.

**Comment by michaelcplusplus** [comment]
Thanks. The emq_lua_hook works now.
