### ISSUE TITLE
 cleanSession: false not working

### ISSUE THREAD

**Issue by mkj-git** [emqtt/emqttd#1017]
This is paho JS client:

```
	this.getMqttClient = function() {
		console.log("getMqttClient called");
		if(mqttClient !== undefined && mqttClient.isConnected()) {
			return mqttClient;
		} else {
    		var constants = $injector.get('Constants'), userDetails = this.getCurrentUserDetails();
			mqttClient = new Paho.MQTT.Client(
				constants.MQTT_HOST,
				Number(constants.MQTT_PORT),
				'/mqtt',
				_ref.escapedUserId(userDetails.id)
			);
			return mqttClient;
		}
	}  

    mqttClient.connect({
      userName: Utils.escapedUserId(userDetails.id),
      password: userDetails.mqttPwd,
      onSuccess: onConnect,
      onFailure: onFailure,
      cleanSession: false
    });
```

Here I have set       cleanSession: false even then everytime when i install and reconnect with same userName but different password, it is not subscribing to any of the previous topics. WHY?

Does the password change make any difference for session?

**Comment by phanimahesh** [comment]
sessions are bound to client id, not user id. You need to set a static
client id or else libraries usually assign one randomly.

**Comment by mkj-git** [comment]
mqttClient = new Paho.MQTT.Client(
				constants.MQTT_HOST,
				Number(constants.MQTT_PORT),
				'/mqtt',
				_ref.escapedUserId(userDetails.id)
			);

`_ref.escapedUserId(userDetails.id)` is client id and it is same

**Comment by phanimahesh** [comment]
Oh, okay. I am not familiar with Paho API, so it wasn't obvious for me.
Password change shouldn't be an issue.

can you trace the clientid and confirm whether the issue is with messages
not being sent or not being received by paho? I've seen reports of Paho
ignoring messages from channels it didn't explicitly subscribe to. The
client that reconnected might be dropping messages in that case. My first
thoughts.

**Comment by mkj-git** [comment]
If paho would drop message then other client won't be able to get message but all messaging exchange across client is happening properly. So i don't think paho is dropping message. But yes persistence is not working

**Comment by emqplus** [comment]
@ralphtheninja Thanks for your support. I will close the Cool issue now.
