### ISSUE TITLE
Authenticate plugin

### ISSUE THREAD

**Issue by truonglx-56** [emqtt/emqttd#1019]
Hi, I'm writting a plugin with token([https://jwt.io](url)), but i do not know what project to use  verify token, i use RS512 to sign
Please, help me!

**Comment by lewnie** [comment]
Hi, try using https://github.com/talentdeficit/jsx and https://github.com/potatosalad/erlang-jose.

**Comment by truonglx-56** [comment]
Thanks for help!

**Comment by pavankumarkatakam** [comment]
Hi @truonglx-56, have completed writing the plugin.

**Comment by dhananjaysathe** [comment]
Where can i find this code ?

**Comment by dhananjaysathe** [comment]
bump @pavankumarkatakam @truonglx-56 is the jwt auth plugin code available somewhere?

**Comment by turtleDeng** [comment]
EMQ JWT Authentication Plugin https://github.com/emqtt/emq-auth-jwt
