### ISSUE TITLE
specify multiple tcp listeners

### ISSUE THREAD

**Issue by nestor5** [emqtt/emqttd#1020]
How to specify multiple tcp listeners?  I tried the following but none of them works.

mqtt.listener.tcp = 10.58.73.231:1883, 127.0.0.1:1883
mqtt.listener.tcp = 10.58.73.231:1883; 127.0.0.1:1883
mqtt.listener.tcp = [10.58.73.231:1883, 127.0.0.1:1883]

**Comment by emqplus** [comment]
@nestor5 This feature has been merged to `emq22` branch.

**Comment by emqplus** [comment]
@nestor5 The 2.2-beta.1 release supported to configure multiple listeners now:

```
listener.tcp.external = 0.0.0.0:1883
listener.tcp.internal = 127.0.0.1:11883
```
