### ISSUE TITLE
node not automatically connected to other nodes

### ISSUE THREAD

**Issue by nestor5** [emqtt/emqttd#1021]
After starting emqttd, nodes() shows nothing.  After running net_adm:world(), the node is connected to all other emqttd nodes:

(emqttd@a1.my.com)1> nodes().
[]
(emqttd@a1.my.com)2> net_adm:world().
['emqttd@a1.my.com', 'emqttd@a2.my.com', 'emqttd@a3.my.com']

Is this a feature or a bug?  How to tell emqttd to automatically connect to all other nodes?

**Comment by emqplus** [comment]
Clustering Guide: http://emqtt.io/docs/v2/cluster.html
