### ISSUE TITLE
emqttd-centos7-v2.1.2-1.el7.centos.x86_64.rpm conflicts with other packages

### ISSUE THREAD

**Issue by nestor5** [emqtt/emqttd#1022]
This is CentOS 7.3:

# rpm -i emqttd-centos7-v2.1.2-1.el7.centos.x86_64.rpm
[sudo] password for simon:
        file /etc from install of emqttd-2.1.2-1.el7.centos.x86_64 conflicts with file from package filesystem-3.2-21.el7.x86_64
        file /usr from install of emqttd-2.1.2-1.el7.centos.x86_64 conflicts with file from package filesystem-3.2-21.el7.x86_64
        file /usr/lib from install of emqttd-2.1.2-1.el7.centos.x86_64 conflicts with file from package filesystem-3.2-21.el7.x86_64
        file /var/lib from install of emqttd-2.1.2-1.el7.centos.x86_64 conflicts with file from package filesystem-3.2-21.el7.x86_64
        file /usr/lib/debug from install of emqttd-2.1.2-1.el7.centos.x86_64 conflicts with file from package filesystem-3.2-21.el7.x86_64
        file /usr/src/debug from install of emqttd-2.1.2-1.el7.centos.x86_64 conflicts with file from package filesystem-3.2-21.el7.x86_64
        file /usr/lib64 from install of emqttd-2.1.2-1.el7.centos.x86_64 conflicts with file from package filesystem-3.2-21.el7.x86_64
        file /usr/src from install of emqttd-2.1.2-1.el7.centos.x86_64 conflicts with file from package filesystem-3.2-21.el7.x86_64
        file /usr/sbin from install of emqttd-2.1.2-1.el7.centos.x86_64 conflicts with file from package filesystem-3.2-21.el7.x86_64
        file /var from install of emqttd-2.1.2-1.el7.centos.x86_64 conflicts with file from package filesystem-3.2-21.el7.x86_64
        file /var/log from install of emqttd-2.1.2-1.el7.centos.x86_64 conflicts with file from package filesystem-3.2-21.el7.x86_64
        file /etc/init.d from install of emqttd-2.1.2-1.el7.centos.x86_64 conflicts with file from package chkconfig-1.7.2-1.el7.x86_64

**Comment by turtleDeng** [comment]
@nestor5  rpm -ivh --force emqttd-centos7-v2.1.2-1.el7.centos.x86_64.rpm
