### ISSUE TITLE
emq mysql login issue

### ISSUE THREAD

**Issue by franklinxkk** [emqtt/emqttd#1028]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

log:
14:12:10.725 [error] Client(client@117.139.128.166:44837): Username 'bb00000000' login failed for password_error

 /etc/emqttd/plugins/emq_auth_mysql.conf ：
auth.mysql.password_hash = md5

but my database is:
INSERT INTO `mydb`.`mqtt_user` (`id`, `username`, `password`, `salt`, `is_superuser`, `created`) VALUES ('1', 'bb00000000', '846fae12e524edaa022ff8028383d02c', NULL, '0', '2017-04-29 14:16:54');
why did it not work

**Comment by turtleDeng** [comment]
@franklinxkk  What is the password entered by the client?

**Comment by franklinxkk** [comment]
used the org.fusesource.mqtt.client
....
mqtt.setUserName("bb00000000");
mqtt.setPassword("846fae12e524edaa022ff8028383d02c");
