### ISSUE TITLE
Can't start the console 

### ISSUE THREAD

**Issue by YouriKorostelev** [emqtt/emqttd#1032]
#### Environment

- OS: Windows 7
- Erlang/OTP: 19.3

- EMQ: 2.1.2

Hello,

I'm working on an IoT project and wanted to try the eMQTT broker with Paho Eclipse.
I followed the installation guide provided on the site [http://emqtt.io/docs/v2/install.html](url) (for a Windows environment)
I've installed the erlang as asked [https://www.erlang.org/downloads](url)
Unzipped the eMQTT package, in the installation folder and then tried to launch the console, using the windows command prompt (that i launched as an administrator)

However when i try to launch emqttd console, i get the following error:

```
C:\Program Files (x86)\eMQTT\emqttd-windows7-v2.1.2\emqttd\bin> .\emqttd console

C:\Program Files (x86)\eMQTT\emqttd-windows7-v2.1.2\emqttd\bin>set args_file=-args_file "C:\Program Files (x86)\eMQTT\emqttd-windows7-v2.1.2\emqttd\etc\vm.args"

C:\Program Files (x86)\eMQTT\emqttd-windows7-v2.1.2\emqttd\bin>set sys_config=-config "C:\Program Files (x86)\eMQTT\emqttd-windows7-v2.1.2\emqttd\etc\sys.config"
\eMQTT\emqttd-windows7-v2.1.2\emqttd\releases\2.1.2\emqttd was unexpected at this time.

C:\Program Files (x86)\eMQTT\emqttd-windows7-v2.1.2\emqttd\bin>  set boot_script=C:\Program Files (x86)\eMQTT\emqttd-windows7-v2.1.2\emqttd\releases\2.1.2\emqttd
````

I think, i misunderstood or missed some basic steps to the installation.
What am i doing wrong ?
Could you please help me out ?
Thanks !

**Comment by emqplus** [comment]
@YouriKorostelev The `bin\emqttd` script does not support the directory which contains spaces.

**Comment by YouriKorostelev** [comment]
Thank you sir.
That solved the issue, i didn't even think about it...
Have a good day
