### ISSUE TITLE
Connection lost infinite loop

### ISSUE THREAD

**Issue by eugene-haas** [emqtt/emqttd#1035]
#### Environment

- OS: ubuntu 16.04
- Erlang/OTP: 8.1
- EMQ: R2.1.0-beta1

#### Description

I have configured two emq-brokers and connected to the domain via haproxy.
When connected emq-broker independently, the connection is maintained stably, but connection via haproxy is unstable. The connections and disconnections are repeated infinitely at 0.5 second intervals.

The configuration of emq.conf has no change other than node.name, and haproxy uses load balance by setting mqtt.mydomain.com.

I do not know what makes this connection unstable.

There is no emq error log, but it seems to be a problem with configuring haproxy, and I want to know how to fix it.

* haproxy.cfg

        global
                log /dev/log    local0
                log /dev/log    local1 notice
                chroot /var/lib/haproxy
                stats socket /run/haproxy/admin.sock mode 660 level admin
                stats timeout 30s
                user haproxy
                group haproxy
                daemon
                ca-base /etc/ssl/certs
                crt-base /etc/ssl/private
                ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128
                ssl-default-bind-options no-sslv3

        defaults
                log     global
                mode    http
                option  httplog
                option  dontlognull
                timeout connect 5000
                timeout client  50000
                timeout server  50000
                errorfile 400 /etc/haproxy/errors/400.http
                errorfile 403 /etc/haproxy/errors/403.http
                errorfile 408 /etc/haproxy/errors/408.http
                errorfile 500 /etc/haproxy/errors/500.http
                errorfile 502 /etc/haproxy/errors/502.http
                errorfile 503 /etc/haproxy/errors/503.http
                errorfile 504 /etc/haproxy/errors/504.http

        frontend map_domain
                mode tcp
                bind *:1883
                bind *:8883
                use_backend mqtt-broker if { hdr(host) -i mqtt.mydomain.com }

        backend mqtt-broker
                mode tcp
                balance roundrobin
                server emq01 10.0.1.11:1883 check
                server emp02 10.0.2.12:1883 check

        listen stats
                bind *:1883
                mode tcp
                option tcplog
                server emq01 10.0.1.11:1883
                server emq02 10.0.2.12:1883
                stats enable
                stats hide-version
                stats realm HAproxy-Statistics
                stats uri /haproxy_stats

Is there a way to solve this problem?

**Comment by eugene-haas** [comment]
The cause could not be determined, but it was resolved.

**Comment by anupamadak** [comment]
I am facing the same issue , can you please tell how this issue got resolved.

**Comment by eugene-haas** [comment]
I could not figure out the cause, but it was solved, and the same issue occurred during client duplicate access.
One of the causes is that the client ID is duplicated and connected.
I do not know if this will help.
I am sorry that I can not help you.
