### ISSUE TITLE
Feature-Request: Shared subscriptions across cluster nodes (MQTT 5 spec)

### ISSUE THREAD

**Issue by gbrehmer** [emqtt/emqttd#1036]
like VerneMQ: https://vernemq.com/docs/configuration/shared_subscriptions.html (mode random)
spec: https://issues.oasis-open.org/browse/MQTT-234

**Comment by emqplus** [comment]
@gbrehmer EMQ will not support this mode for it's not reliable. Messages dispatched to remote nodes in the cluster will be lost quietly for there is no ACK mechanism.

**Comment by gbrehmer** [comment]
I don't know whether other brokers have an reliable implementation of this feature but I think the number of brokers with this feature will increase in the near future, because this type of load balancing can solve many performance/stability problems, if many messages must be handled by a single subscriber/backend-service. Because connections to the emq broker are loadbalanced, we are not able to verify, that the message-processing-backend has a connection to each node.
Another Broker with this Feature is the commercial HiveMQ mqtt broker.
