### ISSUE TITLE
进程异常退出

### ISSUE THREAD

**Issue by w3yyb** [emqtt/emqttd#104]
在做 benchmark时，好几次进程异常退出。。

**Comment by erylee** [comment]
0.5.4? or 0.6.1? mnesia crash?

**Comment by w3yyb** [comment]
0.6.1

**Comment by erylee** [comment]
any log?

**Comment by erylee** [comment]
first of all, do you tune linux kernel parameter?

https://github.com/emqtt/emqttd/wiki/One-Million-Connections(Draft)

**Comment by w3yyb** [comment]
I tuned.

**Comment by erylee** [comment]
attach your crash log

**Comment by w3yyb** [comment]
will later

**Comment by erylee** [comment]
duplicated with issue #54 and fixed in 0.6.2 release.
