### ISSUE TITLE
ACL with postgres based on client id or IP without authentication using emq_auth_pgsql

### ISSUE THREAD

**Issue by pritstift** [emqtt/emqttd#1041]
#### Environment

- OS: Mac OS 10.12
- Erlang/OTP: 19.0
- EMQ: 2.1.2

#### Description

I have opened that issue at emqtt/emq_auth_pqsql, but i hope getting some more info here :)

I am using EMQ with the emq_sn plugin. I have activated the emq-auth-pgsql plugin to achieve ACL based on client id or IP-address. However, as reported in issue [#18](https://github.com/emqtt/emq-auth-pgsql/issues/18), the broker denies access for clients that are not authenticated (i.e. with username and password).

To my best knowledge, MQTT-SN does not support authentication (at least it is not specified). This makes the emq-auth-pgsql plugin unusable with MQTT-SN.

is there a chance of decoupling auth and acl or configuring the plugin such that it allows for unauthenticated access?

**Comment by grutabow** [comment]
@pritstift  Add following entry in emq_sn.conf
```
mqtt.sn.username = mqtt_sn_user
mqtt.sn.password = abc
```
Thus mqtt-sn plugin will connect emqttd core with this username.

Please add this username in your emq_auth_pqsql.

**Comment by grutabow** [comment]
This feature will be released in next official version.

**Comment by pritstift** [comment]
Thanks. Will give it a try when the new release comes out 👍

**Comment by pritstift** [comment]
Thanks for bringin out the new release.

It seems to work so far. Thank you very much! But something seems wrong when i have a look at the logs:

```
23:38:20.602 [error] MQTT-SN(127.0.0.1:57342): UNEXPECTED INFO: emit_stats
23:38:20.602 [error] MQTT-SN(127.0.0.1:57342): UNEXPECTED INFO: {subscribe,[{<<"$client/mqtt-sn-tools-99190">>,1}]}
```

Is this something to be worried about?

**Comment by grutabow** [comment]
@pritstift  Don't worry about these error messages which means emq-sn does not support statistic features. Will support it in next version and eliminate errors.

**Comment by pritstift** [comment]
I tested it for some while and it works. Thank you very much. I am closing this issue now. 

But I think this solution does not fix the actual problem that you cannot have ACL based on IP adresses without authentication (e.g. even if you are not using the emq_sn plugin). 

I would prefer having an option in the auth_pgsql plugin that turns off authentication.
