### ISSUE TITLE
Allow for Content-Type:application/json in HTTP Publish API

### ISSUE THREAD

**Issue by pritstift** [emqtt/emqttd#1045]
#### Environment

- OS: Mac OS 10.12
- Erlang/OTP: 19.01
- EMQ: 2.1.2

#### Description

It seems like the HTTP Publish API does only accept `Content-Type: application/x-www-form-urlencoded`. When i try `curl -v --basic -u user:passwd -H "Content-Type: application/json" -X POST -d '{"qos":1, "retain":0, "topic":"world", "meesage":"test"}' -k http://127.0.0.1:8083/mqtt/publish` i get
```
* upload completely sent off: 56 out of 56 bytes
* Curl_http_done: called premature == 0
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server
```

So the emq HTTP Publish API doesn't seem to work with application/json content-type. Is that correct or am I missing something?

**Comment by turtleDeng** [comment]
@pritstift This issue has been fixed in 2.2-beta.2
