### ISSUE TITLE
Incorrect username with correct password can login (MySQL auth)

### ISSUE THREAD

**Issue by edmandiesamonte** [emqtt/emqttd#1048]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 19
- EMQ: Latest (2.2 beta)

#### Description

Using emq_auth_mysql, clients can connect to host using an incorrect username with correct password. Tried to rollback to 2.1.2 and it does not happen. 

Also, no documentation as to why `auth.mysql.acl_nomatch = deny` was removed from the conf file. I'm not sure if it has something to do with the bug.

**Comment by turtleDeng** [comment]
@edmandiesamonte  etc/emq.conf  mqtt.acl_nomatch

**Comment by edmandiesamonte** [comment]
Thanks, @turtleDeng. I might have missed it in the docs.
