### ISSUE TITLE
How can I use LDAP Authentication Plugin

### ISSUE THREAD

**Issue by mostafiz789** [emqtt/emqttd#1049]
#### Environment

- OS: Windows 10
- Erlang/OTP: 19.0
- EMQ: 2.1.2

I want to use LDAP Authentication Plugin based authentication from paho java client. Is LDAP plugin functional? If so how can I test LDAP is running after install emqtt? How can I implement this? Is there any sample implementation which I can follow? TIA

**Comment by turtleDeng** [comment]
@mostafiz789  http://emqtt.io/docs/v2/plugins.html#emq-auth-ldap-ldap-auth-plugin

**Comment by mostafiz789** [comment]
@turtleDeng thanks, I am able to use LDAP authentication plugin at windows, but I also want to use at docker image, for this, I need to change the configuration of LDAP plugin. I found the way https://github.com/emqtt/emq-docker by using the environment variable. But haven't manage to set the config value, can you help me by giving sample command to change *auth.ldap.port = 389* and *auth.ldap.user_dn = uid=%u,ou=People,dc=example,dc=com* parameter of LDAP plugin?

**Comment by turtleDeng** [comment]
@mostafiz789 
```
-e EMQ_AUTH__LDAP__PORT="your port" \
```

**Comment by emqplus** [comment]
@mostafiz789 Closed the issue.
