### ISSUE TITLE
Are shared subscriptions supported across cluster?

### ISSUE THREAD

**Issue by ajay-aggarwal** [emqtt/emqttd#1052]
The documentation says  "Shared Subscription supports Load balancing to distribute MQTT messages between multiple subscribers in the same group"

Its not clear if they work on a single node only or across cluster as well? If I have a cluster will the shared subscription messages be distributed (load-balanced) across the cluster nodes?

**Comment by yogin16** [comment]
I don't think so.
I could find the following related issue: https://github.com/emqtt/emqttd/issues/1036

**Comment by emqplus** [comment]
@ajay-aggarwal @yogin16  The shared subscription works on a single node, and you can use '$local/$share/<group>/topic' to balance the consumption across the cluster nodes.

**Comment by gbrehmer** [comment]
@emqplus will active subscribers be preferred? Like if you have multiple subscribers with session enabled and part of the subscribers is currently offline.
