### ISSUE TITLE
Using wss://ip:8084 to access EMQ

### ISSUE THREAD

**Issue by maxshucn** [emqtt/emqttd#1056]
#### Environment

- OS: centos7.1
- Erlang/OTP: 7.3
- EMQ: 2.0.7

#### Description
How to use **wss**://xxxx:8084/mqtt/  style to use emqttd?  notice:  like https style.
I use  [http://www.hivemq.com/demos/websocket-client/](http://www.hivemq.com/demos/websocket-client/)  to test,  if I don't select ssl, it's working, if I select ssl, it's not working.

**Comment by terry-xiaoyu** [comment]
@maxshucn The hivemq demo uses a JS (mqttws31.js) in browser to access the MQTT broker, and thus it won't support self-signed ssl certificates by default - it depends on the trusted CA certificates installed in your browser.
You need a CA SSL certificate, and configure it in your emq.conf file.
If you just want to have a try with you self-signed certificate (there's already one configured in the emq.conf), try to install the cert in your browser by accessing 'https://xxxx:8084/mqtt', and then select 'continue' if any warning about security.
The [mqttws31.js ](https://eclipse.org/paho/clients/js/) uses the 'wss://' style to connect to the Broker, you could dive into the code if you want to know more.

**Comment by maxshucn** [comment]
I had imported my self-signed certificate to ie. but not working...

**Comment by terry-xiaoyu** [comment]
@maxshucn Use the original self-sgined certificate come with EMQ, and do not modify the emq.conf. Then install the certs by accessing 'https://xxxx:8084' and click continue or 'always trust' when the address bar becomes red. This works fine for me.
If not, try the similar procedure with Chrome or other web browsers.

**Comment by emqplus** [comment]
@maxshucn Please fix your SSL configurations of EMQ first. I will close the issue now.  @terry-xiaoyu

**Comment by maxshucn** [comment]
:-(
