### ISSUE TITLE
客户端 只要一连接 emqttd 进程就自动退出 

### ISSUE THREAD

**Issue by w3yyb** [emqtt/emqttd#106]
0.6.1 版

**Comment by w3yyb** [comment]
确切说是一刷新就退出 ，每次都是 。2台机器 都一样

**Comment by erylee** [comment]
你这问题单提得…... 比如退出:

1. emqttd运行的服务器类型，操作系统、内存等

2. 进程异常退出，系统日志是什么，emqttd crash日志是什么？

3. 客户端收到什么错误？

问题单上，什么都不贴。就一句“地球自转好像不对了”，你觉得我该如何处理？

**Comment by w3yyb** [comment]
找到问题了，只要设置 cleansession=0 就退出

**Comment by erylee** [comment]
ok, I check it now...

**Comment by erylee** [comment]
杨，

My QQ: 22061135,

Skype: feng.emqtt.io

Feng

**Comment by erylee** [comment]
My Test: 

13:54:04.633 [info] Connect from 127.0.0.1:51342 -> 127.0.0.1:1883
13:54:04.634 [info] RECV from undefined@127.0.0.1:51342: CONNECT(Qos=0, Retain=false, Dup=false, ClientId=testClientId, ProtoName=MQTT, ProtoVsn=4, CleanSess=false, KeepAlive=60, Username=undefined, Password=undefined)
13:54:04.634 [info] event PUBLISH to $SYS/brokers/emqttd@127.0.0.1/clients/testClientId/connected
13:54:04.634 [info] SEND to testClientId@127.0.0.1:51342: CONNACK(Qos=0, Retain=false, Dup=false, AckFlags=0, RetainCode=0)

13:55:04.641 [info] RECV from testClientId@127.0.0.1:51342: PINGREQ(Qos=0, Retain=false, Dup=false)
13:55:04.641 [info] SEND to testClientId@127.0.0.1:51342: PINGRESP(Qos=0, Retain=false, Dup=false)
13:55:28.259 [info] RECV from testClientId@127.0.0.1:51342: SUBSCRIBE(Qos=1, Retain=false, Dup=false, PacketId=1, TopicTable=[{<<"a/bc/d">>,0}])
13:55:28.260 [info] <0.255.0> call <0.199.0>
13:55:28.261 [info] Client testClientId subscribe [{<<"a/bc/d">>,0}]. Granted QoS: [0]

13:55:54.794 [info] RECV from testClientId@127.0.0.1:51342: PUBLISH(Qos=0, Retain=false, Dup=false, TopicName=a/bc/d, PacketId=undefined, Payload=<<"haha">>)
13:55:54.794 [info] testClientId PUBLISH to a/bc/d
13:55:54.795 [info] SEND to testClientId@127.0.0.1:51342: PUBLISH(Qos=0, Retain=false, Dup=false, TopicName=a/bc/d, PacketId=undefined, Payload=<<"haha">>)

**Comment by w3yyb** [comment]
要刷新才 退出的，，第一次连接不会退出

**Comment by erylee** [comment]
This issue is duplicated with #54 and fixed in 0.6.2 release.
