### ISSUE TITLE
How i can use MySql plugin to authorize MQTT client. Please don't give 

### ISSUE THREAD

**Issue by kamleshnarola** [emqtt/emqttd#1061]
#### Environment

-EMQ
-MySql plugins

#### Description
I want to authorize MQTT client using mysql plugin, i have try all the way which is give at 
[https://github.com/emqtt/emq-auth-mysql](https://github.com/emqtt/emq-auth-mysql)
Every time it gives 
,{1045,<<"28000">>,<<"Access denied for user ''@'localhost' (using password: NO)">>}}}}}}}}},[{emq_auth_mysql_app,start,2,[{file,"src/emq_auth_mysql_app.erl"},{line,33}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}]}}}}

*A description of the issue*

**Comment by emqplus** [comment]
@kamleshnarola The plugin cannot access your MySQL server, please check the MySQL parameters.
```
Access denied for user ''@'localhost' (using password: NO)
```
