### ISSUE TITLE
clustering - add more than two nodes 

### ISSUE THREAD

**Issue by m-abdalrahman** [emqtt/emqttd#1065]
#### Environment

- OS: Ubuntu 16:04
- EMQ: emqttd-2.1.2

when I try to add new node using `emqttd_ctl cluster join` if nodes more then 2, I find other node not in cluster, and stopped.

**Comment by turtleDeng** [comment]
@m-abdalrahman  New node joins the cluster,  new_node  emqttd_ctl cluster join cluster_node

**Comment by satrox28** [comment]
Hi,
We are facing the similar issue, is it possible to create a 4node emqttd cluster?. Whenever I try to add 3rd node, 2nd node is disconnected. 

Can you tell me, how to fix this issue.

**Comment by satrox28** [comment]
Can we have 4node cluster?

**Comment by turtleDeng** [comment]
@satrox28 Of course

**Comment by satrox28** [comment]
I got it working with 4nodes, thanks. Any update on 2.2 release as managing multiple nodes stats in each page is difficult.
