### ISSUE TITLE
chaining authentications? 

### ISSUE THREAD

**Issue by wiiikiii** [emqtt/emqttd#1082]
#### Environment

- OS: FreeBSD
- Erlang/OTP: 18
- EMQ: 22

#### Description

I am working on a fine graded authentication system based on auth_http. All requests will be checked agains a webservice.

To make my life easies I'd like to chain authentifikations. The idea is to have emq_auth_username for general system subscriptions done with acl.conf and the rest via emq_auth_http?

Is that possible?

**Comment by emqplus** [comment]
@wiiikiii Load the `emq_auth_username` plugin first, and then load the emq_auth_http.
