### ISSUE TITLE
setting up a superuser with em_auth_username

### ISSUE THREAD

**Issue by wiiikiii** [emqtt/emqttd#1083]
#### Environment

- OS: FreeBSD
- Erlang/OTP: 18
- EMQ: 22

#### Description

I try to setup a superuser with only em_auth_username. With sql based system and all others it is working.

Is there a way?

**Comment by emqplus** [comment]
@wiiikiii EMQ R2.2 supports Authentication/ACL chain. You can load more than one authentication plugin at the same time.

Documentation: http://emqtt.io/docs/v2/guide.html#authentication
