### ISSUE TITLE
How much memory does every client connection take?

### ISSUE THREAD

**Issue by nestor5** [emqtt/emqttd#1085]
I have observed that for every 100 MQTT client connections, about 42M more memory is used.  Not sure if my observation is correct.

Could you please give an estimation of memory usage per client?

Any recommendation on configuration of emqttd or linux kernel to make emqttd more memory efficient?

Thanks

#### Environment

- OS: CentOS 7.3
- Erlang/OTP: 19.3
- EMQ: 2.1.2

#### Description

*A description of the issue*

**Comment by emqplus** [comment]
Benchmark documentation: http://emq-xmeter-benchmark-en.readthedocs.io/en/latest/
