### ISSUE TITLE
How to store all MQTT messages to MongoDB

### ISSUE THREAD

**Issue by duythang** [emqtt/emqttd#1086]
Dear authors

I want to store all incoming MQTT messages from EMQTT to Mongo.
I am confusing how can I do this because I see in EMQTT guide of Mongo Plugin
https://github.com/emqtt/emq-auth-mongo 
MongoDB is only used to store authentication info. 

Hope you can help me. Thank you so much.

**Comment by plugplayco** [comment]
Hi @emqplus  and @huangdan

is this feature deployed in EMQTT 2.2-beta.3 or i have to wait for next version ?

Thank you.

**Comment by duythang** [comment]
Dear @emqplus  and @huangdan 

Is this feature deployed into 2.2-beta.3 or I have to wait for next version ?

Thank you so much.

**Comment by turtleDeng** [comment]
@duythang we have released an enterprise edition of EMQ to support persistence in mongodb backends. I plan to upgrade the emqtt.io site and publish the edition later:)
