### ISSUE TITLE
Publish on $SYS/brokers/${node}/clients/ not working on 2.1.2

### ISSUE THREAD

**Issue by davidepozza** [emqtt/emqttd#1089]
#### Environment

OS: Docker alpine:3.4
Erlang/OTP: default installed from this alpine version repos
EMQ: v2.1.2

#### Description

No connect/disconnect notifications are published on $SYS/brokers/${node}/clients/# anymore.
Previously I was using the 2.0.7 and they were working without any problem.
If I try to subscribe to "$SYS/#" I can receive all the other SYS messages like "uptime", "datetime" and so on (so I'm sure that my ACLs are well configured). Just the client connect/disconnect notifications are missing.

Have they been disabled by default? If so which is the configuration parameter I should change?

Thank you in advance

**Comment by emqplus** [comment]
@davidepozza Please subscribe `$SYS/brokers/+/clients/#`.

**Comment by davidepozza** [comment]
Hello
Already tried that subscription. No notifications at all. This was the reason because I also tried to subscribe to $SYS/#. On the previous message I wrote "$SYS/brokers/${node}/clients/#" but I was meaning "$SYS/brokers/+/clients/#"

**Comment by emqplus** [comment]
@davidepozza We cannot reproduce the issue. The steps:

1. Start EMQ 2.1.2:
```
feng$ ./bin/emqttd_ctl status
Node 'emqttd@127.0.0.1' is started
emqttd 2.1.2 is running
```

2. `mosquitto_sub` the '$SYS/brokers/+/clients/#' topic on localhost:

```
mosquitto_sub -t '$SYS/brokers/+/clients/#' -d
```

3. Create a MQTT client and then CTRL+C to kill: 

```
 mosquitto_sub -t t -d
```

4. The MQTT messages received from `$SYS/brokers/+/clients/#` topic:

```
FengdeMacBook-Pro:~ feng$ mosquitto_sub -t '$SYS/brokers/+/clients/#' -d
Client mosqsub/18695-FengdeMac sending CONNECT
Client mosqsub/18695-FengdeMac received CONNACK
Client mosqsub/18695-FengdeMac sending SUBSCRIBE (Mid: 1, Topic: $SYS/brokers/+/clients/#, QoS: 0)
Client mosqsub/18695-FengdeMac received SUBACK
Subscribed (mid: 1): 0
Client mosqsub/18695-FengdeMac received PUBLISH (d0, q0, r0, m0, '$SYS/brokers/emqttd@127.0.0.1/clients/mosqsub/18698-FengdeMac/connected', ... (144 bytes))
{"clientid":"mosqsub/18698-FengdeMac","username":"undefined","ipaddress":"127.0.0.1","clean_sess":true,"protocol":3,"connack":0,"ts":1496885750}
Client mosqsub/18695-FengdeMac received PUBLISH (d0, q0, r0, m0, '$SYS/brokers/emqttd@127.0.0.1/clients/mosqsub/18698-FengdeMac/disconnected', ... (72 bytes))
{"clientid":"mosqsub/18698-FengdeMac","reason":"closed","ts":1496885750}
Client mosqsub/18695-FengdeMac sending PINGREQ
```

**Comment by davidepozza** [comment]
Dears
I can confirm that your use case works.
I forgot to tell you that on my use case I'm using the redis auth plugin. It seems that the issue is strictly related to that additional component.
I created another use case with the same version and configuration of your use case and just added the redis auth plugin. On redis I executed the following commands:
redis-cli HSET "mqtt_user:myuser" "password" "mypass" 
redis-cli HSET "mqtt_acl: myuser" "\$SYS/#" "1"

With this configuration you should be able to reproduce the issue that, as I previously said, is only related to the publishing on $SYS/brokers/+/clients/#. All the other $SYS messages are correctly received.

**Comment by totojack** [comment]
We found the problem: from release 2.1 module emq_mod_presence was deprecated, and we didn't load the plugin into EMQ_LOADED_PLUGINS variable. So, the solution was to replace emq_mod_presence with emq_modules

**Comment by emqplus** [comment]
@davidepozza I will reopen the issue and reproduce it with Redis Plugin.

**Comment by chinhnguyentrung** [comment]
@davidepozza I think the cause could be that "{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}." in etc/acl.config file.
