### ISSUE TITLE
Allow subscribing via HTTP

### ISSUE THREAD

**Issue by CheyenneForbes** [emqtt/emqttd#1093]
I am building a messaging platform using EMQTT and I believe allowing subscriptions through a HTTP API would be a great feature for EMQTT.

**My use case:**

**1.** On the web server, check if both users already have a chat together in the database.
**2.** If they don't, create one and subscribe both users to the chat's ID via a HTTP call to the EMQTT cluster (like with the HTTP Publish API)

**Comment by CheyenneForbes** [comment]
I added the code to enable the feature [https://github.com/emqtt/emqttd/compare/develop...CheyenneForbes:patch-1](https://github.com/emqtt/emqttd/compare/develop...CheyenneForbes:patch-1)

**Comment by emqplus** [comment]
@CheyenneForbes The HTTP API will be separated from MQTT/WS in 2.2-rc.1 release. You can submit a PR Later, Thanks.

**Comment by CheyenneForbes** [comment]
@emqplus When will it be released?

**Comment by emqplus** [comment]
@CheyenneForbes This feature has been released in 2.3-beta.2. Documentation: https://github.com/emqtt/emq-docs-en/blob/master/source/rest.rst#create-a-subscription
