### ISSUE TITLE
[EMQTT] emq_auth_mongo with wrong username still connect success

### ISSUE THREAD

**Issue by dinhquy94** [emqtt/emqttd#1095]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: v2.3 beta

#### Description

*A description of the issue*
 I have downloaded and current I am using emqtt latest version (emqttd-2.2-beta.3 has been released on 2017-05-27).
I active plugin emq_auth_mongo and config all done. When I connect to server with auth like that:

var client  = mqtt.connect('mqtt://localhost:1883',
{
	username: 'test123',
	password: '1234567'  
});

then:
- With exactly username/password, connection success
- With exactly username and wrong password, connection fail
- With wrong username and wrong password, connection success (why?)
- With wrong username and exactly password, connection success.

This is 4 cases in my test, I think that is bug, if I wrong, please explain me more detail and help me fix.

**Comment by emqplus** [comment]
@dinhquy94 Tune off the anonymous authentication in etc/emq.conf:

```
mqtt.allow_anonymous = true
```
