### ISSUE TITLE
emqttd starts from console but not as a service?

### ISSUE THREAD

**Issue by Bazmundi** [emqtt/emqttd#1104]
#### Environment

- OS:  armbian.org debian server: ARMBIAN 5.31 stable Debian GNU/Linux 8 (jessie) 3.4.113-sun8i
- Erlang/OTP: V9.2/19
- EMQ: 2.2

#### Description

Can run emqttd from /opt/emqttd/bin/emqttd but it fails when attemting to run it as a service.

The following runs from the console but does not run at startup:

```
#! /bin/sh
#  /etc/init.d/mqtt

case "$1" in
    start)
      echo "Starting eqmttd"
      /opt/emqttd/bin/emqttd start
      ;;
    stop)
      echo "Stopping emqttd"
      /opt/emqttd/bin/emqttd stop
      ;;
    restart)
      echo "Restarting emqttd"
      /opt/emqttd/bin/emqttd stop
      /opt/emqttd/bin/emqttd start
      ;;
    *)
      echo "Usage: /etc/init.d/mqtt {start|stop|restart}"
     /opt/emqttd/bin/emqttd stop
      /opt/emqttd/bin/emqttd start
      ;;
    *)
      echo "Usage: /etc/init.d/mqtt {start|stop|restart}"
      exit 1
esac

exit 0
```

The error reported is:

```
root@house:~# systemctl -l status mqtt.service
? mqtt.service - (null)
   Loaded: loaded (/etc/init.d/mqtt)
   Active: failed (Result: exit-code) since Fri 2017-06-16 08:46:52 CEST; 24min ago
  Process: 979 ExecStart=/etc/init.d/mqtt start (code=exited, status=1/FAILURE)

Jun 16 08:46:36 house mqtt[979]: Starting eqmttd
Jun 16 08:46:52 house systemd[1]: mqtt.service: control process exited, code=exited status=1
Jun 16 08:46:52 house systemd[1]: Failed to start (null).
Jun 16 08:46:52 house systemd[1]: Unit mqtt.service entered failed state.
```

Is there an interaction between emqttd and systemd?

**Comment by turtleDeng** [comment]
@Bazmundi  http://emqtt.io/docs/v2/install.html#install-via-deb

**Comment by Bazmundi** [comment]
@turtleDeng and?

I did pose the question on emqttd groups about the /etc/rc.f/init.d/functions file.  Including what was the point of the "functions" file which does not come with my version of linux.  

I had no /etc/rc.d/init.d/functions.  

I found a "version" on the internet but that did not help from the group.

So, add a rogue file from "somewhere", into a mix that isn't working, didn't make sense.

I am not even sure the functions file was being called?

**Comment by Bazmundi** [comment]
@turtleDeng and so ...

... chkconfig --del mqtt

returned:

insserv: warning: script 'mqtt' missing LSB tags and overrides
mqtt                      0:off  1:off  2:off  3:off  4:off  5:off  6:of

**Comment by Bazmundi** [comment]
@turtleDeng ta da!

```
root@house:~# systemctl -l status mqtt.service
? mqtt.service - SYSV: emqttd is mqtt broker.
   Loaded: loaded (/etc/init.d/mqtt)
   Active: inactive (dead)
```

**Comment by Bazmundi** [comment]
@turtleDeng wow
These strips are tricky with all the undocumented "features"
My script would not start with either service or systemctl.
The http://emqtt.io/docs/v2/install.html#install-via-deb script starts using service but still doesn't appear to run on boot.

**Comment by Bazmundi** [comment]
Just after booting:

```
root@house:~# systemctl -l status mqtt.service
? mqtt.service - SYSV: emqttd is mqtt broker.
   Loaded: loaded (/etc/init.d/mqtt)
   Active: inactive (dead)
```

```
root@house:~# systemctl enable mqtt
Synchronizing state for mqtt.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d mqtt defaults
insserv: warning: script 'mqtt' missing LSB tags and overrides
Executing /usr/sbin/update-rc.d mqtt enable
update-rc.d: error: mqtt Default-Start contains no runlevels, aborting.
```

**Comment by turtleDeng** [comment]
@Bazmundi 
systemd service https://github.com/emqtt/emq-package/blob/master/rpm/emqttd.service

/usr/lib/systemd/system/emqttd.service

**Comment by Bazmundi** [comment]
should:

```
[Service]
Type=forking
Environment=HOME=/root
ExecStart=/bin/sh emqttd start
```

Become:

[```
Service]
Type=forking
Environment=HOME=/root
ExecStart=/bin/sh /opt/emqttd/bin/emqttd start
```

And I assume that is instead of /etc/init.d/mqtt?  So I should delete /etc/init.d/mqtt?

**Comment by Bazmundi** [comment]
@turtleDeng ah hem

From reboot with /etc/init.d/mqtt deleted and /usr/lib/systemd/system/emqttd.service created at your behest:

```
root@house:~# systemctl -l status mqtt
? mqtt.service - emqtt daemon
   Loaded: loaded (/usr/lib/systemd/system/mqtt.service; disabled)
   Active: inactive (dead)
```

**Comment by Bazmundi** [comment]
@turtleDeng perhaps,

There is a school of thought on one forum that the following is needed (a change to /opt/emqttd/bin/emqttd):

Changed /opt/emqttd/bin/emqttd to turn off console on startup (doesn’t work).  Or at least the example code I used does not work as advertised.  The change suggested is from:

`-args_file $RUNNER_ETC_DIR/vm.args `

To:

`-args_file $RUNNER_ETC_DIR/vm.args -detached -noinput -noshell -- ${1+"$@"}"`

Guess what, that didn't work for me either BUT the """ at the end is ambiguous as the code in the emqttd file is surrounded by "" - so I wasn't sure if the author was lazy (and left out the " at the far left of line) or the change was to be within "<changed line>"

**Comment by Bazmundi** [comment]
@turtleDeng so

from console:

```
root@house:~# service mqtt start
root@house:~# systemctl -l status mqtt
? mqtt.service - emqtt daemon
   Loaded: loaded (/usr/lib/systemd/system/mqtt.service; disabled)
   Active: active (running) since Mon 2017-06-19 14:03:23 CEST; 2min 37s ago
  Process: 869 ExecStart=/bin/sh /opt/emqttd/bin/emqttd start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/mqtt.service
           tq 925 /opt/emqttd/erts-8.2/bin/epmd -daemon
           tq 932 /opt/emqttd/erts-8.2/bin/run_erl -daemon /tmp/root_erl_pipes/emqttd@127.0.0.1/ /opt/emqttd/log exec "/opt/emqttd/bin/emqttd" "console"
           tq 934 /opt/emqttd/erts-8.2/bin/beam.smp -W w -e 256000 -Q 65536 -P 256000 -A 32 -K true -zdbbl 32768 -- -root /opt/emqttd -progname opt/emqttd/bin/emqttd -- -home /root -- -boot /opt/emqttd/releases/2.2/emqttd -mode embedded -boot_var ERTS_LIB_DIR /opt/emqttd/erts-8.2/../lib -mnesia dir "/opt/emqttd/data/mnesia/emqttd@127.0.0.1" -config /opt/emqttd/data/configs/app.2017.06.19.14.03.09.config -kernel net_ticktime 60 -smp auto -setcookie emqsecretcookie -name emqttd@127.0.0.1 -vm_args /opt/emqttd/data/configs/vm.2017.06.19.14.03.09.args -- console
           tq1199 erl_child_setup 1024
           tq1273 sh -s disksup
           tq1274 /opt/emqttd/lib/os_mon-2.4.1/priv/bin/memsup
           mq1276 /opt/emqttd/lib/os_mon-2.4.1/priv/bin/cpu_sup

Jun 19 14:03:23 house sh[869]: emqttd 2.2 is started successfully!
Jun 19 14:03:23 house systemd[1]: Started emqtt daemon.
```

**Comment by Bazmundi** [comment]
@turtleDeng Here we are full circle.

**Comment by Bazmundi** [comment]
What I also see on boot is:

```
root@house:~# systemctl --failed
  UNIT                         LOAD   ACTIVE SUB    DESCRIPTION
? systemd-modules-load.service loaded failed failed Load Kernel Modules
```

**Comment by Bazmundi** [comment]
@turtleDeng hmmm

Using /usr/lib/systemd/system/mqtt.service (instead of /etc/init.d/mqtt) I find mqtt does not turn up when listing with:

`chkconfig --list`

Nor can I add it with: 

`chkconfig --add mqtt`

or:

`chkconfig --add /usr/lib/systemd/system/mqtt.service`

So I can't work out (yet) what runlevel the mqtt.service is running at (yet) - I am still muddling through learning this admin fun.

**Comment by Bazmundi** [comment]
@turtleDeng have you given up?  Is there someone who can help please then if you cannot?

**Comment by turtleDeng** [comment]
@Bazmundi  systemctl enable emqttd.service

**Comment by Bazmundi** [comment]
@turtleDeng leave that with me

I have found that the emqttd service dabblings have, some how, now broken my node-red service startup.

I will get back to this once I have seen what has stopped the node-red service.

**Comment by Bazmundi** [comment]
@turtleDeng another problem has popped up.  My board seems to have dropped its lan config???

Probably note related but I can see node-red running (but can't browse to my OPiZ), but it still doesn't report emqttd as having started on reboot.  

Let me sort the problem with IP and I will then look at the enabling of the mqtt service.

Note I did enable the service as you suggested.  Prior to rebooting I could browse into node-red.  After rebooting no browsing??

**Comment by Bazmundi** [comment]
@turtleDeng nope

```
systemctl enable emqttd.service
reboot
```

Once up again:

```
root@house:~# systemctl --failed
  UNIT                         LOAD   ACTIVE SUB    DESCRIPTION
? mqtt.service                 loaded failed failed emqtt daemon
? systemd-modules-load.service loaded failed failed Load Kernel Modules

```

**Comment by Bazmundi** [comment]
@turtleDeng WTFO?

So, having enabled the service to find it still won't start.  And then disabling to try to get it back to the original state.  It turns out that it does not start at all now - not even in console.

Previously, as reported, it would start using:

`service mqtt start`

Now it reports:

`job for mqtt.service failed. See 'systemctl status mqtt.service' and 'journalctl -xn' for details.`

Even the `systemctl start mqtt.service` equivalent now reports the same.

```
systemctl status mqtt.service
? mqtt.service - emqtt daemon
   Loaded: loaded (/usr/lib/systemd/system/mqtt.service; disabled)
   Active: failed (Result: exit-code) since Wed 2017-06-21 12:57:17 CEST; 21s ago
  Process: 815 ExecStart=/bin/sh /opt/emqttd/bin/emqttd start (code=exited, status=127)

Jun 21 12:57:17 house sh[815]: /bin/sh: 0: Can't open /opt/emqttd/bin/emqttd
Jun 21 12:57:17 house systemd[1]: mqtt.service: control process exited, cod...27
Jun 21 12:57:17 house systemd[1]: Failed to start emqtt daemon.
Jun 21 12:57:17 house systemd[1]: Unit mqtt.service entered failed state.
```

**Comment by Bazmundi** [comment]
@turtleDeng thank you for your patience.

That was the last piece of the puzzle.  The the OPiZ now boots both node-red and emqttd so I have a match box sized mqtt/node-red server at last.

Thankyou again.

**Comment by Bazmundi** [comment]
I can confirm, after rebooting a number of times, the emqttd starts without having to log in and run it from console.

I did have a niggly problem were I couldn't even browse into node-red (which was starting on boot fine).  It seems occasionally my OPiZ was starting up with no connection configuration (static IP, gateway address nor DNS addresses).  I will count that as a separate problem (and likely not for emqttd issue).
