### ISSUE TITLE
Store Data to Database

### ISSUE THREAD

**Issue by TuanTuanTu** [emqtt/emqttd#1107]
How can I store data like client, topic, event... to my database? Use client library or what plugin is best way?

**Comment by emqplus** [comment]
Hi @TuanTuanTu, We have released an Enterprise Edition - EMQ X to support various backends including MySQL, Redis, PostgreSQL, MongoDB. Please contact [Hong](mailto:hong@emqtt.io ) for quotations. Thanks.

**Comment by TuanTuanTu** [comment]
Thanks, I have a question. How can I get all live client? and all topic throw your dashboard API?
