### ISSUE TITLE
Forced Subscriptions

### ISSUE THREAD

**Issue by Hades32** [emqtt/emqttd#111]
*feature request*
We're migrating away from IBM WebSphere MQ (as it is terrible), but it has a feature that we found useful at first and now have issues migrating away from it:

IBM MQ allows to send messages "point 2 point" which means you can send a mqtt message to a specific client without that client even being subscribed to any topic.

The most mqtt idiomatic way of implementing that, which I could think of, was to configure the broker with "forced subscription", like "foo/broadcast" or "foo/p2p/$c" which all clients get an automatic subscription to (without getting a SUBACK of course). The server could then send e.g. to "foo/p2p/client1" to reach exactly the client with client id "client1".

Besides enabling the migration scenario from IBM MQ this also allows for sending messages to clients  directly after they have connection and thus saving a few hundred ms what a SUB could take over a GSM network.

**Comment by erylee** [comment]
The feature is easy to implemented I think if pubsub works well:)

Have a question about the 'point 2 point' mode: which topic the sender publish message to?

**Comment by Hades32** [comment]
That sounds great! :)

The sender has to know of the special topics. So in the above example this would be 'foo/p2p/SOME_CLIENTID'.

IBM MQ implements this with some special queues, but this clearly nit appropriate here :)

**Comment by erylee** [comment]
okay, I will write a simple design first and plan this feature in 0.7.x release.

**Comment by erylee** [comment]
@Hades32, please checkout 'issue#111' branch and build.  I implemented a simple P2P queue that a client will subscribe automatically when connected. 

1. etc/emqttd.config:

```
 %% Subscribe these topics automatically when client connected
 {forced_subscriptions, [{"$Q/client/$c", 0}]},
```

2. send message to the queue.

If the feature works for your project, I will improve the design.

**Comment by Hades32** [comment]
Hy @erylee I'm not really sure what a "queue" in emqtt is/does, but I made some tests with my "foo/bar/CLIENT1" topics and even with some ACL rules that protect the topics accordingly and it worked flawlessly! 

Thanks so much!

What I haven't tried yet is cluster behavior. I guess it SHOULD work in a cluster environment?

**Comment by erylee** [comment]
@Hades32, This feature works well in cluster environment. I write a simple introduction about Queue: https://github.com/emqtt/emqttd/wiki/Queue-Design

I will improve the design in 0.8.0 release. Any suggestion and issue report is welcome:)

**Comment by erylee** [comment]
Support this feature by emqttd_mod_autosub module in formal 0.8.0 release
