### ISSUE TITLE
Connection Timeout Broker Crashed...

### ISSUE THREAD

**Issue by SumitFlochat** [emqtt/emqttd#1115]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

Connection Timeout.

2017-06-28 06:41:06 =ERROR REPORT====
** Generic server <0.7007.0> terminating
** Last message in was {inet_async,{ssl_socket,#Port<0.3303>,{sslsocket,{gen_tcp,#Port<0.3303>,tls_connection,undefined},<0.7008.0>}},#Ref<0.0.2.5668>,{ok,<<16,210,1,0,6,77,81,73,115,100,112,3,44,0,20,0,38,53,57,53,49,51,55,100,100,49,54,102,100,102,97,51,101,55,55,52,52,48,101,99,57,47,49,52,57,56,52,57,52,57,53,50,53,48,52,0,33,112,114,101,115,101,110,99,101,47,53,57,53,49,51,55,100,100,49,54,102,100,102,97,51,101,55,55,52,52,48,101,99,57,0,121,123,34,99,97,116,101,103,111,114,121,34,58,48,44,34,100,97,116,97,34,58,123,34,112,114,101,115,101,110,99,101,34,58,34,108,97,115,116,32,115,101,101,110,32,97,116,32,49,48,58,50,56,97,109,34,125,44,34,108,97,116,34,58,48,46,48,44,34,108,111,110,34,58,48,46,48,44,34,115,101,110,100,101,114,73,100,34,58,34,53,57,53,49,51,55,100,100,49,54,102,100,102,97,51,101,55,55,52,52,48,101,99,57,34,44,34,118,34,58,48,125>>}}
** When Server state == {client_state,{esockd_connection,[{ssl_socket,#Port<0.3303>,{sslsocket,{gen_tcp,#Port<0.3303>,tls_connection,undefined},<0.7008.0>}},#Fun<esockd_transport.3.2626899>,[]]},["10.0.51.48",58,"51447"],{{10,0,51,48},51447},{10,0,51,48},51447,true,running,undefined,#Fun<emqttd_parser.0.27418187>,{proto_state,{{10,0,51,48},51447},#Fun<emqttd_client.0.88959049>,false,undefined,<0.7007.0>,undefined,undefined,undefined,undefined,false,undefined,undefined,1024,undefined,undefined,undefined},[{max_clientid_len,1024},{max_packet_size,65536},{client_idle_timeout,60}],undefined,undefined}
** Reason for termination ==
** {{timeout,{gen_server2,call,[<0.1284.0>,{start_session,false,{<<"595137dd16fdfa3e77440ec9/1498494952504">>,undefined},<0.7007.0>},120000]}},[{gen_server2,call,3,[{file,"src/gen_server2.erl"},{line,340}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,182}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,266}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-06-28 06:41:06 =CRASH REPORT====
  crasher:
    initial call: emqttd_client:init/1
    pid: <0.7007.0>
    registered_name: []
    exception exit: {{timeout,{gen_server2,call,[<0.1284.0>,{start_session,false,{<<"595137dd16fdfa3e77440ec9/1498494952504">>,undefined},<0.7007.0>},120000]}},[{gen_server,terminate,7,[{file,"gen_server.erl"},{line,826}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [<0.2362.0>,<0.2361.0>,esockd_sup,<0.1117.0>]
    messages: []
    links: [<0.2362.0>]
    dictionary: [{guid,{1498631941121644,56736517987167,0}}]
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 3501
  neighbours:
2017-06-28 06:41:06 =SUPERVISOR REPORT====
     Supervisor: 'esockd_connection_sup - <0.2362.0>'
     Context:    connection_crashed
     Reason:     {timeout,{gen_server2,call,[<0.1284.0>,{start_session,false,{<<"595137dd16fdfa3e77440ec9/1498494952504">>,undefined},<0.7007.0>},120000]}}
     Offender:   [{pid,<0.7007.0>},{name,connection},{mfargs,{emqttd_client,start_link,[[{max_clientid_len,1024},{max_packet_size,65536},{client_idle_timeout,60}]]}}]

**Comment by emqplus** [comment]
Invalid issue, won't fix.

**Comment by SumitFlochat** [comment]
I am stuck kindly help me how to fix on my end?

**Comment by SumitFlochat** [comment]
Can you specify the reason for this crash or help me with the way to get out of this?
It will be a great help.

**Comment by SumitFlochat** [comment]
Atleast let me know the issue so that i can figure out the way to get out of it.
I am stuck on my production and its down since 26th June
