### ISSUE TITLE
QoS 1 and 2 seem to malfunction (testing with malaria)

### ISSUE THREAD

**Issue by syberkitten** [emqtt/emqttd#1118]
#### Environment
- OS: 
 Linux Obuntu 14.04 LTS
On Amazon ECS - 4 cores, 16gb.

- Erlang/OTP: 
[{release,"Erlang/OTP","19","8.3",
          [{kernel,"5.2","/usr/lib/erlang/lib/kernel-5.2"},
           {stdlib,"3.3","/usr/lib/erlang/lib/stdlib-3.3"},
           {sasl,"3.0.3","/usr/lib/erlang/lib/sasl-3.0.3"}],
          permanent}]

- EMQ: 
Latest Master 2.2
compiled from  https://github.com/emqtt/emq-relx.git

#### Description
Testing Qos 1 and Qos 2 with [Malaria](https://github.com/remakeelectric/mqtt-malaria)
 yields that only QoS 0 is stable and all messages arrive to subscribers.

With Qos 1 and Qos 2 not all messages are received...
and the Malaria subscriber simply waits for many messages
while the subscriber says it's finished.

It seems like the messages are simply not routed to all the clients
and the dashboard does not report any of these anomalies.

Does EMQ have tests that make sure all units functioning correctly?

# Reproduce:

malaria subscribe -n 1000 -N 20 --host emq.net -q 1
malaria publish -t -n 1000 -P 20 --host emq.net -q 1
**:fails.**

malaria subscribe -n 1000 -N 20 --host emq.net -q 2
malaria publish -t -n 1000 -P 20 --host emq.net -q 2
**- fails.**

malaria subscribe -n 1000 -N 20 --host emq.net -q 0
malaria publish -t -n 1000 -P 20 --host emq.net -q 0
**- Success.**

**Comment by emqplus** [comment]
@syberkitten Thanks for your report. @huangdan will benchmark EMQ with Malaria tool and try to reproduce the issue.

**Comment by syberkitten** [comment]
Adding to the report, first try with 10 workers, 20 seems too much, at least on my local machine.
so, 10 should not be clogging the bandwidth, but it still fails:

The following example creates sends 1000 messages for every worker (10k messages)
malaria subscribe -n 1000 -N 10 --host emq.net -q 1
malaria publish -t -n 1000 -P 10 --host emq.net -q 1

ps: Also nodjes Mosca broker fails these tests, the only broker that did pass
was verneMQ. both Qos1/2

**Comment by emqplus** [comment]
@syberkitten Tune the two parameters in etc/emq.conf:

```
mqtt.mqueue.max_length = 0
mqtt.session.max_awaiting_rel = 0
```

By default, the EMQ broker will queue 1000 Qos1/2 messages for each session to avoid memory overload. 

The full benchmark report for EMQ 2.0: http://emq-xmeter-benchmark-en.readthedocs.io/en/latest/

**Comment by syberkitten** [comment]
Yes, this fixes the problem perfectly.
Thank you 👍
