### ISSUE TITLE
Shared subscription for $Sys Topic

### ISSUE THREAD

**Issue by miller111** [emqtt/emqttd#1123]
#### Environment

- OS: Linux RHEL
- Erlang/OTP: 
- EMQ: 2.0

#### Description
We want to use $SYS topic to get the client connected and disconnected events. However we have multiple servers and each one subscribes to this Topic.
 Is there a way we can use shared subscription for $SYS topic?

**Comment by emqplus** [comment]
@miller111 Please subscribe to the topic '$share/<group>/$SYS/#'

**Comment by ankurgarg1041** [comment]
@emqplus  Thanks . 
It was mentioned on http://emqtt.io/docs/v2 that "The broker only allows clients from localhost to subscribe $SYS topics by default".

How can we change it to allow subscription on $SYS topic from non localhost clients?

**Comment by miller111** [comment]
@emqplus Thanks .
It was mentioned on http://emqtt.io/docs/v2 that "The broker only allows clients from localhost to subscribe $SYS topics by default".

How can we change it to allow subscription on $SYS topic from non localhost clients?

**Comment by emqplus** [comment]
Configure the internal ACL rules in 'etc/acl.conf' file:

```
{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.

{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.

{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.
```

**Comment by Rebellioncry** [comment]
hello @emqplus ,I have this problem, too，my environment follow as ：
EMQX：3.4.2，
springboot：2.1.6，
org.eclipse.paho.client.mqttv3：1.2.0
I subscribe to the topic like '$share/group/$SYS/#' ,but it does not work.It will have an exception："org.eclipse.paho.client.mqttv3.MqttException: MqttException"。
so how to shared system topic？Looking forword your reply!
