### ISSUE TITLE
Build Works But No executables

### ISSUE THREAD

**Issue by codewiget95** [emqtt/emqttd#1125]
#### Environment

- OS: Ubuntu 14
- Erlang/OTP: 18.2
- EMQ: Erl 2.1.2

#### Description

Hello, 

For backround, I am attempting to modify Erlang source code to add Pre-Shared Key support, which is why I need to compile from source.

I downloaded the source for EMQ v2.1.2. When I used 'make', I got a message saying that there was a syntax error, and other issues suggested that i revert my Erlang version to 18. So I just reverted the Erlang to 18.2, and now it "makes" but there are no executables created.

Afterwards, i attempted to install emq-rlx, cloning from the repository and making, and got the following error : 

In file included from c_src/async_queue.c:32:0:
c_src/async_queue.h:45:21: fatal error: erl_nif.h: No such file or directory
 #include <erl_nif.h>
                     ^
compilation terminated.

Could this be because my erlang version is 18? For this project, I need a stable version of emq, and the most recent is 2.1. So, I need Erlang 18 or earlier to compile , I believe. Any information that you can provide that will help me compile, I would greatly appreciate !

I appreciate all of your help
Thanks!

**Comment by turtleDeng** [comment]
@codewiget95 sudo apt-get install libbsd-dev

**Comment by codewiget95** [comment]
@turtleDeng I did that, and then I just upgraded my GNU make to version 4, but it is still not giving me any bin folder to start my emqttd console with my RP 18.2 and emq 2.1.2.

**Comment by turtleDeng** [comment]
@codewiget95  Run make command, console print log sent me

**Comment by codewiget95** [comment]
@turtleDeng, I upgraded my Erlang install to the most updated version, and compiled and made the emq-rlx perfectly fine. I'm not sure which version of Erlang should be used with 2.1.2

**Comment by emqplus** [comment]
@codewiget95 EMQ R2.1.2 requires Erlang/OTP R19+ to build, and EMQ R2.2 requires Erlang/OTP R19.3+
