### ISSUE TITLE
increase io/max_fds

### ISSUE THREAD

**Issue by hos7ein** [emqtt/emqttd#1126]
#### Environment

- OS: centos 7.3
- Erlang/OTP: 
- EMQ: emqttd-centos7-v2.1.2-1.el7.centos.x86_64.rpm
- Kernel : 3.10.0-514.26.1.el7.x86_64

#### Description

Followed all the [instructions listed in doc](http://docs.emqtt.com/en/latest/tune.html), but the io/max_fds was always 1024. 

```bash
 # emqttd_ctl vm io

io/max_fds              : 1024
io/active_fds           : 1
```
how can I increase io/max_fds ?
Tnx

- My Config : 

> /etc/security/limits.conf

`*      soft   nofile      1048576`
`*      hard   nofile      1048576`

> /etc/sysctl.conf 

`fs.file-max=2097152`
`fs.nr_open=2097152`
`net.core.somaxconn=32768`
`net.ipv4.tcp_max_syn_backlog=16384`
`net.core.netdev_max_backlog=16384`
`net.ipv4.ip_local_port_range=1000 65535`
`net.core.rmem_default=262144`
`net.core.wmem_default=262144`
`net.core.rmem_max=16777216`
`net.core.wmem_max=16777216`
`net.core.optmem_max=16777216`
`net.ipv4.tcp_rmem=1024 4096 16777216`
`net.ipv4.tcp_wmem=1024 4096 16777216`
`net.nf_conntrack_max=1000000`
`net.netfilter.nf_conntrack_max=1000000`
`net.netfilter.nf_conntrack_tcp_timeout_time_wait=30`
`net.ipv4.tcp_max_tw_buckets=1048576`
`net.ipv4.tcp_fin_timeout = 15`

```bash
# emqttd_ctl status
Node 'emqttd@127.0.0.1' is started
emqttd 2.1.2 is running
```

```bash
# emqttd_ctl vm memory
memory/total            : 79186248
memory/processes        : 26412864
memory/processes_used   : 26412784
memory/system           : 52773384
memory/atom             : 1000625
memory/atom_used        : 977584
memory/binary           : 11752
memory/code             : 25459482
memory/ets              : 5450928
```

```bash
# emqttd_ctl listeners
listener on mqtt:wss:8084
  acceptors       : 4
  max_clients     : 64
  current_clients : 0
  shutdown_count  : []
listener on mqtt:ws:8083
  acceptors       : 4
  max_clients     : 64
  current_clients : 0
  shutdown_count  : []
listener on mqtt:ssl:8883
  acceptors       : 4
  max_clients     : 512
  current_clients : 0
  shutdown_count  : []
listener on mqtt:tcp:1883
  acceptors       : 64
  max_clients     : 1000000
  current_clients : 0
  shutdown_count  : []
listener on dashboard:http:18083
  acceptors       : 2
  max_clients     : 512
  current_clients : 0
  shutdown_count  : []
```

**Comment by emqplus** [comment]
@hos7ein Do you check the max-fds allowed by 'ulimit -n'?

**Comment by hos7ein** [comment]
@emqplus  Tnx for reply

```bash
# ulimit -n
1048576
```

**Comment by turtleDeng** [comment]
@hos7ein 

vim /etc/systemd/system.conf

```
DefaultLimitNOFILE= 1048576
```

**Comment by hos7ein** [comment]
@turtleDeng  
tnx, it's worked
