### ISSUE TITLE
Can't start background service

### ISSUE THREAD

**Issue by anchandan** [emqtt/emqttd#1129]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: 2.2

#### Description

emqtt is not starting on startup after adding it as a service.

This is the unit file:

```
[Unit]
Description=emqttd - Erlang MQTT broker
Documentation=http://emqtt.io/docs/v2/
Wants=network-online.target
After=network-online.target

[Service]
#emqttd can't be tracked with a single PID as it starts a number of sub-processes
#so we treat it as a one-shot, per example 3 in https://www.freedesktop.org/software/systemd/man/systemd.service.html
#systemd doesn't recognise a primary process (so there can be no auto-restart after failure)
#and the ExecStart and ExecStop directives refer to brief program runs that manage the sub-processes
Type=oneshot
RemainAfterExit=yes
#EnvironmentFile=-/etc/default/emqttd # the prefix hyphen means that this is an optional file
User=emqttd
Group=emqttd
WorkingDirectory=/opt/emqttd
ExecStart=/opt/emqttd/bin/emqttd start
ExecStop=/opt/emqttd/bin/emqttd stop

[Install]
WantedBy=multi-user.target
```

This is the error:
Loaded: loaded (/etc/systemd/system/emqtt.service; enabled; vendor preset: enabled)
   **_Active: failed_** (Result: exit-code) since Mon 2017-07-03 13:11:21 IST; 14s ago
     Docs: http://emqtt.io/docs/v2/
  Process: 22607 ExecStart=/opt/emqttd/bin/emqttd start (code=exited, status=217/USER)
 Main PID: 22607 (code=exited, status=217/USER)

**Comment by turtleDeng** [comment]
@anchandan The status code ("217/USER") seems to indicate that the user you specified in the service declaration is not valid on your system.
