### ISSUE TITLE
What about ErlPort?

### ISSUE THREAD

**Issue by mindflayer** [emqtt/emqttd#113]
What about adding ErlPort (http://erlport.org/) to support plugins made in Python and Ruby?

The project is on GitHub, as well, at:
https://github.com/hdima/erlport

**Comment by mindflayer** [comment]
On Python side, I can help writing some test plugins, if needed.

**Comment by erylee** [comment]
Giorgio,

This is cool, I will check it later. emqtt 0.7.0 release will support a simple plugin architecture based on OTP application.

Regards
Feng

**Comment by erylee** [comment]
@mindflayer, I released 0.8.0 with a simple plugin mechanism, please try and help me write some test plugins:)  

Plugin Design: https://github.com/emqtt/emqttd/wiki/Plugin%20Design

**Comment by mindflayer** [comment]
As far as I understand, only Erlang is supported. Am I wrong?

**Comment by erylee** [comment]
Write plugin with Erlang, and use ErlPort to connect to python or ruby program
