### ISSUE TITLE
Emqttd crashed when stress test is running

### ISSUE THREAD

**Issue by sincethen** [emqtt/emqttd#1130]
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP: 20/9.0
- EMQ: 2.1.2
- CPU: 4-vcore
- MEM: 8GB

#### Description

I used emqtt_benchmark to run stress test. When I simulated 8k publishers to run for minutes, the system would be out of memory and the emqttd processes would be crashed:

###### emq.conf is default except for:
    mqtt.listener.tcp.max_clients = 65536
    mqtt.listener.ssl.max_clients = 65536
###### acl.conf is default except for:
    {allow, all, subscribe, ["$SYS/#", {eq, "#"}]}.

###### Sub:
    ./emqtt_bench_sub -h <emqttd-ip> -c 8 -t bench/test
###### Pub:
    ./emqtt_bench_pub -h <emqttd-ip> -c 8000 -t bench/test -q 0

###### CPU & MEM Usage(OOM can be observed)
![image](https://user-images.githubusercontent.com/13453681/27821523-270d17fe-60d5-11e7-84d2-e8afa25f1d3e.png)
###### error.log
    2017-07-04 11:44:15.777 [error] <0.1139.0> Supervisor 'esockd_connection_sup - <0.1139.0>' had child connection started with mochiweb_http:start_link({emq_dashboard,handle_request,[{state,"/usr/lib/emqttd/lib/emq_dashboard-2.1.2/priv/www",#Fun<emq_d..>}]}) at <0.17389.0> exit with reason {json_encode,{bad_term,{'EXIT',{badarith,[{emqttd_vm,loads,0,[{file,"src/emqttd_vm.erl"},{line,160}]},{emq_dashboard_overview,node_info,0,[{file,"src/emq_dashboard_overview.erl"},{line,77}]},{rpc,local_call,3,[{file,"rpc.erl"},{line,311}]},{emq_dashboard_overview,'-nodes_info/0-lc$^0/1-0-',2,[{file,"src/emq_dashboard_overview.erl"},{line,73}]},{emq_dashboard_overview,nodes_info,0,[{file,"src/emq_dashboard_overview.erl"},{line,73}]},{emq_dashboard,'-dispatcher/1-fun-3-',4,[{file,"src/emq_das..."},...]},...]}}}} in context connection_crashed
###### crash.log
    2017-07-04 11:44:15 =SUPERVISOR REPORT====
     Supervisor: 'esockd_connection_sup - <0.1139.0>'
     Context:    connection_crashed
     Reason:     {json_encode,{bad_term,{'EXIT',{badarith,[{emqttd_vm,loads,0,[{file,"src/emqttd_vm.erl"},{line,160}]},{emq_dashboard_overview,node_info,0,[{file,"src/emq_dashboard_overview.erl"},{line,77}]},{rpc,local_call,3,[{file,"rpc.erl"},{line,311}]},{emq_dashboard_overview,'-nodes_info/0-lc$^0/1-0-',2,[{file,"src/emq_dashboard_overview.erl"},{line,73}]},{emq_dashboard_overview,nodes_info,0,[{file,"src/emq_dashboard_overview.erl"},{line,73}]},{emq_dashboard,'-dispatcher/1-fun-3-',4,[{file,"src/emq_dashboard.erl"},{line,52}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,75}]}]}}}}
     Offender:   [{pid,<0.17389.0>},{name,connection},{mfargs,{mochiweb_http,start_link,[{emq_dashboard,handle_request,[{state,"/usr/lib/emqttd/lib/emq_dashboard-2.1.2/priv/www",#Fun<emq_dashboard.1.31422183>}]}]}}]
###### crash.dump analyzed by erl_crashdump_analyzer.sh
    analyzing /var/log/emqttd/crash.dump, generated on:  Tue Jul 4 11:45:29 2017 
    Slogan: eheap_alloc: Cannot allocate 762886488 bytes of memory (of type "old_heap").
    Memory:
    ===
      processes: 9123 Mb
      processes_used: 9122 Mb
      system: 534 Mb
      atom: 0 Mb
      atom_used: 0 Mb
      binary: 399 Mb
      code: 24 Mb
      ets: 20 Mb
    ---
    total: 9657 Mb
    Different message queue lengths (5 largest different):
    ===
          1 281442
          1 276601
          1 251671
          1 243350
          1 208328
    Error logger queue length:
    ===
    0
    File descriptors open:
    ===
      UDP:  0
      TCP:  8023
      Files:  7
      ---
      Total:  8030
    Number of processes:
    ===
    16270
    Processes Heap+Stack memory sizes (words) used in the VM (5 largest different):
    ===
          1 79467343
          2 66222786
          1 55185655
          1 45988046
          1 26613454
    Processes OldHeap memory sizes (words) used in the VM (5 largest different):
    ===
          3 95360811
          3 79467343
          1 66222786
          1 196650
          1 6772
    Process States when crashing (sum): 
    ===
          3 Current Process Garbing
          3 Current Process Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING | GC | TRAP_EXIT | ON_HEAP_MSGQ
          2 Garbing
          1 Internal ACT_PRIO_HIGH | USR_PRIO_HIGH | PRQ_PRIO_HIGH | ON_HEAP_MSGQ
          1 Internal ACT_PRIO_LOW | USR_PRIO_LOW | PRQ_PRIO_LOW | IN_PRQ_LOW | ACTIVE | IN_RUNQ | TRAP_EXIT | ON_HEAP_MSGQ
          2 Internal ACT_PRIO_LOW | USR_PRIO_LOW | PRQ_PRIO_LOW | TRAP_EXIT | ON_HEAP_MSGQ
          2 Internal ACT_PRIO_MAX | USR_PRIO_MAX | PRQ_PRIO_MAX | ON_HEAP_MSGQ
          2 Internal ACT_PRIO_MAX | USR_PRIO_MAX | PRQ_PRIO_MAX | TRAP_EXIT | ON_HEAP_MSGQ
          2 Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING | GC | TRAP_EXIT | ON_HEAP_MSGQ
       8006 Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | IN_PRQ_NORMAL | ACTIVE | IN_RUNQ | ON_HEAP_MSGQ
          9 Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | IN_PRQ_NORMAL | ACTIVE | IN_RUNQ | TRAP_EXIT | ON_HEAP_MSGQ
          1 Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | IN_PRQ_NORMAL | IN_RUNQ | TRAP_EXIT | ACTIVE_SYS | ON_HEAP_MSGQ
         94 Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ON_HEAP_MSGQ
       8150 Internal ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | TRAP_EXIT | ON_HEAP_MSGQ
       8017 Scheduled
       8251 Waiting

I don't think emqttd couldn't handle 8k cocurrent publishers with such resources(4-vcore/8GB), can anynoe know why the crash occured?

Thank you in advance.

**Comment by emqplus** [comment]
@sincethen The fanout is 8K(pub) * 8 (sub) = 64K/s for you use only one topic in this test case. Messages will be accumulated in the queue of subscribers, and finally memory overloaded. 

Benchmark report of EMQ 2.0: http://emq-xmeter-benchmark-en.readthedocs.io/en/latest/

**Comment by sincethen** [comment]
@emqplus Thanks for your reply so much. I'll publish 8k different topics and use 8k subsribers to subscribe each topic later.

**Comment by emqplus** [comment]
@sincethen The benchmark scripts for 8K/s PubSub: 

```
./emqtt_bench_sub -h <emqttd-ip> -c 8000 -t bench/%i -q 0

./emqtt_bench_pub -h <emqttd-ip> -c 8000 -t bench/%i -q 0
```

**Comment by sincethen** [comment]
@emqplus Then, how many messages could the emq be able to process per second for only one topic? It seems that it depends on memory and the amount of subscribers. I'd also like to have the quantization result. For example, for one topic, how many memories would be used by 1k messages per second and how many subsribers should subscribe them? Maybe, we should also consider the amount of publisher?

**Comment by emqplus** [comment]
@sincethen The benchmark report of EMQ 2.0: https://readthedocs.org/projects/emq-xmeter-benchmark-en/

**Comment by sincethen** [comment]
@emqplus Thank you. But I couldn't find the one topic scenario in the performance report above. Could you tell me how to calculate/transform the result from the report for the one topic scenario?
