### ISSUE TITLE
Dialyzer for emqttd application not working

### ISSUE THREAD

**Issue by SumitFlochat** [emqtt/emqttd#1131]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

Command:
dialyzer --build_plt --apps emqttd

Output:
dialyzer: No such file, directory or application: "emqttd"

where as it works fine for 
dialyzer --build_plt --apps mnesia

**Comment by huangdan** [comment]
hi @SumitFlochat, With the release of emqttd 2.2.0，you can run dialyzer with `make dialyze`
