### ISSUE TITLE
unsubscribe do not work,please check!

### ISSUE THREAD

**Issue by w3yyb** [emqtt/emqttd#114]
unsubscribe do not work,please check!
my unsubscribe topic is 'topic/#'
apollo broker can work with my php client
0.6.2

**Comment by erylee** [comment]
please paste your sub/unsub process.  I check it use emqttc client and could work well, test code below:

```
{ok, C} = emqttc:start_link([{client_id, <<"testClient">>}]).
emqttc:subscribe(C, <<"topic/#">>).
emqttc:publish(C, <<"topic/a">>, <<"haha">>).
emqttc:unsubscribe(C, <<"topic/#">>).
emqttc:publish(C, <<"topic/a">>, <<"haha">>).
```

**Comment by w3yyb** [comment]
my php client is process as the above, but still work well, if i unsubscribe a topic ,I still receive it later.
I tried mosquitto and apollo work well.

**Comment by erylee** [comment]
past your php code here

**Comment by erylee** [comment]
php mqtt client issue. emqttd broker did not receive any UNSUBSCRIBE packet.
