### ISSUE TITLE
Does the HTTP Publish API support CORS

### ISSUE THREAD

**Issue by naruto0916** [emqtt/emqttd#1154]
- OS: 
- Erlang/OTP: 
- EMQ: 2.2

Hi EMQ team
We are trying the EMQ server and we need to publish message by the http publish api.
We wan't to confirm that the http publish api support the CORS (Cross-Origin Resource Sharing) function or not.
Thank you.

**Comment by emqplus** [comment]
@naruto0916 The HTTP publish API does not support CORS. You can create a MQTT/Websocket  connection to publish messages on web browser.
