### ISSUE TITLE
mysql auth plugin sample

### ISSUE THREAD

**Issue by goldalworming** [emqtt/emqttd#116]
first of all, thank you @erylee to create great app.
you broker is the most stable I've tried so far.

can you please give some configuration sample using mysql auth plugin.
it's very useful if it can be implemented.

thank you

**Comment by erylee** [comment]
@goldalworming I am tagging 0.7.0 release with plugin samples. I will write a simple emqttd_auth_mysql plugin this weekend.

**Comment by goldalworming** [comment]
ok, I'm waiting for it. thanks a lot.

**Comment by erylee** [comment]
hi, @goldalworming, please checkout 'plugins' branch. I commit a demo emqttd_auth_mysql plugin.

If you want to authenticate with your own database and users table,  you could:

1. configure database parameters in 'etc/plugins.config'

```
 {emysql, [
    {pool_size, 4},
    {host, "localhost"},
    {port, 3306},
    {username, ""},
    {password, ""},
    {database, "mqtt"},
    {encoding, utf8}
 ]},
 {emqttd_auth_mysql, [
    {user_table, mqtt_users}
 ]}
```

2. modify plugins/emqttd_auth_mysql/src/emqttd_auth_mysql.erl to hash your password if not plaintext is stored.

**Comment by goldalworming** [comment]
ok, I'll try it. 

thank you

**Comment by goldalworming** [comment]
I got these problem while compiling

ERROR: generate failed while processing /home/lmvm/mqtt/emqttd-plugins/rel: {'EXIT',{{badmatch,{error,"goldrush: Application version clash. Multiple directories contain version \"0.1.6\"."}},
         [{rebar_reltool,generate,2,
                         [{file,"src/rebar_reltool.erl"},{line,53}]},
          {rebar_core,run_modules,4,[{file,"src/rebar_core.erl"},{line,490}]},
          {rebar_core,execute,6,[{file,"src/rebar_core.erl"},{line,415}]},
          {rebar_core,maybe_execute,8,
                      [{file,"src/rebar_core.erl"},{line,299}]},
          {rebar_core,process_dir1,7,[{file,"src/rebar_core.erl"},{line,258}]},
          {rebar_core,process_commands,2,
                      [{file,"src/rebar_core.erl"},{line,90}]},
          {rebar,main,1,[{file,"src/rebar.erl"},{line,58}]},
          {escript,run,2,[{file,"escript.erl"},{line,752}]}]}}
make: *** [rel] Error 1

I don't understand how to debug it

**Comment by goldalworming** [comment]
I read your https://github.com/emqtt/emqttd/wiki/FAQ
but I don't understand what to do if error appear

**Comment by goldalworming** [comment]
ok, I've successfully add plugin to your binary download

now, unauthenticated user could be blocked but I still cannot connect using python paho set password

client.username_pw_set("alice", "secret");
client.connect("localhost", 1884, 60)
client.loop_forever()

nb: I've already add username password in mysql

**Comment by erylee** [comment]
1. start emqttd console:

```
./bin/emqttd console
```

2. check mysql:

```
emysql:select(UserTab, {{username, Username}, {password, Password}}.
```

**Comment by goldalworming** [comment]
it return nothing 
(emqttd@127.0.0.1)1> emysql:select('mqtt_user', {{username, 'alice'}, {password, 'secret'}} 
(emqttd@127.0.0.1)1> emysql:select('mqtt_user', {{username, 'alice'}, {password, 'secret'}}.
* 2: syntax error before: '.'
(emqttd@127.0.0.1)1> emysql:select('mqtt_user', {{username, 'alice'}, {password, 'secret'}} 
(emqttd@127.0.0.1)1>

**Comment by erylee** [comment]
```
emysql:select('mqtt_user', {{username, 'alice'}, {password, 'secret'}}.
```

**Comment by erylee** [comment]
must be ended with "."

**Comment by goldalworming** [comment]
got this * 1: syntax error before: '.'

**Comment by goldalworming** [comment]
(emqttd@127.0.0.1)1> emysql:select('mqtt_user', {{username, 'alice'}, {password, 'secret'}}).
** exception error: undefined function emysql:select/2

**Comment by erylee** [comment]
@goldalworming, I fixed the mysql query issue that 'where' condition of select is wrong:

```
emysql:select(UserTab, {'and', {username, Username}, {password, Password}}).
```

Please checkout 'plugins' branch and build to test.

**Comment by goldalworming** [comment]
I'm not successfully build the plugin due to goldrush error

add mysql auth plugin to compiled (0.7.1) version just make any connection successfully connected with/without password

**Comment by erylee** [comment]
git clone -b plugins https://github.com/emqtt/emqttd.git && make && make dist

**Comment by goldalworming** [comment]
I always got this error
==> emqttd (compile)
==> rel (generate)
ERROR: generate failed while processing /home/lmvm/mqtt/emqttd/rel: {'EXIT',{{badmatch,{error,"goldrush: Application version clash. Multiple directories contain version \"0.1.6\"."}},
         [{rebar_reltool,generate,2,
                         [{file,"src/rebar_reltool.erl"},{line,53}]},
          {rebar_core,run_modules,4,[{file,"src/rebar_core.erl"},{line,490}]},
          {rebar_core,execute,6,[{file,"src/rebar_core.erl"},{line,415}]},
          {rebar_core,maybe_execute,8,
                      [{file,"src/rebar_core.erl"},{line,299}]},
          {rebar_core,process_dir1,7,[{file,"src/rebar_core.erl"},{line,258}]},
          {rebar_core,process_commands,2,
                      [{file,"src/rebar_core.erl"},{line,90}]},
          {rebar,main,1,[{file,"src/rebar.erl"},{line,58}]},
          {escript,run,2,[{file,"escript.erl"},{line,752}]}]}}
make: *** [rel] Error 1

**Comment by erylee** [comment]
find . -name goldrush


> 在 2015年5月6日，下午4:33，arief nur andono <notifications@github.com> 写道：
> 
> goldrush

**Comment by goldalworming** [comment]
lmvm@lm17 ~/mqtt/emqttd $ find . -name goldrush
./deps/goldrush

**Comment by goldalworming** [comment]
then what to do to remove goldrush error?
