### ISSUE TITLE
Goldrush error installing on rhel 7

### ISSUE THREAD

**Issue by rauger** [emqtt/emqttd#1165]
#### Environment

- OS: rhel 7
- Erlang/OTP: 19.2 
- EMQ: emq-rlx

#### Description

I have create a rhel 7 instance on AWS and am in the process of moving some of my broker to the cloud and bridging them. Unfortunately, I cannot 'make' emq-rlx on this server.

Verification of Erlang version:\
erl
   Erlang/OTP 19 [erts-8.2] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

which erl
/bin/erl

Here is the error:
```
[emq-relx]# make
 DEP    goldrush
{"init terminating in do_boot",{undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,670}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,228}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,229}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,878}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,422}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,122}]},{init,start_it,1,[]}]}}
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done
 DEP    emqttd
 DEP    emq_modules
 DEP    emq_dashboard
 DEP    emq_retainer
 DEP    emq_recon
 DEP    emq_reloader
 DEP    emq_auth_clientid
 DEP    emq_auth_username
 DEP    emq_auth_ldap
 DEP    emq_auth_http
 DEP    emq_auth_mysql
 DEP    emq_auth_pgsql
 DEP    emq_auth_redis
 DEP    emq_auth_mongo
 DEP    emq_sn
 DEP    emq_coap
 DEP    emq_stomp
 DEP    emq_plugin_template
 DEP    emq_web_hook
 DEP    emq_lua_hook
 DEP    emq_elixir_plugin
 DEP    emq_auth_jwt
 DEP    emq_lwm2m
make[1]: Entering directory `/home/ec2-user/repos/emq-relx/deps/goldrush'
make[1]: *** No targets.  Stop.
make[1]: Leaving directory `/home/ec2-user/repos/emq-relx/deps/goldrush'
make: *** [deps] Error 2

```

Thank you for your help!

**Comment by turtleDeng** [comment]
@rauger Please check your erlang operating environment

**Comment by rauger** [comment]
@turtleDeng You're right. 

Just in case anyone has this problem: Issue was that I has OTP 20 installed on accident, I needed less than 20. But when I uninstalled OTP 20 and installed 19.2, the uninstallation was not complete. I needed to empty /usr/local/lib of all of the library files, clear erl from my path, and reinstall emq-relx.

**Comment by toy-lin** [comment]
I have encountered with the same problem.I have tried OPT21.1 and OPT21 version of erlang and i got the same error.
Could you please tell me how to check my erlang operating environment?
@turtleDeng 
@rauger

**Comment by Gilbert-Wong** [comment]
Refer this link: https://www.erlang-solutions.com/resources/download.html. You can just use erlang-solution to install the latest erlang/otp on centos 7 or rhel 7. You know that they are almost same, right?
