### ISSUE TITLE
How many messages per seconds a node Server acting as a client can handle

### ISSUE THREAD

**Issue by arihantdaga** [emqtt/emqttd#1167]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*I am working on a home automation device. Where lot of devices(approx 1000-5000 per second ) will be publishing messages every second about the sensor reports. I want to store the sensor attributes them in the database as well as do some other processing based on the value sent by the device. I am using a NodeJs Server for my other apis. If i want to use this Node Server or a seperate instance of Node Server as a client who is subscribed to all the sensors's topic, how many messages will it be able to handle every second ? can it handle 1000-2000 messages every second ? if i have good amount of ram and cpus. ? . Or is there any better solution for logging sensor data into Database(mongoDB)*

**Comment by turtleDeng** [comment]
@arihantdaga we have released an enterprise edition of EMQ to support persistence in mongodb backends. I plan to upgrade the emqtt.io site and publish the edition later:)

**Comment by pineli** [comment]
how can I get information about EMQ Enterprise. I already sent you an email? # @ @emqplus

**Comment by emqplus** [comment]
@pineli Please contact zhengyu.pan@emqtt.io who is responsible for EMQ global marketing.
