### ISSUE TITLE
Complete Server Crash

### ISSUE THREAD

**Issue by syberkitten** [emqtt/emqttd#1169]
Running the latest release broker for 24 hours,
with various clients connecting, I suddenly got reports the server is down.

seeing this in erlang.log.1:
```
09:01:15.424 [info]  [alarm_handler: {:set, {:process_memory_high_watermark, #PID<0.3929.0>}}]
eheap_alloc: Cannot allocate 9794840320 bytes of memory (of type "old_heap").

Crash dump is being written to: crash.dump...done
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed^M
```

**Comment by emqplus** [comment]
@syberkitten Do you create one subscriber to consume messages from many publishers?

**Comment by grutabow** [comment]
What is your test scenario? How many publishers? How many subscribers? How many topics?

**Comment by syberkitten** [comment]
@grutabow 
Not many clients connected, around 10.
each clients was creating between 500-3000 topics.

**Comment by grutabow** [comment]
@syberkitten  What about qos? QOS2? QOS0?

**Comment by syberkitten** [comment]
@grutabow 
QOS0.
We will run the test again on a stable version 2.2.0
and see how it goes....
