### ISSUE TITLE
Subscription qos=2, but received message with qos=1

### ISSUE THREAD

**Issue by Loxchen** [emqtt/emqttd#1172]
#### Environment

- OS: centos 6.8
- Erlang/OTP: R19/8.3
- EMQ: 2.2

#### Description

*Found out that our clients subscribed topic 'test' in qos =2, but the received messages were qos = 1,
Then we tried to change our publishers' qos from 1 to 2, the clients got the messages in qos = 2 !!!
The subscribers' qos setting is not working, it's depend on the publishers' qos now !!!*

below:
1. client subscribe topic 'test' with qos = 2
2. publisher published message to topic with qos = 1
3. publisher published message to topic with qos = 2
> 

16:28:09.030 [info] Client(loxchen@10.0.27.8:64086): RECV UNSUBSCRIBE(Q1, R0, D0, PacketId=54172, Topics=[<<"test">>])
16:28:09.030 [info] Session(loxchen): Unsubscribe [{<<"test">>,[]}]
16:28:09.030 [info] Client(loxchen@10.0.27.8:64086): SEND UNSUBACK(Q0, R0, D0, PacketId=54172)
16:28:11.071 [info] Client(loxchen@10.0.27.8:64086): RECV SUBSCRIBE(Q1, R0, D0, PacketId=54173, TopicTable=[{<<"test">>,2}])
16:28:11.071 [info] Session(loxchen): Subscribe [{<<"test">>,[{qos,2}]}]
16:28:11.071 [info] Client(loxchen@10.0.27.8:64086): SEND SUBACK(Q0, R0, D0, PacketId=54173, QosTable=[2])
16:28:21.072 [info] Client(loxchen@10.0.27.8:64086): RECV PINGREQ(Q0, R0, D0)
16:28:21.072 [info] Client(loxchen@10.0.27.8:64086): SEND PINGRESP(Q0, R0, D0)
16:28:24.552 [info] Client(loxchen@10.0.27.8:64086): SEND PUBLISH(Q1, R0, D0, Topic=test, PacketId=14, Payload=<<"ccc">>)
16:28:24.553 [info] Client(loxchen@10.0.27.8:64086): RECV PUBACK(Q0, R0, D0, PacketId=14)
16:28:31.627 [info] Client(loxchen@10.0.27.8:64086): SEND PUBLISH(Q2, R0, D0, Topic=test, PacketId=15, Payload=<<"ccc">>)
16:28:31.628 [info] Client(loxchen@10.0.27.8:64086): RECV PUBREC(Q0, R0, D0, PacketId=15)
16:28:31.628 [info] Client(loxchen@10.0.27.8:64086): SEND PUBREL(Q1, R0, D0, PacketId=15)
16:28:31.629 [info] Client(loxchen@10.0.27.8:64086): RECV PUBCOMP(Q0, R0, D0, PacketId=15)

**Comment by grutabow** [comment]
MQTT spec v3.1.1 addressed that:

> The Server might grant a lower maximum QoS than the subscriber requested. The QoS of Payload Messages sent in response to a Subscription MUST be the minimum of the QoS of the originally published message and the maximum QoS granted by the Server.

So the qos behaviour is as expected.

**Comment by Loxchen** [comment]
I found out that below in emq.conf can solve my problem
## Upgrade QoS?
mqtt.session.upgrade_qos = on
