### ISSUE TITLE
emqttd - "proxy" for protocols or not?

### ISSUE THREAD

**Issue by UserXYZ** [emqtt/emqttd#1178]
#### Environment

- OS: Linux
- Erlang/OTP: latest
- EMQ: latest

#### Can emqttd work as a protocol "translator"?

I am maybe dumb to ask such a question here, but I don't seem to find an explicit YES or NO in the docs - does emqttd work as a proxy/translator between CoAP and MQTT?

In other words, if I have a client publishing data on a specific topic using CoAP on one side, and a client listening to the same topic but using MQTT, will they be able to communicate? Or, will the MQTT client receive the message from CoAP client, and vice versa?

Does emqttd work in that respect like Eclipse Ponte which does "translate" messages from any protocol to any protocol it supports or does emqttd allow only the same type of clients to communicate - CoAP to CoAP, and MQTT to MQTT?

I tried to test this, and while I can use mosquitto_pub/sub and coap-client to send/receive messages of the same type, mixing them using the same topic just does not work...

Am I wrong about the whole idea or am I just doing something wrong?

**Comment by emqplus** [comment]
@UserXYZ 

1. Yes. The CoAP and MQTT clients can communicate with each other. For example,
    CoAP <- EMQ -> MQTT

2. Works like Eclipse Ponte. 

3. The documentation on how to publish a MQTT message: https://github.com/emqtt/emq-coap#publish

4. If any issues, contact @grutabow

**Comment by UserXYZ** [comment]
I did see that exact page and I tried to replicate that, but no success...
Here's what I was trying:
- in one console: mosquitto_sub -h localhost -t "/#"
- in another console: coap-client -m put -e "message" "coap://localhost/mqtt/test?c=localhost"
and nothing happens - coap-client spits out two lines of something and nothing is shown in the other console.

Tried the other way around as well:
- in one console: coap-client -m get -s 10 "coap://localhost/mqtt/test?c=client1"
- in another console: mosquitto_pub -t "/test" -h localhost -m "test msg"
Nothing is received on the other side...

mqtt to mqtt works, as does coap to coap - but not mixing it.
I tried with normal IP address instead of localhost, I tried with different parameters...nothing. I do not have auth enabled nor any other special/tricky feature, so it confuses me...

What am I doing wrong?

**Comment by emqplus** [comment]
@grutabow Please check the issue.

**Comment by grutabow** [comment]
@UserXYZ   

The first case
Please replace "/#" with "+" or "#" or "test", since the published topic is "test".

The second case
Please replace "/test" with "test" in mosquitto_pub command.

**Comment by UserXYZ** [comment]
Why, thank you, that did the trick...I just wonder how it didn't work with me using '/#' since I always had to use '/something' to make mqtt work properly, so all my topics on already working devices are in '/a/b/c' form...
Tested also that version, I had to put /mqtt/%2ftest?c=client1 in order to encode the topic as '/test' and it also worked.

Thanks again.

BTW is emqt_coap going to implement POST and DELETE methods? I must say I did have a lot of unsuccessful tests using POST instead of PUT before I found out that coap plugin only supports PUT and GET...

**Comment by grutabow** [comment]
The "mqtt" resource for coap is a "bridge" between coap and mqtt, which make coap and mqtt talk to each other. Since GET and PUT are enough for SUB and PUB action, POST and DELETE is useless in mqtt scenario.

If you want to implement a pure coap feature, please write a resource handler for your customed path(for example coap://localhost/my_coap) which is able to process GET/PUT/POST/DELETE as will. Such a development procedure has not been documented yet.
