### ISSUE TITLE
Will the topic name's length and layer impact the EMQ node's memory usage??

### ISSUE THREAD

**Issue by naruto0916** [emqtt/emqttd#1182]
Hello EMQ team:

As I know, the max topic count depend on EMQ node's memory, right??
And I want to confirm with you:
1. the length of topic name will consume more memory??
2. the more layer of topic will consume more memory and impact publish message performance??

Thank you!!

**Comment by grutabow** [comment]
Sure, longer topic name consumes more memory. And more topic layers consumes more CPU resources.

**Comment by naruto0916** [comment]
Thank you for your reply.
