### ISSUE TITLE
Restricting topic pub/sub access to users

### ISSUE THREAD

**Issue by codewiget95** [emqtt/emqttd#1184]
#### Environment

- OS: Ubuntu 16
- Erlang/OTP: 19.2
- EMQ: 2.2

#### Description

How would I restrict users to only be able to publish to a specific topic BASED on their client ID or username? This question here : https://github.com/emqtt/emqttd/issues/554 is asking about how to do it with MySQL. I am using simple redis auth, so I would just like to use the standard acl file if possible, or else please let me know how to go about this!

For example, 

{allow, {user, $user}, pubsub, ["device/$user"]}, so every user can publish and subscribe to their own topic but not to any other topics.

Thank you for all the work you do.

**Comment by PiedPieper** [comment]
@codewiget, this was just answered for me coincidentally. You need to use some sort of authentication plugin, acl.conf does not support this. You're using redis auth, so you just need to configure redis and using HGET. Check out the readme for emq_auth

**Comment by codewiget95** [comment]
Thanks, that worked!
