### ISSUE TITLE
broker stops, no trace of errors

### ISSUE THREAD

**Issue by syberkitten** [emqtt/emqttd#1186]
#### Environment

- OS: 
Ubuntu 14.04 trusty
- Erlang/OTP: 
19
- EMQ: 
2.2 stable release

#### Description

```
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
```

*A description of the issue*

Happens after broker runs for a day or less,
no crash log simply broker stops.

Is there way to add timestamp to erlang.log as well (to each line below?)

```
starting emqttd on node 'emqttd@127.0.0.1'
emqttd ctl is starting...[ok]
emqttd hook is starting...[ok]
emqttd router is starting...[ok]
```

I will need to increase the number of rotated logs to 
find if there was any error in console.log.

We are trying to create many topics (1-10k) for every client.
from observation server does not clear memory properly for these topics
trying to allocated more and more memory until is closed or crashes.

We are using clean session true, and QoS 0 mostly at this stage. 
Yet still eventually server crashes every day.

**Comment by syberkitten** [comment]
Is it possible to increase the number of rotated logs?

**Comment by emqplus** [comment]
@syberkitten  Crash is usually caused by a slow subscriber which accumulates messages in memory. There will be a crash.dump file generated under the `logs` folder if the Erlang VM crashed.
