### ISSUE TITLE
eMQTT Security

### ISSUE THREAD

**Issue by sivalai** [emqtt/emqttd#1188]
#### Environment

- OS: Ubuntu

#### Description

We are exploring eMqtt to integrate with our platform., we have few queries specific on Security. 
 
We are looking for,
 
Transport level security
Authentication 
 
Transport level security - 
 
We will be running eMqtt broker in Cloud and within our Embedded Linux device.
 
·         When user connect to Cloud Server data should travel on https and if the user is with in LAN it could be on http – will regular SSL method work?
·         When Message Broker listen on a specific port how to ensure the source reliability? - that is to ensure accept requests only from known clients
 
Is there any reference guide or implementation available?
 
Authentication -
 
We want to authenticate the user with Cassandra database - do you have plugin for that? 
 
Is there any other best practice which we should follow?

**Comment by dreamcatcha** [comment]
Look into the http auth plugin, you can then use any auth method and language to roll your own system for auth and acl

**Comment by emqplus** [comment]
@sivalai All the features you mentioned have been prod ready before EMQ R2.2 release. 
The documentation: http://emqtt.io/docs/v2/
