### ISSUE TITLE
Failed to start emqttd in debian testing(buster, 10)

### ISSUE THREAD

**Issue by srdgame** [emqtt/emqttd#1189]
#### Environment

- OS: Debian Testing(buster)
- Erlang/OTP: R20/9.0
- EMQ: v2.3-beta.1

#### Description
Installed emq with downloaded deb file:
emqttd-debian9-v2.3-beta.1_amd64.deb

installed lksctp-tools with apt-get

> sudo service emqttd status
● emqttd.service - LSB: Erlang MQTT Broker
   Loaded: loaded (/etc/init.d/emqttd; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-08-07 15:57:42 CST; 9min ago
     Docs: man:systemd-sysv-generator(8)
      CPU: 662ms

> 8月 07 15:57:24 dirk-laptop systemd[1]: Starting LSB: Erlang MQTT Broker...
8月 07 15:57:25 dirk-laptop su[26171]: Successful su for emqtt by root
8月 07 15:57:25 dirk-laptop su[26171]: + ??? root:emqtt
8月 07 15:57:25 dirk-laptop su[26171]: pam_unix(su:session): session opened for user emqtt by (uid=0)
8月 07 15:57:42 dirk-laptop systemd[1]: emqttd.service: Control process exited, code=exited status=1
8月 07 15:57:42 dirk-laptop systemd[1]: Failed to start LSB: Erlang MQTT Broker.
8月 07 15:57:42 dirk-laptop systemd[1]: emqttd.service: Unit entered failed state.
8月 07 15:57:42 dirk-laptop systemd[1]: emqttd.service: Failed with result 'exit-code'.
8月 07 15:59:47 dirk-laptop epmd[5735]: epmd: got KILL_REQ - terminates normal

There is no useful log content in /var/log

**Comment by srdgame** [comment]
Buster has same lksctp-tools version as  stretch

**Comment by turtleDeng** [comment]
@srdgame 
```
sudo emqttd start
```
 successfully?

**Comment by srdgame** [comment]
> netstat -an | grep 883
tcp        0      0 0.0.0.0:11883           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8883            0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:12883         0.0.0.0:*               LISTEN     
unix  3      [ ]         STREAM     CONNECTED     2883     
unix  3      [ ]         STREAM     CONNECTED     12883001 
unix  3      [ ]         STREAM     CONNECTED     12883002 
cch@dirk-laptop:~/下载$ sudo service emqttd status
● emqttd.service - LSB: Erlang MQTT Broker
   Loaded: loaded (/etc/init.d/emqttd; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-08-07 15:57:42 CST; 18h ago
     Docs: man:systemd-sysv-generator(8)
      CPU: 662ms

> 8月 07 15:57:24 dirk-laptop systemd[1]: Starting LSB: Erlang MQTT Broker...
8月 07 15:57:25 dirk-laptop su[26171]: Successful su for emqtt by root
8月 07 15:57:25 dirk-laptop su[26171]: + ??? root:emqtt
8月 07 15:57:25 dirk-laptop su[26171]: pam_unix(su:session): session opened for user emqtt by (uid=0)
8月 07 15:57:42 dirk-laptop systemd[1]: emqttd.service: Control process exited, code=exited status=1
8月 07 15:57:42 dirk-laptop systemd[1]: Failed to start LSB: Erlang MQTT Broker.
8月 07 15:57:42 dirk-laptop systemd[1]: emqttd.service: Unit entered failed state.
8月 07 15:57:42 dirk-laptop systemd[1]: emqttd.service: Failed with result 'exit-code'.
8月 07 15:59:47 dirk-laptop epmd[5735]: epmd: got KILL_REQ - terminates normal

**Comment by srdgame** [comment]
@turtleDeng 
sudo emqttd start is ok for my laptop.  I have opened the dashboard in browser.

**Comment by fleimgruber** [comment]
@srdgame this #1228?

**Comment by turtleDeng** [comment]
@fleimgruber Yes, The problem we will fix in v2.3-beta.4

**Comment by srdgame** [comment]
:-) Great!

**Comment by fleimgruber** [comment]
@srdgame Since this seems to be the same issue as #1228, please do as @emqplus said in https://github.com/emqtt/emqttd/issues/1228#issuecomment-329028740.
