### ISSUE TITLE
emqtt authentication per topic or subscription

### ISSUE THREAD

**Issue by Rotem19** [emqtt/emqttd#1190]
Hi,
Is there a way to create authentication per subscription or topic?
For example: I have one broker and I want few of the topics that are published to it to be available for everybody and few topics I want to be available just with username/password?
is it possible to do and how?

**Comment by PiedPieper** [comment]
Check out emq_redis_auth plugin. You can set up a simple username/password auth and allow users to connect to certain topics, and in your acl.config specify what topics you want everyone to have access to.
