### ISSUE TITLE
Querying the broker for online (connected) clients in realtime

### ISSUE THREAD

**Issue by syberkitten** [emqtt/emqttd#1192]
Hi

**Is there a way to query the broker for a specific clientID,
whether it is online or not (connected or not)?**

The use case is that we need to send a push notification to wake our clients if they 
are disconnected, which means we need a way to ask the broker
if the client is connected or not (across the cluster if possible, or just a single broker instance)

Thanks a lot

**Comment by emqplus** [comment]
@syberkitten We will release more management APIs including clientId lookup in 2.3-beta.2 :)

**Comment by turtleDeng** [comment]
@syberkitten http://emqtt.io/docs/v2/rest.html#clients

**Comment by emqplus** [comment]
@syberkitten More HTTP Management APIs have been added in 2.3-beta.2 release.
