### ISSUE TITLE
SSL handshake failure 

### ISSUE THREAD

**Issue by nikoladsp** [emqtt/emqttd#1194]
#### Environment

- OS: Ubuntu 16.04.2 LTS
- Erlang/OTP: 19.3 (compiled from source)
- EMQ: 2.2.0 (compiled from source)

#### Description

Hi, for past few days I am struggling to make SSL works with EMQTT. I have certificates generated by LetsEncrypt and tested them with Mosquitto - which worked flawlessly. I confirmed also with:

<pre>
sudo openssl s_client -showcerts -connect notebook.snailit.org:8883
</pre>

However, when run EMQTT, I got following error in broker log:

<pre>
2017-08-09 12:32:17.457 [error] <0.1362.0> SSL: certify: ssl_connection.erl:484:Fatal error: handshake failure
</pre>

openssl client output is:
<pre>
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = notebook.snailit.org
verify return:1
139665569322648:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:s3_pkt.c:1487:SSL alert number 40
139665569322648:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
---
Certificate chain
 0 s:/CN=notebook.snailit.org
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
-----BEGIN CERTIFICATE-----
.......

.......
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=notebook.snailit.org
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
---
Acceptable client certificate CA names
/CN=notebook.snailit.org
/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
Client Certificate Types: ECDSA sign, RSA sign, DSA sign
Requested Signature Algorithms: ECDSA+SHA512:RSA+SHA512:ECDSA+SHA384:RSA+SHA384:ECDSA+SHA256:RSA+SHA256:ECDSA+SHA224:RSA+SHA224:ECDSA+SHA1:RSA+SHA1:DSA+SHA1
Shared Requested Signature Algorithms: ECDSA+SHA512:RSA+SHA512:ECDSA+SHA384:RSA+SHA384:ECDSA+SHA256:RSA+SHA256:ECDSA+SHA224:RSA+SHA224:ECDSA+SHA1:RSA+SHA1:DSA+SHA1
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 3085 bytes and written 138 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: F2FD489B4994A30E9B67E4829DD17A773FD25EBB54C33978DA2B6E11DA0AC7A1
    Session-ID-ctx: 
    Master-Key: 99B5DB18CCFB57F4BFC03A61EF02BFDB97CFFB0C4D3B6C340A66599A3C9314D6F1DABBD231147211D3C715E4D2FE84DD
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1502274737
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
</pre>

Here is is the part of the emqtt configuration:

<pre>
listener.ssl.external.keyfile = /etc/letsencrypt/live/notebook.snailit.org/privkey.pem
listener.ssl.external.certfile = /etc/letsencrypt/live/notebook.snailit.org/cert.pem
listener.ssl.external.cacertfile = /etc/letsencrypt/live/notebook.snailit.org/fullchain.pem
listener.ssl.external.dhfile = etc/certs/dh-params.pem
listener.ssl.external.verify = verify_peer
listener.ssl.external.fail_if_no_peer_cert = true
</pre>

For HTTPS web socket is the same (but without dhfile option).

Can somebody please help? Thank you in advance

**Comment by emqplus** [comment]
@nikoladsp Comment the `verify_peer` option if you use one-way SSL authentication:

```
## listener.ssl.external.verify = verify_peer
## listener.ssl.external.fail_if_no_peer_cert = true
```

**Comment by nikoladsp** [comment]
Thank you kindly - it helped

**Comment by xerosanyam** [comment]
@nikoladsp Can you please mention how did you generate the certificate ?
this way 
`sudo certbot certonly --webroot -w /var/www/example -d example.com -d www.example.com -w /var/www/thing -d thing.is -d m.thing.is`
or 
this way
`sudo certbot certonly --webroot -w /var/www/example -d example.com -d www.example.com`

I am having trouble generating the certificate and configuring it.

**Comment by nikoladsp** [comment]
Hi,
I think it was something like this: `sudo letsencrypt certonly --webroot -w /var/www/html -d www.snailit.org -d sb.snailit.org`
