### ISSUE TITLE
All traffic in FW to start service issue

### ISSUE THREAD

**Issue by GibliX** [emqtt/emqttd#1196]
I started an instance of emqttd on an AWS server.
I opened the following ports:
4369 - 0.0.0.0/0
1883 - 0.0.0.0/0
44369 - 0.0.0.0/0

When I start the emqttd (sudo service emqttd start) it hangs.
Only when I open:
ALL traffic - 0.0.0.0/0
The service starts successfully.

Why is that?
After opening All traffic it works fine and I can cluster and everything works.
If I don't open All traffic it doesn't start the service at all.

I'm using "emqttd-ubuntu14.04-v2.2.0_amd64.deb"

**Comment by emqplus** [comment]
@GibliX Clustering on AWS: https://github.com/emqtt/emqttd/issues/496
