### ISSUE TITLE
When deleting retained message subscribed clients not notified

### ISSUE THREAD

**Issue by sobelman** [emqtt/emqttd#1207]
#### Environment

- OS: Ubuntu
- Erlang/OTP: latest
- EMQ: latest 

#### Description

I have a question regarding the behavior of EMQ compared to Mosquitto broker,

In mosquitto,
When deleting retained messages(empty payload, retained message) all subscribed clients received the new empty retained message and can tell a message was deleted.

Now after moving to EMQ, i can see that in case clients subscribe to a topic, and other client will publish delete command (empty retained message) the subscribe clients won't get it, and the only way to figure it out is to re-subscribe to this topic.

Is it possible to change this behavior?
thanks
assaf

**Comment by sobelman** [comment]
I can confirm the following things as well:
1. HiveMQ public server behave the same as mosquitto  (subscribed clients get empty payload retained messages) 
2. In EMQ server, Sending empty messages to a topic is working and the client can see it,
But:
Once message is sent as retained + empty payload the subscribe clients won't get any notification on this message 

Commands to tests:

Client 1 subscribe:
mosquitto_sub -h 127.0.0.1 -t 'test/1' -d

Client 2 publish:
mosquitto_pub -h 127.0.0.1 -t 'test/1' -n  <--Client 1 can see this message  **<-- OK.** 
mosquitto_pub -h 127.0.0.1 -t 'test/1' -n **-r**  <--Client 1 can **not** see this message **<-- NOT OK.**

**Comment by sobelman** [comment]
Thank you @turtleDeng , waiting for 2.3-beta.3 milestone to be released.
Appreciate your quick response and for handling this issue.

**Comment by turtleDeng** [comment]
@sobelman The issue has been fixed in 2.3-beta.3

**Comment by sobelman** [comment]
Hi,
Tested -> working as expected. 
Closing this issue. 
Thank you.
