### ISSUE TITLE
How to get rid of automatic subscription of $client/{clientID} after connection?

### ISSUE THREAD

**Issue by tremoteye** [emqtt/emqttd#1209]
#### Environment

- OS: CentOS7
- Erlang/OTP: 
- EMQ: 2.3

#### Description

After each client connects, web-hook logs shows that the client automatically subscribe a topic - '$client/{clientID}' as below.

`Body: {"action":"client_connected","client_id":"aaabbbcccc","conn_ack":0}
Body: {"action":"client_subscribe","client_id":"aaabbbcccc","username":"111","topic":"$client/aaabbbcccc","opts":{"qos":1}}
`
Could you guide me how to remove the automatic subscription behavior unless it is mandatory feature for any system monitoring reasons?

Thanks.

**Comment by turtleDeng** [comment]
@tremoteye 

https://github.com/emqtt/emq-modules#subscription-module
```
## Enable Subscription, Values: on | off
module.subscription = on

## Subscribe the Topics automatically when client connected
## module.subscription.1.topic = $client/%c
## Qos of the subscription: 0 | 1 | 2
module.subscription.1.qos = 1

## module.subscription.2.topic = $user/%u
## module.subscription.2.qos = 1
```

**Comment by tremoteye** [comment]
thanks a lot
