### ISSUE TITLE
emqttd cluster issuse

### ISSUE THREAD

**Issue by w3yyb** [emqtt/emqttd#121]
一、0.7.0版
在哪台机器上执行这个cluster命令  ./bin/emqttd_ctl  cluster emqttd@host1后
哪个机器就不能连接了。

 二、0.6.1版（最新版没有测试）我用lvs-dr模式， 192.168.6.41路由2机器192.168.6.156,192.168.6.157,当在某一台机器上执行emqttd stop 后，客户端就再也收不到消息了,重新emqttd start后也收不到。
客户端 连接的是 192.168.6.41.

**Comment by w3yyb** [comment]
0.7.1 发现一个问题 ，在哪台机器上执行 cluster命令后，再在此机器上 emqttd stop就收不到消息了  
Lenix 13:45:12 
如果在A机器上，执行cluster命令，再在B机器上执行

**Comment by erylee** [comment]
LVS集群下，一台服务器down，连接到该服务器的客户端，必需重新连接到其他服务器。

emqttd应用层面集群无问题，客户端应该支持自动重连机制。
