### ISSUE TITLE
some questions about the EMP auth plugins

### ISSUE THREAD

**Issue by naruto0916** [emqtt/emqttd#1210]
#### Environment

- OS: CentOS 7
- Erlang/OTP: 
- EMQ: 2.2

#### Description

Hello EMQ team:

We are trying the EMQ server and have some questions about the auth part:

1. We saw the EMQ support emq_auth_clientid and emq_auth_username. Can we use both two plugins at the same time?? If yes, the client need to have the correct clientid, username and password at the same time while connecting to EMQ server?? Or we can just select one of them as our auth rule??

2. Can the emq_auth_mongo plugin also support to store and verify clientid by mongodb if we use emq_auth_clientid??

3.  If we use emq_auth_mongo plugin to manager our auth and acl data, we don't need to restart EMQ server once the auth/acl data be updated, right??

Please kindly give use some suggestion about above questions, thank you.

**Comment by turtleDeng** [comment]
@naruto0916 
http://emqtt.io/docs/v2/guide.html#

**Comment by naruto0916** [comment]
@turtleDeng 
Thank you for your reply.
From the guide, it seems EMQ will check username auth first if we enable username and clientid auth at the same time.
But, from the chart of the guide.
We are confused about if username is allowed and EMQ will accept the connection or continue to check the clientid is allow or not??
And from the guide about emq_auth_mongo part, it seems we can just set username auth by mongodb.
If we want to enable username and clientid auth by mongodb, how we set the emq_auth_mongo.conf ??

**Comment by turtleDeng** [comment]
@naruto0916 
eg: enabled emq_auth_username, emq_auth_clientid, emq_auth_mongo.
if emq_auth_username is allowed,EMQ will accept the connection,if emq_auth_username not find, next check emq_auth_clientid, if emq_auth_clientid not find,  check emq_auth_mongo, and so on.

**Comment by naruto0916** [comment]
@turtleDeng 
OK!! Thank you for your explanation.
I think we misunderstood the usage about the auth plugins.
Your answer had clarified our confusion.

**Comment by turtleDeng** [comment]
Suggested use: 
emq_auth_mysql
emq_auth_pgsql
emq_auth_http

**Comment by naruto0916** [comment]
@turtleDeng 
Thank you for your suggestion.
