### ISSUE TITLE
Duplicate Topics - Possible Bug or Intended?

### ISSUE THREAD

**Issue by PiedPieper** [emqtt/emqttd#1218]
#### Environment

- OS: 
- Erlang/OTP: 19.2
- EMQ: 2.2

#### Description

Hello, 

Whenever a client subscribes, two topics are created instead of one. For example, with only one subscriber, my dashboard shows:

Topic | SubTopicCount
-- | --
dev/0234567890123456                   | 1
$client/mosqsub/46831-Mac | 1

The top one is the topic I am subscribing to, and the bottom one looks like it is $client with the Client ID appended to it. I verify that there is only one subscription because when I close the subscribe, both topics disappear from the dashboard. 

There are a few other things to note:

1. What I noticed is that when I subscribe, the on_client_subscribe hook and on_session_subscribe will be run twice.

2. the access control mod is only run one time.

3. There is still only 1 client and 1 session in the dashboard

I believe this is probably not a bug, maybe it is just a way to send the client unique commands, I would just like to let you know if it is important.

**Comment by PiedPieper** [comment]
These are special system topics for statistics.

**Comment by emqplus** [comment]
Tune off the auto subscription module in etc/plugins/emq_modules.conf:

```
module.subscription = off
```

**Comment by emqplus** [comment]
@PiedPieper  Turn off the `module.subscription` by default in 2.3.1 release.
