### ISSUE TITLE
labeling message with unique id

### ISSUE THREAD

**Issue by goldalworming** [emqtt/emqttd#122]
hi, I tried to identified unique message and this is my log
{'qos': 0, 'timestamp': 1430723700.092239, 'mid': 0, 'topic': 'users/alice', 'state': 0, 'dup': 0, 'retain': 0, 'payload': 'Hello, World!'}
{'qos': 0, 'timestamp': 1430723700.336642, 'mid': 0, 'topic': 'users/alice', 'state': 0, 'dup': 0, 'retain': 0, 'payload': 'Hello, World!'}

does mid will increase in exact timestamp so I can use timestamp+mid as unique id?

**Comment by erylee** [comment]
@goldalworming, timestamp+mid cannot work if there are too many concurrent messages, I think.

There are two issues:

1. Qos0 message has no mid
2. Qos1/2 message has a increase mid that is only unique in same session

**Comment by goldalworming** [comment]
I have 3 python worker that subscribe one topic. how to make sure the message has been process ti job queue without duplicate?

**Comment by erylee** [comment]
duplicated with #185.
