### ISSUE TITLE
not work https Dashboard

### ISSUE THREAD

**Issue by edgiru** [emqtt/emqttd#1220]
#### Environment

- OS: Ubuntu Server 16.04.3 x64
- Erlang/OTP: R20/9.0
- EMQ: 2.3

#### Description
Hello!
not work https Dashboard on Ubuntu server 16.04.3 x64

![default](https://user-images.githubusercontent.com/4624056/29753891-2d9e5b4a-8b83-11e7-938f-e6adabf20cc0.JPG)
![2](https://user-images.githubusercontent.com/4624056/29753893-3135ef70-8b83-11e7-9826-4c300ad282fe.JPG)
![3](https://user-images.githubusercontent.com/4624056/29753894-32ecaf48-8b83-11e7-820d-091b306b3852.JPG)

Listener port 18084 not work

**Comment by emqplus** [comment]
@edgiru This issue is introduced in 2.3-beta.2. Please install the 2.3-beta.3 or 2.2.0 release.

**Comment by edgiru** [comment]
install 2.3-beta.3 not work. Deleted old, installed a new and deb package.
![3](https://user-images.githubusercontent.com/4624056/29793831-1bee8e76-8c4e-11e7-923c-68d36df6f745.JPG)
![2](https://user-images.githubusercontent.com/4624056/29793820-18d4815a-8c4e-11e7-8a77-8f907a0ff6fc.JPG)
![default](https://user-images.githubusercontent.com/4624056/29793817-163667ce-8c4e-11e7-8d27-774851fcdce1.JPG)

18083 - http work

**Comment by edgiru** [comment]
Figured out! the error was that emqtt did not find certificates on the specified path. The default is:
dashboard.listener.https.certfile = etc/certs/cert.pem
dashboard.listener.https.keyfile = etc/certs/key.pem

**Comment by bchhabra2490** [comment]
I am facing the same issue and I have certs on the right path. How can I check the logs of HTTPS dashboard?
