### ISSUE TITLE
emq_auth_redis plugin 

### ISSUE THREAD

**Issue by Rotem19** [emqtt/emqttd#1222]
I want to set up username/password and allow users to connect to certain topics.
How can I configure it in the emq_auth_redis plugin?

**Comment by emqplus** [comment]
@Rotem19 Documentation on Redis Authentication Plugin: http://emqtt.io/docs/v2/plugins.html#emq-auth-redis-redis-auth-acl-plugin

**Comment by Rotem19** [comment]
thx...I tried it but something is not working.
should I configure HSET mqtt_acl and HSET mqtt_user inside etc/plugins/emq_auth_redis.conf?
