### ISSUE TITLE
invalid clients can publish will message

### ISSUE THREAD

**Issue by srdgame** [emqtt/emqttd#1230]
#### Environment

- OS: Debian Testing(buster)
- Erlang/OTP:  R20/9.0
- EMQ:  v2.3-beta.1

#### Description

We haveing http backend for client authorization.  Client sets the will messages for helping servers detect the clients connection status (e.g. online, offline). 

The issue is that the will message (e.g. offline) has been published, even the clients do not pass authorization.

**Comment by srdgame** [comment]
@emqplus 
Attention *PLEASE*!!!!

This will message will not be valided by any auth interface!  It means user will hack on your MQTT Broker, and fire messages on *ANY* topics they want!!!!!

**Comment by emqplus** [comment]
@srdgame, Thanks for the security report. The issue will be fixed in 2.3-rc.1

**Comment by srdgame** [comment]
Code:
logging.debug('%s\t%s\t%d\t%d', msg.topic, msg.payload.decode('utf-8'), msg.qos, msg.retain)

LOG:
Sat, 30 Sep 2017 14:59:51 mqtt_sub.py[line:55] DEBUG i_am_a_hack	this is hack content, which breaks your auth module	0	0

**Comment by emqplus** [comment]
@srdgame The issue has been fixed in 2.3-rc.1 release. https://github.com/emqtt/emqttd/commit/88c77cf4c2e11e6cb1be27316c353060921b4018#diff-83e84d76b96bcb793b363258fac67e26
