### ISSUE TITLE
Joining two clusters

### ISSUE THREAD

**Issue by concurrent88** [emqtt/emqttd#1232]
If I have two nodes in each cluster such as 
Cluster1 - emq@10.60.101.1 and emq@10.60.101.2
Cluster2 - emq@10.60.101.3 and emq@10.60.101.4

Now if I join from emq@10.60.101.2 to 3 as - emqttd_ctl cluster join emq@10.60.101.3
Node 2 leaves its current cluster and moves to the new one. So, the cluster ends up as - 
Cluster1 - emq@10.60.101.1
Cluster2 - emq@10.60.101.2, emq@10.60.101.3 and emq@10.60.101.4

Is there a way to join two clusters such that it becomes a single cluster? For the above scenario, is it possible to have a single cluster with all 4 nodes when I join as stated above? Please let me know!

**Comment by turtleDeng** [comment]
@concurrent88 New node joins the cluster, new_node emqttd_ctl cluster join cluster_node

**Comment by turtleDeng** [comment]
#1065

**Comment by emqplus** [comment]
Invalid issue. A master node should be started first, and the following nodes join in.

**Comment by concurrent88** [comment]
Thanks for your response. Can you please explain how to use new_node? I don't see any in the documentation. Also, how to specify a node as master?
