### ISSUE TITLE
Can I use paho-mqtt client?

### ISSUE THREAD

**Issue by AhnSeongHyun** [emqtt/emqttd#1235]
#### Environment

- OS: CentOS 6.5
- Erlang/OTP: 
- EMQ: 2.2

Now, I check whether use or not. 
#### Description
Can I use paho-mqtt client? or have  another python client library for emqtt?

**Comment by trehn** [comment]
We're successfully using the Paho client libraries for Python, Java, and JavaScript with EMQ. So you should be fine.

**Comment by AhnSeongHyun** [comment]
Thank you! :+1:
