### ISSUE TITLE
Job for emqttd.service failed because the control process exited with error code. 

### ISSUE THREAD

**Issue by EagleSmith** [emqtt/emqttd#1238]
#### Environment

- OS: centos 7
- Erlang/OTP: 
- EMQ: 2.3.beta.3

#### Description

systemctl start emqttd.service
Job for emqttd.service failed because the control process exited with error code. See "systemctl status emqttd.service" and "journalctl -xe" for details.

systemctl status emqttd.service
● emqttd.service - emqtt daemon
   Loaded: loaded (/usr/lib/systemd/system/emqttd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-09-08 11:04:17 CST; 13s ago
  Process: 9278 ExecStart=/bin/sh emqttd start (code=exited, status=127)

Sep 08 11:04:17 iZ2zea13ipvafvo61r86p2Z systemd[1]: Starting emqtt daemon...
Sep 08 11:04:17 iZ2zea13ipvafvo61r86p2Z su[9278]: (to emqtt) root on none
Sep 08 11:04:17 iZ2zea13ipvafvo61r86p2Z systemd[1]: emqttd.service: control process exited, code=exited status=127
Sep 08 11:04:17 iZ2zea13ipvafvo61r86p2Z systemd[1]: Failed to start emqtt daemon.
Sep 08 11:04:17 iZ2zea13ipvafvo61r86p2Z systemd[1]: Unit emqttd.service entered failed state.
Sep 08 11:04:17 iZ2zea13ipvafvo61r86p2Z systemd[1]: emqttd.service failed.
[root@iZ2zea13ipvafvo61r86p2Z system]#
[root@iZ2zea13ipvafvo61r86p2Z system]# systemctl start emqttd.service
Job for emqttd.service failed because the control process exited with error code. See "systemctl status emqttd.service" and "journalctl -xe" for details.
[root@iZ2zea13ipvafvo61r86p2Z system]# systemctl stop emqttd.service
[root@iZ2zea13ipvafvo61r86p2Z system]# systemctl start emqttd.service
Job for emqttd.service failed because the control process exited with error code. See "systemctl status emqttd.service" and "journalctl -xe" for details.
[root@iZ2zea13ipvafvo61r86p2Z system]# systemctl status emqttd.service
● emqttd.service - emqtt daemon
   Loaded: loaded (/usr/lib/systemd/system/emqttd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-09-08 11:09:26 CST; 42s ago
  Process: 9544 ExecStart=/bin/sh emqttd start (code=exited, status=127)

Sep 08 11:09:25 iZ2zea13ipvafvo61r86p2Z systemd[1]: Starting emqtt daemon...
Sep 08 11:09:26 iZ2zea13ipvafvo61r86p2Z su[9544]: (to emqtt) root on none
Sep 08 11:09:26 iZ2zea13ipvafvo61r86p2Z systemd[1]: emqttd.service: control process exited, code=exited status=127
Sep 08 11:09:26 iZ2zea13ipvafvo61r86p2Z systemd[1]: Failed to start emqtt daemon.
Sep 08 11:09:26 iZ2zea13ipvafvo61r86p2Z systemd[1]: Unit emqttd.service entered failed state.
Sep 08 11:09:26 iZ2zea13ipvafvo61r86p2Z systemd[1]: emqttd.service failed.

**Comment by EagleSmith** [comment]
[root@iZ2zea13ipvafvo61r86p2Z emqttd]# vi run_erl.log
run_erl [7303] Fri Sep  8 09:49:00 2017
Args before exec of shell:
run_erl [7303] Fri Sep  8 09:49:00 2017
argv[0] = sh
run_erl [7303] Fri Sep  8 09:49:00 2017
argv[1] = -c
run_erl [7303] Fri Sep  8 09:49:00 2017
argv[2] = exec "/usr/sbin/emqttd" "console"

**Comment by EagleSmith** [comment]
sorry ,my Erlang/OTP version is: R20/9.0.
emqtt start is working fine.

**Comment by emqplus** [comment]
@EagleSmith The issue has been fixed in 2.3-beta.4
