### ISSUE TITLE
problem about acl http plugin

### ISSUE THREAD

**Issue by naruto0916** [emqtt/emqttd#1239]
#### Environment

- OS: Windows10
- Erlang/OTP: 
- EMQ: 2.2

#### Description

Hi EMQ team
I am trying the EMQ's HTTP Auth/ACL Plugin.
I follow the document' setting (http://emqttd-docs.readthedocs.io/en/latest/plugins.html#configure-http-auth-acl-plugin) and the auth part seems OK.
But, the acl part seems not work.
My acl rest api doesn't be called and the mqtt client can sub/pub topics.

And the cmd have a error:
16:15:09.487 [error] You've tried to set auth.http.acl_nomatch, but there is no setting with that name.
16:15:09.487 [error]   Did you mean one of these?
16:15:09.563 [error]     auth.http.acl_req
16:15:09.563 [error]     mqtt.acl_nomatch
16:15:09.563 [error]     auth.http.acl_req.method
16:15:09.577 [error] Error generating configuration in phase transform_datatypes
16:15:09.577 [error] Conf file attempted to set unknown variable: auth.http.acl_nomatch

I am not sure why emq show this message while start it.
If I remove the "auth.http.acl_nomatch = deny" from emq_auth_http.conf and restart emq server, the message won't appear.

Have any configuration I miss??
Please give me some suggestion about this question.
Thank you.

**Comment by turtleDeng** [comment]
auth.http.acl_nomatch The configuration item has been removed
emq.conf
```
mqtt.acl_nomatch  = allow
```

**Comment by naruto0916** [comment]
Hi turtleDeng

After I remove the auth.http.acl_nomatch in emq_auth_http.conf, the error message doesn't appear.
But, my acl rest api still doesn't be called and mqtt client still can pub/sub any topic.
Have other configuration need to set for http acl feature ??

My emq_auth_http.conf content is like below, have anything I lost ??

## Variables: %u = username, %c = clientid, %a = ipaddress, %P = password, %t = topic

auth.http.auth_req = http://localhost:8080/goalkeeper/service/v1/auth
auth.http.auth_req.method = get
auth.http.auth_req.params = clientid=%c,username=%u,password=%P

auth.http.super_req = http://localhost:8080/goalkeeper/service/v1/superuser
auth.http.super_req.method = get
auth.http.super_req.params = clientid=%c,username=%u

## 'access' parameter: sub = 1, pub = 2
auth.http.acl_req = http://localhost:8080/goalkeeper/service/v1/acl
auth.http.acl_req.method = get
auth.http.acl_req.params = access=%A,username=%u,clientid=%c,ipaddr=%a,topic=%t

**Comment by dreamcatcha** [comment]
My experience is when you first authenticate with http it checks if the user is a super user and if they are, then its cached that they are and never needs to call the acl as its a super user. Make sure your not connecting as a super user, then you will see the acl get call every request.

**Comment by naruto0916** [comment]
@dreamcatcha 

Thank you for your reply.
