### ISSUE TITLE
Config parsing bug in v2.3-beta.4

### ISSUE THREAD

**Issue by chriswue** [emqtt/emqttd#1251]
I just built a docker image from here: https://github.com/emqtt/emq-docker which points to 2.3-beta.4. The container crashes with the following message:

    CRASH REPORT Process <0.1205.0> with 0 neighbours exited with reason: call to undefined function string:split("emq_auth_clientid.conf", ".") in application_master:init/4 line 134
    [os_mon] memory supervisor port (memsup): Erlang has closed

This doesn't happen when I change the Docker file to point to 2.3-beta.3
Looks like a regression

**Comment by turtleDeng** [comment]
@chriswue Issue been fixed.

**Comment by emqplus** [comment]
@chriswue
