### ISSUE TITLE
Rewrite rules

### ISSUE THREAD

**Issue by Hades32** [emqtt/emqttd#126]
*feature request*

# Motivation
When operating a system for a longer time you will want to "refactor" your topic structure, just like any other part of your system. But when the clients cannot be update instantly (like IoT and mobile devices) this is a problem. Either you make double subscriptions and double your publications for the old and the new topic structure or you keep everything as it is and only add new stuff.

# Solution Proposal
In the world of HTTP the solution to above's problem has long been established: rewrite rules. E.g. an Apache has some regex that makes http://host.com/old/customers and changes it to http://host.com/new/sub/customers .

I'm proposing a similar feature for mqtt. The most straight forward approach I could think of would be to allow regex search and replace on a per Publish/Subscribe message base. So that the replacement could happen when a sub or pub arrives and the rest of the system always only sees the new topics.

**Comment by erylee** [comment]
An experimental design in 0.8.0 release: https://github.com/emqtt/emqttd/wiki/Rewrite

**Comment by erylee** [comment]
@Hades32, released 0.8.0-alpha with this feature. please try it.

**Comment by Hades32** [comment]
It's working very well! Great! 

What I haven't tried yet: I assume ACLs are applied *after* the rewrite. Correct?

**Comment by erylee** [comment]
No, ACL are applied before rewrite.

**Comment by Hades32** [comment]
so, have you come to the conclusion, that it is better to have them applied BEFORE rewrite?

**Comment by erylee** [comment]
@Hades32, no finally conclusion. We could improve the design when more users use the Rewrite features.

**Comment by ouinouin** [comment]
@emqplus  , old topic, as newcomer here i couldnt find some infos about acl  and rewrite precedence, finally, in 2024 , does acl takes place before or after rewrite ? 
in the case acl takes place before , is there any trickery available ? the goal being to isolate every user , with a rewrite rule in pub/sub rewriting everything and placing the username in front.

**Comment by zmstone** [comment]
Hi @ouinouin 
EMQX implements various features based on its hook mechanism.
The order of the hooked calls in older versions are not very deterministic (depends on the hook registration order).
Starting from v5, the order is determined, topic rewrite has a higher priority than ACL (authz),
see https://github.com/emqx/emqx/blob/15fbb966a072faa6765823328bd48554ade7e14d/apps/emqx/include/emqx_hooks.hrl#L24-L26

To achieve per-user isolation, you can configure a`mountpoint` for the listener.
Username is allowed as mountpoint placeholder, see https://github.com/emqx/emqx/blob/15fbb966a072faa6765823328bd48554ade7e14d/apps/emqx/src/emqx_mountpoint.erl#L37-L41

`listeners.tcp.default.mountpoint="${username}/"`

Here is an example:

1. Start EMQX:
```
docker run -p 1883:1883 -p 18083:18083 --rm -it -e EMQX_LISTENERS__TCP__DEFAULT__MOUNTPOINT="\${username}/" emqx/emqx:5.7.0 emqx console
```

2. Start subscriber
```
mqttx sub -t 't1' -h localhost -p 1883 -i 'clientid1' -u 'user2'
```

3. Observe the subscription on dashboard:
<img width="725" alt="image" src="https://github.com/emqx/emqx/assets/164324/2c9d1f1e-3f4f-4856-80e1-8c86d281046b">

**Comment by ouinouin** [comment]
@zmstone  thanks for valuable answer, by trial i could see that apparently rewrite rules takes precedence over ACL.
for mountpoint, i ll dig into that , looks interresting.
Thanks again for the hint.
