### ISSUE TITLE
How can I count a topic 's subscribers?

### ISSUE THREAD

**Issue by n3ksus** [emqtt/emqttd#1260]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 2.3.1

#### Description

I need to get the count of a topic's subscribers in my plugin.
Should I user ets:select_count  directly like the below code:
  `Count=ets:select_count(mqtt_subscriber, ets:fun2ms(fun({Topic,_})when Topic == <<"xxx">>  -> true  end)),`
If not ,is there any better way to do it?

**Comment by turtleDeng** [comment]
@n3ksus 
```
ets:match_object(mqtt_subproperty, {{Topic, '_'}, '_'}).
```
