### ISSUE TITLE
单机部署连接数上不去

### ISSUE THREAD

**Issue by hahafeixiu** [emqtt/emqttd#1266]
#### Environment

- OS: centos7.4
- Erlang/OTP: 19.1
- EMQ: 2.2

#### Description
服务器只能接受65512的连接数配置
![default](https://user-images.githubusercontent.com/11630625/30683689-08d37ea4-9e74-11e7-8f1b-098fa059a1cc.png)
![default](https://user-images.githubusercontent.com/11630625/30683699-12e25e1a-9e74-11e7-987d-404a2c2b43c0.png)

*A description of the issue*

请问怎么样才能连接更多的连接数？需要改配置文件么？

**Comment by turtleDeng** [comment]
Invalid issue, closed
