### ISSUE TITLE
Subscribe to topic with wildcard fails /test/# etc

### ISSUE THREAD

**Issue by dreamcatcha** [emqtt/emqttd#1269]
#### Environment

- OS:  Ubuntu 16.04.3
- Erlang/OTP:  20
- EMQ:  2.3

#### Description

I have setup emq with the deb file and enabled the http auth plugin and written a simple node http server to fulfill the auth, superuser, and acl requests to just allow all in testing.

The problem i have is when I go to send a message to the rest api 'api/v2/mqtt/publish' endpoint its failing on subscriptions with wildcards

user subscribe to /test/#
and message published to /test/room

I'm not sure what I'm doing wrong, but it seems this should work, 

Im also using the android toolkit app as the client

EDIT:

Turns out it is working but the android toolkit app isn't displaying anything for subscribed topics with wildcards

**Comment by turtleDeng** [comment]
@dreamcatcha The mqtt protocol states, publish can not use wildcards.

**Comment by dreamcatcha** [comment]
@turtleDeng yeah i corrected the post, its the android application failing to show the messages from subscriptions with wildcards, works in another android client
