### ISSUE TITLE
关于 PUBACK、 PUBREC 或 PUBREL返回的packet id(message id)问题

### ISSUE THREAD

**Issue by w3yyb** [emqtt/emqttd#127]
PUBACK、 PUBREC 或 PUBREL返回的 message id 为什么和客户端发送的message id不一样？
怎么样保持 客户端和broker的 msgid一致？是否不一致也可以？

另外 客户端每断开一次链接，broker 返回的msgid要重置（mosquitto） ，emqtt貌似不会，是否bug?,
发现更新订阅客户端clientid再订阅 ，msgid会重置（也就是说msgid是针对每客户端 的么）

望解答，谢谢

**Comment by erylee** [comment]
1. 同一消息的PUBACK, PUBREC, PUBREL messageid一致，客户端必须通过msgid确定qos1, qos2消息。你们php客户端id处理错误，只保留了last message ID，应该保存未响应的sub、unsub、qos1、qos2 publish。

2. 客户端端开，emqttd会重置msgid。
