### ISSUE TITLE
win7/10安装服务失败

### ISSUE THREAD

**Issue by xljiulang** [emqtt/emqttd#1271]
#### Environment

- OS: win7/10 x64
- Erlang/OTP: 
- EMQ: 2.2

#### Description

Windows 无法启动 emqttd_2.2 服务(位于 本地计算机 上)。
错误 1067: 进程意外终止。

**Comment by emqplus** [comment]
Invalid issue, closed.

**Comment by 0zhouquan0** [comment]
How can this problem be solved? @xljiulang @emqplus

**Comment by xljiulang** [comment]
@0zhouquan0 No solved，无解
