### ISSUE TITLE
Single user authentication

### ISSUE THREAD

**Issue by davorozo** [emqtt/emqttd#1272]
####    ###Environment

- OS: Windows
- Erlang/OTP: 
- EMQ: 

#### Description

Hello,

I'd like to know if is there any way to configure the broker in order to allow a single user session connection?, this could be by user name or client id. We are using MySQL authentication plugin, but we need to limit the connections to be single instance per user. 

Thank you.

**Comment by grutabow** [comment]
In fact, mqtt has such a constraint that each clientId allows only one instance. For example, a mqtt client connects broker with clientId=test. Minutes later, another mqtt client connects broker with clientId=test too. The later one will kick out the first one who will lost the connection.

Is this what you want?

**Comment by roysG** [comment]
@davorozo,@grutabow,
 I am looking for the same answer, can you tell me how you did it?
