### ISSUE TITLE
How to push a subscriber based on clientid？ I only see topic push？

### ISSUE THREAD

**Issue by hahafeixiu** [emqtt/emqttd#1273]
#### Environment

- OS: macos
- Erlang/OTP: 20
- EMQ: 2.2

#### Description
I want  push a subscriber based on clientid? but I cann't see the interface? sos
*A description of the issue*

**Comment by hahafeixiu** [comment]
curl -v --basic -u admin:public -d "qos=1&retain=0&topic=hello&message=sd1234&clientid=localhost_bench_sub_1_3885104127" -k http://127.0.0.1:8080/mqtt/publish

**Comment by turtleDeng** [comment]
@hahafeixiu  publish topic $client/<clientid>

**Comment by HJianBo** [comment]
@hahafeixiu 
You can get the solution at http://www.emqtt.com/docs/v2/rest.html#id18
