### ISSUE TITLE
Persist Logs for longer time

### ISSUE THREAD

**Issue by nareshbvemula** [emqtt/emqttd#1275]
#### Environment

- OS: ubuntu 16.04
- Erlang/OTP: 
- EMQ: 2.2

#### Description

Do emqtt support in persisting erlang.log.1 for longer time.

**Comment by emqplus** [comment]
@nareshbvemula Added more log configurations in 2.3-rc.1 release to fix the issue. 

```
## Console log file size
## log.console.size = 10485760

## Console log count size
## log.console.count = 5

## Error log file size
log.error.size = 10485760

## Error log file count
log.error.count = 5
```

**Comment by xerosanyam** [comment]
What is the meaning of log file count ? 
I can currently see
1. crash.log
2. crash.log.0
3. erlang.log.1
4. error.log
5. error.log.0
6. run_erl.log
What is the meaning of 0,1 suffixes ?
Is there a way to get only 1 crash.log, 1 erlang.log and 1 error.log and remove old logs from these files like a queue.

**Comment by HJianBo** [comment]
Hi @xerosanyam The file in larger suffixes number is older log file

Sure, just set a file count to some log level in `etc/emq.conf` i.e:
```
## Error log file size
log.error.size = 10485760

## Error log file count
log.error.count = 1
```
