### ISSUE TITLE
Windows 7 can't start service

### ISSUE THREAD

**Issue by sinegole** [emqtt/emqttd#1278]
#### Environment

- OS: Windows 7 Profesional, SP1 / 64bit 
- Erlang/OTP:  ?
- EMQ: emqttd-2.3-beta.4  also was tested and problem is same on emqttd-2.3-beta.3 and 2.2.

#### Description
I can start console (bin\emqttd console), also can install service (bin\emqttd install), but starting service have problem (bin\emqttd start). The service emqttd_2.3 is installed, but service is not started.
I was tried manually start using Services windows, but service have error.
Please see image: https://prnt.sc/gr268b
This is relay urgent can someone fix this service.

**Comment by epopoee** [comment]
workaround is here https://github.com/emqtt/emqttd/issues/803

**Comment by emqplus** [comment]
@sinegole Close the issue.
