### ISSUE TITLE
Emqtt broker limits to less than 1000 connections

### ISSUE THREAD

**Issue by swarno** [emqtt/emqttd#1279]
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP: 
- EMQ: 2.2

#### Description

I have tuned the emqtt broker as per the one million connection guide. Every time **emqtt machine is restarted** , it doesn't accept more than 1000 client connections.The number varies from 985 to 1000 , none of the emqttd_ctl commands works and responds back with node not responding error. However the messages still keep on flowing between the existing client connections(Publisher/Subscriber). Any more clients spawned after this gets a shutdown/timeout error.

As a workaround, a stop and start of emqtt broker(**Not the Machine in itself**) is required for the number of connections to go above this 1000 mark. After that it goes up as per the requirements but on restart of the machine again it limits to 1000 clients.

Here is the snapshot of the error log.

![image](https://user-images.githubusercontent.com/13292675/31120163-23345f3e-a851-11e7-8c73-fa04f49fc6ff.png)

**Comment by swarno** [comment]
I think the problem is updation of the vm io for erlang.
On restart of the machine it shows 1024 and on restart of only borker after that it gets the correct value. What is the configuration required so that erlang takes the value on restart of the machine.

![image](https://user-images.githubusercontent.com/13292675/31121146-af5ae16a-a854-11e7-938b-cae6896544c2.png)

**Comment by PiedPieper** [comment]
The problem is your file limit. The default for Ubuntu is ~1000 open files. You need to change the limits on your system, here is a link:
http://posidev.com/blog/2009/06/04/set-ulimit-parameters-on-ubuntu/

**Comment by turtleDeng** [comment]
@swarno http://emqtt.io/docs/v2/tune.html
