### ISSUE TITLE
MQTT detected framing error invalid_mqtt_frame_len for connection 

### ISSUE THREAD

**Issue by brangi** [emqtt/emqttd#128]
I am using the paho library android on a nexus 5 phone and after publishing a message, the broker experiences the following error:

10:05:43.162 [info] RECV from mqttandroid-e9622abe69cba5e5a68d2b54e558e208d5972977@85.76.142.118:36558: PUBACK(Qos=0, Retain=false, Dup=false, PacketId=1)
10:05:44.174 [error] MQTT detected framing error invalid_mqtt_frame_len for connection "85.76.142.118:36558 -> 172.31.8.18:1883"

and immediately the client disconnects, this continues every time the client tries to connect

Is there anyway to fix this?

**Comment by erylee** [comment]
@brangi, It seems your packet is too long. You could configure 'max_packet_size' in etc/emqttd.config, for example:

```
    %% MQTT Protocol Options
    {mqtt, [
        %% Packet
        {packet, [
            %% Max ClientId Length Allowed
            {max_clientid_len, 1024},
            %% Max Packet Size Allowed, 4K default
            {max_packet_size,  4096}
        ]},
```

**Comment by erylee** [comment]
64K default in 0.8.0 release.

etc/emqttd.config:
```
 %% Max Packet Size Allowed, 64K default
            {max_packet_size,  65536}
```

**Comment by brangi** [comment]
Thanks, this helped.

**Comment by kani-rifluxyss** [comment]
Trying to send large files (about 10 MB), is it okay to increase this value to more than 10 MB?
`max_packet_size`
Please advise.

**Comment by turtleDeng** [comment]
hi
max packet size is 64K, If you want to modify, etc/emqttd.conf  mqtt_max_packet_size

**Comment by emqplus** [comment]
The new configuration syntax in 2.0:

```
## Max Packet Size Allowed, 64K by default.
mqtt.max_packet_size = 64KB
```
