### ISSUE TITLE
Endless Last-Will-And-Testament

### ISSUE THREAD

**Issue by EzPluto** [emqtt/emqttd#1286]
#### Environment

Docker images : emqttd-docker-v2.3-beta.4

3 nodes cluster

#### Description

step1 : connect to the cluster and set up the last will message in MQTTLens（Chrome extensions）
step2 : disconnect the client network (in my case, close the wifi switch)
step3 : other client subscribe  the last will topic, and  receive the last will message sent by emqttd endless

**Comment by turtleDeng** [comment]
@EzPluto Will message  RETAIN flag is?

**Comment by EzPluto** [comment]
@turtleDeng flag is true ，the screenshots upload error ，can not show the details

**Comment by EzPluto** [comment]
@turtleDeng  turn the flag to false , same

**Comment by turtleDeng** [comment]
step1: clear retian message
step2: Will message RETAIN flag false
