### ISSUE TITLE
Crash on macOS High Sierra

### ISSUE THREAD

**Issue by qudenger** [emqtt/emqttd#1297]
#### Environment

- OS: mac 10.13 (17A405)
- Erlang/OTP: 20 [erts-9.1.2]
- EMQ: emqttd 2.2 or 2.3-rc.1 

#### Description
 It will crash on the new macOS High Sierra when start running.

emqttd 2.2 is running now
Eshell V8.3  (abort with ^G)
(emqttd@127.0.0.1)1> Assertion failed: (ctx), function digest_update, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl/boringssl-109.1.6/apple/crypto/digests.c, line 49.
                                                                                                                                                                                       [os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[1]    2893 abort      sudo bin/emqttd console

**Comment by HJianBo** [comment]
@qudenger We have built a compatible to macos10.13 release package. You can download it now :) http://www.emqtt.io/downloads

**Comment by qudenger** [comment]
ok, it works now, thanks!
