### ISSUE TITLE
mongo_auth throwing error while enabling

### ISSUE THREAD

**Issue by shuaibakram** [emqtt/emqttd#1303]
#### Environment

- OS: Ubuntu
- Erlang/OTP: 2.3-rc1
- EMQ: 

The following is my config entry

`
auth.mongo.type = single`
`
auth.mongo.server = ds11****.mlab.com:17829
`
emqtt clients are not able to connect with valid username and password

**Comment by turtleDeng** [comment]
@shuaibakram Please provide more log.

**Comment by shuaibakram** [comment]
Hi
I have upgraded the version from 2.3-rc.2 and the issue persists.
Below is the error log.
`
12:06:22.025 [info] Started Apps: [emq_auth_mongo]
12:06:22.025 [info] Load plugin emq_auth_mongo successfully
12:06:22.025 [info] Application emq_auth_mongo started on node 'emq@127.0.0.1'
12:06:22.113 [debug] Mod:emqttd_rest_api, Fun:plugin_list, Args:['GET',[{"timestamps","1508760381379"}],"emq@127.0.0.1"]
12:06:22.522 [error] gen_server <0.1506.0> terminated with reason: killed
12:06:22.522 [error] CRASH REPORT Process <0.1506.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:22.522 [error] gen_server <0.1469.0> terminated with reason: killed
12:06:22.560 [error] CRASH REPORT Process <0.1469.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:22.560 [error] gen_server <0.1496.0> terminated with reason: killed
12:06:22.560 [error] CRASH REPORT Process <0.1496.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:22.560 [error] gen_server <0.1481.0> terminated with reason: killed
12:06:22.561 [error] CRASH REPORT Process <0.1481.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:22.561 [error] gen_server <0.1476.0> terminated with reason: killed
12:06:22.561 [error] CRASH REPORT Process <0.1476.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:22.562 [error] gen_server <0.1486.0> terminated with reason: killed
12:06:22.562 [error] CRASH REPORT Process <0.1486.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:22.562 [error] gen_server <0.1491.0> terminated with reason: killed
12:06:22.563 [error] CRASH REPORT Process <0.1491.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:22.563 [error] gen_server <0.1501.0> terminated with reason: killed
12:06:22.563 [error] CRASH REPORT Process <0.1501.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:23.175 [error] gen_server <0.1558.0> terminated with reason: killed
12:06:23.175 [error] CRASH REPORT Process <0.1558.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:23.175 [error] gen_server <0.1559.0> terminated with reason: killed
12:06:23.176 [error] CRASH REPORT Process <0.1559.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:23.176 [error] gen_server <0.1561.0> terminated with reason: killed
12:06:23.176 [error] CRASH REPORT Process <0.1561.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:23.176 [error] gen_server <0.1546.0> terminated with reason: killed
12:06:23.177 [error] CRASH REPORT Process <0.1546.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:23.177 [error] gen_server <0.1489.0> terminated with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204
12:06:23.381 [error] CRASH REPORT Process <0.1489.0> with 0 neighbours crashed with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204
12:06:23.381 [error] gen_server <0.1550.0> terminated with reason: killed
12:06:23.381 [error] CRASH REPORT Process <0.1550.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:23.381 [error] gen_server <0.1554.0> terminated with reason: killed
12:06:23.382 [error] CRASH REPORT Process <0.1554.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:23.382 [error] gen_server <0.1544.0> terminated with reason: killed
12:06:23.382 [error] CRASH REPORT Process <0.1544.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:25.271 [error] gen_server <0.1484.0> terminated with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204
12:06:25.271 [error] CRASH REPORT Process <0.1484.0> with 0 neighbours crashed with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204
12:06:25.271 [error] gen_server <0.1556.0> terminated with reason: killed
12:06:25.272 [error] CRASH REPORT Process <0.1556.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:25.272 [error] gen_server <0.1529.0> terminated with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204
12:06:25.272 [error] CRASH REPORT Process <0.1529.0> with 0 neighbours exited with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204 in gen_server:handle_common_reply/8 line 726
12:06:25.272 [error] gen_server <0.1576.0> terminated with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204
12:06:25.272 [error] CRASH REPORT Process <0.1576.0> with 0 neighbours exited with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204 in gen_server:handle_common_reply/8 line 726
12:06:25.272 [error] gen_server <0.1467.0> terminated with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204
12:06:25.272 [error] CRASH REPORT Process <0.1467.0> with 0 neighbours crashed with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204
12:06:25.272 [error] gen_server <0.1527.0> terminated with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204
12:06:25.273 [error] CRASH REPORT Process <0.1527.0> with 0 neighbours exited with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204 in gen_server:handle_common_reply/8 line 726
12:06:25.273 [error] gen_server <0.1578.0> terminated with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204
12:06:25.273 [error] CRASH REPORT Process <0.1578.0> with 0 neighbours exited with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204 in gen_server:handle_common_reply/8 line 726
12:06:25.433 [error] gen_server <0.1517.0> terminated with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204
12:06:25.433 [error] CRASH REPORT Process <0.1517.0> with 0 neighbours exited with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204 in gen_server:handle_common_reply/8 line 726
12:06:25.433 [error] gen_server <0.1584.0> terminated with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204
12:06:25.433 [error] CRASH REPORT Process <0.1584.0> with 0 neighbours exited with reason: no match of right hand value [] in mc_topology:parse_ismaster/4 line 204 in gen_server:handle_common_reply/8 line 726
12:06:25.433 [error] gen_server <0.1589.0> terminated with reason: killed
12:06:25.435 [error] CRASH REPORT Process <0.1589.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:25.435 [error] gen_server <0.1598.0> terminated with reason: killed
12:06:25.435 [error] CRASH REPORT Process <0.1598.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:25.476 [error] gen_server <0.1594.0> terminated with reason: killed
12:06:25.476 [error] CRASH REPORT Process <0.1594.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:25.477 [error] gen_server <0.1596.0> terminated with reason: killed
12:06:25.477 [error] CRASH REPORT Process <0.1596.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:25.477 [error] gen_server <0.1593.0> terminated with reason: killed
12:06:25.477 [error] CRASH REPORT Process <0.1593.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:25.477 [error] gen_server <0.1612.0> terminated with reason: killed
12:06:27.080 [error] CRASH REPORT Process <0.1612.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:27.080 [error] gen_server <0.1614.0> terminated with reason: killed
12:06:27.080 [error] CRASH REPORT Process <0.1614.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:27.080 [error] gen_server <0.1616.0> terminated with reason: killed
12:06:27.240 [error] CRASH REPORT Process <0.1616.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:27.240 [error] gen_server <0.1618.0> terminated with reason: killed
12:06:27.241 [error] CRASH REPORT Process <0.1618.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:27.241 [error] gen_server <0.1615.0> terminated with reason: killed
12:06:27.241 [error] CRASH REPORT Process <0.1615.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:27.241 [error] gen_server <0.1628.0> terminated with reason: killed
12:06:27.242 [error] CRASH REPORT Process <0.1628.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:27.242 [error] gen_server <0.1627.0> terminated with reason: killed
12:06:27.242 [error] CRASH REPORT Process <0.1627.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:27.280 [error] gen_server <0.1650.0> terminated with reason: killed
12:06:27.280 [error] CRASH REPORT Process <0.1650.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:27.280 [error] gen_server <0.1641.0> terminated with reason: killed
12:06:27.280 [error] CRASH REPORT Process <0.1641.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:27.280 [error] gen_server <0.1648.0> terminated with reason: killed
12:06:27.280 [error] CRASH REPORT Process <0.1648.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:27.280 [error] gen_server <0.1649.0> terminated with reason: killed
12:06:27.281 [error] CRASH REPORT Process <0.1649.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:27.281 [error] gen_server <0.1647.0> terminated with reason: killed
12:06:27.281 [error] CRASH REPORT Process <0.1647.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:27.282 [error] gen_server <0.1633.0> terminated with reason: killed
12:06:27.282 [error] CRASH REPORT Process <0.1633.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
12:06:27.282 [error] gen_server <0.1664.0> terminated with reason: killed
12:06:27.282 [error] CRASH REPORT Process <0.1664.0> with 1 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410`

**Comment by turtleDeng** [comment]
@shuaibakram Please check your emq_auth_mongo state.

**Comment by shuaibakram** [comment]
@turtleDeng Incase you are referring to the plugin status in EMQ Dashboard, it shows running.
If you are referring to something else, please let me know where I can check it.

**Comment by shuaibakram** [comment]
The following is the error I got while running form source. 

`05:08:40.306 [error] GenServer #PID<0.11687.1> terminating
** (stop) killed
Last message: {:EXIT, #PID<0.11686.1>, :killed}
State: {:state, :undefined, 'ds117829.mlab.com', 17829, #PID<0.11670.1>, #PID<0.11686.1>, [], [database: "db", login: "login", password: "password"], :undefined, 20000, 10000, 1000, #PID<0.11689.1>, 1}`

**Comment by HJianBo** [comment]
Repeated at https://github.com/emqtt/emq-auth-mongo/issues/88

**Comment by emqplus** [comment]
@shuaibakram The issue will be fixed in `emq-auth-mongo` plugin.
