### ISSUE TITLE
Installing EMQTTD from source failed

### ISSUE THREAD

**Issue by hamdijmii1992** [emqtt/emqttd#1307]
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP: 19.2
- EMQ: v2.3-rc.2

I am trying to install emqttd from source, but I cannot run "make dist"

> git clone https://github.com/emqtt/emqttd.git
> 
> cd emqttd
> 
> git submodule update --init --recursive
> 
> make && make dist

make dist command failed with "make: *** No rule to make target `dist'.  Stop."

**Comment by turtleDeng** [comment]
@hamdijmii1992 
https://github.com/emqtt/emq-relx

**Comment by hamdijmii1992** [comment]
Thanks @turtleDeng, With emq-relx, can I add a new plugin and recompile the project .
