### ISSUE TITLE
Unable to start emqttd with auth.mongo.acl_nomatch = deny

### ISSUE THREAD

**Issue by xerosanyam** [emqtt/emqttd#1308]
#### Environment

- OS: UBUNTU 17.04
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

Unable to start emqttd with auth.mongo.acl_nomatch = deny

**Comment by turtleDeng** [comment]
@xerosanyam 

This configuration auth.mongo.acl_nomatch does not exist, please use it emq.conf
```
mqtt.acl_nomatch = deny
```

**Comment by xerosanyam** [comment]
Thanks for prompt reply.
Adding ACL rules in mongo work or I need to add local ACL rules only ?
ie
1. db.mqtt_acl.insert({username: "test", publish: ["t/1", "t/2"], subscribe: ["user/%u", "client/%c"]})
Or 
2. acl.conf

Will 1 work or need to follow 2nd method ?

**Comment by turtleDeng** [comment]
@xerosanyam 
Please see documentation: http://emqtt.io/docs/v2/guide.html#user-guide

**Comment by xerosanyam** [comment]
@turtleDeng 
I have seen that. The documentation says to set `auth.mongo.acl_nomatch = deny`. But as you pointed out it does not exist.
My question is whether I can still use mongo to set ACL rules ?

**Comment by turtleDeng** [comment]
@xerosanyam 
auth.mongo.acl_nomatch unavailable

**Comment by xerosanyam** [comment]
I think I figured this out.
Mongo ACL rules work even **without** adding this parameter.
`auth.mongo.acl_nomatch = deny` in `emq_auth_mongo.conf`

also keeping
`mqtt.acl_nomatch = allow` in `emq.conf` will still block if mongo ACL rule is set.
