### ISSUE TITLE
undefined status in web ui

### ISSUE THREAD

**Issue by carlos-renjel-coderoad-com** [emqtt/emqttd#1309]
#### Environment

- OS: official docker image
- Erlang/OTP: 8.1
- EMQ: Stable 2.2.0

#### Description

I've been trying to use a newer version of emqttd as I was using 2.0.2 from a non official container, but in all EMQ 2.2.x version I see an undefined label in clients and session tabs. I.e, SendMsg RecvMsg, MaxInflight.... and so on
![image](https://user-images.githubusercontent.com/9953086/31900646-1f25dd0e-b7ed-11e7-82a0-c1a1f45802bd.png)

**Comment by emqplus** [comment]
@carlos-renjel-coderoad-com Enable the client Stats in etc/emqttd.conf:

```
## Enable client Stats: on | off
mqtt.client.enable_stats = on
```

**Comment by carlos-renjel-coderoad-com** [comment]
@emqplus 
Hi! I just enabled mqtt.client.enable_stats = on and mqtt.session.enable_stats = on, and everything is as expected
Thanks!
