### ISSUE TITLE
EMQ + LetsEncrypt

### ISSUE THREAD

**Issue by xerosanyam** [emqtt/emqttd#1310]
#### Environment

- OS: Ububtu
- Erlang/OTP: 
- EMQ: 2.3

#### Description

Please give steps on how to Generate a certificate using letsencrypt and use it successfully over wss.

**Comment by xerosanyam** [comment]
@emqplus @turtleDeng Anyone please mention the steps ? I tried the method, still getting `ERR_SSL_PROTOCOL_ERROR`

**Comment by xerosanyam** [comment]
Getting `ERR_CONNECTION_CLOSED` for  `:8083/mqtt` & `ERR_SSL_PROTOCOL_ERROR` `:18083/`

**Comment by xerosanyam** [comment]
````
Error in process <0.4010.0> on node 'emq@127.0.0.1' with exit value:
{{ssl_error,{options,{certfile,"/etc/letsencrypt/live/api.sanyamja.in-0001/fullchain.pem",{error,eacces}}}},[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{line,131}]},{mochiweb_http,init,2,[{file,"src/mochiweb_http.erl"},{line,30}]}]}
2017-10-25 15:17:29 =SUPERVISOR REPORT====
     Supervisor: 'esockd_connection_sup - <0.1490.0>'
     Context:    connection_crashed
     Reason:     {{ssl_error,{options,{certfile,"/etc/letsencrypt/live/api.sanyamja.in-0001/fullchain.pem",{error,eacces}}}},[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{line,131}]},{mochiweb_http,init,2,[{file,"src/mochiweb_http.erl"},{line,30}]}]}
     Offender:   [{pid,<0.4010.0>},{name,connection},{mfargs,{mochiweb_http,start_link,[{emqttd_ws,handle_request,[]}]}}]
```

**Comment by xerosanyam** [comment]
okay, so ran with sudo command.
able to connect on wss. but still unable to access the dashboard at https

**Comment by zhengyupan** [comment]
@xerosanyam please refer to this article to find how to config the EMQ with Let's Encrypt certificates.
﻿﻿﻿https://medium.com/@emqtt/using-lets-encrypt-certificates-in-emq-b11e0e57efa6
