### ISSUE TITLE
rest api not work

### ISSUE THREAD

**Issue by kekemuyu** [emqtt/emqttd#1313]
#### Environment

- OS: win7
- Erlang/OTP: 8.3
- EMQ: 2.3

#### Description
run this request:  curl -v --basic -u <user>:<passwd> -k http://localhost:8080/api/v2/nodes/emq@127.0.0.1/clients
the respond is :not found.

**Comment by turtleDeng** [comment]
@kekemuyu http://emqtt.io/docs/v2/rest.html#basic-authentication

**Comment by kekemuyu** [comment]
It is still not work.  
This is the screenshot
![image](https://user-images.githubusercontent.com/8471788/31974394-15bebb60-b95e-11e7-9acc-7c9c953b1705.png)
