### ISSUE TITLE
Change SSL port of EMQ

### ISSUE THREAD

**Issue by Prerna2929** [emqtt/emqttd#1317]
#### Environment

- OS: Ubuntu 
- Erlang/OTP: All
- EMQ: All

#### Description

I have tried to change the port of SSL but it is not affected even after server restarted.
I have made a change in emq.conf file and restarted the server but could not affect.
I want to change the port 8083 to 443 or some else. is it possible?

**Comment by turtleDeng** [comment]
@Prerna2929 1024 before the port, Please use 
```
sudo ./bin/emqttd start 
```

**Comment by weljack** [comment]
I have the same issue. Please help us !!

**Comment by grutabow** [comment]
443 is a privileged port which can not be open by a normal user. Please run emqttd with root account.

**Comment by emqplus** [comment]
Close the issue.
