### ISSUE TITLE
Difference between Windows10 and Windows 7 binary build

### ISSUE THREAD

**Issue by michaelcplusplus** [emqtt/emqttd#1326]
#### Environment

OS: Windows 10
Erlang/OTP:
EMQ: 2.3 rc.2

#### Description

Whats is the difference between these both downloads:
http://emqtt.io/downloads/latest/windows10
http://emqtt.io/downloads/latest/windows7

It seems to me, that the windows 10 binary download runs on an windows 7 based operationg system without any problems.

**Comment by emqplus** [comment]
@michaelcplusplus No difference. We build two binary packages for windows to avoid compatible issue.
