### ISSUE TITLE
How to get datetime?

### ISSUE THREAD

**Issue by xerosanyam** [emqtt/emqttd#1327]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 2.3

#### Description

*A description of the issue*
I want to get datetime of server. After lot of research I figured out that $SYS/broker/time topic exists specially for this purpose. But I am unable to make use of it. Can anyone please mention steps to get it.
Thanks in advance.

**Comment by HJianBo** [comment]
First, you should subscribe the topic `$SYS/brokers/emq@127.0.0.1/datetime` to get system datetime. (**emq@127.0.0.1** is the specified broker name, which you can find on Dashboard)

Besides, check out access control configurations in the `etc/acl.conf` file. The others IP address will be denied by default, when they subscribe system topic!

**Comment by xerosanyam** [comment]
Thanks for reply!

Two questions:
1. With what frequency, the system publishes datetime at this topic? Is the frequency configurable, if yes, how?
2. In Acl rules, I have configured user 'A' to subscribe/publish to only topic 'A/#', does that mean, it cannot subscribe to '$SYS/#' ? I mean system topics are also bound in Acl rules?

Thanks in advance. Still trying to get the datetime.

**Comment by xerosanyam** [comment]
@HJianBo this is not working, tried many permutation combinations.

**Comment by xerosanyam** [comment]
figured this out.
1. System publishes datetime every second.
2. 'A' cannot subscribe to '$SYS' if it is only configured in ACL for 'A/#'.

$ in $SYS needs to be escaped.
mosquitto_sub -t \$SYS/brokers/emq@127.0.0.1/datetime works!
but 
mosquitto_sub -t $SYS/brokers/emq@127.0.0.1/datetime or mosquitto_sub -t '$SYS/brokers/emq@127.0.0.1/datetime' don't.
