### ISSUE TITLE
mysql_acl rules not working

### ISSUE THREAD

**Issue by LChunYuan** [emqtt/emqttd#1328]
#### Environment

- OS: Ubuntu 16.04.1 LTS
- Erlang/OTP: 
- EMQ: emqttd-ubuntu16.04-v2.3-rc.2

#### Description

I loaded the emq_auth_mysql  plugin correctly, and I can use the username and password to login sucessfuly. 

Problem:  When I use username='test' Account,  I can subscribe any topics and publish ant topics , so the ACL rule not works for me.

- **This is my emq.conf configuration**

<img width="550" alt="emq conf" src="https://user-images.githubusercontent.com/4382827/32413197-20ca4ec4-c247-11e7-8b13-aaade29119be.png">

- **mqtt_user**
![image](https://user-images.githubusercontent.com/4382827/32413202-5b66dc50-c247-11e7-9392-6f4c17732551.png)

- **mqtt_acl**
![image](https://user-images.githubusercontent.com/4382827/32413265-f22105a2-c248-11e7-8cf5-9060ccc344c5.png)

Thanks in advance. @emqplus

**Comment by HJianBo** [comment]
It seems right! There are some tips about that:
- restart services, when you modify the `etc/emq.conf` file
- if you are not sure whether client has been blocked, you can check it in the `etc/error.log` file

**Comment by emqplus** [comment]
Close the issue.

**Comment by vec715** [comment]
@emqplus why close? Any details how to fix this one? Got the same results right now with the serverless broker
