### ISSUE TITLE
mysql _acl not work

### ISSUE THREAD

**Issue by zhaolei-best** [emqtt/emqttd#1329]
#### Environment

- OS: window7
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*
配置了mysql acl 
INSERT INTO `mqtt_acl` (`allow`, `ipaddr`, `username`, `clientid`, `access`, `topic`) VALUES (1, '127.0.0.1', 'user1', 'c2', 3, 'topic2');

**emq_auth_mysql.conf：**
auth.mysql.auth_query = select password from mqtt_user where username = '%u' limit 1
auth.mysql.super_query = select is_superuser from mqtt_user where username = '%u' limit 1
auth.mysql.acl_query = select allow, ipaddr, username, clientid, access, topic from mqtt_acl where ipaddr = '%a' or username = '%u' or username = '$all' or clientid = '%c'

emq.conf：
mqtt.allow_anonymous = false
mqtt.acl_nomatch = deny

但是 当我用客户端发布消息的时候失败 在error.log里面有打印
“2017-11-06 21:51:44.692 [error] <0.498.0>@emqttd_protocol:process:233 Client(c2@10.13.64.194:51372): Cannot publish to topic2 for ACL Deny”

是我哪里配置错了 还是acl控制有问题？

**Comment by Nawneet47** [comment]
Same Issue , Is there any example of how to make a public topic for that client to access this topic outside of localhost
