### ISSUE TITLE
REST API HTTP basic auth

### ISSUE THREAD

**Issue by sincsc** [emqtt/emqttd#1331]
#### Environment

- OS: UBUNTU
- Erlang/OTP: 
- EMQ: 2.3.2

#### Description

where can I config the REST API HTTP basic auth username and password？

**Comment by turtleDeng** [comment]
@sincsc Authorized dashboard user is admin/public

**Comment by sincsc** [comment]
![image](https://user-images.githubusercontent.com/17526484/32583964-08fad0f6-c531-11e7-863e-aea390b77891.png)
I and user 'test' in Admins, but  I can use any username and password authorize the HTTP REST API, I don't know why.

**Comment by turtleDeng** [comment]
@sincsc  emqttd version?

**Comment by sincsc** [comment]
I use emqttd 2.2

**Comment by sincsc** [comment]
@turtleDeng I use emqttd 2.2

**Comment by turtleDeng** [comment]
@sincsc 2.2？, Please provide the path to your download package.

**Comment by sincsc** [comment]
@turtleDeng Here is : http://emqtt.com/static/brokers/emqttd-ubuntu16.04-v2.2.0_amd64.deb

**Comment by turtleDeng** [comment]
@sincsc 2.2 does not support REST API, please upgrade to 2.3-beta.3 after the version.

**Comment by sincsc** [comment]
@turtleDeng OK，I will have a try. But where can I config the HTTP basic auth username  and password in version 2.2,thanks.
