### ISSUE TITLE
last will message

### ISSUE THREAD

**Issue by sincsc** [emqtt/emqttd#1334]
#### Environment

- OS: ubuntu
- Erlang/OTP: 
- EMQ: 2.2

#### Description

I set will message on client, but when I remove the Internet line，it will wait ten more minutes can receive the will message for the mqtt server，why？thanks

**Comment by HJianBo** [comment]
@sincsc 
The server will conclude the connection having been broken, When not received message after 1.2*keepalive.

so, what the keepalive value is?

**Comment by sincsc** [comment]
@HJianBo I set keepalive value 60 seconds，and I try to change it to other values，for example 30 seconds, however it seems has no effect，I still receive the will message ten more minutes，so I am very confused，I don‘’t know why。Thanks

**Comment by HJianBo** [comment]
> The server will conclude the connection having been broken, When not received message after 1.2*keepalive*.

The previous reply was wrong, sorry...

The right value should be `Keepalive * backoff * 2`:
https://github.com/emqtt/emqttd/blob/419004a37af340ddb22d54cba2aa53d16a5ba746/etc/emq.conf#L198-L199

And, more accurate answer is `2 to 3 times of keepalive * backlog`:
https://github.com/emqtt/emqttd/blob/419004a37af340ddb22d54cba2aa53d16a5ba746/src/emqttd_keepalive.erl#L45-L59

**Comment by HJianBo** [comment]
@sincsc And I had tested it on EMQ v2.2.0. It works well!
The test details is:
1. Modify `etc/emq.conf` file with:
    - `log.console.level = debug`
2. Restart EMQ, and attacth to services: `./bin/emqttd attach`
2. The client named `iosclient` connect to server with:
    - keepalive=30
    - willTopic=test, payload='This is will message'
3. Switch iPhone to Flight-Mode

And were getting following logs (omitted some useless information):
<img width="846" alt="kp" src="https://user-images.githubusercontent.com/13825269/32932707-acd05836-cba3-11e7-92e5-051ed8622a89.png">

We can see  that the will message has been published, 84 seconds after the client connection broken

- The 84s is from `17:53:24-17:52:00 = 84s`
- And (2 * Keepalive * backoff) < 84, And  84 < (3 * Keepalive * backoff)

So, the keepalive mechanism works well!

**Comment by sincsc** [comment]
@HJianBo OK，I will try again，thank you very much!

**Comment by emqplus** [comment]
@sincsc You can tune the `mqtt.keepalive_backoff` to shorten the keepalive timeout. For example:

```
mqtt.keepalive_backoff = 0.75
```

**Comment by sincsc** [comment]
@emqplus I don't find it in etc/emqtt/emq.conf, so where can I tune it? thanks

**Comment by emqplus** [comment]
The `mqtt.keepalive_backoff` option is introduced in 2.3 release.

**Comment by sincsc** [comment]
@emqplus OK, thank you very much.
