### ISSUE TITLE
MQTT-3.3.1-10

### ISSUE THREAD

**Issue by Zhang-Xianglong** [emqtt/emqttd#1336]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

MQTT-3.3.1-10 said
A PUBLISH Packet with a RETAIN flag set to 1 and a payload contain zero bytes will be processed as normal by the Server and sent to Clients with a subscription matching the topic name. Additionally any existing retained message with the same topic name MUST be removed and any future subscribers for the topic will not received a retained message.

I tried sometimes, Retained message removed, but Server doesn't send it to clients. Can it be config somewhere?

*A description of the issue*

**Comment by turtleDeng** [comment]
@Zhang-Xianglong  emqttd version?

**Comment by Zhang-Xianglong** [comment]
emqttd-centos6.8-v2.2.0-1.el6.x86_64.rpm

**Comment by turtleDeng** [comment]
@Zhang-Xianglong The issue has been fixed in 2.3-beta.3 release.#1027

**Comment by Zhang-Xianglong** [comment]
thanks a lot
