### ISSUE TITLE
Any ETA on 2.3.0?

### ISSUE THREAD

**Issue by MarsWarrior** [emqtt/emqttd#1338]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

Looking at the previous release schedules, a release is about 1-2 weeks after rc2.
I see however that there ar still issues blocking the release of 2.3.

As we would really like to deploy 2.3 in the upcoming weeks with its new features, is there an ETA on the 2.3 release? Otherwise we should use the current 2.3rc2, but I don't know if that is wise...

**Comment by HJianBo** [comment]
@MarsWarrior The EMQ 2.3.0 has released now! You can download it at http://www.emqtt.io.
Thanks for your attention :)

**Comment by MarsWarrior** [comment]
;-)

Running since 5 days!

Thanx!
