### ISSUE TITLE
publish payload size

### ISSUE THREAD

**Issue by sincsc** [emqtt/emqttd#1346]
#### Environment

- OS: Ubuntu
- Erlang/OTP: 
- EMQ: 2.2

#### Description

I use emqtt publish to transfer picture, but when the picture's size more than 48kb, the picture will transfer  failed because of  "[Errno 104] Connection reset by peer", I don't know why。thanks

**Comment by HJianBo** [comment]
First, you should make sure the `Max Packet Size` configuration in `emq.conf`
```bash
## Max Packet Size Allowed, 64K by default.
mqtt.max_packet_size = 64KB
```
You can increase this value, but not over 256MB.

**And, We do not recommend that you use EMQ to transmit a single too large volume of messages**

**Comment by sincsc** [comment]
@HJianBo OK，I will have a try. I just use it to transmit file no more than 32MB. Is it OK?

**Comment by HJianBo** [comment]
@sincsc May works well, but not a good idea for transmit files!
