### ISSUE TITLE
{"code":107,"message":"params error"}

### ISSUE THREAD

**Issue by yyguo1986** [emqtt/emqttd#1347]
#### Environment

- OS: Windows
- Erlang/OTP: 
- EMQ: 2.3-rc.2

#### Description
I followed the doc (http://emqtt.io/docs/v2/rest.html#subscriptions) to create a subscribe without the client_id request parameter but got an error. I don't want to use ClientID auth. So how to set the request parameters? And what's all the request parameters of REST API for mqtt subscribe?

POST http://localhost:18083/api/v2/mqtt/subscribe HTTP/1.1
Host: localhost:18083
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Accept: application/json
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Referer: http://localhost:18083/
Authorization: Basic YWRtaW46cHVibGlj
Connection: keep-alive
Content-Length: 0

{
    "topic"    : "test",
    "qos"      : 1
}

HTTP/1.1 200 OK
Server: MochiWeb/1.0 (Any of you quaids got a smint?)
Date: Wed, 22 Nov 2017 09:47:06 GMT
Content-Type: application/json
Content-Length: 37

{"code":107,"message":"params error"}

**Comment by HJianBo** [comment]
@yyguo1986 
The **code: 107** is mean `missing request parameter`.  you can find  all of code description at http://emqtt.io/docs/v2/rest.html#error-code

In this case,  you must offer `client_id` parameter in the request. Because this parameter will tell to the server,  who have subscribe the topics.

For examples:
```
curl -v --basic -u admin:public -k http://localhost:80be -X POST -d '{"topic": "test", "qos": 1, "client_id": "test1"}'
```

**Comment by yyguo1986** [comment]
I got the 102 error if offering client_id parameter. Why?
{"code":102,"message":"Clientid: test1 not found"}

**Comment by HJianBo** [comment]
@yyguo1986 This operation is required that the session of client must have existed (you can find that on Dashboard)
https://github.com/emqtt/emqttd/blob/cb30f69a13617dea52fc8772b35e1cfa29898663/src/emqttd_mgmt.erl#L230-L242

**Comment by yyguo1986** [comment]
Got it. Thanks.
