### ISSUE TITLE
If client had connect to the mqtt server,but not subscribe any topic,can i publish a message to this client?

### ISSUE THREAD

**Issue by kansifang** [emqtt/emqttd#135]
If client had connect to the mqtt server,but not subscribe any topic,can i publish a message to this client?

**Comment by erylee** [comment]
Please check issue #111, Forced Subscription feature is supported in 0.8.0.

**Comment by erylee** [comment]
Any client will subscribe '$Q/client/ClientId' topic when connected successfully. So Other clients could publish messages to the client directly by '$Q/client/ClientId' topic.
