### ISSUE TITLE
Forcefully disconnect client.

### ISSUE THREAD

**Issue by Think7** [emqtt/emqttd#1350]
Greetings,

Is there a way / command to tell EMQ to forcefully / immediately / completely close a specific client's connection?

For security reasons, our application must be able instantly and completely revoke a user's access. Simply deactivating their account and modifying the ACL does not cause the EXISTING connection to drop which is problematic.

Thanks!

**Comment by HJianBo** [comment]
@Think7  The  command tool named`emqttd_ctl` provide more instructions to manage EMQ broker.

kick some client:
```bash
./bin/emqttd_ctl clients kick client_id
```

**Comment by emqplus** [comment]
Close the issue.

**Comment by Think7** [comment]
Thank you!

Was this in the docs? I searched and searched before posting :/

**Comment by emqplus** [comment]
@Think7  
CLI:  http://emqtt.io/docs/v2/commands.html
HTTP API: http://emqtt.io/docs/v2/rest.html#disconnect-a-specified-client-in-the-cluster
