### ISSUE TITLE
Docker Hub repo emqttd/emqttd out of date

### ISSUE THREAD

**Issue by Densaugeo** [emqtt/emqttd#1352]
#### Description

Is the emqttd/emqttd repo at [https://hub.docker.com/r/emqttd/emqttd/](https://hub.docker.com/r/emqttd/emqttd/) maintained by this project? It appears to still be on version 0.17.

**Comment by emqplus** [comment]
@Densaugeo No. We don't know who occupied the `emqttd` organization on docker hub;) 

Download the latest docker image from: http://emqtt.io/downloads/latest/docker

**Comment by Densaugeo** [comment]
Too bad someone took the name. Guess there's not much you can do about that, so I'll close this.
