### ISSUE TITLE
REST API - empty reply from server

### ISSUE THREAD

**Issue by 7wonders** [emqtt/emqttd#1353]
#### Environment

- OS: alpine:3.5 emq-docker:latest
- EMQ: 2.3.0

#### Description

Seem to get a totally empty reply on all api requests.

```
curl -v --basic -u admin:public -H "Content-Type: application/json" -k http://myip:8080/api/v2/monitoring/nodes
*   Trying myip...
* TCP_NODELAY set
* Connected to myip (myip) port 8080 (#0)
* Server auth using Basic with user 'admin'
> GET /api/v2/monitoring/nodes HTTP/1.1
> Host: myip:8080
> Authorization: Basic YWRtaW46cHVibGlj
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
>
* Empty reply from server
* Connection #0 to host myip left intact
curl: (52) Empty reply from server
```

**Comment by HJianBo** [comment]
Hi @7wonders  Could you have check the REST API listener address configuration in the `etc/emq.conf`? If you want to access the manage API by others host, you must set listener address to `0.0.0.0:8080`
```
listener.api.mgmt=0.0.0.0:8080
```

**Comment by emqplus** [comment]
@7wonders I changed the default configuration for management API listener. Close the issue.
