### ISSUE TITLE
Retained message cannot be cleaned

### ISSUE THREAD

**Issue by windhc** [emqtt/emqttd#1354]
#### Environment

- OS: centos7.3
- EMQ: 2.3.0

#### Description
- clientA往topic：abc发送一条保留消息，clientB收到这条保留消息，并发送一条空消息给topic：abc
- clientB自身又收到自己发送的这条空消息，然后又发送一条空消息出去，以此循环...
- 同样的代码在2.2.0可以正常运行，在2.3.0出现这个问题
- 代码

```
        // 发送消息 
        Server server =  new Server();
        server.message = new MqttMessage();
        server.message.setQos(2);
        server.message.setRetained(true);
        server.message.setPayload("".getBytes());
        server.publish(server.message);
```

```
    // 收到消息
    @Override
    public void messageArrived(String topic, MqttMessage message) throws Exception {
        // subscribe后得到的消息会执行到这里面
        System.out.println("client接收消息主题:"+topic);
        System.out.println("client接收消息Qos:"+message.getQos());
        System.out.println("client接收消息内容:"+new String(message.getPayload()));

        System.out.println("client 发送空消息 清除保留消息");
        MqttMessage message2 = new MqttMessage();
        message2.setQos(2);
        message2.setRetained(true);
        message2.setPayload("".getBytes());
        Client.publish(message2);
    }
```

*A description of the issue*

**Comment by HJianBo** [comment]
@windhc The server's behavior is correct!
Accord to MQTT-3.3.1-10:
>  A PUBLISH Packet with a RETAIN flag set to 1 and a payload containing zero bytes **will be processed as normal by the Server and sent to Clients** with a subscription matching the topic name. Additionally any existing retained message with the same topic name MUST be removed and any future subscribers for the topic will not receive a retained message

So, the server should send the empty message to client as normally, but we don't implement in previous version.
We has fixed this issue in EMQ 2.3.0. so your code show different behaviour than pervious version. sorry about that...

**Comment by windhc** [comment]
thank you very much

**Comment by emqplus** [comment]
Close the issue.
