### ISSUE TITLE
Not WebSocket: Upgrade = undefined Error

### ISSUE THREAD

**Issue by Tabrizian** [emqtt/emqttd#1373]
#### Environment

- OS: Linux
- Erlang/OTP: 
- EMQ: 2.7

#### Description 

When I try to connect to the WebSocket I get the following error:

```emqttd_http:handle_request:64 Not WebSocket: Upgrade = undefined```

It is configured to run behind Nginx reverse proxy with this configuration:

```nginx
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```

This configuration has worked for almost 4 months but suddenly I'm seeing this issue.

**Comment by emqplus** [comment]
@Tabrizian which release? The latest is R2.3.0, no 2.7 available still.

**Comment by Tabrizian** [comment]
Sorry, my mistake. It was 2.0.7.

**Comment by HJianBo** [comment]
Hi @Tabrizian It's seem the `Upgrade` field is incorrect!

Have you capture the HTTP Packet that is client to broker? 
And make sure the `Upgrade` field of HTTP Headers is `websocket`

**Comment by Tabrizian** [comment]
Sorry for the delay. I checked it and saw the upgrade field equals ```websocket```.

**Comment by HJianBo** [comment]
It's seems right. Could you please provide the captured Packet or file?

**Comment by Tabrizian** [comment]
Thank you very much. It seemed like there was a problem with the network.

**Comment by emqplus** [comment]
@Tabrizian Close the issue.

**Comment by polyglotm** [comment]
@Tabrizian could you explain more about the reason and solution?
I got an exact same error on AWS
