### ISSUE TITLE
Error while install

### ISSUE THREAD

**Issue by sustchenkov** [emqtt/emqttd#1381]
#### Environment

- OS - Windows7 x64: 
- Erlang/OTP: 
- EMQ v 2.2.0: 

#### Description

*A description of the issue*

![image](https://user-images.githubusercontent.com/4864528/33658120-9bff855c-da8c-11e7-9453-2bdb5821f8fb.png)

**Comment by HJianBo** [comment]
Hi @sustchenkov

It's seems some file not exist! But can't get any more details. 
Could you please provide more details information to diagnose this issue?

**Comment by sustchenkov** [comment]
[image: Встроенное изображение 1]

2017-12-25 4:37 GMT+03:00 HeeeJianBo <notifications@github.com>:
