### ISSUE TITLE
Question: Whether support forwarding specific topic content to one specific client of several clients which subscribed this topic 

### ISSUE THREAD

**Issue by yyguo1986** [emqtt/emqttd#1384]
Currently, I have one requirement: different clients subscribe same topic, only require one of these clients to consume this topic message. Whether the emq supports this or not? If yes, how to configure or use it?

**Comment by yyguo1986** [comment]
Same requirement with #416。
Is there any detailed document available to use it?

**Comment by HJianBo** [comment]
http://emqtt.io/docs/v2/advanced.html#shared-subscription
