### ISSUE TITLE
peer_cert_as_username does not seem to work

### ISSUE THREAD

**Issue by ztittle** [emqtt/emqttd#1385]
https://github.com/emqtt/emqttd/blob/85124242dfe4bc658d4bc0d809dd5bf4ab6b9a6c/etc/emq.conf#L483

I've setup TLS Client Authentication and was looking into getting the username from the CN, but this setting does not seem to do anything.

**Comment by emqplus** [comment]
@ztittle This feature will be ready in version 2.4-beta.1 next week.  Erlang/OTP consumes too many resources to handle TLS connections, so we plan to use HAProxy and the Proxy Protocol V2 to extract CN of X.509 certificate.

**Comment by emqplus** [comment]
@ztittle The X.509 certificate-based authentication has been improved in R2.3.2. Close the issue.
