### ISSUE TITLE
Can $SYS message result Contains the topic name?

### ISSUE THREAD

**Issue by w3yyb** [emqtt/emqttd#139]
such as 

$SYS/brokers/${node}/clients/count  : the result should be : clients/count:100.	 

this is useful , so I  not need subscribe a lot of $SYS topics,to get the specified result

**Comment by erylee** [comment]
This feature is invalid. Messages published to client contain topic name.

**Comment by w3yyb** [comment]
ok,,I forgot it,hehe.
