### ISSUE TITLE
e.q_auth_pgsql config unknown variable auth.pgsql.acl_nomatch

### ISSUE THREAD

**Issue by pritstift** [emqtt/emqttd#1395]
#### Environment

- OS: Alpine 3.5
- Erlang/OTP: 19
- EMQ: 2.3.1

#### Description

I am having problems getting the ACL running with the `emq_auth_pgsql` plugin. I wanted the plugin to refuse subscriptions and publications when no matching entry is found in the database. Therefore i added `auth.pgsql.acl_nomatch = deny` in the `etc/plugins/emq_auth_pgsql.conf` (according to the docs). I get the error ` [error] Conf file attempted to set unknown variable: auth.pgsql.acl_nomatch`.

Is there any other way to deny subscriptions and publications if no acl match is found?

**Comment by HJianBo** [comment]
Hi @pritstift You should set this field in the `etc/emq.conf` file only

```conf
## ACL nomatch
mqtt.acl_nomatch = deny
```

**Comment by pritstift** [comment]
That was the trick. I think that the docs should be updated accordingly. I can do this if you tell me where i find its repo.

**Comment by HJianBo** [comment]
@pritstift 
This configuration has appearances at http://emqtt.io/docs/v2/config.html#allow-anonymous-and-acl-file

**Comment by emqplus** [comment]
Close the issue.
