### ISSUE TITLE
Subscriber with wildcard topic does not receive retained messages with sub topic has $ sign

### ISSUE THREAD

**Issue by yossita** [emqtt/emqttd#1398]
#### Environment

- OS: Win10
- Erlang/OTP: 19
- EMQ: 2.3.1

#### Description
Given a publisher publishes a single retained message to a sub topic which start with '$' (i.e. `devices/dev_1/$online`), when a subscriber subscribes to a wildcard topic (i.e. `devices/dev_1/+`), it will not receive the retained message.

This scenario works as expected when the sub topic is without '$'. It is easily reproducible using the websockets page in the admin console.

**Comment by emqplus** [comment]
@yossita Fix the issue in PR: #1418
