### ISSUE TITLE
how to call rest api remotely ??

### ISSUE THREAD

**Issue by naruto0916** [emqtt/emqttd#1399]
#### Environment

- OS: CentOS 7
- EMQ: 2.2

Hello EMQ team:
I am trying EMQ and want to publish message by the rest api.
The AP doesn't run on the same machine with EMQ server.
I found the "HTTP Management API Listener" section of emq.conf has a listener.api.mgmt parameter.
I try to modify it as "0.0.0.0:8080" and restart EMQ server.
But, I still be refused once I call the rest API from other machine.
(I am sure the basic auth setting is correct and the port is open)
Have any things I miss??
Please give me some suggestion if I want to call the rest api remotely.
Thank you.

**Comment by turtleDeng** [comment]
@naruto0916 Has been fixed and released at v2.3.1
