### ISSUE TITLE
cluster can improve

### ISSUE THREAD

**Issue by w3yyb** [emqtt/emqttd#140]
One 'disc_copies' node and many 'ram_copies' nodes.

Topic trie tree will be copied to every clusterd node.

Subscribers to topic will be stored in each node and will not be copied.

第1个,其它是内存复制?如果机器down了,怎样保持高可用 .
第3个,订阅不复制到其它机器,这就会产生一个问题,如果用 lvs直接路由 负载均衡,就会 导致分次订阅的客户端再连接时,收不到某些消息.

**Comment by w3yyb** [comment]
一个客户端分次订阅6个主题用(192.168.6.1连接),他们分别路由到机器A和B上(A和B各收到3个订阅),  以后客户端 保持和 192.168.6.1连接,当publish6条消息时,这个客户端 只收到 3条消息.

**Comment by erylee** [comment]
1. Topic tree每台机器有副本，down机不影响数据
2. 连接、订阅是单节点，down机客户端必须重练其他节点，并重新订阅。
