### ISSUE TITLE
How to auto subscribe for other user

### ISSUE THREAD

**Issue by thuandh86** [emqtt/emqttd#1400]
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP: E(8.3)/O(19)
- EMQ: newest (2.3.1)

#### Description

I have a question, 
I want auto subscribe a topic for other user, ex: I am user A(is admin), i'll send a message (ex: 123,/topic/subscribe) to a special topic(call System topic, and only me can send message to this topic). Sys receive message, attach payload and auto subscribe user(123) to topic(topic/subscribe). I try use mqttd:subscribe(Topic(topic/subscribe), ClientId(123)) and return success, i show in api (http://host:8080/api/subscriptions/123) have subscribe topic (topic/subscribe) but user(123) not receive message if i send a message to topic (topic/subscribe).
I have any question:
1. Sys allow a user(special) can doing this? have poblem?
2. Why user(123) have subscribe in (http://host:8080/api/subscriptions/123) but send message to topic, this user not receive message?
3. when i disconnected, in statistic subscribe topic of user(123) disable topic (topic/subscribe). this topic(topic/subscribe) create/delete by my session? how to i can create with session of user(123)?
Thanks

P/S: I write a plugin and hook for do it.

**Comment by turtleDeng** [comment]
@thuandh86  REST API http://emqtt.com/docs/v2/rest.html#id18

**Comment by thuandh86** [comment]
Can you tell me more? i use mqttd:subcribe in plugin  subscribe for other user but  user not subcribe topic although in api of other user is had subscribed

**Comment by thuandh86** [comment]
I used emqttd_sm:lookup_session for look clienid session and use emqttd_session:subscribe for auto subcribe for other user, it's success. 
thanks, closed topic.
