### ISSUE TITLE
REST API Username / Password Config

### ISSUE THREAD

**Issue by Think7** [emqtt/emqttd#1401]
Hello,

Where can the username and password for the REST API be configured? The default login information appears to be u:admin p:public however i'm unable to find where this is set in the configs.

Another user asks a similar question in the last post here: https://github.com/emqtt/emqttd/issues/1274 and did not receive a response.

The docs mention how to authenticate with the REST api but nothing about the configuration for it.

**Comment by turtleDeng** [comment]
@Think7 http://emqtt.io/docs/v2/commands.html#admins

**Comment by pritstift** [comment]
Would it be possible to add admin users in a configuration file?

**Comment by HJianBo** [comment]
Could not now!  The admin users will be added to EMQ by CLIs only

**Comment by pritstift** [comment]
What about passing it through command line argument when starting the broker using emqttd?

**Comment by HJianBo** [comment]
After the emqttd server has started successfully, you can add it.
i.e:
```
./bin/emqttd_ctl admins add root2 public2
```

The doc http://emqtt.io/docs/v2/commands.html#admins may be help you

**Comment by HJianBo** [comment]
Hi, @Think7 @pritstift Sorry too late reply. You can config the default Username/Password in the `etc/plugins/emq_dashboard.conf` before v2.3.3. (published on 11 Jan) 

Close it now. if has any problems reopen it!

**Comment by khoshbin** [comment]
I changed dashboard admin user and also default password in etc/plugins/emq_dashboard.conf
But rest api password has not chnaged yet
