### ISSUE TITLE
CRASH REPORT Process <0.1384.0> with 0 neighbours exited with reason: bad argument in inet_tcp:listen/2 line 160

### ISSUE THREAD

**Issue by akhan4u** [emqtt/emqttd#1410]
#### Environment

- OS: Red Hat Enterprise Linux Server 7.4 (Maipo)
- Erlang/OTP: 
- EMQ: emqttd-2.3-1 

#### Description

Getting the Crash error on startup of EMQ. 
=====
 LOGGING STARTED Mon Dec 25 09:45:21 UTC 2017

Exec: /usr/lib64/emqttd/erts-9.0/bin/erlexec -boot /usr/lib64/emqttd/releases/2.3.1/emqttd -mode embedded -boot_var ERTS_LIB_DIR /usr/lib64/emqttd/erts-9.0/../lib -mnesia dir "/var/lib/emqttd/mnesia/emq@127.0.0.1" -config /var/lib/emqttd/configs/app.2017.12.25.09.45.22.config -args_file /var/lib/emqttd/configs/vm.2017.12.25.09.45.22.args -vm_args /var/lib/emqttd/configs/vm.2017.12.25.09.45.22.args -- console^M
Root: /usr/lib64/emqttd^M
/usr/lib64/emqttd^M
starting emqttd on node 'emq@127.0.0.1'^M
emqttd ctl is starting...[ok]^M
emqttd hook is starting...[ok]^M
emqttd router is starting...[ok]^M
emqttd pubsub is starting...[ok]^M
emqttd stats is starting...[ok]^M
emqttd metrics is starting...[ok]^M
emqttd pooler is starting...[ok]^M
emqttd trace is starting...[ok]^M
emqttd client manager is starting...[ok]^M
emqttd session manager is starting...[ok]^M
emqttd session supervisor is starting...[ok]^M
emqttd wsclient supervisor is starting...[ok]^M
emqttd broker is starting...[ok]^M
emqttd alarm is starting...[ok]^M
emqttd mod supervisor is starting...[ok]^M
emqttd bridge supervisor is starting...[ok]^M
emqttd access control is starting...[ok]^M
emqttd system monitor is starting...[ok]^M
emqttd 2.3.1 is running now^M
Eshell V9.0  (abort with ^G)^M
(emq@127.0.0.1)1> Load emq_mod_presence module successfully.^M
(emq@127.0.0.1)1> dashboard:http listen on 0.0.0.0:18089 with 2 acceptors.^M
(emq@127.0.0.1)1> 09:45:24.297 [error] CRASH REPORT Process <0.1384.0> with 0 neighbours exited with reason: bad argument in inet_tcp:listen/2 line 160^M^M
(emq@127.0.0.1)1> 09:45:24.297 [error] Autocluster exception: {badmatch,{error,{{'EXIT',{{badmatch,{error,{badarg,{child,undefined,listener,{esockd_listener,start_link,['mqtt:tcp',1000000,[{connopts,[]},{sockopts,[binary,{packet,raw},{reuseaddr,true},{backlog,1024},{nodelay,true}]},{acceptors,8},{max_clients,1024}],<0.1383.0>,{gen_logger,error_logger_logger,2}]},transient,4294967295,worker,[esockd_listener]}}}},[{esockd_listener_sup,start_link,4,[{file,"src/esockd_listener_sup.erl"},{line,62}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}},{child,undefined,{listener_sup,{'mqtt:tcp',1000000}},{esockd_listener_sup,start_link,['mqtt:tcp',1000000,[{connopts,[]},{sockopts,[binary,{packet,raw},{reuseaddr,true},{backlog,1024},{nodelay,true}]},{acceptors,8},{max_clients,1024}],{emqttd_client,start_link,[[{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,1024},{max_packet_size,65536},{keepalive_backoff,1.25}]]}]},transient,infinity,supervisor,[esockd_listener_sup]}}}}^M^M
(emq@127.0.0.1)1>

Also getting the following in the crash log:
======
2017-12-25 09:45:24 =CRASH REPORT====
  crasher:
    initial call: esockd_listener:init/1
    pid: <0.1384.0>
    registered_name: []
    exception exit: {badarg,[{inet_tcp,listen,2,[{file,"inet_tcp.erl"},{line,160}]},{esockd_listener,init,1,[{file,"src/esockd_listener.erl"},{line,78}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.1381.0>,esockd_sup,<0.1160.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1381.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 387
  neighbours:

Can someone help me in understanding this. We are evaluating the performance of MQTT broker's. 
I am following this Link: http://emqtt.io/docs/v2/getstarted.html#one-million-connections
Please let me know if i am doing anything wrong in this.

**Comment by HJianBo** [comment]
Hi, @akhan4u The error caused by an invalid listening port. (As you can see from the crash log, the port you configured is 10000)

So, please make sure the listening port is correct

**Comment by sivasindhur** [comment]
im getting the below issue

2020-07-21 04:21:51 =ERROR REPORT====
** Generic server <0.8883.53> terminating
** Last message in was {'EXIT',<0.8898.53>,heartbeat_timeout}
** When Server state == {state,undefined,undefined,undefined,undefined,{<<"/">>,<<"multi_request_shovel">>},dynamic,#{ack_mode => on_confirm,dest => #{current => {<0.8898.53>,<0.8909.53>,<<"amqp://10.128.164.152/prod.interop-pca">>},dest_exchange => <<"icms-mirror">>,fields_fun => #Fun<rabbit_shovel_parameters.11.64789379>,module => rabbit_amqp091_shovel,props_fun => #Fun<rabbit_shovel_parameters.12.64789379>,resource_decl => #Fun<rabbit_shovel_parameters.10.64789379>,unacked => #{},uris => ["amqp://shovel_user:CZTB87VK4zgKDQTA2Pmv@10.128.164.152/prod.interop-pca","amqp://shovel_user:CZTB87VK4zgKDQTA2Pmv@10.128.164.153/prod.interop-pca","amqp://shovel_user:CZTB87VK4zgKDQTA2Pmv@10.128.164.154/prod.interop-pca"]},name => <<"multi_request_shovel">>,reconnect_delay => 10,shovel_type => dynamic,source => #{current => {<0.8886.53>,<0.8895.53>,<<"amqp://10.32.1.157">>},delete_after => never,module => rabbit_amqp091_shovel,prefetch_count => 1000,queue => <<"cv_claim">>,remaining => unlimited,remaining_unacked => unlimited,resource_decl => #Fun<rabbit_shovel_parameters.14.64789379>,source_exchange_key => <<>>,uris => ["amqp://shovel_user:CZTB87VK4zgKDQTA2Pmv@10.32.1.155","amqp://shovel_user:CZTB87VK4zgKDQTA2Pmv@10.32.1.156","amqp://shovel_user:CZTB87VK4zgKDQTA2Pmv@10.32.1.157"]}},undefined,undefined,undefined,undefined,undefined}
** Reason for termination ==
** heartbeat_timeout
2020-07-21 04:21:51 =CRASH REPORT====
  crasher:
    initial call: rabbit_shovel_worker:init/1
    pid: <0.8883.53>
    registered_name: []
    exception exit: {heartbeat_timeout,[{gen_server2,terminate,3,[{file,"src/gen_server2.erl"},{line,1172}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.1466.0>,<0.1462.0>,rabbit_shovel_dyn_worker_sup_sup,rabbit_shovel_sup,<0.1458.0>]
    message_queue_len: 3
    messages: [{'EXIT',<0.8895.53>,normal},{'EXIT',<0.8909.53>,shutdown},{'EXIT',<0.8886.53>,{shutdown,normal}}]
    links: [<0.1466.0>]
    dictionary: [{rand_seed,{#{bits => 58,jump => #Fun<rand.21.53802439>,next => #Fun<rand.18.53802439>,type => exsss,uniform => #Fun<rand.19.53802439>,uniform_n => #Fun<rand.20.53802439>},[80211918345976195|3781892947583643]}},{gen_server_call_timeout,60000}]
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 10877
  neighbours:
2020-07-21 04:21:51 =SUPERVISOR REPORT====
     Supervisor: {<0.1466.0>,rabbit_shovel_dyn_worker_sup}
     Context:    child_terminated
     Reason:     heartbeat_timeout
     Offender:   [{pid,<0.8883.53>},{name,{<<"/">>,<<"multi_request_shovel">>}},{mfargs,{rabbit_shovel_worker,start_link,[dynamic,{<<"/">>,<<"multi_request_shovel">>},[{<<"ack-mode">>,<<"on-confirm">>},{<<"dest-add-forward-headers">>,false},{<<"dest-exchange">>,<<"icms-mirror">>},{<<"dest-protocol">>,<<"amqp091">>},{<<"dest-uri">>,[<<"amqp://shovel_user:CZTB87VK4zgKDQTA2Pmv@10.128.164.152/prod.interop-pca">>,<<"amqp://shovel_user:CZTB87VK4zgKDQTA2Pmv@10.128.164.153/prod.interop-pca">>,<<"amqp://shovel_user:CZTB87VK4zgKDQTA2Pmv@10.128.164.154/prod.interop-pca">>]},{<<"reconnect-delay">>,10},{<<"src-delete-after">>,<<"neve:
