### ISSUE TITLE
MQTT detected network error 'closed'

### ISSUE THREAD

**Issue by kansifang** [emqtt/emqttd#142]
当手机锁屏后服务器出现如下如下log后就断开与客户端的链接了：

MQTT detected network error 'closed'

手机端的网络一开启的而且链接emqtt服务器的service也是开启的,但是不知道什么原因服务器就主动断开了客户端的链接？

**Comment by erylee** [comment]
1. MQTT detected network error 'closed', 先检查服务端是否有keepalive_timeout的日志，如没有是客户端主动关闭了连接

2. Android下你mqtt客户端是否写成Android的Service？如果Activity中建立mqtt连接，一担屏幕切换会自动断开
