### ISSUE TITLE
windows run error 

### ISSUE THREAD

**Issue by EagleSmith** [emqtt/emqttd#1424]
#### Environment

- OS: Windows server 2012
- Erlang/OTP: 
- EMQ: Emqtt 2.3.1

#### Description

kernel-poll not supported; "K" parameter ignored
Erlang/OTP 19 [erts-8.3] [64-bit] [smp:2:2] [async-threads:32]

starting emqttd on node 'emq@127.0.0.1'
emqttd ctl is starting...[ok]
emqttd hook is starting...[ok]
emqttd router is starting...[ok]
emqttd pubsub is starting...[ok]
emqttd stats is starting...[ok]
emqttd metrics is starting...[ok]
emqttd pooler is starting...[ok]
emqttd trace is starting...[ok]
emqttd client manager is starting...[ok]
emqttd session manager is starting...[ok]
emqttd session supervisor is starting...[ok]
emqttd wsclient supervisor is starting...[ok]
emqttd broker is starting...[ok]
emqttd alarm is starting...[ok]
emqttd mod supervisor is starting...[ok]
emqttd bridge supervisor is starting...[ok]
emqttd access control is starting...[ok]
emqttd system monitor is starting...[ok]
emqttd 2.3.1 is running now
Eshell V8.3  (abort with ^G)
(emq@127.0.0.1)1> Load emq_mod_presence module successfully.
dashboard:http listen on 0.0.0.0:18083 with 2 acceptors.
mqtt:tcp listen on 127.0.0.1:11883 with 16 acceptors.
mqtt:tcp listen on 0.0.0.0:1883 with 16 acceptors.
mqtt:ws listen on 0.0.0.0:8083 with 4 acceptors.
mqtt:ssl listen on 0.0.0.0:8883 with 16 acceptors.
mqtt:wss listen on 0.0.0.0:8084 with 4 acceptors.
mqtt:api listen on 0.0.0.0:8080 with 4 acceptors.
09:34:32.826 [error] CRASH REPORT Process <0.340.0> with 0 neighbours exited with reason: no match of right hand value {error,econnrefused} in mysql:init/1 line 484 in gen_server:init_it/6 line 352
09:34:32.826 [error] load plugin emq_auth_mysql error, cannot start app emq_auth_mysql for {bad_return,{{emq_auth_mysql_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emq_auth_mysql,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{{badmatch,{error,econnrefused}},[{mysql,init,1,[{file,"d:/emqtt/v2.3/2.3.1/emq-relx/deps/mysql/src/mysql.erl"},{line,484}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}}}}}}},[{emq_auth_mysql_app,start,2,[{file,"d:/emqtt/v2.3/2.3.1/emq-relx/deps/emq_auth_mysql/src/emq_auth_mysql_app.erl"},{line,33}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}]}}}}
09:34:32.826 [error] Supervisor {<0.338.0>,ecpool_worker_sup} had child {worker,1} started with ecpool_worker:start_link(emq_auth_mysql, 1, emq_auth_mysql_cli, [{pool_size,8},{auto_reconnect,1},{host,"127.0.0.1"},{port,3306},{user,[]},{password,[]},{database,...},...]) at undefined exit with reason no match of right hand value {error,econnrefused} in mysql:init/1 line 484 in context start_error
09:34:32.826 [error] CRASH REPORT Process <0.339.0> with 0 neighbours exited with reason: no match of right hand value {error,econnrefused} in mysql:init/1 line 484 in gen_server:init_it/6 line 344
09:34:32.826 [error] Supervisor {<0.336.0>,ecpool_pool_sup} had child worker_sup started with ecpool_worker_sup:start_link(emq_auth_mysql, emq_auth_mysql_cli, [{pool_size,8},{auto_reconnect,1},{host,"127.0.0.1"},{port,3306},{user,[]},{password,[]},{database,...},...]) at undefined exit with reason {shutdown,{failed_to_start_child,{worker,1},{{badmatch,{error,econnrefused}},[{mysql,init,1,[{file,"d:/emqtt/v2.3/2.3.1/emq-relx/deps/mysql/src/mysql.erl"},{line,484}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}} in context start_error
09:34:32.826 [error] Supervisor emq_auth_mysql_sup had child emq_auth_mysql started with ecpool:start_pool(emq_auth_mysql, emq_auth_mysql_cli, [{pool_size,8},{auto_reconnect,1},{host,"127.0.0.1"},{port,3306},{user,[]},{password,[]},{database,...},...]) at undefined exit with reason {shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{{badmatch,{error,econnrefused}},[{mysql,init,1,[{file,"d:/emqtt/v2.3/2.3.1/emq-relx/deps/mysql/src/mysql.erl"},{line,484}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}}} in context start_error
09:34:32.826 [error] CRASH REPORT Process <0.333.0> with 0 neighbours exited with reason: no match of right hand value {error,{shutdown,{failed_to_start_child,emq_auth_mysql,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{{badmatch,{error,econnrefused}},[{mysql,init,1,[{file,"d:/emqtt/v2.3/2.3.1/emq-relx/deps/mysql/src/mysql.erl"},{line,484}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}}}}}} in emq_auth_mysql_app:start/2 line 33 in application_master:init/4 line 134

**Comment by HJianBo** [comment]
Hi, @EagleSmith It seems the `emq_auth_mysql` plugins start failure. Because It can't connect to MySQL services! Please make sure the MySQL server has started and the configuration of `emq_auth_mysql` is right

**Comment by EagleSmith** [comment]
hi HJianBo,I use dashboard to configure Mysql to start success,the windows service can not start ,error code 1067 Unexpected termination of process

**Comment by EagleSmith** [comment]
thanks

**Comment by HJianBo** [comment]
@EagleSmith 
1. First, Please make sure the MySQL can be connected using correct IP Address, Port, username, password, etc.
2. And, Make sure the configuration of `emq_auth_mysql.conf` is right?

If it does not works well still, please provide more details reproduce step, log or configurations.

It's very helpful to analyze the error reason! Thanks!

**Comment by EagleSmith** [comment]
it's working now ,but the windows service can not run?error code is 1607.
emqttd_2.3.1: Could not start erlang machine
emqttd_2.3.1: Not enough parameters for erlang service.
