### ISSUE TITLE
2.3.1 emqttd not starting properly at reboot. getting emfile error

### ISSUE THREAD

**Issue by hbli** [emqtt/emqttd#1433]
#### Environment

- OS: Ubuntu  14.04
- Erlang/OTP: using the default binary
- EMQ: 2.3.1

#### Description

I am using version 2.3.1 binary for ubuntu 14.40 64 bit. I am following the guide to create /etc/init.d/emqttd service to let emqttd run after a server reboot. So after the reboot, emqttd starts itself. Then I run the bench mark tool.

./emqttd_bench_sub -c 50000 -t bench/%i -q2

I am get emfile error after ~990 connected clients. The kernel was configured following the Tuning Guide. If I manually start emqttd, I don't have this problem. I can at least reach 5000 clients after the manual start.

What's wrong with the auto start script?

**Comment by HJianBo** [comment]
@hbli The error `emfile` is mean `Too many open files`.

So, please make sure the limit in the system of running `emqttd_bench_sub ` more than `50000`. You can check it with:
```
ulimit -n
```
or, increase temporarily it with `ulimit -n 1048576`

**Comment by hbli** [comment]
It does show ulimit -n 1048576.
The problem happens only during the reboot. If you start emqtt manually, no emfile error is reported.

**Comment by hbli** [comment]
It seems to me that the kernel is not fully initialized before the emqttd is launched.

**Comment by emqplus** [comment]
@hbli See http://emqtt.io/docs/v2/tune.html. Closed the issue.
