### ISSUE TITLE
Where is information on the Enterprise version?

### ISSUE THREAD

**Issue by Eric24** [emqtt/emqttd#1435]
I've sent a few emails to contact@emqtt.io and feng@emqtt.io, with no response. Who should I contact and/or where can I find information on the Enterprise version of eMQTT?

**Comment by emqplus** [comment]
@Eric24, Please contact [zhengyu.pan@emqtt.io](mailto: zhengyu.pan@emqtt.io) who is responsible for EMQ global marketing.

@zhengyupan Please contact @Eric24, Thanks.
