### ISSUE TITLE
 Question:mqttjs login emqtt using emq-auth-mongo

### ISSUE THREAD

**Issue by duchieu95** [emqtt/emqttd#1446]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*
I use the node js as API but mqtt login error encountered. bad username or password. password encryption
[bcrypt](https://www.npmjs.com/package/bcrypt-nodejs)

**Comment by HJianBo** [comment]
Repeated issue at https://github.com/emqtt/emq-auth-mongo/issues/104
