### ISSUE TITLE
Load balancer for EMQ broker with 2 cluster

### ISSUE THREAD

**Issue by Bakkiyaraj** [emqtt/emqttd#1448]
#### Environment

- OS: Windows
- Erlang/OTP: 
- EMQ: 2.3.1

#### Description

I have 2 cluster setup and running with name node1@aaa and node2@bbb. What is the recommended load balancer for cluster design ?

**Comment by emqplus** [comment]
@Bakkiyaraj See: http://emqx-enterprise-docs-en.readthedocs.io/en/latest/deploy.html#load-balancer-lb

**Comment by Bakkiyaraj** [comment]
@emqplus Thanks for the document.
