### ISSUE TITLE
ACL rules

### ISSUE THREAD

**Issue by chcmq** [emqtt/emqttd#1452]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description
How to write an ACL rule: the client can only receive messages on a topic, but cannot send messages?
*A description of the issue*

**Comment by HJianBo** [comment]
See: http://emqtt.io/docs/v2/guide.html#acl

An example may be:
```
{allow, {user, "test"}, subscribe, ["topic1"]}.
{deny, {user, "test"}, publish, ["topic1"]}.
```

It's mean the user named`test` can subscribe `topic1` but does not publish message to `topic1`
