### ISSUE TITLE
Dashboard to launch emq_auth_mysql for error 102

### ISSUE THREAD

**Issue by chcmq** [emqtt/emqttd#1455]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description
The emq_auth_mysql plug-in has been configured, but after the launch in the Dashboard background, 102 errors occurred. What's going on here?
*A description of the issue*

**Comment by JiangLiguoME** [comment]
I got the same problem with you.
I check the log then found that the emq server show:
"Access denied for user ''@'localhost' (using password: NO)"
But my username and password is correct in the emq_auth_mysql
