### ISSUE TITLE
deploy settings to every node in cluster

### ISSUE THREAD

**Issue by atomrocktech** [emqtt/emqttd#1456]
#### Environment

- OS:  Ubuntu 16.04 Server
- Erlang/OTP:  OTP19
- EMQ:  v2.3.3

#### Description
I have 2 different servers as 2 nodes in the cluster, 
I'm wondering that if I change the settings on node 1 for example, 
does this setting will be deployed to node 2 automatically? or need to be done manually?

**Comment by emqplus** [comment]
@atomrocktech No. Each node should be configured separately. You can copy one `emq.conf` to different nodes and use ENV to setting the `node.name`.
