### ISSUE TITLE
Unable to enable MySQL plug-in authentication: there were 102 errors

### ISSUE THREAD

**Issue by chcmq** [emqtt/emqttd#1458]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*
Configure emq_auth_mysq.conf file according to the official document. I am configuring the address on my server. What was the reason for the error after the CMD was executed?
error:
:\emqttd\bin>emqttd_ctl plugins load emq_auth_mysql
load plugin error: {emq_auth_mysql,
                   {bad_return,
                    {{emq_auth_mysql_app,start,[normal,[]]},
                     {'EXIT',
                      {{badmatch,
                        {error,
                         {shutdown,
                          {failed_to_start_child,emq_auth_mysql,
                           {shutdown,
                            {failed_to_start_child,worker_sup,
                             {shutdown,
                              {failed_to_start_child,
                               {worker,1},
                               {1045,<<"28000">>,
                                <<"Access denied for user ''@'192.168.12.5' (us
ng password: NO)">>}}}}}}}}},
                       [{emq_auth_mysql_app,start,2,
                         [{file,
                           "d:/emqtt/v2.3/2.3.1/emq-relx/deps/emq_auth_mysql/sr

**Comment by emqplus** [comment]
@chcmq  check the `username` and `password` options in emq_auth_mysql.conf:

```
## MySQL username.
##
## Value: String
auth.mysql.username =

## MySQL password.
##
## Value: String
auth.mysql.password =
```

**Comment by chcmq** [comment]
I just use my already configured, and have successfully logged in with the username and password phpmyadmin, since the official document is the default is the local IP 127.0.0.1, I changed to my own IP address of the server, in addition to the official documents are only need to configure the emq_auth_mysql. Outside the conf file also need to configure?

**Comment by wangh09** [comment]
I have the same issue showing that the auth.mysql.* in the conf file don't work.  my conf:

**Comment by wangh09** [comment]
auth.mysql.server = 52.80.12.323:3306
auth.mysql.username=xxxx
auth.mysql.password=xxxx

**Comment by wangh09** [comment]
Found that the service need to be started when the plugin settings was changed.
