### ISSUE TITLE
EMQ 2.3.3: retain bit is not set when publishing to clients (when it should be set).

### ISSUE THREAD

**Issue by victorclaessen** [emqtt/emqttd#1461]
#### Environment

- OS:  Debian 9 x64
- Erlang/OTP: 19
- EMQ: 2.3.3

#### Description

I recently upgraded my cluster to release version 2.3.3, and it appears that in this version, **the retain flag is never sent to clients**.

Proof:
```
claessen@brokernode1:~$ mosquitto_pub -t "test/topic" -m "testvalue" -r
claessen@brokernode1:~$ mosquitto_sub -t "test/topic" -v -R -C 1
test/topic testvalue
```
Or in words: 

* I publish to the topic "test/topic" a message "testvalue" _with the retain bit set_.
* I subscribe to the topic "test/topic" and ask (_-R_) that retained messages not be shown, and quit after receiving one message (-C 1).
* I receive the message "testvalue" (that was sent **with** the retain bit set) back **without** the retain bit, and therefore mosquitto_sub outputs the message to my terminal. Any messages with the retain bit are not shown because of the _-R_ option.
* I have confirmed this with the MQTT.fx client.
* (Note that there are no other subscribers/publishers on this topic on my system.)

I think that the retain bit on that message should have been set, because:

> When sending a PUBLISH Packet to a Client the Server MUST set the RETAIN flag to 1 if a message is sent as a result of a new subscription being made by a Client [MQTT-3.3.1-8].

I suspect that this is a bug.

**Comment by HJianBo** [comment]
https://github.com/emqtt/emqttd/blob/a992b50308aec74814f376c19d7f7aa290614a7f/src/emqttd_protocol.erl#L566-L569

**Comment by HJianBo** [comment]
Yes, This is a BUG. It caused by:
https://github.com/emqtt/emqttd/blob/a992b50308aec74814f376c19d7f7aa290614a7f/src/emqttd_protocol.erl#L566-L569

**Comment by HJianBo** [comment]
#1293

**Comment by emqplus** [comment]
@victorclaessen Fixed the issue in the `emq-retainer` and `emqttd` projects. The `emq_protocol` module will not clean the `retain` flag for a new subscription now.

**Comment by victorclaessen** [comment]
Thanks!
