### ISSUE TITLE
Websockets connection crashes

### ISSUE THREAD

**Issue by TheBeachMaster** [emqtt/emqttd#1464]
#### Environment

- OS: Centos 7
- Erlang/OTP: 20
- EMQ: 2.3.3

#### Description

Webscokets connection crashes internally

### A snippet of crash log  `crash.log` under `/var/log/emqttd`
  
`2018-01-24 11:03:22 =ERROR REPORT====
Error in process <0.26372.0> on node 'emq@127.0.0.1' with exit value:
{{invalid_proxy_info,<<"GET /mqtt HTTP/1.1\r\n">>},[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{li
ne,122}]},{mochiweb_http,init,2,[{file,"src/mochiweb_http.erl"},{line,48}]}]}
2018-01-24 11:03:22 =SUPERVISOR REPORT====
     Supervisor: 'esockd_connection_sup - <0.1403.0>'
     Context:    connection_crashed
     Reason:     {{invalid_proxy_info,<<"GET /mqtt HTTP/1.1\r\n">>},[{esockd_connection,upgrade,1,[{file,"src/esockd_con
nection.erl"},{line,122}]},{mochiweb_http,init,2,[{file,"src/mochiweb_http.erl"},{line,48}]}]}
     Offender:   [{pid,<0.26372.0>},{name,connection},{mfargs,{mochiweb_http,start_link,[{emqttd_ws,handle_request,[]}]}
}]`

`2018-01-24 11:03:28 =ERROR REPORT====
Error in process <0.26373.0> on node 'emq@127.0.0.1' with exit value:
{{invalid_proxy_info,<<"GET /mqtt HTTP/1.1\r\n">>},[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{li
ne,122}]},{mochiweb_http,init,2,[{file,"src/mochiweb_http.erl"},{line,48}]}]}
2018-01-24 11:03:28 =SUPERVISOR REPORT====
     Supervisor: 'esockd_connection_sup - <0.1403.0>'
     Context:    connection_crashed
     Reason:     {{invalid_proxy_info,<<"GET /mqtt HTTP/1.1\r\n">>},[{esockd_connection,upgrade,1,[{file,"src/esockd_con
nection.erl"},{line,122}]},{mochiweb_http,init,2,[{file,"src/mochiweb_http.erl"},{line,48}]}]}
     Offender:   [{pid,<0.26373.0>},{name,connection},{mfargs,{mochiweb_http,start_link,[{emqttd_ws,handle_request,[]}]}
}]` 

### A snippet of `info.log`  

`2018-01-24 11:19:08.522 [error] <0.1403.0> Supervisor 'esockd_connection_sup - <0.1403.0>' had child connection started
with mochiweb_http:start_link({emqttd_ws,handle_request,[]}) at <0.26607.0> exit with reason {invalid_proxy_info,<<"GET
/mqtt HTTP/1.1\r\n">>} in esockd_connection:upgrade/1 line 122 in context connection_crashed
2018-01-24 11:19:11.687 [error] <0.1403.0> Supervisor 'esockd_connection_sup - <0.1403.0>' had child connection started
with mochiweb_http:start_link({emqttd_ws,handle_request,[]}) at <0.26608.0> exit with reason {invalid_proxy_info,<<"GET
/mqtt HTTP/1.1\r\n">>} in esockd_connection:upgrade/1 line 122 in context connection_crashed
2018-01-24 11:19:11.688 [error] emulator Error in process <0.26608.0> on node 'emq@127.0.0.1' with exit value:
{{invalid_proxy_info,<<"GET /mqtt HTTP/1.1\r\n">>},[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{li
ne,122}]},{mochiweb_http,init,2,[{file,"src/mochiweb_http.erl"},{line,48}]}]}
2018-01-24 11:19:17.719 [error] <0.1403.0> Supervisor 'esockd_connection_sup - <0.1403.0>' had child connection started
with mochiweb_http:start_link({emqttd_ws,handle_request,[]}) at <0.26609.0> exit with reason {invalid_proxy_info,<<"GET
/mqtt HTTP/1.1\r\n">>} in esockd_connection:upgrade/1 line 122 in context connection_crashed
2018-01-24 11:19:17.719 [error] emulator Error in process <0.26609.0> on node 'emq@127.0.0.1' with exit value:
{{invalid_proxy_info,<<"GET /mqtt HTTP/1.1\r\n">>},[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{li
ne,122}]},{mochiweb_http,init,2,[{file,"src/mochiweb_http.erl"},{line,48}]}]}
2018-01-24 11:19:21.133 [error] emulator Error in process <0.26610.0> on node 'emq@127.0.0.1' with exit value:
{{invalid_proxy_info,<<"GET /mqtt HTTP/1.1\r\n">>},[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{li
ne,122}]},{mochiweb_http,init,2,[{file,"src/mochiweb_http.erl"},{line,48}]}]}
2018-01-24 11:19:21.133 [error] <0.1403.0> Supervisor 'esockd_connection_sup - <0.1403.0>' had child connection started
with mochiweb_http:start_link({emqttd_ws,handle_request,[]}) at <0.26610.0> exit with reason {invalid_proxy_info,<<"GET
/mqtt HTTP/1.1\r\n">>} in esockd_connection:upgrade/1 line 122 in context connection_crashed
2018-01-24 11:19:27.955 [error] emulator Error in process <0.26611.0> on node 'emq@127.0.0.1' with exit value:
{{invalid_proxy_info,<<"GET /mqtt HTTP/1.1\r\n">>},[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{li
ne,122}]},{mochiweb_http,init,2,[{file,"src/mochiweb_http.erl"},{line,48}]}]}
2018-01-24 11:19:27.955 [error] <0.1403.0> Supervisor 'esockd_connection_sup - <0.1403.0>' had child connection started
with mochiweb_http:start_link({emqttd_ws,handle_request,[]}) at <0.26611.0> exit with reason {invalid_proxy_info,<<"GET
/mqtt HTTP/1.1\r\n">>} in esockd_connection:upgrade/1 line 122 in context connection_crashed
2018-01-24 11:19:31.377 [error] <0.1403.0> Supervisor 'esockd_connection_sup - <0.1403.0>' had child connection started
with mochiweb_http:start_link({emqttd_ws,handle_request,[]}) at <0.26612.0> exit with reason {invalid_proxy_info,<<"GET
/mqtt HTTP/1.1\r\n">>} in esockd_connection:upgrade/1 line 122 in context connection_crashed
2018-01-24 11:19:31.377 [error] emulator Error in process <0.26612.0> on node 'emq@127.0.0.1' with exit value:
{{invalid_proxy_info,<<"GET /mqtt HTTP/1.1\r\n">>},[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{li
ne,122}]},{mochiweb_http,init,2,[{file,"src/mochiweb_http.erl"},{line,48}]}]}
2018-01-24 11:19:34.402 [error] emulator Error in process <0.26613.0> on node 'emq@127.0.0.1' with exit value:
{{invalid_proxy_info,<<"GET /mqtt HTTP/1.1\r\n">>},[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{li
ne,122}]},{mochiweb_http,init,2,[{file,"src/mochiweb_http.erl"},{line,48}]}]}
2018-01-24 11:19:34.402 [error] <0.1403.0> Supervisor 'esockd_connection_sup - <0.1403.0>' had child connection started
with mochiweb_http:start_link({emqttd_ws,handle_request,[]}) at <0.26613.0> exit with reason {invalid_proxy_info,<<"GET
/mqtt HTTP/1.1\r\n">>} in esockd_connection:upgrade/1 line 122 in context connection_crashed` 
 
Similar output under `console.log`

*A description of the issue* 
 
## My Configs 
![mqls](https://user-images.githubusercontent.com/9129843/35322835-aef7232c-00fc-11e8-802c-6871d7395ec3.PNG)

### Websockets Configs 
`listener.ws.external = 18183` 
`listener.wss.external = 18084` 
 
Client configuration : 
Address : `ws://<server>:18183/mqtt`

**Comment by emqplus** [comment]
@TheBeachMaster Turn off the Proxy Protocol Flag:

```
listener.ws.external.proxy_protocol = off
listener.wss.external.proxy_protocol = off
```

**Comment by TheBeachMaster** [comment]
Thanks, this issue has been resolved by explicitly declaring 
`listener.ws.external.proxy_protocol = off` 
`listener.wss.external.proxy_protocol = off`  as mentioned above.

Then killing and starting up the `emqttd` service

Thanks @emqplus .
👍
