### ISSUE TITLE
High cpu usage of beam.swp in docker

### ISSUE THREAD

**Issue by Shawn-ye** [emqtt/emqttd#1465]
#### Environment

- OS: Debian 8 64bit
- Erlang/OTP: not found
- EMQ: v2.2.0

#### Description
 We have a single emq node running on a cloud virtual machine and there're about 5000 established connections simultaneously and about 1000 connections in `TIME_WAIT` condition (perhaps client auth error). There're about 1000 messages per second totally. And the cpu usage in `top` is about 50% all the time. Any suggestions to troubleshoot this problem? Thanks.  The config options we modified are as below:
```
      - EMQ_NODE__PROCESS_LIMIT=2097152
      - EMQ_NODE__MAX_PORTS=1048576
      - EMQ_MQTT__CLIENT__IDLE_TIMEOUT=240S
      - EMQ_MQTT__ALLOW_ANONYMOUS=false
      - EMQ_MQTT__CACHE_ACL=false
      - EMQ_MQTT__MQUEUE__MAX_LENGTH=8
      - EMQ_LISTENER__TCP__EXTERNAL__ACCEPTORS=64
      - EMQ_LISTENER__TCP__EXTERNAL__MAX_CLIENTS=1024000
      - EMQ_LISTENER__SSL__EXTERNAL__MAX_CLIENTS=1024000
      - EMQ_LISTENER__WS__EXTERNAL__MAX_CLIENTS=1024000
      - EMQ_LISTENER__WSS__EXTERNAL__MAX_CLIENTS=1024000
      - EMQ_SYSMON__LARGE_HEAP=64MB
```
*A description of the issue*

**Comment by hfcorriez** [comment]
It's same to me.

**Comment by huangdan** [comment]
hi, @Shawn-ye 
Could you describe your  more detail for test scenario?
 for example:
the number of Pub/Sub Connection, QoS, the number of messages, the frequency of the message, the size of Payload, the number of Topic.

**Comment by Shawn-ye** [comment]
hi, @huangdan Thanks for your reply. It would take a while to collect these information you required and I will provide them later.
