### ISSUE TITLE
login failed for timeout

### ISSUE THREAD

**Issue by hello2dj** [emqtt/emqttd#1471]
#### Environment

- OS: Docker 2.3.3
- Erlang/OTP: 
- EMQ: Docker 2.3.3

#### Description
when i mock 10k devices connect to the emqtt it will report this error, and some devices can connect, but others can't (i use mongodb to auth), i want to know what this mean? can you help me?
![image](https://user-images.githubusercontent.com/10645383/35423971-d3f6e23a-028b-11e8-9c47-af6e325e3649.png)

**Comment by emqplus** [comment]
Cool issue, closed.

**Comment by hello2dj** [comment]
@emqplus  I don't understand you, how can i do? what does invalid, Cool, and wontfix mean?

**Comment by liuxiaodong** [comment]
+1

**Comment by hello2dj** [comment]
@emqplus  I just want to how what does this error mean? so that i can use right

**Comment by hello2dj** [comment]
this mean i Call mongodb to auth timeout ?
