### ISSUE TITLE
How to get the current online user?

### ISSUE THREAD

**Issue by kansifang** [emqtt/emqttd#148]
How to get the current online user?

**Comment by erylee** [comment]
Please check: https://github.com/emqtt/emqttd/wiki/Presence.

Could subscribe the $SYS topics to trace clients.

**Comment by roytan883** [comment]
need wait 0.9.0? I download 0.8.2, it return "Not found."

**Comment by erylee** [comment]
@roytan883, HTTP API will be supported in 0.9.0, and you could subscribe the $SYS topics to record all presence messages.

**Comment by erylee** [comment]
@kansifang, @roytan883, this feature has been released in 0.10.0. Pls check issue #230.
