### ISSUE TITLE
Acessing Packet Data and Reading It

### ISSUE THREAD

**Issue by Nawneet47** [emqtt/emqttd#1489]
#### Environment

- OS: Ubuntu
- Erlang/OTP: 
- EMQ: 2.3.4

#### Description
Hello I am Completely new in EMQTT protocols and its  features. I am working in a home automation project  And I want to know that How can i access all of pending data of publish or subscribe. So that i can make a log of it using other language of successful and failed request. By this way I can show the users that their request are processed or still pending in queue .
If there is any API or tools then Please Suggest me ASAP.

Thanks

**Comment by HJianBo** [comment]
Hi, @Nawneet47 The [Web Hook](https://github.com/emqtt/emq-web-hook) may be helpful for you!

And, You can find more information at http://emqtt.io/docs/v2/index.html

**Comment by Nawneet47** [comment]
Thanks. For your help.
