### ISSUE TITLE
session and queue meaning?

### ISSUE THREAD

**Issue by roytan883** [emqtt/emqttd#150]
1, Does ‘session’stand for clientID？when session expired what will happen？All queued messages will be deleted and subscribed topics will be deleted too？when reconnected， need redo subscription？

2，{max_queued_messages, 100} means queue for one session or one topic？
If it stand for session， while one topic has lots of offline messages（100）, the user's other topic offline messages will be flushed？

3，About the retained message, how to config one topic only keep the latest retained message, the older retained messages will be auto deleted?

**Comment by erylee** [comment]
1. When a client connected to broker with 'clean session' flag 0, a session identified by clientId will be created. The session will expire after 24 hours if no client connections bind with it,  and all queued messages and subscriptions will be dropped.

2.  max_queued_messages for session. Topic just dispatch messages to clients or sessions that matched the subscriptions. Topic has no idea about offline messages.

3. By default, the broker only keep the latest retained message of one topic.

**Comment by roytan883** [comment]
Thanks for clarify them.
follow question:
max_queued_messages for session. when the client with 'clean session' flag 0 and offline not expire.
4, Will the broker put session's subscribed topic new messages to session's queue? 
5, If it limit 100, when the session subscribed topic1 and topic2, what will happen when topic1 fill 70 messages, then topic2 fill 80 messages?  After the reconnection, will the session lose first 50 message?

**Comment by sailingchen** [comment]
This is some question about session and offline message queue:

emqttd.conf :  
        {session, [
            %% Expired after 24 hours
            {expires, 24},
            %% Max offline message queue
            {max_queue, 3},
            %% Store Qos0?
            {store_qos0, false}
        ]}
-------------------------------------------------
emqttd setting {max_queue, 3} , client subscriptions topic and set clean_sess=false and  qos=1,  when client disconnect , publish 10 message  with qos 1,  then connection to emqttd , client receive 10 message 。

**Comment by erylee** [comment]
@sailingchen, I am rewriting session and queue, and will write a Wiki to explain the design in detail.

**Comment by erylee** [comment]
@sailingchen,  @roytan883, I move the discussion to FAQ wiki: 

https://github.com/emqtt/emqttd/wiki/FAQ

And the broker released a new design of queue/session in 0.9.0: 

https://github.com/emqtt/emqttd/wiki/Improve-the-Session-Queue-Design

**Comment by Satishpujari** [comment]
Thanks I got clear idea about session expiry. I have one more doubt about Message Expiry In EMQ. what it means exactly ?

**Comment by HJianBo** [comment]
Hi, @Satishpujari  Where is Message Expiry introduced?

**Comment by Satishpujari** [comment]
I have one requirement like  need to implement Session and message expiry in EMQ .

**Comment by Satishpujari** [comment]
I checked in EMQ. CONF file i got session expiry but i didn't get message expiry. I don't have idea about the same.

**Comment by HJianBo** [comment]
Okay, can you open a new issue to describe the details?

**Comment by Satishpujari** [comment]
i have one doubt I set Session expiry for 2h
one device is connected to my emq broker and sent data and disconnected. And the device will not connect after two more hours also .then After two hours only(from disconnected time) The session will expired. please correct me if i am wrong

**Comment by HJianBo** [comment]
Yes, it's right. But it only works by the client connecting with `cleansession = false`.

**Comment by Satishpujari** [comment]
Could you tell me how it(cleansession = false) will work in EMQ 3.1.1

**Comment by HJianBo** [comment]
Hi, @sailingchen you can add my telegram to discuss these.  https://t.me/heeejianbo

**Comment by Gilbert-Wong** [comment]
@sailingchen Also you can join the telegram group of emqx :) https://t.me/emqxcommunity
