### ISSUE TITLE
Custom VM args

### ISSUE THREAD

**Issue by PiedPieper** [emqtt/emqttd#1502]
#### Environment

- OS: All
- Erlang/OTP: All
- EMQ: 2.3+

#### Description

Hello,

I would like the ability to use custom VM args in EMQTT so that I can use distributed erlang TLS to secure communications between clustered nodes.

In my other erlang programs I can use a vm.args file and specify its location in my rebar.config file. How could this be done with emqtt? It seems as if the emq.conf file populates the vm args.

**Comment by emqplus** [comment]
I submit a PR #1504 to support Erlang SSL distribution. @PiedPieper  Please pull the `develop` branch and build to verify the issue, Thanks

**Comment by emqplus** [comment]
@PiedPieper The feature has been released in 2.3.5. Tune on the TLS distribution in `emq.conf`:

`node.proto_dist = inet_tls`

and then configure TLS options in `etc/ssl_dist.conf`.

**Comment by PiedPieper** [comment]
@emqplus It apprears that using ssl_dist_optfile requires OTP 20.2: http://www.erlang.org/news/116

**Comment by emqplus** [comment]
@PiedPieper

**Comment by PiedPieper** [comment]
It worked just as an FYI. I would add that you should not include _verify_peer_ as an option for the client because it checks something in the certificate, I'm not sure what, with the hostname, and it is rare that your hostname is going to be included in the certificate issued.

**Comment by emqplus** [comment]
@PiedPieper I added a brief article in the `emq-tutorial-en` project, please help review: https://github.com/emqtt/emq-tutorial-en/pull/3

**Comment by PiedPieper** [comment]
@emqplus read through it, it looks great!

**Comment by turtleDeng** [comment]
@PiedPieper Fixed in 2.3.6 release.
