### ISSUE TITLE
EMQ | EMQX | EMQ-Plus - Deploy to Prod

### ISSUE THREAD

**Issue by TheBeachMaster** [emqtt/emqttd#1505]
#### Environment

- OS: Centos 7
- Erlang/OTP: 20 
- EMQ: 2.3.3

#### Description
About to deploy EMQ on prod and I'd like a proper set of procedure to follow as far as the platform is concerned. 
- Who should I contact?
-  What is EMQ-Plus?
- What is EMQX ?

*A description of the issue*
+ I've been relying on docs from [this link](http://emqtt.io/docs/v2/index.html) until I came across [these](http://emqx-enterprise-docs-en.readthedocs.io/en/latest/install.html) : what are the differences?
+ I'd like a setup where an AMQP instance talks to my EMQ broker (untested -ignore if this feature exists in the regular broker), is such a feature Enterprise only?

## How to reach me for 1-on-1 convos
- Mail me directly from [my site](https://www.otienoken.me#contact)  _can not share email publicly_

**Comment by emqplus** [comment]
@TheBeachMaster The AMQP bridge is ready in EMQ X, the enterprise edition of EMQ. Please contact [zhengyu.pan@emqtt.io](mailto: zhengyu.pan@emqtt.io) who is our global support for more information.

**Comment by TheBeachMaster** [comment]
Thanks @emqplus . 
We've been in touch.
