### ISSUE TITLE
erlang.log goes to 5 max

### ISSUE THREAD

**Issue by nagendraK6** [emqtt/emqttd#1506]
#### Environment

- OS: ALL
- Erlang/OTP: ALL
- EMQ: ALL

#### Description

I want to increase the number of log file count > 5 in debug mode. I tried by updating settings and then restart but it's still rotating in 1 to 5 and overwriting old ones.

**Comment by turtleDeng** [comment]
@nagendraK6 https://github.com/emqtt/emq-relx/pull/176

**Comment by emqplus** [comment]
@nagendraK6 The issue has been fixed in v2.3.5.
