### ISSUE TITLE
What  is the best AWS EC2 type? - for 10k Concurrent SSL connection  

### ISSUE THREAD

**Issue by incowiz** [emqtt/emqttd#1507]
#### Environment

- OS: Ubuntu 16.04 LTS
- Erlang/OTP: 
- EMQ: version 2.3.3

#### Description

`1.  my purpose: 10k Concurrent connection with SSL`

- i tuned my ubuntu machine and emqtt config file based on  [emqtt document](http://emqtt.io/docs/v2/tune.html) (c4.xlarge EC2 instance type)

`=> Question 1: is this suitable ec2 instance type for my purpose?`

- now i am testing for "10k Concurrent connection with SSL" with apache jmeter.
`Question 2: What is the correct setting value for apache jmeter?`

could you kindly provide your opinion? (the below images are my current setting value for apache jmeter)

![image](https://user-images.githubusercontent.com/24931048/36468454-c1a0aeae-1726-11e8-8bc9-e77372b9f5b3.png)

![image](https://user-images.githubusercontent.com/24931048/36468501-f5ddec90-1726-11e8-92c6-aa89184bc762.png)

Thank you!

**Comment by emqplus** [comment]
Question 1: is this suitable ec2 instance type for my purpose?

A: It's enough for 10K SSL connections. It's better to deploy a LB to handle SSL offloading in the front of EMQ cluster in production.

Question 2: What is the correct setting value for apache jmeter?

A: Please check the [mqtt-jmeter](https://github.com/emqtt/mqtt-jmeter) plugin.

**Comment by incowiz** [comment]
Hello Feng Lee.

 

Thank you for your quickly feedback.

 

Question 1: is this suitable ec2 instance type for my purpose?

A: It's enough for 10K SSL connections. It's better to deploy a LB to handle SSL offloading in the front of EMQ cluster in production.

ð  Could you provide your cost policy for commercial support? (please consider the below my conditions)

n  Set up the Ubuntu machine on AWS with 10K SSL connections without any connection failure

n  Emqtt auto clustering with with a dns-name of AWS load balancer.


 


Best Regards,

Brian,Jang. (Director of incowiz)

**Comment by emqplus** [comment]
@incowiz Sorry for the delay reply that I took biz trip these days. Please contact @zhengyupan for the commercial support plan.

**Comment by brianjang** [comment]
@zhengyupan 
Hello.
i would like to get some information for commercial support plan with below conditions: 

- Could you provide your cost policy for commercial support? (please consider the below my conditions)?
- Set up the Ubuntu machine on AWS with 10K SSL connections without any connection failure
- Emqtt auto clustering with with a dns-name of AWS load balancer.
