### ISSUE TITLE
duplex clientId lead continual reconect

### ISSUE THREAD

**Issue by roytan883** [emqtt/emqttd#151]
I'm confused about session, then read protocol again：
"Session:  
A stateful interaction between a Client and a Server. Some Sessions last only as long as the Network  Connection, others can span multiple consecutive Network Connections between a Client and a Server. "

Does it mean one clientID can have multiple connection with server? Like android, ios, pc client use the same clientID to connect mqtt server.

Then i try to conect emqttd with two equal clientID
mosquitto_sub -c -d -i user5 -q 2 -t topic1
mosquitto_sub -c -d -i user5 -q 2 -t topic1

If only start one client, every thing works fine.
When the second mosquitto_sub start, both mosquitto_sub keep continual reconect. It looks like in some kind of conflict situation.

Client user5 sending CONNECT
Client user5 received CONNACK
Client user5 sending SUBSCRIBE (Mid: 1, Topic: topic1, QoS: 2)
Client user5 received SUBACK
Subscribed (mid: 1): 2
Client user5 sending CONNECT
Client user5 received CONNACK
Client user5 sending SUBSCRIBE (Mid: 2, Topic: topic1, QoS: 2)
Client user5 received SUBACK
Subscribed (mid: 2): 2
Client user5 sending CONNECT
Client user5 received CONNACK
Client user5 sending SUBSCRIBE (Mid: 3, Topic: topic1, QoS: 2)
Client user5 received SUBACK
Subscribed (mid: 3): 2
Client user5 sending CONNECT
Client user5 received CONNACK
Client user5 sending SUBSCRIBE (Mid: 4, Topic: topic1, QoS: 2)
Client user5 received SUBACK
Subscribed (mid: 4): 2

**Comment by erylee** [comment]
No. According the MQTT Specification, clientId cannot be duplicated. If two connections with the same clientId, the older one will be kicked out.

**Comment by roytan883** [comment]
when the older one kick out, is there a reason or something client can know?  it was kicked not normal disconnection, then the client can stop reconnect.

**Comment by erylee** [comment]
@roytan883, no definition about duplicated clientIds in MQTT protocol I think. This is a big issue if two conflict clients reconnect all the time...

I will check MQTT V3.1.1 protocol specification later. And have any suggestions?

**Comment by roytan883** [comment]
I have looked though MQTT V3.1.1 protocol, can't find a elegant way to kick out older client and inform it should not reconnect -_-!

**Comment by erylee** [comment]
CONNACK packet should have a payload...

**Comment by roytan883** [comment]
Can the broker auto publish a "kick" message to older client before close it ?

**Comment by erylee** [comment]
Most MQTT client libraries will not handle the 'kick' message...

**Comment by roytan883** [comment]
But i don't think the broker has ability to control client not reconnect. 
Must need some kinds of message to tell one of clients to stop.
Also, i tested mosquitto mqtt broker. It is the same, continual reconect.

1433233406: New connection from 127.0.0.1 on port 1883.
1433233406: Client user5 already connected, closing old connection.
1433233406: Client user5 disconnected.
1433233406: New client connected from 127.0.0.1 as user5 (c0, k60).

1433233407: New connection from 127.0.0.1 on port 1883.
1433233407: Client user5 already connected, closing old connection.
1433233407: Client user5 disconnected.
1433233407: New client connected from 127.0.0.1 as user5 (c0, k60).

**Comment by erylee** [comment]
The clientId is a secret key in MQTT protocol I think,  something like deviceId of a mobile. So client should not leak its clientId, there is little chance to conflict in broker?

**Comment by roytan883** [comment]
I use userId as clientID.  I believe some other developer will also use uid as clientid.
When the user change his phone, login on the new phone but forget logout on old one. Then the conflict happen.

But your idea is right, we need use deviceId as the clientId. The application server should keep track of the uid <--> deviceId map. Or the application server generate a unique ID for every new login.

**Comment by erylee** [comment]
Design of "userId as clientID" is not common  practice in MQTT I think.  'Username' of CONNECT packet  could be user ID.

**Comment by roytan883** [comment]
So, need emqttd export username:
https://github.com/emqtt/emqttd/wiki/Presence
only connected has username parameter. disconnected and HTTP API did not export username.

**Comment by roytan883** [comment]
Can you add a HTTP API query presences by username ? 
The presences interface only return online clientIds? 
How to get those session not expire but offline ones? I only want push messages to those active users(48h expire). HTTP Query then push seems inefficient，maybe i need write a plugin for push, the plugin will only push message to those username whos session exist.

**Comment by lsxredrain** [comment]
clientid is a prviate id, it is used to  communicated  between user and system for some adminstartor message. 
i have designed a pubilc id  such as mqttid for business。

**Comment by erylee** [comment]
@lsxredrain, please submit a 'Feature Request' issue. Kick out client by clientId by cli command or web console?

**Comment by sufish** [comment]
@roytan883， in general MQTT protocol suggests to use Last Will Testament to do client presence management

**Comment by erylee** [comment]
@sufish, Last Will Message could only report abnormal disconnection.

**Comment by sufish** [comment]
@erylee when clients connect or disconnect normally , it can send a message to a specific topic to identify its state, and  Last Will Testament will do the same job when the client can't. it's great that emqtt will do  similar job from server side. but sometime additional information is needed from the client, like platform, software version. this is hard to do from server side

**Comment by lsxredrain** [comment]
Client = emqttd_cm:lookup(emqttd_util:bin(ClientId)),
                                    case (undefined =/= Client) of
                                        true -> 
                                            #mqtt_client{client_id = ClientId, client_pid = ClientPid} = Client, 
                                            lager:info("This is  ClientPid: ~p self: ~p ~n",[ClientPid, self()]),
                                            case (self() =/= ClientPid) of
                                                true ->
                                                    Json = mochijson2:encode([{type,emqttd_util:bin(["duplicate"])}]),
                                                    ClientTopic = emqttd_util:bin(["/client/",  ClientId]),
                                                    Message = #mqtt_message{qos = 0,
                                                                  topic = ClientTopic,
                                                                  payload = emqttd_util:bin(Json),
                                                                  from = list_to_binary([ClientId])},
                                                    emqttd_pubsub:publish(Message),
                                                    {"tokeAuth", "duplicate"}; 
                                                false -> {"tokeAuth", "success"}
                                            end;
                                        false -> {"tokeAuth", "success"}
                                    end;

**Comment by chrisp22** [comment]
Thanks for clearing the air about the same id problem, at-least i know how to handle it.

**Comment by terry-xiaoyu** [comment]
close this as it has been solved.

**Comment by roytan883** [comment]
@terry-xiaoyu How did it be solved? Do i need any configuration?

**Comment by Gilbert-Wong** [comment]
@roytan883  Open a new issue if you have this problem on emqx3.0 and use the issue template to give us the detailed information .
