### ISSUE TITLE
MySQL ACL (Deny all, except...)

### ISSUE THREAD

**Issue by evdbovenkamp** [emqtt/emqttd#1517]
#### Environment

- OS: Ubuntu
- Erlang/OTP: 
- EMQ: latest

#### Description

Hi, I am searching for a way to restrict the sub and pub topics.
I am using the MySQL plugin for ACL and I am struggling with it. 

My ideal situation is that I want to deny every client access to every topic, EXCEPT the topic(s) I grant the client access to, by setting the ACL in the MySQL database.

Can anyone explain if this is possible and, even more important; how I set this in my database.

Thank you,

Erwin

**Comment by HJianBo** [comment]
In the first, you can import default ACL rules using [emq_auth_mysql/mqtt.sql](https://github.com/emqtt/emq-auth-mysql/blob/master/mqtt.sql)


Then, add the following data to MySQL:
```sql
/* Deny all username to subscribe any topic */
INSERT INTO `mqtt_acl`(`allow`, `username`,`access`, `topic`) VALUES(0, '$all', 1, '#');

/* Allow user `usera`  subscribe `topica`*/
INSERT INTO `mqtt_acl`(`allow`, `username`,`access`, `topic`) VALUES(1, 'usera', 1, 'topica');
```

**Comment by evdbovenkamp** [comment]
Thank you very much!
