### ISSUE TITLE
Feature Request - control client by clientId  for admistrator fucntion

### ISSUE THREAD

**Issue by lsxredrain** [emqtt/emqttd#152]
the best way maybe  to make some dynamic  acl rule to control user to access the topic.
but it maybe consume huge resources to achieve this goal.
I think maybe can add some interfere to control client  to access some topic for system adminstrator。
feature description：
1、kick some client by clientid
2、unsubscribe some topic of the client by clientid
by cli command or web console is all ok，but should have acl rule to control this privilege。
I can use this interfere in java/python/c etc.  to do this  admin function。

**Comment by roytan883** [comment]
3， subscribe some topic of the client by clientid

With 2 and 3, I can use emqttd as a pure push server.  Make my clients full passive, clients only need connect to emqttd and receive messages. Application server know what topic need to be subscribe and unsubscribe for a specified clientID at runtime. 
Also this can save clients network traffic, clients no need subscription and unsubscription, all controlled by internal server.

**Comment by roytan883** [comment]
4, publish message to one username's all session, emqttd will use topic '$Q/client/ClientId'. 

If the username has no session bind, then abandon this message and do nothing.
This can big improve thrid party server performance,  no need query, just push to those active user(48h expire). The client know how long it offline, it will sync information with application server by its own way(like HTTP request) when expired.

**Comment by lsxredrain** [comment]
subscribe topic by clientid
1  add code in emqttd/rel/files/emqttd_ctl
# Check the first argument for instructions
case "$1" in

  subscribe)
        if [ $# -ne 4 ]; then
            echo "Usage: $SCRIPT subscribe <ClientId> <Topic> <Qos>"
            exit 1
        fi

        RES=`$NODETOOL ping`
        if [ "$RES" != "pong" ]; then
            echo "Node is not running!"
            exit 1
        fi
        shift

        $NODETOOL rpc emqttd_ctl subscribe $@
        ;;
2.  in emqttd/apps/emqttd/src/emqttd_ctl.erl 
-export([subscribe/1,
          status/1,
          ..
%%------------------------------------------------------------------------------
%% @doc subscribe topic by clientid
%% @end
%%------------------------------------------------------------------------------
subscribe([ClientId, Topics, Qos]) ->
    Client = emqttd_cm:lookup(bin(ClientId)),
    #mqtt_client{clientid = _, client_pid =ClientPid} = Client,
    %?PRINT("subscribe ~p ~p ~p ~p ~n", [ClientId, Topics, Qos, ClientPid]),
    subscribe_iml([ClientPid, Topics, Qos]).

subscribe_iml([undefined, _, _])->
   ignore;

subscribe_iml([ClientPid, Topics, Qos])->
    [ClientPid ! {subscribe, list_to_binary([Topics]), Qos}].


test result
right clientid
root@10-9-26-83:/data/emqttd/rel/emqttd/bin# ./emqttd_ctl subscribe lsxtest dsfsf  0

19:15:06.851 [info] Client lsxtest subscribe [{<<"dsfsf">>,"0"}]. Granted QoS: ["0"]

wrong cliendid

root@10-9-26-83:/data/emqttd/rel/emqttd/bin# ./emqttd_ctl subscribe lsxtest1 dsfsf  0
RPC to 'emqttd@127.0.0.1' failed: {'EXIT',
                                   {{badmatch,undefined},
                                    [{emqttd_ctl,subscribe,1,
                                      [{file,"src/emqttd_ctl.erl"},{line,59}]},
                                     {rpc,'-handle_call_call/6-fun-0-',5,
                                      [{file,"rpc.erl"},{line,205}]}]}}
root@10-9-26-83:/data/emqttd/rel/emqttd/bin#

**Comment by bmcustodio** [comment]
@erylee I believe that what I am requesting in #252 is roughly the same as @roytan883 is requesting in [here](https://github.com/emqtt/emqttd/issues/152#issuecomment-108180443).
