### ISSUE TITLE
emq_auth_mysql load error

### ISSUE THREAD

**Issue by GUOLIX** [emqtt/emqttd#1520]
#### Environment

- OS: WINDOWS SERVER 2016
- EMQ: 2.3.4
- MYSQL 5.7.17

#### Description

>emqttd_ctl plugins load emq_auth_mysql

load plugin error: {emq_auth_mysql,
                    {bad_return,
                     {{emq_auth_mysql_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,
                         {error,
                          {shutdown,
                           {failed_to_start_child,emq_auth_mysql,
                            {shutdown,
                             {failed_to_start_child,worker_sup,
                              {shutdown,
                               {failed_to_start_child,
                                {worker,1},
                                {{badmatch,{error,econnrefused}},
                                 [{mysql,init,1,
                                   [{file,
                                     "d:/emqtt/v2.3/2.3.4/emq-relx/deps/mysql/src/mysql.erl"},
                                    {line,496}]},
                                  {gen_server,init_it,6,
                                   [{file,"gen_server.erl"},{line,328}]},
                                  {proc_lib,init_p_do_apply,3,
                                   [{file,"proc_lib.erl"},
                                    {line,247}]}]}}}}}}}}},
                        [{emq_auth_mysql_app,start,2,
                          [{file,
                            "d:/emqtt/v2.3/2.3.4/emq-relx/deps/emq_auth_mysql/src/emq_auth_mysql_app.erl"},
                           {line,33}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,273}]}]}}}}}

The windows service can not start also.

**Comment by msyxiongzai** [comment]
这个问题怎么解决的。centos6.6服务器 emqttd-centos6.8-v2.3.8启用mysql认证插件失败。win10系统	emqttd-windows10-v2.3.8 mysql认证插件启用成功
![22j65c vh6l0 j 1qukkso8](https://user-images.githubusercontent.com/12079058/43132366-206fde0e-8f6e-11e8-9583-8a65dd5cf2c2.png)
