### ISSUE TITLE
REST API unsubscribe

### ISSUE THREAD

**Issue by emqplus** [emqtt/emqttd#1522]
#### Environment

- OS: ALL
- Erlang/OTP: ALL
- EMQ: 2.3.5

#### Description

In REST API i can suscribe a client to a topic, POST api/v2/mqtt/subscribe

```
{
"topic": "test",
"qos": 1,
"client_id": "C_1492145414740"
}
```

Is posible with REST API to unsuscribe a client form a topic ?

**Comment by shuaibakram** [comment]
@emqplus @turtleDeng 
Just a thought.
How about having a REST API to subscribe a client to multiple topics?

**Comment by Gilbert-Wong** [comment]
You can use  loop or recursive to solve it .
