### ISSUE TITLE
mqtt.js clinet can not SUB.

### ISSUE THREAD

**Issue by hung119** [emqtt/emqttd#1523]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 20.1
- EMQ: 2.3.5

#### Description

```
var mqtt = require('mqtt')
var client  = mqtt.connect('mqtt://q.emqtt.com:1883')

client.on('connect', function () {
	console.log('-------------')
  	client.subscribe('presence')
  	client.publish('presence', 'Hello mqtt')
})

client.on('message', function (topic, message) {
  // message is Buffer
  	console.log('+++++++++++++++++++');
  	console.log(message.toString())
  	client.end()
})

```

*A description of the issue*
I use emqtt to simulate PUB/SUB. 
 It can not output:
"+++++++++++++++++++
Hello mqtt"
I don't know what is the problem.
Thanks for any helps.

**Comment by wiviwiv** [comment]
JavaScript uses an event-driven, non-blocking I/O model. 
Subscribe and publish are almost executed at the same time. The client publish a message without a topic before it was subscribe successful if you running slow network.

```js
...
client.on('connect', function () {
	console.log('-------------')

  	client.subscribe('presence')
  	setTimeout(function publish() {
                // Luckily 1000ms is enough
                client.publish('presence', 'Hello mqtt')
        }, 1000)
})
...
```

It is necessary to use a callback function or a time drive to solve the timing problem.

```js
...

client.on('connect', function() {
  console.log('-------------')
  client.subscribe('presence', function callback(error) {
    console.log(error && error.toString() || 'Subscribe Success')
    client.publish('presence', 'Hello mqtt')
  })
})

...
```

**Comment by hung119** [comment]
it's worked for me.
Thanks for the response.

**Comment by emqplus** [comment]
@hung119 EMQ R3 will ensure an subscription take effect when the client received 'SUBACK'.
