### ISSUE TITLE
Transparency and Clarification on EMQ vs EMQ-X and Paywall

### ISSUE THREAD

**Issue by gihad** [emqtt/emqttd#1528]
@emqplus 
Can you please clarify the differences between EMQ and EMQ-X in a transparent way? I've read through a lot of the Github issues here and I can see a lot of people are not happy about this the way the business is being conducted and the lack of transparency.

- What are the differences in terms of features and what's behind the paywall between EMQ and EMQ-X?

- Do new features first go into EMQ-X and a few weeks later they are added to EMQ or do they never make it to EMQ and stay behind the paywall forever?

- Can you clarify the pricing model for EMQ-X? It looks like you guys charge based on size of deployment? Or is it a one time fee? Support? Custom plugin development?

- Some Github repos with features have disappeared and moved behind the paywall because they are now part of EMQ-X, have those been the work of the open source community? (e.g.: Kafka Bridge which is [advertised in your home page](http://emqtt.io/static/img/overview.png))

- How do basic features of MQTT such as QoS 1 & 2 work with EMQ if backend persistence is a feature implemented in EMQ-X? See https://github.com/emqtt/emqttd/issues/1064

Please clarify the points above so that I can make an informed decision about which MQTT broker to use for our deployment. Having all of these points clarified on the website would also help the community a lot.

Thanks,
Gihad

**Comment by gihad** [comment]
Just to add some info here: I finally got some answers regarding pricing for EMQ-X by contacting zhengyu.pan@emqtt.io however the pricing tiers are still not clear.

Previous emails to feng@emqtt.io and contact@emqtt.io and the google user group were not responded to so don't bother with those.

**Comment by zhengyupan** [comment]
Hi Gihad,
You can still use contact@emqtt.io to communicate with us. We got your mail at 14:03 CET and sent out the first reply at 14:10. Sometime there would be a delay, but relax, there are our colleagues behind this email address and you will get answered. Everybody is still welcome to send mail to this address:)

For the pricing model, our pricing model is based on the service effort we need to deliver. This is an estimation made base on our service effort already made for different customers. EMQ X is a professional software which is very flexible for different use cases, we provide service almost to every customer. Usually, the larger the deployment is, the more effort we need to bring to the customer. To be noticed, this also covers the service cost cause by responding to the service requirement of the open source edition of our product, the EMQ X. We appreciate every paying customer, without you, the emq cannot survive.

There are more features in the EMQ X than in the EMQ. Which features belong to EMQ X and which belong to EMQ? The cutting-edge ones only available in EMQ X? No. We bring the best technologies both to EMQ X and to EMQ. Only the features which are mostly interested in commercial deployments is in the EMQ X. Maybe different venders have different understanding about it, this is our understanding.

**Comment by gihad** [comment]
- First message was on Feb 21st to the google groups (never got a reply)
- Second massage was Later on Feb 21st to feng@emqtt.io (never got a reply)
- Third message was also on Feb 21st as a Github issue which I followed up twice, 2 days later and 3 days later (never got a reply)

The methods above are advertised as contact address under http://emqtt.io/

Finally got a reply from you today using zhengyu.pan@emqtt.io however the pricing tiers remain very unclear and I'm an interested customer.

**Comment by marcschroeder** [comment]
Hello @zhanghongtong,

have you been able to address this issue?
We are still unable to determine a price for your Enterprice version from the information on your website.

**Comment by MeertenR** [comment]
This may be relevant:
emqx.com/en/news/emqtt-has-been-permanently-changed-to-emqx
