### ISSUE TITLE
retain bit is now always sent to clients even for existing subscriptions

### ISSUE THREAD

**Issue by victorclaessen** [emqtt/emqttd#1529]
#### Environment

- OS: Debian 9
- Erlang/OTP:  R20/9.0
- EMQ: 2.3.5

#### Description

I'm really sorry to keep going on about this, but I think the fixes for the previous _retain_ issues that I raised (#1293 and #1461) have had an unfortunate side effect. **The retain bit is now sent to normal clients also as a result of a message published to an existing subscription.**

Proof:
```
claessen@brokernode1:~$ mosquitto_sub -t "test/topic" -v -R -C 1 &
[1] 540
claessen@brokernode1:~$ mosquitto_pub -t "test/topic" -m "testvalue" -r
claessen@brokernode1:~$ mosquitto_pub -t "test/topic" -m "testvalue"
test/topic testvalue
[1]+  Done                    mosquitto_sub -t "test/topic" -v -R -C 1
```
Or in words:
* I subscribe to the topic "test/topic" and ask (-R) that retained messages not be shown, and quit after receiving one message (-C 1) (and put this as a background job).
* I publish to the topic "test/topic" a message "testvalue" with the retain bit set. This message _is not shown_.
* I publish to the topic "test/topic" a message "testvalue" without the retain bit. This message is shown, and the mosquitto_sub programs exits.
* I have confirmed this with the MQTT.fx client.

I think that the retain bit on the first message should _not_ have been set, because:
> It MUST set the RETAIN flag to 0 when a PUBLISH Packet is sent to a Client because it matches an established subscription regardless of how the flag was set in the message it received [MQTT-3.3.1-9]

And, so once again I suspect that this is a bug.

**Comment by victorclaessen** [comment]
To summarize the past: 
* in #1293, I asked for the retain bit to be kept for bridge clients, which was fixed, but introduced
* in #1461, I reported that the retain bit was not set for previously retained messages, which was fixed but likely introduced the current bug.

In my view, the total decision tree should be something like:

```
IF "this message is the result of an new subscription" THEN
	keep retain bit (because this message already has it set, and it should be set [MQTT-3.3.1-8])
ELSE
	IF "this message is sent to a bridge client" THEN
		keep retain bit (because the broker on the other side of the bridge needs to retain it also)
	ELSE
		remove retain bit (because this is not bridge client, and this is the result of an existing subscription [MQTT-3.3.1-9])
	END IF
END IF
```

**Comment by victorclaessen** [comment]
Will this fix be published in a release soon?

**Comment by HJianBo** [comment]
Sure! It has tagged in v2.3.6. We will publish it soon! 

Please let me known if you have any problems. Thanks!

**Comment by victorclaessen** [comment]
I can confirm that the testcase as I described in the original posts is handled successfully in version 2.3.6.
