### ISSUE TITLE
emqttd  is ready for production ?

### ISSUE THREAD

**Issue by sailingchen** [emqtt/emqttd#153]
now ,I use mosquitto , but emqtt is better , emqttd  is ready for production ?

**Comment by erylee** [comment]
The core features are solid and scalable, and there are some users integrate emqttd in their projects. A small full-time team with many contributors are developing this project. You could submit issues if any feature requests or bug reports.

**Comment by erylee** [comment]
@sailingchen, move this question to wiki: https://github.com/emqtt/emqttd/wiki/FAQ
