### ISSUE TITLE
Question: Pushing MQTT events to Redis

### ISSUE THREAD

**Issue by petewasher** [emqtt/emqttd#1533]
#### Environment

- OS: Linux (Alpine 3.7 in Docker)
- Erlang/OTP: As used in `emq-docker`
- EMQ: 2.3.3

#### Description

This is more a question than a bug. I [tweeted](https://twitter.com/Washdogg/status/973582809485971459) you a question and was directed to start a discussion here. 

We are desiging a system where events are raised on mqtt channels of the form `<id>/c`. Right now, we have a single subscriber which takes those mesasges using the topic subscription of `+/c` and puts them into Redis for processing by other parts of the system. It's important to avoid duplication of these messages so we don't have to write logic to handle this into the other components.

Now we are trying to scale up, and this single subscriber is a cause for concern - if it crashes or has any slowness for some reason, it becomes a bottleneck or single point of failure for the whole system. Clearly we need to have redundancy and scale-ability here.

It would be great if EMQ could push messages directly into Redis for us. But I have some concerns:

* Have I missed something and I can already do this somehow with EMQ as-is?
* If I write an EMQ plugin which picks up on topic messages and pushes them to Redis, will running this on every broker cause message duplication? We run a cluster (in k8s) of at least two brokers.
* Is there some MQTT function/subscription type I've missed which allows me to have multiple subscribers to a channel but only deliver the message to 
exactly one of those subscribers?

Thanks!

**Comment by terry-xiaoyu** [comment]
### First for you questions:
**- Have I missed something and I can already do this somehow with EMQ as-is?**
A: You need to write your plugin. EMQ doesn't have a plugin fit your requirement out of box, but there're already some official plugins using redis, such as [emqt-auth-redis](https://github.com/emqtt/emq-auth-redis), which can be an example for you.

**- If I write an EMQ plugin which picks up on topic messages and pushes them to Redis, will running this on every broker cause message duplication? We run a cluster (in k8s) of at least two brokers.**
A: No. Each client will connect to only one broker at a time, and only your plugin on that broker will be invoked upon a new event.

**- Is there some MQTT function/subscription type I've missed which allows me to have multiple subscribers to a channel but only deliver the message to exactly one of those subscribers?**
A: Yes, try [shared-subscription](http://emqtt.io/docs/v2/advanced.html#shared-subscription)

### My suggestion
I recommend you to try the 'plugin' method. EMQ is designed for massive IoT devices, not stream processing. Your subscribers under a heavy load can be bottleneck of the system, and the parse of MQTT packages would lead to extra overhead.

**Comment by petewasher** [comment]
Great, thanks for your help. I'll get started.
