### ISSUE TITLE
the port 4369 and another random port is security ?

### ISSUE THREAD

**Issue by sailingchen** [emqtt/emqttd#154]
HI, when start emqttd ,  I found the port 4369 and  another random port(63703)  is open, are this  security ? 

Example: 
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      13736/epmd          
tcp        0      0 0.0.0.0:8083            0.0.0.0:*               LISTEN      16745/beam.smp      
tcp        0      0 0.0.0.0:8883            0.0.0.0:*               LISTEN      16745/beam.smp      
tcp        0      0 0.0.0.0:63703           0.0.0.0:*               LISTEN      16745/beam.smp      
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      16745/beam.smp

1883: mqtt no ssl
8883: mqtt with ssl
8083: websocket
thanks!

**Comment by erylee** [comment]
4369 and some random ports are opened by erlang node for internal communication.  Configure your firewall to allow 1883, 8883, 8083 ports to be accessed from outside for security.

**Comment by sailingchen** [comment]
追加： 如果 用于节点之间内部通信的端口 4369 和另外一些随机打开的端口暴露在公网会不会有安全问题, 可以设置监听内网IP吗，1883, 8883, 8083 这三个端口有认证，有ACL控制，安全不太成问题。

我们比较关注的安全就是控制publish 权限，目前版本功能已满足，通过不同用户+acl 控制 topic。
谢谢！

**Comment by erylee** [comment]
Erlang用于分布式节点间通信的端口，建议通过防火墙屏蔽外部访问。防火墙设置为只开放1883等外部访问端口。

emqttd访问控制有两个层面支持：

1. eSockd TCP Acceptor库, 支持基于IP地址的访问控制，例如只允许192.168.1.0/24网段，除192.168.1.1以外的IP访问

  {access, [{deny, "192.168.1.1"},
            {allow, "192.168.1.0/24"},
            {deny, all}]}
]).

2. emqttd本身MQTT协议层面的Subscribe/Publish访问控制，通过etc/acl.config可配置规则。

Regards
Feng

**Comment by erylee** [comment]
move to https://github.com/emqtt/emqttd/wiki/FAQ
