### ISSUE TITLE
EMQ Memory leak gradually

### ISSUE THREAD

**Issue by mshioz** [emqtt/emqttd#1547]
#### Environment

- OS: Windows Server 2012 R2 DataCenter 64Bit
- Erlang/OTP: 
- EMQ: 2.3.5

Memory: 4GB

#### Description

EMQTT seems to gradually leak memory.
When checking the process of erl.exe in Task Manager in Windows, at the time of start up, about 45M has increased to about 85MB at the moment.
Subscribers are using WebSocket to acquire messages, and QOS=0.

The following command was used to check memory usage. Please check attached document, erlshell.log.
./bin/emqttd attach
spawn(fun() -> etop:start([{lines, 25},  {sort, memory}]) end).

As far as looking at the output, it seems that the memory is rising every time MsgQ in the following part rises.

Pid            Name or Initial Func    Time    Reds  Memory    MsgQ Current Function
************************************************************************************
<6195.21715.1> emqttd_ws_client:ini     '-'       011114240   18960 prim_inet:send/3 

The question is below.
1) Why does this event occur? I understand that memory rise is occurring because MsgQ is not being processed. My understanding is correct ?
2) If the assumption of 1) is correct, why does MsgQ increase? Please let me know the cause.
3) Is there a way to forcefully delete messages in this MsgQ?

I also attach emq.conf.txt which I am using for reference.
Thank you.
[erlshell.log](https://github.com/emqtt/emqttd/files/1859292/erlshell.log)

[emq.conf.txt](https://github.com/emqtt/emqttd/files/1859296/emq.conf.txt)

**Comment by terry-xiaoyu** [comment]
@mshioz I think this problem is might caused by your subscribers - the WebSocket client. From your etop output, I can see that the EMQ is trying to send messages but it is blocked as the sending buffer is full.

If your receiver do not consume the messages from it's socket, the receiver's TCP buffer will be full, and eventually the sender's TCP buffer will also be full, and then the prim_send:send will get blocked.

I suggest you inspect your subscribers.

**Comment by mshioz** [comment]
Thank you for your reply.
I think I will investigate the subscriber.

However, I am looking for a provisional countermeasure against this memory leak until the subscriber's investigation is completed.

1) Since qos = 0 is used, how about changing mqtt.mqueue.store_qos0 in emq.conf from true to false? Does this change make sense? Also, please tell me what effect this change has.
If tentative correspondence is possible with other items in emq.conf, please tell me that item.

2) Is there any way to delete stored messages? For example, if you can delete it by using some emqttd (or emqttd_ctl) command, please tell me that command.

Thank you.

**Comment by terry-xiaoyu** [comment]
@mshioz 
1. Changing the `store_qos0` to false won't solve your problem. If `Clean Session` flag is set to true when a client is connected, EMQ will buffer "offline messages" into **EMQ's message queue** for that client if it is offline. Set `store_qos0` to false let EMQ stop buffer the QoS0 offline messages. 
But in your case, your subscriber is online, the messages have already sent to the subscriber, but it doesn't consume messages from the receiving buffer of TCP stack. The messages is buffered in the **TCP stack's message buffer**, and that causes more and more message being queued in the erlang mailbox of the sender. This's why your memory usage is increasing but it is not 'memory-leak'. 

2. No there's not. No such config item or command line tool can help deal with the **TCP stack's message buffer** or the sender's erlang mailbox. If you just do not want the memory to increase anymore, stop the problematic subscriber.

**Comment by mshioz** [comment]
Thank you for your detailed answer. It's a big help.

Your answer has the following sentence.
"But in your case, your subscriber is online, the messages have already sent to the subscriber, but it does not consume messages from the receiving buffer of TCP stack."

Can you guess anything about why messages are not being consumed from Receiving buffer of TCP stack?

In the current environment, the connection between emqtt and Subscriber is wirelessly connected, and this wireless connection may be rarely disconnected.

If "offline" also contains events that cause the connection to be abruptly disconnected, it seems valid to set mqtt.mqueue.store_qos0 = false, but how about that?

Thank you.

**Comment by terry-xiaoyu** [comment]
Maybe your subscriber is blocked by an I/O event and can't read from the socket, but I am not sure about that. In linux you could inspect your connection status such as `Recv-Q and Send-Q` using `netstat`, but there seems no way to do the same thing in windows.

The last suggestion I can make is, trying to replace your subscriber with [hive-webscoket-demo](http://www.hivemq.com/demos/websocket-client/), to see if the issue remains.
