### ISSUE TITLE
How to connect to EMQ using Java?

### ISSUE THREAD

**Issue by viveklamba** [emqtt/emqttd#1553]
#### Environment

- OS:  Windows 8
- Erlang/OTP: 
- EMQ: 2.3.6

**Comment by csilvav** [comment]
Hi @viveklamba I think that here is not the right place to post questions like this. However about your question, you can use any java client lib that implement the MQTT protocol or event WebSockets thru mqtt if you want to connect from front-end web app.

You can use a nice toolkit called Vert.x, they have an implementation of MQTT client, you can go here https://vertx.io/docs/vertx-mqtt/java/. Also you can use another popular lib called Paho, here is the doc https://www.eclipse.org/paho/clients/java/.
