### ISSUE TITLE
why pub message is faster than sub message?

### ISSUE THREAD

**Issue by lsxredrain** [emqtt/emqttd#156]
for example in emqttd_mod_autosub.erl , I wan to add some code to do some auth fucntion in user system。

client_connected(?CONNACK_ACCEPT, #mqtt_client{clientid = ClientId,
                                               client_pid = ClientPid}, Topics) ->
    F = fun(Topic) -> emqtt_topic:feed_var(<<"$c">>, ClientId, Topic) end,
    [ClientPid ! {subscribe, F(Topic), Qos} || {Topic, Qos} <- Topics],

    Json = mochijson2:encode([ {ts, emqttd_vm:timestamp()}]),
    Message = #mqtt_message{qos     = 0,
                            topic   = list_to_binary(["$Q/client/", ClientId]),
                            payload = iolist_to_binary(Json)},
    emqttd_pubsub:publish(list_to_binary(["From:", ClientId]), Message);

client_connected(_ConnAck, _Client, _Topics) ->
      ignore.

test result as follow:

(emqttd@127.0.0.1)1> 10:36:11.564 [info] Connect from 106.39.23.73:8766 -> 10.9.26.83:1883
10:36:11.766 [info] RECV from lsxtest@106.39.23.73:8766: CONNECT(Qos=0, Retain=false, Dup=false, ClientId=lsxtest, ProtoName=MQIsdp, ProtoVsn=3, CleanSess=true, KeepAlive=60, Username=undefined, Password=undefined)
lsx client_connected presenst [{qos,0}]
10:36:11.766 [info] From:lsxtest PUBLISH to $Q/client/lsxtest: <<"{\"ts\":1433385371}">>
10:36:11.766 [info] SEND to lsxtest@106.39.23.73:8766: CONNACK(Qos=0, Retain=false, Dup=false, AckFlags=0, RetainCode=0)
10:36:11.767 [info] Client lsxtest subscribe [{<<"$Q/client/lsxtest">>,0}]. Granted QoS: [0]
10:36:11.801 [info] RECV from lsxtest@106.39.23.73:8766: SUBSCRIBE(Qos=1, Retain=false, Dup=false, PacketId=5, TopicTable=[{<<"$Q/client/lsxtest">>,0}])
10:36:11.801 [warning] lsxtest resubscribe [{<<"$Q/client/lsxtest">>,0}]
10:36:11.801 [info] Client lsxtest subscribe [{<<"$Q/client/lsxtest">>,0}]. Granted QoS: [0]
10:36:11.801 [info] SEND to lsxtest@106.39.23.73:8766: SUBACK(Qos=0, Retain=false, Dup=false, PacketId=5, QosTable=[0])

**Comment by lsxredrain** [comment]
in emqttd\apps\emqttd\src\emqttd_protocol.erl files, I add this fuction to archive auto register.
but have a trouble 

handle(Packet = ?CONNECT_PACKET(Var), State0 = #proto_state{peername = Peername}) ->
    #mqtt_packet_connect{proto_ver  = ProtoVer,
                         proto_name = ProtoName, 
                         username   = Username,
                         password   = Password,
                         clean_sess = CleanSess,
                         keep_alive = KeepAlive,
                         clientid   = ClientId} = Var,

    State1 = State0#proto_state{proto_ver  = ProtoVer,
                                proto_name = ProtoName, 
                                username   = Username,
                                clientid   = ClientId,
                                clean_sess = CleanSess
                                },

    trace(recv, Packet, State1),

    {ReturnCode1, State3} =
    case validate_connect(Var, State1) of
        ?CONNACK_ACCEPT ->
            case emqttd_access_control:auth(client(State1), Password) of
                ok ->
                    %% Generate clientId if null
                    State2 = State1#proto_state{clientid = clientid(ClientId, State1)},
                   
                    %% Register the client to cm
                    emqttd_cm:register(client(State2)),

                    %%Starting session
                    {ok, Session} = emqttd_session:start({CleanSess, clientid(State2), self()}),


                    %% Start keepalive
                    start_keepalive(KeepAlive),

                    %% ACCEPT
                    {?CONNACK_ACCEPT, State2#proto_state{session = Session, will_msg = willmsg(Var)}},
                    
                    %% Start Register to app system
                    #mqtt_packet{header = _Header, variable = Variable, payload = _Payload} = Packet,
                    #mqtt_packet_connect{
                         proto_ver     = _ProtoVer,
                         proto_name    = _ProtoName,
                         will_retain   = _WillRetain,
                         will_qos      = _WillQoS,
                         will_flag     = WillFlag,
                         clean_sess    = _CleanSess,
                         keep_alive    = _KeepAlive,
                         clientid      = ClientId,
                         will_topic    = WillTopic, 
                         will_msg      = WillMsg, 
                         username      = Username, 
                         password      = Password} = Variable,
                    %io:format("lsx CONNACK_ACCEPT WillMsg  ~p ~n",[WillFlag]),
                    send_register(WillFlag, ClientId, WillTopic, WillMsg);
                {error, Reason}->
                    lager:error("~s@~s: username '~s', login failed - ~s",
                                    [ClientId, emqttd_net:format(Peername), Username, Reason]),
                    {?CONNACK_CREDENTIALS, State1}
                                                        
            end;
        ReturnCode ->
            {ReturnCode, State1}
    end,
        %% Run hooks
    emqttd_broker:foreach_hooks(client_connected, [ReturnCode1, client(State3)]),
    %% Send connack
    send(?CONNACK_PACKET(ReturnCode1), State3);

%%  ignore if have no willflag
send_register(false,_,_,_) ->
   ignore;

%% send to user system
send_register(true,ClientId,WillTopic,WillMsg) ->
    <<A:32,B:32,C:32,D:32>> = crypto:strong_rand_bytes(16),
    Mqttid = list_to_binary([integer_to_list(A,16),integer_to_list(B,16),integer_to_list(C,16),integer_to_list(D,16)]),

    self() ! {subscribe, list_to_binary([WillTopic, "/",  Mqttid]), 0},

    Json = mochijson2:encode([%{clientid, ClientId},
                               %{username,UserName},
                               %{password, PasssWord},
                               %{will_topic, WillTopic},
                               {will_msg,   WillMsg},
                               {mqttid,     Mqttid}]),
 
   %% because pub is faster than sub, I have to send /sys/register then send to $Q/client/$c
     Message = #mqtt_message{qos = 0,
                            topic   = list_to_binary(["/sys/register"]), 
                            payload = iolist_to_binary(Json)},
    emqttd_pubsub:publish(list_to_binary(["$Q/client/", ClientId]), Message).

**Comment by erylee** [comment]
@lsxredrain,  emqttd_mod_autosub just send a 'subcribe' message to client pid,  the message will be handled until all hooks include your code 'emqttd_pubsub:publish'  executed.

**Comment by lsxredrain** [comment]
self() ! {subscribe, list_to_binary([WillTopic, "/",  Mqttid]), 0},     %% ----->>>  first execute
 log time is  13:53:35.162
emqttd_pubsub:publish(list_to_binary(["$Q/client/", ClientId]), Message). %%  --->> then execute 
 log time is 13:53:35.161

so pub is faster than sub at leaste  more than1 ms,  sequence is not  corrected。
in some realtime system，it maybe leaded to confuse .

13:53:35.161 [info] $Q/client/mosqsub/11100-johncenaP PUBLISH to /sys/register: <<"{\"clientid\":\"mosqsub/11100-johncenaP\",\"uid\":\"dsdfsfsd999\",\"sid\":\"276\",\"appid\":\"100000\",\"mqttid\":\"2479193C147669907572D57FC9E6D8ED\"}">>

13:53:35.162 [info] Client mosqsub/11100-johncenaP subscribe [{<<"/tesg/ddd/2479193C147669907572D57FC9E6D8ED">>,0}]. Granted QoS: [0]

**Comment by erylee** [comment]
emqttd_pubsub:subscribe is a synchronous call. If you call the subscribe first, the broker assure it will execute first. Now the problem is your pub/sub messages are sent to two erlang processes asynchronously, so the sequence is time depended.

"a systemid for every session" is a great idea! let's discuss it in detail.

**Comment by lsxredrain** [comment]
![image](https://cloud.githubusercontent.com/assets/5266023/8006105/37a5c80e-0bc3-11e5-832e-981eaccc5838.png)
as the above picture
one connect then be ready for everything。
use usename，password，and some business information in willtopic and willMsg， emqttd can give 
this use some topic privilege to do something。
user can use system id to do what he like, and some adminstration info can send to $Q/client/$c

**Comment by lsxredrain** [comment]
![Uploading 123.jpg…]()
as the above picture
one connect then be ready for everything。
use usename，password，and some business information in willtopic and willMsg， emqttd can give 
this use some topic privilege to do something。
user can use system id to do what he like, and some adminstration info can send to $Q/client/$c

**Comment by erylee** [comment]
synchronous subscribe in emqttd_mod_autosub.erl:

```
client_connected(?CONNACK_ACCEPT, #mqtt_client{clientid = ClientId, client_pid = ClientPid}, Top|    end.
ics) ->                                                                                         |
    F = fun(Topic) -> emqtt_topic:feed_var(<<"$c">>, ClientId, Topic) end,  
   emqttd_pubsub:subscribe([{F(Topic), Qos} || {Topic, Qos} <- Topics]);
```

**Comment by lsxredrain** [comment]
now is ok,thanks!
sample code:
client_connected(?CONNACK_ACCEPT, #mqtt_client{clientid = ClientId,
                                               client_pid = ClientPid}, Topics) ->
    F = fun(Topic) -> emqtt_topic:feed_var(<<"$c">>, ClientId, Topic) end,
    %[ClientPid ! {subscribe, F(Topic), Qos} || {Topic, Qos} <- Topics],
    emqttd_pubsub:subscribe([{F(Topic), Qos} || {Topic, Qos} <- Topics]),
    Json = mochijson2:encode([ {lsx,list_to_binary("thanks erylee!")},
                              {ts, emqttd_vm:timestamp()}]),
    Message = #mqtt_message{qos     = 0,
                            topic   = list_to_binary(["$Q/client/", ClientId]),
                            payload = iolist_to_binary(Json)},
     emqttd_pubsub:publish(list_to_binary([ClientId]), Message);

test result
21:29:48.290 [info] lsxtest PUBLISH to $Q/client/lsxtest: <<"{\"lsx\":\"thanks erylee!\",\"ts\":1433597388}">>
21:29:48.290 [info] SEND to lsxtest@111.192.141.189:25165: CONNACK(Qos=0, Retain=false, Dup=false, AckFlags=0, RetainCode=0)
21:29:48.290 [info] lsxtest PUBLISH to $Q/client/lsxtest: <<"{\"lsx\":\"thanks erylee!\",\"ts\":1433597388}">>
