### ISSUE TITLE
Latest Docker image (2.3.6) shows version 2.3.5 at startup

### ISSUE THREAD

**Issue by gautaz** [emqtt/emqttd#1561]
#### Environment

- OS: OSX 10.13.4 / Docker 18.04.0-ce-rc2-mac61 (23890)
- Erlang/OTP: 2.3.6
- EMQ: irrelevant for this bug report

#### Description

Running the 2.3.6 Docker image downloaded from the [emqtt.io download page](http://emqtt.io/downloads) logs this line on startup:
```
emqttd 2.3.5 is running now
```

Perhaps a bad link for the `latest` package.

**Comment by ahmadalli** [comment]
this is the docker project's issue. take a look at [this line](https://github.com/emqtt/emq-docker/blob/55a773a8a216c126799a7387de6ed94cd3b7a9bf/Dockerfile#L5): `ENV EMQ_VERSION=v2.3.5`. it's still creating the image using the v2.3.5

**Comment by terry-xiaoyu** [comment]
@gautaz @ahmadalli We'll update the image soon. Thanks !

**Comment by turtleDeng** [comment]
@gautaz @ahmadalli Sorry, it has been updated, please download http://emqtt.io/downloads/latest/docker

**Comment by gautaz** [comment]
Thanks! The right version is now displayed.
