### ISSUE TITLE
emqtt的安全负载是怎么界定的，性能是否可以提升

### ISSUE THREAD

**Issue by bhzhu203** [emqtt/emqttd#1569]
#### Environment

- OS: centos6 
- Erlang/OTP: R20/9.0
- EMQ: 2.3.6

#### Description

*A description of the issue*
emqtt 不是说支持  “单节点100万并发”么   我们新项目节点emqtt的连接数达到
600个ESTABLISHED  CPU load  就达到2.0+ 以上，阿里云网络优化双核4G机器就hold不住了；反之传输数据量相对比较小的老项目emqtt单机（1核1G）阿里云机器 1000个ESTABLISHED ，CPU load基本在0.5 以下。

官方教程中的 “8核心、32G内存”  可以压力测试到 130万是怎么实现的？ 是以超保守CPU负载标准来压测的吗（一般8核服务器的安全负载为8）？  以我们的业务体量来看，新业务要承载1200个连接是不是要8核的服务器？

下面是一个压测的例子负载为2时，双核CPU中eqmtt几乎占满200%

./emqtt_bench_pub -c 1000 -I 10 -t bench/%i -s 2 -h xxxxx

![qq 20180418153345](https://user-images.githubusercontent.com/3523160/38990938-ab54e754-440e-11e8-9502-834121ca5856.png)

我们公司的业务对实时性要求比较高，不知道非安全负载下emqtt传输是否还正常？麻烦解答，谢谢

**Comment by terry-xiaoyu** [comment]
**Close it as we don't support Chinese issues.**

But for your question, check out our bench_mark report here:
https://github.com/emqtt/emq-xmeter-en

If your concern is mostly on the throughput performance, then refer to [throughput.rst ](https://github.com/emqtt/emq-xmeter-en/blob/master/throughput.rst).
