### ISSUE TITLE
Feature Request - the cluster any question

### ISSUE THREAD

**Issue by sailingchen** [emqtt/emqttd#157]
I configure the emqttd cluster and test it , I found the client session  will not be copied to every clusterd node , so every clusterd node is not equal 。

**Comment by erylee** [comment]
Cluster Design: https://github.com/emqtt/emqttd/wiki/Cluster%20Design <https://github.com/emqtt/emqttd/wiki/Cluster%20Design>

Topic tree will be copied to each cluster nod, but clients, sessions and subscriptions are local.

**Comment by sailingchen** [comment]
Cluster 存在这样的问题：
客户端断开一段时间后，连接上一个从未连接过的集群节点A，在断开连接到重新连接上集群节点A这段时间内，在集群A上发布的消息则不到。

当然 Bridge 模式也存在同样问题。

**Comment by erylee** [comment]
客户端session模式连接，断线重连其他Node，那么离线消息收不到。如果有这个需求，可以支持session takeover，接管其他节点的session。

**Comment by sailingchen** [comment]
session takeover 是客户端实现，还是broker 实现，看了一段描述，雾里看花一样：

Client Take-Over

A disconnected client will most likely try to connect again. It could be the case that the broker still has an half-open connection for the same client. In this scenario the MQTT will perform a so-called client take-over. The broker will close the previous connection to the same client (determined by the same client identifier) and establishes the connection with the newly connected client. This behavior makes sure that half-open connection won’t stand in the way of a new connection establishment of the same client.

**Comment by sailingchen** [comment]
我们用于手机app 的PUSH , 看来目前只有从业务分割。

或者app 初始化连接broker 时，连接一次所有节点IP

**Comment by erylee** [comment]
Broker实现的Session Take-Over, 和你上面的文档不同。Broker集群模式下，比如Session之前在A节点，断线重连后从B节点上线；那么把A节点的Session数据，应该传递给B节点的新Session。

**Comment by sailingchen** [comment]
Broker实现的Session Take-Over, 和你上面的文档不同。Broker集群模式下，比如Session之前在A节点，断线重连后从B节点上线；那么把A节点的Session数据，应该传递给B节点的新Session。
______________________________________________
请问emqttd 具本了这个功能吗，相关配置选项有哪些，谢谢。

**Comment by erylee** [comment]
@sailingchen, this feature is not supported now. I could plan in late release if the feature is important in cluster deploy.

**Comment by benjamin658** [comment]
I solved this problem by using haproxy as /api/sessions API load balancer, and polling every broker in the cluster to get the session list, this may not the best solution, but for now I need to know actual number of the sessions... hope it can be supported soon.
