### ISSUE TITLE
run_erl : Erlang closed the connection

### ISSUE THREAD

**Issue by chrizkiran** [emqtt/emqttd#1570]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 20
- EMQ: 2.3

#### Description

emqttd goes down when all the clients gets disconnected.

**Comment by terry-xiaoyu** [comment]
Maybe all connections gone because of the emqttd is crashed? Do you have any `erl_crash.dump` in your log dir? Attach it here with all of your logs if you find one.

Could you describe more about the problem? Such as your testing scenarios, how to reproduce (if you are able to), etc.

**Comment by chrizkiran** [comment]
Hi terry, thanks for the quick response.

There is no error or crash log, the syslog says "run_erl: Erlang closed the connection".

Am doing emqtt benchmark test with 25k subscriptions and 25k publishes each publishing around 8k msgs/sec and when I disconnect the Publish client the emqttd goes down.

**Comment by terry-xiaoyu** [comment]
@chrizkiran 
May I have your system info such as how many CPU cores, physical memory size, etc?

Each of your publisher is publishing 8k messages/sec, to 25k subscribers? And you have total of 25k publishers which will do this one by one?

Try to tune your system and EMQ using steps listed in: http://emqtt.io/docs/v2/tune.html#.

If you till have the same issue, compress and attach your entire `log` dir here.

**Comment by chrizkiran** [comment]
Am using `n1-standard-4 (4 vCPUs, 15 GB memory) `

And yes, Each of my publisher is publishing 8k messages/sec to 25k Subscribers. Each of the client and subscribers are publishing and subscribed to 25k unique topics.

I have followed the same doc to tune the System and Emq.

I will try to attach the log as early as possible.

**Comment by chrizkiran** [comment]
Increased the Disk Storage and the Issue got resolved.

**Comment by hinimix** [comment]
May I ask how to start when it is down. 
It is no listening port when I restart emqx and said below:
Apr  1 11:26:24 emox-dev-0001 run_erl[25692]: Erlang closed the connection.
Apr  1 11:26:27 emox-dev-0001 emqx[26889]: Starting up
Now process is live but no listening port, I can not use it.
