### ISSUE TITLE
Mongo Auth Plugin Not Connecting Automatically to Mongodb after failing once. 

### ISSUE THREAD

**Issue by arihantdaga** [emqtt/emqttd#1573]
#### Environment

- OS:
CentOs 
- EMQ: 
2.3.6

#### Description
AuthMongo Plugin is Not reconnecting with mongodb if failure occur once.
Steps to reproduce. 
Start Broker -> Enable Auth Mongo Plugin -> Kill MongoDb -> Start MongoDB Again -> Now try to connect using your username and password , It wont connect unless we reload the auth mongo plugin.

**Comment by terry-xiaoyu** [comment]
Hi, I'll check this.

**Comment by arihantdaga** [comment]
@terry-xiaoyu Thank you. I think its my bad. I was having 2.3.4. I tested the same thing on 2.3.6 and its working now. Thank you. I am closing this issue.
