### ISSUE TITLE
What is the relationship between a client and a session?

### ISSUE THREAD

**Issue by PiedPieper** [emqtt/emqttd#1583]
How would you describe the relationship between emqttd_client and emqttd_session? It seems like they do very similar things. The client process seems to handle the actual tcp socket, while the session handles sending and routing publishes. Is this correct? What was the design philosophy?

Thanks !

**Comment by terry-xiaoyu** [comment]
Mostly correct. 

The client process is for handling the tcp connection for the client. And there will be one session process created for **each client** to maintain the state (e.g. the message queue, the expiry timer, etc.) of the client. 

If `ClientA` sending a message with `TopicC` which is subscribed by `ClientB`, the message flow will be:

`Client process of ClientA`   ----route(TopicC)--->   `Session process of Client B`   ----deliver--->   `Client process of ClientB`
