### ISSUE TITLE
Push data to 3rd party DB efficiently

### ISSUE THREAD

**Issue by utkarshns** [emqtt/emqttd#1585]
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: R20/9.0
- EMQ: 2.3.7

#### Description
I need to push the oncoming data to influxDB, currently there is a 2-node cluster of emq brokers.

One way to do it would be to write a client app which subscribes to all topics and pushes the data to influxDB and put it on one broker machine, this isn't proper distribution. Putting the client writer on both broker machines and splitting topic subscriptions between the two is not really proper load distribution.

Other way would be to _somehow (maybe a plugin)_ have an async routine which would process each point and write to influxDB (this load should also be handled across the entire cluster).

How do I do this? Any help is appreciated.

**Comment by terry-xiaoyu** [comment]
@utkarshns
I recommend you to go the latter way (the plugin). 

The [shared-subscription](http://emqtt.io/docs/v2/advanced.html#shared-subscription) across the nodes in a cluster is not supported at present, but would be ready in the EMQ 3.0.

If you wrote a plugin, your callback functions would only be invoked on one node (the node on which the event occurs).

**Comment by utkarshns** [comment]
@terry-xiaoyu 
Thanks for the prompt reply.

Setup:
Cluster: emq@node1, emq@node2
TCP connection load balanced with HAProxy.

If I write a plugin and deploy it on both, then:
The remote client publishing the data to emq@node1 will trigger the callback on node1 only and the remote client publishing data to emq@node2 will trigger callback only on node2.
Then onwards the callback functions on both nodes will write the points to the DB. Correct?

**Comment by terry-xiaoyu** [comment]
@utkarshns  Correct.
