### ISSUE TITLE
How to restrict publish and subscribe using ACL and topic permissions

### ISSUE THREAD

**Issue by utkarshns** [emqtt/emqttd#1586]
I have a 2-node emq cluster. I want to restrict clients from subscribing and publishing to the topics which don't concern them. I saw ACL in the docs but that isn't very clear, some light on the topic would be much appreciated.

TL;DR: Help needed in implementing ACL and Topic restriction on clients

**Comment by terry-xiaoyu** [comment]
@utkarshns 

Hi, the doc is here:
http://emqtt.io/docs/v2/guide.html#acl

Start with the simplest one using etc/acl.conf. I'm going to update the commits before the configs as following:
```
%% Allow user with username 'dashboard' to subscribe '$SYS/#'
{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.

%% Allow clients from localhost to subscribe and publish to any topics
{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.

%% Deny clients to subscribe topics which matches '$SYS/#' and the topic exactly equals to '#'. But this doesn't deny topics such as 'abc' or 'abc/d'
{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.

%% Allow all by default
{allow, all}.
```

ACL via databases such as mysql and mongodb should be similar.

You'd better to test your ideas for better understanding. You could use [HiveMQ's WebSocket Client](http://www.hivemq.com/demos/websocket-client/) to do that.

**Comment by utkarshns** [comment]
@terry-xiaoyu
Thank you. This is pretty crisp.

I will give it a go.
