### ISSUE TITLE
Benchmark and performance  any question

### ISSUE THREAD

**Issue by sailingchen** [emqtt/emqttd#159]
emqttd 0.8.3 (192.168.0.1 )
OS: CentOS7  + 16 core CPU  + 96G mem

configrue reference:
https://github.com/emqtt/emqttd/wiki/One%20Million%20Connections

Benchmark tools:
 https://github.com/emqtt/emqttd_benchmark.git

#./run 192.168.0.1 1883 40000 10
........
conneted: 21233
conneted: 21234
[error] [Client <0.14608.1>] CONNACK Timeout!
client 24221 EXIT: {shutdown,connack_timeout}
conneted: 21235
[error] [Client <0.14611.1>] CONNACK Timeout!
client 24220 EXIT: {shutdown,connack_timeout}

top command:
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND 
24485 root      20   0 4410624 1.933g   2760 S 173.9  2.1   9:18.97 beam.smp

before run  benchmark test , delete data/mnesia/* , I found Connections  less than  22K  every time 
and the emqttd  is hold , not response any request.

**Comment by erylee** [comment]
Please check logs of the broker, or discuss benchmark test with @turtleDeng.  He achieved 300K concurrent connections with 2000 messages per second a few days ago.

**Comment by sailingchen** [comment]
emqttd_benchmark

#./run 192.168.0.1 1883 40000 10
conneted: 21988
conneted: 21989
conneted: 21990
conneted: 21991
conneted: 21992
conneted: 21993
conneted: 21994
conneted: 21995
conneted: 21996
conneted: 21997
conneted: 21998
conneted: 21999
conneted: 22000
conneted: 22001
conneted: 22002
conneted: 22003
[error] [Client <0.16915.1>] CONNACK Timeout!
client 23452 EXIT: {shutdown,connack_timeout}
conneted: 22004
[error] [Client <0.16918.1>] CONNACK Timeout!
client 23451 EXIT: {shutdown,connack_timeout}
conneted: 22005
[error] [Client <0.16921.1>] CONNACK Timeout!
client 23450 EXIT: {shutdown,connack_timeout}
conneted: 22006
[error] [Client <0.16924.1>] CONNACK Timeout!
client 23449 EXIT: {shutdown,connack_timeout}

----------------------------------------------------------------------
emqttd_error.log 

11:55:06.453 <0.256.0> [error] large_heap: gcpid = <0.29.0>,[{registered_name,user_drv},{memory,114859432},{message_queue_len,440576},{heap_size,5157867},{total_heap_size,12594997}] 
 [{old_heap_block_size,7427328},{heap_block_size,5157867},{mbuf_size,0},{stack_size,13},{old_heap_size,4213089},{heap_size,1505660}]
11:55:08.645 <0.256.0> [error] large_heap: gcpid = <0.94.0>,[{registered_name,lager_event},{memory,91614496},{message_queue_len,7495},{heap_size,5157867},{total_heap_size,11354202}] 
 [{old_heap_block_size,6189440},{heap_block_size,5157867},{mbuf_size,0},{stack_size,38},{old_heap_size,2335728},{heap_size,1328111}]
11:55:15.920 <0.256.0> [error] large_heap: gcpid = <0.94.0>,[{registered_name,lager_event},{memory,103839640},{message_queue_len,16278},{heap_size,2072833},{total_heap_size,12768184}] 
 [{old_heap_block_size,6189440},{heap_block_size,3581853},{mbuf_size,0},{stack_size,34},{old_heap_size,3663779},{heap_size,1147898}]
11:55:36.066 <0.256.0> [error] large_heap: gcpid = <0.94.0>,[{registered_name,lager_event},{memory,99048392},{message_queue_len,18928},{heap_size,1439468},{total_heap_size,12134819}] 
 [{old_heap_block_size,6189440},{heap_block_size,3581853},{mbuf_size,0},{stack_size,38},{old_heap_size,4811072},{heap_size,1092123}]
11:56:01.735 <0.256.0> [error] large_heap: gcpid = <0.94.0>,[{registered_name,lager_event},{memory,118706832},{message_queue_len,21262},{heap_size,1727361},{total_heap_size,14561782}] 
 [{old_heap_block_size,6189440},{heap_block_size,3581853},{mbuf_size,0},{stack_size,38},{old_heap_size,5903135},{heap_size,1118634}]
11:56:31.685 <0.256.0> [error] large_heap: gcpid = <0.94.0>,[{registered_name,lager_event},{memory,118793152},{message_queue_len,22092},{heap_size,1727361},{total_heap_size,14561782}] 
 [{old_heap_block_size,0},{heap_block_size,10695351},{mbuf_size,0},{stack_size,38},{old_heap_size,0},{heap_size,6313612}]
11:57:02.266 <0.256.0> [error] large_heap: gcpid = <0.94.0>,[{registered_name,lager_event},{memory,142092032},{message_queue_len,22093},{heap_size,2072833},{total_heap_size,17474138}] 
 [{old_heap_block_size,10695351},{heap_block_size,3581853},{mbuf_size,0},{stack_size,38},{old_heap_size,5847945},{heap_size,1076172}]
11:57:33.073 <0.256.0> [error] large_heap: gcpid = <0.94.0>,[{registered_name,lager_event},{memory,118793152},{message_queue_len,22092},{heap_size,1727361},{total_heap_size,14561782}] 
 [{old_heap_block_size,10695351},{heap_block_size,3581853},{mbuf_size,0},{stack_size,34},{old_heap_size,6924057},{heap_size,968758}]

**Comment by erylee** [comment]
Please configure log level of lager in etc/emqttd.config:

 {lager, [
    {colored, true},
    {async_threshold, 1000},
    {error_logger_redirect, false},
    {crash_log, "log/emqttd_crash.log"},
    {handlers, [
        {lager_file_backend, [
            {formatter_config, [time, " ", pid, " [",severity,"] ", message, "\n"]},
            {file, "log/emqttd_error.log"},
            {level, error},
            {size, 104857600},
            {date, "$D0"},
            {count, 30}
        ]}
    ]}
 ]},

**Comment by erylee** [comment]
update wiki: https://github.com/emqtt/emqttd/wiki/One-Million-Connections

**Comment by sailingchen** [comment]
@erylee 
Thankyou very much, it's OK , only change log level 
{lager, [
....
{level, error},
....
]},

**Comment by erylee** [comment]
update [FAQ](https://github.com/emqtt/emqttd/wiki/FAQ), and close this issue
