### ISSUE TITLE
Redis Backend

### ISSUE THREAD

**Issue by bharat-mehta** [emqtt/emqttd#1595]
#### Environment

- OS: Ubuntu
- Erlang/OTP: 
- EMQ: 2.4.2

#### Description

I am trying to set up Redis backend on emqx. The following is the content of file emqx_backend_redis.conf
`
```
## Redis Server xxx.0.0.1:6379, Redis Sentinel: xxx.0.0.1:26379
backend.redis.pool1.server = xxx.0.0.1:6379

## redis sentinel cluster name
## backend.redis.pool1.sentinel = mymaster

backend.redis.pool1.pool_size = 8
backend.redis.pool1.database = 2
## backend.redis.pool1.password =
backend.redis.pool1.channel = mqtt_channel

## backend.redis.pool2.server = 127.0.0.1:6379
## backend.redis.pool2.pool_size = 8
## backend.redis.pool2.database = 1
## backend.redis.pool2.password =

## Expired after seconds, if =< 0 take the default value
backend.redis.msg.expired_after = 3600

## Redis Backend Rules
backend.redis.hook.client.connected.1    = {"action": {"function": "on_client_connected"}, "pool": "pool1"}
backend.redis.hook.client.connected.2    = {"action": {"function": "on_subscribe_lookup"}, "pool": "pool1"}
backend.redis.hook.client.disconnected.1 = {"action": {"function": "on_client_disconnected"}, "pool": "pool1"}
backend.redis.hook.session.subscribed.1  = {"topic": "queue/#", "action": {"function": "on_message_fetch_for_queue"}, "pool": "pool1"}
backend.redis.hook.session.subscribed.2  = {"topic": "pubsub/#", "action": {"function": "on_message_fetch_for_pubsub"}, "pool": "pool1"}
backend.redis.hook.session.subscribed.3  = {"action": {"function": "on_retain_lookup"}, "pool": "pool1"}
backend.redis.hook.session.unsubscribed.1= {"topic": "#", "action": {"commands": ["DEL mqtt:acked:${clientid}:${topic}"]}, "pool": "pool1"}
backend.redis.hook.message.publish.1     = {"topic": "#", "action": {"function": "on_message_publish"}, "pool": "pool1"}
backend.redis.hook.message.publish.2     = {"topic": "#", "action": {"function": "on_message_retain"}, "pool": "pool1"}
backend.redis.hook.message.publish.3     = {"topic": "#", "action": {"function": "on_retain_delete"}, "pool": "pool1"}
backend.redis.hook.message.acked.1       = {"topic": "queue/#", "action": {"function": "on_message_acked_for_queue"}, "pool": "pool1"}
backend.redis.hook.message.acked.2       = {"topic": "pubsub/#", "action": {"function": "on_message_acked_for_pubsub"}, "pool": "pool1"}

## redis commands config
## backend.redis.hook.client.connected.3 = {"action": {"commands": ["SET test_table 10"]}, "pool": "pool1"}
backend.redis.hook.client.connected.3 = {"action": {"commands": ["SET conn:${clientid} clientid"]}, "pool": "pool1"}
```
 When I load the plugin using  
`emqx_ctl plugins load emqx_backend_redis` , I get 

> load plugin error: {emqx_backend_redis,
>                     {bad_return,
>                      {{emqx_backend_redis_app,start,[normal,[]]},
>                       {'EXIT',
>                        {{badmatch,
>                          {error,
>                           {shutdown,
>                            {failed_to_start_child,emqx_backend_redis_sub,
>                             {connection_error,econnrefused}}}}},
>                         [{emqx_backend_redis_app,start,2,
>                           [{file,"src/emqx_backend_redis_app.erl"},{line,17}]},
>                          {application_master,start_it_old,4,
>                           [{file,"application_master.erl"},{line,273}]}]}}}}}

Can anyone help. I am using [http://emqx-enterprise-docs-en.readthedocs.io/en/latest/backends.html#redis-backend](url)

**Comment by terry-xiaoyu** [comment]
hi, are you able to connect to your redis server by `redis-cli -h xxx.0.0.1 -p 6379 -n 2`?

**Comment by bharat-mehta** [comment]
@terry-xiaoyu thanks, I am using redis auth/acl plugin for the mentioned redis server and that works

**Comment by terry-xiaoyu** [comment]
Hi, I am sorry to inform you that configuration via dashboard is not a mature feature, and the implementation would be changed in the future versions. Please use the config files instead.

We (The EMQX Enterprise Team) is working on a new dashboard which is flexible and easy to use.

Issues of community version of EMQ is supported here, and all questions about EMQX could get help from the EMQX's contact person directly.
