### ISSUE TITLE
REST publish API causes to crash the server on specific payload

### ISSUE THREAD

**Issue by yuregir** [emqtt/emqttd#1599]
#### Environment

- OS: Docker image
- Erlang/OTP: Docker image
- EMQ: 2.3.7 docker

#### Description

*Bug in REST publish API (server crashes on specific payload) *
What causes to crash:

POST to api/v2/mqtt/publish

{
    "topic": "test",
    "payload": false,     *****this causes to crash ****
    "qos": 1,
    "retain": false,
    "client_id": "C_1492145414740"
}

Logs:

===== Tue May  8 13:50:15 UTC 2018
13:50:15.010 [error] gen_server <0.4534.0> terminated with reason: no function clause matching emqttd_serializer:serialize_payload(false) line 124
13:50:15.011 [error] CRASH REPORT Process <0.4534.0> with 0 neighbours exited with reason: no function clause matching emqttd_serializer:serialize_payload(false) line 124 in gen_server2:terminate/3 line 1157
13:50:15.012 [error] Supervisor 'esockd_connection_sup - <0.1469.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.4534.0> exit with reason no function clause matching emqttd_serializer:serialize_payload(false) line 124 in context connection_crashed

===== ALIVE Tue May  8 14:05:15 UTC 2018

**Comment by huangdan** [comment]
@yuregir Has been fixed and will be released at v2.3.9.

**Comment by yuregir** [comment]
@huangdan  Thank you
