### ISSUE TITLE
Not creating home directory `/var/lib/emqttd' - wrong message printed during package installation

### ISSUE THREAD

**Issue by brad-plumewifi** [emqtt/emqttd#1604]
#### Environment

- OS: Ubuntu 16.04.3
- Erlang/OTP: 
- EMQ: emqttd-ubuntu16.04-v2.3.8_amd64.deb

#### Description

When installing the package it says "Not creating home directory `/var/lib/emqttd'.

I assume this is a typo that should say "now creating... " since installation of the package actually does create /var/lib/emqttd

**Comment by turtleDeng** [comment]
@brad-plumewifi 
If the  '/var/lib/emqttd/' directory exists,  printed "Not creating home directory `/var/lib/emqttd' message.
