### ISSUE TITLE
Client Connected messages are fired on $sys topic even if the client connection was unsuccessful due to authentication

### ISSUE THREAD

**Issue by arihantdaga** [emqtt/emqttd#1607]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 
2.3.6

In my application i want to keep track of online and offline users/devices for that i came across this feature in emqttd - I am subscribing to the topic, `$SYS/brokers/emq@127.0.0.1/clients/+/connected`
for capturing device connect event in my app and to `$SYS/brokers/emq@127.0.0.1/clients/+/dicconnected` for capturing disconnect event. 
But the problem with this is that device connection event is fired even before authentication was unsuccessful and one disconnect message is published after that. 
for example when i log my messages i get this continously- 

```
$SYS/brokers/emq@127.0.0.1/clients/150da879-f3c5-43c8-8b15-da309d1ab4931526798565999/connected
{"clientid":"150da879-f3c5-43c8-8b15-da309d1ab4931526798565999","username":"testUser","ipaddress":"SOME_IP","clean_sess":true,"protocol":4,"connack":4,"ts":1526818432}
$SYS/brokers/emq@127.0.0.1/clients/150da879-f3c5-43c8-8b15-da309d1ab4931526798565999/disconnected
{"clientid":"150da879-f3c5-43c8-8b15-da309d1ab4931526798565999","username":"testUser","reason":"auth_failure","ts":1526818432}

```

And i keep getting this log continuously hence if i were to store device online status in my database and for some reason credentials is wrong it will keep hogging my database continuously with online = true and online = false queries continuously. 

I think the right manner of publishing message should be only when a client gets connected successfully. Otherwise any random username can be used to connect to the broker and hog the system topic.

**Comment by terry-xiaoyu** [comment]
It is designed to this intentionally for tracking all the connection requests. Verify the value of 'connack' and only update your database if it equals 0.

**Comment by arihantdaga** [comment]
Ohk.. Nice.. Thanks a lot..
