### ISSUE TITLE
how to set rules like this?

### ISSUE THREAD

**Issue by chenxuuu** [emqtt/emqttd#1613]
I looked the document in [http://emqtt.com/docs/v2/config.html#acl]() , now I have a question:

if I want to set a rule like this:
```
allow all subscribe and publish from localhost
deny all subscribe like "/abc/#" or "/abc/+/def" (not include localhost)
allow all subscribe like "/abc/def/12345"
```

how to write the rules?

**Comment by terry-xiaoyu** [comment]
```
{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}. %% for local pub/sub.
{allow, all, subscribe, ["/abc/def/+"]}. %% for all topics matched to "/abc/def/+", the subscription is allowed and the ACL processing stops here.
{deny, all, subscribe, ["/abc/#"]}. %% "/abc/#" is a super set of "/abc/+/def", so we only need to deny "/abc/#"
{deny, all}. %% allowing or denying other topics is up to you
```

Try it yourself and tune your ACL. It is more like tuning a regular expression string before using it.

BTW, using topics prefixed with '/' is not recommended.

**Comment by chenxuuu** [comment]
ummmm, I mean like this:
for all clinets(not include localhost)
subscribe topic "aaa/12345/bbb" : allow
subscribe topic "aaa/23456/bbb" : allow
subscribe topic "aaa/34567/ccc" : allow
subscribe topic "aaa/45678/bbb" : allow
other subscribe topic like "aaa/"+somthing+"/bbb" : allow
subscribe topic "aaa/+/bbb" : deny
subscribe topic "aaa/12345/#" : deny
(deny all subscribe with "+" and "#" symbol ,not include localhost)

**Comment by terry-xiaoyu** [comment]
Write your own plugin then. You could start with [emq-plugin-template](https://github.com/emqtt/emq-plugin-template), and take [auth-mysql ](https://github.com/emqtt/emq-auth-mysql)for example. 

Ignore the auth files as you may only need ACL.

**Comment by terry-xiaoyu** [comment]
Close it now and reopen it if you still have any questions.
