### ISSUE TITLE
clear username cache

### ISSUE THREAD

**Issue by naruto0916** [emqtt/emqttd#1615]
#### Environment

- OS: ubuntu 16.04
- Erlang/OTP: 
- EMQ: 2.3

#### Description
I want to use the emq_auth_username plugin to let client user connect to emq by username/password.
I start the emq_auth_username plugin and add new user by ./bin/emqttd_ctl users add command.
Everything seems OK while I try to connect to emq by the username I create by above command.
But, I try to use  ./bin/emqttd_ctl users list command to show all username and I can't see my created username.
And then, I check the etc/plugins/emq_auth_username.conf file and I don't see anything it change (I don't see the username I create by above command).
And then, I use  ./bin/emqttd_ctl users del command to delete the username I create and the console show "OK".
But, I try to user the username to connect to emq and it still work.
And I try to user the "admin" & "feng@emqtt.io" as username to connect to emq and they are all work.
But, I never add these to username before.
I also restart emq service and restart my pc and the "admin", "feng", and the username I create still work.
Does these username be cache in emq??
Have any way I can remove them??

**Comment by terry-xiaoyu** [comment]
Hi, I used emq 2.3.9, and the emq_auth_username worked as expected in my testing.

```
$ ./bin/emqttd_ctl plugins load emq_auth_username

$ ./bin/emqttd_ctl users add 'feng@emqtt.io' '123456'
$ ./bin/emqttd_ctl users add 'shawn' '123456'

$ ./bin/emqttd_ctl users list
  feng@emqtt.io
  shawn
```

Make sure you've disabled the `mqtt.allow_anonymous` in etc/emq.conf.

The users you created shall be stored permanently on disk, usually under 'data' dir of the EMQ's installation path.

**Comment by naruto0916** [comment]
OK...thank you!!
I think I miss to disable the mqtt.allow_anonymous before.
After I disabled it, everything is OK!!
