### ISSUE TITLE
how to know that a publish is denied?

### ISSUE THREAD

**Issue by wangh09** [emqtt/emqttd#1618]
#### Environment

- OS: macOS
- Erlang/OTP: 
- EMQ: 3.1

#### Description
I used mysql_acl to deny unwanted publishes but got no reply from the server. I'm wondering is there a possible way to know that the topic I'm publishing to is denied by the server? Thanks!
*A description of the issue*

**Comment by terry-xiaoyu** [comment]
open a new one if you still have any questions.
