### ISSUE TITLE
Hardware sizing to serve low to moderate load

### ISSUE THREAD

**Issue by utkarshns** [emqtt/emqttd#1619]
#### Environment

- OS: Ubuntu 16.04 
- Erlang/OTP: R20/9.0
- EMQ: 2.3.9
#### Description

Need to know the desirable server configuration for running EMQTTD in enterprise setting.

My usage is to:
*Receive data from IoT devices over MQTT over TCP (1883)
*Send data to clients over WSS (8084)

All clients connected to the broker are subjected to MongoACL (mongoDB holding the records is on a sufficiently fast machine).

Peak Numbers:
Web browser clients at a given point in time: 5k
Devices sending data: 10k (1 datapoint/second)

I am open to running a cluster setup or a single node and would like to know the hardware requirements for handling such a load.

Everything will be hosted on AWS

**Comment by zhengyupan** [comment]
Hi @utkarshns 
Maybe you can try 4 cores & 8G setup and monitor its load. Since you are on AWS, you can try different setups with ease.
