### ISSUE TITLE
How to get client count

### ISSUE THREAD

**Issue by homerzhou** [emqtt/emqttd#1620]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

My client's clientID have the format `xxxxxxx-MODEL-xxxx`
when client connect emqttd success, it subscribe `1/2/3/xxxxxxx/MODEL/xxxx`

I can get the total client count, but i can't get the every Model client count (i have many Model device) .
Or may be If I can get the subscribe topic count with format `1/2/3/+/MODEL/+` ?

**Comment by terry-xiaoyu** [comment]
There's no built-in support for such kind of requirement.

Do the counting in your own plugin. You could learn how to write one by following [this guide](http://emqtt.com/docs/v2/plugins.html#emq-2-0).

**Comment by terry-xiaoyu** [comment]
Close this for now, you could open a new issue if needed.

**Comment by FranklinRay** [comment]
是否可以在 api/v2/clients/{client_id}增加一个类似REST api，用于查询多个clientId状态？
