### ISSUE TITLE
client 144 EXIT: {shutdown,emfile}

### ISSUE THREAD

**Issue by 571522162** [emqtt/emqttd#1622]
#### Environment

- OS: window10(service)  centos7(Erlang MQTT Benchmark)
- Erlang/OTP: 18 [erts-7.3] [source] [64-bit]
- EMQ: R20/9.3

#### Description

*A description of the issue*
Using instructions at centos7 
./emqtt_bench_sub -h 192.168.1.111 -p 1883 -c 2000 -i 1 -t bench/%i -q 1
success

Using instructions at centos7 
./emqtt_bench_sub -h 192.168.1.111 -p 1883 -c 2000 -i 1 -t bench/%i -q 1

client 144 EXIT: {shutdown,emfile}

Dashboard info:
mqtt:tcp Max Clients：102400
Sessions/Max：2018
Clients/Max：2018
Topics/Max：1012
subscribers/Max：1012

**Comment by terry-xiaoyu** [comment]
Have you tuned your system configurations? http://emqtt.io/docs/v2/tune.html

**Comment by terry-xiaoyu** [comment]
Your EMQ is running on centos7 not a windows 10, right? 

Could be the 'net.core.somaxconn' setting? Try to slow down the connecting speed of the client, and enlarge the MEM of your system.  Our recent testing result shows 1G can support 20K concurrent connections.

**Comment by 571522162** [comment]
thk,slow down the connecting speed of the client

**Comment by Gilbert-Wong** [comment]
So has your problem been resolved ?

**Comment by 571522162** [comment]
The problem is finally solved

**Comment by larseen** [comment]
@571522162 what was the cause of this issue? 
Seeing the same errors, but cannot find the cause of it.

**Comment by evgenyvasilchenko** [comment]
> The problem is finally solved

Hello! Can you please let us know how did you solve the issue?
Thanks!

**Comment by sshhawwnn** [comment]
> The problem is finally solved

Hello, can let us know how did you solve the issue?
