### ISSUE TITLE
Clustering question

### ISSUE THREAD

**Issue by archerian** [emqtt/emqttd#1623]
Thanks for working on this great project! From reading the documentation, it seems to me (I might be mistaken) that having two emqtt nodes makes for high availability as more clients are serviced with the additional nodes, what about reliability in case one node goes down? 

Suppose I have a bunch of clients connected to a node, if that node goes down, those clients lose their connection? They are not transferred to the other nodes, so having that failover/reliability feature needs client logic? What would be the recommended practice here? I have a messaging bus with clients doing pub/sub running via emqtt, my goal is to not let the bus be the single point of failure.

Thanks!

**Comment by emqplus** [comment]
@andrewchambers 

1. The EMQ cluster is usually deployed behind a LB such as HAProxy. The MQTT client on device connects to the public address of the LB:

![Deploy](http://emqx-enterprise-docs-en.readthedocs.io/en/latest/_images/deploy_5.png)

2. The clients which disconnected from the broker for one EMQ node is down, can reconnect to the same address of LB after a period of delay.

3. The EMQ cluster maintains a global routing table on all the nodes. If one node is down, the other nodes just cleanup the routing table and continue to work well.

**Comment by archerian** [comment]
Thanks for the quick reply. Is there any mechanism available without the use of an external Load Balancer? My guess is the load balancing act of selecting the available node will have to moved to client logic? Just trying to keep the number of pieces to a minimum :)

**Comment by utkarshns** [comment]
Client side randomizer would be a thing but you will have to update the list of nodes in the client app whenever a change occurs in the cluster.
I am personally using HAProxy (leastconn) and balancing both ssl and wss, works well.
Netsplit b/w cluster nodes is something to think about though.

**Comment by archerian** [comment]
thanks @utkarshns .. I was looking at HAProxy based on the earlier suggestion, I'm new to using a LB for MQTT. So only the incoming messages go through the LB? The publish part then is routed by one of the nodes directly to the client or does ALL traffic go via the LB?

**Comment by utkarshns** [comment]
In my setup all the traffic goes through the LB.
Checked this using the Security Groups on AWS. Also the clients tab in Emq Dashboard shows every clients' IP to be the LB's IP.

@terry-xiaoyu It would be great if you can help us configure HAProxy to handover the connection to the broker itself, so the HAProxy only allots the node and doesnt handle the connection itself.

**Comment by terry-xiaoyu** [comment]
@utkarshns hi, I don't think it is an option to 'handover' the TCP connections to the broker as HA works as an L4 reverse proxy.

BTW, you could use [Proxy Protocol](https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#5.2-send-proxy) to avoid the real client size IP being hidden by the proxy.

@archerian Although server-side load balancing is the recommended method, you would also benefit from the 'client-side' load balancing, because in this way you're able to control which group of users connect to which node. This will reducing the internal message passing between the node if the groups are well designed, but with the drawback of more complicated client side logics. 

So it depends, if you just want to make things done the simplest way, use server side proxy. Otherwise go for the client side load balancing.

**Comment by archerian** [comment]
It would be great if the clustering strategy used by EMQTT (or MQTT in general) allows for the same client to connect to both or more nodes (maybe with the same clientID) and pub/sub to both. The nodes would then share the intelligence among them to know it's from the same client and hence take only 1 copy of the pub for delivery. For subscribe, the nodes again will have the logic to know both these connections are from the same client and send only 1 copy of the message to either of the connections. Might be complicated, but something like how mongoDB clients allow connection to multiple IPs in the replicaset and manage the connection as a single logical one but serviceable by the current master but with seamless failover to the next elected master. This will require client side change too, perhaps beyond the scope of MQTT at all. 

I understand the need for a LB from an availability and scale out perspective, however the LB is in itself another point of failure and it seems logical for the MQTT nodes to offer this service. Just a thought :-)

**Comment by zhengyupan** [comment]
@archerian Hi, I understand you idea. But according the the MQTT standard, the ClientID is unique in a broker, when a second connection from the same client with the same ClientID comes in, a reasonable handling is to drop the first connection with the same ID. Keeping multiple links with same id could be a non standard implementation. 
On the other hand, to achieve your idea, there will be lot of extra logic put into the implementation. Like how much connections from the same id are allowed? What if when a link is broken and the client try to reconnect, is there a way the broker distinguishes if it is a reconnection or a multiple connection? And handling multiplication of sub/pub, which link should it use to avoid multiple copies of a same message? 
I believe all these extra logics can be avoid by a simple way of maintaining a node list on the client side (if you don't want to use a LB, or you are afraid of introducing the LB is introducing another SPOF). The broker should focus on the performance of message routing.

**Comment by panypopo** [comment]
> @andrewchambers
> 
> 1. The EMQ cluster is usually deployed behind a LB such as HAProxy. The MQTT client on device connects to the public address of the LB:
> 
> ![Deploy](https://camo.githubusercontent.com/b8042f6b576b43cfb2fae34204924ff0a64ed8b6/687474703a2f2f656d71782d656e74657270726973652d646f63732d656e2e72656164746865646f63732e696f2f656e2f6c61746573742f5f696d616765732f6465706c6f795f352e706e67)
> 
> 1. The clients which disconnected from the broker for one EMQ node is down, can reconnect to the same address of LB after a period of delay.
> 2. The EMQ cluster maintains a global routing table on all the nodes. If one node is down, the other nodes just cleanup the routing table and continue to work well.

That means in the "period of delay", the whole cluster is unavaliable ?
