### ISSUE TITLE
Missing  MSVCR120.dll

### ISSUE THREAD

**Issue by Bensuqi** [emqtt/emqttd#1624]
#### Environment

- OS:  Win 7 X64 bit
- Erlang/OTP: 
- EMQ: emqttd-windows7-v2.3.9

#### Description

When Start console ".\bin\emqttd console" , the console not showing up, and the error box showing :

" The Program can't start because MSVCR120.dll is missing from your computer. Try reinstalling the program to fix the program"

I have install VC++ Redistristubeable 2012,2013 and 2015 on my computer.

Is there some procedure I am missing ?

Thanks

**Comment by Gilbert-Wong** [comment]
You can try to reinstall VC++ Redistristubeable 2013 packages or download MSVCR120.dll on this website: https://www.dll-download-system.com/msvcr120_dll.html

**Comment by mikeedwards83** [comment]
Wanted to add a commend to @gilbertwong96  I wonder NEVER recommend downloading DLLs from any third party website such www.dll-download-system.com. This is the easiest way to get a virus or some other malicious software.
