### ISSUE TITLE
Failed to build issue on Windows 7 for x64 architecture

### ISSUE THREAD

**Issue by starlily** [emqtt/emqttd#1628]
Environment

    OS: Windows 7 x64
    Erlang/OTP: 20
    EMQ: 2.3.9

Description

I tried to build eMQTT to be installed on Windows 7 x64 system.

I installed Erlang OTP 20.0 for x64.

I installed MSYS2 for x64.

After that i tried this

git clone -b windows https://github.com/emqtt/emqttd-relx.git

cd emqttd-relx && make

I am getting build error and with this request i have attached the erl_crash.dump logs also.

erl_crash.dump.txt

Below is the console output

$ make
DEP goldrush
make[1]: Entering directory '/home/Z0031CDA/emqttd-relx/.erlang.mk/rebar'
./bootstrap
escript: exception error: no match of right hand side value "Could Not Find C:\msys32\home\Z0031CDA\emqttd-relx\.erlang.mk\rebar\ebin\rebar.beam\r\n"
make[1]: *** [Makefile:12: all] Error 127
make[1]: Leaving directory '/home/Z0031CDA/emqttd-relx/.erlang.mk/rebar'
/home/Z0031CDA/emqttd-relx
{"init terminating in do_boot",{undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,670}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,228}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,229}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,878}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,422}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,122}]},{init,start_it,1,[{file,"init.erl"},{line,1097}]}]}}
init terminating in do_boot ({undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{},{}]},{erl_eval,expr,5,[{},{}]},{erl_eval,expr,5,[{},{}]},{erl_eval,expr_list,6,[{},{}]},{erl_eval,exp

Crash dump is being written to: erl_crash.dump...done
DEP emqttd
DEP emq_modules
DEP emq_dashboard
DEP emq_retainer
DEP emq_recon
DEP emq_reloader
DEP emq_auth_clientid
DEP emq_auth_username
DEP emq_auth_ldap
DEP emq_auth_http
DEP emq_auth_mysql
DEP emq_auth_pgsql
DEP emq_auth_redis
DEP emq_auth_mongo
DEP emq_sn
DEP emq_coap
DEP emq_stomp
DEP emq_plugin_template
DEP emq_web_hook
DEP emq_lua_hook
DEP emq_auth_jwt
DEP emq_lwm2m
make[1]: Entering directory '/home/Z0031CDA/emqttd-relx/deps/goldrush'
make[1]: *** No targets. Stop.
make[1]: Leaving directory '/home/Z0031CDA/emqttd-relx/deps/goldrush'
make: *** [erlang.mk:312: deps] Error 2

I try to build the rebar manually as the following operations:
cd .erlang.mk\rebar
touch ebin/rebar.beam
run bootstrap.bat

But it still not solved, below is the console output:

YANGHAO@YANGHAOZBYFV MINGW64 ~/emqttd-relx
# make
make[1]: 进入目录“/home/YANGHAO/emqttd-relx/deps/goldrush”
make[1]: *** 无目标。 停止。
make[1]: 离开目录“/home/YANGHAO/emqttd-relx/deps/goldrush”
make: *** [erlang.mk:312：deps] 错误 2

Is there any solutions? Thank you!

**Comment by terry-xiaoyu** [comment]
Try to remove the dir '/home/YANGHAO/emqttd-relx/deps/goldrush' and try again. 

If that doesn't work, try to remove the dir '.erlang.mk' and then `make distclean && make `. 

Hope it helps.

**Comment by starlily** [comment]
Remove the dir '/home/YANGHAO/emqttd-relx/deps/goldrush' and make again, goldrush has been solved, thank terry-xiaoyu！
But i get new problems as follows:
=====================================
YANGHAO@YANGHAOZBYFV MINGW64 ~/emqttd-relx
# make
make[1]: 进入目录“/home/YANGHAO/emqttd-relx/deps/goldrush”
make[1]: 离开目录“/home/YANGHAO/emqttd-relx/deps/goldrush”
make[1]: 进入目录“/home/YANGHAO/emqttd-relx/deps/emqttd”
make[2]: 进入目录“/home/YANGHAO/emqttd-relx/deps/cuttlefish”
./rebar get-deps
==> getopt (get-deps)
==> goldrush (get-deps)
==> lager (get-deps)
==> neotoma (get-deps)
==> cuttlefish (get-deps)
./rebar compile
==> getopt (compile)
==> goldrush (compile)
==> lager (compile)
==> neotoma (compile)
==> cuttlefish (compile)
'rebar' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
ERROR: Command [compile] failed!
make[2]: *** [Makefile:17：compile] 错误 1
make[2]: 离开目录“/home/YANGHAO/emqttd-relx/deps/cuttlefish”
make[1]: *** [../../erlang.mk:313：deps] 错误 2
make[1]: 离开目录“/home/YANGHAO/emqttd-relx/deps/emqttd”
make: *** [erlang.mk:312：deps] 错误 2

**Comment by Gilbert-Wong** [comment]
It looks like some problems happens on rebar. Did you install rebar on your system or add rebar to your $PATH environment ?

**Comment by starlily** [comment]
Thank  Gilbert-Wong!
Reintall and set rebar，everything is OK！
