### ISSUE TITLE
Use SSL authentication and mysql ACL

### ISSUE THREAD

**Issue by cerfelix** [emqtt/emqttd#1636]
#### Environment

- OS: windows10
- Erlang/OTP: 
- EMQ: 2.3.9

#### Description
We would like to use SSL authentication without username/password and use emq-auth-mysql plugin to realize mqtt topic ACL. The following operations have been performed.    

- Start emq-auth-mysql plugin.
- Modify file emq.conf 
listener.ssl.external.peer_cert_as_username = cn
listener.ssl.external.certfile ... 
listener.ssl.external.cacertfile...

- Modify mysql table mqtt_user, add certificate cn value as username, password empty.

#### Expected behavior
Client with SSL certificates files can connect to EMQ. No username/password is required.

#### Actual behavior
Client failed to connect. Log: Username 'undefined' login failed for username_or_password_undefined.

How to disable mysql password validate? 
Thanks!

**Comment by terry-xiaoyu** [comment]
You don't need the auth right? Then try to comment out the `auth.mysql.auth_query` config line in `etc/plugins/emq_auth_mysql.conf`, this will disable the auth functionality.

**Comment by cerfelix** [comment]
Thanks, it works. 
Can we control the no-password SSL connection permissions through the table mqtt_user ?

**Comment by abser** [comment]
@cerfelix ,
I hope your SSL connection error "No auth module to check!" you resolved. I am also having the same problem. Could you please share how it resolved? Without any auth plugin using the SSL certificate and CN name as username should able to connect to the broker. Do I need to do any other config change to resolve the issue?
Regards
Nurul

**Comment by petergerten** [comment]
@terry-xiaoyu so it this a bug? As you are describing a workaround by disabling auth.
I have same problem as the orignal poster but I need auth for other users that are not using certs.

**Comment by Gilbert-Wong** [comment]
If you guys have the same issue but did not resolve it, please open a new issue with the tempate, give more details

**Comment by petergerten** [comment]
@Gilbert-Wong thanks. Yes I did that here: https://github.com/emqx/emqx/issues/1932
