### ISSUE TITLE
Hooking into message delivered event

### ISSUE THREAD

**Issue by behrad** [emqtt/emqttd#164]
How can I know when a message is acked (puback received on the server)? 
my app wants to update it's models with the delivery timestamp.

P.S. very nice and promising work :+1:

**Comment by erylee** [comment]
Hi Behrad,

Thanks for your suggestion. I am rewriting the code about session(emqttd_session) and queue(emqttd_queue). I will add puback, pubcomp hooks that you could extend the broker later.

Feng

**Comment by behrad** [comment]
great @erylee 

1. Is it good to publish those events into `$SYS` so that all interested clients would sub for them? or should I write Erlang code to get them?

2. Do you have any estimates when it may be available for tests?

**Comment by emqplus** [comment]
@behrad, I forgot to check the issue. The delivered/acked hooks have been implemented in 1.0 release.
 
Demo: https://github.com/emqtt/emqttd_plugin_template/blob/master/src/emqttd_plugin_template.erl
