### ISSUE TITLE
Build from source error

### ISSUE THREAD

**Issue by aloneboat** [emqtt/emqttd#1642]
#### Environment

- OS: Ubuntu 18.04
- Erlang/OTP: 20
- EMQ: 

#### Description

I try to build from source,like this:

> git clone https://github.com/emqtt/emq-relx.git
> 
> cd emq-relx && make
> 

then 

> make[2]: Entering directory '/home/cnssk/emq/emq-relx/deps/gen_coap'
>  XYRL   core_link_scanner.xrl core_link_parser.yrl
> Compiler function leex:compile/3 failed:
> {undef,[{leex,compile,
>               ["/home/cnssk/emq/emq-relx/deps/gen_coap/src/core_link_scanner",
>                "/home/cnssk/emq/emq-relx/deps/gen_coap/src/core_link_scanner",
>                {options,[],"/home/cnssk/emq/emq-relx/deps/gen_coap/src",
>                         undefined,[],1,true,999,[],[],
>                         "/home/cnssk/emq/emq-relx/deps/gen_coap"}],
>               []},
>         {erl_compile,compile_file,4,[{file,"erl_compile.erl"},{line,304}]},
>         {erl_compile,compile3,3,[{file,"erl_compile.erl"},{line,285}]},
>         {erl_compile,'-compiler_runner/1-fun-1-',1,
>                      [{file,"erl_compile.erl"},{line,92}]}]}
> make[2]: *** No rule to make target 'gen_coap.d'.  Stop.
> make[2]: Leaving directory '/home/cnssk/emq/emq-relx/deps/gen_coap'
> ../../erlang.mk:312: recipe for target 'deps' failed
> make[1]: *** [deps] Error 2
> make[1]: Leaving directory '/home/cnssk/emq/emq-relx/deps/emq_coap'
> erlang.mk:310: recipe for target 'deps' failed
> make: *** [deps] Error 2
> 

what's wrong with this?

**Comment by Gilbert-Wong** [comment]
I make emq-relx in  ubuntu 18.04 too and it make successfully. The error log shows that there is some thing wrong when compiling the function in gen_coap. Maybe network problem lead to some broken in gen_coap deps.   I suggest you try to delete  `/home/cnssk/emq/emq-relx/deps` directory and remake again.

**Comment by aloneboat** [comment]
I delete /home/cnssk/emq/emq-relx/deps directory and remake again,but still the same error.and I have another coworker has the same problem.

**Comment by aloneboat** [comment]
`
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [kernel-poll:false]

Eshell V9.2  (abort with ^G)

`

**Comment by aloneboat** [comment]
> Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [kernel-poll:false]
> 
> Eshell V9.2  (abort with ^G)

**Comment by Gilbert-Wong** [comment]
Did you install your erlang version from this command `sudo apt install erlang`  or build your erlang version from erlang source code ?

I reinstall  ubuntu server on my  virtual machine  and apt install erlang , then I build emq-relx successfully again.

**Comment by aloneboat** [comment]
I'm not familiar with Erlang. I was just install something refer this [https://github.com/emqtt/emqttd/issues/520](url),I will try again with that you said:`apt install erlang`

**Comment by aloneboat** [comment]
I run the: `apt install erlang`,then make again,then successfuly,thank you for your help @Gilbert-Wong

**Comment by Gilbert-Wong** [comment]
If you

**Comment by Gilbert-Wong** [comment]
If you want to build your Erlang edition from source code . I recommend you to use [kerl](https://github.com/kerl/kerl) to build and install.
