### ISSUE TITLE
Why does EMQTT broker node have high Disk I/O usage?

### ISSUE THREAD

**Issue by venks-warrior** [emqtt/emqttd#1648]
OS: Linux
Erlang/OTP: OTP
EMQ: 2.2 

I am observing high disk I/O usage on my emqtt node. Tried disabling the logs on node and still seeing high disk I/O usage on the node.I am using Qos0,1,2 for message transfers and mysql plugins for auth.Could you please let me know in what cases there can be high disk i/o seen?

**Comment by terry-xiaoyu** [comment]
Is is probably your mysql. 

Would you check which process has the highest I/O usage? Using [iotop](http://guichaz.free.fr/iotop/) for example.

**Comment by venks-warrior** [comment]
We have caching enabled on the mysql quth queries too. FYI. will check iotop and get back.

**Comment by venks-warrior** [comment]
please refer to the iotop command output.
![screenshot from 2018-06-26 15-03-12](https://user-images.githubusercontent.com/29368745/41907180-b6ffded6-795d-11e8-8daf-87fc7267a480.png)

There are two processes writing to disk.Both are of emqtt process.May i know what is this process with TID 23164 which is writing to disk?

**Comment by terry-xiaoyu** [comment]
I'm not sure what file emqttd is writing. 

You could get the PID of emq (the `beam` process), then use `lsof -p $PID` to see all the files opened (only pay attention on the regular files). And then check the increasing speed of those files.

Most likely it is the `log` dir or the `data/mnesia` dir.

**Comment by terry-xiaoyu** [comment]
you could reopen this if you still have questions.
