### ISSUE TITLE
Question: Any plans for replicating session information?

### ISSUE THREAD

**Issue by mknj** [emqtt/emqttd#1651]
#### Description

MQTT Sessions are a great mean to guarantee message delivery in case of communication problems ( i.e. unreliable/wireless client connections and node failure)

The documentation states that session information is not shared between nodes.

So unfortunaltely QOS1/2 does not work when the client connects to a different or restarted broker after communication loss. This makes QOS1/2 nearly useless, as the given guarantees are not fullfilled.

Are there any plans to share session information across nodes? (i.e. in flight QOS 1/2 message state)

I personally think that replication is more important than persisting. 
Replication would guarantee correct sessioning as long as there is no simultaneous power loss or shutdown of all cluster nodes.

Persisting is more relevant in a single-broker environment. But I hope that anyone seriously talking about quarantees is using a cluster and some means of UPS.

btw. emqttd clusters work great with "cleansession=true" and retained state ;)

**Comment by terry-xiaoyu** [comment]
You could reopen this if you still have questions.
