### ISSUE TITLE
Client Subscribe Asynchronously

### ISSUE THREAD

**Issue by homerzhou** [emqtt/emqttd#1653]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

Hi:
    I have emqttd cluster, the cluster node is in 'US', 'Asia'..., If client subscribe to 'US' node, the client will receive subscribe success quickly, but it can not receive publish data; I think it is because the subscribe info should 'sync' to Other emqttd node.
   If i set `mqtt.pubsub.async = false`, Is it mean client will get subscribe success after every emqttd have sync the subscribe info?

**Comment by terry-xiaoyu** [comment]
This configuration is deprecated and about to be removed. It is not used in the current version.

Did you mean you were not able to receive messages from the other node? You could check the connectivity using `./bin/emqttd_ctl cluster status`. And change the log level to 'debug' to see the detailed info.

**Comment by terry-xiaoyu** [comment]
you could reopen this if you still have questions.
