### ISSUE TITLE
how to update or delete subscription of client by build in rest-api

### ISSUE THREAD

**Issue by krittanon-w** [emqtt/emqttd#1654]
#### Environment

- Erlang/OTP: 2.3.9

#### Description
for this document [REST-API create-subscriptions](http://emqtt.io/docs/v2/rest.html#subscriptions)
it has list and create function. Did Emq have a delete subscription of client or unsubscription ? 
If Emt has no this function in this version 2.3.9, Will it have in next version?

**Comment by Gilbert-Wong** [comment]
Emqttd support to perform unsubscription by using rest-api ,  something important haven't been written into the document. Sorry for that and we would add related instruction into the document as soon as possible.

**Comment by Gilbert-Wong** [comment]
Hi, Krittanon-w! The rest api doc has been updated, you can read this doc on official site. The  rest api which get configs has bugs in emqtt v2.3.9 and it has been fixed. It will run correctly in  the release of v2.3.10.
