### ISSUE TITLE
not see convert from mqtt to lwm2m

### ISSUE THREAD

**Issue by jazzyict** [emqtt/emqttd#1662]
Chrome browser

http://emqtt.io/docs/v2/lwm2m.html

Convert between MQTT and LWM2M
Commands from mqtt client to LWM2M device is carried in following topic:

And mqtt payload will be a json format data which specifies the command. Please refer to emq-lwm2m document for details.

Response from LWM2M device to mqtt client is carried in following topic:

And mqtt payload will be a json format data which specifies the command. Please refer to emq-lwm2m document for details.

Not see following topic.  Cannot find emq-lwm2m document  as well.

**Comment by Gilbert-Wong** [comment]
You can find it in this [repo](https://github.com/emqx/emqx-lwm2m), it is integrated in enterprise edition of emqtt. If you want to use this, contact our boss @emqplus  please.
