### ISSUE TITLE
ClientId wildcard in acl.conf

### ISSUE THREAD

**Issue by Think7** [emqtt/emqttd#1672]
#### Environment

- OS:  Windows Server 2016
- Erlang/OTP: 20
- EMQ: 2.3.9

#### Description

ClientId wildcards don't appear to work when specifying rules in acl.conf.

The following rule does not allow the user to subscribe to topics that include their ClientId.

`{allow,	{user, "testuser"}, 		subscribe, 		["app/data/response/+/%c"]}.
`

**Comment by Gilbert-Wong** [comment]
EMQ does not support to use %c as wildcard.

**Comment by Think7** [comment]
Understood!

So for this authentication scheme, it is necessary to use one of the DB plugins?
