### ISSUE TITLE
Build from source fails while building COAP

### ISSUE THREAD

**Issue by aruldd** [emqtt/emqttd#1687]
#### Environment

- OS: Raspbian stretch lite
- Erlang/OTP: 21 [erts-10.0] [source] [smp:4:4] [ds:4:4:10] [async-threads:1]
- EMQ: latest
- Hardware: Raspberry Pi 3 B+
#### Description

> 
> make[1]: Entering directory '/home/pi/emqttd-relx/deps/emq_coap'
>  DEP    gen_coap
> make[2]: Entering directory '/home/pi/emqttd-relx/deps/gen_coap'
>  XYRL   core_link_scanner.xrl core_link_parser.yrl
> Parsing file src/core_link_scanner.xrl, contained 8 rules.
> NFA contains 45 states, DFA contains 18 states, minimised to 12 states.
> Writing file src/core_link_scanner.erl, ok
>  DEPEND gen_coap.d
>  DEPEND gen_coap.d
>  ERLC   coap_channel.erl coap_channel_sup.erl coap_channel_sup_sup.erl coap_client.erl coap_dtls_listen.erl coap_dtls_socket.e$l coap_message.erl coap_message_parser.erl coap_observer.erl coap_resource.erl coap_responder.erl coap_responder_sup.erl coap_$erver.erl coap_server_content.erl coap_server_registry.erl coap_test.erl coap_transport.erl coap_udp_socket.erl core_iana.erl $ore_link.erl core_link_parser.erl core_link_scanner.erl
> src/coap_channel.erl:76: Warning: call to crypto:rand_bytes/1 will fail, since it was removed in 20.0; use crypto:strong_rand_$ytes/1
> src/coap_channel.erl:164: Warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
> src/coap_channel.erl:165: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
> src/coap_client.erl:127: Warning: variable 'ChId' is unused
> src/coap_dtls_socket.erl:47: Warning: ssl:ssl_accept/1: deprecated; use ssl:handshake/1 instead
> src/coap_transport.erl:159: Warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
> src/coap_transport.erl:160: Warning: random:uniform/1: the'random' module is deprecated; use the 'rand' module instead
> Old inliner: threshold=0 functions=[{yeccpars2_22_,1},
>                                     {yeccpars2_20_,1},
>                                     {yeccpars2_19_,1},
>                                     {yeccpars2_18_,1},
>                                     {yeccpars2_17_,1},
>                                     {yeccpars2_16_,1},
>                                     {yeccpars2_13_,1},
>                                     {yeccpars2_11_,1},
>                                     {yeccpars2_10_,1},
>                                     {yeccpars2_8_,1},
>                                     {yeccpars2_6_,1},
>                                     {yeccpars2_2_,1}]
> Old inliner: threshold=0 functions=[{yyaction_7,2},
>                                     {yyaction_6,2},
>                                     {yyaction_5,1},
>                                     {yyaction_4,1},
>                                     {yyaction_3,1},
>                                     {yyaction_2,1},
>                                     {yyaction_1,1},
>                                     {yyaction_0,1}]
> APP    gen_coap.app.src
> make[2]: Leaving directory '/home/pi/emqttd-relx/deps/gen_coap'
>  DEPEND emq_coap.d
>  ERLC   emq_coap_app.erl emq_coap_config.erl emq_coap_mqtt_adapter.erl emq_coap_ps_resource.erl emq_coap_ps_topics.erl emq_coap
> _registry.erl emq_coap_resource.erl emq_coap_server.erl emq_coap_sup.erl emq_coap_timer.erl
> src/emq_coap_ps_resource.erl:241: field location_path undefined in record coap_content
> src/emq_coap_ps_resource.erl:260: field location_path undefined in record coap_content
> src/emq_coap_ps_resource.erl:19: Warning: undefined callback function coap_get/4 (behaviour 'coap_resource')
> src/emq_coap_ps_resource.erl:19: Warning: undefined callback function coap_observe/4 (behaviour 'coap_resource')
> src/emq_coap_ps_resource.erl:240: Warning: variable 'LocPath' is unused
> src/emq_coap_ps_resource.erl:273: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang"chapter of
>  the ERTS User's Guide for more information.
> ../../erlang.mk:1174: recipe for target 'ebin/emq_coap.app' failed
> make[2]: *** [ebin/emq_coap.app] Error 1
> ../../erlang.mk:992: recipe for target 'app' failed
> make[1]: *** [app] Error 2
> make[1]: Leaving directory '/home/pi/emqttd-relx/deps/emq_coap'
> erlang.mk:310: recipe for target 'deps' failed
> make: *** [deps] Error 2
> 

Tried installing erlang from both apt and source.

**Comment by Gilbert-Wong** [comment]
The master branch of emqttd does not support to run on erlang/otp 21 now. Please  downgrade your erlang/otp to 20 and rebuild it.

**Comment by aruldd** [comment]
Thank you, Building erlang 20.3 from source and then trying to build worked.
