### ISSUE TITLE
Shared Subscription: $share v/s $queue

### ISSUE THREAD

**Issue by bharat-mehta** [emqtt/emqttd#1689]
#### Environment

- OS: Ubuntu
- Erlang/OTP: NA
- EMQ: 2.3.10

#### Description

Hi Folks,

As per [Shared Subscription](http://emqtt.io/docs/v2/advanced.html#shared-subscription) we can subscribe to a topic in shared mode using _**$share**_ and _**$queue**_ prefix. Are there any differences between the two ways. If yes, what is the impact on performance.

**Comment by Gilbert-Wong** [comment]
Use _**$share**_ prefix you could set a group for multiple subscribers, but _**queue**_ doesn't support  this perform.

**Comment by Gilbert-Wong** [comment]
No, If you use _**$share**_ , it means that you can use multiple groups to do load balancing but if you  use _**$queue**_, it means that it has no groups, so you can think of it as one group. Both of them can do load balancing.  By the way, the mqtt v3.1.1 protocol which emq 2.3.10 implemented does not support shared subscription and the shared subscription isn't supported in emq cluster. In addition, the performance of shared subscription implementation in emq 2.3.10 is not good enough to use. I recommend you not to use shared subscription now. 

Please wait for the release of emqx-3.0  which is a full implementation of mqtt v5.0 and support shared subscription much better.

**Comment by bharat-mehta** [comment]
@Gilbert-Wong  Thanks for your detailed response. Any idea on the emqx-3.0 release time ?

**Comment by Gilbert-Wong** [comment]
I'm not sure. We are developing it and try our best to finish the first release as quick as possible.
