### ISSUE TITLE
 Failed to enable mysql authentication plug-in

### ISSUE THREAD

**Issue by msyxiongzai** [emqtt/emqttd#1691]
#### Environment

- OS: centos6.6
- Erlang/OTP: 
- EMQ: emqttd-centos6.8-v2.3.8

#### Description:  Failed to enable mysql authentication plug-in

*A description of the issue*
![image](https://user-images.githubusercontent.com/12079058/43132605-ec6a70b4-8f6e-11e8-88bf-e33616d0b2a6.png)
![image](https://user-images.githubusercontent.com/12079058/43132709-26f4ba96-8f6f-11e8-9fde-8ac541efbe5f.png)

**Comment by Gilbert-Wong** [comment]
Try to connect your mysql  database on your localhost machine.

**Comment by msyxiongzai** [comment]
successfu lconnection
![image](https://user-images.githubusercontent.com/12079058/43134145-a028b81e-8f73-11e8-9e8e-d642882938a7.png)

**Comment by Gilbert-Wong** [comment]
![image](https://user-images.githubusercontent.com/20479699/43134547-f6993268-8f74-11e8-8160-f3cb155d26d0.png)
What's this you circled? 　Is the database name consistent with the database name in your mysql database ?

**Comment by msyxiongzai** [comment]
The connection failed because of the firewall, Thank you. The problem has been solved
