### ISSUE TITLE
Configure Docker image

### ISSUE THREAD

**Issue by andileeb** [emqtt/emqttd#1692]
#### Environment

- OS: linux
- Erlang/OTP: 
- EMQ: docker (https://github.com/emqx/emqx-docker)

#### How to edit the config (Maybe it's a lack of knowledge in docker

*I am using the docker image to run my emq. I want to edit the config (allow anonymous, etc..), install and configure plugins. So I want to know how to edit these files in the docker image? Or what's the right way to configure my emq docker? (Dockerfile)*

**Comment by turtleDeng** [comment]
@andileeb https://github.com/emqx/emqx-docker#configuration

**Comment by andileeb** [comment]
Thanks, well it was a misunderstanding in Docker.
