### ISSUE TITLE
Patch version not part of emq ubuntu package version

### ISSUE THREAD

**Issue by gbrehmer** [emqtt/emqttd#1696]
The ubuntu packages have currently only major.minor version set (2.3), so updates with only changes on patch-level does not lead to version differences => packages will not be updated.

**Comment by Gilbert-Wong** [comment]
You have to uninstall old patch-level of emq first , then  reinstall it on ubuntu.

**Comment by Gilbert-Wong** [comment]
Of course loaded_plugins file is overwritten each time. Each time we updated emqttd, we are very likely to update plugins too.

**Comment by gbrehmer** [comment]
but you can not use a package manager/repo like apt

**Comment by Gilbert-Wong** [comment]
Yes, we have not add emq source to ubuntu software repositories. You can use dpkg to install , update and remove emq

**Comment by gbrehmer** [comment]
we are using a self hosted apt mirror / internal repository to maintain sw packages on our nodes (I think all bigger customer have similar setups). And it would be nice if the apt support would be better :)

**Comment by Gilbert-Wong** [comment]
Can’t agree more.   We would add it to our schedule after release of emqx-3.0 .
On Jul 25, 2018, 5:37 PM +0800, gbrehmer <notifications@github.com>, wrote:

we are using a self hosted apt mirror / internal repository to maintain sw packages on our nodes (I think all bigger customer have similar setups). And it would be nice if the apt support would be better :)
