### ISSUE TITLE
how to carry forward web socket publish message over TCP 

### ISSUE THREAD

**Issue by write2jaydeep** [emqtt/emqttd#1704]
#### Environment

- OS: Linux (ubantu)

- EMQ: 2.3.8

#### Description

*A description of the issue*

I am a newbie to this MQTT stuff. I have multiple clients connected through the web socket as well as over TCP. So I would like to forward publish message sent by web socket client to another client which has subscribed over TCP.

is it possible? Please help me.

**Comment by Gilbert-Wong** [comment]
Yes, it is possible.

**Comment by dono1986** [comment]
I'm also interested in an answer how to this. I'm digging through the docs but i'm still not sure, how to handle this task. As the data in my software can come from several platforms (angular, android, wpf, qt, ...), this functionality is crucial. It can't be this hard...

**Comment by Gilbert-Wong** [comment]
@write2jaydeep  You need to let another client which has subscribed over TCP subscribe the topic where publisher client publish message.

Execute `emqttd_ctl listeners`, you would see that emqttd has listened tcp connection on 1883 port.

**Comment by write2jaydeep** [comment]
@Gilbert-Wong Thanks!
I have one client which is connected to TCP(1883) and has subscribed with topic **/emq/test**
Now another client which is connected to WS(8083) has published a message with the same topic **/emq/test**
here published message didn't deliver to 1883 client.

how to fulfill this requirement?

**Comment by dono1986** [comment]
@write2jaydeep Meanwhile i'm tired of waiting. I switched to mosquitto with websocket support. This was kind of a hassle, since the windows version has to be rebuild with websocket support but this shouldn't concern you, since you're using linux. TCP and websocket clients do communicate without any problem now... you could check if this is an option for you. Cheers

**Comment by write2jaydeep** [comment]
@dono1986 Thank you very much, I just tried it and works well. I appreciate your help!
Thank you all.

**Comment by Gilbert-Wong** [comment]
@write2jaydeep  It is strange. I tried as you stated. It has no problem to receive message from 1883 over TCP.
