### ISSUE TITLE
Relationship of github.com/emqtt and github.com/emqx

### ISSUE THREAD

**Issue by vosst** [emqtt/emqttd#1714]
We are aiming to leverage `emqttd` in our production environments. However, when investigating into available auth plugins, we stumbled over the difference between `github.com/emqtt` and `github.com/emqx`. Could you please clarify why there are two top-level organizations and why plugins to the broker seem to have been moved to `github.com/emqx`, although link text still states `github.com/emqtt`.

**Comment by jgrossmac** [comment]
+1

**Comment by Gilbert-Wong** [comment]
The whole projects of `emqtt` will be migrated to the `emqx` in the future and emqttd would be deprecated. This is the emqx road map <https://github.com/emqtt/emqttd/issues/1659>

**Comment by vosst** [comment]
ack and thx, that answers my question. I'll close the issue.
