### ISSUE TITLE
Unable to connect Websocket with SSL

### ISSUE THREAD

**Issue by write2jaydeep** [emqtt/emqttd#1716]
#### Environment

- OS: Ubantu Linux
- Erlang/OTP: 
- EMQ: 2.3.8

#### Description
I have configured wss in emq.conf as per configuration guide. Please find the configuration in this snippet
Now I tried to connect on WSS 8084 port with the tool provided by emqtt http://localhost:18083/#/websocket

but it always prompts **Connect failed on 8084**
I even tried connecting with other WebSocket services with SSL, but it didn't work
Can you please help me to resolve this?

Thanks

##--------------------------------------------------------------------
## External WebSocket/SSL listener for MQTT Protocol
listener.wss.external = 8084
listener.wss.external.acceptors = 4
listener.wss.external.max_clients = 64
 listener.wss.external.zone = external
listener.wss.external.access.1 = allow all
 listener.wss.external.proxy_protocol = off
listener.wss.external.handshake_timeout = 15s
listener.wss.external.keyfile = /etc/emqttd/certs/key.pem

listener.wss.external.certfile = /etc/emqttd/certs/cert.pem

listener.wss.external.verify = verify_none
listener.wss.external.fail_if_no_peer_cert = false

listener.wss.external.backlog = 1024
listener.wss.external.send_timeout = 15s

listener.wss.external.send_timeout_close = on

listener.wss.external.reuseaddr = true

**Comment by Gilbert-Wong** [comment]
First, comment lines which is unnecessary as follows:
```
listener.wss.external.proxy_protocol = off
listener.wss.external.zone = external
listener.wss.external.fail_if_no_peer_cert = false
listener.wss.external.verify = verify_none
listener.wss.external.fail_if_no_peer_cert = false
```
Second, kill emqttd processes by `kill command` and execute `emqttd start` again,
Last, open the `https:// {your ip address}:8084`,
If you see the page like this:
![image](https://user-images.githubusercontent.com/20479699/43760160-e095c1f4-9a53-11e8-873c-f6959a3c15dc.png)
you would be able to  connect websocket with ssl

**Comment by write2jaydeep** [comment]
@Gilbert-Wong Thank you! it works now. I appreciate your help!

**Comment by MarioDarge** [comment]
It does not work
