### ISSUE TITLE
How many topics can be created in EMQ server?

### ISSUE THREAD

**Issue by chunzhenzyd** [emqtt/emqttd#1718]
#### Environment

- OS: Centos
- Erlang/OTP: 20
- EMQ: 2.3.11

#### Description

We have hundreds of thousands of terminals, each terminal(inner-network) can connect to our server(outer-network) ，server will publish some content to terminal(s). So should we create hundreds of thousands of topics? Because each content is related to only one terminal, other terminals shouldn't receive it.

**Comment by Gilbert-Wong** [comment]
Yes, you can create topic like `terminal/$terminalId`

**Comment by chunzhenzyd** [comment]
Hi Gilbert,

Thank you!
But I want to know is there a test to see how many topics can we create for max value?

BR
Jack Zhang

**Comment by Gilbert-Wong** [comment]
Please refer to emqtt_benchmark https://github.com/emqtt/emqtt_benchmark
On Aug 7, 2018, 4:56 PM +0800, chunzhenzyd <notifications@github.com>, wrote:

Hi Gilbert,

Thank you!
But I want to know is there a test to see how many topics can we create for max value?

BR
Jack Zhang

**Comment by chunzhenzyd** [comment]
Hi Gilbert,

I don't think it sovles my problem, it's just a benchmark test for concurrency..

BR
Jack Zhang

**Comment by Gilbert-Wong** [comment]
Yes, sorry for that,  I’m too busy to read your issue carefully this afternoon. In general, emq supported to create and store more than 20,000,000 topics. The specific situation depends on your actual hardware performance.
On Aug 7, 2018, 5:28 PM +0800, chunzhenzyd <notifications@github.com>, wrote:

Hi Gilbert,

I don't think it sovles my problem, it's just a benchmark test for concurrency..

BR
Jack Zhang

**Comment by chunzhenzyd** [comment]
Hi Gilbert,

Thanks! 
Seems EMQ work is very challenging. I used to work in Ericsson, and wrote code with Erlang, I know how difficult to solve Erlang concurrency problem, and mnesia issues.
Thanks again!

BR
Jack Zhang
