### ISSUE TITLE
What's the maximum size of EMQ publish payload?

### ISSUE THREAD

**Issue by chunzhenzyd** [emqtt/emqttd#1719]
#### Environment

- OS: Centos
- Erlang/OTP: 20
- EMQ: 2.3.11

#### Description

What's the maximum size of EMQ publish payload?

**Comment by Gilbert-Wong** [comment]
It depends your hardware performance.

**Comment by Gilbert-Wong** [comment]
Sorry , I misunderstood your issue just now.  The Maximum size of mqtt packet could be configured in `emq.conf` which also means that the maximum size of EMQ  publish payload could also be configured in `emq.conf`
![image](https://user-images.githubusercontent.com/20479699/43764077-06678c7c-9a5f-11e8-84f2-b80db55e6388.png)

**Comment by chunzhenzyd** [comment]
Hi Gilbert,

So I can change mqtt.max_packet_size to any value? Please check this article:
https://blog.csdn.net/chancein007/article/details/77996544
It said mqtt max payload size should < 268435455 bytes (about 256M).

BR
Jack Zhang

**Comment by Gilbert-Wong** [comment]
No, you can't , the article you referred is right. You can configure max packet size in emqttd but the size shoud be less than 268 435 455 bytes.

**Comment by chunzhenzyd** [comment]
Hi Gilbert,

OK, thanks!

BR
Jack Zhang
