### ISSUE TITLE
Pluggable customised authorisation / authentication / ACL.

### ISSUE THREAD

**Issue by dvorobiov** [emqtt/emqttd#172]
Hi, 
Can I please suggest this feature? I would like to auth users by making a database call. In node.js mosca they provide an interface so  you can implement functions for AAA.

Thank you!

**Comment by erylee** [comment]
The broker supports Pluggable Authentication/ACL. Please check these two plugins as example:

 https://github.com/emqtt/emqttd/tree/master/plugins/emqttd_auth_mysql

or

https://github.com/emqtt/emqttd_plugin_mysql

**Comment by lsxredrain** [comment]
emqttd_acl_mysql.erl --- this files
-module(emqttd_acl_mysql).

-include_lib("../../include/emqttd.hrl").

-behaviour(emqttd_acl_mod).

%% ACL callbacks
-export([init/1, check_acl/2, reload_acl/1, description/0]).
-record(state, {user_table, acl_table, acl_username_field, acl_topic_field, acl_rw_field, user_name_field, user_super_field}).

init(Opts) ->
  Mapper = proplists:get_value(field_mapper, Opts),
  State =
    #state{
      user_table = proplists:get_value(users_table, Opts, auth_user),
      user_super_field = proplists:get_value(is_super, Mapper, is_superuser),
      user_name_field = proplists:get_value(username, Mapper, username),
      acl_table = proplists:get_value(acls_table, Opts, auth_acl),
      acl_username_field = proplists:get_value(acl_username, Mapper, username),
      acl_rw_field = proplists:get_value(acl_rw, Mapper, rw),
      acl_topic_field = proplists:get_value(acl_topic, Mapper, topic)
    },
  {ok, State}.

check_acl({#mqtt_client{username = Username}, PubSub, Topic}, #state{user_table = UserTab, acl_table = AclTab, user_name_field = UsernameField, user_super_field = SuperField, acl_topic_field = TopicField, acl_username_field = AclUserField, acl_rw_field = AclRwField}) ->
  Flag = case PubSub of publish -> 2; subscribe -> 1; pubsub -> 2 end,
  Where = {'and', {'>=', AclRwField, Flag}, {TopicField, Topic}},
  Where1 = {'or', {AclUserField, Username}, {AclUserField, "*"}},
  Where2 = {'and', Where, Where1},
  case emysql:select(UserTab, {'and', {UsernameField, Username}, {SuperField, 1}}) of
    {ok, []} ->
      case emysql:select(UserTab, {UsernameField, Username}) of
        {ok, []} -> ignore;
        {ok, _} -> case emysql:select(AclTab, Where2) of
                     {ok, []} -> deny;
                     {ok, _Record} -> allow
                   end
      end;
    {ok, _} -> allow
  end.

reload_acl(_State) -> ok.

description() -> "ACL Module by Mysql".
 

emqttd_auth_mysql.app.erl  -- this file
-module(emqttd_auth_mysql_app).

-behaviour(application).
%% Application callbacks
-export([start/2, prep_stop/1, stop/1]).

-behaviour(supervisor).
%% Supervisor callbacks
-export([init/1]).

%%%=============================================================================
%%% Application callbacks
%%%=============================================================================

start(_StartType, _StartArgs) ->
    Env = application:get_all_env(),
    ok = emqttd_access_control:register_mod(auth, emqttd_auth_mysql, Env),
    emqttd_access_control:register_mod(acl, emqttd_acl_mysql, Env),
    crypto:start(),
    supervisor:start_link({local, ?MODULE}, ?MODULE, []).

prep_stop(State) ->
    emqttd_access_control:unregister_mod(auth, emqttd_auth_mysql), State,
    emqttd_access_control:unregister_mod(acl, emqttd_acl_mysql), State,
    crypto:stop().

stop(_State) ->
    ok.

%%%=============================================================================
%%% Supervisor callbacks(Dummy)
%%%=============================================================================

init([]) ->
    {ok, { {one_for_one, 5, 10}, []} }.

emqttd_auth_myslq.erl --- this file

-module(emqttd_auth_mysql).

-author("Feng Lee <feng@emqtt.io>").

-include_lib("../../include/emqttd.hrl").

-behaviour(emqttd_auth_mod).

-export([init/1, check/3, description/0]).

-record(state, {user_table, name_field, pass_field, pass_hash}).

init(Opts) -> 
    Mapper = proplists:get_value(field_mapper, Opts),
    {ok, #state{user_table = proplists:get_value(user_table, Opts),
                name_field = proplists:get_value(username, Mapper),
                pass_field = proplists:get_value(password, Mapper),
                pass_hash  = proplists:get_value(password_hash, Opts)}}.

check(#mqtt_client{username = undefined}, _Password, _State) ->
    {error, "Username undefined"};
check(#mqtt_client{username = <<>>}, _Password, _State) ->
    {error, "Username undefined"};
check(_Client, undefined, _State) ->
    {error, "Password undefined"};
check(_Client, <<>>, _State) ->
    {error, "Password undefined"};
check(#mqtt_client{username = Username}, Password,
      #state{user_table = UserTab, pass_hash = Type,
             name_field = NameField, pass_field = PassField}) ->
    Where = {'and', {NameField, Username}, {PassField, hash(Type, Password)}},
    io:format("~n~p ~p~n", [UserTab,Where]),
    case emysql:select(UserTab, Where) of
        {ok, []} -> {error, "Username or Password "};
        {ok, _Record} -> ok
    end.

description() -> "Authentication by MySQL".

hash(plain, Password) ->
    Password;

hash(md5, Password) ->
    hexstring(crypto:hash(md5, Password));

hash(sha, Password) ->
    hexstring(crypto:hash(sha, Password)).

hexstring(<<X:128/big-unsigned-integer>>) ->
    lists:flatten(io_lib:format("~32.16.0b", [X]));

hexstring(<<X:160/big-unsigned-integer>>) ->
    lists:flatten(io_lib:format("~40.16.0b", [X])).

plugins.config --- this file

[
{emqttd_dashboard, [
    {listener, 
        {http, 18083, [
            {acceptors, 4},
            {max_clients, 512}]}}
 ]},
{emysql, [
    {pool, 4},
        {host, "localhost"},
        {port, 3306},
        {username, "root"},
        {password, "root"},
        {database, "emqtt"},
        {encoding, utf8}
]},
{emqttd_auth_mysql, [
    {user_table, auth_user},
    {acl_table, auth_acl},
    {password_hash, plain},
    {field_mapper, [
        {username, username},
        {password, password},
        {user_super, is_super_user},
        {acl_username, username},
        {acl_rw, rw},
        {acl_topic, topic}
    ]}
]}
].

mysql script --- this file

CREATE TABLE `mqtt_users` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(60) DEFAULT NULL,
  `password` varchar(60) DEFAULT NULL,
  `is_superuser` tinyint(1) NOT NULL,
  `salt` varchar(20) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mqtt_users_username` (`username`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE auth_acl (
        id int(11) NOT NULL AUTO_INCREMENT,
        topic varchar(100) NOT NULL,
        username varchar(30) NOT NULL,
        rw tinyint(1) NOT NULL,
        PRIMARY KEY (id)
        ) ENGINE=InnoDB AUTO_INCREMENT=66 DEFAULT CHARSET=utf8

**Comment by erylee** [comment]
@dvorobiov, 0.10.0 released with new plugin design and mysql/pgsql auth/ACL plugins.

MySQL Plugin: https://github.com/emqtt/emqttd_plugin_mysql
PgSQL Plugin:  https://github.com/emqtt/emqttd_plugin_pgsql
