### ISSUE TITLE
About ip_local_port_range when doing client test

### ISSUE THREAD

**Issue by chunzhenzyd** [emqtt/emqttd#1729]
#### Environment

- OS: Centos 7
- Erlang/OTP: 20
- EMQ: 2.3.11

#### Description

If set:
sysctl -w net.ipv4.ip_local_port_range="500 65535"

It seems we can only create about (65535-500)/2 ~= 30000 connections while not 60000.
Please check it!

**Comment by chunzhenzyd** [comment]
client tool: emqtt_benchmark

**Comment by turtleDeng** [comment]
@chunzhenzyd Please submit at https://github.com/emqtt/emqtt_benchmark/issues/new
