### ISSUE TITLE
Integration with Kafka.

### ISSUE THREAD

**Issue by dvorobiov** [emqtt/emqttd#173]
I would like to suggest the functionality when mqtt get messages you can re-publish them to Kafka. And if you publish data to some topic in Kafka, the emqtt re-publish them within the broker.

**Comment by erylee** [comment]
@dvorobiov, I agree with you. Let's discuss the issue in detail later. The queue in emqttd should be extended and plugined, and could integrate with RabbitMQ, Redis or Kafka.

**Comment by vleushin** [comment]
Looking forward to it. Could you give some hints how to properly do it? Should it be just plugin with hook or should it be module? I looked at https://github.com/helpshift/ekaf and it looks as good candidate to handle Kafka protocol

**Comment by erylee** [comment]
@huangdan, please check the feature request, and we should write plugins for RabbitMQ, Redis and Kafka Now I think.

**Comment by lsxredrain** [comment]
git clone git://github.com/wooga/eredis.git plugins
then we can use eredis in any files，for example as follow
{ok, C} = eredis:start_link("127.0.0.1", 6379, 0),
{ok, <<"OK">>} = eredis:q(C, ["SET", "foo", "bar"]),
{ok, SetResult} = eredis:q(C, ["SET", "foo", "bar"]),
io:format("~n~p~n", [SetResult]),
{ok, GetReuslt} = eredis:q(C, ["GET", "foo"]),
io:format("~n~p~n", [GetReuslt]),

**Comment by erylee** [comment]
Create https://github.com/emqtt/emqttd_plugin_kafka project and release the first version in 0.11.0

**Comment by vowstar** [comment]
You can try this [emqttd_plugin_kafka_bridge] (https://github.com/vowstar/emqttd_plugin_kafka_bridge) plugin, which can publish messages from emqttd to kafka topic

https://github.com/vowstar/emqttd_plugin_kafka_bridge

**Comment by wuqunfei** [comment]
Hi guys, all these plugins are removed into business version, so you delete all.
so sad, I would like to try the business version, is there any trial-Version to test?
