### ISSUE TITLE
Emq built in mac fail to start

### ISSUE THREAD

**Issue by hongdanyang1991** [emqtt/emqttd#1731]
#### Environment

- OS: mac os sierra  version:10.12.6
- Erlang/OTP:  21
- EMQ: emq-relx master branch

#### Description

git clone https://github.com/emqtt/emq-relx.git
cd emq-relx && make
cd _rel/emqttd && ./bin/emqttd console

Error log:
MacBook-Air:bin HongDanyang$ ./emqttd  console
init terminating in do_boot ({cannot get bootfile,no_dot_erlang.boot})

Crash dump is being written to: erl_crash.dump...done

**Comment by Gilbert-Wong** [comment]
Use Erlang/OTP 20 to build.
