### ISSUE TITLE
user list did not match in api and ctl command

### ISSUE THREAD

**Issue by c0otlass** [emqtt/emqttd#1739]
#### Environment

- OS: mac os
- Erlang/OTP: 20
- EMQ: 2.3.11

#### Description
HI!
i have started emq_auth_username module and add user with ./emqttd_ctl command and "/api/v2/users" rest api.
when i list users they are not same,
```
./emqttd_ctl users list
jack
john
```

api:
```
{
    "code": 0,
    "result": [
        {
            "username": "jim",
            "tags": "admin"
        },
        {
            "username": "admin",
            "tags": "administrator"
        },
        {
            "username": "bob",
            "tags": "user"
        }
    ]
}
```

 in the other hand my mqtt client could connect to emqtt which generate with emqttd_ctl  command!
why user are not same? why user which generate whit api could not connect?

**Comment by Gilbert-Wong** [comment]
The use generated with api is administrator user who could log in the  dashboard. However, the user which created by emqttd_ctl is not administrator user. It is mqtt user which you need to fill the input inbox in the picture as follows:
![image](https://user-images.githubusercontent.com/20479699/44560684-7fb62d00-a783-11e8-98f4-dcef8fd754d1.png)

**Comment by Gilbert-Wong** [comment]
No,  you can also config it in `emqx_auth_username.conf`.
![image](https://user-images.githubusercontent.com/20479699/44578719-f7597b80-a7c6-11e8-8654-7045f9d06804.png)

**Comment by c0otlass** [comment]
Thanks

**Comment by Gilbert-Wong** [comment]
You can also use other auth plugins such as emqx-auth-mongodb , emqx-auth-mysql to persist your user information.
2018年8月24日 +0800 PM7:28 c0otlass <notifications@github.com>，写道：

Thanks

**Comment by c0otlass** [comment]
Thanks, i used mongo plugin and its worked
