### ISSUE TITLE
MQTTException

### ISSUE THREAD

**Issue by sivasrc7** [emqtt/emqttd#1741]
I want to connect my Raspberry Pi with amazon web service. I followed this website https://circuitdigest.com/tutorial/getting-started-with-amazon-aws-for-iot-projects. I'm a beginner on amazon web service. I followed these steps correctly. But I got MQTTException error in MQTT.fx. Someone help me
![capture](https://user-images.githubusercontent.com/42666202/44567938-3caf8600-a792-11e8-9040-41e404e67f2c.PNG)

**Comment by Gilbert-Wong** [comment]
Is it the problem of emqttd ? I supposed you need to open issue on this [project](https://github.com/Jerady/mqttfx-manual)
