### ISSUE TITLE
Banchmark client

### ISSUE THREAD

**Issue by behrad** [emqtt/emqttd#176]
I'm bench marking our node.js based mosca broker, with a simple hand made node.js based client traffic generator.

Is there any possibility to link me to your client/load code/tool ? so than we can share the same benchmark environment ?

**Comment by erylee** [comment]
@behrad, we use https://github.com/emqtt/emqttd_benchmark to do simple benchmark test.

**Comment by behrad** [comment]
nice @erylee I'll try it out.
Have you ever successfully tried to go over 65K client connections with in a single machine? adding extra ip addresses as localAddresses but couldn't get it to work...
that way we need tons of client machines!!!

**Comment by erylee** [comment]
Hi Behrad,

No:) I created 6 nodes on QingCloud(a cloud provider in China), and start about 50k connections on each client node.

It’s very cheap if you only use these nodes for benchmark test. I’d like to share with your project if you want to benchmark Mosca.



Regards
Feng Lee

**Comment by behrad** [comment]
Great @erylee 
I've reached 150K connections on a 12core machine with 12G RAM with Mosca on centos7 so far, but think I can go further with more memory... my limits are clients now, I should test if docker can solve this.

Do you mind sharing kernel/network tunings?

**Comment by behrad** [comment]
this is mine:
```
  fs.file-max = 999999

  net.core.rmem_max = 16777216
  net.core.wmem_max = 16777216
  net.core.rmem_default = 16777216
  net.core.wmem_default = 16777216
  net.core.optmem_max = 2048000
  net.core.somaxconn = 65000
  net.core.netdev_max_backlog = 50000

  net.ipv4.tcp_rmem = 4096 4096 16777216
  net.ipv4.tcp_wmem = 4096 4096 16777216
  net.ipv4.tcp_max_syn_backlog = 30000
  net.ipv4.tcp_max_tw_buckets = 2000000
  net.ipv4.tcp_tw_reuse = 1
  net.ipv4.tcp_fin_timeout = 10
  net.ipv4.conf.all.send_redirects = 0
  net.ipv4.conf.all.accept_redirects = 0
  net.ipv4.conf.all.accept_source_route = 0
  net.ipv4.tcp_slow_start_after_idle = 0
  net.ipv4.ip_local_port_range = 8000 65535

  net.netfilter.nf_conntrack_max = 1000000
  net.netfilter.nf_conntrack_tcp_timeout_time_wait = 30

  vm.min_free_kbytes = 65536
  vm.swappiness = 0
  vm.overcommit_memory = 1
```

**Comment by erylee** [comment]
It's really great. I had thought node.js could not handle too many concurrent connections...

My settings of Linux and Broker for benchmark: https://github.com/emqtt/emqttd/wiki/One%20Million%20Connections 

I will check the detailed kernel parameters and compare with yours later. I reached about 200k connections on a 8core, 32G RAM server with Centos, and one of my friends reached about 300k.

**Comment by behrad** [comment]
how much memory were `emqtt` consuming when reaching 200K? what showed `free -m`

I've written both in node.js and Erlang, and believe both are GOLD :dancer: 
however node.js should be more memory hungry than Erlang optimized VM.

**Comment by behrad** [comment]
> I’d like to share with your project if you want to benchmark Mosca.

so helpful, can I install iojs on them to load my broker instance?

**Comment by erylee** [comment]
About 7~8G RAM. @Behrad, I never use node.js before. could it scale one process on multicores, or start a process on each core?

**Comment by behrad** [comment]
a process on each core!

each node.js process is a single thread (single core) event loop. Using builtin cluster https://nodejs.org/api/cluster.html module you can scale up to multicores, 1 process/core is a normal model for typical apps.

I believe both Erlang pseudo-threads and node's epoll based non-blocking event driven event loop are very powerful concurrency models with their own characteristics.

**Comment by erylee** [comment]
mv to wiki: https://github.com/emqtt/emqttd/wiki/linux-kernel-tuning
