### ISSUE TITLE
A little question between bridge and cluster model

### ISSUE THREAD

**Issue by MQ-EL** [emqtt/emqttd#177]
How did i select model between bridge and cluster? did it has some criteria?

**Comment by erylee** [comment]
Cluster will replicate topic trees, and bridge will not.

https://github.com/emqtt/emqttd/wiki/Cluster-Design <https://github.com/emqtt/emqttd/wiki/Cluster-Design>

https://github.com/emqtt/emqttd/wiki/Bridge <https://github.com/emqtt/emqttd/wiki/Bridge>

Regards
Feng

**Comment by MQ-EL** [comment]
I already readed this two links in many times(forgive my bluntness). 

Does it can ***reconfig*** bridge dynamicly when it has already started?
```erlang
emqttd_bridge_sup:start_bridge(Node, SubTopic)
```
When broker started, it can't know what topic subscribed by device in future. The bridge may need to add/remove some topic in the fly.

BTW, could I use a bridge between two clusters(replicate topic mode) for relay msg? 

Expect your reply!

**Comment by erylee** [comment]
@MQ-EL, we provide admin commands with 'bin/emqttd_ctl'

```
  bridges list                  #query bridges
  bridges start <Node> <Topic>  #start bridge
  bridges stop <Node> <Topic>   #stop bridge
```

Yes, bridge could relay msg between clusters. We hope use cluster and bridge to build complicated broker topology.

Notice that the bridge design is not production ready, and we will improve it later. Any suggestion or bug report is welcome:)

**Comment by MQ-EL** [comment]
I think the replication mode will meet a bottleneck with topic tree increasing. we can narrow the scope of the devices (who need communication with each other) in one cluster, and open the bridge for cross-clusters. But this way may need to change the topic of bridge in the fly, the admin commands may not be the best solution IMG. I hope change the relayed topic of bridge when needed in the runtime by the code :) 

Thanks for your reply!
