### ISSUE TITLE
[bug] can't get any client with http api

### ISSUE THREAD

**Issue by zhitingxie** [emqtt/emqttd#1780]
#### Environment

- OS: ubuntu 16.04.1
- Erlang/OTP: R20/9.0
- EMQ: 2.3.11

#### Description

I have installed my emqttd broker on our private server, it had ran several weeks well, more than 1000 clients are connecting with it to publish or subscribe messages. I always view status of clients and sessions on dashboard web view. But now, there is no any client or session is shown, although my publish/subscribe of clients are working well.

I checked with http api, for example, api/v2/nodes/emq@127.0.0.1/clients, the response message shows no clients. 

current dashboard web view is: 
![image](https://user-images.githubusercontent.com/16298142/44956121-74849f00-aef1-11e8-89ca-2ca20ff56fd2.png)

if i checked with http api, its response message is: 
![image](https://user-images.githubusercontent.com/16298142/44956137-b31a5980-aef1-11e8-8274-c717a60648cf.png)

but, if I checked with mosquitto_sub to subscribe from all publisher, a lot of message is received:
![image](https://user-images.githubusercontent.com/16298142/44956117-6040a200-aef1-11e8-9143-bb435f44d4b6.png)

**Comment by Gilbert-Wong** [comment]
Looks like the the mochiweb integrated in emqttd  crashed.  The code of mochiweb  is too old. And we do not have schedule to maintain it any more. We have migrated from mochiweb to cowboy on emqttd v3.0 - beta.1. On the edtion, I suggest you attach to emqttd shell to restart mochiweb application.

**Comment by zhitingxie** [comment]
@Gilbert-Wong Thanks a lot for your suggestion. 
Is there any log about mochiweb crashed, which can help me to ensure this bug? 
BTW, could you pls tell me how to attach to emqttd shell to restart mochiweb?

**Comment by Gilbert-Wong** [comment]
Try to use `emqttd attach` to get into emqttd shell and execute `application:start(mochiweb).`. It would be ok.

**Comment by zhitingxie** [comment]
@Gilbert-Wong I have tried with your method. It seems not working.
![image](https://user-images.githubusercontent.com/16298142/44970018-48652e80-af82-11e8-9681-c345f3010600.png)

**Comment by zhitingxie** [comment]
this bug is got at the version 2.3.7. it remains after I upgrade to 2.3.11, the latest version

**Comment by Gilbert-Wong** [comment]
Execute `./_rel/emqttd/bin/emqttd_ctl clients list` and look what happened. I do not encounter the problem you mentioned on emqttd 2.3.11. I need  more details.

**Comment by zhitingxie** [comment]
nothing is got

**Comment by zhitingxie** [comment]
![image](https://user-images.githubusercontent.com/16298142/44971489-4ef6a480-af88-11e8-82c8-e5aa6f7d92e7.png)

**Comment by Gilbert-Wong** [comment]
It is odd. Do you have any ideas @turtleDeng ?

**Comment by Gilbert-Wong** [comment]
Make sure you have clients connected to emqttd broker after you upgrade the emqttd from 2.3.7 to 2.3.11.

**Comment by Gilbert-Wong** [comment]
Give me your screenshots which shows that you have clients connected to the broker.

**Comment by zhitingxie** [comment]
when I execute "application:start(mochiweb)." at the first time, the log gives error saying mochiweb already_started. Then I exit erlang shell, try to attach again, the log shows "node is not running"
![image](https://user-images.githubusercontent.com/16298142/44971790-7306b580-af89-11e8-920b-b73ae54879e1.png)
![image](https://user-images.githubusercontent.com/16298142/44971798-7dc14a80-af89-11e8-9935-e4306a6f2ca2.png)

So, I stop the emqttd and start it again, then execute "emqttd attach" to get into shell, and then run the command "application:start(mochiweb).", it works well. But, no improvement is got.

**Comment by zhitingxie** [comment]
this log in this picture is got when I use mosquitto_sub as a clients to receive message from other publish clients. The message is published by clients.

![image](https://user-images.githubusercontent.com/16298142/44971954-11931680-af8a-11e8-8c31-6c7b33a99d57.png)

**Comment by Gilbert-Wong** [comment]
![image](https://user-images.githubusercontent.com/20479699/44990696-6a7fa080-afc4-11e8-8c7f-ecd27782a773.png)
Connect mqtt broker via websocket on dashboard check the overview on your dashboard.

![image](https://user-images.githubusercontent.com/20479699/44990807-d19d5500-afc4-11e8-9933-685761765f87.png)


Are you sure the broker you ran on your vps is emqttd rather than mosquitto?

**Comment by zhitingxie** [comment]
sorry, my broker is mosquitto instead of emqttd. I am confused with when the mosquitto is installed and executed. I have uninstalled mosquitto, and all works well. Thanks very much,I am so sorry for my mistake.
