### ISSUE TITLE
Adding nodes to cluster

### ISSUE THREAD

**Issue by tharanga2006** [emqtt/emqttd#1782]
#### Environment

- OS:  Windows
- Erlang/OTP: 
- EMQ: V 2.3.11

#### Description
I have started 4 nodes in same server using below document details
http://emqtt.io/docs/v2/commands.html

So I'm trying to add 4 nodes to one cluster.
I have used below command to add the nodes .
First I try to add the node 1 and node 2
form node to folder.
emqttd_ctl cluster join emq1@127.0.0.1
it was executed successfully and the node 2 to the cluster

C:\EMQ\emqttd2\bin>emqttd_ctl cluster join emq1@127.0.0.1
Join the cluster successfully.
Cluster status: [{running_nodes,['emq1@127.0.0.1','emq2@127.0.0.1']}]

then I try to add the node 3 to the cluster 
C:\EMQ\emqttd2\bin>emqttd_ctl cluster join emq3@127.0.0.1
Join the cluster successfully.
Cluster status: [{running_nodes,['emq3@127.0.0.1','emq2@127.0.0.1']}]

But It remove the node 1 from my cluster and adding the node3 to it. 

any idea why this happening"

**Comment by jerry-chao** [comment]
emqttd_ctl cluster join will check node is already in cluster and node is running [ekka_cluster](https://github.com/emqx/ekka/blob/411c309ed65b778826ee7d14d0056704e8ca130b/src/ekka_cluster.erl#L29), then stop and clean current cluster info no matter what it is and join the new node [ekka_mnesia](https://github.com/emqx/ekka/blob/411c309ed65b778826ee7d14d0056704e8ca130b/src/ekka_mnesia.erl#L133)

**Comment by tharanga2006** [comment]
Hi Jerry,
So how we can add  my all  four nodes to the cluster. 
Appreciate if you can provide me step by step instructions to add for node to cluster

**Comment by jerry-chao** [comment]
you can join emq1@127.0.0.1 by emq2@127.0.0.1 and emq3@127.0.0.1 and emq4@127.0.0.1 one by one, then the four nodes are in one cluster

**Comment by jerry-chao** [comment]
```
hen I try to add the node 3 to the cluster
C:\EMQ\emqttd2\bin>emqttd_ctl cluster join emq3@127.0.0.1
Join the cluster successfully.
Cluster status: [{running_nodes,['emq3@127.0.0.1','emq2@127.0.0.1']}]
```
this is what you have done, you should do something like this 
```
C:\EMQ\emqttd3\bin>emqttd_ctl cluster join emq1@127.0.0.1
```
you also can join in emq2@127.0.0.1

**Comment by tharanga2006** [comment]
Hi Jerry,
Right on target . thanks.
