### ISSUE TITLE
http://127.0.0.1:8080/api/v2/  HTTP ERROR 404

### ISSUE THREAD

**Issue by chao-cn** [emqtt/emqttd#1785]
#### Environment

- OS: win10
- Erlang/OTP: V8.3
- EMQ: 2.3.11

#### Description
http://127.0.0.1:8080/api/v2/  return HTTP ERROR 404

http://localhost:8080/status
Node emq@127.0.0.1 is started
emqttd is running

*A description of the issue*

**Comment by Gilbert-Wong** [comment]
Please update your Erlang/OTP to version 20.

**Comment by chao-cn** [comment]
emqttd.cmd use emqttd-windows10-v2.3.11\emqttd\erts-8.3\bin\erl.exe the version is  Erlang/OTP 19 [erts-8.3]

**Comment by Gilbert-Wong** [comment]
I'm not familiar with windows package and I did not advise you to use emqttd on windows. In this situation, maybe you did not use http basic authentication to  do request .  The REST API are protected with HTTP Basic authentication.

**Comment by Gilbert-Wong** [comment]
Hi, @chao-cn  , Did you read emqttd documentation or api lists on dashboard? 
There is no such api called `http://127.0.0.1:8080/api/v2/`

![image](https://user-images.githubusercontent.com/20479699/45028065-1a611680-b076-11e8-9e7e-d67dd454917f.png)
