### ISSUE TITLE
http://127.0.0.1:8080/api/v2/ HTTP ERROR 404

### ISSUE THREAD

**Issue by chao-cn** [emqtt/emqttd#1786]
#### Environment

- OS: win10
- Erlang/OTP: V8.3
- EMQ: 2.3.11

#### Description
http://127.0.0.1:8080/api/v2/  return HTTP ERROR 404

http://localhost:8080/status
Node emq@127.0.0.1 is started
emqttd is running

C:\Users\Administrator>curl -v --basic -u admin:public -k http://localhost:8080/api/v2
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Server auth using Basic with user 'admin'
> GET /api/v2 HTTP/1.1
> Host: localhost:8080
> Authorization: Basic YWRtaW46cHVibGlj
> User-Agent: curl/7.53.1
> Accept: */*
>
< HTTP/1.1 404 Object Not Found
< Content-Length: 0
< Content-Type: text/plain
< Date: Tue, 04 Sep 2018 06:51:39 GMT
< Server: MochiWeb/1.0 (Any of you quaids got a smint?)
<
* Connection #0 to host localhost left intact

*A description of the issue*

**Comment by Gilbert-Wong** [comment]
Please  don't open the same issues
