### ISSUE TITLE
http push qos 1/2 not work

### ISSUE THREAD

**Issue by roytan883** [emqtt/emqttd#181]
my client connect to emqttd server with clean flag "false"
but http push qos 1/2 not work, the client can't receive offline message when reconnect.

the log show http push is qos 1/2, but send to client force to qos 0, is it a bug?

15:32:33.760 [info] HTTP Publish: [{"qos","2"},{"retain","0"},{"topic","$Q/client/client-1"},{"message","{\"msgType\":\"String\",\"msgContent\":\"hello-1\"}"}]
15:32:33.761 [info] SEND to client-1@192.168.1.68:40339: PUBLISH(Qos=0, Retain=false, Dup=false, TopicName=$Q/client/client-1, PacketId=undefined, Payload=<<"{\"msgType\":\"String\",\"msgContent\":\"hello-1\"}">>)

15:34:32.788 [info] HTTP Publish: [{"qos","1"},{"retain","0"},{"topic","$Q/client/client-1"},{"message","{\"msgType\":\"String\",\"msgContent\":\"hello-1\"}"}]
15:34:32.789 [info] SEND to client-1@192.168.1.68:40339: PUBLISH(Qos=0, Retain=false, Dup=false, TopicName=$Q/client/client-1, PacketId=undefined, Payload=<<"{\"msgType\":\"String\",\"msgContent\":\"hello-1\"}">>)

also i try mosquitto_pub to publish message to client, also the log shows Qos=0

**Comment by roytan883** [comment]
seems the auto sub $Q/client/xxx force use qos 0
[{<<"$Q/client/ms1">>,0}]. Granted QoS: [0]
can you add a config to sepcify the auto sub qos level?

**Comment by erylee** [comment]
etc/emqttd.config:

    %% Modules
    {modules, [
       
        %% Subscribe topics automatically when client connected
        {autosub, [{"$Q/client/$c", 0}]}

Regards
Feng@emqtt.io

> 在 2015年7月1日，下午3:54，roytan883 <notifications@github.com> 写道：
> 
> Granted

**Comment by roytan883** [comment]
OK, it worked. But i need auto sub 3 qos, then http publish can choose qos 

{autosub, [{"$Q/client/qos0/$c", 0},{"$Q/client/qos1/$c", 1},{"$Q/client/qos2/$c", 2}]}

By the way, how long will a topic expired?

**Comment by erylee** [comment]
@roytan883, {autosub, [{"$Q/client/qos2/$c", 2}]} , then you can publish with 0, 1, 2
