### ISSUE TITLE
is it possible to add support for retained message expiration?

### ISSUE THREAD

**Issue by sufish** [emqtt/emqttd#182]
i know it's not specified by MQTT protocol, but for offline message handling,  it will be very useful if message can be set to expire after some time interval.

**Comment by erylee** [comment]
@sufish, expired fo all retained messages?

**Comment by sufish** [comment]
General expiration for pesistented messages, like retained and QoS1,2, offline messages

**Comment by berrywira** [comment]
same with my problem. +1

**Comment by brangi** [comment]
+1

**Comment by lsxredrain** [comment]
if use redis to stroe message ,it is very easy to support for retained message expiration.

**Comment by erylee** [comment]
Configure the expiration time in etc/emqttd.config:

```
        %% Retained messages
        {retained, [
            %% Expired after seconds, never expired if 0
            {expired_after, 0},

            %% Max number of retained messages
            {max_message_num, 100000},

            %% Max Payload Size of retained message
            {max_playload_size, 65536}
        ]},
```

**Comment by erylee** [comment]
@sufish, @brangi, @berrywira. The feature has been merged to the latest master branch. Please check 
PR: https://github.com/emqtt/emqttd/pull/329

**Comment by berrywira** [comment]
Thanks +1
