### ISSUE TITLE
why erlang server not reply to client socket connect request ?

### ISSUE THREAD

**Issue by lsxredrain** [emqtt/emqttd#183]
as the picture,
tcp socket connect, client try 4-5 times,erlang server no reply
192.168.154.112 is server 
192.168.100.1 is client

![1](https://cloud.githubusercontent.com/assets/5266023/8499422/54827e3c-21c5-11e5-9d86-49792aecdc7b.jpg)

**Comment by lsxredrain** [comment]
hi，erylee，where can I print socket connect packet in emqttd?
I want to know why emqttd spent a minute to reply client socket connect.

**Comment by erylee** [comment]
Start the broker with './bin/emqttd console'.

**Comment by erylee** [comment]
@lsxredrain, resolved?

**Comment by lsxredrain** [comment]
maybe It was caused by improper linux core parm，I modified it to as follow,  I can't reappear it.

kernel.unknown_nmi_panic = 0
fs.file-max = 1000000
vm.swappiness = 10
fs.inotify.max_user_watches = 10000000
net.ipv4.ip_forward = 0
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.default.accept_source_route = 0
kernel.sysrq = 0
kernel.core_uses_pid = 1
net.ipv4.tcp_syncookies = 1
kernel.msgmnb = 65536
kernel.msgmax = 65536
kernel.shmmax = 68719476736
kernel.shmall = 4294967296
net.ipv4.tcp_max_tw_buckets = 6000
net.ipv4.tcp_sack = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_rmem = 4096 87380 4194304
net.ipv4.tcp_wmem = 4096 16384 4194304
net.core.wmem_default = 8388608
net.core.rmem_default = 8388608
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.netdev_max_backlog = 262144
net.core.somaxconn = 65535
net.ipv4.tcp_max_orphans = 3276800
net.ipv4.tcp_max_syn_backlog = 262144
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_synack_retries = 1
net.ipv4.tcp_syn_retries = 1
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_mem = 94500000 915000000 927000000
net.ipv4.tcp_fin_timeout = 1
net.ipv4.tcp_keepalive_time = 30
net.ipv4.ip_local_port_range = 1024 65000

**Comment by lsxredrain** [comment]
old linux core param as follows：

fs.file-max = 1000000
#Increase number of incoming connections
net.core.somaxconn = 65535

net.core.wmem_default = 8388608 
net.core.rmem_default = 8388608 
net.core.rmem_max = 16777216 
net.core.wmem_max = 16777216

net.unix.max_dgram_qlen = 100

net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_timestamps=1
net.ipv4.ip_local_port_range = 1024    65000
net.ipv4.tcp_max_syn_backlog = 81920
net.ipv4.tcp_max_tw_buckets = 200000

**Comment by erylee** [comment]
how many concurrent connections?

**Comment by lsxredrain** [comment]
only two clients kick out each other, and login and logout quickly.

**Comment by erylee** [comment]
please close this issue, thx.
