### ISSUE TITLE
can emqttd rerserve emqttd_cm.er?

### ISSUE THREAD

**Issue by lsxredrain** [emqtt/emqttd#186]
hi, I want to use emqttd_cm:lookup to check clientid is online  or offline,
but in new version, this file is cut, can emqttd  rerserve it?

Client = emqttd_cm:lookup(emqttd_util:bin(ClientId)),

**Comment by erylee** [comment]
Yes, emqttd_cm module will be restored in 0.9.0 normal release. For We start a session for each client, I remove this module first. Then we find these module should be kept and store all clients to display on dashboard.

**Comment by lsxredrain** [comment]
ok，thanks,
how long 0.90 version will be released?
now I have to store these infomation to redis.

**Comment by erylee** [comment]
Will tag 0.9 this evening:)

**Comment by erylee** [comment]
commited
