### ISSUE TITLE
what diffirence between emqttd_pubsub and emqttd_session?

### ISSUE THREAD

**Issue by lsxredrain** [emqtt/emqttd#190]
can give some example for how to use they?

-module(emqttd_pubsub).

-export([create/1,
         subscribe/1,
         unsubscribe/1,
         publish/1]).

%%------------------------------------------------------------------------------
%% @doc Subscribe topic
%% @end
%%------------------------------------------------------------------------------
-spec subscribe({Topic, Qos} | list({Topic, Qos})) -> 
    {ok, Qos | list(Qos)} | {error, any()} when
    Topic   :: binary(),
    Qos     :: mqtt_qos().

%%------------------------------------------------------------------------------
%% @doc Unsubscribe Topic or Topics
%% @end
%%------------------------------------------------------------------------------
-spec unsubscribe(binary() | list(binary())) -> ok.
unsubscribe(Topic) when is_binary(Topic) ->
    cast({unsubscribe, self(), Topic});

%%------------------------------------------------------------------------------
%% @doc Publish to cluster nodes
%% @end
%%------------------------------------------------------------------------------
-spec publish(Msg :: mqtt_message()) -> ok.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-module(emqttd_session).

%% PubSub APIs
-export([publish/2,
         puback/2, pubrec/2, pubrel/2, pubcomp/2,
         subscribe/2, unsubscribe/2]).

%%------------------------------------------------------------------------------
%% @doc Subscribe Topics
%% @end
%%------------------------------------------------------------------------------
-spec subscribe(pid(), [{binary(), mqtt_qos()}]) -> {ok, [mqtt_qos()]}.

%%------------------------------------------------------------------------------
%% @doc Publish message
%% @end
%%------------------------------------------------------------------------------
-spec publish(pid(), mqtt_message()) -> ok.

%%------------------------------------------------------------------------------
%% @doc Unsubscribe Topics
%% @end
%%------------------------------------------------------------------------------
-spec unsubscribe(pid(), [binary()]) -> ok.

**Comment by erylee** [comment]
@lsxredrain,  pubsub sequence: emqttd_client -> emqttd_session -> emqttd_pubusb

If you develop plugins or modules, should call emqttd_pubsub directly

**Comment by lsxredrain** [comment]
thank，I want to hook some topic and publish other message.
