### ISSUE TITLE
emqttd 0.10.0 Feature Reuqest

### ISSUE THREAD

**Issue by emqplus** [emqtt/emqttd#191]
Discuss features of 0.10.0 release in this issue.

**Comment by toh2526** [comment]
Would anyone agree with "shared subscription" support?

with this feature, we can bring up EMQTTD with some workload distribution
which was formerly impossible with most MQTT implementations.
Previously mentioned by this post:
http://knolleary.net/2012/04/11/queuing-with-mqtt/

Some of MQTT implementations which already supports "shared subscription":
IBM MessageSight
https://www.ibm.com/developerworks/community/blogs/c565c720-fe84-4f63-873f-607d87787327/entry/easily_balance_messaging_workload_with_new_ibm_messagesight_v1_1
JoramMQ
http://www.scalagent.com/en/joram-33/technology-36/mqtt-protocol

**Comment by roytan883** [comment]
Enhance HTTP admin feature (eg: I'm a nodejs user, not familar with erlang, enhance HTTP feature can make emqttd easier extending with other language)。
1, HTTP publish message by 'username', not 'clientId'. Because one user can have multiple clientId, this makes application server sending message easier.
2, HTTP query user online status and active status(offline but not expired)
3, HTTP interface support keep-alive, application server can keep long HTTP connection with emqttd, improve performance.

**Comment by roytan883** [comment]
add more wiki about plugins.
1, how to write a plugins, how to hook emqtt event
2, how to integrate plugin with emqttd(the pre-bulid one from your website)

**Comment by lsxredrain** [comment]
add auto subscribe and auto  publish fucntion.
for example.
when connented 
1. auto subscribe /client/$c     here $c is clientid
2. auto publish some message(for example sessionid )  to  /client/$c 
3、client will get sessionid for bussiness.

**Comment by santif** [comment]
hi, lsxredrain
I'm using hooks to provide such funcionality, and it looks pretty
straightforward:

emqttd_broker:hook('client.connected',
{?MODULE, client_connected},
{?MODULE, client_connected, []}).

client_connected(?CONNACK_ACCEPT, #mqtt_client{client_id = ClientId,
client_pid = ClientPid}) ->
  subscribe_to_topics(ClientPid,
my_find_topics_by_client_id_function(ClientId));


glad to know if there is a more convenient way to achieve auto-subscribe
functionality.





--
Santiago

**Comment by erylee** [comment]
@toh2526, I agree that no queue in MQTT is painful for workload distribution. "shared subscription" or "queue" will be implemented in 0.10

**Comment by KrishnaPG** [comment]
Wondering if this has been implemented. Adding workload distribution can enable RPC like features for devices. If already implemented, any info on how to switch it on could greatly help.

**Comment by emqplus** [comment]
Hi @KrishnaPG, The 1.x release supports "$queue/topic" style workload distribution. The enterprise edition of the broker will support local, shared subscriptions in R2 release.

**Comment by KrishnaPG** [comment]
Thank you @emqplus 

You have mentioned 'enterprise edition' - what is it? I was under the impression that this is Apache License. Is this project going to divide into commercial line with divided functionality?
