### ISSUE TITLE
why subcribe then publish will be error?

### ISSUE THREAD

**Issue by lsxredrain** [emqtt/emqttd#192]
in emqtt_mod_autosub.erl  files add follow code.
version 0.9 is not ok, but 0.88 is ok

client_connected(?CONNACK_ACCEPT, #mqtt_client{client_id = ClientId, client_pid = ClientPid}, Topics)
 ClientTopic = emqttd_util:bin(["/client/",  ClientId]),
 emqttd_pubsub:subscribe({ClientTopic, 2}),
 
 Json = mochijson2:encode([{clientid, ClientId},
                              {ts, emqttd_util:now_to_secs()}]),

 Msg = emqttd_message:make(presence,
                              0,
                              emqttd_util:bin(ClientTopic),
                              emqttd_util:bin(Json)),
   
emqttd_pubsub:publish(Msg);

erro log:
17:10:27.646 [critical] Client 192.168.152.31:60391: unexpected info {dispatch,{mqtt_message,undefined,undefined,<<"/client/282fe6c42e37dc141dd39c0754829738">>,<<"282fe6c42e37dc141dd39c0754829738">>,0,false,false,false,<<"{\"clientid\":\"282fe6c42e37dc141dd39c0754829738\",\"ts\":1436865027}">>,{1436,865027,644686}}}

**Comment by huangdan** [comment]
maybe emqttd_message:make return Message Type is not right

**Comment by lsxredrain** [comment]
cleansession flag is 0，
Qos 0 and  Qos 1 is ok
Qos 2 will crash

**Comment by erylee** [comment]
@lsxredrain, the issue is not valid. You should not publish message to self when client connected.

You should hook "client.subscribe.after" in 0.9.x, publish message when the client subscribed topic.
