### ISSUE TITLE
Mysql auth plugin for windows

### ISSUE THREAD

**Issue by titus7lite** [emqtt/emqttd#194]
i am trying to use emqtt on a windows server, which is working great.

Thing is that i am having some issues with the plugins for mysql auth/acl support. i have download both the plugin sources: emysql and emqttd_plugin_mysql into the plugins folder, created the ebin folders inside them, renamed the app.src files to .app and moved them to ebin folder and also erlc compiled the .erl files and moved them to ebin too.
Now i did append the plugins.config to enable both of the plugins, but when i restart emqtt i get:
- load plugin emysql error: {"no such file or directory","emysql.app"}
- load plugin emqttd_plugin_mysql error: {"no such file or directory","emqttd_plugin_mysql.app"}

is it something i am missing because of my luck of experience with erlang or is the issue closer to my OS type?

regards

**Comment by erylee** [comment]
This plugin cannot work in 0.9.0 release, I will fix this issue in 0.9.2.

**Comment by lsxredrain** [comment]
0.90 is ok, emysql and acl is all ok,  i have test.

https://github.com/emqtt/emqttd/issues/172

**Comment by erylee** [comment]
@titus7lite, I released a new plugin design and merged the code to master branch. Could you build by yourself now? The binary package is not available now for I am waiting for emqttd_dashboard ready.
