### ISSUE TITLE
when Qos = 2 , emqttd_session:publish   will crash

### ISSUE THREAD

**Issue by lsxredrain** [emqtt/emqttd#195]
code
ClientTopic = list_to_binary(["/client/", From]),
        Message = #mqtt_message{qos = 2,
                      topic = ClientTopic,
                      payload = emqttd_util:bin(Json),
                      from = list_to_binary([From])},
        emqttd_session:publish(Sess_pid, Message); 

if qos = 0 or 1 no crash
and when qos = 0 or 1, it is use this  function --->  emqttd_pubsub:publish(Msg);
if qos =2 
use this function -->   gen_server:call(Session, {publish, Msg}).

result
10:23:12.058 [error] Session 282fe6c42e37dc141dd39c0754829738 AwaitingRel Timout!
Drop Message:{mqtt_message,undefined,undefined,<<"/client/282fe6c42e37dc141dd39c0754829738">>,<<"282fe6c42e37dc141dd39c0754829738">>,2,false,false,false,<<"{\"type\":\"register\",\"result\":\"0\",\"mqttid\":\"ceb3c14ba34f41aba76f329e7d41ce27\"}">>,undefined}
10:23:13.890 [error] Session f86f256e8d6430930c7497af14f9542c AwaitingRel Timout!
Drop Message:{mqtt_message,undefined,undefined,<<"/client/f86f256e8d6430930c7497af14f9542c">>,<<"f86f256e8d6430930c7497af14f9542c">>,2,false,false,false,<<"{\"type\":\"register\",\"result\":\"0\",\"mqttid\":\"21189329b2cd4fffe40cb7bc4280ab4b\"}">>,undefined}

**Comment by erylee** [comment]
Please use emqttd_pubsub:publish directly.
