### ISSUE TITLE
can send pricture

### ISSUE THREAD

**Issue by dtxlink** [emqtt/emqttd#197]
or audio?

**Comment by dtxlink** [comment]
能传送 图片，音频吗？ or 大小 有限制？

**Comment by erylee** [comment]
Could send image, audio, video with payload of MQTT. 

Max allowed packet size could be configured in etc/emqtt.config:

```
    {mqtt, [
        %% Packet
        {packet, [
            %% Max ClientId Length Allowed
            {max_clientid_len, 1024},
            %% Max Packet Size Allowed, 64K default
            {max_packet_size,  65536}
        ]},
```

**Comment by Joey-Lee** [comment]
> Could send image, audio, video with payload of MQTT.
> 
> Max allowed packet size could be configured in etc/emqtt.config:
> 
> ```
>     {mqtt, [
>         %% Packet
>         {packet, [
>             %% Max ClientId Length Allowed
>             {max_clientid_len, 1024},
>             %% Max Packet Size Allowed, 64K default
>             {max_packet_size,  65536}
>         ]},
> ```

Are there any code examples of send image, audio or video? Thanks a lot.
