### ISSUE TITLE
怎么获取在线列表？

### ISSUE THREAD

**Issue by dtxlink** [emqtt/emqttd#198]
如题

**Comment by huangdan** [comment]
是说所有client数吗？
client的ets表是‘mqtt_client’
可以通过emqttd_vm:get_ets_object(mqtt_client)获得在线列表
在之后的版本有dashboard可以界面查看

**Comment by erylee** [comment]
@dtxlink, you need client statistics or detailed connected clients?

**Comment by dtxlink** [comment]
detailed connected clients

**Comment by erylee** [comment]
emqttd_dashboard will add the JSON/HTTP API. released with 0.10.0

**Comment by erylee** [comment]
Move to https://github.com/emqtt/emqttd_dashboard/issues/8
