### ISSUE TITLE
Update benchmark

### ISSUE THREAD

**Issue by Hades32** [emqtt/emqttd#199]
The benchmark is pretty outdated now (from 0.6 and probably with an old Erlang version). Also, it only shows a single node deployment. If someone really had 1 million clients he surely had a cluster of at least 2 nodes, so that should be the benchmark setup IMHO. I assume that this will affect performance quite significantly. And if not, even better :)

**Comment by erylee** [comment]
okay, will plan a thoroughly benchmark with 0.10.0 release:)

**Comment by erylee** [comment]
move to 0.11.0

**Comment by erylee** [comment]
@Hades32, done in 0.12.0 release: https://github.com/emqtt/emqttd/wiki/benchmark-for-0.12.0-release
