### ISSUE TITLE
群集了，怎么用呀，，救命啊，老大！！

### ISSUE THREAD

**Issue by dtxlink** [emqtt/emqttd#200]
群集了，怎么用呀，，救命啊，老大！！

**Comment by huangdan** [comment]
集群成功了吗？你可以参考下下面这两个wiki
https://github.com/emqtt/emqttd/wiki/Cluster%20Design
https://github.com/emqtt/emqttd/wiki/Cluster

**Comment by erylee** [comment]
@dtxlink, you could join QQ Group: 12222225 to ask for help, this is not a issue really:)
