### ISSUE TITLE
一些疑问，麻烦解答下，感谢!

### ISSUE THREAD

**Issue by hbyscpp** [emqtt/emqttd#201]
1集群模式下，假设有2个节点，A和B。客户端C连接到A节点了，如果A挂了，C是否自动连接到B?session是否会丢失?

2session的持久化支持外部存储吗,比如redis等?

3对于一个topic，支持多个client组成一个group来消费吗，其中group中每个client只接收到部分消息，便于客户端扩展?

4topic的实现，toipc A中假设有10条消息，10个客户端连接，每个客户端消费的进度是不一样的，如何记录client消费的状态呢，每个消费者有一个队列?

5订阅主题的模式匹配是否支持扩展呢?

**Comment by dtxlink** [comment]
客户端C连接到A节点了， A挂了， 
C 不可能连到 B 吧，，不一样的IP,,

**Comment by dtxlink** [comment]
2session的持久化支持外部存储吗,比如redis等?

看他文档好像是扶持。

**Comment by dtxlink** [comment]
toipc A中假设有10条消息
每个客户都存10条。

**Comment by dtxlink** [comment]
结合 zookeeper ？

**Comment by dtxlink** [comment]
lvs?

**Comment by erylee** [comment]
1. 集群模式下，假设有2个节点，A和B。客户端C连接到A节点了，如果A挂了，C是否自动连接到B?session是否会丢失?

答复：Session丢失。

2session的持久化支持外部存储吗,比如redis等?

答复：Session不支持外部存储，如果有好的外部存储建议或方案，会考虑在后续版本加入。

3对于一个topic，支持多个client组成一个group来消费吗，其中group中每个client只接收到部分消息，便于客户端扩展?

答复：类似负载均衡的Queue吗？0.10.0计划支持"Shared Subscription"，实现负载均衡方式向订阅者派发消息。

4topic的实现，toipc A中假设有10条消息，10个客户端连接，每个客户端消费的进度是不一样的，如何记录client消费的状态呢，每个消费者有一个队列?

答复：对，topic A的消息会派发到每个订阅匹配的客户端队列。消费状态可以通过扩展'message.acked'监听纪录。

5订阅主题的模式匹配是否支持扩展呢?

答复：请提单详细介绍。

**Comment by erylee** [comment]
Should move to FAQ later.
