### ISSUE TITLE
emqttd_cluster error with RPC 

### ISSUE THREAD

**Issue by eurus9989** [emqtt/emqttd#203]
Dear, 

When I run command  "emqttd_ctl cluster emqttd@my_disc_node_ip" , there is an error about Remote Procedure Call that make me can't cluster to disc_node immediately. The ram node service emqttd of Ram Node also not running. The error is:  RPC to 'emqttd@my_ip' failed: timeout
How can I avoid this error?

**Comment by erylee** [comment]
please check etc/vm.args.  Start the broker with "-name emqttd@your_node_ip".

**Comment by eurus9989** [comment]
I have already config /etc/vm.args with "-name emqttd@my_node_ip". I use a bash script to do it automatically when the server started. This error happen when I start new node server and cluster it with disc_node. I check all the config but don't see something wrong. I solved it by removed  data/mnesia folder of disc_node server. But it is not what I really want.
