### ISSUE TITLE
how is the cluster forward the message across the nodes?

### ISSUE THREAD

**Issue by zhongjin616** [emqtt/emqttd#205]
hi, there:

i did not find docs which explain how the emqttd cluster works. so i wonder that is emqttd meets these two strategies:

A message only gets forwarded to other cluster nodes if a cluster node is interested in it。this reduces the network traffic tremendously, because it prevents nodes from forwarding unnecessary messages
As soon as a client on a node subscribes to a topic it becomes known within the cluster. If one of the clients somewhere in the cluster is publishing to this topic, the message will be delivered to its subscriber no matter to which cluster node it is connected.
thanks.

**Comment by erylee** [comment]
Yes, same strategies as you described. I will update wiki later: https://github.com/emqtt/emqttd/wiki/Cluster-Design

**Comment by zhongjin616** [comment]
these strategies are cited from [HiveMQ](http://www.hivemq.com/building-a-high-availability-mqtt-cluster/) . thought maybe useful to someone. :)

**Comment by bmcustodio** [comment]
@erylee This doesn't seem to be working as described. I've clustered two nodes (let's call them `n1` and  `n2`). Then, I connected one client to `n1` and another one to `n2`. The client on `n2` subscribed to `topic/test` and when client on node `n1` published to `topic/test`, the message didn't get forwarded to the client on `n2`. Can you confirm this behaviour?

**Comment by erylee** [comment]
@bmcustodio, please describe your issue in detail.

For example, I cluster two nodes:

Name  | Node | MQTT Port
----------- |---------|---------
emqttd1 | emqttd1@127.0.0.1 | 1883
emqttd2 | emqttd2@127.0.0.1 | 2883

Follow steps:

### 1. Start brokers

```
cd emqttd1 && ./bin/emqttd console
cd emqttd2 && ./bin/emqttd console
```

### 2. Cluster 

```
cd emqttd2 && ./bin/emqttd_cluster emqttd1@127.0.0.1
```

### 3. Subscribe on emqttd2

```
mosquitto_sub -p 2883 -t topic/test -q 2
```

### 4. Publish to emqttd1

```
mosquitto_pub -t topic/test -m haha
```

It works well.

**Comment by bmcustodio** [comment]
@erylee This seems to be working now, as of `0.9.3-alpha`. I could not achieve this behaviour with `0.9.1`, however. Was it something introduced on the new release?

**Comment by erylee** [comment]
0.9.3 Release Notes: https://github.com/emqtt/emqttd/releases. No fix for cluster.

Could check cluster nodes by CLI:
 
```
./bin/emqttd_ctl cluster
```

Please close this issue.

**Comment by bmcustodio** [comment]
@erylee I cannot close as I was not the one who originally opened it.

However, and as I said, this was not working previously, so something must have been done about it in a release since `0.9.1`.

**Comment by erylee** [comment]
okay, @bmcustodio,  I will try 0.9.1 later, thanks:)
