### ISSUE TITLE
make dist error

### ISSUE THREAD

**Issue by zhongjin616** [emqtt/emqttd#207]
hi, there.
i try to compile emqttd from source. `gcc version 4.8.4`  `Ubuntu14.04 64bit`. And `erl --version` says:
`Erlang/OTP 17 [erts-6.4] [source-2e19e2f] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]`

just as you said:
`git clone https://github.com/emqtt/emqttd.git`
`cd emqttd && make && make dist`

when i execute `make dist`, it gives an error：
==> gproc (get-deps)
==> goldrush (get-deps)
==> lager (get-deps)
==> gen_logger (get-deps)
==> esockd (get-deps)
==> mochiweb (get-deps)
==> rel (get-deps)
==> emqttd (get-deps)
==> gproc (compile)
==> goldrush (compile)
==> lager (compile)
==> gen_logger (compile)
==> esockd (compile)
==> mochiweb (compile)
==> rel (compile)
==> emqttd (compile)
==> rel (generate)
ERROR: generate failed while processing /home/vagrant/emqttd/rel: {'EXIT',{{badmatch,{error,"lager: Application version clash. Multiple directories contain version \"2.1.1\"."}},
         [{rebar_reltool,generate,2,
                         [{file,"src/rebar_reltool.erl"},{line,53}]},
          {rebar_core,run_modules,4,[{file,"src/rebar_core.erl"},{line,490}]},
          {rebar_core,execute,6,[{file,"src/rebar_core.erl"},{line,415}]},
          {rebar_core,maybe_execute,8,
                      [{file,"src/rebar_core.erl"},{line,299}]},
          {rebar_core,process_dir1,7,[{file,"src/rebar_core.erl"},{line,258}]},
          {rebar_core,process_commands,2,
                      [{file,"src/rebar_core.erl"},{line,90}]},
          {rebar,main,1,[{file,"src/rebar.erl"},{line,58}]},
          {escript,run,2,[{file,"escript.erl"},{line,752}]}]}}
make: *** [rel] Error 1

i'm new to erlang. so could you give a hit how can i resolve this error?

thanks

**Comment by erylee** [comment]
Caused by your erlang environment that there are lager libraries in multiple directories.

Closed.
