### ISSUE TITLE
Error reading /tmp/emqttd/etc/emqttd.config

### ISSUE THREAD

**Issue by zhongjin616** [emqtt/emqttd#208]
hi there:
i use `ubuntu 14.04 64bit` `gcc 4.8.4` `Erlang/OPT 17`
i download emqttd binary file `mqttd-ubuntu64-0.9.2-alpha-20150718.zip` from `http://emqtt.io/downloads`.  and then i do the command as Quick Start say:

Start console
./bin/emqttd console

Start as daemon
./bin/emqttd start

they all gives the same error:

`vagrant@vagrant-ubuntu-trusty-64:/tmp/emqttd$ ./bin/emqttd start

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
Error reading /tmp/emqttd/etc/emqttd.config
{"init terminating in do_boot",{'cannot load',error_handler,get_files}}`

 +++++++++++++++++++++++++++++++++++++++++++++++++++++++

i have the privilege to read and write. the `ls -al` gives the output:

vagrant@vagrant-ubuntu-trusty-64:/tmp/emqttd$ ls -al
`total 92

drwxr-xr-x 11 vagrant vagrant  4096 Jul 24 17:28 .
drwxrwxrwt  5 root    root     4096 Jul 24 17:29 ..
drwxr-xr-x  2 vagrant vagrant  4096 Jul 24 17:28 bin
drwxr-xr-x  2 vagrant vagrant  4096 Jul 24 17:28 data
-rw-r-----  1 vagrant vagrant 49063 Jul 24 17:29 erl_crash.dump
drwxr-xr-x  3 vagrant vagrant  4096 Jul 24 17:28 erts-6.4
drwxr-xr-x  3 vagrant vagrant  4096 Jul 24 17:28 etc
drwxr-xr-x 23 vagrant vagrant  4096 Jul 24 17:28 lib
drwxr-xr-x  2 vagrant vagrant  4096 Jul 24 17:28 log
drwxr-xr-x  2 vagrant vagrant  4096 Jul 24 17:28 plugins
drwxr-xr-x  3 vagrant vagrant  4096 Jul 24 17:28 releases
drwxr-xr-x  3 vagrant vagrant  4096 Jul 24 17:28 var`

thanks.

**Comment by prakashr87** [comment]
Hai 
      Me too having the same issue...
Thanks.

**Comment by erylee** [comment]
Fixed. Please download: http://emqtt.io/downloads/ubuntu

**Comment by prakashr87** [comment]
Thanks...
