### ISSUE TITLE
Hw requirements - 5K users, 25-50 msgs/sec, QoS=1

### ISSUE THREAD

**Issue by santif** [emqtt/emqttd#209]
We're evaluating to migrate from a plain websocket based service to MQTT over websockets and QoS=1, using emqttd.
What are the minimum server requirements for 5K users? Clients don't send messages. The server sends 25-50 msgs/sec to all clients using QoS=1.. Each message has 100-150 bytes. Any help will be appreciated, thanks!

**Comment by erylee** [comment]
@santif, Are your sure about your requirements? It means the broker should publish messages at the rate of 125K~250K msg/sec!  

I write a new benchmark tool. Your could benchmark the case with the latest broker by yourself:

Subscribe with 5000 clients:

```
./emqtt_bench_sub -h 10.61.63.50 -i 10 -c 5000 -t bench -q 1
```

Publish messages at the rate of 10 msg/sec:

```
./emqtt_bench_pub -h 10.61.63.50 -c 1 -I 100 -t bench -q 1 -s 150
```
