### ISSUE TITLE
Cluster function is not working

### ISSUE THREAD

**Issue by macleetw** [emqtt/emqttd#211]
Hi,

I download prebuilt image and run with default setting first.
It's ok, broker can accept publish/subscribe command.

But I change the node name from  "emqttd@127.0.0.1" to "emqttd@192.168.2.167".
Then the sever can not start correctly.
The log with command "./emqttd console"

=INFO REPORT==== 27-Jul-2015::11:49:50 ===
    alarm_handler: {set,{{disk_almost_full,"/"},[]}}

=INFO REPORT==== 27-Jul-2015::11:49:50 ===
    alarm_handler: {set,{system_memory_high_watermark,[]}}
starting emqttd on node 'emqttd@192.168.2.167'
emqttd trace is starting...[done]
emqttd pooler is starting...[done]
emqttd client manager is starting...[done]
emqttd session manager is starting...[done]
emqttd session supervisor is starting...[done]
emqttd pubsub is starting...[done]
emqttd stats is starting...Eshell V6.4  (abort with ^G)
(emqttd@192.168.2.167)1>
=INFO REPORT==== 27-Jul-2015::11:49:50 ===
    application: emqttd
    exited: {bad_return,
                {{emqttd_app,start,[normal,[]]},
                 {'EXIT',
                     {{badmatch,
                          {error,
                              {{{badmatch,{error,{no_exists,topic}}},
                                [{emqttd_stats,'-init/1-lc$^1/1-1-',1,
                                     [{file,"src/emqttd_stats.erl"},
                                      {line,144}]},
                                 {emqttd_stats,init,1,
                                     [{file,"src/emqttd_stats.erl"},
                                      {line,144}]},
                                 {gen_server,init_it,6,
                                     [{file,"gen_server.erl"},{line,306}]},
                                 {proc_lib,init_p_do_apply,3,
                                     [{file,"proc_lib.erl"},{line,237}]}]},
                               {child,undefined,emqttd_stats,
                                   {emqttd_stats,start_link,[]},
                                   permanent,10000,worker,
                                   [emqttd_stats]}}}},
                      [{emqttd_app,start_child,2,
                           [{file,"src/emqttd_app.erl"},{line,105}]},
                       {emqttd_app,start_server,2,
                           [{file,"src/emqttd_app.erl"},{line,94}]},
                       {emqttd_app,'-start_servers/1-lc$^0/1-0-',2,
                           [{file,"src/emqttd_app.erl"},{line,85}]},
                       {emqttd_app,'-start_servers/1-lc$^0/1-0-',2,
                           [{file,"src/emqttd_app.erl"},{line,85}]},
                       {emqttd_app,start,2,
                           [{file,"src/emqttd_app.erl"},{line,53}]},
                       {application_master,start_it_old,4,
                           [{file,"application_master.erl"},{line,272}]}]}}}}
    type: permanent

=INFO REPORT==== 27-Jul-2015::11:49:50 ===
    alarm_handler: {clear,system_memory_high_watermark}

=INFO REPORT==== 27-Jul-2015::11:49:50 ===
    alarm_handler: {clear,{disk_almost_full,"/"}}
{"Kernel pid terminated",application_controller,"{application_start_failure,emqttd,{bad_return,{{emqttd_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{{{badmatch,{error,{no_exists,topic}}},[{emqttd_stats,'-init/1-lc$^1/1-1-',1,[{file,\"src/emqttd_stats.erl\"},{line,144}]},{emqttd_stats,init,1,[{file,\"src/emqttd_stats.erl\"},{line,144}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,237}]}]},{child,undefined,emqttd_stats,{emqttd_stats,start_link,[]},permanent,10000,worker,[emqttd_stats]}}}},[{emqttd_app,start_child,2,[{file,\"src/emqttd_app.erl\"},{line,105}]},{emqttd_app,start_server,2,[{file,\"src/emqttd_app.erl\"},{line,94}]},{emqttd_app,'-start_servers/1-lc$^0/1-0-',2,[{file,\"src/emqttd_app.erl\"},{line,85}]},{emqttd_app,'-start_servers/1-lc$^0/1-0-',2,[{file,\"src/emqttd_app.erl\"},{line,85}]},{emqttd_app,start,2,[{file,\"src/emqttd_app.erl\"},{line,53}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,272}]}]}}}}}"}

Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,emqttd,{bad_return,{{emqttd_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{{{badmatch,{error,{no_exists,topic}}},[{emqtt
chlee:bin maclee$

**Comment by erylee** [comment]
Please remove 'data/mnesia' if you change node node.

**Comment by macleetw** [comment]
Thanks a lot, it's working.
