### ISSUE TITLE
为什么，发送消息慢？

### ISSUE THREAD

**Issue by bayuemu** [emqtt/emqttd#214]
当我使用 emqttd_benchmark-master 分别对 mosquitto 和 emqtt 进行测试，同样的 是用户数情况下，emqtt明显比mosquitto 慢的很多，怎样调整可以使 emqtt 能发送快一些？？？

**Comment by erylee** [comment]
请详细描述具体问题，比如用户数、发送的消息Qos、首发消息速率、发送慢还是接收慢？emqttd_error.log是否有日志？是否打印了大量info日志？

**Comment by bayuemu** [comment]
我先描述一下我的使用场景：
1，emqttd-0.9.0-alpha为基础，修改了登录认证方式为http方式
2，修改了acl读取方式，从mongodb集群读取acl
3，使用emqttd_benchmark 进行测试（很吃内存），100个人登录（每隔300毫秒登录一个），都向“/1”订阅点发数据（每隔100毫秒发送一条），Qos使用emqttd_benchmark默认
4，系统使用ubuntu14.02server（64bit），内存1g，单核，系统参数也做了相应的修改，
当100个链接点都登录完成以后，运行及分钟后，然后从emqttd_benchmark  中q()出去;这时emqttd的console里还有大量的收发信息不断打印，显示信息发送和接受，这个过程很漫长，emqttd_error.log 没有报错，开启了info日志打印.显示信息发送和接受 这个是不是就是慢的表现？或者说log是异步显示的和发送接受信息没有关系？
     还有就是假设用x 订阅了/x，仅仅上线一次，就不在上线，此时系统不断的向/x 发生订阅信息，会不会造成系统消息积压？
    当用户登录后acl会放在内存中，当系统运行很长时间后，大量的acl会不会在内存中造成积压？
谢谢

**Comment by erylee** [comment]
正式部署要关闭info日志，否则就积压大量日志消息:) 请修改:

```
 {lager, [
    {colored, true},
    {async_threshold, 1000},
    {error_logger_redirect, false},
    {crash_log, "log/emqttd_crash.log"},
    {handlers, [
        {lager_file_backend, [
            {formatter_config, [time, " ", pid, " [",severity,"] ", message, "\n"]},
            {file, "log/emqttd_error.log"},
            {level, error},
            {size, 104857600},
            {date, "$D0"},
            {count, 30}
        ]}
    ]}
 ]},
```

**Comment by bayuemu** [comment]
其实不慢，只是内存在我使用 emqttd_benchmark-master 开了10000个链接，只保持 emqttd_benchmark-master接受数据，在不发数据时，但是emqtt 的内存会慢慢一点一点的往上增加，这个怎么解决？？？？？

**Comment by erylee** [comment]
@bayuemu, 我们需要详细讨论下场景，0.9.x版本为每个session增加了inflight window和queue，参数配置在etc/emqttd.config，默认对Qos1/2消息，inflight 100条，queue 1000条。如果客户端无法及时ack，inflight/queue就会累积，你加我QQ: 22061135，详细讨论你的应用场景。

```
       %% Session
        {session, [
            %% Expired after 2 days
            {expired_after, 48},

            %% Max number of QoS 1 and 2 messages that can be “in flight” at one time.
            %% 0 means no limit
            {max_inflight, 100},

            %% Max retries for unack Qos1/2 messages
            {unack_retries, 3},

            %% Retry after 4, 8, 16 seconds
            {unack_timeout, 4},

            %% Awaiting PUBREL Timeout
            {await_rel_timeout, 8},

            %% Max Packets that Awaiting PUBREL, 0 means no limit
            {max_awaiting_rel, 0}

        ]},
        %% Session
        {queue, [
            %% Max queue length. enqueued messages when persistent client disconnected,
            %% or inflight window is full.
            {max_length, 1000},

            %% Low-water mark of queued messsages
            {low_watermark, 0.2},

            %% High-water mark of queued messsages
            {high_watermark, 0.6},

            %% Queue Qos0 messages?
            {queue_qos0, true}
        ]}
```

**Comment by erylee** [comment]
@bayuemu, this issue is invalid. Please read Erlang Garbage collection and Memory management. And discuss benchmark of 0.9.x in issue #225.
