### ISSUE TITLE
为什么emqttd_dashboard插件显示加载成功，但是浏览器中无法访问？

### ISSUE THREAD

**Issue by hzaupj** [emqtt/emqttd#215]
我的步骤
1、下载emqttd_dashboard到plugins目录
2、新建ebin目录，使用erlc编译src目录下的所有源码，输出到ebin目录
3、将emqttd_dashboard.app.src拷贝到ebin目录并去除.src后缀
4、plugins.config配置中添加emqttd_dashboard的配置
5、load 插件
6、emqttd_ctl plugins list 显示{emqttd_dashboard,"emqttd web dashboard","0.1"}
这样应该就是插件安装成功了吧
但是浏览器访问18083端口，显示ERR_EMPTY_RESPONSE？
哪里还有问题么？

**Comment by erylee** [comment]
Wait for 0.10.0 release. I will integrate dashboard plugin.

**Comment by erylee** [comment]
Hi, we will integrate with the dashboard plugin in 0.10.0, and release it next week.

**Comment by erylee** [comment]
@hzaupj, 0.10.0 released with the new emqttd_dashboard plugin. please pull latest master branch.

**Comment by hzaupj** [comment]
现在还没有0.10.0的binary packages可供下载吧？

**Comment by erylee** [comment]
All the code has been merged to master branch, but the Dashboard still has a issue to fix.

> 在 2015年8月17日，下午2:03，hzaupj <notifications@github.com> 写道：
> 
> 现在还没有0.10.0的binary packages可供下载吧？
> 
>
