### ISSUE TITLE
load plugin emysql error: {"no such file or directory","emysql.app"}

### ISSUE THREAD

**Issue by prakashr87** [emqtt/emqttd#218]
Hai,
     Iam getting error while starting emqtt. iam trying to use mysql plugin for username and password client authentication but i stuck.

Please assist me Thanks.  

16:36:46.406 [info] load module presence successfully
16:36:46.406 [info] load module autosub successfully
16:36:46.440 [error] load plugin emysql error: {"no such file or directory","emysql.app"}
16:36:46.442 [error] load plugin emqttd_auth_mysql error: {"no such file or directory","emqttd_auth_mysql.app"}
16:36:46.532 [info] mqtt listen on 0.0.0.0:1883 with 16 acceptors.
16:36:46.536 [info] mqtts listen on 0.0.0.0:8883 with 4 acceptors.
16:36:46.546 [info] http listen on 0.0.0.0:8083 with 4 acceptors.
Erlang MQTT Broker 0.9.3 is running now

**Comment by erylee** [comment]
Will release a new mysql_plugin in 0.10.0

**Comment by prakashr87** [comment]
Thanks for the reply....when we can expect this release?

**Comment by erylee** [comment]
about next week.

**Comment by prakashr87** [comment]
Hai 
      Did you release new mysql_plugin in 0.10.0

**Comment by erylee** [comment]
@prakashr87, The new plugin design has been merged to master branch. Could you pull the latest master branch to build?  I will release 0.10.0 binary packet when emqttd_dashboard ready.

Wiki: https://github.com/emqtt/emqttd/wiki/Plugin%20Design
