### ISSUE TITLE
emqttd  0.93 cluster start will crash

### ISSUE THREAD

**Issue by lsxredrain** [emqtt/emqttd#219]
change 127.0.0.1 to  192.168.154.111 and  ./rel/emqttd/bin/emqttd console
then crash， log as follow

starting emqttd on node 'emqttd@192.168.154.111'
emqttd trace is starting...[done]
emqttd pooler is starting...[done]
emqttd client manager is starting...[done]
emqttd session manager is starting...[done]
emqttd session supervisor is starting...[done]
emqttd pubsub is starting...[done]
emqttd stats is starting...
=INFO REPORT==== 29-Jul-2015::11:43:43 ===
    application: emqttd
    exited: {bad_return,
                {{emqttd_app,start,[normal,[]]},
                 {'EXIT',
                     {{badmatch,
                          {error,
                              {{{badmatch,{error,{no_exists,topic}}},
                                [{emqttd_stats,'-init/1-lc$^1/1-1-',1,
                                     [{file,"src/emqttd_stats.erl"},
                                      {line,144}]},
                                 {emqttd_stats,init,1,
                                     [{file,"src/emqttd_stats.erl"},
                                      {line,144}]},
                                 {gen_server,init_it,6,
                                     [{file,"gen_server.erl"},{line,306}]},
                                 {proc_lib,init_p_do_apply,3,
                                     [{file,"proc_lib.erl"},{line,237}]}]},
                               {child,undefined,emqttd_stats,
                                   {emqttd_stats,start_link,[]},
                                   permanent,10000,worker,
                                   [emqttd_stats]}}}},
                      [{emqttd_app,start_child,2,
                           [{file,"src/emqttd_app.erl"},{line,105}]},
                       {emqttd_app,start_server,2,
                           [{file,"src/emqttd_app.erl"},{line,94}]},
                       {emqttd_app,'-start_servers/1-lc$^0/1-0-',2,
                           [{file,"src/emqttd_app.erl"},{line,85}]},
                       {emqttd_app,'-start_servers/1-lc$^0/1-0-',2,
                           [{file,"src/emqttd_app.erl"},{line,85}]},
                       {emqttd_app,start,2,
                           [{file,"src/emqttd_app.erl"},{line,53}]},
                       {application_master,start_it_old,4,
                           [{file,"application_master.erl"},{line,272}]}]}}}}
    type: permanent
Eshell V6.4  (abort with ^G)
(emqttd@192.168.154.111)1> [os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,emqttd,{bad_return,{{emqttd_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{{{badmatch,{error,{no_exists,topic}}},[{emqttd_stats,'-init/1-lc$^1/1-1-',1,[{file,\"src/emqttd_stats.erl\"},{line,144}]},{emqttd_stats,init,1,[{file,\"src/emqttd_stats.erl\"},{line,144}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,237}]}]},{child,undefined,emqttd_stats,{emqttd_stats,start_link,[]},permanent,10000,worker,[emqttd_stats]}}}},[{emqttd_app,start_child,2,[{file,\"src/emqttd_app.erl\"},{line,105}]},{emqttd_app,start_server,2,[{file,\"src/emqttd_app.erl\"},{line,94}]},{emqttd_app,'-start_servers/1-lc$^0/1-0-',2,[{file,\"src/emqttd_app.erl\"},{line,85}]},{emqttd_app,'-start_servers/1-lc$^0/1-0-',2,[{file,\"src/emqttd_app.erl\"},{line,85}]},{emqttd_app,start,2,[{file,\"src/emqttd_app.erl\"},{line,53}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,272}]}]}}}}}"}

Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,emqttd,{bad_return,{{emqttd_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{{{badmatch,{error,{no_exists,topic}}},[{emqtt

**Comment by erylee** [comment]
If you start the broker with node name emqttd@127.0.0.1, and then stop it and change node name to cluster, you should rm 'data/mnesia/*' .

**Comment by lsxredrain** [comment]
thanks a lot, it ok

**Comment by erylee** [comment]
Okay, I will update wiki about cluster
