### ISSUE TITLE
内存据高不下，怎么办？

### ISSUE THREAD

**Issue by bayuemu** [emqtt/emqttd#220]
使用emqttd_benchmark-master 链接 emqtt  100个链接，然后q() emqttd_benchmark-master.
重复3次，emqtt的内存只升不降低，这个是3次的emqtt的数据--------------------------
 1，[{total,3511198296},
 {processes,3476011872},
 {processes_used,3476011648},
 {system,35186424},
 {atom,471633},
 {atom_used,468284},
 {binary,846728},
 {code,12902433},
 {ets,2228888}]
-----------------------------
2，[{total,3509657208},
 {processes,3474773856},
 {processes_used,3474773632},
 {system,34883352},
 {atom,471633},
 {atom_used,468284},
 {binary,776608},
 {code,12902433},
 {ets,2163872}]
-----------------------------------
3，[{total,4066543208},
 {processes,4031483712},
 {processes_used,4031483488},
 {system,35059496},
 {atom,471633},
 {atom_used,468284},
 {binary,892912},
 {code,12902433},
 {ets,2223712}]
断开所有链接后，内存没有丝毫降低的意思，怎么吧？

**Comment by erylee** [comment]
@bayuemu, please add my QQ: 22061135, let's discuss this issue.

**Comment by erylee** [comment]
This metrics are invalid, one hundred connections will not consume so much memory anyway!

Please check issue #225.

**Comment by w3hacker** [comment]
提问请用英文
