### ISSUE TITLE
three node cluster , restart crash and configure lost

### ISSUE THREAD

**Issue by sailingchen** [emqtt/emqttd#221]
three node clusterd :
   -name emqttd@192.168.18.9
   -name emqttd@192.168.18.10
   -name emqttd@192.168.18.11

on 18.10 run  ./bin/emqttd_ctl cluster emqttd@192.168.18.9
on 18.11 run ./bin/emqttd_ctl cluster emqttd@192.168.18.9

then, restart 18.9, 18.10 , 18.11 , run './bin/emqttd_ctl cluster' found cluster configure is lost  。

try to run ./bin/emqttd_ctl cluster emqttd@192.168.18.9 on 18.11  will carsh:
RPC to 'emqttd@192.168.18.11' failed: {'EXIT',
                                       {{case_clause,
                                         {error,
                                          {merge_schema_failed,
                                           "Incompatible schema cookies. Please, restart from old backup.'emqttd@192.168.18.10' = [{name,schema},{type,set},{ram_copies,['emqttd@192.168.18.10']},{disc_copies,['emqttd@192.168.18.11']},{disc_only_copies,[]},{load_order,0},{access_mode,read_write},{majority,false},{index,[]},{snmp,[]},{local_content,false},{record_name,schema},{attributes,[table,cstruct]},{user_properties,[]},{frag_properties,[]},{storage_properties,[]},{cookie,{{1436,444971,772460},'emqttd@192.168.18.11'}},{version,{{4,0},{'emqttd@192.168.18.11',{1436,446112,654991}}}}], 'emqttd@192.168.18.11' = [{name,schema},{type,set},{ram_copies,['emqttd@192.168.18.11','emqttd@192.168.18.10']},{disc_copies,['emqttd@192.168.18.9']},{disc_only_copies,[]},{load_order,0},{access_mode,read_write},{majority,false},{index,[]},{snmp,[]},{local_content,false},{record_name,schema},{attributes,[table,cstruct]},{user_properties,[]},{frag_properties,[]},{storage_properties,[]},{cookie,{{1436,430392,499098},'emqttd@192.168.18.9'}},{version,{{5,0},{'emqttd@192.168.18.11',{1436,446165,408554}}}}]\n"}}},
                                        [{emqttd_mnesia,cluster,1,
                                          [{file,"src/emqttd_mnesia.erl"},
                                           {line,144}]},
                                         {emqttd_ctl,cluster,1,
                                          [{file,"src/emqttd_ctl.erl"},
                                           {line,85}]},
                                         {rpc,'-handle_call_call/6-fun-0-',5,
                                          [{file,"rpc.erl"},{line,205}]}]}}

```

```

anthother question restart node , the auth user and password is lost

**Comment by virtustilus** [comment]
The same problem. After any server restart it looses the user.
