### ISSUE TITLE
Use `application:ensure_all_started` to start plugins

### ISSUE THREAD

**Issue by phanimahesh** [emqtt/emqttd#223]
`emqttd` fails to start plugins if they have dependent applications which are not started already. To be more precise, if `applications` lists anything additional to the defaults, such as

```
{applications, [
                  kernel,
                  stdlib,
                  myapp
                 ]},
```
`emqttd` will not start properly, and will complain 

```
[error] start plugin emqttd_plugin_custom error: {not_started, myapp}
```

This can be fixed by using `application:ensure_all_started` [here][src]
[src]:https://github.com/emqtt/emqttd/blob/master/src/emqttd.erl#L156

**Comment by bmcustodio** [comment]
@erylee I can confirm this. However, even after applying the fix suggested by @phanimahesh I can't load my plugin, as it has a dependency on `base64url` and `jiffy`. I get the message

```
[error] start plugin emqttd_auth_jwt error: {base64url,{"no such file or directory","base64url.app"}}
```
It seems that this file isn't copied when `make dist`ing. What can I do to fix this?

**Comment by bmcustodio** [comment]
@erylee In my case, I have an auth plugin (`emqttd_auth_ext`) which has the following dependency tree:

```
emqttd_auth_ext ---(depends on)--> ext ---(depends on)--> base64url + jiffy
```

I can load `emqttd_auth_ext` correctly, but as soon as the first call to `ext` takes place, `emqttd` complains. None of `ext`, `base64url` and `jiffy` are loaded on the console. What is the best way to get around this?

**Comment by erylee** [comment]
@phanimahesh, I will improve the plugin loading mechanism and release it this weekend.

**Comment by erylee** [comment]
@phanimahesh, I merged new plugin design to master branch, please pull the the latest master branch and check if it works for your plugin. Wiki: https://github.com/emqtt/emqttd/wiki/Plugin%20Design

**Comment by erylee** [comment]
@bmcustodio, Please pull latest master branch and check the new plugin design. 

@phanimahesh,  Could we close this issue now? Thanks.

**Comment by phanimahesh** [comment]
Yes, this looks good. Thanks for the quick response.
