### ISSUE TITLE
0.93启动有问题

### ISSUE THREAD

**Issue by w3yyb** [emqtt/emqttd#227]
# ./emqttd start
emqttd failed to start within 15 seconds,
see the output of 'emqttd console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.

提示这个，实际已经起来了。

**Comment by w3yyb** [comment]
并且，不能stop, stop后提示 Node is not running! ，其实进程都还在

**Comment by w3yyb** [comment]
但是用 console又提示成功。
./emqttd console
Exec: /opt/emqttd093/emqttd/erts-6.4/bin/erlexec -boot /opt/emqttd093/emqttd/releases/0.9.3-alpha-2-gb14e8eb/emqttd             -embedded -config /opt/emqttd093/emqttd/etc/emqttd.config -config /opt/emqttd093/emqttd/etc/plugins.config             -pa ./lib/basho-patches             -args_file /opt/emqttd093/emqttd/etc/vm.args -- console
Root: /opt/emqttd093/emqttd
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:32] [hipe] [kernel-poll:true]

starting emqttd on node 'cypush@162.168.6.156'
emqttd trace is starting...[done]
emqttd pooler is starting...[done]
emqttd client manager is starting...[done]
emqttd session manager is starting...[done]
emqttd session supervisor is starting...[done]
emqttd pubsub is starting...[done]
emqttd stats is starting...[done]
emqttd metrics is starting...[done]
emqttd broker is starting...[done]
emqttd alarm is starting...[done]
emqttd mode supervisor is starting...[done]
emqttd bridge supervisor is starting...[done]
emqttd access control is starting...[done]
emqttd system monitor is starting...[done]
13:01:18.939 [info] load module presence successfully
13:01:18.939 [info] load module autosub successfully
13:01:18.978 [info] mqtt listen on 0.0.0.0:1883 with 16 acceptors.
13:01:18.979 [info] mqtts listen on 0.0.0.0:8883 with 4 acceptors.
13:01:18.986 [info] http listen on 0.0.0.0:8083 with 4 acceptors.
Erlang MQTT Broker 0.9.3 is running now
Eshell V6.4  (abort with ^G)

**Comment by erylee** [comment]
do you change the node name in etc/vm.args?

**Comment by w3yyb** [comment]
是的，改为了 cypush@162.168.6.156

**Comment by erylee** [comment]
The node name is not right. Should not use the public IP. Close the issue.

**Comment by w3yyb** [comment]
以前的版本没这个问题啊 可以用 192.168.6.X

**Comment by erylee** [comment]
设置公网IP，你两个Erlang Node间无法访问，和broker版本没关系。

测试:

```
erl -name a@162.168.6.156
erl -name b@162.168.6.156

## ping b on  a@162.168.6.156
net_adm:ping('b@162.168.6.156').

## or ping a on b@162.168.6.156
net_adm:ping('a@162.168.6.156').
```

**Comment by w3yyb** [comment]
很奇怪，这里说的明明是可以的 https://github.com/emqtt/emqttd/wiki/Cluster

Configure and start 'node1'

configure 'etc/vm.args':

-name emqttd@192.168.0.10
or

**Comment by erylee** [comment]
服务器私网IP

**Comment by w3yyb** [comment]
我这个 162.168.6.156 也是私网哦

**Comment by erylee** [comment]
erl -name a@162.168.6.156
erl -name b@162.168.6.156

## ping b on  a@162.168.6.156
net_adm:ping('b@162.168.6.156').

## or ping a on b@162.168.6.156
net_adm:ping('a@162.168.6.156').

**Comment by w3yyb** [comment]
192.168.0.10 和 192.168.6.156有什么 不同？

**Comment by w3yyb** [comment]
以前用 111.206.*.* 这样的也是没问题的，我再看看。

**Comment by w3yyb** [comment]
如果这个不能弄，请问，如何设计集群

**Comment by erylee** [comment]
Add my QQ: 22061135, or Join QQ Group: 12222225 to discuss this issue

**Comment by w3yyb** [comment]
erl -name a@162.168.6.156
erl -name a@162.168.6.159

## ping b on  a@162.168.6.156
net_adm:ping('a@162.168.6.159').
pong
## or ping a on b@162.168.6.159
net_adm:ping('a@162.168.6.156').
pong 


可以ping通
