### ISSUE TITLE
how to register users

### ISSUE THREAD

**Issue by yon86** [emqtt/emqttd#229]
I would like to register users  preferably using http api is there support for this...and do u provide disk persistence for username and password

thanks

**Comment by erylee** [comment]
1. etc/emqttd.config

```
 {auth, [
            %% Authentication with username, password
            {username, []},
```

2. Cli

#add user, and store in mnesia database
./bin/emqttd_ctl  useradd <Username> <Password>

**Comment by erylee** [comment]
@yon86, this issue has been moved to emqttd_dashboard project.
