### ISSUE TITLE
Get all connected clients to the broker

### ISSUE THREAD

**Issue by shrihubble** [emqtt/emqttd#230]
I am working on IoT implementation in my current project. I have setup my MQTT broker using emqttd. Is there a way in which I can find what are the clients connected to each other with the same topic.

**Comment by erylee** [comment]
emqttd 0.10.0 released with a emqttd_dashboard plugin contributed by @huangdan. And you could find all connected clients by three ways:

1. JSON/HTTP API: http://127.0.0.1:18083/api/clients

2. Dashboard: http://127.0.0.1:18083/#/clients

3. Admin Command: ./bin/emqttd_ctl sessions list

**Comment by TangMonk** [comment]
How to query clients by id? `http://127.0.0.1:18083/api/clients?client_key=12312` seems not work
