### ISSUE TITLE
SUBSCRIBE without client intervention

### ISSUE THREAD

**Issue by ghost** [emqtt/emqttd#252]
Is there a way to subscribe clients to a given topic without their intervention (e.g., from an external application via, say, HTTP)? Users in our application register via a REST API and it would be great if I could automatically subscribe them to certain topics on the broker upon registration (even if they have never actually connected to the broker) so that, upon the first connection, they will already receive what has been sent while they were offline.

Can this be achieved somehow?

**Comment by erylee** [comment]
@bmcustodio please check emqttd_mod_autosub module, you could hook 'client.connected' and subscribe some topics when client connected.

```
load(Opts) ->
    Topics = [{list_to_binary(Topic), Qos} || {Topic, Qos} <- Opts, 0 =< Qos, Qos =< 2],
    emqttd_broker:hook('client.connected', {?MODULE, client_connected},
                       {?MODULE, client_connected, [Topics]}),
    {ok, #state{topics = Topics}}.

client_connected(?CONNACK_ACCEPT, #mqtt_client{client_id = ClientId, client_pid = ClientPid}, Topics) ->
    F = fun(Topic) -> emqttd_topic:feed_var(<<"$c">>, ClientId, Topic) end,
    ClientPid ! {subscribe, [{F(Topic), Qos} || {Topic, Qos} <- Topics]};
```

**Comment by bmcustodio** [comment]
@erylee Thanks! I had already come across that module, but I believe it does a different thing. What I would need is to create a (non-clean) session for a given client ID (if none exists yet) and subscribe that client to a bunch of topics "remotely" from my Java application. Is there any way this could be included in a future release?

**Comment by bmcustodio** [comment]
@erylee It would be really great if this could be done via, for example, the HTTP API (create a persistent session for a given client ID and subscribe it to a given topic even if it has never connected before). Would allow for a couple of nice things in my scenario :-)

Even if you don't want to include this feature in the codebase, would you help me implementing it via a plugin or something?

**Comment by erylee** [comment]
@bmcustodio, I will support this feature.

**Comment by bmcustodio** [comment]
@erylee That's really great :-)

**Comment by bmcustodio** [comment]
@erylee Not trying to make any kind of pressure, of course, but do you have an estimated date for a release with this? :-)

**Comment by bmcustodio** [comment]
@erylee That's great :-) Do you have any idea on when you can start working on it? (Y)

**Comment by erylee** [comment]
@bmcustodio, I plan to design and coding this feature this weekend. Let's discuss the design in detail later:)

**Comment by bmcustodio** [comment]
@erylee That would be great :-) If you want to hang on Freenode or something to discuss this just let me know ;-)

**Comment by bmcustodio** [comment]
@erylee Have you been making any progress on this? Do you need any input?

**Comment by erylee** [comment]
@bmcustodio, I am working on design of this issue:)

**Comment by bmcustodio** [comment]
@erylee My idea for this would be to create the persistent subscription by CLI or HTTP, as you say. Then, clients would retrieve offline messages the first time they connect. That would be the whole point :-)
