### ISSUE TITLE
Log message flood crash the broker

### ISSUE THREAD

**Issue by eurus9989** [emqtt/emqttd#253]
This is my config of etc/emqttd.config for lager. I follow the link https://github.com/emqtt/emqttd/wiki/One%20Million%20Connections . But when the server reach to 3000 concurent connections, server crashed. What's wrong here ? The log show the reason of acceptors and emfiles error

```
[{kernel,
        [{start_timer, true},
         {start_pg2, true}
 ]},
 {sasl, [
        {sasl_error_logger, {file, "log/emqttd_sasl.log"}}
 ]},
 {ssl, [
    %{versions, ['tlsv1.2', 'tlsv1.1']}
 ]},
 {lager, [
    {colored, true},
    {async_threshold, 1000},
    {error_logger_redirect, false},
    {crash_log, "log/emqttd_crash.log"},
    {handlers, [
        {lager_file_backend, [
            {formatter_config, [time, " ", pid, " [",severity,"] ", message, "\n"]},
            {file, "log/emqttd_error.log"},
            {level, error},
            {size, 104857600},
            {date, "$D0"},
            {count, 30}
        ]}
    ]}
  ]},
{esockd, [
    {logger, {lager, info}}
 ]},
```

**Comment by erylee** [comment]
please check etc/vm.arg config:

```
## max process numbers
+P 1000000

## Increase number of concurrent ports/sockets
-env ERL_MAX_PORTS 1000000

-env ERTS_MAX_PORTS 1000000
```

**Comment by eurus9989** [comment]
This is my vm.args config.  The error I have exactly is: 
07:33:10.061 <0.521.0> [error] acceptor on 0.0.0.0:9989 suspend 100(ms) for 2300 emfile errors!! 
It makes server crash, eventhough I have set my ulimit -n to 1.000.000 like the guide in the link https://github.com/emqtt/emqttd/wiki/One%20Million%20Connections . 

##-------------------------------------------------------------------------
## Name of the node
##-------------------------------------------------------------------------
-name emqttd@10.240.46.240

## Cookie for distributed erlang
-setcookie emqttdsecretcookie

##-------------------------------------------------------------------------
## Mnesia dir. NOTICE: quote the dir with '" "'
##-------------------------------------------------------------------------
-mnesia dir '"data/mnesia"'

##-------------------------------------------------------------------------
## Flags
##-------------------------------------------------------------------------

## Heartbeat management; auto-restarts VM if it dies or becomes unresponsive
## (Disabled by default..use with caution!)
##-heart
-smp true

## Enable kernel poll and a few async threads
+K true
+A 64

## max process numbers
+P 1000000

## Increase number of concurrent ports/sockets
-env ERL_MAX_PORTS 1000000

-env ERTS_MAX_PORTS 1000000

#-env ERL_MAX_ETS_TABLES 1024

## Tweak GC to run more often
-env ERL_FULLSWEEP_AFTER 1000
#

**Comment by erylee** [comment]
do you check "ulimit -n" ?

**Comment by erylee** [comment]
"emfile error" means that the broker cannot open new file descriptor.
