### ISSUE TITLE
Qos1 message may be dropped under unstable mobile network

### ISSUE THREAD

**Issue by sailingchen** [emqtt/emqttd#264]
Under unstable mobile network(2G, GRPS...) , default   retries 3 for unack Qos1/2 messages , if faild ,  message may be dropped。

**Comment by chiarishow** [comment]
and please add "0" for not dropping any qos1/2 messages.

**Comment by erylee** [comment]
@sailingchen, @chiarishow, This issue has been fixed. Please check PR: https://github.com/emqtt/emqttd/pull/323, and pull the latest master branch.
