### ISSUE TITLE
client under unstable mobile network generate a lot of log

### ISSUE THREAD

**Issue by sailingchen** [emqtt/emqttd#265]
when client under unstable mobile network, or manual  disable/enable mobile  network , 
generate  many log like this:

erlang.log.1
[error] clientId 'f30989kobc0824684b20ddf1caaca19a1' is duplicated  pid=<0.21261.97>, oldpid=<0.19101.97>

emqttd_info.log:
[error] Shutdown for duplicate clientid: e7b63c2f1Sffb0c79198a09edb, conn:11.4.61.124:51175 -> 17.9.20.33:80

**Comment by erylee** [comment]
Duplicated with #273
