### ISSUE TITLE
port can't connect

### ISSUE THREAD

**Issue by zuogan** [emqtt/emqttd#270]
I install the emqtt newest zip in centos, erlang env is ok, and when i start emqtt, it shows success. Strangely, i can't connect any port(8083,18083etc) with telnet, and cant' access the dashboard(port 18083)from chrome, i insert the port rule in iptable as this 'iptables -I INPUT -p tcp --dport 8083-j ACCEPT' and save the iptable after update. To my suprise, any of these port still can't connect. so i don't know why, everything seems ok. could you give me some advice pls ? Thx.

**Comment by erylee** [comment]
./bin/emqttd console to check if the tcp listener is started.

**Comment by zuogan** [comment]
i run empttd with console mode, here is the log, port is listening, so i don't know why port still can't be connected.

starting emqttd on node 'emqttd@127.0.0.1'
emqttd trace is starting...[done]
emqttd pooler is starting...[done]
emqttd client manager is starting...[done]
emqttd session manager is starting...[done]
emqttd session supervisor is starting...[done]
emqttd pubsub is starting...[done]
emqttd stats is starting...[done]
emqttd metrics is starting...[done]
emqttd broker is starting...[done]
emqttd alarm is starting...[done]
emqttd mode supervisor is starting...[done]
emqttd bridge supervisor is starting...[done]
emqttd access control is starting...[done]
emqttd system monitor is starting...[done]
07:15:05.640 [info] load module presence successfully
07:15:05.743 [info] http listen on 0.0.0.0:18083 with 4 acceptors.
07:15:05.745 [info] started Apps: [emqttd_dashboard]
07:15:05.745 [info] load plugin emqttd_dashboard successfully
07:15:05.750 [info] mqtt listen on 0.0.0.0:1883 with 16 acceptors.
07:15:05.755 [info] mqtts listen on 0.0.0.0:8883 with 4 acceptors.
07:15:05.760 [info] http listen on 0.0.0.0:8083 with 4 acceptors.
----------------------------------------------
And this is port tcp listener state:
[root@host2 emqttd-0.10.2]# netstat -anp | grep 18083
tcp        0      0 0.0.0.0:18083               0.0.0.0:*                   LISTEN      2406/beam.smp

**Comment by erylee** [comment]
@zuogan, the broker is started successfully. please check your firewall.
