### ISSUE TITLE
Add Sockjs support

### ISSUE THREAD

**Issue by rock59** [emqtt/emqttd#277]
Please add Sockjs support for browsers that dont support websocket
Does sockjs affects performance when emqttd runs in cluster mode?

**Comment by erylee** [comment]
@rock59, the broker side could add sockjs support, but what protocol used on the browser side?

**Comment by rock59** [comment]
First, Sorry for my bad english ;-(
I am using Stomp, RabbitMQ and its Stomp over Sockjs plugin in my company..I need to migrate to MQTT protocol to support IoT too (my company Raspberry Pi based gadgets) .. I consider to use emqttd but emqttd only support Websockets and we need to support our customers who use older browsers..
I am not a network programmer guru.. I googled and I found that Eclipse Paho implemented a javascript library that tunnel MQTT over websocket.. Is it possible to implement such library to tunnel MQTT over Sockjs?

**Comment by erylee** [comment]
@rock59,  I read some documents about SockJS. It seems SockJS use JSONP on older browsers that cannot support WebSocket. For MQTT(same to AMQP) is a binary protocol,  it will not work with JSONP, I think.

We have to write a Stomp over SockJS plugin to support your requirements.

**Comment by rock59** [comment]
This is correct.. SockJS uses Websocket in modern browsers and fallbacks to JSONP , Long Polling or other Text based Protocols(HTTP) in older browsers..

SockJS has two problems
1- It uses Text based protocols in fallback mode
2- Some develpers have doubt about its performance in clustered environments

We must use emqtt in clustered mode and performance is critical.

How much it cost to develop an stomp plugin for us?
Do you guaranty its performance in clustered mode specially when our users using older browsers with SockJS?

**Comment by erylee** [comment]
@rock59, I will support Stomp over SockJS and release the first version in this week. I think SockJS will not be the bottleneck anyway.

**Comment by rock59** [comment]
tnx

**Comment by lsxredrain** [comment]
Stomp over SockJS  is ok?

**Comment by rock59** [comment]
We are using RabbitMQ-Web-Stomp(Stomp over Sockjs) plugin in our current stack and we are satisfied with it
We need a full featured MQTT broker like emqttd and are waiting for your Stomp over Sockjs implementation

**Comment by erylee** [comment]
@lsxredrain, Stomp plugin has been ready: https://github.com/emqtt/emqttd_stomp 
We will integrate SockJS later.

**Comment by rock59** [comment]
Great job..

**Comment by lsxredrain** [comment]
good job,  wait for SockJS,

**Comment by erylee** [comment]
@rock59, The SockJS/Stomp plugin has been released in 0.11.0: https://github.com/emqtt/emqttd_sockjs
