### ISSUE TITLE
Message not delivery

### ISSUE THREAD

**Issue by berrywira** [emqtt/emqttd#278]
Hi,
I have 2 question :
1. Client A send message to client B, when client B offline. after that service emqttd dead or restart, client B online when service has up, but client B not received retained message from client A?
2. Emqttd 3 clustering, when 1 cluster crash, service dead, Client A send message to client B, when client B offline. after that service emqttd up on all cluster ( 3 cluster ), but all emqttd crash. I cannot send any message. and must delete Mnesia on all node emqttd.

Can you help me?

**Comment by erylee** [comment]
Hi Berry,

1. Yes. The broker will not persist messages in current releases

2. All brokers crashed for inconsistent_schema or other reasons?

Regards
Feng

**Comment by berrywira** [comment]
1. whether emqttd will support persist messages soon?

sorry, I don't know what you mean inconsistent_schema
2. what I mean is, I have 3 emqttd in one cluster, I stop one emqttd in the cluster, after that I pub message to another emqttd in the same cluster. when I start again the stoped emqttd, all emqttd in the cluster crash.

**Comment by erylee** [comment]
@berrywira 

1. emqttd will support persistent messages about 0.12.0
2. I will check the cluster issue.

**Comment by berrywira** [comment]
Thanks :+1:

**Comment by erylee** [comment]
@berrywira, I cannot reproduce the cluster issue. I start three nodes:

```
[{'emqttd0@127.0.0.1',disc_copies},
 {'emqttd1@127.0.0.1',ram_copies},
 {'emqttd2@127.0.0.1',ram_copies}] = [schema]
```

![2015-09-06 3 38 26](https://cloud.githubusercontent.com/assets/11869/9703183/9b469662-54ad-11e5-87c7-798c4b87f39c.png)


Step1:

Stop emqttd1 and pubsub messages on emqttd0 and emqttd2, and then start emqttd1. 

Step2:

Stop emqtt0 and pubsub messages on emqttd1 and emqttd2, and then start emqttd0.

Could you send me your crash dump file:

**Comment by berrywira** [comment]
Spec :
MQ 0 with my intern service for add timestamp message for client.
MQ 1 Connect to Client A.
MQ 2 Connect to Client B.
Start all service emqttd, and test pubsub, all can run well.

My step reproduce error :

Stop MQ2, Client B offline. Client A pub messages. and then MQ2 start, MQ2 join cluster to MQ1 manual ,Client B online and not receive any message from Client A. 
After that all MQ cannot pubsub. and must delete dir Mnesia.

And I got error emqtt_error.log :

```
07:55:36.164 <0.395.0> [critical] Session qWWdGwHW@<0.504.0> died unexpectedly!
```

and emqttd_info.log :

```
07:56:16.356 <0.395.0> [critical] Session qWWdGwHW@<0.504.0> died unexpectedly!
07:56:16.356 <0.585.0> [info] Client XX.XX.XX.XX:11201 terminated, reason: {shutdown,session_died}
07:56:16.356 <0.585.0> [info] Protocol shutdown session_died
07:56:16.430 <0.586.0> [info] Connect from XX.XX.XX.XX:11233 -> YY.YY.YY.YY:1883
07:56:16.448 <0.586.0> [info] RECV from qWWdGwHW@XX.XX.XX.XX:11233: CONNECT(Qos=0, Retain=false, Dup=false, ClientId=qWWdGwHW, ProtoName=MQIsdp, ProtoVsn=3, CleanSess=false, KeepAlive=60, Username=undefined, Password=undefined)
```

XX.XX.XX.XX --> my ip client
YY.YY.YY.YY --> Emqttd IP 

By the way, What the command for show list schema like this?
![This](https://cloud.githubusercontent.com/assets/11869/9703183/9b469662-54ad-11e5-87c7-798c4b87f39c.png)

**Comment by berrywira** [comment]
Hi @erylee 
How with this issue? 
Whether you cannot reproduce?

**Comment by erylee** [comment]
@berrywira, I will check this issue after 0.11.0 tagged:)

**Comment by hbyscpp** [comment]
I also have this issue. In cluster env,two node A and B,using LVS for Loadbalance.Client C connect  Node A.
1 stop Node A.
2 start Node A
3In node B,cluster to  Node A
client reconnect.
 produce 
09:48:28.397 <0.828.0> [critical] Session xxx@<0.660.0> died unexpectedly。
