### ISSUE TITLE
emqttd_benchmark concurrent time out

### ISSUE THREAD

**Issue by zuogan** [emqtt/emqttd#281]
I download the emqttd_benchmark code from your git, and i run this benchmark test with 30000 clients, and i used two brokers for testing, emqtt and mosquitto. Of course, i adjust my client machine file max limit. Each time i run the benchmark, it only connect almost half(about 15000 clients) successfully(tcp established). and others failed with error(" {shutdown,timeout}"), i search many docs from others and of course adjust many linux tcp parameters. Unfortunately, they are no use, could you help me how to solve it? Cause i need to test the broker server max concurrent clients number, so i think your benchmark program can help me. Thanks.

**Comment by erylee** [comment]
./run 127.0.0.1 1883 30000 10

**Comment by zuogan** [comment]
I run the test again as your advice, set the create interval time value 10, still 30000 clients test,  and this time the broker server holds 17878 clients established. There are still many clients error("shutdown, timeout"). And at the same time, some clients throw other error, such as "connecttion lost tcp_closed" and "shutdown connack timeout", so do you know what is the reason? Thanks.

**Comment by erylee** [comment]
Mem/CPU of your test client/server? And any logs in emqttd/log/emqttd_error.log?

**Comment by taoyonggang** [comment]
I also test with the emqttd_benchmark . it only connect almost half(about 15000 clients) successfully(tcp established). How improve to 200+K??

I am use ubuntu 14.04 server. Set it with https://github.com/emqtt/emqttd/wiki/One%20Million%20Connections

**Comment by erylee** [comment]
I will write a benchmark test guide later.

**Comment by taoyonggang** [comment]
You need reference the Kafka io design.

**Comment by erylee** [comment]
@zuogan, @taoyonggang. Please download my emqttd.config for your benchmark test. 

I create about 50K connections with 2K messages/sec on a 4G/2Core node:

![image](https://cloud.githubusercontent.com/assets/11869/9780381/a92ce708-57ba-11e5-86db-20dc3b1c7a7e.png)

The broker is on a 32G/8Cores node:

```
[root@i-m7nrq9fa emqttd-0.10.3]# ./bin/emqttd_ctl stats
subscribers/max: 49995
topics/count: 50029
clients/count: 49995
topics/max: 50029
queues/count: 0
sessions/count: 0
sessions/max: 0
queues/max: 0
clients/max: 49995
subscribers/count: 49995
```

```
[root@i-m7nrq9fa emqttd-0.10.3]# ./bin/emqttd_ctl metrics
bytes/received: 88416722
bytes/sent: 84902404
messages/dropped: 2136
messages/received: 1778374
messages/retained: 2
messages/sent: 1778374
packets/connack: 49995
packets/connect: 49995
packets/disconnect: 0
packets/pingreq: 0
packets/pingresp: 0
packets/publish/received: 1778374
packets/publish/sent: 1778374
packets/received: 1878364
packets/sent: 1878364
packets/suback: 49995
packets/subscribe: 49995
packets/unsuback: 0
packets/unsubscribe: 0
```

```
[root@i-m7nrq9fa emqttd-0.10.3]# ./bin/emqttd_ctl listeners
listener http:8083
  acceptors: 4
  max_clients: 64
  current_clients: 0
  shutdown_count: []
listener mqtt:1883
  acceptors: 64
  max_clients: 1000000
  current_clients: 49995
  shutdown_count: []
listener http:18083
  acceptors: 4
  max_clients: 512
  current_clients: 0
  shutdown_count: []
```

Top:

![image](https://cloud.githubusercontent.com/assets/11869/9780429/1f4e005c-57bb-11e5-8c6a-e397945653d1.png)

**Comment by erylee** [comment]
https://github.com/emqtt/emqttd/wiki/emqttd.config

**Comment by taoyonggang** [comment]
I will wirte mqtt server with golang.  The server will support more than 100M connections.
