### ISSUE TITLE
Retain message  Bug

### ISSUE THREAD

**Issue by hbyscpp** [emqtt/emqttd#286]
按照mqtt规范，对于同一个主题，retained message应该只保留最后一个。

发送者 

MQTT mqtt = new MQTT();
		mqtt.setCleanSession(false);
		mqtt.setVersion("3.1.1");
		mqtt.setClientId("123456");
		mqtt.setConnectAttemptsMax(5);
		BlockingConnection bc=mqtt.blockingConnection();
		bc.connect();
		bc.publish("test", new String("456").getBytes(), QoS.EXACTLY_ONCE, true);
		bc.publish("test", new String("789").getBytes(), QoS.EXACTLY_ONCE, true);
               bc.disconnect();

订阅者
             MQTT mqtt = new MQTT();
		mqtt.setCleanSession(false);
		mqtt.setVersion("3.1.1");
		mqtt.setClientId("t123456");
		mqtt.setConnectAttemptsMax(5);
		BlockingConnection bc = mqtt.blockingConnection();
		bc.connect();
		bc.subscribe(new Topic[] { new Topic("test", QoS.EXACTLY_ONCE) });
		while (true) {
			Message m = bc.receive();
			System.out.println(new String(m.getPayload()));
			if (m == null)
				break;
			m.ack();
		}

输出456 和789，按照mqtt规范应该输出为789
查看日志broker接收的时候确实为retain
21:01:01.677 <0.328.0> [info] RECV from 123456@127.0.0.1:33430: PUBLISH(Qos=2, Retain=true, Dup=false, TopicName=test, PacketId=1, Payload=<<"456">>)
21:01:01.683 <0.328.0> [info] RECV from 123456@127.0.0.1:33430: PUBLISH(Qos=2, Retain=true, Dup=false, TopicName=test, PacketId=2, Payload=<<"789">>)

当订阅者链接后
21:01:07.034 <0.329.0> [info] SEND to t123456@127.0.0.1:33431: PUBLISH(Qos=2, Retain=false, Dup=false, TopicName=test, PacketId=12, Payload=<<"456">>)
21:01:07.034 <0.329.0> [info] SEND to t123456@127.0.0.1:33431: PUBLISH(Qos=2, Retain=false, Dup=false, TopicName=test, PacketId=13, Payload=<<"789">>)

**Comment by erylee** [comment]
@hbyscpp, Invalid issue, closed. 
 
For your subscriber is persistent: 

```
订阅者
MQTT mqtt = new MQTT();
mqtt.setCleanSession(false);
mqtt.setClientId("t123456");
```

If you have ever connected to the broker with clientId 't123456', there will be a persistent session to enqueue messages when client if offline.

So the two messages you got is offline messages, not retained. 

You could reproduce with mosquitto_pub/sub:

1. publish two mesages to topic 'test'

```
mosquitto_pub -t test -m 456 -q 2 -r
mosquitto_pub -t test -m 789 -q 2 -r
```

2. subscriber connects to the broker for the first time

```
mosquitto_sub -t test -q 2 -c -i t12345
789
```

3. disconnect the subscriber and publish messages again

```
mosquitto_pub -t test -m 456 -q 2 -r
mosquitto_pub -t test -m 789 -q 2 -r
```

4. subscriber connects the broker again

```
mosquitto_sub -t test -q 2 -c -i t12345
456
789
```

You got two offline messages for persistent session.
