### ISSUE TITLE
mysql_plugin can't connect mysql

### ISSUE THREAD

**Issue by taoyonggang** [emqtt/emqttd#287]
./bin/emqttd_ctl plugins load emqttd_plugin_mysql
load plugin error: {emysql,
                       {{shutdown,
                            {failed_to_start_child,1,
                                {login_failed,
                                    "#28000Access denied for user ''@'localhost' (using password: YES)"}}},
                        {emysql_app,start,[normal,[]]}}}

**Comment by taoyonggang** [comment]
./bin/emqttd_ctl plugins list
Plugin(emqttd_dashboard, version=0.1, description=emqttd web dashboard, active=true)
Plugin(emqttd_plugin_mysql, version=0.10, description=emqttd Authentication/ACL with MySQL, active=false)
Plugin(emqttd_plugin_pgsql, version=0.1, description=emqttd PostgreSQL Plugin, active=false)
Plugin(emysql, version=4.0, description=Erlang MySQL Client, active=false)

**Comment by taoyonggang** [comment]
[
{emysql, [
    {pool, 4},
    {host, "127.0.0.1"},
    {port, 3306},
    {username, "tao"},
    {password, "taotao"},
    {database, "mqtt"},
    {encoding, utf8}
]},
{emqttd_plugin_mysql, [

    %% select password only
    {authquery, "select password from mqtt_user where username = '%u' limit 1"},

    %% hash algorithm: md5, sha, sha256, pbkdf2?
    {password_hash, sha256},

    %% select password with salt
    %% {authquery, "select password, salt from mqtt_user where username = '%u'"},

    %% sha256 with salt prefix
    %% {password_hash, {salt, sha256}},

    %% sha256 with salt suffix
    %% {password_hash, {sha256, salt}},

    %% comment this query, the acl will be disabled
    {aclquery, "select * from mqtt_acl where ipaddr = '%a' or username = '%u' or username = '$all' or clientid = '%c'"},

    %% If no rules matched, return...
    {acl_nomatch, allow}
]}
].

**Comment by erylee** [comment]
Invalid issue. You still use the default etc/plugin.config: https://github.com/emqtt/emqttd_plugin_mysql/blob/master/etc/plugin.config

"#28000Access denied for user ''@'localhost' (using password: YES)"
