### ISSUE TITLE
Switch to rebar3

### ISSUE THREAD

**Issue by phanimahesh** [emqtt/emqttd#289]
rebar3 has many improvements over rebar. It would be great if emqttd moved to using rebar3.

One of the improvements that my use case needs is support for declaring dependencies on hex packages.

[This document](https://www.rebar3.org/docs/from-rebar-2x-to-rebar3) summarizes the changes required to move to rebar3, for reference.

**Comment by erylee** [comment]
@phanimahesh, agree:) would you like to fork the project to try rebar3 first?

**Comment by joaohf** [comment]
Hi,

WIP here: https://github.com/joaohf/emqttd/tree/rebar3

rebar3 compile works. Now I am focus on release and templates files (rel/files).

I think the emqttd plugin build should be revisited. What about plugins using rebar too ?

**Comment by erylee** [comment]
@joaohf, cool:) I agree that the plugins should be revisited. A plugin is just a normal erlang application that could be started/stopped as required. Maybe I need to change the project structure for rebar3.

**Comment by phanimahesh** [comment]
Vernemq handles plugins really well. May be we can look at how it does it?

**Comment by joaohf** [comment]
Hi, now plugins work with rebar3 too.

Just put the plugins into plugins directory. Any OTP application inside plugins will be handled by rebar3.

Another option is to put the plugin as deps. It will work too.

Now I am working on release

**Comment by phanimahesh** [comment]
Wow, the relx config looks so simple, compared to the mess of reltool.

Can you also test the case when a plugin itself is dependent on other apps, let's consider hackney for instance? How can things be arranged so that hackney will be included in the release without having to edit emqttd's relx config?

Putting a rebar.config in the plugin directory listing the deps should do everything, ideally. To my knowledge, there was no way to let reltool look at all plugins and include their dependencies automagically, which prompted me to file this issue. It may be possible with relx.

I haven't found enough time to work on this myself, unfortunately. Thanks @joaohf for your efforts! Your work will save my time next week.

**Comment by joaohf** [comment]
Hi,

See this plugin: https://github.com/joaohf/emqttd_elasticsearch 

rebar3 will take care to get depends.

And now check this: https://github.com/joaohf/emqttd/commit/b7bc938d8c25739c11699e54a40fadc2469b7c18

Using rebar.config.script we can get all the plugins and add to relx release. Without edit rebar.config ;)

To let plugin as simple as possible (and rebar3 too), I think that the contains of 'etc' directory should be in 'priv'. Then the priv dir will be copied. We will not need the etc dir anymore.

Now I am working on release (finally).

**Comment by erylee** [comment]
@joaohf, You did right:) I developed an emqttd_sockjs plugin yesterday and tried to manage the dependencies with:https://github.com/emqtt/emqttd_sockjs/blob/master/rebar.config. But I failed to make a release for rebar will not include the plugin's deps if I don't modify the rel/reltool.config...(

**Comment by phanimahesh** [comment]
Hello @joaohf, Are there any blockers? If this is usable, I suggest we move this discussion to a pull request where it can be merged after some testing.

**Comment by joaohf** [comment]
Hi @phanimahesh. I'm blocking with rebar3 release. emqttd has done small adjusts to rebar scripts. Like the use of 'etc/emqttd.config' and other minor changes.

I'm doing some tests to see the best way to how to handle it.

The worst case: Use rebar3 default release and then go through emqttd release way (config files in etc, and script adjusts).

In this mean time, I'm am investigating this https://github.com/basho/node_package to help with some things.

**Comment by joaohf** [comment]
Hi, with last https://github.com/joaohf/emqttd/tree/rebar3 I got this:

```
joaohf@couve:~/opensource/emqttd/_build/default/rel/emqttd$ bin/emqttd console
config is OK
-config /home/joaohf/opensource/emqttd/_build/default/rel/emqttd/bin/../etc/app.config -args_file /home/joaohf/opensource/emqttd/_build/default/rel/emqttd/bi
n/../etc/vm.args -vm_args /home/joaohf/opensource/emqttd/_build/default/rel/emqttd/bin/../etc/vm.args
!!!!
!!!! WARNING: ulimit -n is 1024; 4096 is the recommended minimum.
!!!!
Exec:  /home/joaohf/opensource/emqttd/_build/default/rel/emqttd/bin/../erts-7.0/bin/erlexec -boot /home/joaohf/opensource/emqttd/_build/default/rel/emqttd/bi
n/../releases/0.1.0/emqttd               -config /home/joaohf/opensource/emqttd/_build/default/rel/emqttd/bin/../etc/app.config -args_file /home/joaohf/opens
ource/emqttd/_build/default/rel/emqttd/bin/../etc/vm.args -vm_args /home/joaohf/opensource/emqttd/_build/default/rel/emqttd/bin/../etc/vm.args              -
pa /home/joaohf/opensource/emqttd/_build/default/rel/emqttd/bin/../lib/emqtt-patches -- console
Root: /home/joaohf/opensource/emqttd/_build/default/rel/emqttd/bin/..
Erlang/OTP 18 [erts-7.0] [source] [64-bit] [smp:4:4] [async-threads:16] [hipe] [kernel-poll:true]

starting emqttd on node 'emqttd@127.0.0.1'
emqttd trace is starting...[done]
emqttd pooler is starting...[done]
emqttd client manager is starting...[done]
emqttd session manager is starting...[done]
emqttd session supervisor is starting...[done]
emqttd pubsub is starting...[done]
emqttd stats is starting...[done]
emqttd metrics is starting...[done]
emqttd broker is starting...[done]
emqttd alarm is starting...[done]
emqttd mode supervisor is starting...[done]
emqttd bridge supervisor is starting...[done]
emqttd access control is starting...[done]
emqttd system monitor is starting...[done]

=INFO REPORT==== 22-Sep-2015::23:03:00 ===
    application: emqttd
    exited: {bad_return,
                {{emqttd_app,start,[normal,[]]},
                 {'EXIT',
                     {undef,
                         [{lager,info,
                              ["load module ~s successfully",[presence]],
                              []},
                          {lists,foreach,2,[{file,"lists.erl"},{line,1337}]},
                          {emqttd_app,start,2,
                              [{file,
                                   "/home/joaohf/opensource/emqttd/_build/default/lib/emqttd/src/emqttd_app.erl"},
                               {line,54}]},
                          {application_master,start_it_old,4,
                              [{file,"application_master.erl"},
                               {line,273}]}]}}}}
    type: permanent
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,emqttd,{bad_return,{{emqttd_app,start,[normal,[]]},{'EXIT',{undef,[{lager,info,[\
"load module ~s successfully\",[presence]],[]},{lists,foreach,2,[{file,\"lists.erl\"},{line,1337}]},{emqttd_app,start,2,[{file,\"/home/joaohf/opensource/emqt
td/_build/default/lib/emqttd/src/emqttd_app.erl\"},{line,54}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}

Crash dump is being written to: erl_crash.dump...done
Kernel pid terminated (application_controller) ({application_start_failure,emqttd,{bad_return,{{emqttd_app,start,[normal,[]]},{'EXIT',{undef,[{lager,info,["l
oad module ~s successfully",[presence]],[
```

Any hint?

With 'rebar shell' lager is founded. By the way is rebar shell useful to emqttd ?

**Comment by erylee** [comment]
In rebar.config:

```
%% fail_on_warning,
{erl_opts, [debug_info, {parse_transform, lager_transform}]}.
```

Please check how to configure this options in rebar3.

**Comment by joaohf** [comment]
Good hint.

There were two erl_opts in rebar.config. 

Now:

```
08:26:06.217 [info] load module presence successfully
08:26:06.218 [error] Cannot find plugins: [emqttd_dashboard]
Erlang MQTT Broker 0.10.4 is running now
```

I need to check minor things and I back here to post the results.

**Comment by erylee** [comment]
@joaohf, I resolved the dependency issue of plugins on my 'dev-feng' branch by adding  'rel/reltool.config.script' :)  Each plugin could have a 'rebar.config' file and let rebar to manage the deps now.  Please check if rebar3 could work with 'rebar.config.script', 'reltool.config.script' like rebar.

**Comment by joaohf** [comment]
Almost done.

General questions:

- Is important to have an etc directory for every plugin? Will be better to put plugin.config inside priv directory and let the build tool handle it?



- To make a release, all apps inside plugins directory goes to _build/default/rel/emqttd/lib. The plugins directory (_build/default/rel/emqttd/plugins) does not exists anymore. However emqttd_plugins.erl will check if plugins dir  has any app. 

During my tests I've created the directory plugins and symbolic link to lib/emqtdd_dashboard-0.1. Like this:
```
jfreitas@jfreitas:~/emqttd/_build/default/rel/emqttd$ ls -l plugins/
total 0
lrwxrwxrwx 1 jfreitas jfreitas 27 Set 24 10:34 emqttd_dashboard -> ../lib/emqttd_dashboard-0.1
lrwxrwxrwx 1 jfreitas jfreitas 31 Set 24 10:34 emqttd_elasticsearch -> ../lib/emqttd_elasticsearch-0.1
```

Then emqttd load the plugins.

The list of plugins that will be loaded could be place in a config file instead a plugins directory? Like this:

```
emqttd.conf:

    %% Plugins
    {plugins, [
        %% Plugin App Library Dir
        {plugins, ["emqttd_dashboard", "emqttd_elasticsearch"]},

        %% File to store loaded plugin names.
        {loaded_file, "./data/loaded_plugins"}
    ]}
```

**Comment by phanimahesh** [comment]
This is actually a very good idea. `priv` is the standard place to put anything you want bundled with the application, mostly assets and external dependencies. Configuration has traditionally been left out of `priv` ( I haven't seen it being done, yet ).

But I like this idea. Every plugin's config lives with it.

**Comment by erylee** [comment]
How about the ebin/emqttd_plugin_xxx.app to configure environments of a plugin?

**Comment by joaohf** [comment]
Nice idea. This will save a few lines of code.

And what about the plugins directory? It's important to keep the current behaviour?

**Comment by phanimahesh** [comment]
Isn't it unusual to store config in plugin app files? I haven't seen it being done anywhere else.

**Comment by phanimahesh** [comment]
Also, it is standard practice to provide a config sample in the codebase, and a config file derived from it is placed at appropriate location during the deployments. So I don't think moving the plugin config from `etc` to either `*.app` or `priv` is a good idea.

If typical release strategies are considered, build and deploy phases are clearly separated. The configuration should be replaceable after the build, just before application is started.

The best strategy is to make every plugin provide a config.sample, and have a single consolidated config in `emqttd/etc`, or config files named after plugins in `emqttd/etc`. Having the config files all over the place only makes deployments difficult.

**Comment by erylee** [comment]
@phanimahesh, Agree with you. Could we copy all of the plugin's config files to emqttd/etc/plugins/ folder when building a release?

```
emqttd/etc/plugins/
      emqttd_dashboard.config
     emqttd_stomp.config
     emqttd_plugin_pgsql.config
```

**Comment by phanimahesh** [comment]
Yep. Or have everything in `emqttd.config`. Everyone has to customize this anyway, so why split the config?

Also, is it possible to reload config at runtime? There doesn't appear to be a way currently.

**Comment by Prots** [comment]
What about erlang.mk tool for dependency management and release assembling? 
I think it is more powerful and quick than rebar, but I don't know about rebar3.

**Comment by joaohf** [comment]
Hi, 

See: #401

**Comment by emqplus** [comment]
Switch to erlang.mk in 2.0 release: https://github.com/emqtt/emqttd-relx

**Comment by drasko** [comment]
@emqplus why this move to `erlang.mk`? It has not been explained in this discussion - what is the advantage of `erlang.mk` over `rebar3`?
