### ISSUE TITLE
Efficient data transfer through zero copy

### ISSUE THREAD

**Issue by taoyonggang** [emqtt/emqttd#293]
http://www.ibm.com/developerworks/library/j-zerocopy/

**Comment by erylee** [comment]
@taoyonggang, This is the traditional DMA copy trick that Kafka sendFile used. It works for persistent queue/log systems that need high throughput. It's not suitable for in-memory pubsub broker like emqttd that aimed to handle massive connections with low latency and low throughput.

Closed, Thanks.

**Comment by taoyonggang** [comment]
You can use kennel network to replace the user network . It can save cpu and memory copy time.
