### ISSUE TITLE
how to support offline messages ?

### ISSUE THREAD

**Issue by honger05** [emqtt/emqttd#295]
Hi, I'm a javascripter

I don't konw how does offline-messages work!

As far as I can understand, connected the host, and subscribe a topic, then can receive the messages that host published.

Then disconnected the host, can I receive the messages when connected ? the answer is no.

I must connect and subscribe first.

 so how does offline-messages mean ?

**Comment by erylee** [comment]
MQTT protocol supports 'clean session' flag.  If the 'clean session' is set to false, the broker will keep a session to receive messages when the client is disconnected.

**Comment by therahulprasad** [comment]
If you are using npm mqtt module. You can use this code: 

    var uniqueid = "some-unique-id";
    var client  = mqtt.connect('mqtt://host-name/', {
      protocolId: 'MQIsdp', 
      protocolVersion: 3,
      clientId: 'id_' + uniqueid,
      clean: false
    });
    client.subscribe('topic', {qos: 2});
    client.publish('topic', 'Hello ' + friendphone, {qos:2});


1. Keeping a clientId will maintain a session in server. 
2. clean(session) = false will not clean session if client disconnect
3. whatever message you publish or subscribe, do it with qos=1 or 2

**Comment by chriz-kiran** [comment]
Hi, am a newbie trying to get to know about emqtt.

Can you please clarify the following things

1. with clean_sess flag set to false, will the messages get stored even after the client has disconnected and are those messages delivered as soon as the client reconnects?

2. How the subscriptions and topics are stored in emqttd broker using ets or dets or mnesia.
