### ISSUE TITLE
How do I allow user with some pattern to access topic with some pattern ?

### ISSUE THREAD

**Issue by therahulprasad** [emqtt/emqttd#297]
How do I allow users with username __user_{uniqueId}__ to only subscribe to topic __user/{uniqueId}__ ?

**Comment by erylee** [comment]
@therahulprasad, could write an extended module like emqttd_mod_autosub.erl, then configure etc/emqttd.config to add your module.

```
   %% Modules
    {modules, [

        {yourmod, []},

        %% Client presence management module.
        %% Publish messages when client connected or disconnected
        {presence, [{qos, 0}]}

        %% Subscribe topics automatically when client connected
        %% {autosub, [{"$Q/client/$c", 0}]}
```

In the extended module named emqttd_mod_yourmod:

```
client_connected(?CONNACK_ACCEPT, #mqtt_client{ username = <<"user_", UniqueId/binary>>, client_pid = ClientPid}, Opts) ->
    emqttd_client:subscribe(ClientPid, [{<<"user/", UniqueId/binary>>, qos1}]);
```

**Comment by therahulprasad** [comment]
Thanks for quick reply @erylee. I see that you added it to 0.11.0 milestone. Are you planning a regex based pattern matching capability directly into core module ? :)

**Comment by erylee** [comment]
This feature has been supported in 0.10.x. The emqttd_mod_autosub.erl module supports $c, $u variables without regex pattern. You could use the whole username in the topic, I think:)

```
{autosub, [{"user/$u", 0}]}
```
