### ISSUE TITLE
In a cluster is data shared or are separate for each node ?

### ISSUE THREAD

**Issue by therahulprasad** [emqtt/emqttd#298]
Hello, I have few questions.
1. Where is data stored, memory or disk ? 
2. In a cluster, is everything copied in each server like a replica ? or every node keeps its own set of messages, it just copies topic and subscriber list ?
3. If everything is stored in memory, does it fall back to disk in case there is low memory ?

Thanks in advance :)

**Comment by erylee** [comment]
1. Memory
2. Only topics tree is copied.
3. No. Will support later.

Wiki: https://github.com/emqtt/emqttd/wiki/Cluster%20Design
