### ISSUE TITLE
What happens if a node goes down in a cluster ?

### ISSUE THREAD

**Issue by therahulprasad** [emqtt/emqttd#299]
1. If a node goes down (hard reboot) in a cluster, I assume client will reconnect with another node. In that case what happens to messages stored in that node which is not yet delivered to subscribers ?

2. If I have to stop emttd daemon, will it dump data from memory and load it back when it restarts ?

**Comment by erylee** [comment]
1. Client will connect another node, messages not delivered will be dropped. 
2. No. I plan to persist subscriptions/messages to leveldb or kakfa after emqttd 1.0. released.

**Comment by therahulprasad** [comment]
Is it possible to persist subscriptions/messages to redis?

**Comment by erylee** [comment]
@therahulprasad, what's type of your application? IoT, Mobile IM? Please check https://github.com/emqtt/emqttd_plugin_template. Could extend the broker by hooks and plugin, and persist subscriptions/messages to redis, mongodb or sql database.

**Comment by therahulprasad** [comment]
Its a mobile IM. Thanks for the link

**Comment by brechmos** [comment]
Hey, I was wondering if #2 (persist subscriptions/messages) has been implemented in the code base? That would be very useful...
