### ISSUE TITLE
How can I test the max connections?

### ISSUE THREAD

**Issue by FlowerWrong** [emqtt/emqttd#305]
Hi, I want to test the max connections number on my server.
How can I do it?

**Comment by erylee** [comment]
@FlowerWrong, Wiki:

https://github.com/emqtt/emqttd/wiki/One%20Million%20Connections

https://github.com/emqtt/emqttd/wiki/etc-emqttd.config-for-benchmark

https://github.com/emqtt/emqttd/wiki/etc-vm.args-for-benchmark
