### ISSUE TITLE
Java client ?

### ISSUE THREAD

**Issue by muhun** [emqtt/emqttd#307]
is there any Java client available for this broker for android development ? or is that in pipeline  ? 
can it work with Paho Java client ?

**Comment by erylee** [comment]
@muhun, You could use Paho Java Client or https://github.com/fusesource/mqtt-client

These client libraries works well with emqttd broker:)

**Comment by muhun** [comment]
@erylee , thank you ! I am trying some broadcast system for huge number of participants, this broker seems very promising , I want to give a try , Cheers

**Comment by erylee** [comment]
Okay, The broker could support 1 million client connections now:) Please check Wiki for benchmark and tuning guide.

**Comment by elsennov** [comment]
Hi @emqplus , Do you know what is the best option for android between Paho and Fuse Source Mqtt Client?

**Comment by emqplus** [comment]
@elsennov, Paho.

**Comment by elsennov** [comment]
@emqplus Thanks!
