### ISSUE TITLE
Beam.smp memory used

### ISSUE THREAD

**Issue by berrywira** [emqtt/emqttd#308]
Hi @erylee ,

Can I limit Beam.smp usage memory? 
because beam.smp use all of my memory .

**Comment by erylee** [comment]
@berrywira, How many connections, messages per sec? How much memory consumed?  Please check logs to find if there are errors occurred.

**Comment by berrywira** [comment]
Memory consumed :

<img width="414" alt="screen shot 2015-09-23 at 1 40 03 pm" src="https://cloud.githubusercontent.com/assets/9605173/10039029/7424b138-61f8-11e5-8c9a-09a1376aee2f.png">

Connection value :
```
./emqttd_ctl stats
subscribers/max: 287
topics/count: 321
clients/count: 29
topics/max: 321
queues/count: 0
sessions/count: 42
sessions/max: 42
queues/max: 0
clients/max: 34
subscribers/count: 287
```

Metric
```
./emqttd_ctl metrics
bytes/received: 3582807
bytes/sent: 2786964
messages/dropped: 670870
messages/received: 12685
messages/retained: 2
messages/sent: 21137
packets/connack: 6021
packets/connect: 6021
packets/disconnect: 20
packets/pingreq: 108922
packets/pingresp: 108922
packets/publish/received: 12685
packets/publish/sent: 21137
packets/received: 183562
packets/sent: 184956
packets/suback: 41027
packets/subscribe: 41027
packets/unsuback: 0
packets/unsubscribe: 0
```

And this Log error, too much error duplicate clientid :

<img width="709" alt="screen shot 2015-09-23 at 1 44 42 pm" src="https://cloud.githubusercontent.com/assets/9605173/10039125/1ee4f312-61f9-11e5-86ce-529780e61f0e.png">

**Comment by erylee** [comment]
@berrywira,there are something wrong... It should not consume memory more then 100M!

```
./bin/emqttd_ctl listeners
```

Pls zip your log files and send to me: feng@emqtt.io, Thanks.

**Comment by berrywira** [comment]
@erylee 

<img width="489" alt="screen shot 2015-09-23 at 5 12 31 pm" src="https://cloud.githubusercontent.com/assets/9605173/10042570/1dbac4ae-6216-11e5-9c64-660715066136.png">

I was send log error to you. please check, Thanks.

**Comment by hbyscpp** [comment]
my beam.smp also consume lots of memeory. 7.4G of 8G
running 11days

 ./emqttd_ctl metrics
bytes/received: 7303765
bytes/sent: 44448214
messages/dropped: 2609993
messages/received: 11872
messages/retained: 490
messages/sent: 81105
packets/connack: 326
packets/connect: 341
packets/disconnect: 118
packets/pingreq: 41540
packets/pingresp: 41540
packets/publish/received: 11872
packets/publish/sent: 81105
packets/received: 68505
packets/sent: 132953
packets/suback: 302
packets/subscribe: 331
packets/unsuback: 0
packets/unsubscribe: 0

**Comment by erylee** [comment]
@hbyscpp,  please attach result of the admin commands:

````
./bin/emqttd_ctl stats

./bin/emqttd_ctl listeners
```

 the mail I sent to @berrywira:

There are three issues I found from logs:

1. Should remove the ‘info’ level log of lager:  

{lager, [
    {colored, true},
    {async_threshold, 1000},
    {error_logger_redirect, false},
    {crash_log, "log/emqttd_crash.log"},
    {handlers, [
        {lager_file_backend, [
            {formatter_config, [time, " ", pid, " [",severity,"] ", message, "\n"]},
            {file, "log/emqttd_error.log"},
            {level, error},
            {size, 104857600},
            {date, "$D0"},
            {count, 30}
        ]}
    ]}
 ]},

2. Configure pool_size of pubsub:

```
        %% PubSub
        {pubsub, [
            %% default should be scheduler numbers
           {pool_size, 8}
        ]},
```
....

**Comment by erylee** [comment]
@berrywira, @hbyscpp. Please check your Erlang/OTP version. It seems this issue is caused by Erlang/OTP R18.0 binary memory leak: http://erlang.org/pipermail/erlang-questions/2015-September/086098.html

**Comment by hbyscpp** [comment]
@erylee  Thanks.I will upgrade OTP.

**Comment by berrywira** [comment]
sorry for late respon.
Now I used Erlang/OTP version 18.  I will try uptade the version.
But, this issue just because erlang otp issue, or I must off log level 'info' and config pool_size? 
This is server development, I need all log for see the error.

**Comment by erylee** [comment]
@berrywira, yes, just an Erlang/OTP R18 issue. All the binary memory allocated for logs will not be released.

1. Keep the 'info' log level if Erlang/OTP upgraded. 
2. Tune the pubsub pool_size

Thanks for you bug report:)

**Comment by berrywira** [comment]
Ok, now used memory normaly. Thank you very much.
