### ISSUE TITLE
Injecting timestamp into a message's payload

### ISSUE THREAD

**Issue by ghost** [emqtt/emqttd#309]
Although the MQTT protocol does not specify a method of including timestamps in packets, it would come in handy in a variety of scenarios. Would there be an easy way (via some kind of custom-written interceptor, for example) for the broker to "inject" a timestamp into the payload of a `PUBLISH` packet?

**Comment by erylee** [comment]
For QoS1/2 message, the message id contains timestamp:

```
emqttd_guid:timestamp(MsgId)
```

**Comment by bmcustodio** [comment]
@erylee hmm, and how do I access that from a client?

**Comment by bmcustodio** [comment]
@erylee Ok, so let me make a simple test and I will get back and report if that suffices for my use case :-)

**Comment by erylee** [comment]
Want the timestamp from client??? You have to sync the time with the broker first, and then calculate the timestamp.

**Comment by bmcustodio** [comment]
@erylee I need the timestamp from the broker. What I was asking is if there was an easy way (I know its a hackish solution) to modify the payload of any `PUBLISH` packets to include this timestamp, say, as the first 4 bytes.

**Comment by lsxredrain** [comment]
just like rest api?

**Comment by erylee** [comment]
@bmcustodio,  'message.publish' hook.

https://github.com/emqtt/emqttd_plugin_template/blob/master/src/emqttd_plugin_template.erl

**Comment by bmcustodio** [comment]
@erylee That's exactly what I was looking for. Seems like it is working in my case :-) Many thanks.

**Comment by bmcustodio** [comment]
@erylee I guess now the only notable case in which I can't inject the timestamp is in the payload of the Last Will and Testament. Is there any hook in place for when this particular message is delivered?

**Comment by erylee** [comment]
Invalid now.
