### ISSUE TITLE
unsubcribe will  lead to  crash

### ISSUE THREAD

**Issue by lsxredrain** [emqtt/emqttd#312]
09:25:08.878 [info] SEND to a827dfab001741756404a4bc914f817a@192.168.153.239:60276: PUBACK(Qos=0, Retain=false, Dup=false, PacketId=1)
client a827dfab001741756404a4bc914f817a will subscribe 000 [{<<"/room/1443144308876275">>,
                                                             1}]
client a827dfab001741756404a4bc914f817a subscribed [{<<"/room/1443144308876275">>,
                                                     1}]
09:25:08.879 [info] Session(a827dfab001741756404a4bc914f817a): subscribe [{<<"/room/1443144308876275">>,1}], Granted QoS: [1]
09:25:08.879 [info] SEND to a827dfab001741756404a4bc914f817a@192.168.153.239:60276: PUBLISH(Qos=1, Retain=false, Dup=false, TopicName=/client/a827dfab001741756404a4bc914f817a, PacketId=1, Payload=<<"{\"type\":\"createresult\",\"ts\":1443144309,\"rn\":\"/room/1443144308876275\",\"rk\":\"\"}">>)
09:25:08.894 [info] RECV from a827dfab001741756404a4bc914f817a@192.168.153.239:60276: PUBACK(Qos=0, Retain=false, Dup=false, PacketId=1)
09:25:08.895 [info] client a827dfab001741756404a4bc914f817a acked Message(MsgId=undefined, PktId=1, from=a827dfab001741756404a4bc914f817a, Qos=1, Retain=false, Dup=false, Topic=/client/a827dfab001741756404a4bc914f817a)
09:25:08.895 [info] client acked Qos 1
09:25:08.934 [info] RECV from a827dfab001741756404a4bc914f817a@192.168.153.239:60276: UNSUBSCRIBE(Qos=1, Retain=false, Dup=false, PacketId=2, Topics=[<<"/room/1443144308876275">>])
client a827dfab001741756404a4bc914f817a unsubscribe [<<"/room/1443144308876275">>]

=ERROR REPORT==== 25-Sep-2015::09:25:08 ===
** Generic server <0.389.0> terminating
** Last message in was {unsubscribe,[<<"/room/1443144308876275">>]}
** When Server state == {session,false,
                            <<"a827dfab001741756404a4bc914f817a">>,<0.395.0>,
                            #Ref<0.0.0.2345>,2,
                            [{<<"/room/1443144308876275">>,1},
                             {<<"/user/c7f16df034335c960d026f2f6bce8593/data">>,
                              2},
                             {<<"/user/c7f16df034335c960d026f2f6bce8593/signal">>,
                              2},
                             {<<"/client/a827dfab001741756404a4bc914f817a">>,
                              2}],
                            [],100,
                            {mqueue,<<"a827dfab001741756404a4bc914f817a">>,
                                {[],[]},
                                0,20,60,100,true,0,
                                #Fun<emqttd_alarm.0.113092>},
                            #{},8,0,#{},3,4,#{},172800,undefined,10,
                            #Ref<0.0.0.2356>,
                            {1443,144007,468900}}
** Reason for termination ==
** {function_clause,[{emqttd_pubsub,unsubscribe,
                                    [ok],
                                    [{file,"src/emqttd_pubsub.erl"},
                                     {line,155}]},
                     {emqttd_session,handle_call,3,
                                     [{file,"src/emqttd_session.erl"},
                                      {line,326}]},
                     {gen_server2,handle_msg,2,
                                  [{file,"src/gen_server2.erl"},{line,1019}]},
                     {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,247}]}]}
09:25:08.935 [info] Client(192.168.153.239:60276) terminated, reason: {{function_clause,[{emqttd_pubsub,unsubscribe,[ok],[{file,"src/emqttd_pubsub.erl"},{line,155}]},{emqttd_session,handle_call,3,[{file,"src/emqttd_session.erl"},{line,326}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1019}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server2,call,[<0.389.0>,{unsubscribe,[<<"/room/1443144308876275">>]},60000]}}
09:25:08.935 [info] Client a827dfab001741756404a4bc914f817a@192.168.153.239:60276: shutdown {{function_clause,[{emqttd_pubsub,unsubscribe,[ok],[{file,"src/emqttd_pubsub.erl"},{line,155}]},{emqttd_session,handle_call,3,[{file,"src/emqttd_session.erl"},{line,326}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1019}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server2,call,[<0.389.0>,{unsubscribe,[<<"/room/1443144308876275">>]},60000]}}
09:25:08.936 [info] Client a827dfab001741756404a4bc914f817a send willmsg: {mqtt_message,undefined,undefined,<<"/drop/900000/0c3279ef-a6f2-375a-9717-1f0287a523ab">>,undefined,0,false,false,false,<<"{\"uid\":\"lsx\",\"authtype\":\"TOKEN\",\"appid\":\"900000\",\"vs\":1,\"clienttype\":\"android\"}">>,{1443,144295,62046}}
client a827dfab001741756404a4bc914f817a disconnected, reason: {{function_clause,[{emqttd_pubsub,unsubscribe,[ok],[{file,[115,114,99,47,101,109,113,116,116,100,95,112,117,98,115,117,98,46,101,114,108]},{line,155}]},{emqttd_session,handle_call,3,[{file,[115,114,99,47,101,109,113,116,116,100,95,115,101,115,115,105,111,110,46,101,114,108]},{line,326}]},{gen_server2,handle_msg,2,[{file,[115,114,99,47,103,101,110,95,115,101,114,118,101,114,50,46,101,114,108]},{line,1019}]},{proc_lib,wake_up,3,[{file,[112,114,111,99,95,108,105,98,46,101,114,108]},{line,247}]}]},{gen_server2,call,[<0.389.0>,{unsubscribe,[<<47,114,111,111,109,47,49,52,52,51,49,52,52,51,48,56,56,55,54,50,55,53>>]},60000]}}

**Comment by erylee** [comment]
This issue is caused by emqttd_plugin_template plugin. 

```
diff --git a/src/emqttd_plugin_template.erl b/src/emqttd_plugin_template.erl
index b120d02..466a18e 100644
--- a/src/emqttd_plugin_template.erl
+++ b/src/emqttd_plugin_template.erl
@@ -79,7 +79,8 @@ on_client_subscribe_after(ClientId, TopicTable, _Env) ->
     io:format("client ~s subscribed ~p~n", [ClientId, TopicTable]).

 on_client_unsubscribe(ClientId, Topics, _Env) ->
-    io:format("client ~s unsubscribe ~p~n", [ClientId, Topics]).
+    io:format("client ~s unsubscribe ~p~n", [ClientId, Topics]),
+    Topics.
```
