### ISSUE TITLE
Debugging emqttd

### ISSUE THREAD

**Issue by bmcustodio** [emqtt/emqttd#321]
@erylee do you have any idea how I can debug emqttd in my local development environment (set breakpoints, watch variables, etc)? I tried to load the project using [intellij-erlang](http://ignatov.github.io/intellij-erlang/) but I can't seem to be able to run the broker (I really can't figure out what I must put in the debug configuration). What do you use in your daily development? :-) Sorry for the question, but I am a big Erlang noob.

**Comment by erylee** [comment]
@bmcustodio, I write Erlang with vim. If you try to use intellij-erlang, you should import the project as 'rebar' mode, I think.

For erlang is a FP lauguage, I never set breakpoints and debug the program:) Write some tests, let it crash, and fix it.

**Comment by bmcustodio** [comment]
@erylee I understand :-) Many thanks!
