### ISSUE TITLE
Make "client.disconnected" receive #mqtt_client

### ISSUE THREAD

**Issue by bmcustodio** [emqtt/emqttd#322]
Just like the `client.connected` hook receives a `#mqtt_client` record, could `client.disconnected` receive the same `#mqtt_client` record instead of simply receiving a `ClientId`?

**Comment by erylee** [comment]
Try:

```
case emqttd_cm:lookup(ClientId) of
    undefined -> ok;
    Client -> do_something
end.
```

**Comment by bmcustodio** [comment]
@erylee worked like a charm! Many thanks!

**Comment by bmcustodio** [comment]
@erylee `emqttd_cm:lookup` is not working in clustered mode. For instance, I have two nodes (`n1` and `n2`) and a client connected to `n1`. In `n1`, `emqttd_cm:lookup` returns the corresponding `#mqtt_client` record but in `n2` it returns `undefined`. Is there any way this information can be replicated or at least made accessible across nodes?

**Comment by erylee** [comment]
Of c. Cluster will not replicate the client.
