### ISSUE TITLE
Supported Number of Connections Greatly Reduced When Clients are Subscribing

### ISSUE THREAD

**Issue by galvezlj** [emqtt/emqttd#324]
I was able to reach around 700K connections from my benchmark application when I set my clients not to subscribe to any queue.  But when I start making each connection subscribe to a queue, It dropped to less than 150K connections.  I am using mqtt.js to test subscription.

**Comment by erylee** [comment]
@galvezlj, would you like to use mqtt.js test subscription to benchmark 0.12.0 release again?
