### ISSUE TITLE
benchmark error

### ISSUE THREAD

**Issue by smartbruce** [emqtt/emqttd#328]
single machine(4core 8G),beyond 60K connection,emqttd server occurs error:
21:01:39.448 <0.231.0> [error] large_heap: gcpid = <0.444.0>,[{registered_name,[]},{memory,73395528},{message_queue_l
en,0},{heap_size,2984878},{total_heap_size,9174318}]
 [{old_heap_block_size,6189440},{heap_block_size,2984878},{mbuf_size,0},{stack_size,256101},{old_heap_size,4293792},{
heap_size,577578}]
21:01:49.080 <0.231.0> [error] large_heap: gcpid = <0.443.0>,[{registered_name,[]},{memory,78171328},{message_queue_l
en,0},{heap_size,3581853},{total_heap_size,9771293}]
 [{old_heap_block_size,6189440},{heap_block_size,3581853},{mbuf_size,0},{stack_size,255329},{old_heap_size,4004547},{
heap_size,853094}]
21:01:59.092 <0.231.0> [error] large_heap: gcpid = <0.443.0>,[{registered_name,[]},{memory,73395544},{message_queue_l
en,0},{heap_size,2984878},{total_heap_size,9174318}]
 [{old_heap_block_size,6189440},{heap_block_size,2984878},{mbuf_size,0},{stack_size,255737},{old_heap_size,4162439},{
heap_size,702709}]
21:02:09.440 <0.231.0> [error] large_heap: gcpid = <0.444.0>,[{registered_name,[]},{memory,73395528},{message_queue_l
en,0},{heap_size,2984878},{total_heap_size,9174318}]
 [{old_heap_block_size,6189440},{heap_block_size,2984878},{mbuf_size,0},{stack_size,255724},{old_heap_size,4162462},{
heap_size,702696}]
21:02:39.054 <0.231.0> [error] large_heap: gcpid = <0.443.0>,[{registered_name,[]},{memory,73395544},{message_queue_l
en,0},{heap_size,2984878},{total_heap_size,9174318}]
 [{old_heap_block_size,6189440},{heap_block_size,2984878},{mbuf_size,0},{stack_size,255857},{old_heap_size,4215457},{
heap_size,652229}]
21:03:09.054 <0.231.0> [error] large_heap: gcpid = <0.443.0>,[{registered_name,[]},{memory,73395544},{message_queue_l
en,0},{heap_size,2984878},{total_heap_size,9174318}]
 [{old_heap_block_size,6189440},{heap_block_size,2984878},{mbuf_size,0},{stack_size,255857},{old_heap_size,4215470},{
heap_size,652216}]

**Comment by erylee** [comment]
Ignore this warning message.

**Comment by erylee** [comment]
Attach to the VM and find the processes with large heap:

```
  ./bin/emqttd attach

erlang:process_info(pid(0, 443,0)).

```

CTRL+D to exit.

**Comment by erylee** [comment]
Suppress sysmon messages: https://github.com/emqtt/emqttd/pull/338
