### ISSUE TITLE
Compilation fails if repo is cloned with a different name

### ISSUE THREAD

**Issue by phanimahesh** [emqtt/emqttd#348]
This is because `..` is added to `lib_dirs` and `include_lib` is used to include emqttd's own header files. This is a very ugly hack and compilation fails under our CI environment.

Why are we not using `include` with relative paths instead?

**Comment by erylee** [comment]
@phanimahesh, agree that this is a boring issue.

If we use relative path, have to "-inclue("../../../include/emqttd.hrl"). It seems a bit ugly:(

**Comment by phanimahesh** [comment]
If erlang include path is set properly, it should be possible to just do `-include("emqttd.hrl")`, right?

**Comment by erylee** [comment]
Hi @phanimahesh, I comment the 'lib_dir'  in rebar.config:)
