### ISSUE TITLE
Retained Messages Delivered Only Once?

### ISSUE THREAD

**Issue by ghost** [emqtt/emqttd#349]
I've run into a strange behaviour in which I have 5 retained messages across different topics (all under `msg/<something>`, and a client connecting and subscribing to `msg/#`. Now, if the client connects using a clean session, these retained messages are delivered every time the client connects (the expected behaviour). However, if clean session is set to `false`, the client only receives them once (the first time the client connects). I would say this behaviour is unexpected, as I believe retained messages should be delivered every time an interested client connects (regardless of whether its session is clean or not). Could you reproduce this @erylee?

**Comment by bmcustodio** [comment]
BTW, I'm using both  `0.11.0` and `0.12.1`.

**Comment by bmcustodio** [comment]
@erylee it may be interesting to notice that I can work around this by first unsubscribing from `msg/#` and then re-subscribing it. However, this is a workaround I would prefer not to use.

**Comment by erylee** [comment]
@bmcustodio, sorry for late reply. A business trip to Beijing yesterday. 

The retained messages will be delivered when new subscriptions created. The persistent sessions(clean session = 0) cached all the subscriptions, so retained messages will not be dispatched when a client resume an existed session. 

I will check the MQTT V3.1.1 protocol specification to check if the broker works properly.

**Comment by bmcustodio** [comment]
@erylee no problem at all. I have re-read the protocol spec now and, indeed, I see no mention as to whether retained messages should be re-delivered in case of a non-clean session (so this might indeed be expected). However, it would be great if the broker's behaviour could be extended to support this (the way I see it the protocol leaves this matter open, so it could be implemented as an extension). What do you think? Do you agree?

**Comment by erylee** [comment]
Okay, I will check it later. Maybe we could add a config item in etc/emqttd.config to support this feature.

**Comment by bmcustodio** [comment]
@erylee that would be great indeed :-)

**Comment by syberkitten** [comment]
@emqplus We have an issue with version 2.2
Where a client that subscribes to topics
when connects again with with clean session false
does not get the retained message for the topics it subscribed.

This is a good breakdown of the differences of behavior,
http://www.steves-internet-guide.com/mqtt-clean-sessions-example/

is Test 4. Supported? Whe QoS 1 for publish and subscribe yields retained
messages when re-connecting?
