### ISSUE TITLE
Subscribing to Identic Topic Filters

### ISSUE THREAD

**Issue by ghost** [emqtt/emqttd#352]
@erylee  I don't know whether this can be related to #349, but I came across this while trying to find a workaround for it.

[MQTT-3.8.4-3] states that

> A subscribe request which contains a Topic Filter that is identical to an existing Subscription’s Topic Filter completely replaces that existing Subscription with a new Subscription.

However, I think that [this check](https://github.com/emqtt/emqttd/blob/master/src/emqttd_session.erl#L305) kinda goes against this rule, for if the topic filter is the same the subscriptions are in fact not being replaced currently. What is your opinion on this?

**Comment by mtappler** [comment]
I actually observed a related issue (also similar to #349, but without disconnecting). If I subscribe to a topic with a retained message twice, I receive the retained message only once, whereas [MQTT-3.8.4-3] further states that

>  Any existing retained messages matching the Topic Filter MUST be re-sent, but the flow of publications MUST NOT be interrupted

**Comment by emqplus** [comment]
Has been fixed in 1.x
