### ISSUE TITLE
emqttd_ctl: 'subscriptions' command to force clients to subscribe some topics

### ISSUE THREAD

**Issue by zgysc** [emqtt/emqttd#361]
1. bin/emqttd_ctl
2. HTTP API

**Comment by zgysc** [comment]
我已经在emqtt_http里实现了，呵呵，就是代码太ugly，

handle_request('GET',"/mqtt/subtopic", Req) ->
  Params=mochiweb_request:parse_qs(Req),
  ClientId = list_to_binary(get_value("clientId", Params, http)),
  Topic = list_to_binary(get_value("topic", Params, http)),
  case  emqttd_sm:lookup_session(ClientId) of
  undefined ->
        Req:ok({"text/plain", <<"BAD_CLIENT">>});
  Session ->
  lager:info("SUBTOPIC:Finded session: ~p", [Session]),
  #mqtt_session{sess_pid = Sess_pid} = Session,
  lager:info("SUBTOPIC:sessionId is: ~p", [Sess_pid]),
  _Status = emqttd_session:subscribe(Sess_pid, [{Topic, 1}]),
  lager:info("SUBTOPIC:subtopic result: ~p" ,[_Status]),
  Req:ok({"text/plain",<<"ok">>})
  end;

**Comment by erylee** [comment]
Add './bin/emqttd_ctl subscriptions' command:

```
$ ./bin/emqttd_ctl subscriptions
subscriptions list                      #list all subscriptions
subscriptions show <ClientId>           #show subscriptions of a client
subscriptions add <ClientId> <Topic> <Qo#add subscription
subscriptions del <ClientId> <Topic>    #delete subscription
```

**Comment by erylee** [comment]
HTTP API should be supported by dashboard plugin:  https://github.com/emqtt/emqttd_dashboard/issues/40
