### ISSUE TITLE
How I can send message from plugin?

### ISSUE THREAD

**Issue by Prots** [emqtt/emqttd#376]
I'm developing plugin for emqttd, and have a question: how I can publish message to client from plugin after subscription not using once more emqttc and TCP connection ?

**Comment by Prots** [comment]
I think I found a solution =)
```erl
on_client_subscribe_after(_ClientId, TopicTable, _Env) ->
    [{Topic, _Type}] = TopicTable,
    Msg = emqttd_message:make(broker, Topic, <<"Hello client">>),
    io:format("Message for client: ~p~n", [Msg]),
    Res = emqttd_pubsub:publish(Msg),
    io:format("emqttd_pubsub:publish: ~p~n", [Res]).
```

**Comment by erylee** [comment]
Hi Igor, call emqttd_pubsub:publish/1 API directly?

**Comment by Prots** [comment]
Yes, looks like it works.
It needs, for example, when you want get messages for client from redis and publish it directly from plugin.

**Comment by erylee** [comment]
It works.

**Comment by Prots** [comment]
Thanks.

**Comment by erylee** [comment]
Your solution is elegant:)

```
on_client_subscribe_after(_ClientId, TopicTable, _Env) ->
    .....
```

**Comment by BADBDY23** [comment]
I'm trying to publish message to specific topic, and i even tried the solution in this topic, but it didn't work.
the first problem with this solution is `emqttd_pubsub:publish(Msg)` function needs two parameters. 
so I'd be happy to show me a way to solve the problem
