### ISSUE TITLE
CentOS系统上使用非root用户启动emqttd时启动不了

### ISSUE THREAD

**Issue by kansifang** [emqtt/emqttd#379]
我在CentOS系统上使用非root用户启动emqttd时启动不了，错误信息如下：

文件权限修改：
chown -R emqttd.emqttd /home/emqttd
chmod -R 755  /home/emqttd

[emqttd]$ bin/emqttd start
emqttd failed to start within 15 seconds,
see the output of 'emqttd console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.

**Comment by erylee** [comment]
./bin/emqttd console 

查看控制台错误？启动本来就不应该root，应该是hostname之类问题。
