### ISSUE TITLE
paho client connect with setWill got an java.io.EOFException

### ISSUE THREAD

**Issue by s1ckness** [emqtt/emqttd#381]
code works with ver0.10.3,but connect a 0.12 emqttd server we got a java.io.EOFException.
also tested php client，same result.

**Comment by erylee** [comment]
@s1ckness, could you past your php code?

**Comment by s1ckness** [comment]
thanks for reply,check your mailbox please

**Comment by erylee** [comment]
@s1ckness, I cannot reproduce this issue with the php code u sent to me.
