### ISSUE TITLE
Cannot connect to emqttd@000.000.000.000 on AWS EC2 Instances

### ISSUE THREAD

**Issue by com9009** [emqtt/emqttd#385]
I try to clustering with two AWS EC2 Instances.

I set each node name by emqttd@each host's ip

then start emqttd. emqttd works fine.

but when i run this command "./bin/emqttd_ctl cluster emqttd@another host ip"

I got message like this.
Cannot connect to emqttd@another host ip

Every setting thing is same without node name. Because I copied instance with same image.

Can i get any information concerned with this problem?

How to get clustering log?

Help please.

OS : Ubuntu 14.04
Erlang Version : OTP 17.5

**Comment by Prots** [comment]
Hello, please copy here settings of the security group of your AWS EC2 Instances.
I think you should enable incoming traffic via epmd port for cluster normal work.

**Comment by com9009** [comment]
<img width="1188" alt="kakaotalk_photo_2015-11-18-21-21-33_94" src="https://cloud.githubusercontent.com/assets/12993592/11240996/5eae3b76-8e3a-11e5-9fdd-0d2b3d1e09d3.png">

this.

**Comment by com9009** [comment]
And I also check $HOME/.erlang.cookie.
There are same.

**Comment by Prots** [comment]
Please try to open 4369 TCP port for incoming connections. This is default port for epmd daemon.

**Comment by com9009** [comment]
Thanks Prots

I opened it, but clustering is still not working.

**Comment by erylee** [comment]
hi, @com9009, did you configure the '-name emqttd@private ip' in etc/vm.args?

**Comment by com9009** [comment]
Sure

this is my vm.args.

##-------------------------------------------------------------------------
## Name of the node
##-------------------------------------------------------------------------
-name emqttd@private ip

## Cookie for distributed erlang
-setcookie emqttdsecretcookie

##-------------------------------------------------------------------------
## Flags
##-------------------------------------------------------------------------

## Heartbeat management; auto-restarts VM if it dies or becomes unresponsive
## (Disabled by default..use with caution!)
##-heart
-smp true

## Enable kernel poll and a few async threads
+K true

## 12 threads/core.
+A 48

## max process numbers
+P 8192

## Sets the maximum number of simultaneously existing ports for this system
+Q 8192

## max atom number
## +t

## Set the distribution buffer busy limit (dist_buf_busy_limit) in kilobytes.
## Valid range is 1-2097151. Default is 1024.
## +zdbbl 8192

##-------------------------------------------------------------------------
## Env
##-------------------------------------------------------------------------

## Increase number of concurrent ports/sockets, deprecated in R17
-env ERL_MAX_PORTS 8192

-env ERTS_MAX_PORTS 8192

-env ERL_MAX_ETS_TABLES 1024

## Tweak GC to run more often
-env ERL_FULLSWEEP_AFTER 1000

**Comment by com9009** [comment]
Hi, erylee

Sure

I configure node name , -name emqttd@private ip

and others is default

**Comment by com9009** [comment]
This is current result of command 'netstat -tlnp'

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1299/sshd       
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      1918/cupsd      
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      2120/beam.smp   
tcp        0      0 0.0.0.0:56926           0.0.0.0:*               LISTEN      2120/beam.smp   
tcp        0      0 0.0.0.0:18083           0.0.0.0:*               LISTEN      2120/beam.smp   
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      2089/epmd       
tcp        0      0 0.0.0.0:8083            0.0.0.0:*               LISTEN      2120/beam.smp   
tcp        0      0 0.0.0.0:8883            0.0.0.0:*               LISTEN      2120/beam.smp   
tcp6       0      0 :::22                   :::*                    LISTEN      1299/sshd       
tcp6       0      0 ::1:631                 :::*                    LISTEN      1918/cupsd

**Comment by 7wonders** [comment]
Well this has been frustrating the #%&# out of me and so I did some digging. Turns out that ec2/ubuntu does some weird stuff with some ports and to make the problem worse it does it on every reboot.

```
lsof -i :4369

COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
epmd     1141 ubuntu    3u  IPv4   9182      0t0  TCP *:epmd (LISTEN)
epmd     1141 ubuntu    4u  IPv4   9314      0t0  TCP localhost:epmd->localhost:60931 (ESTABLISHED)
beam.smp 1176 ubuntu   14u  IPv4   9313      0t0  TCP localhost:60931->localhost:epmd (ESTABLISHED)
```

So the trick is within your security group settings open to all traffic but only to instances within your security group of course. Make a new security group, use that security group for your instance, then set a rule:

Type: All traffic
Protocol: All
Port range: All
Source: Custom - start typing your security group id

After this clustering works straight away. I use instance ID and instance private IP as node name.

```
wget http://s3.amazonaws.com/ec2metadata/ec2-metadata
chmod u+x ec2-metadata
INSTANCE_ID=$(./ec2-metadata | grep instance-id | awk 'NR==1{print $2}')
INSTANCE_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --region eu-west-1 --query Reservations[].Instances[].PrivateIpAddress --output text | grep '^[0-9]')
OUR_NODE="$INSTANCE_ID"'@'"$INSTANCE_IP"
```

**Comment by emqplus** [comment]
Duplicated with #496.
