### ISSUE TITLE
why not emqttd_auth_ldap plugin file in new relase 0.13.1 version?

### ISSUE THREAD

**Issue by coco1960** [emqtt/emqttd#396]
why not emqttd_auth_ldap plugin file in new relase 0.13.1 version?
how to integrate LDAP in version 0.13.1?

**Comment by erylee** [comment]
emqttd_aut_ldap is a module, not a plugin. Please uncomment LDAP authentication config in etc/emqttd.config :

```
            %% Authentication with LDAP
            % {ldap, [
            %    {servers, ["localhost"]},
            %    {port, 389},
            %    {timeout, 30},
            %    {user_dn, "uid=$u,ou=People,dc=example,dc=com"},
            %    {ssl, fasle},
            %    {sslopts, [
            %        {"certfile", "ssl.crt"},
            %        {"keyfile", "ssl.key"}]}
            % ]},
```

**Comment by coco1960** [comment]
if the ldap need Authentication by username,password,how to write the config?

**Comment by coco1960** [comment]
if the ldap server need to Authentication by username and passowrd (like cn=Direcotry Manager ),how to config the parameter?
