### ISSUE TITLE
non-root user failed to start emqttd

### ISSUE THREAD

**Issue by smartbruce** [emqtt/emqttd#397]
root user start emqttd successfully, but no-root user start emqttd fail
![image](https://cloud.githubusercontent.com/assets/1074421/11606497/8e9705d0-9b5e-11e5-8d1e-5995d771d7d7.png)
![image](https://cloud.githubusercontent.com/assets/1074421/11606500/99cf2ae0-9b5e-11e5-80ea-ca4b74a55358.png)

**Comment by erylee** [comment]
```
rm ~/.erlang.cookie
```
