### ISSUE TITLE
emqttd service stops immediately after starts

### ISSUE THREAD

**Issue by Bazmundi** [emqtt/emqttd#398]
I get an erl_crash.dump immediately after starting emqttd as a service under windoze 10.  

Virgin install earlier today with no config changes, that is out of the box.

Slogan: Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{k

Any hints appreciated.

Cheers,
A

**Comment by Bazmundi** [comment]
Ah.  Dopey me.  I had a emqttd console up in a second window.  I closed that and then the problem disappears.

**Comment by erylee** [comment]
Hi @Bazmundi,  could only start one instance, otherwise the later one will crash for erlang node name collision.
