### ISSUE TITLE
0.13.0 没有打印调试日志

### ISSUE THREAD

**Issue by zyfmix** [emqtt/emqttd#407]
请问，我的 Ubuntu 14.04 下载 emqttd-ubuntu64-0.13.0-beta-20151108.zip 后，执行 ./bin/emqttd console 并没有客户端连接的状态信息呢？原来 0.8.2 版的有很多日志信息，换成 0.13.0 的之后，就没有日志信息
![qq 20151215173752](https://cloud.githubusercontent.com/assets/12183914/11807763/dfe3e43a-a356-11e5-9d17-fed2453ffcf0.jpg)

**Comment by lsxredrain** [comment]
rel/files/emqttd.config.production
lager_console_backend, info},  ---- check here

**Comment by zyfmix** [comment]
非常感谢，默认 ./etc/emqttd.conf 这行被注释掉了。
