### ISSUE TITLE
Observer application should be removed from reltool.config for 'wx' app is not available

### ISSUE THREAD

**Issue by erylee** [emqtt/emqttd#410]

**Comment by mikybone** [comment]
Hi
while emqttd running **emqttd start**, if want to enter **emqttd console** crash_dump generated:

> Slogan: Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}}

also when enter **erl** in .../emqttd-1.1.3/erts-7.3/bin

> {(no error logger present)" ienrirto rt: e<r0m.i2n.a0t>i
> ng in do_boot",{badarg,[{erl_prim_loader,check_file_result,3,[{file,"erl_prim_lo
> ader.erl"},{line,302}]},{init,get_boot,1,[{file,"init.erl"},{line,790}]},{init,g
> et_boot,2,[{file,"init.erl"},{line,777}]},{init,do_boot,3,[{file,"init.erl"},{li
> ne,744}]}]}}
> 
> Crash dump is being written to: erl_crash.dump...done
> init terminating in do_boot ()

How i can access **observer:start().** while emqttd running?

**Comment by mikybone** [comment]
Solved:
need to Copy wx-1.6.1 from .../erlang_installed_dir/lib to lib folder of emqttd.

**Comment by SumitFlochat** [comment]
Still not working .
Any help?
