### ISSUE TITLE
Subscription Group Support: Deliver message to only one client in the same group

### ISSUE THREAD

**Issue by smartbruce** [emqtt/emqttd#416]
出于安全和可维护性的考虑，应用被划分为两个集群A,B,其中A是用来处理内部的业务逻辑，B是专门用来处理外部的业务。由于两个集群都需要关注设备上线和离线的消息来进行相关业务处理，所以A和B都需要订阅设备上线和遗愿消息，但是A、B每个集群都有n台机器，只希望其中一台机器处理消息即可，如果多台机器都处理就会存在消息重复处理的情况。如果每个topic相关的订阅client可以进行分组管理，其中client属于哪个组，进行topic订阅的时候进行制定，示意图如下：
![image](https://cloud.githubusercontent.com/assets/1074421/12015909/95bbe29a-ad7e-11e5-877c-628486705b16.png)
其中c1、c2订阅时没有指定分组，则默认是两个单独的分组，c31、c32、c33指定了分组为c3，c41，c42，c43指定了分组为c4，当topic有消息到达的时候，按分组进行消息投递，每个分组选择一个client进行投递，所以c1、c2都会进行投递，c31、c32、c33属于c3分组随机选择一个进行投递，c41、c42、c43属于c4分组随机选择一个进行投递。希望后续能够添加对这种场景的支持。

**Comment by mpoornima** [comment]
Eagerly awaiting for this feature to be implemented. This is one of the major bottlenecks I've found with MQTT brokers so far. This would massively increases scale on the client side.

**Comment by Yongke** [comment]
Hi, this is the key feature for subscriber load balancing which we are waiting for in emqttd. Would it possible to have higher priority? ;-)

**Comment by emqplus** [comment]
@Yongke, we are working on this feature which will be released in 2.0

**Comment by emqplus** [comment]
The 'Shared Subscription' feature has been released in 2.0-beta.3. For example:

```
mosquitto_sub -t '$share/group/topic'
```

**Comment by smartbruce** [comment]
great job

**Comment by adarshlal** [comment]
Hi,

Its a wonderful feature..
Is there any document available for implementing this in emqttd cluster.
