### ISSUE TITLE
mongodb for authentication 

### ISSUE THREAD

**Issue by prakashr87** [emqtt/emqttd#417]
Hai,

     We using mongodb for our application. can we get mongodb plugin for authentication which same like mysql means it will helpful to us.

**Comment by abhidtu** [comment]
same here even we are using MongoDb for most of the stuff, we also need mongodb for auth
@prakashr87  : have a look at this project,
https://github.com/emqtt/emqttd_mongodb,

@erylee : is this work in progress or stable ?

**Comment by erylee** [comment]
@prakashr87 @abhidtu, I am working on this plugin and coding the connection pool now. The first release will be ready by this weekend if everything going on well:)

**Comment by abhidtu** [comment]
Thanks @erylee

**Comment by erylee** [comment]
@prakashr87 @abhidtu, please checkout https://github.com/emqtt/emqttd_mongodb plugin. The release has been test ready.

**Comment by prakashr87** [comment]
Thanks lot @erylee...

**Comment by erylee** [comment]
This issue will be closed for mongodb plugin has been released. If any issues, please submit to  https://github.com/emqtt/emqttd_mongodb.
