### ISSUE TITLE
Crypto and openssl error on centos 6.3

### ISSUE THREAD

**Issue by hzaupj** [emqtt/emqttd#422]
=ERROR REPORT==== 30-Dec-2015::14:41:56 ===
The on_load function for module crypto returned {error,
                                                 {load_failed,
                                                  "Failed to load NIF library: '/data/emqttd/lib/crypto-3.5/priv/lib/crypto.so: symbol EC_KEY_get0_group, version OPENSSL_1.0.1_EC not defined in file libcrypto.so.10 with link time reference'"}}

**Comment by erylee** [comment]
Please check the openssl version of your centos:

```
openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
```
