### ISSUE TITLE
Bridge emqttd broker to another emqttd broker & emqttd to mosquitto bridge

### ISSUE THREAD

**Issue by shrikantlahase** [emqtt/emqttd#438]
Please can anybody tell me configurations  (emqttd.conf) required for  creating bridge.

**Comment by erylee** [comment]
@shrikantlahase, please check wiki: https://github.com/emqtt/emqttd/wiki/Bridge

**Comment by shrikantlahase** [comment]
thanks feng

**Comment by erylee** [comment]
@shrikantlahase, I am not sure if mosquitto could bridge to emqttd. If any issues, please contact us:)

**Comment by shrikantlahase** [comment]
Hi feng,

1. Bridging mosquitto broker and emqttd broker was not successful. Can you
do any help...?
2. I am trying  to connect paho mqtt client which written in python to
emqttd broker but its not happening. How to connect as a client to emqttd
broker...?


Regards & Thanks,
Shrikant

**Comment by erylee** [comment]
Hi @shrikantlahase 

1. Please add my Skype: feng.emqtt.io to discuss the bridge issue.

2. We also use The paho client library written in python to test emqttd broker, so it should work well with emqttd.

**Comment by shrikantlahase** [comment]
Hi feng,

I am attaching my python client code. I tried command "./emqttd_ctl
clients  list"
 to see clients connected but output is blank.  Can u tell me anything
wrong in code...? or need to check on broker side

Thanks and regards,

**Comment by erylee** [comment]
please open the console log in etc/emqttd.config, and then ./bin/emqttd console to debug:

```
    {handlers, [
        {lager_console_backend, info},
       ...
```

**Comment by jianglinchun** [comment]
bridge from mosquitto to emqttd not successfully. I've test both mqtt broker by mosquitto_pub and both of them works fine.

mosquitto bridge configuration:
`connection emqttd                                                              
address xxx.xxx.xxx.xxx:1883                                                    
topic /test both                                                          
#bridge_protocol_version mqttv31                                              
start_type automatic                                                         
local_clientid C_00:0C:29:2B:77:52`

emqttd error log:
`18:11:20.601 <0.485.0> [error] Client(116.236.226.166:60775): Framing error - protocol_header_corrupt`

emqttd listeners:
`[root@iZ25r8abgnyZ emqttd]# ./bin/emqttd_ctl listeners
listener on http:8083
  acceptors       : 4
  max_clients     : 64
  current_clients : 1
  shutdown_count  : []
listener on mqtts:8883
  acceptors       : 4
  max_clients     : 512
  current_clients : 0
  shutdown_count  : []
listener on mqtt:1883
  acceptors       : 16
  max_clients     : 512
  current_clients : 0
  shutdown_count  : [{protocol_header_corrupt,31}]
listener on http:18083
  acceptors       : 4
  max_clients     : 512
  current_clients : 3
  shutdown_count  : []`

**Comment by erylee** [comment]
@shrikantlahase, @jianglinchun mosquitto bridge works now.

The mosquitto bridge uses a special 0x83 as protocol version in the CONNECT packet.

Please check out the '0.17' branch.

**Comment by jianglinchun** [comment]
Unexpected behavior. Pls check the following mosquitto log(unacceptable protocol version and works after retry???):

1455734681: Connecting bridge 000C292 (101.200.88.13:1883)
1455734681: Bridge OpenWrt.000C292 sending CONNECT
1455734681: Received CONNACK on connection wd_000C292B7752.
1455734681: Connection Refused: unacceptable protocol version
1455734681: Socket error on client wd_000C292B7752, disconnecting.
1455734712: Bridge wd_000C292B7752 doing local SUBSCRIBE on topic /test
1455734712: Connecting bridge 000C292 (101.200.88.13:1883)
1455734712: Bridge OpenWrt.000C292 sending CONNECT
1455734712: Received CONNACK on connection wd_000C292B7752.
1455734712: Bridge wd_000C292B7752 sending SUBSCRIBE (Mid: 2, Topic: /test, QoS: 0)

**Comment by erylee** [comment]
Please check the console log of emqttd broker, configure etc/emqttd.config:
```
{lager_console_backend, info},
```

**Comment by erylee** [comment]
@jianglinchun The broker will reply 'unacceptable protocol version' error code when mosquitto bridge CONNECT packet received. I fixed in the latest 0.17 branch, please pull and verify.

**Comment by jianglinchun** [comment]
Thank you for you fix. It works now.

**Comment by erylee** [comment]
hi @shrikantlahase, could we close the issue?

**Comment by shrikantlahase** [comment]
thanks for the fix.
I am yet to test your solution you provided to this issue. Time being you
can closed the issue. If some problem other issue occurs , i will inform
you.

thanks and Regards
Shrikant

**Comment by drasko** [comment]
I can not make it work:
```
drasko@Lenin:~/mainflux/mosquitto$ /usr/sbin/mosquitto -c mosquitto.conf -p 1111
1476137283: mosquitto version 1.4.8 (build date Sun, 14 Feb 2016 15:06:55 +0000) starting
1476137283: Config loaded from mosquitto.conf.
1476137283: Opening ipv4 listen socket on port 1111.
1476137283: Opening ipv6 listen socket on port 1111.
1476137283: Bridge local.Lenin.bridge-to-mainflux doing local SUBSCRIBE on topic #
1476137283: Connecting bridge bridge-to-mainflux (localhost:1883)
1476137283: Bridge Lenin.bridge-to-mainflux sending CONNECT
1476137283: Socket error on client local.Lenin.bridge-to-mainflux, disconnecting.
```

I am using latest debian `emqttd-debian64-v2.0-beta.3-20160918.zip` and I can not see anything in the debug console (set laget to debug, and wun in the foreground - no indeication tat mosquitto tries to connect)

**Comment by drasko** [comment]
Any news on this?
