### ISSUE TITLE
How to add users on version 0.15.0 ?

### ISSUE THREAD

**Issue by dianyong** [emqtt/emqttd#444]
Hello everyone,

I am using emqttd 0.15.0-beta-20160131 on CentOS 6.7 x86_64.
I need a username and password when I access the dashboard on port 18083, so I tried to find a default user or add a new user, here the problem came: the old document show that try "emqttd_ctl users add" to add a user, however, this version I use do not have a emqttd_ctl users command block.
Anyone can help me ? How to access the dashboard ?

**Comment by dianyong** [comment]
I found it in plugin.

https://github.com/emqtt/emqttd_dashboard/blob/2a1de2c79fe97a91b6c1e4da19af94273b874b21/etc/plugin.config

Thanks!

**Comment by erylee** [comment]
hi @dianyong, wiki: https://github.com/emqtt/emqttd/wiki/Authentication

**Comment by dianyong** [comment]
@erylee I got it, thank u~~
