### ISSUE TITLE
Input on using emqttd

### ISSUE THREAD

**Issue by 87sanchavan** [emqtt/emqttd#447]
Hi ,

We don't know erlang however  have worked on other languages. Do you think we can use emqttd even without knowing erlang. We are in just phase of choosing technology for push notifications for mobile phones. We checked other MQTT brokers( e.g Mosquitto , Mosca etc) however not sure if they are highly scalable to support millions of requests in future.

we are just going to start with small user base and once technology is working fine , we will use it for large users.

If any issue comes in emqttd broker in production, how important that one should know erlang very well to solve that problem.

Thanks
Sanjay

**Comment by VikramTiwari** [comment]
emqttd is written using Erlang, but the final output package is a binary that you can run on various platforms. Working with this binary is as easy as running nginx or apache server on your server. You don't need to know the semantics of the language unless you want to contribute to the development of the project.

There is enough documentation, configuration examples and supporting tools available for emqttd that normally you will never have to be worried about not understanding what's going on in the program. Moreover, if you have any issues, you can always get some help here.

To compare this with other brokers, others might be older and more stable, but emqttd is rapidly evolving for not just scale but also for security and its plugins base.

My suggestion: Always go for something that gives you peace of mind.

**Comment by 87sanchavan** [comment]
Thank you so much for inspiring me to use Erlang. I have started learning Erlang from past 2 days. Its really great programming language even though it is little difficult to understand in the beginning for people like me who worked on other languages like java , javascript etc.
