### ISSUE TITLE
Cluster support and feature

### ISSUE THREAD

**Issue by mingchuno** [emqtt/emqttd#454]
I am reading then doc and want to ask if the 2 feature below is supported or not? Let's say I have 2 nodes (node 1 and node 2) in the emqttd cluster. If producer A publish a message to <<"Topic">> though node1. Then will the consumer B connected to node 2 receive the message that A just publish?

> A message only gets forwarded to other cluster nodes if a cluster node is interested in it. this reduces the network traffic tremendously, because it prevents nodes from forwarding unnecessary messages.
> 
> As soon as a client on a node subscribes to a topic it becomes known within the cluster. If one of the clients somewhere in the cluster is publishing to this topic, the message will be delivered to its subscriber no matter to which cluster node it is connected.

Cluster Design · emqtt/emqttd Wiki
https://github.com/emqtt/emqttd/wiki/Cluster%20Design

**Comment by erylee** [comment]
@mingchuno, sorry for late reply. The new documents have been released on http://docs.emqtt.com/en/latest/cluster.html.

**Comment by mingchuno** [comment]
@erylee thank you very much. I think we can close the issue

**Comment by erylee** [comment]
@mingchuno Thanks. Please help me review the documents. For english isn't my mother tongue, there might be many problems in the documents. Please submit a PR if any issue you found:)

**Comment by mingchuno** [comment]
@erylee of coz
