### ISSUE TITLE
wrong document 

### ISSUE THREAD

**Issue by TangMonk** [emqtt/emqttd#455]
On this page: [https://github.com/emqtt/emqttd/wiki/Authentication](https://github.com/emqtt/emqttd/wiki/Authentication)

![image](https://cloud.githubusercontent.com/assets/3498786/13278921/1e39f626-db0f-11e5-96eb-40e40fe308df.png)

command not work:
```
./bin/emqttd_ctl users add <Username> <Password>
```

**Comment by erylee** [comment]
hi @TangMonk, please configure username authentication in etc/emqttd.config first:

```
{auth, [
     %% Authentication with username, password
     {username, []},
     ...
```

**Comment by TangMonk** [comment]
I got, I am sorry

**Comment by erylee** [comment]
@TangMonk, I will improve this CLI later, Please check issue #450
