### ISSUE TITLE
Windows support for emqttd_ctl command

### ISSUE THREAD

**Issue by syepes** [emqtt/emqttd#457]
It would be nice to have a Windows wrapper "emqttd_ctl.cmd" to be able to use the emqttd_ctl in a Windows environment, just like the emqttd.cmd

**Comment by huangdan** [comment]
The EMQ 2.0+ fully supports Windows platform. You can run `emqttd_ctl` command  on Windows.

**Comment by sh4nnongoh** [comment]
Hi I am unable to run "emqttd_ctl.cmd" on windows. 
Error as follows:

PS> C:\Users\Internet\Documents\emqttd2\bin\emqttd_ctl.cmd
escript: exception error: no function clause matching 
erlang:set_cookie(nonode@nohost,rpc) (erlang.erl, line 3283)
  in function  nodetool__escript__1503__305775__143000__2:process_args/3 (C:\Users\Internet\Documents\emqttd2\bin\nodetool, line 128)
  in call from nodetool__escript__1503__305775__143000__2:main/1 (C:\Users\Internet\Documents\emqttd2\bin\nodetool, line 14)
  in call from escript:run/2 (escript.erl, line 757)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 (init.erl, line 1076)
  in call from init:do_boot/3 (init.erl, line 784)

**Comment by hungthuanmk** [comment]
I laso face to the same issue
 escript: exception error: no function clause matching

**Comment by sjxu1982** [comment]
I laso face to the same issue when I do " ./bin/emqx_ctl plugins load emqx_auth_username "

**Comment by Gilbert-Wong** [comment]
Hi, @sjxu1982, which edition of emqx do you use? Could you please open the new issue for your problem on windows?
