### ISSUE TITLE
How about using radix tree (patrica trie) instead of trie?

### ISSUE THREAD

**Issue by rock59** [emqtt/emqttd#461]
I've used ZeroMQ in some projects and now migrating those projects to nanomsg because nanomsg improves those projects performance.
I dont know erlang and I dont know how subscription system of emqttd works. The only thing that I know is that a trie data structure is used.

This is only a suggestion to consider using radix tree..
Please read this blog post

http://250bpm.com/blog:19

**Comment by erylee** [comment]
hi @rock59, Thanks. I researched the radix tree of nanomsg months ago and tried to improve the design of emqttd broker. For we use mnesia database of erlang to store topic trie, the bottleneck will not be trie structure but the trie size. Finally I removed the topic names from the trie and only store the topic filters(wildcard):

```
--------------------------
|          t             |
|         / \            |
|        +   #           |
|      /  \              |
|    x      y            |
--------------------------
| t/+/x -> node1, node3  |
| t/+/y -> node1         |
| t/#   -> node2         |
| t/a   -> node3         |
--------------------------
```

**Comment by rock59** [comment]
As I said before, unfortunately I am absolute beginner at Erlang. I am evaluating emqtt about 3 months to eventually replace my startup web and mobile notification system(currently based on ejabberd) with emqtt.

You work hard and I am confident that emqtt will be a bright future.
Thanks for your efforts :-)

**Comment by emqplus** [comment]
@rock59, Thanks for your help:) I'd like to close the discussion now.
