### ISSUE TITLE
How to delete the retained message of a topic?

### ISSUE THREAD

**Issue by raymond852** [emqtt/emqttd#464]
Is there a means to delete the retained message of a topic?

**Comment by erylee** [comment]
A message with empty payload will delete the retained one of the topic. Please read MQTT V3.1.1 protocol specification.

**Comment by JoeFerrucci** [comment]
How do you send an empty payload using Swift and CocoaMQTT?

**Comment by JoeFerrucci** [comment]
I keep getting the same message every time I subscribe to a particular topic. I have tried sending an empty payload to the topic, but I still get the message.
