### ISSUE TITLE
emqtt drops all connections when having more than 3000 Publishers

### ISSUE THREAD

**Issue by Zordiac91** [emqtt/emqttd#466]
Is this intended?

I already increased  the max_clients and the size of the acceptors pool, but still no change. Is there anything else I can configure in order for it to support more clients? Happens with both QoS0 and QoS1.

Thanks in advance :)

**Comment by erylee** [comment]
Hi @Zordiac91:

1. Please check logs/emqttd_error.log

2. Configure etc/vm.args and tune '+P', '+Q' parameters

Docs: http://docs.emqtt.com/en/latest/config.html#etc-vm-args

**Comment by Zordiac91** [comment]
Thank you very much, that's exactly it!
