### ISSUE TITLE
Anonymous Authentication with Redis Plugin

### ISSUE THREAD

**Issue by 87sanchavan** [emqtt/emqttd#469]
Hi ,

I want to keep  Anonymous users as well as user/password authentication using Redis Plug in.
Without Redis plug in , any anonymous client is able to connect to emqttd server. However after loading redis plug in , it is only allowing clients having user and password stored in redis database.

below in authentication setting from emqttd.conf file and along with this , I have stored some user and password in redis database.
{emqttd, [
    %% Authentication and Authorization
    {access, [
        %% Authetication. Anonymous Default
        {auth, [
            %% Allow all
            {anonymous, []}
        ]},
]} 
]}

Can you please let me know what settings to be done to solve this issue. 

Thanks
Sanjay

**Comment by erylee** [comment]
Hi Sanjay, If we enable several authentication modules(plugins) at the same time, the authentication process:

```
           ----------------           ----------------           -------------
Client --> |   Username   | -ignore-> |   ClientID   | -ignore-> | Anonymous |
           ----------------           ----------------           -------------
                  |                         |                         |
                 \|/                       \|/                       \|/
            allow | deny              allow | deny              allow | deny
````

If you want authentication with both redis and anonymous, please customize the emqttd_plugin_redis/src/emqttd_auth_redis.erl. For example:

```
check(#mqtt_client{username = Anonymous}, Password, _State) ->
    ignore;
```

**Comment by mingchuno** [comment]
@87sanchavan yup, you need to customize the redis plugin yourself to support complicated Auth/Acl log. That's what I am doing.

**Comment by 87sanchavan** [comment]
Oky... Thanks
