### ISSUE TITLE
Dynamic Topic on Acl Control

### ISSUE THREAD

**Issue by nikolatesla11** [emqtt/emqttd#475]
Hello,

i am checking  Mysql Plugin for  authentication and acl control. Is there any way to define a dynamic topic for all users to publish or subscribe to their specific topic. For example;

Definining a rule with  username as "$all"  with a topic "/command/%u/+" with publish access would give publish access to clients on their separate topics .

username1 can publish on topic /command/username1/test
username2 can publish on topic /command/username2/test 

and username2 can't publish on  topic /command/username1/test

**Comment by erylee** [comment]
@nikolatesla11, the mysql plugin supports this pattern, for example:

```
INSERT INTO `mqtt_acl` (`id`, `allow`, `ipaddr`, `username`, `clientid`, `access`, `topic`)
VALUES
	(1, 0, NULL, '$all', NULL, 1, '#'),
	(2, 1, NULL, '$all', NULL, 3, '/command/$u/test');
```
**The variable name is '$u', not '%u'. **

**Comment by nikolatesla11** [comment]
thank you for quick response, it is exactly what i asked for.
