### ISSUE TITLE
emqttd_broker failed first start

### ISSUE THREAD

**Issue by Prots** [emqtt/emqttd#476]
It seems 0.17.0 tag has some issue, can't understand why emqttd_broker goes down, please check it:

`
2016-03-15 19:39:03 =CRASH REPORT====
  crasher:
    initial call: emqttd_broker:init/1
    pid: <0.260.0>
    registered_name: emqttd_broker
    exception error: bad argument: [{erlang,length,[3],[]},{gen_server,error_info,5,[{file,"gen_server.erl"},{line,821}]},{gen_server,terminate,7,[{file,"gen_server.erl"},{line,803}]},{proc_lib,wake_up,3,[{file,"
proc_lib.erl"},{line,247}]}]
    ancestors: [emqttd_sup,<0.136.0>]
    messages: []
    links: [<0.213.0>,<0.37.0>]
    dictionary: [{random_seed,{1459,2931,15705}}]
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 1324
  neighbours:
2016-03-15 19:39:03 =SUPERVISOR REPORT====
     Supervisor: {local,emqttd_sup}
     Context:    child_terminated
     Reason:     badarg
     Offender:   [{pid,<0.260.0>},{name,emqttd_broker},{mfargs,{emqttd_broker,start_link,[]}},{restart_type,permanent},{shutdown,10000},{child_type,worker}]
`

**Comment by erylee** [comment]
Hi @Prots, Do you build the broker from latest master? How to reproduce the issue?

**Comment by Prots** [comment]
No, I built from tag 0.17.0 and loaded my plugin.

**Comment by erylee** [comment]
Sorry for that I improved the the Hooks API design in 0.17.0 release in order to consolidate the 'foreach_hooks' and 'foldl_hooks'. 

I added a new emqttd_hook.erl module, and hook/unhook APIs to emqttd.erl module:
```
-spec(hook(atom(), function(), list(any())) -> ok | {error, any()}).
hook(Hook, Function, InitArgs) ->
    emqttd_hook:add(Hook, Function, InitArgs).

-spec(hook(atom(), function(), list(any()), integer()) -> ok | {error, any()}).
hook(Hook, Function, InitArgs, Priority) ->
    emqttd_hook:add(Hook, Function, InitArgs, Priority).

-spec(unhook(atom(), function()) -> ok | {error, any()}).
unhook(Hook, Function) ->
    emqttd_hook:delete(Hook, Function).

-spec(run_hooks(atom(), list(any()), any()) -> {ok | stop, any()}).
run_hooks(Hook, Args, Acc) ->
    emqttd_hook:run(Hook, Args, Acc).
```

The latest template plugin shows how to use the new Hooks API:

https://github.com/emqtt/emqttd_plugin_template/blob/master/src/emqttd_plugin_template.erl

**Comment by Prots** [comment]
Hi, I've checked code of my plugin, insert changes like in plugin_template example and now all right. Thanks for great job!
