### ISSUE TITLE
emqttd start failed but use emqttd console success

### ISSUE THREAD

**Issue by heidawei** [emqtt/emqttd#481]
I download emqttd and follow the Quick Start:
# Start console
./bin/emqttd console

# Start as daemon
./bin/emqttd start

# Check status
./bin/emqttd_ctl status

# Stop
./bin/emqttd stop_
    
I see start console OK, but start as daemon failed, the error info is "**emqttd failed to start within 15 seconds,
see the output of 'emqttd console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.**"

and I see the process beam.smp still alive after mqttd start failed. and the client can connect the server and publish or subscribe topic. 
I do't know why

**Comment by heidawei** [comment]
I know why. I must start the emqttd with root

**Comment by congleetea** [comment]
I also meet this problem,  It is strange,  when we run it in local machine, it can also run successfully not root.  @emqplus whether it must run with root?  I also use inner ip in vm.args.
