### ISSUE TITLE
is there any examples for redis  to do access control ?

### ISSUE THREAD

**Issue by Karity** [emqtt/emqttd#483]
hi: 
   I want to use redis plugin .but i can't find any examples for that can you give me some example

**Comment by erylee** [comment]
Hi @Karity, Redis Plugin: https://github.com/emqtt/emqttd_plugin_redis

**Comment by emqplus** [comment]
@Karity, I updated the README: https://github.com/emqtt/emqttd_plugin_redis/blob/master/README.md
