### ISSUE TITLE
Possible race condition using emqttd_cm

### ISSUE THREAD

**Issue by obi458** [emqtt/emqttd#486]
1) register using cast(async)
2) lookup is sync

So it is possible that the client is being registered(async) while for example
on_client_subscribe(ClientId, TopicTable, _Env), i need the mqtt_client record,
emqttd_cm:lookup(ClientId)(sync) gives undefined!

**Comment by erylee** [comment]
@obi458, Agree that there is a possible race condition issue. I will check the design later. But notice that you should not lookup the 'mqtt_client' record in on_client_subscribe for the function is called by session process. The session and client may be on different nodes in a cluster.

**Comment by obi458** [comment]
Ok, i have only "bridge cluster", but in an "erlang cluster" this could be a problem with the
sessions, i've only the clientid and can't get the mqtt_client record.

I think a "global" MQTT Client Manager should solve it!

**Comment by erylee** [comment]
Hi @obi458, please checkout the latest '0.17' branch and verify this issue. Thanks.

**Comment by obi458** [comment]
Works, the 120 seconds timeout is your experience or a pessimistic value?

**Comment by erylee** [comment]
The timeout is a tradeoff to ensure the broker could handle about 1k+ TCP connections per second.

@obi458, would you like to benchmark the fix? The tool: https://github.com/emqtt/emqtt_benchmark

```
./emqtt_bench_sub -h server -p 1883 -c 50000 -i 1 -t test/%i -q 1
```

**Comment by obi458** [comment]
[Dashboard_50000_171.pdf](https://github.com/emqtt/emqttd/files/199803/Dashboard_50000_171.pdf)

**Comment by erylee** [comment]
Hi @obi458, could we close the issue now?

**Comment by obi458** [comment]
Closed!
