### ISSUE TITLE
emqttd_plugin_mongo not found in emqttd

### ISSUE THREAD

**Issue by 87sanchavan** [emqtt/emqttd#489]
Hi , I have downloaded latest version of emqttd server -emqttd-ubuntu64-0.17.1-beta-20160322.zip.
I want to user mongodb plugin however it is not showing when I run command :
 
./bin/emqttd_ctl plugins list..
Even I went inside plugins directory. I didnt find emqttd_plugin_mongo.

Can you please advise me on how to enable mongo plug in with emqttd.

**Comment by erylee** [comment]
hi @87sanchavan, the mongodb plugin is not built by default for it depends on many third-party libraries. Please build the plugin by yourself.

**Comment by 87sanchavan** [comment]
Thank you erylee.

**Comment by erylee** [comment]
@87sanchavan, I created a 'plugins' branch from the latest master and added the mongodb plugin. could we close the issue now?

**Comment by 87sanchavan** [comment]
I will close the issue. However It would be really helpful for everyone if you can add mongodb plugin to emqttd installable ( like redi plugin)so we don't need to separately fetch mongodb plugin into emqttd.

**Comment by emqplus** [comment]
@87sanchavan, The mongodb plugin will be released in 1.1
