### ISSUE TITLE
File not found but existing

### ISSUE THREAD

**Issue by sleepingshorty** [emqtt/emqttd#491]
Hi. 

I try to follow the Quickstart-guide. 

Here a note: The zip-file is called "debian" or "ubuntu" without zip-extension when I download it with wget. In the tutorial for Ubuntu 64bit its called "emqttd-macosx-0.16.0-beta-20160216.zip". Do I have to use the mac-os Zip? ôO

I have downloaded the one for ubuntu, unzipped it and tried to start it. But what ever I try I get this message:

~/emqttd# ./bin/emqttd console
./bin/emqttd: 104: ./bin/emqttd: /root/emqttd/erts-7.1/bin/escript: not found
./bin/emqttd: 1: ./bin/emqttd: /root/emqttd/erts-7.1/bin/escript: not found
Error reading /root/emqttd/etc/emqttd.config

I tried it with different permissions and rights. Every time this error. The files exists.

Thank you in advance for your help.

Kind regards,
sleepingshorty

**Comment by sleepingshorty** [comment]
I am using 32bit version of ubuntu. Could that be the problem? I tried to compile the git-version but it failed too :-( 

Any idea?

**Comment by erylee** [comment]
Hi @sleepingshorty, the binary package downloaded from emqtt.io is 64bit:) 

Please build from source: http://docs.emqtt.com/en/latest/install.html#installing-from-source

**Comment by sleepingshorty** [comment]
Thank you so far... but I do need a further hint for this problem. I just cloned the repository, and tried to make it. This happens:

`/emqttd# make && make dist
Submodule 'plugins/emqttd_dashboard' () registered for path 'plugins/emqttd_dashboard'
Submodule 'plugins/emqttd_plugin_mysql' () registered for path 'plugins/emqttd_plugin_mysql'
Submodule 'plugins/emqttd_plugin_pgsql' () registered for path 'plugins/emqttd_plugin_pgsql'
Submodule 'plugins/emqttd_plugin_redis' () registered for path 'plugins/emqttd_plugin_redis'
Submodule 'plugins/emqttd_plugin_template' () registered for path 'plugins/emqttd_plugin_template'
Submodule 'plugins/emqttd_recon' () registered for path 'plugins/emqttd_recon'
Submodule 'plugins/emqttd_stomp' () registered for path 'plugins/emqttd_stomp'

=ERROR REPORT==== 5-Apr-2016::01:33:25 ===
beam/beam_load.c(1365): Error loading module rebar:
  use of opcode 153; this emulator supports only up to 152


=ERROR REPORT==== 5-Apr-2016::01:33:25 ===
Loading of /root/emqttd/rebar/rebar/ebin/rebar.beam failed: badfile
escript: exception error: undefined function rebar:main/1
  in function  escript:run/2
  in call from escript:start/1
  in call from init:start_it/1
  in call from init:start_em/1
make: *** [deps] Error 127
`

**Comment by erylee** [comment]
Erlang/OTP R17+ Required.

**Comment by sleepingshorty** [comment]
I used this `https://gist.github.com/bryanhunter/10380945` to compile it. Now it works.

Thank you very much!

**Comment by erylee** [comment]
@sleepingshorty, please close the issue. Thanks.
