### ISSUE TITLE
Is emqttd in production somewhere ? Is it production ready product ?

### ISSUE THREAD

**Issue by mkj-git** [emqtt/emqttd#492]
I can see that there are only one very active developer inside 'contributors'

**Comment by erylee** [comment]
Yeah, there are about 100+ deployments in production. We are a startup to provide open source MQTT broker, and more information will be available on our web site after 1.0 release.

**Comment by mkj-git** [comment]
When 1.0 is expected to release ?

**Comment by erylee** [comment]
Hi @mkj-git, we are working on the new web site these days. 1.0 release will come next week.
