### ISSUE TITLE
Upgrade Advice

### ISSUE THREAD

**Issue by AngeloBestetti** [emqtt/emqttd#493]
Would you mind to put down some steps to upgrade versions, such as what configuration files we need to keep and other pertinent info?

**Comment by erylee** [comment]
@AngeloBestetti, sorry for late reply, we will add a section for upgrade steps in release notes when 1.0 is ready.

**Comment by mr-bobfrog** [comment]
+1 By the way, does the 1.0.x_beta version count?

**Comment by zhengyupan** [comment]
Hi, 
Please refer to this document for version upgrade:
https://emqttd-docs.readthedocs.io/en/latest/upgrade.html
