### ISSUE TITLE
Cannot join cluster, node not running?

### ISSUE THREAD

**Issue by kenpeter** [emqtt/emqttd#496]
I have 2 nodes running. I tried to in node 2 joins node 1, but it says node 1 is not running. (but both are running)

Cannot join:
![cannot_join](https://cloud.githubusercontent.com/assets/927150/14268366/947394ae-fb1d-11e5-9b19-d4df98a546fb.png)

config node 1:
![config_node_1](https://cloud.githubusercontent.com/assets/927150/14268368/947d332e-fb1d-11e5-8f57-0f29540ba817.png)

config node 2:
![config_node_2](https://cloud.githubusercontent.com/assets/927150/14268367/947b0cac-fb1d-11e5-8614-a67e6be0c1fb.png)

node 1 port:
![node_1_port](https://cloud.githubusercontent.com/assets/927150/14268369/94860364-fb1d-11e5-8bce-eea1cb3836b5.png)

node 2 port:
![node_2_port](https://cloud.githubusercontent.com/assets/927150/14268371/948deb9c-fb1d-11e5-950d-8503429c8668.png)

aws ports:
![rule](https://cloud.githubusercontent.com/assets/927150/14268370/948b323a-fb1d-11e5-8ca4-6bd54ad496da.png)

**Comment by erylee** [comment]
The Firewall: http://docs.emqtt.com/en/latest/cluster.html#the-firewall

**Comment by kenpeter** [comment]
Same error.

config:
![config](https://cloud.githubusercontent.com/assets/927150/14270923/6430a304-fb36-11e5-9b85-4b9d069bbcfa.png)

node 2 port:
![node_2_port](https://cloud.githubusercontent.com/assets/927150/14270924/64344f68-fb36-11e5-9583-994cb5bc01e5.png)

node 1 port:
![node_port_1](https://cloud.githubusercontent.com/assets/927150/14270925/6439cf38-fb36-11e5-985d-b157f80c8e83.png)

port in aws:
![port](https://cloud.githubusercontent.com/assets/927150/14270926/643fb056-fb36-11e5-9dba-55872b885e65.png)

**Comment by 7wonders** [comment]
Try as a test to do as I suggest with vpc security groups - https://github.com/emqtt/emqttd/issues/385

**Comment by kenpeter** [comment]
@7wonders , not working.....

![all_traffic](https://cloud.githubusercontent.com/assets/927150/14563931/a3c3ecb8-0367-11e6-880e-d205c6e76f20.png)

![cannot_join](https://cloud.githubusercontent.com/assets/927150/14563956/ba1db534-0367-11e6-8226-27a9d5dfb02c.png)

![pang](https://cloud.githubusercontent.com/assets/927150/14563957/ba20d7d2-0367-11e6-8597-4c0beed96f0c.png)

![pang1](https://cloud.githubusercontent.com/assets/927150/14563958/ba24c806-0367-11e6-81a3-b7b1df85b41e.png)

**Comment by 7wonders** [comment]
Have you set the name in vm.args to the correct name? I use the node and private IP:

```-name i-1234abcdef@ec2.private.ip```

Have you set the erlang cookie on each instance to be the same?

```ubuntu@ip-10-0-0-34:~$ nano .erlang.cookie```

**Comment by kenpeter** [comment]
Ok, working now.

The trick are:
1. if you have ubuntu@ip.1-2-3-4, then you node name needs to be ubuntu@1.2.3.4. The 1.2.3.4 needs to be your private IP. ubuntu is the username of machine.

2. .erlang.cookie has the same cookie value in itself, also in vm.args

**Comment by navaid789** [comment]
> Ok, working now.
> 
> The trick are: 1 if you have ubuntu@ip.1-2-3-4, then your node name needs to be ubuntu@1.2.3.4. The 1.2.3.4 needs to be your private IP. ubuntu is the username of machine.
> 
> 2 .erlang.cookie has the same cookie value in itself, also in vm.args
> 
> 3 Do netstat -npl, to see what ports are using. Then open them in aws security group, need to open all ports.

You saved my day, it worked. Thanks
