### ISSUE TITLE
Cannot not publish qos2 message with HTTP Publish API

### ISSUE THREAD

**Issue by congleetea** [emqtt/emqttd#497]
Hi, I want to publish a topic with qos = 2 using webclient, but it disconnected when publishing it, and lager error 
`17:48:20.883 [error] WsClient(127.0.0.1): Frame error: {{badmatch,0},[{emqttd_parser,parse_frame,3,[{file,"src/emqttd_parser.erl"},{line,146}]},{emqttd_ws_client,ws_loop,3,[{file,"src/emqttd_ws_client.erl"},{line,103}]},{mochiweb_websocket,request,5,[{file,"src/mochiweb_websocket.erl"},{line,61}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,250}]}]}`
`                                                                                                                                                          17:48:20.884 [error] WsClient(127.0.0.1): Error data: [<<96,2,0,1>>]`
if there can not support publishing topics that qos=2  or there are other reasons? 
thanks.

**Comment by callbay** [comment]
Did you use that command as below to test?
curl -v --basic -u user:passwd -d "qos=2&retain=0&topic=/a/b/c&message=hello from http..." -k http://localhost:8083/mqtt/publish

**Comment by erylee** [comment]
@congleetea Which client library you used? The QoS of PUREL packet <<96,2,0,1>> is incorrect, which should be 1.

**Comment by congleetea** [comment]
Hi, @callbay  @erylee thanks your reply, I tested it use curl like below:
`curl -v --basic -u myusername:mypassword -d "qos=2&retain=0&topic=/a/b/c&message=hello from http..." -k http://localhost:8083/mqtt/publish`
it works well, so whether it is caused by my mqtt client library?  My client library was obtained from [this link](http://www.hivemq.com/demos/websocket-client/#data).   
however,in the other hand, when I use curl described above to publish a topic which qos=2, I lager the qos in emqttd_parser.erl, I find that its value is 0 not 2.
could you give me some information about them? 
thanks a lot.

**Comment by callbay** [comment]
I may give you some comments as below for your reference:
First, you might be using an improper lib. So I suggest you check it.
Second, you may trace up pubrec and pubcomp in emqttd_parser.erl only in the case of qos=2 by means of curl. so please mention how you did your trace it while qos=0.

**Comment by congleetea** [comment]
thanks a lot, I will check it as your suggestion.

**Comment by erylee** [comment]
@congleetea sorry for late reply, working on 1.0 release these days:)

1. The hivemq javascript library does not send a PUBREL with incorrect QoS, Please try https://github.com/mqttjs

2. The QoS of PUBLISH delivered to subscribers depends on the Subscription, for example:

```
mosquitto_sub -t '#' -q 2 -d

curl -v --basic -u myusername:mypassword -d "qos=2&retain=0&topic=/a/b/c&message=hello from http..." -k http://localhost:8083/mqtt/publish
```

You will receive:

```
Client mosqsub/8483-172-13-0-4 received PUBLISH (d0, q2, r0, m1, '/a/b/c', ... (18 bytes))
Client mosqsub/8483-172-13-0-4 sending PUBREC (Mid: 1)
Client mosqsub/8483-172-13-0-4 received PUBREL (Mid: 1)
hello from http...
Client mosqsub/8483-172-13-0-4 sending PUBCOMP (Mid: 1)
```

**Comment by erylee** [comment]
@congleetea, I closed this issue first. Thanks.

**Comment by congleetea** [comment]
@erylee ok, thanks a lot.
