### ISSUE TITLE
emqttd_plugin_mongo Error While Loading in emqttd

### ISSUE THREAD

**Issue by prakashr87** [emqtt/emqttd#505]
Hai,

we compiled **emqttd_plugin_mongo** completely, when we listing plugins with **emqttd_ctl plugins list** also showing mongo plugin. but while loading we got **load plugin error: {bson,{"no such file or directory","bson.app"}}** error.

Thank You.

**Comment by erylee** [comment]
Hi @prakashr87, I have no idea about what's happened:) I created a 'plugins' branch and built the mongodb plugin successfully. Please checkout the 'plugins' branch to verify this issue.

**Comment by callbay** [comment]
@prakashr87,My suggestion is that you have to check wether "bson-erlang" exists in the directory "emqtt/deps", as "emqttd_plugin_mongo" depends on "mongodb-erlang", and what is more, "mongodb-erlang" depends on "bson-erlang", so you have to clone the whole " https://github.com/comtihon/bson-erlang " onto the directory "deps" if "bson-erlang" is not found in "emqtt/deps", or you may check or change "rebar.config" in case of need.

**Comment by prakashr87** [comment]
Hi  **@erylee, @callbay,** Thanks for the support. :-). I loaded mongodb plugin successfully from the source . but i can't load plugin on "emqttd-ubuntu64-1.0-beta-20160413.zip" build. when i trying to load iam getting following error.
** load plugin error: {mongodb,
                    {bad_return,
                     {{mongo_app,start,[normal,[]]},
                      {'EXIT',
                       {undef,
                        [{mongo_app,start,[normal,[]],[]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,273}]}]}}}}}
  **
Thank You

**Comment by emqplus** [comment]
@prakashr87, The mongodb plugin has been upgraded in 1.1 release: https://github.com/emqtt/emqttd_plugin_mongo
