### ISSUE TITLE
CoAP support

### ISSUE THREAD

**Issue by hachreak** [emqtt/emqttd#510]
Hi, 
I have some question about the support of CoAP.
I cannot find documentation or code. Is it actually supported now?
I was looking about library that implement this protocol and the more advanced I found is [gen_coap](https://github.com/gotthardp/gen_coap).
Talking with the creator I discovered that, currently, `OTP` has a [poor support](https://github.com/gotthardp/gen_coap/issues/1) about DTLS and it's required to use a "secure" version of CoAP.

Thanks :)

**Comment by erylee** [comment]
Hi @hachreak, support of CoAP will be released in 1.2 as a plugin.

**Comment by hachreak** [comment]
Hi @erylee, did you plan to implement directly inside `emqttd` or to use an external lib?

**Comment by hachreak** [comment]
Hi @erylee, did you plan to implement directly inside `emqttd` or to use an external lib?

**Comment by erylee** [comment]
We will write the code from scratch and implement CoAP protocol inside emqttd.

**Comment by hachreak** [comment]
Exist a roadmap to consult somewhere? Just to know for when is planned the v1.2.
By the way, if you look for DTLS support, I think you can be interested on this [PR](https://github.com/erlang/otp/pull/936).

**Comment by drasko** [comment]
Any news on this one? Is v1.2 on the way?

**Comment by emqplus** [comment]
@drasko, cooking on CoAP, MQTT-SN and 2.0 release these days. Thanks for your patience:)

**Comment by drasko** [comment]
@emqplus great news! Thanks a lot for your impressive work!

I have started seriously evaluating EMQTT for our Mainflux (https://github.com/Mainflux/mainflux) project. I think it can replace several architectural blocks and simplify the structure.

One question about CoAP: how will you do CoAP-to-MQTT PUB/SUB? Actually what I had in mind is something like this: https://github.com/eclipse/ponte - so possibility to publish from MQTT to CoAP and vice versa. I.e. we need some protocol-to-protocol communication.

How will your solution work?
