### ISSUE TITLE
Connection Forcibly Closed

### ISSUE THREAD

**Issue by edfungus** [emqtt/emqttd#511]
When I attempt to connect as a client, I am able to but then get this message:

> 
[Errno 10054] An existing connection was forcibly closed by the remote host

and I get disconnected. I am using python as my client and seems to only break if I attempt to send something. Also used to work before but now doesn't

**Comment by erylee** [comment]
@edfungus, set the log level to info and check log/emqttd_error.log

**Comment by edfungus** [comment]
It said:

> [error] MQTT detected framing error invalid_mqtt_frame_len for connection 

So I went to the emqttd.config, increased the max_packet_size and now all is well. 

Thanks!
