### ISSUE TITLE
Another Race Condition

### ISSUE THREAD

**Issue by obi458** [emqtt/emqttd#512]
If you send an message(emqttd:publish(Msg) or emqttd_client:publish(Msg)) in hook 'client.subscribe.after' makes an race with
emqttd_server:pubsub_subscribe_ which calls emqttd_pubsub: async_subscribe(Topic, SubPid) and
this calls emqttd_trie:insert, trie is needed by publish to route!

Solution i guess: 
1) call emqttd_pubsub: subscribe(Topic, SubPid) which is sync instead of
emqttd_pubsub: async_subscribe(Topic, SubPid) or 
2) we hook a new one called subscribed in emqttd_router add_route!

Hints?

**Comment by erylee** [comment]
@obi458, it's not race condition. The SUBSCRIBE is asynchronous.

**Comment by obi458** [comment]
Ok, what i need is to send(from a plugin) a message to a client, the plugin! makes the subscription like
the  {"$Q/username/$u", 1} subscription, but there is no way to notify the subscription is done(sync)!

**Comment by erylee** [comment]
Use the 'client.subscribe.after' hook:

```
on_client_subscribe_after(ClientId, TopicTable, _Env) ->
    io:format("client ~s subscribed ~p~n", [ClientId, TopicTable]),
    self() ! {dispatch, Topic, Msg},
    {ok, TopicTable}.
```

Template code: 

https://github.com/emqtt/emqttd_plugin_template/blob/master/src/emqttd_plugin_template.erl

**Comment by obi458** [comment]
Ok, this solve how to send a message, if sessions the calling process.
Nice would be if there is a notify if the subscription is completed at the end of add_subscriber_.

**Comment by erylee** [comment]
@obi458 The design of async subscribe is a bit confusing, I think. Any suggestions?

**Comment by obi458** [comment]
I will think about it, now 2 weeks holiday :-)
