### ISSUE TITLE
SSL服务端的配置问题

### ISSUE THREAD

**Issue by lem12** [emqtt/emqttd#513]
我用openssl生成自签名的证书，在服务器中配置
 {ssl, [
	{certfile, "etc/ssl/server.crt"},
       {keyfile,  "etc/ssl/server.key"}]},

客户端使用m2mqtt进行发布和订阅
连接服务器时传了证书
程序报错说，（根据验证过程，远程证书无效）

**Comment by erylee** [comment]
Invalid issue. Closed.
