### ISSUE TITLE
Node hostname causes emqttd not to start

### ISSUE THREAD

**Issue by 51systems** [emqtt/emqttd#516]
In the cluster documentation it says that the `-name` parameter in `vm.args` supports both IP and hostnames:

> -name emqttd@host1
> 
> or
> 
> -name emqttd@192.168.0.10

However, if an IP address isn't used, it seems that emqtt thinks that it has failed to start.

>  emqttd failed to start within 30 seconds,
> emqttd_1 | see the output of 'emqttd console' for more information.

However it looks like it is actually running `ps -aux` shows processes:

```
root        52  0.0  0.0   7500    92 ?        S    19:13   0:00 /opt/emqttd/erts-7.1/bin/epmd -daemon
root       178  0.0  0.0  14868  1808 ?        S    19:13   0:00 /opt/emqttd/erts-7.1/bin/run_erl -daemon /tmp/emqttd/ /opt/emqttd/lo
root       181  1.3  1.7 1157296 51980 pts/0   Ssl+ 19:13   0:01 /opt/emqttd/erts-7.1/bin/beam.smp -K true -A 48 -P 8192 -Q 819
```

But all of the tools (`emqttd`, `emqttd_ctl`, `emqttd_top`) report that the node is not running.

May be somewhat related to #496 as I notice that the IP address had to be used for that setup as well.

**Comment by 51systems** [comment]
Turns out this is because erlang is expecting FQDNs. Putting a dot after the hostname if there is no domain specified makes it work.
eg: `emqttd@host1.`

**Comment by erylee** [comment]
@51systems I will update docs later.

**Comment by emqplus** [comment]
@51systems, Thanks. I have updated the docs about cluster setup in 2.0 release: http://emqtt.io/docs/v2/cluster.html#cluster-setup
