### ISSUE TITLE
Topic trace support with + or # ?

### ISSUE THREAD

**Issue by kunaldawn** [emqtt/emqttd#518]
Hey, great work and really happy for your release v1.

#### Is it possible to trace topic tree with + or # ?

For example,
If i have topic **foo/bar/one** and **foo/bar/two** can I trace both of them with **foo/bar/#** using **_/bin/emqttd_ctl "foo/bar/#" /home/footrace.log_** trace topic "?

I am using 0.15.0 broker.

**Comment by erylee** [comment]
@kunaldawn. The trace will not match topic filter.

**Comment by kunaldawn** [comment]
@erylee Thanks for the information. it will be really cool if you can support this feature. Looking forward to it.

**Comment by erylee** [comment]
Hi @kunaldawn, why not use mqtt client to trace '#', for example:
```
mosquitto_sub -t '#' -q 1 -d > mqtt.log
```

**Comment by kunaldawn** [comment]
Will try that, thank you for the idea
