### ISSUE TITLE
node not running when trying to install plugins

### ISSUE THREAD

**Issue by yon86** [emqtt/emqttd#521]
I always get node not not running when trying to install the plugins...I have started it as a service or console but when I check status its says node not running..I am able to connect to the service for other application which means the service is running but I can't get to install the plugins....I have tried it on Ubuntu and windows with the same result...can anybody help me what am I missing

**Comment by erylee** [comment]
Hi @yon86, this issue is usually caused by hostname. Did you change the '-name' in etc/vm.args?

**Comment by yon86** [comment]
@erylee  I didn't know that so do i need to change hostname to my pc name or ipaddress only

**Comment by yon86** [comment]
btw @erylee I tried it on centos 7 and it works

**Comment by yon86** [comment]
@emqplus  so I have a separate erlang installation for running rabbitmq on my pc is this the reason that I get the message node is not running
