### ISSUE TITLE
ACL-Files with mysql.

### ISSUE THREAD

**Issue by sleepingshorty** [emqtt/emqttd#522]
Hi. 

I'm sorry to say, that I do not understand how to configure ACLs. 

I've read https://github.com/emqtt/emqttd/wiki/ACL-Design for houres now and tried different things, but I can't get easiest thinks working.

I even don't see what possibilities I have. I found that there is $c for clientId and $u for userId. And in the mysql example is $all used. Are there more? 

I do not understand the example for the eq-tag and when I do have to use it. 

I understand 

> {deny, all, subscribe, ["$SYS/#", "#"]}.

as there are two rules. One for $SYS/# and one for #

But I do not understand 

> {deny, all, subscribe, [{eq, "$SYS/#"}, {eq, "#"}]}.
>  is it for $SYS/#/#?

I need the following:

All Clients can pubsub to public/#
All Clients can pubsub to $u/#
System, Dashboard can # 
All Clients can't pubsub #

This is my last config. But when I try to subscribe or publish my client disconnects.

100 1 NULL $all NULL 3 public/# 
101 1 NULL $all NULL 3    $u/#
400 1 127.0.0.1 NULL NULL 2 $SYS/# 
401 1 127.0.0.1 NULL NULL 2 # 
402 1 NULL dashboard NULL 1  $SYS/# 
500 0 NULL $all NULL 3   # 

Thank you for your help.
Torsten

**Comment by 51systems** [comment]
Have you enabled the mysql plugin via `emqttd_ctl plugins load emqttd_plugin_mysql`?
What does your `plugins/emqttd_plugin_mysql/etc/plugin.config` config file look like.

**Comment by sleepingshorty** [comment]
Hi. 
Thank you for your reply. 

The plugin is enabled and seems to be working with the rules from the wiki or no rules but not with mine.

My plugin.config (Password is replaced with *):

> [
>
>  {emqttd_plugin_mysql, [
>
>    {mysql_pool, [
>        %% ecpool options
>        {pool_size, 8},
>        {pool_type, round_robin},
>        {auto_reconnect, 3},
>
>        %% mysql options
>        {host,     "localhost"},
>        {port,     3306},
>        {user,     "emqtt"},
>        {password, "******************"},
>        {database, "emqtt"},
>        {encoding, utf8}
>    ]},
>
>    %% select password only
>    {authquery, "select password from mqtt_user where username = '%u' limit 1"},
>
>    %% hash algorithm: plain, md5, sha, sha256, pbkdf2?
>    {password_hash, sha256},
>
>    %% select password with salt
>    %% {authquery, "select password, salt from mqtt_user where username = '%u'"},
>
>    %% sha256 with salt prefix
>    %% {password_hash, {salt, sha256}},
>
>    %% sha256 with salt suffix
>    %% {password_hash, {sha256, salt}},
>
>    %% comment this query, the acl will be disabled
>    {aclquery, "select allow, ipaddr, username, clientid, access, topic from mqtt_acl where ipaddr = >'%a' or username = '%u' or username = '$all' or clientid = '%c'"},
>
>    %% If no rules matched, return...
>    {acl_nomatch, allow}
>
>  ]}
>].

**Comment by sleepingshorty** [comment]
I think i understood what # is. 

eq # means that you disallow to use # for the user while # means the topics itself.

Thats ok now. 

But there is something strange with acls:

If I use now rule, everything works fine.
If I create a dissalow rule, nothing works. Thats fine.
But when I try to allow only one topic and dissallow the other topics, all topics keep dissallowed.

It looks like this:
id, allow,ipaddr,username,clientid,access,topic
1 , 1 , null, $all, null, 3, public/#
1000, 0, null, $all, null, 3, #521 

Isn't it first match?

**Comment by 51systems** [comment]
I don't know how the rules engine handles rules where there are multiple matches. From the example mysql file, it looks like they setup the deny rules first. Eg:
```sql
INSERT INTO `mqtt_acl` (`id`, `allow`, `ipaddr`, `username`, `clientid`, `access`, `topic`)
VALUES
(1,0,NULL,'$all',NULL,1,'$SYS/#'),
(2,0,NULL,'$all',NULL,1,'eq #'),
(3,1,'127.0.0.1',NULL,NULL,2,'$SYS/#'),
(4,1,'127.0.0.1',NULL,NULL,2,'#'),
(5,1,NULL,'dashboard',NULL,1,'$SYS/#'),
```
so it may be that your less specific deny rule is overwriting your more-specific allow rule.

What we've done is disallow all topics by default by editing the mysql config:
```erlang
%% If no rules matched, return...
    {acl_nomatch, deny}
```

and then explicitly allowed certain topics in mysql.

**Comment by sleepingshorty** [comment]
This is working. 

I am not sure if it's the right way and I think I will edit the wiki.

Thank you very much for helping me out of this. 

:+1:

**Comment by sleepingshorty** [comment]
Basic ACLs are working. But I have a new problem where I do not understand where it comes from.

I want (working): 
$u/#             Everything allowed in user-path

and:
#/public/#     subscripe every possible path that is "public"

for example: if a user creates: username/public/temperaturGermany/garden everyone should be able to read it.

I have two rules:
ID, allow, ipaddr, username, clientid, access, topic
10 1 NULL $all NULL 3 $u/# 
20 1 NULL $all NULL 1 #/public/#

Thank you again.

**Comment by kenpeter** [comment]
@51systems, Are you able to give me a hint, https://github.com/emqtt/emqttd_plugin_mysql/issues/13
