### ISSUE TITLE
Base64 for emqttd_auth_mod hash encoding

### ISSUE THREAD

**Issue by lpfeup** [emqtt/emqttd#524]
Hi,

Currently emqttd_auth_mod is hashing passwords and then encoding them to an hex string.
It would be useful if one could use another encoding such as base64 (mainly for space efficiency).

Thanks.

**Comment by emqplus** [comment]
Hi @lpfeup, do you mean 'base64:encode(Password)' directly?

**Comment by lpfeup** [comment]
Hi. No, I meant using 'base64:encode(crypto:hash(sha256, Password))' instead of 'hexstring(crypto:hash(sha256, Password))'.

I would propose something as specified below (emqttd_auth_mod.erl):

```erlang
-type encoding_type() :: hex | base64.

-spec(passwd_hash(hash_type(), encoding_type(), binary()) -> binary()).

passwd_hash(plain,  Encoding, Password)  ->
    Password;
passwd_hash(md5,   Encoding, Password)  ->
    encode(Encoding, crypto:hash(md5, Password));
passwd_hash(sha,  Encoding,   Password)  ->
    encode(Encoding, crypto:hash(sha, Password));
passwd_hash(sha256, Encoding, Password)  ->
    encode(Encoding, crypto:hash(sha256, Password)).

encode(hex, X) -> hexstring(X);
encode(base64, X) -> base64:encode(X).
```

The encoding could be speficied in the plugin.config :
<code>
{password_hash_encoding, base64},
</code>

It could be optional and default to 'hex', which is the encoding currently being applied.
