### ISSUE TITLE
emqttd_ctl subscriptions is not working properly?

### ISSUE THREAD

**Issue by kunaldawn** [emqtt/emqttd#529]
#### Add or Remove subscriptions does not reflect unless broker is restarted?

```bash
$ ./rel/emqttd/bin/emqttd_ctl subscriptions list
lens_PKFPO9Anx1LvREkRgXCAGACZwZr -> foo/bar/one:1

$ ./rel/emqttd/bin/emqttd_ctl subscriptions add lens_PKFPO9Anx1LvREkRgXCAGACZwZr foo/bar/two 1
ok

$ ./rel/emqttd/bin/emqttd_ctl subscriptions list
lens_PKFPO9Anx1LvREkRgXCAGACZwZr -> foo/bar/one:1

$ ./rel/emqttd/bin/emqttd_ctl subscriptions del lens_PKFPO9Anx1LvREkRgXCAGACZwZr foo/bar/one
ok

$ ./rel/emqttd/bin/emqttd_ctl subscriptions list
lens_PKFPO9Anx1LvREkRgXCAGACZwZr -> foo/bar/one:1
```

##### After broker restart

```
$ ./rel/emqttd/bin/emqttd_ctl subscriptions list
lens_PKFPO9Anx1LvREkRgXCAGACZwZr -> foo/bar/two:1
```

#### What i am doing wrong here?

**Comment by emqplus** [comment]
@kunaldawn There are two types of subscription: static and dynamic.

1. The subscriptions you created manually by './bin/emqttd_ctl' are static and will be persisted.

2. The subscriptions created by the broker when a client subscribes to topics are dynamic and stored only in memory

3. './bin/emqttd_ctl subscriptions list' will list all the dynamic subscriptions(no static)

4. 'bin/emqttd_ctl subscriptions del' will delete the static subscription you created before

**Comment by kunaldawn** [comment]
Hi @Feng Lee 

Regarding "'bin/emqttd_ctl subscriptions del' will delete the static subscription you created before"

Got it. It will be cool if you add support for dynamic subscriptions removal, but it is not required for our job though.

Any how, can you look at #526 issue once (description given below).

Our protocol logic needs explicit control of subscriptions made by clients. Clients can move to different subscriptions and in many cases it does not have information regarding list of topics it is already subscribed to. So broker need to manage cleaning process. If we dont do cleaning process at broker side, then clients are getting messages from old topics.

### Can you please specify what core API we should use to remove dynamic subscriptions from emqtt plugin?

###### We have been blocked by this issue as we are not able to remove dynamic subscriptions from plugin.

**Comment by kunaldawn** [comment]
emqttd:unsubscribe(iolist_to_binary(ClientId), iolist_to_binary(OT), 1); seem to be working. TY
