### ISSUE TITLE
Can not build on Ubuntu16.04

### ISSUE THREAD

**Issue by dcy** [emqtt/emqttd#530]
==> rel (generate)
ERROR: Unable to generate spec: read file info /usr/lib/erlang/man/man1/x86_64-linux-gnu-gcov-tool.1.gz failed
ERROR: Unexpected error: rebar_abort
ERROR: generate failed while processing /home/dcy/app/emqttd/rel: rebar_abort
Makefile:36: recipe for target 'rel' failed
make: **\* [rel] Error 1

**Comment by emqplus** [comment]
@dcy, It seems rebar cannot read the man files: 

/usr/lib/erlang/man/man1/gcov-tool.1.gz
/usr/lib/erlang/man/man1/x86_64-linux-gnu-gcov-tool.1.gz

**Comment by tellypath** [comment]
@dcy I think this can be solved with a workaround by deleting a symlink and rerunning the `make` command `rm /usr/lib/erlang/man`. Don't know if this breaks something else down the line.

**Comment by paragasu** [comment]
This solve the issue i have on debian stretch.
