### ISSUE TITLE
Subscribe via http

### ISSUE THREAD

**Issue by xiongtec** [emqtt/emqttd#531]
My problem is I will eventually have thousand of devices connected to the broker and anytime a device publish a message it gets sent to a webapi microservice.   The solution I have is I opened a websocket client connection and subscribed to multilevel wildcard topic to get message from any device.  I am also using the websocket connection for webapi service to publish message to emqtt broker.  My concern is since I only have connection opened will there be a performance issue if all devices decided to publish message at same time through that one websocket connection.  Is there a better solution to this problem?

**Comment by emqplus** [comment]
@xiongtec, Yes. There will be performance issue in the long run. You can write a plugin and hook 'message.publish' to forward all messages arrived to your service:

https://github.com/emqtt/emqttd_plugin_template/blob/master/src/emqttd_plugin_template.erl

**Comment by xiongtec** [comment]
Thank you for your help.  I am very new to erlang.  How would the publish message be sent?  In the plugin would I create websocket connection pool or open send close via http.
