### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by primantok** [emqtt/emqttd#538]
Hello, I try to download emqtt for windows from http://emqtt.io/downloads/windows but it seems that download link not working.

Can you please fix this issue.

Thanks

**Comment by emqplus** [comment]
hi @primantok, where are you from? I can download the windows package by clicking the link directly now.

**Comment by primantok** [comment]
Hi @emqplus sorry for the late reply. I am from Indonesia, last night try to download using Google Chrome via Samsung Galaxy J5 (Android 5.1.1).

Will try again tonight when at home, thanks.

**Comment by emqplus** [comment]
okay, closed.
