### ISSUE TITLE
Feature request: HTTP Authentication

### ISSUE THREAD

**Issue by dreson4** [emqtt/emqttd#541]
Requesting to have an authentication feature where someone can authenticate via HTTP POST requests, emqttd would make a request to the given http routes e.g /superuser, /acl, /userauth and on response code 200 the server would allow the client, or deny the client upon receiving other status codes e.g. 403.
This way anyone can implement their own authentication mechanisms e.g use of webtokens e.t.c through any language they prefer as a server running either locally or even on a different machine.

**Comment by s4nch3z** [comment]
+1

**Comment by emqplus** [comment]
@dreson4, @s4nch3z. The HTTP authentication plugin has been released: https://github.com/emqtt/emqttd_auth_http.

**Comment by s4nch3z** [comment]
Big Thanks!

**Comment by teifip** [comment]
Thanks for the new plugin! I'm lost on one point. How do I control whether the authentication request is for a superuser or a normal user? I'm connecting with a Node.js MQTT client, and I see that the first authentication attempt is a super_req, followed by an auth_req in case the super_req fails.

**Comment by emqplus** [comment]
@teifip, The 'super_req' could be commented.
