### ISSUE TITLE
can not load sockjs plugin

### ISSUE THREAD

**Issue by Sovigod** [emqtt/emqttd#544]
Hello!
We want to use your product. Perfect for our purposes. But we can not load the plugin sockjs

mqtt01 emqttd # ./bin/emqttd_ctl plugins list
Plugin(emqttd_dashboard, version=1.0.2, description=emqttd web dashboard, active=true)
Plugin(emqttd_plugin_mysql, version=1.0.2, description=emqttd Authentication/ACL with MySQL, active=false)
Plugin(emqttd_plugin_pgsql, version=1.0.2, description=emqttd PostgreSQL Plugin, active=false)
Plugin(emqttd_plugin_redis, version=1.0.2, description=emqttd Redis Plugin, active=false)
Plugin(emqttd_plugin_template, version=1.0.2, description=emqttd plugin template, active=false)
Plugin(emqttd_recon, version=1.0, description=emqttd recon plugin, active=false)
Plugin(emqttd_reloader, version=1.0.2, description=emqttd reloader, active=false)
Plugin(emqttd_sockjs, version=1.1, description=SockJS(Stomp) Plugin for emqttd broker, active=false)
Plugin(emqttd_stomp, version=1.0.2, description=Stomp Protocol Plugin for emqttd broker, active=true)

mqtt01 emqttd # ./bin/emqttd_ctl plugins load emqttd_sockjs
load plugin error: {emqttd_sockjs,
                       {bad_return,
                           {{emqttd_sockjs_app,start,[normal,[]]},
                            {'EXIT',
                                {{badmatch,undefined},
                                 [{emqttd_sockjs,load,1,
                                      [{file,"src/emqttd_sockjs.erl"},
                                       {line,62}]},
                                  {emqttd_sockjs_app,with_sup,1,
                                      [{file,"src/emqttd_sockjs_app.erl"},
                                       {line,42}]},
                                  {application_master,start_it_old,4,
                                      [{file,"application_master.erl"},
                                       {line,273}]}]}}}}}

In logs we have:
==> emqttd_crash.log <==
2016-05-05 15:14:12 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.17371.3>
    registered_name: []
    exception exit: {{bad_return,{{emqttd_sockjs_app,start,[normal,[]]},{'EXIT',{{badmatch,undefined},[{emqttd_sockjs,load,1,[{file,"src/emqttd_sockjs.erl"},{line,62}]},{emqttd_sockjs_app,with_sup,1,[{file,"src/emqttd_sockjs_app.erl"},{line,42}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,134}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [<0.17370.3>]
    messages: [{'EXIT',<0.17372.3>,normal}]
    links: [<0.17370.3>,<0.7.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 122
  neighbours:

**Comment by emqplus** [comment]
Hi @Sovigod, please update sockjs plugin:
```
git submodule update --remote
```

**Comment by Sovigod** [comment]
Thanks! Now it loads))
