### ISSUE TITLE
Multi-tenancy support

### ISSUE THREAD

**Issue by joaohf** [emqtt/emqttd#545]
Hi,

I'm just curious. Has emqttd support to multi-tenancy (https://en.wikipedia.org/wiki/Multitenancy) ?

For example: "isolation of topics and storage, just use username@tenant as username"

Is it feasible?

Thanks

**Comment by emqplus** [comment]
Hi @joaohf, the emqtt broker cannot support multi-tenancy.

BTW, thanks for your rebar3 PR:)

**Comment by joaohf** [comment]
Thanks.
