### ISSUE TITLE
Cowboy handler sockjs_cowboy_handler terminated

### ISSUE THREAD

**Issue by Sovigod** [emqtt/emqttd#553]
we use emqttd + emqttd_sockjs. After one day of use, the connection with sockjs over websocket does not work.

Errors in log 

emqttd_error.log:

10:21:02.106 <0.25373.157> [error] Cowboy handler sockjs_cowboy_handler terminated in sockjs_cowboy_handler:websocket_init/3 with reason: bad argument in call to ets:lookup(sockjs_table, undefined) in sockjs_session:maybe_create/3 line 48
10:21:02.168 <0.7125.158> [error] Cowboy handler sockjs_cowboy_handler terminated in sockjs_cowboy_handler:handle/2 with reason: bad argument in call to ets:lookup(sockjs_table, "ezzcputa") in sockjs_session:maybe_create/3 line 48

emqttd_crash.log:

2016-05-10 10:21:01 =ERROR REPORT====
** Cowboy handler sockjs_cowboy_handler terminating in handle/2
   for the reason error:badarg
** Handler state was {service,"/stomp",#Fun<emqttd_sockjs.0.83525389>,{stomp_state,undefined,[{frame,[{max_headers,10},{max_header_length,1024},{max_body_length,8192}]}]},"https://d1fxtkz8shb9d2.cloudfront.net/sockjs-0.3.min.js",false,true,5000,25000,131072,#Fun<sockjs_handler.0.67321156>}
** Request was [{socket,#Port<0.1588468>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.6771.158>},{method,<<"POST">>},{version,{1,1}},{peer,{{10,3,9,1},34322}},{host,<<"stompbz">>},{host_info,undefined},{port,80},{path,<<"/stomp/892/q2g7kniv/xhr_send">>},{path_info,[<<"892">>,<<"q2g7kniv">>,<<"xhr_send">>]},{qs,<<>>},{qs_vals,undefined},{fragment,<<>>},{bindings,[]},{headers,[{<<"connection">>,<<"upgrade">>},{<<"host">>,<<"stompbz">>},{<<"content-length">>,<<"88">>},{<<"user-agent">>,<<"Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0">>},{<<"pragma">>,<<"CacheHandler=8B616B7E9004F5C2934A7305242A71AFAEEC0283">>},{<<"accept">>,<<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>},{<<"accept-language">>,<<"fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"referer">>,<<"https://www.domain.com/community/post/education/1711783">>},{<<"content-type">>,<<"text/plain; charset=UTF-8">>},{<<"origin">>,<<"https://www.domain.com">>},{<<"cookie">>,<<"_ym_uid=1462864787892608504; _ym_isad=1; _ga=GA1.2.4151611.1462864787; _gat=1; _gat_gaAdv=1; _ym_visorc_37578=b; kvcd=1462864789526; km_ai=nzjhSY%2BVQ%2FCdtMva9ZKQn6jud00%3D; km_uq=; km_vs=1; km_lv=1462864790; JSESSIONID=dummy">>},{<<"pragma">>,<<"no-cache">>},{<<"cache-control">>,<<"no-cache">>}]},{p_headers,[{<<"connection">>,[<<"upgrade">>]}]},{cookies,undefined},{meta,[]},{body_state,waiting},{multipart,undefined},{buffer,<<"[\"SEND\\ndestination:mqtt_online_topic:bbazar\\ncontent-length:13\\n\\nGGG1462864861\\u0000\"]">>},{resp_compress,false},{resp_state,waiting},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]
** Stacktrace: [{ets,lookup,[sockjs_table,"q2g7kniv"],[]},{sockjs_session,spid,1,[{file,"src/sockjs_session.erl"},{line,103}]},{sockjs_session,received,2,[{file,"src/sockjs_session.erl"},{line,64}]},{sockjs_action,handle_recv,3,[{file,"src/sockjs_action.erl"},{line,171}]},{sockjs_action,xhr_send,4,[{file,"src/sockjs_action.erl"},{line,145}]},{sockjs_handler,handle,3,[{file,"src/sockjs_handler.erl"},{line,194}]},{sockjs_cowboy_handler,handle,2,[{file,"src/sockjs_cowboy_handler.erl"},{line,25}]},{cowboy_handler,handler_handle,4,[{file,"src/cowboy_handler.erl"},{line,119}]}]

2016-05-10 10:21:02 =ERROR REPORT====
** Cowboy handler sockjs_cowboy_handler terminating in websocket_init/3
   for the reason error:badarg
** Options were {service,"/stomp",#Fun<emqttd_sockjs.0.83525389>,{stomp_state,undefined,[{frame,[{max_headers,10},{max_header_length,1024},{max_body_length,8192}]}]},"https://d1fxtkz8shb9d2.cloudfront.net/sockjs-0.3.min.js",false,true,5000,25000,131072,#Fun<sockjs_handler.0.67321156>}
** Request was [{socket,#Port<0.1588471>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.25373.157>},{method,<<"GET">>},{version,{1,1}},{peer,{{10,3,9,1},34372}},{host,<<"stompbz">>},{host_info,undefined},{port,80},{path,<<"/stomp/641/8_rf4s5d/websocket">>},{path_info,[<<"641">>,<<"8_rf4s5d">>,<<"websocket">>]},{qs,<<>>},{qs_vals,undefined},{fragment,<<>>},{bindings,[]},{headers,[{<<"upgrade">>,<<"websocket">>},{<<"connection">>,<<"upgrade">>},{<<"host">>,<<"stompbz">>},{<<"origin">>,<<"https://www.domain.com">>},{<<"pragma">>,<<"no-cache">>},{<<"cache-control">>,<<"no-cache">>},{<<"sec-websocket-key">>,<<"A9NqAyPIdP2PD22+US3nQw==">>},{<<"sec-websocket-version">>,<<"13">>},{<<"sec-websocket-extensions">>,<<"permessage-deflate; client_max_window_bits, x-webkit-deflate-frame">>},{<<"user-agent">>,<<"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36">>},{<<"cookie">>,<<"km_ai=gGDtsLIzGJamHEe9e% _ym_visorc_37578=w">>}]},{p_headers,[{<<"upgrade">>,[<<"websocket">>]},{<<"connection">>,[<<"upgrade">>]}]},{cookies,undefined},{meta,[{websocket_version,13}]},{body_state,waiting},{multipart,undefined},{buffer,<<>>},{resp_compress,false},{resp_state,waiting},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]
** Stacktrace: [{ets,lookup,[sockjs_table,undefined],[]},{sockjs_session,maybe_create,3,[{file,"src/sockjs_session.erl"},{line,48}]},{sockjs_cowboy_handler,websocket_init,3,[{file,"src/sockjs_cowboy_handler.erl"},{line,39}]},{cowboy_websocket,handler_init,2,[{file,"src/cowboy_websocket.erl"},{line,100}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,514}]}]

**Comment by Sovigod** [comment]
I restart server. After 7 hour normal work i have error in log

**Comment by emqplus** [comment]
Hi @Sovigod, this issue has been moved to https://github.com/emqtt/emqttd_sockjs/issues/2
