### ISSUE TITLE
ACL Restricting users and topics

### ISSUE THREAD

**Issue by xiongtec** [emqtt/emqttd#554]
I am using mysql acl plugin for rules.  I need to make a rule for a client to only be allow to publish and a specific topic.  For example, client A is only allow to publish to topic **home/pub/test/a** and is only allow to subscribe to **home/sub/test/a**.  Also restrict topic creation to specific user.

**Comment by xiongtec** [comment]
I found the solution I was asking.

**Comment by kenpeter** [comment]
Hi,

Are you able to post more detail on how you resolved it. I am able to authenticate user with mysql, but failed at ACL. Here is my issue, https://github.com/emqtt/emqttd_plugin_mysql/issues/13

**Comment by xiongtec** [comment]
I just used the MySQL plugins and created rules in database.  That was my solution, didn't have to implement any new plugin.

**Comment by emqplus** [comment]
Hi @xiongtec: 

```
INSERT INTO `mqtt_acl` ( `allow`, `ipaddr`, `username`, `clientid`, `access`, `topic`)
VALUES (1,NULL,'$all',NULL,1,'home/sub/test/%c');
```
