### ISSUE TITLE
can not trigger disconnected hook when client disconnected unexpected

### ISSUE THREAD

**Issue by congleetea** [emqtt/emqttd#555]
Hi,  I want to do some work if the client disconnected from broker, but sometimes, the client is disconnected by some unexpected cause,  I find that the disconnected hook can not work in this case.  

can you give me some advice for executing the disconnected hook in spite of unexpected disconnection. 
thanks a lots.

**Comment by emqplus** [comment]
@congleetea, Invalid issue, closed.
