### ISSUE TITLE
./emqttd_top msg_q result: {"init terminating in do_boot",{undef,[{etop,start,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

### ISSUE THREAD

**Issue by njnuwjq** [emqtt/emqttd#557]
hi, I'm new to emqtt

after installed emqtt, i tried the command, but seems there's a problem

=================
[root@ejabber01_dev bin]# ./emqttd_top msg_q
{"init terminating in do_boot",{undef,[{etop,start,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()
=================
but i can run it in the shell

[root@ejabber01_dev bin]# erl
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> 
1> 
1> etop:start().

========================================================================================
 nonode@nohost                                                             06:12:48
 Load:  cpu         0               Memory:  total       12273    binary         21

==================

thanks
& nice to meet you

**Comment by emqplus** [comment]
@njnuwjq, The issue has been fixed in issue#557 branch.
