### ISSUE TITLE
An ideal solution for pushing notification to 1000's user

### ISSUE THREAD

**Issue by mkj-git** [emqtt/emqttd#559]
I have a situation. There is post and 1000's user has put comments on this post. Now if any new comment come I want to notify all 1000's user. SO what will the best solution. What i am considering:
1. Everytime a user do any activity it will subscribe to a new topic. The problem that i think it might have is, 1 user can subscribe to 1000's topic (i.e for each new activity e.g for new post, comment etc)
2. Keep a specific topic for each user let say like user1/notification, user2/notification,...user1000/notification. So whenever a new activity comes get all user id and push to this specific topic.

Which one is good or is there any other good way?

**Comment by kunaldawn** [comment]
@mkj-git You can create a new channel per group and let each client in that group subscribe to that channel. QOS : 1

**Comment by mkj-git** [comment]
can you please explain in details?
