### ISSUE TITLE
About adding meta information into published message

### ISSUE THREAD

**Issue by anhldbk** [emqtt/emqttd#563]
Is there any way to make published messages containing information from the sender?

For example, if a client A is authenticated to connect to `emqttd`. A may send B a message of: 
```js
{
     message: "holla"
}
```
Before delivering it to B, the message may be intercepted by us, adding some stuff:
```js
{
    sender: 'A',
    message: 'holla'
}
```

@emqplus is this feature feasible with [hooks](http://docs.emqtt.com/en/latest/design.html#hooks-design)? Would you pls tell me how to achieve it?

**Comment by emqplus** [comment]
@anhldbk Hook 'message.publish': 
https://github.com/emqtt/emqttd_plugin_template/blob/master/src/emqttd_plugin_template.erl

```
on_message_publish( Message = #mqtt_message{from = ClientId}, _Env) ->
    case emqttd_cm:lookup(ClientId) of
       undefined -> 
           {ok, Message};
        Client ->
            {ok, enrich(Client, Message)}
    end.
```

**Comment by anhldbk** [comment]
@emqplus Is the code above ready to use? (I'm sorry, I just dont know anything about Erlang).

**Comment by anhldbk** [comment]
@emqplus Would you pls tell me what wrong with this code?

```erlang
    case emqttd_cm:lookup(ClientId) of
       undefined -> 
           {ok, Message};
        Client ->
            % I want to modify messages by altering its payload
            % But it doesn't work
            Msg = Message#mqtt_message{payload="data is where?"},
            {ok, Msg}
    end.
```

**Comment by emqplus** [comment]
@anhldbk, It's demo code that you should not use directly.

**Comment by anhldbk** [comment]
@emqplus Oh, what's about my code above? Is that a good way of modifying a being-published packet?

**Comment by emqplus** [comment]
It's okay. Notice that the payload is a binary: <<"new data">>.

 Please close this issue later.

**Comment by anhldbk** [comment]
@emqplus Thank you! I really appreciate.

**Comment by anhldbk** [comment]
@emqplus I've implemented a plugin named `emqttd_plugin_header`. Do you think it's necessary to add the plugin into `eMQTT` repo?
