### ISSUE TITLE
More password hash type?

### ISSUE THREAD

**Issue by kenpeter** [emqtt/emqttd#567]
I have a look at this: https://github.com/emqtt/emqttd/blob/master/src/emqttd_auth_mod.erl

It current supports hash_type :: plain | md5 | sha | sha256.

Is it possible to use bcrypt?

passwd_hash(bcrypt, Password)  ->
    hexstring(crypto:hash(bcrypt, Password)).

Laravel 5 has bcrypt built-in. If not possible, I will try to use sha256.

**Comment by emqplus** [comment]
Added 'pbkdf2' hash in 2.1 release.
