### ISSUE TITLE
Location of Images/Messages sent by users on the server

### ISSUE THREAD

**Issue by 87sanchavan** [emqtt/emqttd#569]
Hi ,

We are using Emqttd broker to send images/videos apart from text. So would like to know where these images/text/videos are stored on the server when recipient is offline. We just want to make sure there is enough space in the directory where these data is stored to be sent to subscribed clients when they are connected.

Thanks
Sanjay

**Comment by emqplus** [comment]
@87sanchavan, You should not send Images/Videos to the broker directly.
