### ISSUE TITLE
About multi level wilcards

### ISSUE THREAD

**Issue by anhldbk** [emqtt/emqttd#570]
I've got the following NodeJS code to subscribe to any subtopic of `system` (using broker `emqtt`), displaying messages received

```js
var mqtt    = require('mqtt');
var client  = mqtt.connect(
    {
        host: 'localhost',
        port: 1883,
    }
);

client.on('connect', function () {
    client.subscribe('system/#');
    client.publish('system/log', 'A log'); 
});

client.on('message', function (topic, message) {
    console.log('topic: ' + topic) 
    console.log('message: ' + message)
});
```

**PROBLEM**
- A message is published to `system/log`, I expect to have the message's information printed out. But it's NOT. 
- If I modify `client.subscribe('system/#');` to become `client.subscribe('system/log');`, the code works well.

@emqplus Would you pls tell me what wrong is?

**Comment by anhldbk** [comment]
@emqplus Please have a look at the image below
![screenshot from 2016-05-28 21-14-47](https://cloud.githubusercontent.com/assets/3270746/15627792/a73c350c-2519-11e6-8949-639e7833be2d.png)

**Comment by anhldbk** [comment]
Well, I think there's trouble with handling messages with `qos` = 0 or 1.

If I publish messages with `qos = 2`, it always works as expected

![screenshot from 2016-05-28 21-49-09](https://cloud.githubusercontent.com/assets/3270746/15627942/297b213c-251e-11e6-80bc-6ca102a926c4.png)

**Comment by emqplus** [comment]
Hi @huangdan, please check the issue.

**Comment by huangdan** [comment]
@anhldbk  the  V1.1.1 repair it. please verify it;

**Comment by anhldbk** [comment]
@huangdan Yep, the patch works.
