### ISSUE TITLE
Use of variables in internal ACL rules

### ISSUE THREAD

**Issue by teifip** [emqtt/emqttd#578]
Would it be possible to support the use of `%c` in the ACL rules used by the internal ACL module without sacrificing efficiency?
I'm implementing a scheme like the one found on Amazon IoT where each device subscribes to a bunch of device-specific topics – such as `/devices/{clientId}/#` – and publish to a subset thereof. Of course it is not desirable to put all these _algorithmic_ rules in a database.
I've tried the new `emqttd_auth_http plugin`, and that works just fine. However,  variables in the internal ACL rules would be my first choice if supported.

**Comment by emqplus** [comment]
@teifip, Yeah, the ACL supports '%c', '%u' variables. For example, the 'etc/acl.config' used by the internal ACL module:

```
{allow, all, subscribe, ["/devices/%c/#"]}.
{allow, all, subscribe, ["/devices/%u/#"]}.
{deny, all}.
```

**Comment by teifip** [comment]
@emqplus, wonderful! Thanks a lot for following up!
