### ISSUE TITLE
emqttd_broker: BROKER_TAB is used?

### ISSUE THREAD

**Issue by hachreak** [emqtt/emqttd#581]
Hi,
I was looking in the code to find how `ets` and `mnesia` are used and I found this: https://github.com/emqtt/emqttd/blob/master/src/emqttd_broker.erl#L121
Are this `ets` table `BROKER_TAB` used? 
Because I can't find any place. Maybe I need to look better.
In any case, thanks.

L.

**Comment by emqplus** [comment]
Hi @hachreak, you are right. The BROKER_TAB table has been used to store hooks before, which moved to HOOK_TAB later.
