### ISSUE TITLE
HTTP Publish API authentication does not work with emqttd_auth_http plugin

### ISSUE THREAD

**Issue by teifip** [emqtt/emqttd#582]
I'm successfully using the new `emqttd_auth_http` plugin for user authentication and subscribe/publish access control. However, with the plugin loaded, the HTTP Basic Authentication for the **HTTP Publish API** does not seem to work. Specifically, all the POST requests get rejected with 401 without any attempt to validate the HTTP user:password combination through the `emqttd_auth_http` plugin.
Is this a design choice? If so, how can I use the **HTTP Publish API** while the `emqttd_auth_http` plugin is loaded?

**Comment by emqplus** [comment]
@teifip, If the emqttd_auth_http plugin is loaded, the HTTP Publish API will be authenticated by the plugin.

**Comment by teifip** [comment]
@emqplus, great! Thank you!
