### ISSUE TITLE
EMQTT MYSQL Plugin: Error after a little while

### ISSUE THREAD

**Issue by takeuz** [emqtt/emqttd#586]
Hello
After about two days of starting and operating the EMQTT server with mysql plugin for acl, the system fails to login people. Gives  the following error on emqtt_error and erlang.log. Nothing on crash log
<START ERROR>
login failed for {{{case_clause,{error,closed}},[{mysql_protocol,fetch_response,5,[{file,"src/mysql_protocol.erl"},{line,307}]},{mysql,handle_call,3,[{file,"src/mysql.erl"},{line,556}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{gen_server,call,[<0.24153.0>,{query,"select uc_password as password from USER_TABLE  where UT_PHONE = '1234567890' limit 1"},infinity]}}
<END ERROR>

When I restart the server all seems fine.  I have been able to repeat it multiple times

One thing I have NOT checked yet is whether mysql is receiving this SQL request.

**Comment by emqplus** [comment]
@takeuz, a quick fix: https://github.com/emqtt/emqttd_plugin_mysql/issues/15

A long story: https://github.com/mysql-otp/mysql-otp/pull/42
