### ISSUE TITLE
load mysql plugin error

### ISSUE THREAD

**Issue by xurwxj** [emqtt/emqttd#587]
```
16:58:47.001 <0.1648.0> [error] load plugin emqttd_plugin_mysql error, cannot start app emqttd_plugin_mysql for {bad_return,{{emqttd_plugin_mysql_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emqttd_plugin_mysql,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,4},{{badmatch,{error,nxdomain}},[{mysql,init,1,[{file,"src/mysql.erl"},{line,483}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}}}}}}},[{emqttd_plugin_mysql_app,start,2,[{file,"src/emqttd_plugin_mysql_app.erl"},{line,33}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}]}}}}
```
how to fix?
thanks a lot.

**Comment by xurwxj** [comment]
if i change the mysql server from domain to ip, problem will go away.
can i use mysql server host with domain in config file?

**Comment by emqplus** [comment]
Hi @xurwxj, the Erlang MySQL driver supports domain name. The issue is usually caused by DNS resolv of your server.

**Comment by xurwxj** [comment]
i can ping the mysql domain from emqtt server, but emqtt startup fail.

**Comment by emqplus** [comment]
Attached to the emqttd console:
```
./bin/emqttd_ctl attach
````

And the try to connect to mysql with domain:

```
gen_tcp:connect("domain", 3306, []).
```

Ctrl+D Exit.

**Comment by xurwxj** [comment]
seems no attach command.
all emqttd_ctl command listed when execute  ./bin/emqttd attach

**Comment by xurwxj** [comment]
![image](https://cloud.githubusercontent.com/assets/683421/15990684/8ec05b56-30cd-11e6-9901-2a0b8ec4f786.png)
