### ISSUE TITLE
Mysql ACL, device subscribes to itself

### ISSUE THREAD

**Issue by kenpeter** [emqtt/emqttd#589]
![mqtt_acl](https://cloud.githubusercontent.com/assets/927150/15879141/a3c01b48-2d64-11e6-82cb-85cf542661fb.png)

This is my current acl setup. It contains human user and device records. column mqtt_user_type_id =1 means human. column mqtt_user_type_id = 2 means device. As you can see user_id = 6 (human) controls device_1 and device_2.

My question is device needs to subscribe to itself by default, which means I need to add rule  individually for each device. Is it a better way to do this? I think I saw something using %u, but I am not able to find. Are you able to give me some pointers?

**Comment by emqplus** [comment]
Hi @kenpeter, please fork the [emqttd_plugin_mysql](https://github.com/emqtt/emqttd_plugin_mysql) plugin and customize the ACL by yourself.
