### ISSUE TITLE
erlang VM metrics and monitor

### ISSUE THREAD

**Issue by erylee** [emqtt/emqttd#59]
Monitor Erlang VM:

CPU
Memory
Process
ETS
Ports

**Comment by huangdan** [comment]
1、cpu metrics:
cpu_sup:avg1()、cpu_sup:avg5()、cpu_sup:avg15()、scheduler_usage/1
2、Memory metrics:
erlang:memory()；
allocated： reports the memory that is reserved by the VM.
used、unused、usage

**Comment by huangdan** [comment]
Process：
1、process list:
Pid、Name、reductions、memory、MsgQueue、currentFun；
2、process information:
[initial_call, current_function,registered_name,status,message_queue_len,group_leader,priority,trap_exit,reductions,binary,last_calls,catchlevel,trace,suspending,sequential_trace_token,error_handler]
3、memory and GC
[memory,total_heap_size,heap_size,stack_size,min_heap_size,fullsweep_after]

get_process_list/0;
get_process_info/0
get_process_gc/0
get_process_group_leader_info/1

**Comment by huangdan** [comment]
ETS：
1、get_ets_list/0
ets:all().
2、get_ets_info/0
return: [{owner, Owner}|ets:info(Tab)]
3、get_ets_info(Tabname)
[{owner, Owner}|ets:info(Tabname)]
4、get_ets_object/0
ets:tab2list(AllTable)
5、get_ets_object/1
ets:tab2list(SingleTab)
