### ISSUE TITLE
Request/Help : Need to persist some topics in Database 

### ISSUE THREAD

**Issue by atulgoswami21** [emqtt/emqttd#591]
Any body could help me doing that or suggest me the other way of doing except subscribe and then persist.
I also want to call an api when i received any publish on topic.

**Comment by emqplus** [comment]
Hi @atulgoswami21, we will release a 'EmqPlus' product this month to help users store MQTT messages into various backends such as MySQL, MongoDB, Redis...

**Comment by atulgoswami21** [comment]
Thanks and waiting for release.

**Comment by numbertank** [comment]
Waiting you release

**Comment by maituanmte** [comment]
@emqplus I see that, you have released "EMQPlus" already to store message to mysql. But I don't see that. Can you give me a url?.
