### ISSUE TITLE
Install on windows 32 bit

### ISSUE THREAD

**Issue by araxis** [emqtt/emqttd#592]
sorry for my bad english.
when i try install emqttd v1.1.1  on windows 10 32 bit ,i got this error:

This version of C:\emqttd\erts-7.3\bin\werl.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

how do i can install emqttd on windows 32 bit
thanks.

**Comment by emqplus** [comment]
Hi @araxis, the binary package for windows is 64bit. You have to build from source for win10 32bit.

**Comment by araxis** [comment]
ok!and how do i can build it from soirce on windows?
thanks for your attention!

**Comment by emqplus** [comment]
Contact QQ: 348822724. I will close the issue now.
