### ISSUE TITLE
published message autodelete from broker after expiry time

### ISSUE THREAD

**Issue by iammehrabalam** [emqtt/emqttd#593]
Is it possible to set the expiry time for published message on broker?

My use case:
-----------------
When client publish a message to the broker then all client currently subscribed will receive this message and also another client(s) (previously clean_session is false) if subscribe within 10 min also receive this message.

@emqplus please reply

**Comment by emqplus** [comment]
Hi @iammehrabalam, publish a retained message and configure the expiration in etc/emqttd.config:

```
        %% Retained messages
        {retained, [
            %% Expired after seconds, never expired if 0
            {expired_after, 600},

            %% Max number of retained messages
            {max_message_num, 100000},

            %% Max Payload Size of retained message
            {max_playload_size, 65536}
        ]},
```
