### ISSUE TITLE
error on build from source on windows 32-bit

### ISSUE THREAD

**Issue by araxis** [emqtt/emqttd#594]
sorry for my bad English.
i try build emqttd for windows 32 bit but  build process  ended with this :

==> bson (compile)
Compiled src/bson_schema.erl
Compiled src/bson.erl
Compiled src/bson_binary.erl
==> pbkdf2 (compile)
A subdirectory or file ebin already exists.
Error occurred while processing: ebin.
ERROR: Command [compile] failed!
makefile:14: recipe for target 'compile' failed
make: *** [compile] Error 1

and nothing else.

**Comment by emqplus** [comment]
Hi @araxis, the broker does not support windows 32-bit

**Comment by araxis** [comment]
I am disappointed!!!!!!
