### ISSUE TITLE
connecttion refused:Bad username or password

### ISSUE THREAD

**Issue by amazg** [emqtt/emqttd#596]
when i connect on the first time ，it often occur “connecttion refused:Bad username or password” ，
After a while it connect success

**Comment by amazg** [comment]
i use emqtt_mysql

**Comment by amazg** [comment]
my config:
%% select password only
    {authquery, "select password from mqtt_user where username = '%u' limit 1"},

    %% hash algorithm: plain, md5, sha, sha256, pbkdf2?
    {password_hash, sha256},

    %% select password with salt
    %% {authquery, "select password, salt from mqtt_user where username = '%u'"},

    %% sha256 with salt prefix
    %% {password_hash, {salt, sha256}},

    %% sha256 with salt suffix
    %% {password_hash, {sha256, salt}},

    %% comment this query, the acl will be disabled
    {aclquery, "select allow, ipaddr, username, clientid, access, topic from mqtt_acl where ipaddr = '%a' or username = '%u' or username = '$all' or clientid = '%c'"},

    %% If no rules matched, return...
    {acl_nomatch, deny}

**Comment by emqplus** [comment]
Hi @amazg,  root cause of this issue: https://github.com/mysql-otp/mysql-otp/issues/33

You could configure a 'keep_alive' option for a quick fix:
```
   {mysql_pool, [
        ...
        {auto_reconnect, 1},

        %% mysql options
        ...
        {keep_alive, 60000}
    ]},
```
