### ISSUE TITLE
Empty clientId with non-clean session accepted

### ISSUE THREAD

**Issue by mtappler** [emqtt/emqttd#599]
I am currently investigating the behaviour of several MQTT-brokers and noticed that the emqtt-broker accepts  connections with empty client identifier and clean session set to 0 (emqttd sends a CONNACK with return code 0x00). This is a violation of the MQTT-standard according to

> If the Client supplies a zero-byte ClientId with CleanSession set to 0, the Server MUST respond to the
> CONNECT Packet with a CONNACK return code 0x02 (Identifier rejected) and then close the Network Connection [MQTT-3.1.3-8].

**Comment by emqplus** [comment]
@mtappler, Thx. This compatible issue is fixed in PR: https://github.com/emqtt/emqttd/pull/602
