### ISSUE TITLE
Connection Timeout from emqttd broker.

### ISSUE THREAD

**Issue by numbertank** [emqtt/emqttd#603]
Hi,
I am getting many times connection time out from emqttd broker to my client (Android and iOS).

my mqttd Version is 1.1.1,
**etc/emqttd.config**
        {session, [
            {max_inflight, 10000},
            {unack_retry_interval, 60},
            {await_rel_timeout, 20},
            {max_awaiting_rel, 0},
           {collect_interval, 20},
           {expired_after, 43200}
        ]},

Client side Android , Eclipse paho 1.0.2
                  iOS, MQTT MQTT-Client-Framework 0.7.8
Both have default keepalive timeout 60

My server is Amazon AWS - m4.xlarge
## /etc/sysctl.conf

fs.file-max=2097152
fs.nr_open=2097152
# echo 2097152 > /proc/sys/fs/nr_open
# Increase number of incoming connections backlog:

net.core.somaxconn=32768
net.ipv4.tcp_max_syn_backlog=16384
net.core.netdev_max_backlog=16384
# Local Port Range:

net.ipv4.ip_local_port_range=1000 65535
# Read/Write Buffer for TCP connections:

net.core.rmem_default=262144
net.core.wmem_default=262144
net.core.rmem_max=16777216
net.core.wmem_max=16777216
net.core.optmem_max=16777216

net.ipv4.tcp_rmem=1024 4096 16777216
net.ipv4.tcp_wmem=1024 4096 16777216
# Connection Tracking:
# net.nf_conntrack_max=1000000
# net.netfilter.nf_conntrack_max=1000000
# net.netfilter.nf_conntrack_tcp_timeout_time_wait=30
# net.netfilter.nf_conntrack_max=1000000
# The TIME-WAIT Buckets Pool, Recycling and Reuse:

net.ipv4.tcp_max_tw_buckets=1048576
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_tw_reuse = 1
# Timeout for FIN-WAIT-2 sockets:

net.ipv4.tcp_fin_timeout = 15
## /etc/security/limits.conf

root   soft   nofile      1048576
root   hard   nofile      1048576
-      soft   nofile      1048576
-      hard   nofile      1048576

Any one an help me to resolved this issue.

**Comment by emqplus** [comment]
@numbertank, check log/emqttd_error.log first and show stats of the broker:

```
./bin/emqttd_ctl broker metrics
./bin/emqttd_ctl broker stats
./bin/emqttd_ctl listeners
```

**Comment by numbertank** [comment]
Thanks for your prompt reply.

I have check log/emqttd_error.log, log/emqttd_info.log and log/emqttd_crash.log. It is empty.

**./bin/emqttd_ctl listeners:**
listener on http:8083
  acceptors       : 4
  max_clients     : 64
  current_clients : 0
  shutdown_count  : []
listener on mqtts:8883
  acceptors       : 4
  max_clients     : 512
  current_clients : 0
  shutdown_count  : []
listener on mqtt:1883
  acceptors       : 16
  max_clients     : 8192
  current_clients : 21
  shutdown_count  : [{conflict,2734},{idle_timeout,54},{keepalive_timeout,4903},{closed,11319}]
listener on http:18083
  acceptors       : 4
  max_clients     : 512
  current_clients : 0
  shutdown_count  : []

**./bin/emqttd_ctl broker stats**
clients/count       : 18
clients/max         : 36
retained/count      : 828
retained/max        : 828
routes/count        : 11973
routes/max          : 11973
sessions/count      : 817
sessions/max        : 817
subscribers/count   : 12883
subscribers/max     : 12883
subscriptions/count : 12883
subscriptions/max   : 12883
topics/count        : 12025
topics/max          : 12025

**./bin/emqttd_ctl broker metrics**
bytes/received          : 2302626
bytes/sent              : 1007859
messages/dropped        : 0
messages/qos0/received  : 2907
messages/qos0/sent      : 1543
messages/qos1/received  : 7594
messages/qos1/sent      : 5243
messages/qos2/received  : 10
messages/qos2/sent      : 0
messages/received       : 10511
messages/retained       : 828
messages/sent           : 6786
packets/connack         : 19158
packets/connect         : 19158
packets/disconnect      : 294
packets/pingreq         : 263955
packets/pingresp        : 263955
packets/puback/received : 5132
packets/puback/sent     : 7594
packets/pubcomp/received: 0
packets/pubcomp/sent    : 9
packets/publish/received: 10511
packets/publish/sent    : 6786
packets/pubrec/received : 0
packets/pubrec/sent     : 10
packets/pubrel/received : 9
packets/pubrel/sent     : 0
packets/received        : 321463
packets/sent            : 319916
packets/suback          : 19562
packets/subscribe       : 19562
packets/unsuback        : 2842
packets/unsubscribe     : 2842


What i am doing wrong.
