### ISSUE TITLE
About bridge

### ISSUE THREAD

**Issue by anhldbk** [emqtt/emqttd#606]
@emqplus  I've reading documentation about [Bridge](http://emqtt.io/docs/bridge.html). So this feature is supposed to work on local networks, right? So that means there's no bridge over the internet.

**Comment by emqplus** [comment]
mosquitto could bridge to emqttd remotely: http://emqtt.io/docs/bridge.html#mosquitto-bridge

**Comment by anhldbk** [comment]
Is there any security mechanism for remote bridges? For example: `user name` & `password`?

**Comment by emqplus** [comment]
A remote bridge from mosquitto is just a normal mqtt connection to emqtt broker.

**Comment by anhldbk** [comment]
@emqplus I don't see any security configuration (username, password) for mosquitto to connect to emqttd.

**Comment by anhldbk** [comment]
@emqplus Ping ping ping ....

**Comment by dophlin** [comment]
@anhldbk in mosquitto config file, there are four credential properties for a bridge connection.
local_username, local_password: Configure the username and password to be used when emqttd is connecting the bridge to mosquitto.

remote_username, remote_password: Configure the username and password to be used when mosquitto is connecting the bridge to emqttd.

Please note that all of these properties must be set for a valid connection. Also, keep it in your mind, this connection is not under TLS.

**Comment by anhldbk** [comment]
@dophlin Thank you!
