### ISSUE TITLE
emqttd_ctl listeners and broker stats show clients not match

### ISSUE THREAD

**Issue by xiaosunzhu** [emqtt/emqttd#608]
Use emqtt_ctl listeners show current_clients is 103714, but use emqttd_ctl broker stats show clients/count is 21002, use emqtt_ctl clients list export clients info count is 21002 too, why the  numbers not match?

 emqtt_ctl listeners show that clients number increase 80000+ in a short time, maybe 20 minutes, and system memery used increase 2G and even more. After a while, clients number decrease to 21002, why that happened?

> [root@55 emqttd]# ./bin/emqttd_ctl broker stats
clients/count       : 21002
clients/max         : 21157
queues/count        : 0
queues/max          : 0
retained/count      : 2
retained/max        : 2
routes/count        : 21164
routes/reverse      : 21164
sessions/count      : 21163
sessions/max        : 21163
subscriptions/count : 21168
subscriptions/max   : 21168
topics/count        : 19056
topics/max          : 19056
[root@55 emqttd]# ./bin/emqttd_ctl clients list > clients.list
[root@55 emqttd]# ./bin/emqttd_ctl listeners
listener on http:8083
  acceptors       : 4
  max_clients     : 64
  current_clients : 0
  shutdown_count  : []
listener on mqtts:8883
  acceptors       : 4
  max_clients     : 51200
  current_clients : 0
  shutdown_count  : []
listener on mqtt:1883
  acceptors       : 1600
  max_clients     : 819200
  current_clients : 103714
  shutdown_count  : [{idle_timeout,32},{conflict,23},{closed,149423},{keepalive_timeout,1}]
listener on http:18083
  acceptors       : 4
  max_clients     : 512
  current_clients : 6
  shutdown_count  : []

**Comment by emqplus** [comment]
Invalid issue, closed.
