### ISSUE TITLE
Sudden increase in memory usage

### ISSUE THREAD

**Issue by hcrow110** [emqtt/emqttd#610]
Memory usage has been very stable,about 700M for 10 hours, suddenly rise to 2G, and there is no decline, which did not do any operation.

**Comment by emqplus** [comment]
hi @hcrow110, we cannot get any hints about what's happened... please post the stats of the broker:

```
./bin/emqttd_ctl vm
./bin/emqttd_ctl listeners
./bin/emqttd_ctl broker metrics
./bin/emqttd_ctl broker stats
./bin/emqttd_ctl plugins load emqttd_recon
./bin/emqttd_ctl recon bin_leak
```

**Comment by hcrow110** [comment]
emqtt version is 0.14 


[root@65 bin]# emqttd_ctl vm
cpu/load1               : 0.03
cpu/load5               : 0.05
cpu/load15              : 0.02
memory/total            : 68320272
memory/processes        : 19678672
memory/processes_used   : 19678000
memory/system           : 48641600
memory/atom             : 512601
memory/atom_used        : 492479
memory/binary           : 428512
memory/code             : 13377655
memory/ets              : 1825144
process/limit           : 262144
process/count           : 2396
io/max_fds              : 204800
io/active_fds           : 1

[root@65 bin]# ./emqttd_ctl listeners
listener on http:8083
  acceptors       : 4
  max_clients     : 64
  current_clients : 0
  shutdown_count  : []
listener on mqtts:8883
  acceptors       : 4
  max_clients     : 51200
  current_clients : 0
  shutdown_count  : []
listener on mqtt:1883
  acceptors       : 1600
  max_clients     : 819200
  current_clients : 2
  shutdown_count  : [{conflict,1},{destroy,1},{closed,530}]
listener on http:18083
  acceptors       : 4
  max_clients     : 512
  current_clients : 3
  shutdown_count  : []


[root@65 bin]# emqttd_ctl broker metrics
bytes/received          : 2131450
bytes/sent              : 2075052
messages/dropped        : 3676
messages/qos0/received  : 4350
messages/qos0/sent      : 10327
messages/qos1/received  : 6011
messages/qos1/sent      : 0
messages/qos2/received  : 0
messages/qos2/sent      : 0
messages/received       : 10361
messages/retained       : 2
messages/sent           : 10327
packets/connack         : 534
packets/connect         : 534
packets/disconnect      : 0
packets/pingreq         : 37
packets/pingresp        : 37
packets/puback/received : 0
packets/puback/sent     : 6011
packets/pubcomp/received: 0
packets/pubcomp/sent    : 0
packets/publish/received: 10361
packets/publish/sent    : 10327
packets/pubrec/received : 0
packets/pubrec/sent     : 0
packets/pubrel/received : 0
packets/pubrel/sent     : 0
packets/received        : 11464
packets/sent            : 17441
packets/suback          : 532
packets/subscribe       : 532
packets/unsuback        : 0
packets/unsubscribe     : 0

[root@65 bin]# emqttd_ctl broker stats
clients/count       : 2
clients/max         : 332
queues/count        : 0
queues/max          : 0
retained/count      : 2
retained/max        : 2
routes/count        : 531
routes/reverse      : 531
sessions/count      : 531
sessions/max        : 531
subscriptions/count : 530
subscriptions/max   : 530
topics/count        : 583
topics/max          : 583

[root@65 bin]# emqttd_ctl recon bin_leak
{<10037.311.0>,-49,
 [{current_function,{emysql_recv,loop,1}},{initial_call,{proc_lib,init_p,5}}]}
{<10037.313.0>,-47,
 [{current_function,{emysql_recv,loop,1}},{initial_call,{proc_lib,init_p,5}}]}
{<10037.315.0>,-45,
 [{current_function,{emysql_recv,loop,1}},{initial_call,{proc_lib,init_p,5}}]}
{<10037.142.0>,-41,
 [mnesia_locker,
  {current_function,{mnesia_locker,loop,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.308.0>,-40,
 [{current_function,{emysql_recv,loop,1}},{initial_call,{proc_lib,init_p,5}}]}
{<10037.307.0>,-38,
 [{current_function,{gen_server,loop,6}},{initial_call,{proc_lib,init_p,5}}]}
{<10037.233.0>,-37,
 [{current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.239.0>,-34,
 [{current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.199.0>,-33,
 [emqttd_pubsub_10,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.234.0>,-33,
 [{current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.201.0>,-32,
 [emqttd_pubsub_12,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.231.0>,-32,
 [{current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.236.0>,-31,
 [{current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.237.0>,-31,
 [{current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.242.0>,-31,
 [{current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.243.0>,-28,
 [{current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.314.0>,-25,
 [{current_function,{gen_server,loop,6}},{initial_call,{proc_lib,init_p,5}}]}
{<10037.190.0>,-24,
 [emqttd_pubsub_1,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.205.0>,-24,
 [emqttd_pubsub_16,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.230.0>,-24,
 [{current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.238.0>,-24,
 [{current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.228.0>,-23,
 [{current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.202.0>,-22,
 [emqttd_pubsub_13,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.229.0>,-22,
 [{current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.235.0>,-22,
 [{current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.200.0>,-21,
 [emqttd_pubsub_11,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.241.0>,-21,
 [{current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.240.0>,-20,
 [{current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.250.0>,-20,
 [emqttd_sm_4,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.255.0>,-20,
 [emqttd_sm_9,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.198.0>,-19,
 [emqttd_pubsub_9,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.232.0>,-18,
 [{current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.203.0>,-17,
 [emqttd_pubsub_14,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.253.0>,-15,
 [emqttd_sm_7,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.195.0>,-13,
 [emqttd_pubsub_6,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.310.0>,-13,
 [{current_function,{gen_server,loop,6}},{initial_call,{proc_lib,init_p,5}}]}
{<10037.312.0>,-12,
 [{current_function,{gen_server,loop,6}},{initial_call,{proc_lib,init_p,5}}]}
{<10037.193.0>,-11,
 [emqttd_pubsub_4,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.248.0>,-10,
 [emqttd_sm_2,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.256.0>,-10,
 [emqttd_sm_10,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.191.0>,-9,
 [emqttd_pubsub_2,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.197.0>,-8,
 [emqttd_pubsub_8,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.204.0>,-8,
 [emqttd_pubsub_15,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.196.0>,-7,
 [emqttd_pubsub_7,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.192.0>,-5,
 [emqttd_pubsub_3,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.251.0>,-5,
 [emqttd_sm_5,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.257.0>,-5,
 [emqttd_sm_11,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.259.0>,-5,
 [emqttd_sm_13,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.260.0>,-5,
 [emqttd_sm_14,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.262.0>,-5,
 [emqttd_sm_16,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.263.0>,-5,
 [emqttd_session_sup,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.264.0>,-5,
 [emqttd_broker,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.194.0>,-4,
 [emqttd_pubsub_5,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.219.0>,-4,
 [emqttd_pooler_10,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.247.0>,-4,
 [emqttd_sm_1,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.254.0>,-4,
 [emqttd_sm_8,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.3.0>,-3,
 [erl_prim_loader,
  {current_function,{erl_prim_loader,loop,3}},
  {initial_call,{erlang,apply,2}}]}
{<10037.30.0>,-3,
 [user_drv,
  {current_function,{user_drv,server_loop,6}},
  {initial_call,{user_drv,server,2}}]}
{<10037.212.0>,-3,
 [emqttd_pooler_3,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.213.0>,-3,
 [emqttd_pooler_4,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.214.0>,-3,
 [emqttd_pooler_5,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.215.0>,-3,
 [emqttd_pooler_6,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.217.0>,-3,
 [emqttd_pooler_8,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.221.0>,-3,
 [emqttd_pooler_12,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.222.0>,-3,
 [emqttd_pooler_13,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.223.0>,-3,
 [emqttd_pooler_14,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.225.0>,-3,
 [emqttd_pooler_16,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.261.0>,-3,
 [emqttd_sm_15,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.12.0>,-2,
 [code_server,
  {current_function,{code_server,loop,1}},
  {initial_call,{erlang,apply,2}}]}
{<10037.210.0>,-2,
 [emqttd_pooler_1,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.211.0>,-2,
 [emqttd_pooler_2,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.216.0>,-2,
 [emqttd_pooler_7,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.218.0>,-2,
 [emqttd_pooler_9,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.224.0>,-2,
 [emqttd_pooler_15,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.252.0>,-2,
 [emqttd_sm_6,
  {current_function,{gen_server2,process_next_msg,1}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.6.0>,-1,
 [error_logger,
  {current_function,{gen_event,fetch_msg,5}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.7.0>,-1,
 [application_controller,
  {current_function,{gen_server,loop,6}},
  {initial_call,{erlang,apply,2}}]}
{<10037.31.0>,-1,
 [user,
  {current_function,{group,server_loop,3}},
  {initial_call,{group,server,3}}]}
{<10037.33.0>,-1,
 [{current_function,{shell,get_command1,5}},{initial_call,{erlang,apply,2}}]}
{<10037.42.0>,-1,
 [{current_function,{file_io_server,server_loop,1}},
  {initial_call,{erlang,apply,2}}]}
{<10037.98.0>,-1,
 [{current_function,{application_master,loop_it,4}},
  {initial_call,{application_master,start_it,4}}]}
{<10037.158.0>,-1,
 [{current_function,{disk_log,loop,1}},{initial_call,{proc_lib,init_p,5}}]}
{<10037.220.0>,-1,
 [emqttd_pooler_11,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.271.0>,-1,
 [inet_gethost_native,
  {current_function,{inet_gethost_native,main_loop,1}},
  {initial_call,{inet_gethost_native,server_init,2}}]}
{<10037.0.0>,0,
 [init,{current_function,{init,loop,1}},{initial_call,{otp_ring0,start,2}}]}
{<10037.9.0>,0,
 [{current_function,{application_master,main_loop,2}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.10.0>,0,
 [{current_function,{application_master,loop_it,4}},
  {initial_call,{application_master,start_it,4}}]}
{<10037.11.0>,0,
 [kernel_sup,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.14.0>,0,
 [rex,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.15.0>,0,
 [global_name_server,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.16.0>,0,
 [{current_function,{global,loop_the_locker,1}},
  {initial_call,{erlang,apply,2}}]}
{<10037.17.0>,0,
 [{current_function,{global,loop_the_registrar,0}},
  {initial_call,{erlang,apply,2}}]}
{<10037.18.0>,0,
 [inet_db,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.19.0>,0,
 [net_sup,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.20.0>,0,
 [erl_epmd,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.21.0>,0,
 [auth,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.22.0>,0,
 [net_kernel,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
{<10037.23.0>,0,
 [{current_function,{prim_inet,accept0,2}},
  {initial_call,{inet_tcp_dist,accept_loop,2}}]}
{<10037.24.0>,0,
 [{current_function,{net_kernel,ticker_loop,2}},
  {initial_call,{net_kernel,ticker,2}}]}
{<10037.25.0>,0,
 [global_group,
  {current_function,{gen_server,loop,6}},
  {initial_call,{proc_lib,init_p,5}}]}
