### ISSUE TITLE
Version above 1.0.3 crashs at start

### ISSUE THREAD

**Issue by kenpeter** [emqtt/emqttd#614]
I am currently using v1.0.3 and it is working fine. I checkout a few versions above v1.0.3. Deleted data/mnesia, symbolic link config files like emqttd.conf, vm.args and emqttd_plugin_mysql/etc/plugin.config. Start it, it crashes every time. Error reports are attached.

[emqttd_sasl.log.txt](https://github.com/emqtt/emqttd/files/342583/emqttd_sasl.log.txt)
[erlang.log.1.txt](https://github.com/emqtt/emqttd/files/342584/erlang.log.1.txt)

**Comment by emqplus** [comment]
@kenpeter, upgrade deps/esockd please.
