### ISSUE TITLE
libcrypto missing on an ec2 linux system

### ISSUE THREAD

**Issue by brechmos** [emqtt/emqttd#618]
Hi,
I am on a linux box on EC2 AWS (with the amazon rolling linux version).  I have openssl installed 

```
openssl version
OpenSSL 1.0.1k-fips 8 Jan 2015

```

but I am getting an error:

```
=ERROR REPORT==== 1-Jul-2016::18:48:29 ===
Unable to load crypto library. Failed with error:
"load_failed, Failed to load NIF library /home/ec2-user/mqtt/emqttd/lib/crypto-3.6.3/priv/lib/crypto: 'libcrypto.so.1.0.0: cannot open shared object file: No such file or directory'"
OpenSSL might not be installed on this system.

=WARNING REPORT==== 1-Jul-2016::18:48:29 ===
The on_load function for module crypto returned {error,
                                                 {load_failed,
                                                  "Failed to load NIF library /home/ec2-user/mqtt/emqttd/lib/crypto-3.6.3/priv/lib/crypto: 'libcrypto.so.1.0.0: cannot open shared object file: No such file or directory'"}}
```

I am kind of confused why the error is happening. I have this running on other linux machines, so clearly it is something with the EC2 setup.  

Any ideas on a way around this or what I might have to install to get it going?

[Edit:  I realize this is likely less of a emqttd issue and more of a weird setup, but I would still be grateful for input.]

**Comment by emqplus** [comment]
hi @brechmos, please build the broker from source: http://emqtt.io/docs/install.html#installing-from-source

**Comment by brechmos** [comment]
Ok. I will try that.  Thank you for getting back to me.

On 07/01/2016 10:28 PM, Feng Lee wrote:
>
> hi @brechmos <https://github.com/brechmos>, please build the broker
> from source: http://emqtt.io/docs/install.html#installing-from-source
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/emqtt/emqttd/issues/618#issuecomment-230079024>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA2Le4AgF_y_6IM82vn9yxLS4-nYCHUtks5qRczngaJpZM4JDZTQ>.
>

-- 
Craig Jones
craig@brechmos.org
https://craig.brechmos.org
gpg:1500 550D D162 C7C5 934F 0FF3 2FA1 B752 76E0 09C6
