### ISSUE TITLE
How to persist the recently published message

### ISSUE THREAD

**Issue by edmandiesamonte** [emqtt/emqttd#624]
Is it possible to persist the recently published message to any topic? I'm planning to add a simple REST service on top of MQTT. The intention is to support clients that do not need the realtime data but wants to get the latest published data (i.e. consumers of temperature sensor data)

**Comment by emqplus** [comment]
@edmandiesamonte, MQTT 'retained' message:

```
If the RETAIN flag is set to 1, in a PUBLISH Packet sent by a Client to a Server, the Server MUST store the Application Message and its QoS, so that it can be delivered to future subscribers whose subscriptions match its topic name [MQTT-3.3.1-5]. When a new subscription is established, the last retained message, if any, on each matching topic name MUST be sent to the subscriber [MQTT-3.3.1-6]. If the Server receives a QoS 0 message with the RETAIN flag set to 1 it MUST discard any message previously retained for that topic. It SHOULD store the new QoS 0 message as the new retained message for that topic, but MAY choose to discard it at any time - if this happens there will be no retained message for that topic [MQTT-3.3.1-7]. See Section 4.1 for more information on storing state.
```

**Comment by edmandiesamonte** [comment]
My idea is to actually to retain all published messages regardless if the retain flag is provided. This is only for the REST API interface. In short, if the message has a retain flag set to false, it will not be pushed to new subscribers but will be available via the REST API. This is the same limitation of [Eclipse Ponte](https://github.com/eclipse/ponte). It's a good start nonetheless. Thanks for the response.
