### ISSUE TITLE
Reload ACL without re-connect

### ISSUE THREAD

**Issue by billysz** [emqtt/emqttd#626]
Hi,

I am using mysql ACL plugin, it seems when a client connect to the broker the acl records assigned to that client will get loaded, and will not be loaded again unless the client disconnect and then connect again.
The requirement is when the client is already online, it's ACL records could be changed in database, and expected to be reloaded, so client can sub/pub to some new topics, which was not allowed when it established the connection, is that possible and how?

Thanks

**Comment by emqplus** [comment]
Hi @billysz, emqttd will cache the Pub ACL rules to avoid query database for each MQTT message. Any suggestions to resolve this issue? :)

**Comment by billysz** [comment]
Hi @emqplus ,thanks for reply, it does make sense to cache the ACL rules, but is it possible to provide an API to force reloading ACL for particular clients?
One more question, does the Redis plugin use cache?

**Comment by congleetea** [comment]
@billysz It is cached in process directory.       @emqplus Is there a way to acl again if necessary?  In some cases, if users change the right to access some topic, it should check the acl again.

**Comment by emqplus** [comment]
@congleetea, @billysz We add a 'mqtt.cache_acl' option in 2.0 release. The PR: https://github.com/emqtt/emqttd/pull/764

**Comment by CrazyPandar** [comment]
Suggest to provide an API to force reloading ACL for particular clients and particular topic .
