### ISSUE TITLE
Parser failed

### ISSUE THREAD

**Issue by congleetea** [emqtt/emqttd#629]
Hi, I have an issue with following log:

 [error] Client(192.168.0.111:29031): Parser failed for {{badmatch,<<34,58,34,49,46,51,46,49,46,49,54,48,55,48,52,34,44,34,115,121,115,95,118,101,114,34,58,34,49,46,48,46,50,46,49,34,125,130,62,0,2,0,57,118,49,47,56,56,56,48,48,50,49,48,48,48,48,48,48,48,48,48,48,48,48,48,48,55,52,51,47,102,105,114,109,119,97,114,101,47,100,101,102,97,117,108,116,47,97,99,116,105,111,110,47,102,108,97,115,104,0,130,59,0,3,0,54,118,49,47,56,56,56,48>>},[{emqttd_parser,parse_frame,3,[{file,"src/emqttd_parser.erl"},{line,139}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,260}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,250}]}]}
18:27:57.804 ^[[1;31m[error] Client(192.168.0.111:29031): Error data: <<130,59,0,3,0,54,118,49,47,56,56,56,48,48,50,49,48,48,48,48,48,48,48,48,48,48,48,48,48,48,55,52,51,47,116,111,107,101,110,47,100,101,102,97,117,108,116,47,97,99,116,105,111,110,47,102,108,97,115,104,0>>

can someone help me about it? thanks a lot.

**Comment by emqplus** [comment]
@congleetea, fixed?

**Comment by congleetea** [comment]
No,  sometime it happened. I almost can not catch the error.

**Comment by BADBDY23** [comment]
I have a similar issue, my client is connecting to the broker via lua [https://github.com/geekscape/mqtt_lua](url)

19:57:27.848 <0.2034.0> [error] Client(5.117.227.67:1152): Parser failed for {{badmatch,0},[{emqttd_parser,parse_frame,3,[{file,"src/emqttd_parser.erl"},{line,146}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,247}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,250}]}]}
19:57:27.848 <0.2034.0> [error] Client(5.117.227.67:1152): Error data: <<128,16,0,1,0,11,47,112,108,97,121,101,114,47,49,51,53,0,48,21,0,18,47,112,108,97,121,101,114,47,49,51,53,47,115,116,97,116,117,115,49,128,182,1,0,2,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,50,56,49,56,0,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,50,51,52,54,0,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,51,51,57,55,0,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,49,52,56,53,0,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,50,50,51,55,0,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,54,51,53,53,0,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,55,53,49,55,0,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,54,57,54,48,0,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,51,55,55,56,0>>

**Comment by emqplus** [comment]
@BADBDY23, https://github.com/emqtt/emqttd/issues/575

**Comment by turtleDeng** [comment]
<<128,16,0,1,0,11,47,112,108,97,121,101,114,47,49,51,53,0,48,21,0,18,47,112,108,97,121,101,114,47,49,51,53,47,115,116,97,116,117,115,49,128,182,1,0,2,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,50,56,49,56,0,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,50,51,52,54,0,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,51,51,57,55,0,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,49,52,56,53,0,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,50,50,51,55,0,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,54,51,53,53,0,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,55,53,49,55,0,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,54,57,54,48,0,0,17,47,116,111,117,114,110,97,109,101,110,116,47,52,51,55,55,56,0>>

parse result
{mqtt_packet,{mqtt_packet_header,8,false,1,false},
                 {mqtt_packet_subscribe,1,[{<<"/player/135">>,0}]},
                 undefined}

{mqtt_packet,{mqtt_packet_header,8,false,1,false},
                 {mqtt_packet_subscribe,1,[{<<"/player/135">>,0}]},
                 undefined}

{mqtt_packet,{mqtt_packet_header,8,false,1,false},
                 {mqtt_packet_subscribe,2,
                    [{<<"/tournament/42818">>,0},
                     {<<"/tournament/42346">>,0},
                     {<<"/tournament/43397">>,0},
                     {<<"/tournament/41485">>,0},
                     {<<"/tournament/42237">>,0},
                     {<<"/tournament/46355">>,0},
                     {<<"/tournament/47517">>,0},
                     {<<"/tournament/46960">>,0},
                     {<<"/tournament/43778">>,0}]}, undefined}

**Comment by turtleDeng** [comment]
<<130,59,0,3,0,54,118,49,47,56,56,56,48,48,50,49,48,48,48,48,48,48,48,48,48,48,48,48,48,48,55,52,51,47,116,111,107,101,110,47,100,101,102,97,117,108,116,47,97,99,116,105,111,110,47,102,108,97,115,104,0>>

parse result
{mqtt_packet,{mqtt_packet_header,8,false,1,false},                    
                 {mqtt_packet_subscribe,3,[{<<"v1/888002100000000000000743/token/default/action/flash">>,0}]},
                 undefined}
