### ISSUE TITLE
queue max_length configuration position confuse developer

### ISSUE THREAD

**Issue by roytan883** [emqtt/emqttd#631]
Unlike old version , currently 1.x **max_length** configuration is in %% Queue not in %% Session
Then i guess it meaning for the emqttd node now. But after my testing, i found that the **max_length** in **%% Queue** configuration actually stand for **%% Session**.

**But the max_length position in configure file is strange , it is not in %% Session.**

Test version is 1.1.2 on ubuntu
setting is:
```
%% Session
        {session, [
            {max_inflight, 1},
%% Queue
        {queue, [
            {max_length, 5},
```

the test process is:
```
node u2.js
on connect
sendMsg =  hi-u1-1
sendMsg =  hi-u1-2
sendMsg =  hi-u1-3
sendMsg =  hi-u1-4
sendMsg =  hi-u1-5
sendMsg =  hi-u1-6
sendMsg =  hi-u1-7
sendMsg =  hi-u1-8
sendMsg =  hi-u1-9
sendMsg =  hi-u1-10
sendMsg =  hi-u1-11
sendMsg =  hi-u1-12
sendMsg =  hi-u1-13
sendMsg =  hi-u1-14
sendMsg =  hi-u1-15
sendMsg =  hi-u1-16
^C

node u4.js
on connect
sendMsg =  hi-u3-1
sendMsg =  hi-u3-2
sendMsg =  hi-u3-3
sendMsg =  hi-u3-4
sendMsg =  hi-u3-5
sendMsg =  hi-u3-6
^C

node u1.js
on connect
on message
on message, topic =  u1
on message, message =  hi-u1-12
on message
on message, topic =  u1
on message, message =  hi-u1-13
on message
on message, topic =  u1
on message, message =  hi-u1-14
on message
on message, topic =  u1
on message, message =  hi-u1-15
on message
on message, topic =  u1
on message, message =  hi-u1-16

node u3.js
on connect
on message
on message, topic =  u3
on message, message =  hi-u3-2
on message
on message, topic =  u3
on message, message =  hi-u3-3
on message
on message, topic =  u3
on message, message =  hi-u3-4
on message
on message, topic =  u3
on message, message =  hi-u3-5
on message
on message, topic =  u3
on message, message =  hi-u3-6
^C
```

I  suggest  official team write more explanation in configure file comments for this **Queue max_length** configuration

**Comment by emqplus** [comment]
Hi @roytan883, the doc about session, queue and inflight window: http://emqtt.io/docs/design.html#session-layer.

I am working on new syntax of configuration file for 2.0 release these days. Please check: https://github.com/emqtt/emqttd-relx/blob/master/etc/emqttd.conf

Any suggestions?
