### ISSUE TITLE
queue缓存的是消息实体还是消息引用？

### ISSUE THREAD

**Issue by roytan883** [emqtt/emqttd#632]
rt，假定发布一个60k的数据到一个topic，这个topic目前有1w个离线的非clean session，那么这 1w个session的每个queue都需要放一个离线消息进去。那么问题来了，这些入队的消息是实体还是引用？

如果是实体，那么就会消耗60k*10000=600mb内存
如果是引用的话就只消耗 60k+几k的索引开销，整体内存消耗不大。

这里希望官方说明一下当前emqttd是用的哪种方式？

**Comment by emqplus** [comment]
@roytan883 第二种。下次请用用英文，否则以后issue无法检索
