### ISSUE TITLE
连接不稳定

### ISSUE THREAD

**Issue by shaojj1979** [emqtt/emqttd#633]
1.1.2，客户端为apache paho，将日志设置为info读取的内容为：
15:52:26.406 <0.381.0> [info] Client(shaojj@10.9.40.227:5532): RECV PUBACK(Q0, R0, D0, PacketId=1)
15:52:26.465 <0.381.0> [info] Client(shaojj@10.9.40.227:5532): RECV PUBACK(Q0, R0, D0, PacketId=2)
15:52:33.226 <0.381.0> [info] Client(shaojj@10.9.40.227:5532): Shutdown for closed
15:52:33.227 <0.380.0> [info] Session(shaojj): Client <0.381.0> EXIT for {shutdown,closed}
15:52:34.564 <0.403.0> [info] Client(shaojj@10.9.40.227:5573): RECV CONNECT(Q0, R0, D0, ClientId=shaojj, ProtoName=MQIsdp, ProtoVsn=3, CleanSess=false, KeepAlive=285, Username=kpush, Password=******)
15:52:34.564 <0.380.0> [info] Session(shaojj): resumed by <0.403.0>
15:52:34.565 <0.403.0> [info] Client(shaojj@10.9.40.227:5573): SEND CONNACK(Q0, R0, D0, AckFlags=1, RetainCode=0)
15:52:34.565 <0.380.0> [info] Session(shaojj): Subscribe []
15:52:34.604 <0.403.0> [info] Client(shaojj@10.9.40.227:5573): RECV SUBSCRIBE(Q1, R0, D0, PacketId=1, TopicTable=[{<<"shaojj">>,2}])
15:52:34.604 <0.380.0> [info] Session(shaojj): Subscribe [{<<"shaojj">>,2}]
15:52:34.604 <0.380.0> [warning] Session(shaojj): duplicated subscribe: shaojj, qos = 2
15:52:34.604 <0.403.0> [info] Client(shaojj@10.9.40.227:5573): SEND SUBACK(Q0, R0, D0, PacketId=1, QosTable=[2])
15:52:39.034 <0.404.0> [info] Client(shaojj@10.9.40.227:5674): RECV CONNECT(Q0, R0, D0, ClientId=shaojj, ProtoName=MQIsdp, ProtoVsn=3, CleanSess=false, KeepAlive=285, Username=kpush, Password=******)
15:52:39.034 <0.380.0> [info] Session(shaojj): resumed by <0.404.0>
15:52:39.034 <0.380.0> [warning] Session(shaojj): <0.404.0> kickout <0.403.0>
15:52:39.035 <0.403.0> [warning] Client(10.9.40.227:5573): clientid 'shaojj' conflict with <0.404.0>
15:52:39.035 <0.404.0> [info] Client(shaojj@10.9.40.227:5674): SEND CONNACK(Q0, R0, D0, AckFlags=1, RetainCode=0)
15:52:39.035 <0.380.0> [info] Session(shaojj): Subscribe []
15:52:39.066 <0.404.0> [info] Client(shaojj@10.9.40.227:5674): RECV SUBSCRIBE(Q1, R0, D0, PacketId=1, TopicTable=[{<<"shaojj">>,2}])
15:52:39.066 <0.380.0> [info] Session(shaojj): Subscribe [{<<"shaojj">>,2}]
15:52:39.066 <0.380.0> [warning] Session(shaojj): duplicated subscribe: shaojj, qos = 2
15:52:39.066 <0.404.0> [info] Client(shaojj@10.9.40.227:5674): SEND SUBACK(Q0, R0, D0, PacketId=1, QosTable=[2])

里面的[warning]内容，表现为，web界面看到端口经常改变，连接时间长了就会断开，很难重新连接。

**Comment by emqplus** [comment]
Invalid issue. Closed.

**Comment by cjy37** [comment]
+1 please open!
```
emqtt_emqtt-lb_1 | 2017-11-30T02:27:28.564132026Z 02:27:28.560 [error] SM(zg-2-10017446-34B493MF): Conflict with <35457.10528.540>
emqtt_emqtt-lb_1 | 2017-11-30T02:27:30.540146091Z 02:27:30.536 [error] SM(zg-2-10017446-34B493MF): Conflict with <35457.8505.540>
emqtt_emqtt-lb_1 | 2017-11-30T02:27:32.551577492Z 02:27:32.547 [error] SM(zg-2-10017446-34B493MF): Conflict with <35454.17449.168>
emqtt_emqtt-lb_1 | 2017-11-30T02:27:34.595087930Z 02:27:34.579 [error] SM(zg-2-10017446-34B493MF): Conflict with <35454.17727.168>
emqtt_emqtt-lb_1 | 2017-11-30T02:27:37.127072484Z 02:27:37.123 [error] SM(zg-3-10036537-21D713P): Conflict with <35453.12721.198>
emqtt_emqtt-lb_1 | 2017-11-30T02:27:46.714633060Z 02:27:46.709 [error] SM(zg-2-10017446-34B493MF): Conflict with <35453.12996.198>
emqtt_emqtt-lb_1 | 2017-11-30T02:27:47.729942930Z 02:27:47.724 [error] SM(zg-2-10017446-34B493MF): Conflict with <35455.29069.336>
emqtt_emqtt-lb_1 | 2017-11-30T02:27:51.431870042Z 02:27:51.428 [error] SM(zg-2-10017446-34B493MF): Conflict with <35454.18052.168>
emqtt_emqtt-lb_1 | 2017-11-30T02:27:53.874650625Z 02:27:53.871 [error] SM(zg-2-10017446-34B493MF): Conflict with <35456.662.241>
emqtt_emqtt-lb_1 | 2017-11-30T02:27:56.250512299Z 02:27:56.246 [error] SM(zg-3-10036537-21D713P): Conflict with <35455.29436.336>
emqtt_emqtt-lb_1 | 2017-11-30T02:27:57.255402794Z 02:27:57.250 [error] SM(zg-3-10036537-21D713P): Conflict with <35456.22780.240>
emqtt_emqtt-lb_1 | 2017-11-30T02:28:04.929530528Z 02:28:04.923 [error] SM(zg-2-10017446-34B493MF): Conflict with <35455.2726.337>
emqtt_emqtt-lb_1 | 2017-11-30T02:28:10.606898738Z 02:28:10.602 [error] SM(zg-2-10017446-34B493MF): Conflict with <35456.25762.240>
emqtt_emqtt-lb_1 | 2017-11-30T02:28:17.635357222Z 02:28:17.629 [error] SM(zg-2-10017446-34B493MF): Conflict with <35456.23144.240>
emqtt_emqtt-lb_1 | 2017-11-30T02:28:19.660097660Z 02:28:19.656 [error] SM(zg-3-10036537-21D713P): Conflict with <35457.13636.540>
emqtt_emqtt-lb_1 | 2017-11-30T02:28:22.796140499Z 02:28:22.792 [error] SM(zg-2-10017446-34B493MF): Conflict with <35455.1833.337>
emqtt_emqtt-lb_1 | 2017-11-30T02:28:26.300785341Z 02:28:26.296 [error] SM(zg-2-10017446-34B493MF): Conflict with <35457.14523.540>
emqtt_emqtt-lb_1 | 2017-11-30T02:28:26.612191100Z 02:28:26.608 [error] SM(zg-2-10017446-34B493MF): Conflict with <35454.19328.168>
emqtt_emqtt-lb_1 | 2017-11-30T02:28:30.667062739Z 02:28:30.663 [error] SM(zg-2-10017446-34B493MF): Conflict with <35457.15005.540>
emqtt_emqtt-lb_1 | 2017-11-30T02:29:12.504929646Z 02:29:12.499 [error] SM(zg-3-10036537-21D713P): Conflict with <35457.16736.540>
emqtt_emqtt-lb_1 | 2017-11-30T02:29:22.901333146Z 02:29:22.890 [error] SM(zg-3-10036537-21D713P): Conflict with <35454.19986.168>
emqtt_emqtt-lb_1 | 2017-11-30T02:29:47.145782502Z 02:29:47.140 [error] SM(zg-2-10018228-D651E7F): Conflict with <35457.17598.540>
emqtt_emqtt-lb_1 | 2017-11-30T02:29:50.651015460Z 02:29:50.646 [error] SM(zg-3-10036537-21D713P): Conflict with <35453.13830.198>
emqtt_emqtt-lb_1 | 2017-11-30T02:30:22.888830072Z 02:30:22.885 [error] SM(zg-3-10036537-21D713P): Conflict with <35457.18547.540>
emqtt_emqtt-lb_1 | 2017-11-30T02:30:24.925583694Z 02:30:24.921 [error] SM(zg-3-10036537-21D713P): Conflict with <35456.2808.241>
emqtt_emqtt-lb_1 | 2017-11-30T02:30:29.714008490Z 02:30:29.710 [error] SM(zg-2-10018822-340509UA): Conflict with <35453.13686.198>
emqtt_emqtt-lb_1 | 2017-11-30T02:31:41.620651628Z 02:31:41.617 [error] SM(zg-3-10002114-34DB996S): Conflict with <35453.15311.198>
emqtt_emqtt-lb_1 | 2017-11-30T02:37:09.794649201Z 02:37:09.788 [error] SM(zg-3-10085963-23AA6FDU): Conflict with <35455.9579.337>
emqtt_emqtt-lb_1 | 2017-11-30T02:40:18.182556014Z 02:40:18.177 [error] SM(zg-2-10051520-34021FWS): Conflict with <35456.31911.240>
```
