### ISSUE TITLE
I built a two nodes cluster, how to configure the LB? 

### ISSUE THREAD

**Issue by xsp1220** [emqtt/emqttd#635]
I try to create a two nodes cluster of emqttd broker. How to configure the LB?

**Comment by hongj-sh** [comment]
Just FYI, we are using LVS/DR + KeepAlived as LB of a 3-node emqtt cluster, works flawlessly.

**Comment by prakashr87** [comment]
Hai,
    @hongj-sh Can you please explain about LVS/DR + KeepAlived as LB of a 3-node emqtt cluster

**Comment by KrishnaPG** [comment]
+1 for the info on LVS/DR. It will be helpful.

**Comment by hongj-sh** [comment]
First, create a emqtt cluster  as usual (pls refer the emqtt document). 
Then we should set up a LVS server as LB, here's how to do it.

Some assumptions:
OS = Ubuntu Server 14.04
VIP=192.168.0.10 (virtual ip which your mqtt clients connect to)
LVS server IP = 192.168.0.100
EMQTT server1 IP =192.168.0.101
EMQTT server2 IP =192.168.0.102
EMQTT server2 IP =192.168.0.103
EMQTT port：1883

1. Install ipvsadm on LVS server and config it like below
apt-get install ipvsadm
ipvsadm -A -t 192.168.0.10:1883 -s rr   #rr = round robin
ipvsadm -a -t 192.168.0.10:1883 -r 192.168.0.101:1883 -g    #-g means DR mode
ipvsadm -a -t 192.168.0.10:1883 -r 192.168.0.102:1883 -g
ipvsadm -a -t 192.168.0.10:1883 -r 192.168.0.103:1883 -g

2. Config VIP and IP forwarding on LVS server
ifconfig lo:10 192.168.0.10 netmask 255.255.255.255 broadcast 192.168.0.10 up
echo  'net.ipv4.ip_forward=1'  >> /etc/sysctl.conf
sysctl -p

3. Config VIP and arp on each EMQTT server like below
ifconfig lo:10 192.160.0.10 netmask 255.255.255.255 broadcast 192.168.0.10 up
route add -host 192.160.0.10 dev lo:10
echo "1" > /proc/sys/net/ipv4/conf/lo/arp_ignore
echo "2" > /proc/sys/net/ipv4/conf/lo/arp_announce
echo "1" > /proc/sys/net/ipv4/conf/all/arp_ignore
echo "2" > /proc/sys/net/ipv4/conf/all/arp_announce

That's all. The mqtt client connects to 192.168.0.10 will be forwarded to 192.168.0.101-103 using round robin algorithm.
But, the above solution still lack of health check and the LVS server is a SPOF.
So we should setup another LVS server as standby, and use KeepAlived for health check and HA of LVS server. Pls google for how to install and config KeepAlived.

**Comment by KrishnaPG** [comment]
Thank you @hongj-sh The information is useful.
