### ISSUE TITLE
Any roadmap about Cassandra & Kafka support

### ISSUE THREAD

**Issue by mkj-git** [emqtt/emqttd#636]
I was going through the website and show cassandra & kafka in the displayed picture so thought it is supported now but didn't found any plugin or docs about the same? So what is the plan ?

**Comment by tomazbracic** [comment]
Any actual plugin for connecting to Kafka or better yet Cassandra? That would be really awesome.

**Comment by emqplus** [comment]
@tomazbracic, @mkj-git The Cassandra and Kafka Plugins have been released in our 'EMQ Plus' product.

**Comment by mkj-git** [comment]
What is 'EMQ Plus'  ?  whre can i find that?

**Comment by LeeWong** [comment]
Any update on this?
