### ISSUE TITLE
Recover from a network partition automatically

### ISSUE THREAD

**Issue by silviucpp** [emqtt/emqttd#638]
Hello,

Based on the documentation the cluster cannot recover from network partition automatically. Any plan to improve this ? Maybe using https://github.com/uwiger/unsplit can be an option to recover mnesia after a network split.

Silviu

**Comment by emqplus** [comment]
@silviucpp, we will improve the design to recover the cluster from network partition after 2.0 released. This issue is not urgent for there are usually two or three nodes cluster.

**Comment by hachreak** [comment]
I found also this project that looks interesting: https://github.com/lindenbaum/lbm_kv

`A dynamically-distributed, highly-available, partition-tolerant, in-memory key-value store built with Mnesia.`

**Comment by emqplus** [comment]
@hachreak, really interesting project. I am reading code and docs of lbm_kv now.

**Comment by emqplus** [comment]
Autoheal of network partition has been implemented in 2.2 release.
