### ISSUE TITLE
Any plan to support shared subscriptions feature in the future?

### ISSUE THREAD

**Issue by liszhu** [emqtt/emqttd#639]
Hi there,

Please accept my apprecation for developing such a great project.

While in using Emqtt as client connect interface and message routing platform in my m2m project, the emqtt cluster should connect a cluster of  application server, the feature of shared subscription supported by HiveMQ is very useful in such a scenaire.

I'd like to know does your team have any plan to develop such a feature ?

A brief description of the feature can be found in the url below.
http://www.hivemq.com/blog/mqtt-client-load-balancing-with-shared-subscriptions/

Thanks!
Lee

**Comment by Sephiroth-Wang** [comment]
Hi there, 

I also have this issue about "Share Subscription", not only HiveMQ has this feature, but VerneMQ.
They called "Consumer Session Balancing", but cannot apply in cluster mode.
[](https://vernemq.com/docs/configuration/balancing.html)

I hope this feature be implemented in eMQTT and support cluster.

**Comment by emqplus** [comment]
@liszhu, @Sephiroth-Wang, sorry for the delayed response. I've been working on 2.0 release these days:) The 'shared subscription' and message storage features will be released in the enterprise edition of the broker 2.0.

**Comment by liszhu** [comment]
Hi emqplus,

Thanks for your reply.

As enterprise edition was mentioned in the previous post,  does which mean that there are two or more editions of emqtt, e.g. community edition with limited function and enterprise edition with full function but charging is required ?   I am confused because I understood that emqtt is full open sourced.

Br,
Lee

**Comment by Zong-Li** [comment]
Hi emqplus,

I'm confused about the enterprise edition too.
Will the 'shared subscription' function is open source or for free with binary in the future?

**Comment by pranavmehta** [comment]
@emqplus,  I too am intrigued about  the enterprise edition. 

Would be great if  you could share what are going to be the major feature differences, pricing/licensing model and the overall path going forward.

Thanks!

**Comment by emqplus** [comment]
@pranavmehta, @Zong-Li, @liszhu, don't worry about the the enterprise edition:) First we will still open source all the code of the broker to our users or customers. Second, there will be a clear and very low pricing model for our commercial services or enterprise edition.

There are really too many new features in 2.x release including MQTT-SN, CoAP supports, MQTT Message storage in MySQL, Redis, MongoDB and PostgreSQL, MQTT Message streaming to Kafka... We love to develop open source but cannot maintain and evolve the projects in the long run without income.

The most important thing is not about free, it's about freedom and how we could build something great, I think.

**Comment by pranavmehta** [comment]
Thanks for sharing that information @emqplus 

Of course its important you have a commercial offering to even continue building great software like this project. Many open source projects have successfully done it - CouchBase, Redis, etc, etc. I'm sure you'll find various business models and takers for your commercial offering, so you can continue developing great software and also build a great community around it.

The message storage feature is really interesting. I hope its a plugin kind of model, so we can perhaps use any other data store. This could be especially helpful to store various states of each message such as acknowledged, etc. For example, in a chat app, these status could be useful to tell the sender that the message has been delivered to the recipient, etc. 

Do you have an ETA/roadmap when you expect version 2?

**Comment by liszhu** [comment]
@emqplus Thanks for your clarification and looking forward to the reveal of 2.x release.

**Comment by Sephiroth-Wang** [comment]
Hi emqplus, 

I'm so excited, the 2.0 released, but the "Share Subscription" feature seem not in this version?

**Comment by emqplus** [comment]
The 'Shared Subscription' feature has been released in 2.0-beta.3.
