### ISSUE TITLE
Cannot publish payloads with a size of the order 64K using WebSockets

### ISSUE THREAD

**Issue by tiefschneeteufel** [emqtt/emqttd#642]
Client fails to send message, with no error messages or logging on the emqttd side, for messages greater than 64K in length.

Client trace message looks like this:

Object {severity: "Debug", message: ""Client._disconnected"8"AMQJS0008I Socket closed.""}

**Comment by emqplus** [comment]
Please tune max_packet_size: http://emqtt.io/docs/config.html#mqtt-packet-and-clientid

**Comment by tiefschneeteufel** [comment]
I already changed max_packet_size and it made no difference. I tried making max_packet_size very small and published some messages using a command-line client (i.e. using TCP not WebSockets) and got errors that showed up in the emqttd console. Making max_packet_size very large did not make my WebSocket problem go away.

I believe that there is a problem with the WebSockets support which means that messages with large payloads do not reach the code responsible for implementing broker behaviour, hence changing max_packet_size has no effect in this case.

**Comment by tiefschneeteufel** [comment]
Perhaps changing sockopts would make a difference?

**Comment by emqplus** [comment]
@tiefschneeteufel, No. @huangdan please reproduce this issue.

**Comment by tiefschneeteufel** [comment]
<html>
<body>
    <h1>emqttd websocket test</h1>
    <input id="length" type="tel" name="length" value="65536">
    <button id="button" type="button">Submit</button>
    <p id="status"></p>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js" type="text/javascript"></script>
    <script>
        var length = document.getElementById("length");    
        var button = document.getElementById("button");
        var client;
        button.addEventListener("click", function() {
            var l = Number(length.value);
            document.getElementById("status").innerHTML = "In flight";
            var payload = new Uint8Array(l);            
            var message = new Paho.MQTT.Message(payload);
            message.destinationName = "/World";
            client = new Paho.MQTT.Client("127.0.0.1", Number(8083), "/mqtt", 'client-' + Math.random().toString(36).slice(-6));
            client.trace = function(msg) {
                if (msg.message === '"Client._disconnected"8"AMQJS0008I Socket closed."') {
                    document.getElementById("status").innerHTML = "FAILED :(";
                }
                console.log("trace = ", msg.message);            
            };
            client.onMessageDelivered = function() {
                document.getElementById("status").innerHTML = "Delivered";
            }
            client.connect({
                onSuccess: function () {
                    client.send(message);
                }
            });
        });
        
    </script>


</body>

</html>

![emqttd_websocket_test_failed](https://cloud.githubusercontent.com/assets/10061706/17597176/02464792-5ff5-11e6-93f9-2a046ff868d8.png)
![emqttd_websocket_test_delivered](https://cloud.githubusercontent.com/assets/10061706/17597175/0242651e-5ff5-11e6-9310-ca0703ed8a9a.png)
