### ISSUE TITLE
Cannot publish payloads with a size of the order 64K using WebSockets

### ISSUE THREAD

**Issue by tiefschneeteufel** [emqtt/emqttd#643]
(Reopening #642 ) Client fails to send message, with no error messages or logging on the emqttd side, for messages greater than 64K in length.

Client trace message looks like this: 

Object {severity: "Debug", message: ""Client._disconnected"8"AMQJS0008I Socket closed.""}

There are no trace messages or logging from emqttd. I already changed max_packet_size and it made no difference. I tried making max_packet_size very small and published some messages using a command-line client (i.e. using TCP not WebSockets) and got errors that showed up in the emqttd console. Making max_packet_size very large did not make my WebSocket problem go away.

I believe that there is a problem with the WebSockets support which means that messages with large payloads do not reach the code responsible for implementing broker behaviour, hence changing max_packet_size has no effect in this case.

**Comment by emqplus** [comment]
@tiefschneeteufel, the issue has been fixed in mochiweb project: https://github.com/emqtt/mochiweb/commit/67f905dc027d30e17af7a82362f21206844253bd#diff-0038a9e9f03f48e77c034718721e8400L225
