### ISSUE TITLE
Webhook support

### ISSUE THREAD

**Issue by krvarma** [emqtt/emqttd#647]
I would like to implement a system that call a Webhook or execute a piece of code when a user posts a message to a particular topic. User can configure this using his dashboard. So there will be lots of topics to watch. I want to implement this in Node.js

Since subscribing multi level # is an anti-pattern this is definitely not a solution. I was thinking about writing a plugin which send all messages to Kafka/RabbitMQ and then process the queue from another Node.js application. 

Could someone suggest a a method that is scalable and does not effect the performance?

**Comment by emqplus** [comment]
Hi @krvarma, emqtt->Kafka/RabbitMQ is too complicated for Webhook support, I think. I suggest streaming MQTT messages to Redis: emqtt->Redis->Node.js(Webhook)

**Comment by krvarma** [comment]
Thank you @emqplus for your suggestion and really sorry for the late reply. I was engaged in a personal matter these days and didn't get time to check the reply.

In another thread I read in 2.x it is planned to support message store in MongoDB, Reds, etc... and also MQTT Streaming to Kafka. Does the message store in Redis supports PUBLISH also?

**Comment by emqplus** [comment]
The Web Hook Plugin has been released in version 2.2-beta.1: https://github.com/emqtt/emq-web-hook
