### ISSUE TITLE
http publish api config

### ISSUE THREAD

**Issue by shsjshentao** [emqtt/emqttd#648]
the following config in http publish api has problem

access	允许访问的IP地址段设置，例如: [{allow, “192.168.1.0/24”}]

only config [{deny , all}] works properly

however i set [{allow, "ip"}] format, all host can publish. it doesnt work.

**Comment by emqplus** [comment]
@shsjshentao, please append '{deny, all}':
```
[{allow, “192.168.1.0/24”}, {deny, all}]
```
or
```
[{allow, "127.0.0.1"}, {deny, all}]
```
