### ISSUE TITLE
Send message directly to client

### ISSUE THREAD

**Issue by danipl** [emqtt/emqttd#653]
First at all, I'm gonna expose my current scenario to everyone can understand it better. 

I'm working with RabbitMQ at the moment, with MQTT plugin sets up. I'm thinking change my current RabbitMQ instances for Emqtt (QoS2, cluster. and so on...), but I can't find in your official documentation this feature. Currently, in RabbitMQ, clients are subscribing to one ordinary MQTT topic, for example "/global/${country}/notification", but in RabbitMQ, I can send directly one message for each client through his clientId.

There is in Emqtt this feature?, if it's not, I could subscribing from each client to two topics, for example, the current topic and another for direct messages for client purposes, "/user/${clientId}/inbox" and (THE KEY AND MOST IMPORTANT), these personal topics have issues and are heavy to kepping them talking about performance?. Any other solution better?

Thank you very much for your work.

**Comment by emqplus** [comment]
@danipl, The 'subscription' module in 1.1.x release could help subscribe a 'clientid' topic for each client, for example:

```
    %% Modules
    {modules, [
      
        %% Subscribe topics automatically when client connected
        {subscription, [
            %% $c will be replaced by clientid
            {"$c", 1}
        ]}
```
