### ISSUE TITLE
epmd -daemon not stopped after executing ./emqttd stop command

### ISSUE THREAD

**Issue by seamanIncloud** [emqtt/emqttd#659]
I just downed the latest release version of emqtt and trying to run it on ubuntu 14.04.

starting with ./emqttd start is ok, but when trying the stop the service with

./emqttd stop

when executing ps aux, all other emqttd process are killed except

/opt/emqttd/erts-7.3/bin/epmd -daemon

this process is not killed. Is this normal?

**Comment by congleetea** [comment]
epmd is not just for emqttd,  when you start any erlang application, it will be started and listen other node's communicatioin.

**Comment by emqplus** [comment]
@seamanIncloud, The 'epmd' daemon should not be killed manually.

Docs about distributed Erlang: http://erlang.org/doc/reference_manual/distributed.html
