### ISSUE TITLE
can you tell me what the port 58785 use for ?

### ISSUE THREAD

**Issue by Yaoguais** [emqtt/emqttd#660]
I want to deploy a cluster use a single machine,
then I need to deal with port bind conflict.
so I found this:

```
tcp        0      0 0.0.0.0:58785               0.0.0.0:*                   LISTEN      9150/beam.smp       off (0.00/0/0)
tcp        0      0 0.0.0.0:18083               0.0.0.0:*                   LISTEN      9150/beam.smp       off (0.00/0/0)
```

So I use my script to find out which file contain 58785, but never found.
then I use github to search, use this link "https://github.com/search?q=org%3Aemqtt+58785",
and without result too.

So, can you help me about this ?

**Comment by Yaoguais** [comment]
OK, when I restart the server, it change to a new port
```
tcp        0      0 0.0.0.0:52233               0.0.0.0:*                   LISTEN      10060/beam.smp      off (0.00/0/0)
```

It could be a feature 😊

**Comment by Yaoguais** [comment]
is this ?
http://emqtt.com/docs/cluster.html#cluster-firewall

**Comment by emqplus** [comment]
@Yaoguais, docs about distributed erlang system: http://erlang.org/doc/reference_manual/distributed.html
