### ISSUE TITLE
About ClientID Authentication support with database plugin

### ISSUE THREAD

**Issue by liszhu** [emqtt/emqttd#661]
HI there,

As checking the documentation, it seems that the database (MySQL , PostgreSQL, etc. ) Authentication/ACL Plugin does not support authentication with MQTT client ID.  May I know which way I could use to implement client ID authentication in case I have a large number of clients.

Thanks.

Lee

**Comment by turtleDeng** [comment]
Thank you, we will consider your plan!

**Comment by emqplus** [comment]
This feature has been implemented in 2.3.1
