### ISSUE TITLE
How to determine whether the specified user online

### ISSUE THREAD

**Issue by fanyebo** [emqtt/emqttd#666]

**Comment by josephduchesne** [comment]
The HTTP API can tell you this through /api/sessions or /api/clients.

Alternatively, you could publish a static topic to MQTT for example /users/USER_NAME/online **true**, when the client comes online, and **false** as part of the last will and testament set while connecting (see details [here](http://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament))

**Comment by huangdan** [comment]
if you get client online/offline status, maybe the doc help for you http://emqtt.io/docs/v2/guide.html#sys-topics
