### ISSUE TITLE
Configuring emqttd from environment variables

### ISSUE THREAD

**Issue by danielrhodes** [emqtt/emqttd#667]
I would like to set certain configuration variables from the environment, specifically the HTTP/S port. Is there a way to do this currently? I did not see anything in the docs, but it seems like it would be useful in many situations.

**Comment by emqplus** [comment]
@danielrhodes, it's okay:) Plan to enhance the emqttd_conf module in 2.x release to support OS environment.

**Comment by danielrhodes** [comment]
@emqplus Thanks Feng! Is that the file I should be looking at? I might as well give it a shot, and if it's any good I'll make a PR.

**Comment by emqplus** [comment]
@danielrhodes OS Environment Variables have been supported in 2.0-rc.3 release: http://emqtt.io/docs/v2/config.html#os-environment-variables

Env                                                | Description
--------------------------------|--------------------------------------
EMQ_NODE_NAME                      | Erlang node name
EMQ_NODE_COOKIE	              | Cookie for distributed erlang node
EMQ_MAX_PORTS	                      | Maximum number of opened sockets
EMQ_TCP_PORT	                      | MQTT TCP Listener Port, Default: 1883
EMQ_SSL_PORT	                      | MQTT SSL Listener Port, Default: 8883
EMQ_HTTP_PORT	                      | HTTP/WebSocket Port, Default: 8083
EMQ_HTTPS_PORT	              | HTTPS/WebSocket Port, Default: 8084
