### ISSUE TITLE
What's the recommonded scenario for choosing OS type in Clustering?

### ISSUE THREAD

**Issue by pumpindex** [emqtt/emqttd#668]
Here we need to choose a scenario for Clustering. you can consider two different scenarios for clustering;
Case-1: The Operating systems in Cluster nodes are same. (E.g. All of them are in CentOs)
Case-2: The Operating systems in Cluster nodes are NOT Same.one of them is in CentOs and the others in Windows.
If we imagine, we have not hardware problem and we are neutral in war of Windows and Linux, Do you think, choosing OS type of cluster nodes in case#2 is better than case#1?
I think that same OS types may be lead to same failure chances and bug in running time but in choosing different OS types, it may be lead to safer condition because the MQTT code run in different environment variables and the failure chance (e.g. memory leak and memory management) is not same.
What’s your opinion?

**Comment by emqplus** [comment]
Case-1. Sure. For the ./bin/emqttd_ctl CLI cannot work on windows:( We will try to fix this issue later.

**Comment by ioeverything** [comment]
Generally, you recommend to use different os types or same e.g ubuntu centos and...?
