### ISSUE TITLE
[2.0 beta1] FORMAT ERROR: "~s PUBLISH to ~s: ~p"

### ISSUE THREAD

**Issue by lpfeup** [emqtt/emqttd#671]
I am getting this error on every PUBLISH, since i updated to 2.0-beta1:

<code>
2016-09-01 10:42:18.678 <0.1116.0> [info] FORMAT ERROR: "~s PUBLISH to ~s: ~p" [{<<"paho/123">>,<<"anon">>},<<"data/b16bcbdd-f883-484b-9c0d-234cc03133a8">>,<<"{\"timestamp\": 1472737338000}">>]
</code>

I think it may be related to [commit d0be556](https://github.com/emqtt/emqttd/commit/d0be556f337ed49d4a8b234cca01f96fd040714b) ("2.0 - improve design of session and hook "):

<code> src/emqttd_message.erl</code>

<code>
 from_packet(Username, ClientId, Packet) ->
     Msg = from_packet(Packet),
     Msg#mqtt_message{from = ClientId, sender = Username}.
</code>
changed to:
<code>
 from_packet(Username, ClientId, Packet) ->
     Msg = from_packet(Packet),
     Msg#mqtt_message{from = {ClientId, Username}}.
</code>

**Comment by emqplus** [comment]
@lpfeup, fixed. The 'from' field of mqtt_message record has been changed in 2.0.
