### ISSUE TITLE
eMQTT vs RabbitMQ

### ISSUE THREAD

**Issue by drasko** [emqtt/emqttd#675]
Hello,
I saw a small comparison here: https://github.com/emqtt/emqttd/wiki/emqttd-and-rabbitmq

It is not clear for this how eMQTT compares to RabbitMQ and what extra features does it bring (in the terms of MQTT).

RabbitMQ has now officially MQTT support alongside with MQTT-over-Websocket. But more importantly, it can output all MQTT messages of a broker into AMQP queues - so no need to subscribe to `#` wildcard for persistence (if I get the things right).

It is also highly scalable and efficient, used in the industry and an administrator dashboard and CLI.

I am interested - where does eMQTT does better than RabbitMQ and why should one use eMQTT over RabbitMQ?

**Comment by rock59** [comment]
Six months ago , I tested both for a high volume Android application. eMQTT scales well and can handle high volume of client connections (300k in my case) . eMQTT Authentication and Authorization plugins are nice and flexible and plugin development for eMQTT is easy

I could not reach 300k client connections with RabbitMQ MQTT module on a single box. RabbitMQ does not provide flexible Authentication and Authorization modules and module development for RabbitMQ is not easy... 

If you don't need an enterprise message queue, use eMQTT and enjoy it ;-)

**Comment by drasko** [comment]
@rock59 there are auth plugins in RabbitMQ: http://www.rabbitmq.com/access-control.html. But I would agree that it looks like dev and config for eMQTT is simpler

I do not really need message queue at this moment, but I am afraid that scaling any MQTT broker with the need to store messages in DB will demand some message queue (maybe Kafka), as DB client will not be able to cope with the load. But the moment you start adding MQs to the eMQTT it becomes more complicated solution to RabbitMQ, IMHO.

So conclusion would be - supporting more concurrent connections and simpler to develop/set-up?

**Comment by drasko** [comment]
@rock59 btw - does number of concurrent connections really matter? Linux box can theoretically accept huge number of conncetions, as these are nothing but an opened sockets. What really matters is throughput - i.e. number and size of the messages per second: http://stackoverflow.com/questions/10087396/mqtt-mosquitto-linux-connection-limit

What was the throughput in your case (how many messages per second and what was the size of the messages)?

**Comment by rock59** [comment]
@drasko In my case, throughput is not very important.. The throughput with QoS 0 and 1 kb message size was about 10k/s .. It was not a stress test..
I need eMQTT Authentication and Authorization flexibility thus I chose eMQTT

**Comment by rock59** [comment]
@drasko mosquitto does not use epoll(Linux) or kqueue(BSD) or IOCP(windows) for socket event  notification, so mosquitto can't scale well to thousands of concurrent connections even with a well tuned Linux box

**Comment by srijanmishra** [comment]
@rock59 I second you on this one. I used both for an Android application and emqtt performed far better than RabbitMQ (around 1.5 times more connections). BTW can you please share the machine configuration you used to reach 300K client connections?

**Comment by drasko** [comment]
@rock59 @srijanmishra I think that eMQTT should be more compared to VerneMQ then. Here is some interesting info and benchmarks: https://github.com/erlio/vernemq/issues/83

Also, I see that they embedded Lua, so plugin writing becomes really simple: https://github.com/erlio/vmq_diversity

**Comment by rock59** [comment]
@srijanmishra Unfortunately I don't have configs right now ;-( 
I used official documents to configure the servers and Ubuntu server 15.04 on 3 bare metal servers (one for emqttd and two for clients) 

http://emqtt.io/docs/v2/tune.html
https://github.com/emqtt/emqtt_benchmark

**Comment by rock59** [comment]
@drasko  VerneMQ is nice and has interesting features although It seems that VerneMQ has issues with high volume concurrent connections..

**Comment by drasko** [comment]
@rock59  I have no idea, I never used it. They are showing 200k in their benchmarks as I can see.

**Comment by srijanmishra** [comment]
@rock59 I meant the processor details, RAM, storage and other such specifications 😄

**Comment by rock59** [comment]
@srijanmishra I don't have access to the servers in the company I worked for and the results right now so I can't provide much details.Sorry

3 1U rackmount servers (CPU: Xeon, 8 core, RAM:128 GB, SSD , 10 GB NIC)

1KB QoS 0 message
300K Clients connected and 300K topics (1 topic per client)
up to 10K messages/s out (the application requirement)
 
THAT WAS NOT A STRESS TEST

**Comment by srijanmishra** [comment]
@rock59 No problem I was just curious. Thanks!!

**Comment by dergraf** [comment]
@rock59, @drasko VerneMQ developer here, the issues with the high CPU usage with idling connections is gone since 0.13.1. With proper OS and broker configuration, given enough CPU and RAM, 300K connections on a single node isn't a problem.
