### ISSUE TITLE
Compare brokers

### ISSUE THREAD

**Issue by edgiru** [emqtt/emqttd#676]
Hello.
this is emqtt dynamic topics support?
https://github.com/mqtt/mqtt.github.io/wiki/server-support

what are the advantages over other brokers?

**Comment by emqplus** [comment]
@edgiru, Yes. I updated the wiki. emqttd(EMQ) is the most scalable MQTT broker deployed in production. 900K for example:

![100m](https://cloud.githubusercontent.com/assets/11869/18407999/2438428a-7754-11e6-91f4-19eddde58b88.jpg)
