### ISSUE TITLE
Where messages store?

### ISSUE THREAD

**Issue by mikybone** [emqtt/emqttd#677]
Hi
I produce 200k messages, all sent successfully, some clients subscribe then offline them next begin send messages and when finished offlines became online and get all messages,  **so all messages exists in Ram**, I check with observer ets and mnesia but not exist 200k objects in these.

where messages store?

**Comment by huangdan** [comment]
publish retained message and configure the expiration in etc/emqttd.conf
BTW we will release 'EmqPlus' product this month to help users store MQTT messages into DB

**Comment by drasko** [comment]
@huangdan when constructing DB persistence plugin I think that this should be taken into account: https://github.com/erlio/vernemq/issues/197

**Comment by mikybone** [comment]
@huangdan
thanks for replay.
I think you not understand my notice.
i not intent to change retained message setting. default config is good.
i say all **not delivered messages** exists in Memory, but i enter observer:start() nether ets nor mnesia didn't exist 200k objects in lists.

**200k messages where putted(there is)?**
