### ISSUE TITLE
v2.0版本无法执行执行cluster join

### ISSUE THREAD

**Issue by lmtoo** [emqtt/emqttd#680]
包：emqttd-centos64-v2.0-beta.1-20160830.zip
系统环境：LSB Version: :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description: CentOS Linux release 7.2.1511 (Core)
Release: 7.2.1511
Codename: Core

集群中每台集群的node节点配置正确，也可以正常start；
但是执行cluster join之后，执行该命令的这个节点就会瘫痪掉

**Comment by huangdan** [comment]
The 'topic' tab name has been changed in 2.0
