### ISSUE TITLE
how to check who login with SSL/TLS

### ISSUE THREAD

**Issue by jhaoheng** [emqtt/emqttd#682]
Does anyone know how to watch this info on emqttd?

I do not see this info on emqttd console.

thank you so much.

**Comment by huangdan** [comment]
Logger of emqttd broker is implemented by ‘lager’ application, which is configured in releases/2.0/sys.config
doc about log level  
en sites：http://emqtt.io/docs/v2/config.html#log-level-and-file；
cn sites：http://emqtt.com/docs/v2/config.html#lager

**Comment by jhaoheng** [comment]
Hi @huangdan 

Thanks.
I still don't know how to assign it
I know the structure of 'lager'
But how to get 'login info' tag to help me save it to 'xxx.log'

**Comment by huangdan** [comment]
@jhaoheng please refer to Add bold text 
{handlers, [
  #   {lager_console_backend, info},

    {lager_file_backend, [
        {formatter_config, [time, " ", pid, " [",severity,"] ", message, "\n"]},
        **{file, "log/emqttd_info.log"},**
        **{level, info},**
        {size, 104857600},
        {date, "$D0"},
        {count, 30}
    ]},

    {lager_file_backend, [
        {formatter_config, [time, " ", pid, " [",severity,"] ", message, "\n"]},
        {file, "log/emqttd_error.log"},
        {level, error},
        {size, 104857600},
        {date, "$D0"},
        {count, 30}
    ]}
]}
the info/error log are save to emqttd/log

**Comment by jhaoheng** [comment]
@huangdan Thanks this info.

I try this method, but it still no show ssl/tls info.
`formatter_config` arguments is i needed. I dont find any info.args on docs.

Thanks
