### ISSUE TITLE
Use wildcard in buildin acl control?

### ISSUE THREAD

**Issue by happyyst** [emqtt/emqttd#684]
in acl.config, I add this line:  {allow, all, subscribe, ["/device/+/%c/#"]}  
in emqtt log, I got this : Client ACCF23E19124.... Cannot SUBSCRIBE [{<<"/device/+/ACCF23E19124/#">>,2}] for ACL Deny .
how to slove this with out using acl plugin?

**Comment by turtleDeng** [comment]
hi, “%c” is not allowed  in mqtt wildcard

**Comment by happyyst** [comment]
in this issue [https://github.com/emqtt/emqttd/issues/578](url), the author said, %c and %u is allowed, where is the issue point? 
@turtleDeng

**Comment by emqplus** [comment]
@happyyst the variables are '$u', '$c' in 1.x release,  and '%u', '%c' in 2.0-beta.2 release.
