### ISSUE TITLE
retain message getting multiple times

### ISSUE THREAD

**Issue by numbertank** [emqtt/emqttd#687]
Hi,

I have send retain message multiple times with Retained flag true from dashboard (websocket).
and getting multiple message from client side.

topic:
user/706489/online
value : 0 or 1

emqttd version : 1.1

**Comment by huangdan** [comment]
@numbertank you can read http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718103
