### ISSUE TITLE
ACL Cannot work

### ISSUE THREAD

**Issue by dadait** [emqtt/emqttd#688]
我做了如下配置进行访问控制，但是没起效果，dadait用户依然可以subscribe 主题/user下的任何主题。
不知道这个配置是否有什么问题？

```
{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.

{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.

{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.

{deny, {user, "dadait"}, subscribe, ["/user/#"]}.

{allow, all}.
```

**Comment by turtleDeng** [comment]
你好：
  你查看一下你的etc/emqttd.conf 配置默认使用的是那个acl

**Comment by turtleDeng** [comment]
You check etc/emqttd.conf, acl default is to use anonymous way

**Comment by emqplus** [comment]
Please comment line '{auth, anonymous, []}.' in etc/emqttd.conf if you deployed 2.x release.
