### ISSUE TITLE
emqttd failed to start within 15 seconds

### ISSUE THREAD

**Issue by Venorcis** [emqtt/emqttd#689]
I'm on CentOS 6.8, running the latest EMQ beta (2.0-beta2). 
I can use '/bin/emqttd console' to successfully start the broker. However, when using '/bin/emqttd start' (or 'service emqttd start'), I get an error report "emqttd failed to start within 15 seconds". The error logs, in contrast, show the expected output (i.e. the same as with the console command); there are no errors. The service is still stopped after this though.

I would also like to note that very often a left-over 'run_erl' process remains running after this, which I have to kill manually by its PID in order to free up the port that is used by this 'ghost' instance of EMQ; '/bin/emqttd stop' does not kill this process.

**Comment by emqplus** [comment]
Hi @Venorcis, Did you change the node name in releases/2.0/vm.args?

**Comment by Venorcis** [comment]
Hey @emqplus, I did not notice this file moved from the etc folder, so my puppet installation overlooked this. Still weird no errors were generated at all whilst obviously the start-up did not complete successfully.
