### ISSUE TITLE
emqtt failed to start on windows server 2012

### ISSUE THREAD

**Issue by sgdba** [emqtt/emqttd#692]
version:  emqttd-windows-v2.0-beta.2-20160910
cli:  emqttd console

the follow error occured:
exception exit: {bad_return,
                     {{emqttd_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,{error,enoent}},
                        [{gen_conf,init,1,
                          [{file,
                            "c:/Users/songzigw/Desktop/emqttd-relx/deps/gen_conf/src/gen_conf.erl"},
                           {line,28}]},
                         {emqttd_app,start,2,
                          [{file,
                            "c:/Users/songzigw/Desktop/emqttd-relx/deps/emqttd/src/emqttd_app.erl"},
                           {line,45}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,273}]}]}}}}
      in function  application_master:init/4 (application_master.erl, line 134)

**Comment by emqplus** [comment]
@sgdba,build from source?

**Comment by huangdan** [comment]
@sgdba 
Start the broker in console mode:
.\bin\emqttd console
not emqttd console

**Comment by sgdba** [comment]
@huangdan 
Ok, it works. Thanks
