### ISSUE TITLE
Create ram_node on emqttd

### ISSUE THREAD

**Issue by Moolica23** [emqtt/emqttd#695]
I'm trying to create 8 ram_nodes on one host and cluster them. but i don't find any command or config file to do so.

**Comment by behrad** [comment]
Mohammad Jan,
You can find how to join nodes here http://docs.emqtt.com/en/latest/cluster.html

**Comment by BADBDY23** [comment]
Dash Behrad, 
I've studied the documentation, but i can't find a way to create ram_node. the documentations show the way to create disc_node

**Comment by behrad** [comment]
I'm afraid Mohammad, you will need at least one disc node to be able to setup cluster. I again refer you to read documentation in more details.

**Comment by BADBDY23** [comment]
I have no problems to create discnode, but i can't create ram_node.

**Comment by behrad** [comment]
> but i can't create ram_node

are you getting any errors?
