### ISSUE TITLE
offline message might lose sometime

### ISSUE THREAD

**Issue by njnuwjq** [emqtt/emqttd#698]
test with cleansession=false, session timeout = 0

on mqtt msg:: means subscriber receive the message
MSG:send @   means published @ the time

anyone could help look into this problem? thanks

==============log=============
D:/GOPATH/src/test_paho/test_paho.exe  [D:/GOPATH/src/test_paho]
opts::: &{[tcp://121.40.251.82:1883] go-simple-2223   false true false  [] 0 false 0 false {<nil> <nil> [] map[] <nil> <nil> []  0 <nil> false [] false false [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] <nil> 0 0 [] false 0 {{0 0} 0} {{0 0} 0 0 0 0} []} 30s 10s 0s 10m0s true <nil> 0x401550 <nil> 0x47e7a0 0s 100}
client start
subscriber
on mqtt msg::%!recv @ 2016-09-21 10:13:20.5214243 
MSG:send @ 2016-09-21 10:11:20"}
on mqtt msg::%!recv @ 2016-09-21 10:13:21.5264818 
MSG:send @ 2016-09-21 10:11:30"}
on mqtt msg::%!recv @ 2016-09-21 10:13:31.4990522 
MSG:send @ 2016-09-21 10:11:40"}
on mqtt msg::%!recv @ 2016-09-21 10:13:41.5096247 
MSG:send @ 2016-09-21 10:11:50"}
on mqtt msg::%!recv @ 2016-09-21 10:13:51.5211974 
MSG:send @ 2016-09-21 10:12:00"}
on mqtt msg::%!recv @ 2016-09-21 10:14:01.53277 
MSG:send @ 2016-09-21 10:12:10"}
on mqtt msg::%!recv @ 2016-09-21 10:14:11.4473371 
MSG:send @ 2016-09-21 10:12:20"}
on mqtt msg::%!recv @ 2016-09-21 10:14:21.4569096 
MSG:send @ 2016-09-21 10:12:30"}
on mqtt msg::%!recv @ 2016-09-21 10:14:31.482483 
MSG:send @ 2016-09-21 10:12:40"}
on mqtt msg::%!recv @ 2016-09-21 10:14:41.4980559 
MSG:send @ 2016-09-21 10:12:50"}
on mqtt msg::%!recv @ 2016-09-21 10:14:51.5046282 
MSG:send @ 2016-09-21 10:13:00"}
on mqtt msg::%!recv @ 2016-09-21 10:15:01.5162008 
MSG:send @ 2016-09-21 10:13:10"}
on mqtt msg::%!recv @ 2016-09-21 10:15:11.5277735 
MSG:send @ 2016-09-21 10:13:20"}
on mqtt msg::%!recv @ 2016-09-21 10:15:21.538346 
MSG:send @ 2016-09-21 10:13:30"}
on mqtt msg::%!recv @ 2016-09-21 10:15:31.5499187 
MSG:send @ 2016-09-21 10:13:40"}
on mqtt msg::%!recv @ 2016-09-21 10:15:41.5604913 
MSG:send @ 2016-09-21 10:13:50"}
on mqtt msg::%!recv @ 2016-09-21 10:15:51.5710638 
MSG:send @ 2016-09-21 10:14:00"}

断链时候消息收到

on mqtt msg::%!recv @ 2016-09-21 10:16:28.3471673 
MSG:send @ 2016-09-21 10:14:10"}
on mqtt msg::%!recv @ 2016-09-21 10:16:28.5551792 
MSG:send @ 2016-09-21 10:14:20"}
on mqtt msg::%!recv @ 2016-09-21 10:16:28.5551792 
MSG:send @ 2016-09-21 10:14:30"}
on mqtt msg::%!recv @ 2016-09-21 10:16:31.6203545 
MSG:send @ 2016-09-21 10:14:40"}
on mqtt msg::%!recv @ 2016-09-21 10:16:41.6269269 
MSG:send @ 2016-09-21 10:14:50"}
on mqtt msg::%!recv @ 2016-09-21 10:16:51.6384995 
MSG:send @ 2016-09-21 10:15:00"}
on mqtt msg::%!recv @ 2016-09-21 10:17:01.6510722 
MSG:send @ 2016-09-21 10:15:10"}
on mqtt msg::%!recv @ 2016-09-21 10:17:11.6616447 
MSG:send @ 2016-09-21 10:15:20"}
on mqtt msg::%!recv @ 2016-09-21 10:17:21.6722173 
MSG:send @ 2016-09-21 10:15:30"}
on mqtt msg::%!recv @ 2016-09-21 10:17:31.6827899 
MSG:send @ 2016-09-21 10:15:40"}
on mqtt msg::%!recv @ 2016-09-21 10:17:41.7123635 
MSG:send @ 2016-09-21 10:15:50"}
on mqtt msg::%!recv @ 2016-09-21 10:17:51.7049351 
MSG:send @ 2016-09-21 10:16:00"}
on mqtt msg::%!recv @ 2016-09-21 10:18:01.7165077 
MSG:send @ 2016-09-21 10:16:10"}
on mqtt msg::%!recv @ 2016-09-21 10:18:11.7280803 
MSG:send @ 2016-09-21 10:16:20"}
on mqtt msg::%!recv @ 2016-09-21 10:18:21.739653 
MSG:send @ 2016-09-21 10:16:30"}
on mqtt msg::%!recv @ 2016-09-21 10:18:31.7512256 
MSG:send @ 2016-09-21 10:16:40"}
on mqtt msg::%!recv @ 2016-09-21 10:18:41.7607981 
MSG:send @ 2016-09-21 10:16:50"}
on mqtt msg::%!recv @ 2016-09-21 10:18:51.7723707 
MSG:send @ 2016-09-21 10:17:00"}
on mqtt msg::%!recv @ 2016-09-21 10:19:01.7829433 
MSG:send @ 2016-09-21 10:17:10"}
on mqtt msg::%!recv @ 2016-09-21 10:19:11.7935159 
MSG:send @ 2016-09-21 10:17:20"}
on mqtt msg::%!recv @ 2016-09-21 10:19:21.8040885 
MSG:send @ 2016-09-21 10:17:30"}
on mqtt msg::%!recv @ 2016-09-21 10:19:31.8156611 
MSG:send @ 2016-09-21 10:17:40"}
on mqtt msg::%!recv @ 2016-09-21 10:19:41.8272337 
MSG:send @ 2016-09-21 10:17:50"}
on mqtt msg::%!recv @ 2016-09-21 10:19:51.8378063 
MSG:send @ 2016-09-21 10:18:00"}
on mqtt msg::%!recv @ 2016-09-21 10:20:01.8533792 
MSG:send @ 2016-09-21 10:18:10"}
on mqtt msg::%!recv @ 2016-09-21 10:20:11.8609516 
MSG:send @ 2016-09-21 10:18:20"}
on mqtt msg::%!recv @ 2016-09-21 10:20:21.8755244 
MSG:send @ 2016-09-21 10:18:30"}
on mqtt msg::%!recv @ 2016-09-21 10:20:31.8950974 
MSG:send @ 2016-09-21 10:18:40"}
on mqtt msg::%!recv @ 2016-09-21 10:20:41.9026698 
MSG:send @ 2016-09-21 10:18:50"}

断链时候消息  丢失

on mqtt msg::%!recv @ 2016-09-21 10:22:21.9093899 
MSG:send @ 2016-09-21 10:20:30"}
on mqtt msg::%!recv @ 2016-09-21 10:22:31.9239627 
MSG:send @ 2016-09-21 10:20:40"}
on mqtt msg::%!recv @ 2016-09-21 10:22:41.9345353 
MSG:send @ 2016-09-21 10:20:50"}
on mqtt msg::%!recv @ 2016-09-21 10:22:51.9501081 
MSG:send @ 2016-09-21 10:21:00"}
on mqtt msg::%!recv @ 2016-09-21 10:23:01.9566805 
MSG:send @ 2016-09-21 10:21:10"}

断链时候消息 丢失

on mqtt msg::%!recv @ 2016-09-21 10:23:42.002971 
MSG:send @ 2016-09-21 10:21:50"}
on mqtt msg::%!recv @ 2016-09-21 10:23:52.0185438 
MSG:send @ 2016-09-21 10:22:00"}
on mqtt msg::%!recv @ 2016-09-21 10:24:02.0281164 
MSG:send @ 2016-09-21 10:22:10"}

断链时候消息收到

on mqtt msg::%!recv @ 2016-09-21 10:24:28.7996476 
MSG:send @ 2016-09-21 10:22:21"}
on mqtt msg::%!recv @ 2016-09-21 10:24:29.0176601 
MSG:send @ 2016-09-21 10:22:31"}
on mqtt msg::%!recv @ 2016-09-21 10:24:32.0628342 
MSG:send @ 2016-09-21 10:22:41"}
on mqtt msg::%!recv @ 2016-09-21 10:24:42.0724068 
MSG:send @ 2016-09-21 10:22:51"}
on mqtt msg::%!recv @ 2016-09-21 10:24:52.0839794 
MSG:send @ 2016-09-21 10:23:01"}
on mqtt msg::%!recv @ 2016-09-21 10:25:02.095552 
MSG:send @ 2016-09-21 10:23:11"}

断链时候消息收到

on mqtt msg::%!recv @ 2016-09-21 10:26:21.156074 
MSG:send @ 2016-09-21 10:24:21"}
on mqtt msg::%!recv @ 2016-09-21 10:26:22.1891331 
MSG:send @ 2016-09-21 10:24:31"}
on mqtt msg::%!recv @ 2016-09-21 10:26:32.1967055 
MSG:send @ 2016-09-21 10:24:41"}
on mqtt msg::%!recv @ 2016-09-21 10:26:42.2092782 
MSG:send @ 2016-09-21 10:24:51"}

on mqtt msg::%!recv @ 2016-09-21 10:27:32.261141 
MSG:send @ 2016-09-21 10:25:41"}
on mqtt msg::%!recv @ 2016-09-21 10:27:42.2717136 
MSG:send @ 2016-09-21 10:25:51"}
on mqtt msg::%!recv @ 2016-09-21 10:27:52.2902866 
MSG:send @ 2016-09-21 10:26:01"}
on mqtt msg::%!recv @ 2016-09-21 10:28:02.3018592 
MSG:send @ 2016-09-21 10:26:11"}
on mqtt msg::%!recv @ 2016-09-21 10:28:12.3084316 
MSG:send @ 2016-09-21 10:26:21"}
on mqtt msg::%!recv @ 2016-09-21 10:28:22.3220043 
MSG:send @ 2016-09-21 10:26:31"}
on mqtt msg::%!recv @ 2016-09-21 10:28:32.3335769 
MSG:send @ 2016-09-21 10:26:41"}
on mqtt msg::%!recv @ 2016-09-21 10:28:42.3711511 
MSG:send @ 2016-09-21 10:26:51"}

on mqtt msg::%!recv @ 2016-09-21 10:28:52.3577223 
MSG:send @ 2016-09-21 10:27:01"}

on mqtt msg::%!recv @ 2016-09-21 10:31:19.3121276 
MSG:send @ 2016-09-21 10:28:21"}
on mqtt msg::%!recv @ 2016-09-21 10:31:19.3171279 
MSG:send @ 2016-09-21 10:28:31"}
on mqtt msg::%!recv @ 2016-09-21 10:31:19.320128 
MSG:send @ 2016-09-21 10:28:41"}
on mqtt msg::%!recv @ 2016-09-21 10:31:19.3241283 
MSG:send @ 2016-09-21 10:28:51"}
on mqtt msg::%!recv @ 2016-09-21 10:31:19.3241283 
MSG:send @ 2016-09-21 10:29:01"}
on mqtt msg::%!recv @ 2016-09-21 10:31:19.3241283 
MSG:send @ 2016-09-21 10:29:11"}
on mqtt msg::%!recv @ 2016-09-21 10:31:19.3261284 
MSG:send @ 2016-09-21 10:29:21"}
on mqtt msg::%!recv @ 2016-09-21 10:31:22.5243113 
MSG:send @ 2016-09-21 10:29:31"}

**Comment by emqplus** [comment]
Invalid issue. Session timeout should not be 0.
