### ISSUE TITLE
Redis Auth 密码无效

### ISSUE THREAD

**Issue by dadait** [emqtt/emqttd#700]
EMQTT Server Ubuntu Version 1.1.3
加载了emqttd_plugin_redis 插件，使用的插件默认配置，password_hash为sha256。
然后在Redis中插入了一个新用户名密码。
```
HMSET mqtt_user:dadait is_superuser 1 password 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
```

在订阅主题时不输入用户名名密码，或者输入不存在的用户名会提示用户名密码错误。
```
mosquitto_sub  -t /ip/video
Connection Refused: bad user name or password.

mosquitto_sub -t /ipcam/video -u dadaffit
Connection Refused: bad user name or password.
```

但是再输入正确的用户名，不输入密码或者输入一个错误的密码，竟然可以订阅或者发布。
```
mosquitto_pub -u dadait -t /ip/video -m testmessage

mosquitto_sub  -t /ip/video -u dadait
testmessage
```

请问是我的配置有问题吗？需要怎样配置检测密码是否正确？

**Comment by emqplus** [comment]
Move to redis plugin: https://github.com/emqtt/emqttd_auth_redis/issues/9
