### ISSUE TITLE
How to hot load the new beam file?

### ISSUE THREAD

**Issue by thechamp** [emqtt/emqttd#703]
I'm using the emqtt console to load the newly compiled beam file. But the issue is that there is no way of **detaching** from the console screen without stopping the entire emqtt system.

Steps I am using to load the file,
1. Attaching the console **./bin/emqttd attach**
2. Load my file **l(filename).**

Now, how do I detach from the emqttd console.

**Comment by turtleDeng** [comment]
hi, 
  leave attach using ctl + d

**Comment by thechamp** [comment]
That works. Thanks
