### ISSUE TITLE
install emqttd on raspberry pi

### ISSUE THREAD

**Issue by fubax** [emqtt/emqttd#704]
I'm trying to install emqttd on RPI3 .first install erlang with the following command:
`apt-get install erlang-crypto erlang-eldap erlang-public-key erlang-runtime-tools erlang-ssl`
and then:
`git clone https://github.com/emqtt/emqttd.git`
now when I type the folowing command:
`cd emqttd && make && make dist`

It show me the folowing error:

`pi@raspberrypi:~ $ cd emqttd && make && make dist
 DEP    gproc
make[1]: Entering directory '/home/pi/emqttd/.erlang.mk/rebar'
./bootstrap
escript: exception error: undefined function make:files/2
  in function  erl_eval:do_apply/6 (erl_eval.erl, line 657)
  in call from erl_eval:expr/5 (erl_eval.erl, line 272)
  in call from escript:eval_exprs/5 (escript.erl, line 865)
  in call from erl_eval:local_func/5 (erl_eval.erl, line 544)
  in call from escript:interpret/4 (escript.erl, line 781)
  in call from escript:start/1 (escript.erl, line 276)
  in call from init:start_it/1
Makefile:12: recipe for target 'all' failed
make[1]: **\* [all] Error 127
make[1]: Leaving directory '/home/pi/emqttd/.erlang.mk/rebar'
/home/pi/emqttd
{"init terminating in do_boot",{undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,657}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,227}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,228}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,865}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,425}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,121}]},{init,start_it,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
 DEP    lager
{"init terminating in do_boot",{undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,657}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,227}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,228}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,865}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,425}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,121}]},{init,start_it,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
 DEP    gen_logger
{"init terminating in do_boot",{undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,657}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,227}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,228}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,865}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,425}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,121}]},{init,start_it,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
 DEP    gen_conf
 DEP    esockd
 DEP    mochiweb
{"init terminating in do_boot",{undef,[{rebar_utils,wordsize,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,657}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,227}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,228}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,865}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,425}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,121}]},{init,start_it,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make[1]: Entering directory '/home/pi/emqttd/deps/gproc'
make[1]: **\* No targets.  Stop.
make[1]: Leaving directory '/home/pi/emqttd/deps/gproc'
erlang.mk:310: recipe for target 'deps' failed
make: **\* [deps] Error 2`

Please tell me what is wrong and how I can resolve it?
I'm new to linux and bash script so please give me a newbie instruction
Thanks.

**Comment by fubax** [comment]
dear friends please help me to get rid of this error:

`Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make[1]: Entering directory '/home/pi/emqttd/deps/gproc'
make[1]: *** No targets. Stop.
make[1]: Leaving directory '/home/pi/emqttd/deps/gproc'
erlang.mk:310: recipe for target 'deps' failed
make: *** [deps] Error 2`

**Comment by huangdan** [comment]
you need to read documentation in more details. 
http://emqtt.io/docs/v2/install.html#installing-from-source

**Comment by emqplus** [comment]
Invalid issue
