### ISSUE TITLE
Ubuntu syntax error

### ISSUE THREAD

**Issue by aptjn** [emqtt/emqttd#705]
Hello, I am trying to run emqtt server from past three days but could not succeed. 
I tried to run emqtt-2.0 beta-3 in ubuntu14.04 as well as in windows 10, direct installation as well as installation using source code. Attaching logs of binary installations, once it succeeds, I will retry using source code.

Output of _./bin/emqttd console_
Exec: /home/arpit/workspace/emqttd/erts-7.3/bin/erlexec -boot /home/arpit/workspace/emqttd/releases/2.0/emqttd -mode embedded -boot_var ERTS_LIB_DIR /home/arpit/workspace/emqttd/erts-7.3/../lib -config /home/arpit/workspace/emqttd/releases/2.0/sys.config -mnesia dir "/home/arpit/workspace/emqttd/data/mnesia/emqttd@127.0.0.1" -args_file /home/arpit/workspace/emqttd/releases/2.0/vm.args -- console
Root: /home/arpit/workspace/emqttd
/home/arpit/workspace/emqttd
/home/arpit/workspace/emqttd/erts-7.3/bin/erlexec: 1: /home/arpit/workspace/emqttd/erts-7.3/bin/erlexec: Syntax error: word unexpected (expecting ")")

I tried running it with _bash ./bin/emqttd console_ whose output came as 
Exec: /home/arpit/workspace/emqttd/erts-7.3/bin/erlexec -boot /home/arpit/workspace/emqttd/releases/2.0/emqttd -mode embedded -boot_var ERTS_LIB_DIR /home/arpit/workspace/emqttd/erts-7.3/../lib -config /home/arpit/workspace/emqttd/releases/2.0/sys.config -mnesia dir "/home/arpit/workspace/emqttd/data/mnesia/emqttd@127.0.0.1" -args_file /home/arpit/workspace/emqttd/releases/2.0/vm.args -- console
Root: /home/arpit/workspace/emqttd
/home/arpit/workspace/emqttd
./bin/emqttd: line 400: /home/arpit/workspace/emqttd/erts-7.3/bin/erlexec: cannot execute binary file: Exec format error
./bin/emqttd: line 400: /home/arpit/workspace/emqttd/erts-7.3/bin/erlexec: Success

in both the cases the server couldn't run.

While in windows 10 it showed following error on _.\bin\emqttd start_
 Failed to start service emqttd_2.0.                 Error: The process terminated unexpectedly.  

PS: I am completely naive in erlang. I have installed latest erlang/OTP if that could be a possible problem?
Regards,
Arpit

**Comment by huangdan** [comment]
@aptjn,
I'm sorry for my late reply
 we recommend refer you to read documentation in more details.
 http://emqtt.io/docs/v2/install.html#

**Comment by emqplus** [comment]
@aptjn, please build the broker from source:  http://emqtt.io/docs/v2/install.html#installing-from-source
