### ISSUE TITLE
How to use emqqtd in android?

### ISSUE THREAD

**Issue by useruseri** [emqtt/emqttd#709]
Hi,
can anyone help me or give a hint how to use emqqtd in my android app?Any help apprecited.
should emqqtd be implemented on server or client, i mean is it a technology that must be used in server side and we get benefit in client side?
with regards

**Comment by pranavmehta** [comment]
emqttd is meant to be used on the server. You can use one of the many open source MQTT clients on your android app to connect to the server and exchange messages.

**Comment by turtleDeng** [comment]
hi
 this is java clients, https://eclipse.org/paho/clients/java/ . May be helpful to you.
