### ISSUE TITLE
Rebar Compile failed while processing emqttd/deps/esockd

### ISSUE THREAD

**Issue by phuongnc** [emqtt/emqttd#712]
==> gproc (compile)
==> goldrush (compile)
==> lager (compile)
==> gen_logger (compile)
==> gen_conf (compile)
==> esockd (compile)
emqttd/deps/esockd/src/esockd_udp.erl:46: referring to built-in type port as a remote type; please take out the module name
emqttd/deps/esockd/src/esockd_udp.erl:46: referring to built-in type port as a remote type; please take out the module name
Compiling /emqttd/deps/esockd/src/esockd_udp.erl failed:
ERROR: compile failed while processing emqttd/deps/esockd: rebar_abort

Erlang R14B04 (erts-5.8.5) [source] [64-bit] [smp:8:8] [rq:8] [async-threads:0] [kernel-poll:false]
Eshell V5.8.5  (abort with ^G)

**Comment by turtleDeng** [comment]
hi
  Which branch do you use? You can try using our latest branch of our try.

**Comment by phuongnc** [comment]
I update erlang and compile ok. But when i compiled brocker is running, everything seem be ok but no port 1883 watting for the connection so client can not connect to brocker
I check by terminal "netstat -ntpl".

**Comment by phuongnc** [comment]
No port 1883 is waitting connection :(
---
starting emqttd on node 'emqtt@127.0.0.1'
emqttd ctl is starting...[ok]
emqttd hook is starting...[ok]
emqttd router is starting...[ok]
emqttd pubsub is starting...[ok]
emqttd stats is starting...[ok]
emqttd metrics is starting...[ok]
emqttd pooler is starting...[ok]
emqttd trace is starting...[ok]
emqttd client manager is starting...[ok]
emqttd session manager is starting...[ok]
emqttd session supervisor is starting...[ok]
emqttd wsclient supervisor is starting...[ok]
emqttd broker is starting...[ok]
emqttd alarm is starting...[ok]
emqttd mod supervisor is starting...[ok]
emqttd bridge supervisor is starting...[ok]
emqttd access control is starting...[ok]
emqttd system monitor is starting...[ok]
Erlang MQTT Broker 2.0 is running now
{ok,[gproc,gen_logger,esockd,xmerl,compiler,syntax_tools,
     mochiweb,gen_conf,emqttd]}

**Comment by turtleDeng** [comment]
hi
  Please check etc / emqttd.conf
