### ISSUE TITLE
Ubuntu | compilation error with OTP 19

### ISSUE THREAD

**Issue by aptjn** [emqtt/emqttd#713]
Hello,
Could anyone please help me with the below error

 ERLC   esockd.erl esockd_acceptor.erl esockd_acceptor_sup.erl esockd_access.erl esockd_app.erl esockd_cidr.erl esockd_connection.erl esockd_connection_sup.erl esockd_gen.erl esockd_keepalive.erl esockd_listener.erl esockd_listener_sup.erl esockd_net.erl esockd_ratelimit.erl esockd_server.erl esockd_sup.erl esockd_transport.erl esockd_udp.erl
src/esockd_cidr.erl:59: syntax error before: 
src/esockd_cidr.erl:63: syntax error before: 
src/esockd_cidr.erl:54: function parse_addr/1 undefined
src/esockd_cidr.erl:55: function parse_cidr/3 undefined
src/esockd_cidr.erl:128: Warning: function start_mask/2 is unused
src/esockd_cidr.erl:136: Warning: function end_mask/2 is unused
src/esockd_cidr.erl:158: Warning: function bmask/2 is unused
src/esockd_cidr.erl:163: Warning: function calc_end_address/2 is unused
src/esockd_cidr.erl:166: Warning: function bor_with_mask/2 is unused
src/esockd_cidr.erl:171: Warning: function band_with_mask/2 is unused
src/esockd_cidr.erl:176: Warning: function bit_count/1 is unused
make[2]: **\* [ebin/esockd.app] Error 1

Because of this error, I am not able to install the server on my pc.
I check this file and couldn't really locate any error. I have just started to use Erlang so this could be a really trivial problem.
PS: I am running Ubuntu on VirtualBox if that makes any difference.
Thank you for the help.

**Comment by aptjn** [comment]
Okay I got to know from few queries for some other erlang packages that OTP version could be possible issue for such compilation errors. So I started reducing my OTP version and finally with version 18.2.1 it got compiled.

**Comment by turtleDeng** [comment]
hi
  emqtt2.0 can only support the erlang R18, emqtt3.0 will support erlang R19
