### ISSUE TITLE
Mosquitto Bridge with Emqtt

### ISSUE THREAD

**Issue by drasko** [emqtt/emqttd#718]
I am trying without sucess to bridge Mosquitto with config like this:

```
# For debugging
log_type all

# Bridge to Losant
connection bridge-to-mainflux
address localhost:1883
cleansession true
try_private false
bridge_attempt_unsubscribe false
notifications false
#remote_clientid 444555
topic # both 0
```

to `emqtt` running on `localhost` on port 1883.

This is the error output of Mosquitto:

```
drasko@Lenin:~/mainflux/mosquitto$ /usr/sbin/mosquitto -c mosquitto.conf -p 1111
1476138296: mosquitto version 1.4.8 (build date Sun, 14 Feb 2016 15:06:55 +0000) starting
1476138296: Config loaded from mosquitto.conf.
1476138296: Opening ipv4 listen socket on port 1111.
1476138296: Opening ipv6 listen socket on port 1111.
1476138296: Bridge local.Lenin.bridge-to-mainflux doing local SUBSCRIBE on topic #
1476138296: Connecting bridge bridge-to-mainflux (localhost:1883)
1476138296: Bridge Lenin.bridge-to-mainflux sending CONNECT
1476138296: Socket error on client local.Lenin.bridge-to-mainflux, disconnecting.
```

I am referencing this issue: https://github.com/emqtt/emqttd/issues/438 - for me this is not fixed.

**Comment by drasko** [comment]
Any updates on this? Did anybody tried this?

**Comment by huangdan** [comment]
hi, You can find how to bridge mosquitto here http://emqtt.io/docs/v2/bridge.html

**Comment by drasko** [comment]
@huangdan can you confirm that this works? As you can see from my description I set-up mosquitto correctly (at least I think).

Is `bridge_protocol_version mqttv311` line necessary?

**Comment by turtleDeng** [comment]
hi
  address 127.0.0.1:1883 ok
  address localhost:1883 fail
  Please check whether you support the domain.
