### ISSUE TITLE
General query | insert entries in mongo

### ISSUE THREAD

**Issue by aptjn** [emqtt/emqttd#719]
Hi,
I want to connect to auth mongo plugin and then insert user auth and acl in it.
I am able to load the plugin, but I am not getting how do I insert into the db.
I have checked the example given in test module but I am unable to run it (I compiled it and created a beam file but I am not sure how to load it).
There is a connect/1 function outsourced from emqttd_auth_mongo module, but again the parameter passed in it is little difficult to understand. 

Could anyone help me in
1. how to compile and run a small program along with the server? Do I have to compile it like another plugin?
2. How to run test files available in each library?
3. If there are direct commands using which I can just add users like (users add user1 pass1) for various plugins?

Thank you,
Arpit Jain

**Comment by turtleDeng** [comment]
hi
  https://github.com/emqtt/emqttd_auth_mongo/blob/master/test/emqttd_auth_mongo_SUITE.erl
  should be able to help you.
