### ISSUE TITLE
Using emqttd(Mqtt) as a Key Value database?[Question]

### ISSUE THREAD

**Issue by sreeisalso** [emqtt/emqttd#720]
Hi,

Is it possible to use Mqtt as a Key value database for the sensors settings (these settings will be updated occasionally)? this will reduce the need for using multiple libraries (client side database and parsing).

Are there any problems when we have many topics which are not updated as frequent as other sensor data readings?

**Comment by 51systems** [comment]
Current versions of emqttd don't persist messages between restarts so it should not be used to persist data.

See https://github.com/emqtt/emqttd/issues/327
