### ISSUE TITLE
Emqttd Parser Error

### ISSUE THREAD

**Issue by DataEngg** [emqtt/emqttd#721]
Hi @emqplus, 

Thanks for creating a reliable and fault tolerant MQTT. But in some cases I failed to debug exactly what's going on server. Please help me in the below error to overcome with it.

Whenever a android client tries to connect EMQTT Server some gets connected but some failed to connect. Server throws an error of parse_error. After looking into emqtt_error.log file I got the below error.

18:40:50.494 <0.18240.32> [error] Client(150.70.173.54:41076): Parser failed for {{badmatch,<<"T / HTTP/1.1\r\nUser-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows ">>},[{emqttd_parser,parse_frame,3,[{file,"src/emqttd_parser.erl"},{line,132}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,260}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
18:40:50.494 <0.18240.32> [error] Client(150.70.173.54:41076): Error data: <<"GET / HTTP/1.1\r\nUser-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)\r\nHost: mqtt.theneonos.net:17576\r\nAccept: _/_\r\n\r\n">>
20:16:57.895 <0.12151.48> [error] Client(150.70.173.9:42792): Parser failed for {{badmatch,<<"T / HTTP/1.1\r\nUser-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows ">>},[{emqttd_parser,parse_frame,3,[{file,"src/emqttd_parser.erl"},{line,132}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,260}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
20:16:57.895 <0.12151.48> [error] Client(150.70.173.9:42792): Error data: <<"GET / HTTP/1.1\r\nUser-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)\r\nHost: mqtt.theneonos.net:17576\r\nAccept: _/_\r\n\r\n">>

After seeing an error I can't debug whether it is client side problem or it is our server side.

Client side we are using android Paho

Server side Emqttd version is 1.1.3

Please help me to understand what is parser error and exactly how can i get a solution for it.

**Comment by turtleDeng** [comment]
hi
  You look at your client using the tcp or http protocol, from the log point of view is that you use the websocket request to connect tcp port error

**Comment by DataEngg** [comment]
@turtleDeng ,

Using paho at android side, it connects via mqtt protocol with version 3.11

Recently I got an error 
12:28:23.102 <0.11641.6> [error] Client(47.8.150.241:54457): Parser failed for {function_clause,[{emqttd_parser,parse_utf,[<<"fa9faebca1d3b877ae6a32bee8baccdcd0b363f9">>],[{file,"src/emqttd_parser.erl"},{line,206}]},{emqttd_parser,parse_frame,3,[{file,"src/emqttd_parser.erl"},{line,93}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,260}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}

**Comment by turtleDeng** [comment]
Please use utf8 encoding format

**Comment by DataEngg** [comment]
@turtleDeng 

Utf-8 encoding format requires at client side or server side ?

**Comment by DataEngg** [comment]
@turtleDeng But other user without encoding format are able to connect easily without any error

**Comment by turtleDeng** [comment]
hi
this is java clients, https://eclipse.org/paho/clients/java/ . May be helpful to you.

**Comment by DataEngg** [comment]
@turtleDeng  thanks for a quick response, will let you know whether it has been worked or not.

Can you explain me what is ehostunreach,conflict,etimedout,destroy,idle_timeout,closed ?

**Comment by turtleDeng** [comment]
These are erlang inside the term, please see http://erlang.org

**Comment by prbarik** [comment]
I am facing the same issue. Issue occurs only when I run it in kubernetes(alpine image used) but works on ubuntu machine(not in Kubernetes)

**Comment by Gilbert-Wong** [comment]
Hi, @prbarik, which the version of the emqx do you use? Could you please open a new issue with your problem?

**Comment by toomasz** [comment]
I'm also facing same issue, version v3.2-rc.3. Same scenario works with mosquitto
> 2019-07-09 22:03:56.556 [error] p0DFj6D7opIwK8S1H8bn@83.27.238.160:59600 [Channel] Parse failed for function_clause
> 
>                  Stacktrace:[{emqx_frame,parse_utf8_string,
>                                  [<<48,102,0,37,99,111,110,116,105,47,99,108,
>                                     105,101,110,116,47,111,117,116,47,81,119,
>                                     48,117,116,50,73,99,105,116,86,50,86,84,
>                                     55,99,67,110,103,69,146,21>>],
>                                  [{file,
>                                       "/tmp/emqx/v3.2-rc.3/_checkouts/emqx/src/emqx_frame.erl"},
>                                   {line,378}]},
>                              {emqx_frame,parse_packet,3,
>                                  [{file,
>                                       "/tmp/emqx/v3.2-rc.3/_checkouts/emqx/src/emqx_frame.erl"},
>                                   {line,187}]},
>                              {emqx_frame,parse_frame,4,
>                                  [{file,
>                                       "/tmp/emqx/v3.2-rc.3/_checkouts/emqx/src/emqx_frame.erl"},
>                                   {line,126}]},
>                              {emqx_channel,process_incoming,3,
>                                  [{file,
>                                       "/tmp/emqx/v3.2-rc.3/_checkouts/emqx/src/emqx_channel.erl"},
>                                   {line,397}]},
>                              {gen_statem,call_state_function,5,
>                                  [{file,"gen_statem.erl"},{line,1586}]},
>                              {gen_statem,loop_event_state_function,6,
>                                  [{file,"gen_statem.erl"},{line,967}]},
>                              {proc_lib,wake_up,3,
>                                  [{file,"proc_lib.erl"},{line,259}]}]

**Comment by Gilbert-Wong** [comment]
Hi, @toomasz, which type of packet do you send via mosquitto, could you please tell me more details which help me reproduce this problem and debug this issue?
