### ISSUE TITLE
`mqtt/superuser` calls two times `emqtt_auth_http`

### ISSUE THREAD

**Issue by drasko** [emqtt/emqttd#722]
This is still not fixed, but I can not re-open https://github.com/emqtt/emqttd/issues/696, so I am opening new issue.

**Comment by huangdan** [comment]
hi @drasko 
The issue has been fixed in 2.0-rc.1,
but this version has not yet release,after the release ,please test  again ！🙂

**Comment by emqplus** [comment]
@drasko, I closed the issue.
