### ISSUE TITLE
Unable to publish a message to Emqttd

### ISSUE THREAD

**Issue by DataEngg** [emqtt/emqttd#723]
I am publishing a message to a topic via paho python client, but when I send a message via Django server by hitting an api of message it get stuck in paho.publish method of python client in publishing a message but after sometime in metrics it does not increase the value of  qos1/sent and qos1/received

EMQTTD version is 1.1.3

when I do the same thing via emqttd benchmark, benchmark returns connack timeout for each client publishing a message however count of client is 200 in benchmark so setting 1 for client it able to send message but on other side all subscribers get exit via tcp_closed

**Comment by huangdan** [comment]
please start the broker in console mode to check what's happened.
 .bin/emqttd console

**Comment by DataEngg** [comment]
@huangdan  I got this earlier, the reason is too large number of connection in a single machine does not allow another clients to subscribe and publish a message in same machine. 

What I did is connected another machine and make a cluster of machines to publish a message via another machine.
