### ISSUE TITLE
Acked vs Delivered

### ISSUE THREAD

**Issue by CheyenneForbes** [emqtt/emqttd#724]
For my on_message_delivered callback can I do the following?
- send a notification to the publisher notifying that the subscriber received the message (connected to the broker) or the subscriber did not receive the message (not connected to the broker)

Is Acked called manually by the application code using the MQTT library or is it automatically done by the library(if yes, under what conditions is it done)?

Example use case (Acked)?

Is Acked the same as "seen"/"read" on Facebook/WhatsApp?

**Comment by 51systems** [comment]
MQTT protocol spec is here: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718043

According to the spec, the server sends an publish ack (PUBACK) packet back to the client when the server has successfully received the message under QOS 1.

If you are implementing a messaging application, have the application publish a "Read" message back to the sender to implement the read/seen behaviour.
