### ISSUE TITLE
Regarding the use of HTTP APIs provided.

### ISSUE THREAD

**Issue by ArchanaSomasekhar** [emqtt/emqttd#728]
Hi,
I was exploring about emqttd. Really the clustering and bridging support provided by the emqttd broker is really easy to configure and use. 
I was trying to use the HTTP APIs provided by emqttd broker in one of my webpage but facing some issue. The issue is the response is not parsing to json datatype when I am receiving back from the server after the API call. I am facing this issue i have attached the screen shot.
![error_json](https://cloud.githubusercontent.com/assets/17998228/19425601/121ef0ec-9452-11e6-8c69-2006b272c4f0.JPG)

Thanks

**Comment by huangdan** [comment]
According to the API returns JSON data, check out your Webpage;🙂
