### ISSUE TITLE
Session of a Client In clustering feature

### ISSUE THREAD

**Issue by DataEngg** [emqtt/emqttd#729]
I have setup 3 nodes emqttd and clustered them together. There are few point I could easily see between 3 nodes are **Session is not replicated**, **Message can  be published from any node**, **Topics are replicated and routes are well maintained in independent way in each of the node**.

Most important is session too need to be replicated if suppose user is connected to node 1 with **cleanSession = False** and then after sometime it get disconnected from node 1 and someone publish a message to a topic for which client has been subscribed. After sometime same client tries to connect and it get connected to node 2 so the already published message will not be delivered to the user because according to the node 2 user is new but for node 1 user is already been subscribed and it session is there.  

**Please support session replication in clustering feature**

**Comment by emqplus** [comment]
Hi @DataEngg The broker supports 'session across nodes':  http://docs.emqtt.com/en/latest/cluster.html#session-across-nodes
