### ISSUE TITLE
[question] Consider using Elixir

### ISSUE THREAD

**Issue by Hades32** [emqtt/emqttd#73]
Looks, like "issues" are they way to go when you just want to discuss something on GitHub...

I was pretty excited about a MQTT broker based on the Erlang VM, but I was always put down by the Erlang language. Therefore I wondered if you have considered changing the language to Elixir? The project seems young enough to still be able to do this and I'd expect quite some more community involvement when using a less scary language.

Just a thought...

**Comment by erylee** [comment]
hi, Martin, 
I will try Elixir after 1.0 release with all required features. For I have written Erlang program for about ten years, I really love erlang syntax:) 

Elixir looks like borrowing syntax from languages like ruby, I don't like Ruby:(
