### ISSUE TITLE
Proxy Protocol

### ISSUE THREAD

**Issue by noordawod** [emqtt/emqttd#730]
Hi, and thanks for a wonderful project!

You've probably heard of Proxy Protocol (http://blog.haproxy.com/haproxy/proxy-protocol/). The need is obvious I reckon: get the real IP when emqtt is behind a front proxy, like haproxy.

Does emqtt support it in its latest version? Any plans to support it?

Thanks in advance.

**Comment by emqplus** [comment]
Hi @noordawod, the HAProxy will pass the source IP Address to the EMQ broker.

**Comment by noordawod** [comment]
@emqplus 

HAProxy can be configured to pass on the source IP. By default, it doesn't. I tried passing it but then EMQ didn't understand the TCP packets and barfed.

If you know `X-Forwarded-For` for proxied HTTP packets, this is the same for TCP packets.

**Comment by emqplus** [comment]
@noordawod Please clone the `proxy-protocol` branch to review the experimental `Proxy Protocol V1`  support.

**Comment by noordawod** [comment]
Thanks @emqplus! I will do so asap and report back.

**Comment by noordawod** [comment]
Just installed the latest eMQTT package for CentOS 7 (64 bit). I guess this feature is not yet integrated?

**Comment by satrox28** [comment]
Is it implemented on 2.1 ?.

**Comment by phanimahesh** [comment]
Doesn't look like it. It is targeted at 2.2 currently. You can help by testing out the proxy-protocol branch.

**Comment by noordawod** [comment]
On it!

**Comment by noordawod** [comment]
@phanimahesh 

Okay, facing a wall right now.

I cloned the proxy-protocol branch but there's no `bin/` folder. Looks like this is the source tree. And I got no idea or an erl environment to compile the sources.

Tips?

**Comment by phanimahesh** [comment]
Clone emq-relx](https://github.com/emqtt/emq-relx), and edit the `Makefile`. `dep_emqttd`'s last component is the branch/tag name. Change it to `proxy-protocol`, save it, and `make`. You will need to install erlang for compilation. You can either grab it from erlang.org, or if you don't want to install systemwide, use [asdf version manager to install erlang](https://github.com/asdf-vm/asdf-erlang) in your `$HOME`. If everything goes right you should see a release in `_rel/emqttd`. Copy that folder out somewhere, on the machine you want to run emqttd, and use `bin/emqttd start` as usual.

**Comment by emqplus** [comment]
@noordawod Please checkout the `emq22` branch for the preview release of Proxy Protocol V1/2 support.

1. Build the `emq22` branch of EMQ:

```
git clone -b emq22 https://github.com/emqtt/emq-relx.git
cd emq-relx && make
cd _rel/emqttd && ./bin/emqttd console
```

2. Enable the Proxy Protocol in etc/emq.conf:

```
## Proxy Protocol V1/2
mqtt.listener.tcp.proxy_protocol = on
mqtt.listener.tcp.proxy_protocol_timeout = 3s

**Comment by noordawod** [comment]
Thanks a lot for your help, gentlemen.

I don't understand, though, why did you close this issue?

**Comment by emqplus** [comment]
@noordawod Reopen the issue and tag 'In Progress' now.

**Comment by noordawod** [comment]
So, while compiling on a CentOS machine, I got a problem:

`
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /home/emqtt/emq-relx/deps
          /usr/lib64/erlang/lib
          /home/emqtt/emq-relx/apps
===> Failed to solve release:
 Dependency observer is specified as a dependency but is not reachable by the system.

make: *** [relx-rel] Error 127
`

No idea how to fix this. Help?

**Comment by emqplus** [comment]
It seems the the Erlang 'observer' library missed on your host.

**Comment by noordawod** [comment]
Alright, how do I install it? Output from `erl -v`:

```
emqtt@mail:~/emq-relx/$ erl -v
Erlang/OTP 18 [erts-7.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.2  (abort with ^G)
1> 
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
q
```

**Comment by phanimahesh** [comment]
Quick fix, don't include `emq_recon` in release.  Edit `relx.config` and nuke `emq_recon` from there. It is non-essential and only to assist in debugging if any issues occour. Installing observer would be distribution specific.

Alternately, use `asdf-vm/asdf` and its erlang plugin to install a local version of erlang, and use it to build emq. Then copy `_rel/emqttd` to wherever it is needed and run it from there.

**Comment by noordawod** [comment]
Thanks a lot. Recompiling.

**Comment by noordawod** [comment]
Okay. Back to square one. I had this problem appear in the previous attempt, and what I did was basically to copy `rebar` to the path.

In this attempt, though, I added the current directory to the path. But still facing the same problem. This should be fixed somehow in the build script.

```
==> cuttlefish (escriptize)
make[2]: Leaving directory `/home/emqtt/emq-relx/deps/cuttlefish'
make[2]: Entering directory `/home/emqtt/emq-relx/deps/gproc'
 DEPEND gproc.d
 ERLC   gproc.erl gproc_app.erl gproc_bcast.erl gproc_dist.erl gproc_info.erl gproc_init.erl gproc_lib.erl gproc_monitor.erl gproc_pool.erl gproc_ps.erl gproc_pt.erl gproc_sup.erl
src/gproc_dist.erl:23: Warning: behaviour gen_leader undefined
 APP    gproc.app.src
make[2]: Leaving directory `/home/emqtt/emq-relx/deps/gproc'
make[2]: Entering directory `/home/emqtt/emq-relx/deps/lager'
make[3]: Entering directory `/home/emqtt/emq-relx/deps/goldrush'
make[3]: rebar: Command not found
make[3]: *** [deps] Error 127
make[3]: Leaving directory `/home/emqtt/emq-relx/deps/goldrush'
make[2]: *** [deps] Error 2
make[2]: Leaving directory `/home/emqtt/emq-relx/deps/lager'
make[1]: *** [deps] Error 2
make[1]: Leaving directory `/home/emqtt/emq-relx/deps/emqttd'
make: *** [deps] Error 2
```

Anyway, I'm copying `rebar` to the path (as instructed) and retrying.

**Comment by emqplus** [comment]
@phanimahesh It's really boring that the building requires 'rebar'. Any idea to resolve the issue?

**Comment by noordawod** [comment]
Same result as before:

1) cloned the branch anew
2) Edited `relx.config` and nuked `emq_recon`
3) Put `rebar` on the path

Then `make` again. Same output:

```
make[1]: Leaving directory `/home/emqtt/emq-relx/deps/emq_plugin_template'
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /home/emqtt/emq-relx/deps
          /usr/lib64/erlang/lib
          /home/emqtt/emq-relx/apps
===> Failed to solve release:
 Dependency observer is specified as a dependency but is not reachable by the system.

make: *** [relx-rel] Error 127
```

Any pointers would help, thanks!

**Comment by emqplus** [comment]
@noordawod Please try to reinstall the Erlang/OTP : https://www.erlang-solutions.com/resources/download.html

**Comment by phanimahesh** [comment]
@noordawod sorry,`{observer, load}` should be nuked from relx.config. I mixed things up. observer and recon both depend on runtime tools but recon does not directly depend on observer.

@emqplus I'm facing this and other inconveniences with current build and release process, testing out a full rebar3 based solution, with a makefile so that same steps as previous can be used by users. Will keep you posted.

**Comment by noordawod** [comment]
Wonderful, upgrading to latest Erlang/OTP fixed the compilation problem! Thanks.
Now, I'll go and check the Proxy Protocol.

**Comment by noordawod** [comment]
Even more surprising (or not), I re-cloned the branch, and just ran `make` without touching `relx.config`. Build successful :)

**Comment by phanimahesh** [comment]
You now have an erlang with observer installed. So the build succeeds. It was previously complaining about missing observer.

**Comment by noordawod** [comment]
I'm getting the following errors once I activate Proxy Protocol:

```
2017-03-24 09:17:31 =SUPERVISOR REPORT====
     Supervisor: 'esockd_connection_sup - <0.1208.0>'
     Context:    connection_crashed
     Reason:     proxy_proto_timeout
     Offender:   [{pid,<0.1287.0>},{name,connection},{mfargs,{emqttd_client,start_link,[[{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,128},{max_packet_size,10240}]]}}]

2017-03-24 09:20:26 =CRASH REPORT====
  crasher:
    initial call: emqttd_client:init/1
    pid: <0.1261.0>
    registered_name: []
    exception error: {proxy_proto_timeout,[{esockd_connection,upgrade,1,[{file,"src/esockd_connection.erl"},{line,122}]},{emqttd_client,init,1,[{file,"src/emqttd_client.erl"},{line,100}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.1188.0>,<0.1187.0>,esockd_sup,<0.997.0>]
    messages: []
    links: [<0.1188.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 259
  neighbours:
2017-03-24 09:20:26 =SUPERVISOR REPORT====
     Supervisor: 'esockd_connection_sup - <0.1188.0>'
     Context:    connection_crashed
     Reason:     proxy_proto_timeout
     Offender:   [{pid,<0.1261.0>},{name,connection},{mfargs,{emqttd_client,start_link,[[{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,128},{max_packet_size,10240}]]}}]
```

**Comment by emqplus** [comment]
@noordawod Enable the Proxy Protocol support on external TCP listener by configuring etc/emq.conf:

```
## Proxy Protocol V1/2
listener.tcp.external.proxy_protocol = on
listener.tcp.external.proxy_protocol_timeout = 3s
```

And You have to deploy a LB, such as HAProxy before EMQ. The haproxy.cfg for example:

```
backend nodes
    mode tcp
    balance source
    timeout server 600s
    timeout connect 60s
    server node 127.0.0.1:1883 check inter 10000 fall 2 rise 5 weight 1 send-proxy
```

**Comment by noordawod** [comment]
Okay, where do I actually see the remote IP's as evaluated by eMQTT? Maybe some debugging option?

**Comment by noordawod** [comment]
I have HAProxy in front and I already configured it to `send-proxy`. Still, when `emqttd` starts, it spits out few logs before it stables out and runs without a crash log error. It's been now running for 15 minutes, and no errors yet.

However, can to test that the IP is actually being forwarded properly?

**Comment by phanimahesh** [comment]
Quick hack: trace a client id using `bin/emqttd_ctl trace client <id> <filename>`, connect with that client id, check logs.
Or alternately, edit configuration and turn the loglevel up to `debug`. Be warned that there will be tons of logs if you do this.

**Comment by noordawod** [comment]
No problem with `debug`. I'm running this on a dev server anyway. I'll keep you updated.

**Comment by noordawod** [comment]
Okay, I can see the remote IP in the log file just fine. This seems to work. Still need more tests to verify that, but I cannot proceed just yet.

The reason is because I have internal servers which connect to `emqttd` directly (not through `haproxy`) so this means that either they need to implement Proxy Protocol or `emqttd` need to be configured to ignore certain IP addresses from being handled by the proxy protocol handler.

I suppose this can be rather simple to do, am I right?

**Comment by phanimahesh** [comment]
In that case you need two listeners. Pick two ports, configure one to expect proxy protocol and other for direct connections.

**Comment by noordawod** [comment]
Good idea. I didn't know it's possible.
So, one server but two listen ports? Do you mind writing a snippet to add to `emq.conf` that does that?

**Comment by noordawod** [comment]
Okay. I get it now. You are asking to start a new `emqttd` instance entirely for the purpose of serving internal clients, correct? If so, isn't that a bit overkill for the task at hand? (ie: connect without Proxy Protocol for certain IP ranges).

**Comment by phanimahesh** [comment]
No, On branch emq22 there's support for multiple listeners. The feature is just 4 days old, though. Make sure you are running a version with this support enabled.

Sample config would be:
```
listener.tcp.internal = 0.0.0.0:1883
listener.tcp.proxy = 0.0.0.0:2883
listener.tcp.proxy.proxy_protocol = on
...
```

Essentially, the third component in the config (`<name>` in `listener.<proto>.<name>`) can be arbitrary. Each such valid entry will start one listener on the port specified, binding to that ip address. Parameters for this listener can be configured similar to what is shown in [this commit](https://github.com/emqtt/emqttd/commit/e469ffe7c7d05ca6740bdb91089b3b81a613938d#diff-46fce069b4505449a2d85083abc6dba5R257)

**Comment by noordawod** [comment]
Ahh, beautiful! So much power with the introduction of this feature.

**Comment by emqplus** [comment]
@noordawod The Proxy Protocol feature has been merged to master branch and released in 2.2-beta.1.

**Comment by zacsonskaria** [comment]
How to make this work for emq behind nginx ? Enabling proxy_protocol did not help.

**Comment by terry-xiaoyu** [comment]
Nginx support proxy protocol v1, configs can be found from its doc website.
