### ISSUE TITLE
ACL Support

### ISSUE THREAD

**Issue by sailingchen** [emqtt/emqttd#74]
I think, when client no use ssl  , the acl must control some topic read only for auth user

**Comment by sailingchen** [comment]
just like mosquitto, the acl file : 

user testuser
  topic  read a/b/c
  topic read  d/e/f/#

**Comment by erylee** [comment]
yes, I did it: https://github.com/emqtt/emqttd/wiki/ACL-Design

ACL Pattern: allow | deny Who subscribe | publish Topic

Examples:
```
allow {ipaddr, "127.0.0.1"} subscribe "$SYS/#"
allow {clientid, "clientid"} subscribe  "#"
```

How about this design?

**Comment by sailingchen** [comment]
I use mqtt  in android app,not use ssl connect, I think it is better like this:
(1) support authentication
(2) control the auth user access some topic , read only, not allow publish , the user write in android app configure.
(3) but another auth user can publish the topic , just for web publish.

Thanks!

**Comment by sailingchen** [comment]
now I use mosquitto , my aclefile is :

```
user testuser
topic read a/b/c
topic read d/e/f/#

user admin
topic readwrite  a/b/c
topic readwrite  d/e/f/#
```

topic "a/b/c"   and "d/e/f/#"  is readonly for auth user testuser , but admin can publish.

**Comment by erylee** [comment]
Topic filters in ACL rule support 'eq' tag now

For example:

{deny, all, subscribe, [{eq, "$SYS/#"}, {eq, "#"}]}.
Means all cannot subscribe "$SYS/#", "#". but:

{deny, all, subscribe, ["$SYS/#", "#"]}.
Means that cannot subscribe any topics.

**Comment by erylee** [comment]
hi, chen,

 Please check ACL Design in 0.6.1: https://github.com/emqtt/emqttd/wiki/ACL-Design
