### ISSUE TITLE
Health check endpoint is missing

### ISSUE THREAD

**Issue by gbrehmer** [emqtt/emqttd#740]
see #262 mqtt/status is n/a anymore

**Comment by huangdan** [comment]
hi,
@gbrehmer  you enter the URL address of the error
http://host:8083/status

**Comment by gbrehmer** [comment]
@huangdan 
Is this a 2.0 Feature only? Or did you mean the dashboard port 18083?
For current release 1.1.3 both ports with "/status" http path did not answer correctly or return a 404 error

**Comment by huangdan** [comment]
I used the 1.1.3 version of the test, return to normal
Do you want to check the running status of emqttd? 
http://localhost:8083/status   
Tips: 
Replace 'localhost' with the corresponding address

**Comment by gbrehmer** [comment]
@huangdan Thanks, endpoint works! We have changed the port mapping and I thought, that this port only handles websocket connections

**Comment by Ashtonian** [comment]
not-reopening but the status endpoint seems to be attached to the webport which I think is now 8080 so http://localhost:8080/status is working for me. Is there documentation somewhere for this endpoint ?
