### ISSUE TITLE
Share Subscription

### ISSUE THREAD

**Issue by arvindr21** [emqtt/emqttd#742]
Hello,

Thanks for the [Shared subscription feature](http://emqtt.io/docs/v2/changes.html#version-2-0-beta-3). Can you please share any documentation or example as to how to consume this?

Thanks,
Arvind.

**Comment by emqplus** [comment]
@arvindr21 A brief introduction: http://docs.emqtt.com/en/latest/advanced.html

**Comment by arvindr21** [comment]
Thanks @emqplus, this helps. Also, can you please point to the docker hub image for this release?

**Comment by emqplus** [comment]
@arvindr21, I will tag 2.0-rc.3 this week and then upgrade the docker hub image for the release.

**Comment by arvindr21** [comment]
Thanks. Appreciate the quick response!
