### ISSUE TITLE
How to set the param which named 'mqtt.session.max_inflight'

### ISSUE THREAD

**Issue by LiYBo** [emqtt/emqttd#746]
I have changed 'mqtt.session.max_inflight' from 10 to 100, then i published 1000 messages to my topic by using qos1. for testing this featrue, i subcribed my topic without sending  puback when i got the message,but  i could  only get  10 message.  I have tried chang 'mqtt.session.max_inflight'  to 1000, then i started my app by the same way, i still got only 10 message.
ps: After I changed the param i have done the emqtt server restart .

**Comment by turtleDeng** [comment]
hi
  You modify which file？

**Comment by emqplus** [comment]
@LiYBo, I'd like to close this invalid issue now.

Our steps to validate 'inflight window':

1. Install Python MQTT client:
    
    virtualenv paho-mqtt
    source paho-mqtt/bin/activate
    pip install paho-mqtt
     
2. Comment the puback in lib/python2.7/site-packages/paho/mqtt/client.py:

    \## rc = self._send_puback(message.mid)
    self._handle_on_message(message)
    return MQTT_ERR_SUCCESS
    
3. Write a Python module:

    import time
    import paho.mqtt.client as mqtt

    def on_connect(client, userdata, flags, rc):
      print("Connected with result code "+str(rc))
      client.subscribe("inflight/issue", qos = 1)
      time.sleep(4)
      for i in range(1, 20):
        client.publish("inflight/issue", str(i), 1, False)

    def on_message(client, userdata, msg):
      print(msg.topic+" "+str(msg.payload))

    client = mqtt.Client()
    client.on_connect = on_connect
    client.on_message = on_message
    client.connect("localhost", 1883, 60)

    client.loop_forever()
    
4. Configure the broker's inflight window in etc/emq.conf:
    
    mqtt.session.max_inflight = 10
    
5. Reboot the broker and run the Python module
