### ISSUE TITLE
careless about function name when emqttd_pubsub handle getstats message.

### ISSUE THREAD

**Issue by zhongwencool** [emqtt/emqttd#75]
mnesia:info(topic_subscriber, size)
should be 
mnesia:table_info(topic_subscriber, size)}

maybe add erlang dialyzer check will be better.
extremely to see feature: KPI check on runtime 
:+1:

**Comment by zhongwencool** [comment]
BTW: how many nodes do you deploy ? 
I saw the mnesia copy to all cluster nodes.....

**Comment by erylee** [comment]
Fix.  Dialyzer will be used to check in 0.7

emqttd1.x will adopt the architecture that copy Topic Tree in all clustered nodes. 

2.x will slice and distribute subtree.
