### ISSUE TITLE
"-heart" option for EMQ 2.0

### ISSUE THREAD

**Issue by jsaveljevs** [emqtt/emqttd#754]
Hi,

Since `/etc/vm.args` seems to be no longer supported for 2.0, is there any way to pass `-heart` option for VM arguments without modifying `/bin/emqttd`? 

Also, is `-heart` a good choice for auto-restarting emqttd service? I've looked for working `systemd` script (e.g. https://github.com/emqtt/emqttd/issues/706), but none of them worked for me.

Thanks!

**Comment by emqplus** [comment]
@jsaveljevs, We add a new configuration for '-heart' in etc/emq.conf:

```
## vm.args: -heart
## Heartbeat monitoring of an Erlang runtime system
## Value should be 'on' or comment the line
## node.heartbeat = on
```

**Comment by jsaveljevs** [comment]
@emqplus thanks a lot!
