### ISSUE TITLE
Customize the Broker 

### ISSUE THREAD

**Issue by SumitFlochat** [emqtt/emqttd#760]
If I clone https://github.com/emqtt/emqttd-relx.git and follow the commands 
cd emqttd-relx && make
cd _rel/emqttd && ./bin/emqttd console

Broker Starts.
But i want to customize the broker so i need the source code of the emqttd but i am unable to  find source code where i could had made changes.
Any suggestion to customize the broker.?

**Comment by turtleDeng** [comment]
hi
  source code in deps/emqttd directory

**Comment by SumitFlochat** [comment]
Thank You :)
