### ISSUE TITLE
published message autodelete from broker after expiry time(each message with different expiry time)

### ISSUE THREAD

**Issue by SongCF** [emqtt/emqttd#766]
retained message only config same expiry time with each message,
Is it possible to set different expiry time for published message on broker? just like APNs

**Comment by emqplus** [comment]
@SongCF No plan to support this feature.

**Comment by SongCF** [comment]
Hello, @emqplus 
Is it possible to cancel or delete published message before the subscriber receives?

**Comment by emqplus** [comment]
@SongCF The broker will only persist retained MQTT messages which can be deleted by publishing a  message with empty payload to the same topic.
