### ISSUE TITLE
Connect an IPv6 only client with emqtt broker

### ISSUE THREAD

**Issue by aptjn** [emqtt/emqttd#768]
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP: OTP version 18.2.1
- EMQ: v2.0-beta.3

#### Description

I want to listen on an IPv6 address as well on IPv4.
My machine is a single stack (output to _cat /proc/sys/net/ipv6/bindv6only_ is 0) and have a link local IPv6 address. I can ping to this IPv6 address from my network, but when I try to connect to any of the port (I tried 18083 like _[my local IPv6 address]:18083_ and with third party client putting IPv6 address in place) from any machine in the network, it doesn't reach to broker (no error message or any other log in the broker console, and no connection from client).

What do I need to do to make it work with IPv6?
PS: The broker work fine with IPv4 address.

Thanks,
Arpit

**Comment by turtleDeng** [comment]
18083 is in the etc/emq_dashboard.conf configuration.

**Comment by turtleDeng** [comment]
![Uploading A02092F0-9227-4ABC-B0BA-7FD67E4C660A.png…]()

**Comment by turtleDeng** [comment]
![a02092f0-9227-4abc-b0ba-7fd67e4c660a](https://cloud.githubusercontent.com/assets/1830077/20337685/8c46ae82-ac0d-11e6-88fd-3f5dd92fe980.png)

**Comment by aptjn** [comment]
I checked it, I am still not able to connect. Could you please share the conf file?
The etc/emqtt conf file have only 1883 and 8083 port configured. Even on those ports I am not able to ping using IPv6 address.
Please help me out with this, this seems to be very trivial issue but I am just not getting it.

Thanks,
Arpit

**Comment by zacsonskaria** [comment]
I am also trying to have both IPv4 and IPv6 on the same emqx server. Do we have a solution for that ? 
I could not make IPv6 work for some reason. Can someone share a working configuration please ?
