### ISSUE TITLE
[ACL] TOPIC not match want be disconnected

### ISSUE THREAD

**Issue by jhaoheng** [emqtt/emqttd#770]
#### Environment

- OS: osx
- Erlang/OTP: Erlang/OTP 19  
- EMQ: 1.1.3

#### Description

*A description of the issue*

想請教，想在 acl 認證 topic 時，強迫 subscribe 的用戶中斷連線，並是否可以自定義中斷的訊息？

**Comment by emqplus** [comment]
@jhao If the broker denied a SUBSCRIBE packet, the client will receive an SUBACK packet which contains error QoS 128.
