### ISSUE TITLE
SSL Problem 

### ISSUE THREAD

**Issue by lngjy** [emqtt/emqttd#772]
#### Environment

- OS:  centos 6 
- Erlang/OTP: OTP 19
- EMQ: 2.0 RC3 

#### Description

*A description of the issue*

When I connect the emqtt broker via ssl, log show me below , but the service seems to be right.
How to slove the problem ?

Supervisor 'esockd_connection_sup - <0.1151.0>' had child connection started with emqttd_client:start_link([{max_clientid_len,1024},{max_packet_size,65536},{client_idle_timeout,30}]) at <0.2090.0> exit with reason {ssl_error,{options,{cacertfile,[]}}} in context connection_crashed

2016-11-22 11:15:08 =SUPERVISOR REPORT====
     Supervisor: 'esockd_connection_sup - <0.1151.0>'
     Context:    connection_crashed
     Reason:     {ssl_error,{options,{cacertfile,[]}}}
     Offender:   [{pid,<0.2171.0>},{name,connection},{mfargs,{emqttd_client,start_link,[[{max_clientid_len,1024},{max_packet_size,65536},{client_idle_timeout,30}]]}}]

**Comment by turtleDeng** [comment]
Reason is cacertfile, client connection error!
