### ISSUE TITLE
Last will message is not fired when client closes socket connection

### ISSUE THREAD

**Issue by vetrostudios** [emqtt/emqttd#779]
#### Environment

- OS: Mac OS, Ubuntu 14.04
- Erlang/OTP: 
- EMQ: emqttd-2.0

#### Description

*Last will message is not fired when client closes socket connection*
Hi,
According to the spec, the last will message must be published if a client closes the connection without the client sending a DISCONNECT:

"The Will Message MUST be published when the Network Connection is subsequently closed unless the Will Message has been deleted by the Server on receipt of a DISCONNECT Packet [MQTT-3.1.2-8].
Situations in which the Will Message is published include, but are not limited to:
An I/O error or network failure detected by the Server.
The Client fails to communicate within the Keep Alive time.
The Client closes the Network Connection without first sending a DISCONNECT Packet.
The Server closes the Network Connection because of a protocol error."

I am not seeing this behavior with emqttd-2.0.   The only time I have ever seen the last will message being sent, is when the ping request is not sent in the timeout interval.

**Comment by emqplus** [comment]
@vetrostudios  Produce a last will message when the client closes a connection without DISCONNECT Packet:

1. Subscribe the will topic:

```
mosquitto_sub -t will/topic -d
```

2. Create a connection and ctrl+c to close:

```
mosquitto_sub --will-topic will/topic --will-payload "Die" --will-qos 1 -t t -d
```
