### ISSUE TITLE
Celery module:function to be called from emqttd module.

### ISSUE THREAD

**Issue by SumitFlochat** [emqtt/emqttd#782]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

I have cloned celery client application from
https://github.com/brendanmaguire/celery_erlang_client.git

I have emqttd broker.
Now i want to push specific topics to celery.
I tested celery client it works fine when i call push task through console.
But i am unable to understand how to call the function from broker that could push task.
Both have different node name when they start.Can i start both of them on one node and call celery function from broker (emqtt) modules.
Anyone please help me

**Comment by emqplus** [comment]
Invalid issue, closed.
