### ISSUE TITLE
How to unsub a topic for other client?

### ISSUE THREAD

**Issue by renwanly** [emqtt/emqttd#783]
#### Environment

- OS:  centos 6
- Erlang/OTP:  Erlang/OTP 19
- EMQ: 2.0

#### Description
English:
A client sub a topic named 'sometopic' success.
I want to remove this sub from some OTHER client or admin tools, for reason of acl changing.
How to finish this target?

中文：
客户端A成功订阅了某个topic。但由于权限变更，我想在EMQ服务器中强制取消此订阅，无论是通过其他客户端还是使用管理工具皆可。
如何做到这一点？

**Comment by watchworld** [comment]
client call unscribe method,parameter is topic

**Comment by watchworld** [comment]
emqtt have access control plugin

**Comment by emqplus** [comment]
Invalid. Closed.

**Comment by renwanly** [comment]
Sorry for my poor describe.
My point is how to remove the sub topic IMMEDIATELY, for the live session ?
