### ISSUE TITLE
Does emqtt support mosquitto's persistent_client_expiration type option

### ISSUE THREAD

**Issue by mkj-git** [emqtt/emqttd#789]
Does emqttd has something similar to mosquitto's

>  persistent_client_expiration

 option which says how long to keep atopic after a clients last connection.

**Comment by emqplus** [comment]
etc/emq.conf:

```
## Expired after 1 day:
## w - week
## d - day
## h - hour
## m - minute
## s - second
mqtt.session.expired_after = 1d
```

**Comment by mkj-git** [comment]
So this will delete all topic specific to a particular user if client is not connected for specified interval?
Can i set any specific topic expiration value synamically or using some regex?

**Comment by mkj-git** [comment]
What will happen if a huge number of unused topic in broker ? Will this affect performance ?
