### ISSUE TITLE
Unable to start emqttd service if username/password contains special characters

### ISSUE THREAD

**Issue by Benniu** [emqtt/emqttd#790]
#### Environment

- OS: Ubuntu 14.04.2 LTS
- Erlang/OTP: 
- EMQ: emqttd-ubuntu14.04-v2.0.1

#### Description

Unable to start emqttd service after setting auth info in emq_auth_username.conf

Error Info: 
[error] Syntax error in /opt/emqttd/data/configs/app.2016.12.02.10.04.34.conf after line 485 column 1, parsing incomplete

Line 485: auth.username.AAACwpT2Svi+W2St99ECug=W1saUa}er111amXMU/912hGEe_u|TGQ~

This might be caused by special characters in username and password. However, it works in emq 1.1.3

This is blocking us from upgrading 1.1.3 to 2.0.1.

**Comment by emqplus** [comment]
Fixed in emq-auth-clientid, emq-auth-username plugins:

https://github.com/emqtt/emq-auth-clientid/pull/4
https://github.com/emqtt/emq-auth-username/pull/4

**Comment by Benniu** [comment]
Verified in 2.0.2 build. Thanks for the quick fix.
