### ISSUE TITLE
How can i use SSL/TLS certificate based client authentication ?

### ISSUE THREAD

**Issue by msdevanms** [emqtt/emqttd#794]
#### Environment

- OS: Ubuntu 14.04.2 LTS
- Erlang/OTP:  
- EMQ: 

#### Description

Is there any plan to support  certfile and keyfile  based client authentication including certificate revocation ?
Since emqtt supports pretty much all kind of client authentications it will be good to have certificate based SSL/TLS client auth.

While connecting with mosquitto_sub over mosquitto server i am using --cert and --key for specifying these two files.

If this option already available please let me know.

**Comment by emqplus** [comment]
@msdevanms Plan to support this feature in 2.1 release.

**Comment by KohliDev** [comment]
Isn`t this bug duplicate of #585 ???

**Comment by PiedPieper** [comment]
Was this included in 2.1? I cannot find any documentation on this

**Comment by emqplus** [comment]
@msdevanms @KohliDev @PiedPieper Duplicated with #1185. The feature is production ready for R 2.3.2 release.

**Comment by KohliDev** [comment]
Thanks @emqplus

**Comment by rahulfk** [comment]
is there any documentation on how this feature works??

**Comment by cocowalla** [comment]
I'm also looking for any documentation on how to use x509 client authentication, how to specify trusted issuers, and whether it works when using web sockets?

**Comment by avenetj** [comment]
Hi, I'm also looking for such documentation
