### ISSUE TITLE
Unable to forbidden tcp lisener

### ISSUE THREAD

**Issue by Benniu** [emqtt/emqttd#796]
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP: 
- EMQ: 2.0.2

#### Description

In our environment, we only want to enable connections via ssl or wss listeners.
However, even if the tcp listeners is disabled(comment out) in emq.conf, it is still reachable. And if you check the dashboard, you will see the tcp listen there. 
Please see attached screenshot.

![screen shot 2016-12-06 at 2 33 33 pm](https://cloud.githubusercontent.com/assets/895096/20915526/6cf6e3ee-bbc1-11e6-8de8-0c944dc72ea9.png)
<img width="905" alt="screen shot 2016-12-06 at 2 34 05 pm" src="https://cloud.githubusercontent.com/assets/895096/20915533/744a1cf6-bbc1-11e6-929b-9507e7ac6a6b.png">

**Comment by renwanly** [comment]
you can temp block it by firewall ;-)

**Comment by emqplus** [comment]
@renwanly ;) A quick fix: https://github.com/emqtt/emqttd/pull/797

**Comment by Benniu** [comment]
@renwanly Yes, I have to block it via security rules now.
