### ISSUE TITLE
ACL Rule for one topic subscription 

### ISSUE THREAD

**Issue by Abouzeid** [emqtt/emqttd#798]
#### Environment

- OS: Ubuntu 14.04
- EMQ: V2.0

#### Description
I am pretty much new to Emqtt. 
I want to allow a user to subscribe only to **one** topic.  Could anyone help me with the ACL rule to achieve that? 
Currently, I am just denying the user from subscribing to other topics.
 `{deny, {user,"username"}, subscribe, `["topic1","topic2","topic3"]}.`

Thank you in advance.

**Comment by sanket-kulkarni-vmware** [comment]
@Abouzeid You could try this,

```
{allow, {user, "username"}, subscribe, ["topic"]}.

{deny, all}.

```

**Comment by PiedPieper** [comment]
@sanket-kulkarni-vmware What if you couldn't hardcode in the "username"?

If i have 100 clients, and I wanted to allow users USER1-USER100 to only subscribe to TOPIC1, how would I do that?

**Comment by pavankumarkatakam** [comment]
@PiedPieper, You need to use some storage like Mysql and use Mysql acl plugin for emqttd.

**Comment by PiedPieper** [comment]
@pavan, thank you for the quick reply. It would be nice to have acl.conf limit users without having to perform a lookup on every publish, but this should work fine. Again, thanks!
