### ISSUE TITLE
Can't publish via HTTPS

### ISSUE THREAD

**Issue by chimit** [emqtt/emqttd#799]
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP: 
- EMQ: 2.0.2

#### Description

I can't publish events via HTTP API using SSL. I'm using Postman to send `client`, `qos`, `retain`, `topic`, `message` fields on:
```
POST https://mysite.com:8084/mqtt/publish
```
`Could not get any response`.

I also tried
```
POST http://mysite.com:8083/mqtt/publish
```
but get `Fobbiden` (here is a typo, I think).

https://mysite.com:8084/status - works in the browser without any problems, so I think my SSL-certificate is installed properly.

At the same time, I can successfully publish an event using console:
```
curl -v --basic -u user:passwd -d "qos=1&retain=0&topic=/World&message=Ya" -k https://mysite.com:8084/mqtt/publish
```

**Comment by emqplus** [comment]
@chimit POST https://user:passwd@mysite.com:8084/mqtt/publish 
The typo will be fixed in 2.0.4
