### ISSUE TITLE
 Client can't connect through proxy

### ISSUE THREAD

**Issue by Max01010101010101** [emqtt/emqttd#805]
**About the server**
Ubuntu 14.04, 
Emqtt, with a tcp and a websocket port open.

**About the client**
Android aplication using Paho client library.

**About the Issue**
If the client is using a proxy, it can't connect to the tcp (as expected) but not to the websocket (unexpected) in the server side. How can we connect the Android paho client using a proxy to our server? The only change we need to do in the server is open the port?

**Comment by turtleDeng** [comment]
@Max01010101010101 This issue has been fixed. please build the broker from master branch.
