### ISSUE TITLE
Which certificate to use?

### ISSUE THREAD

**Issue by chimit** [emqtt/emqttd#807]
#### Environment

- OS: Ubuntu 14.04
- Erlang/OTP: 
- EMQ: 2.0.2

#### Description

Hi! I have a domain name with a wildcard SSL certificate by Comodo. And I want to setup an emqttd and make it accessible via secure WebSocket and secure TLS.

In my config file I set my Comodo certificate:
```
mqtt.listener.ssl.keyfile = etc/certs/star.mysite.com_2016.key
mqtt.listener.ssl.certfile = etc/certs/ssl-bundle_2016.crt
...
mqtt.listener.https.certfile = etc/certs/ssl-bundle_2016.crt
mqtt.listener.https.keyfile = etc/certs/star.mysite.com_2016.key
```

Now the secure WebSocket connection works well in Google Chrome. But if I want to use pure MQTT via **mqtt-spy** or **MQTT.fx** it doesn't work at all.

Later I managed to make it work by specifying a CA certificate - [[Intermediate #2 (SHA-2)] Comodo RSA Domain Validation Secure Server CA](https://support.comodo.com/index.php?/Knowledgebase/Article/View/970/0/intermediate-2-sha-2-comodo-rsa-domain-validation-secure-server-ca). So I have to put this file into my IoT client to make it able to connect to the emqttd broker securely.

My question is: when my Comodo certificate expires and I decide to buy a new one in another store (for example, **Verisign** or **Let's Encrypt**) will my IoT client not be able to connect to the broker anymore?

What is the recommended practice for this? Can I get rid of the necessity to put a certificate file on the client?

**Comment by turtleDeng** [comment]
Sorry, this is because the client program security issues lead to, you can use ca-signed certificate.

**Comment by chimit** [comment]
Thank you! I uncommented 
```
mqtt.listener.ssl.cacertfile = etc/certs/cacert.pem
```
and specified CA certificate on both: MQTT and WebSockets and everything started working.

**Comment by mnhpias** [comment]
Hello, I've   SSL certificate by Comodo. Have you used any file from Comodo SSL as cacert.pem ? or you've used which is provided with emqx broker installation ?

**Comment by zmstone** [comment]
> Hello, I've SSL certificate by Comodo. Have you used any file from Comodo SSL as cacert.pem ? or you've used which is provided with emqx broker installation ?

if you have received a full chain bundle file from the issuer, likely the last (or maybe the first) one is the root ca.
You can use openssl x509 command to inspect the certificates to confirm

**Comment by mnhpias** [comment]
I've gathered root CA, from ca-bundle and mentioned it to emqx_dashboard.conf: 

`dashboard.listener.https.cacertfile = etc/certs/emqx_root_ca.crt`

but still the https dashboard doesn't work. It listens to port 18084 though.
