### ISSUE TITLE
Facing an Issue over SSL connection to the broker.

### ISSUE THREAD

**Issue by sanket-kulkarni-vmware** [emqtt/emqttd#811]
#### Environment

- OS: Cent6
- Erlang/OTP: 19
- EMQ: 2.0.2

I am facing an issue to connect broker over SSL. I am getting following error message on the broker console logs,

(emqttd@127.0.0.1)1> 19:34:33.892 [error] SSL: certify: ssl_alert.erl:97:Fatal error: unknown ca
19:34:33.892 [error] CRASH REPORT Process <0.1206.0> with 0 neighbours crashed with reason: {ssl_error,{tls_alert,"unknown ca"}} in esockd_connection:upgrade/1 line 113

19:34:33.892 [error] Supervisor 'esockd_connection_sup - <0.1163.0>' had child connection started with emqttd_client:start_link([{max_clientid_len,1024},{max_packet_size,65536},{client_idle_timeout,30}]) at <0.1206.0> exit with reason {ssl_error,{tls_alert,"unknown ca"}} in context connection_crashed

**Comment by chimit** [comment]
Having the similar problem on HTTP POST publishing over SSL.

```
(emqttd@127.0.0.1)1> 04:31:00.234 [error] Error in process <0.1124.0> on node 'emqttd@127.0.0.1' with exit value:
{badarg,[{erlang,list_to_binary,[undefined],[]},{emqttd_http,http_publish,1,[{file,"src/emqttd_http.erl"},{line,94}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,75}]}]}
04:31:00.234 [error] Supervisor 'esockd_connection_sup - <0.1097.0>' had child connection started with mochiweb_http:start_link({emqttd_http,handle_request,[]}) at <0.1124.0> exit with reason bad argument in call to erlang:list_to_binary(undefined) in emqttd_http:http_publish/1 line 94 in context connection_crashed
```

**Comment by turtleDeng** [comment]
@chimit http://emqtt.com/docs/v2/guide.html#http-publish

**Comment by turtleDeng** [comment]
@sanket-kulkarni-vmware 
Please tell me the way the client connection.

**Comment by sanket-kulkarni-vmware** [comment]
Hi @turtleDeng  my issue got fixed, I was facing the issues because of existing certs provided in the default installation of EMQTT. Default SSL certs provided in the certs folder are not working.

I have created a new set of the client-server key pair and they are working fine now.
