### ISSUE TITLE
Question about gen_conf

### ISSUE THREAD

**Issue by wuhanqing** [emqtt/emqttd#817]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

Hi,
I prepare to debugging emqttd for study,
and found this in rebar.config:
{gen_conf,".*",{git,"https://github.com/emqtt/gen_conf",""}}
Which I can't rebar  get-deps

Another question is
May I ask which is the boot function in src？
emqttd start()
emqttd_broker start_link()
emqttd_server start_link(Pool, Id, Env)
I met with some difficulties on this questions..

**Comment by emqplus** [comment]
The `gen_conf` library is deprecated and removed. Please clone the latest master branch.
