### ISSUE TITLE
Does EMQ support upgrade QOS ?

### ISSUE THREAD

**Issue by SMekhin** [emqtt/emqttd#821]
#### Environment

- OS: ubuntu16.04
- Erlang/OTP: 
- EMQ: 2.0.3

#### Description

I wonder that can sub get higher Qos than Pub's Qos

_Ex: 
Pub Qos0 --> EMQ --> Sub Qos2_

Since my pub side is on emqtt's server but sub is not. So when public message Qos 0 is less process and then subscript can use Qos2 to guarantees that each message is received only once.

**Comment by emqplus** [comment]
No

**Comment by SMekhin** [comment]
Then if you said that it can't be help since it was feature that mosquitto and hive have had. By the way I really like your eMQTT broker.

**Comment by SMekhin** [comment]
Thank you for qos upgrade

> Upgrade QoS
> Support to upgrade QoS accoding to the subscription:
> `mqtt.session.upgrade_qos = on`
