### ISSUE TITLE
support centos 6

### ISSUE THREAD

**Issue by saga1015** [emqtt/emqttd#825]
#### Environment

- OS: centos 6.5
- Erlang/OTP: 18.0
- EMQ: 2.0.3

#### Description
can not download emq 2.0.3 for centos 6

**Comment by KerwinKoo** [comment]
+1

**Comment by KerwinKoo** [comment]
It's required the glibc version later than 2.14. but after installing `glibc-2.14` in Centos 6 , EMQ 2.0 get stuck and doesn't work with nothing to report.

**Comment by emqplus** [comment]
@CMTEST080 @KerwinKoo We built a binary package for CentOS 6.5: http://emqtt.com/downloads/latest/centos6

**Comment by KerwinKoo** [comment]
@emqplus I have installed the binary package from http://emqtt.com/downloads/latest/centos6, but it doesn't work:

```
/opt/emqttd/erts-7.3/bin/escript: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/emqttd/erts-7.3/bin/escript)
```
