### ISSUE TITLE
How to join or link new cluster nodes with running emqttd cluster

### ISSUE THREAD

**Issue by yuvrajdhl1988** [emqtt/emqttd#830]
#### Environment

- OS: ubuntu
- Erlang/OTP: 5.1
- EMQ: 2.0

#### Description
I want to use Clustering feature but facing issue while join erlang nodes with default running node. Default running cluster node is empttd@127.0.0.1.

Error at new started node 
** Connection attempt from disallowed node 'emqttd@127.0.0.1' **
Error at default running node
Failed to join the cluster: {node_not_running,'node6@127.0.0.1'}

I do the following steps:-
1. I open terminal and start emqtt with ./bin/emqttd start.
2. I open new terminal and start new node with erl -name node1@127.0.0.1 
3. I go back start emqtt terminal window and try to join new node node1@127.0.0.1 in running node list. I run ./bin/emqttd_ctl cluster join node1@127.0.0.1 got error both terminal windows.
4. I also try to join at new node window with net_kernel:connect_node('node2@127.0.0.1'). command but got false in response

So, Please let me know where i did mistake and how to use this feature in emqtt.

Thanks,
Manish Yadav

**Comment by turtleDeng** [comment]
@yuvrajdhl1988 http://emqtt.io/docs/v2/cluster.html#

**Comment by emqplus** [comment]
Invalid issue, closed.
