### ISSUE TITLE
Compile error emq 2.0.4 on windows

### ISSUE THREAD

**Issue by michaelcplusplus** [emqtt/emqttd#831]
#### Environment

OS: Windows 7
Erlang/OTP: 18.3
EMQ: 2.0.4

#### Description
Compile error emq 2.0.4 on windows:

...
Klone nach 'neotoma' ...
==> getopt (get-deps)
==> neotoma (get-deps)
./rebar compile
==> getopt (compile)
Compiled src/getopt.erl
==> goldrush (compile)
==> lager (compile)
==> neotoma (compile)
Compiled src/neotoma.erl
Compiled src/neotoma_parse.erl
==> cuttlefish (compile)
Compiled src/cuttlefish_duration_parse.peg
Compiled src/conf_parse.peg
Compiled src/cuttlefish_advanced.erl
Compiled src/cuttlefish.erl
Compiled src/cuttlefish_bytesize.erl
Compiled src/conf_parse.erl
Compiled src/cuttlefish_conf.erl
Compiled src/cuttlefish_datatypes.erl
Compiled src/cuttlefish_duration.erl
Compiled src/cuttlefish_effective.erl
Compiled src/cuttlefish_enum.erl
Compiled src/cuttlefish_duration_parse.erl
Compiled src/cuttlefish_error.erl
Compiled src/cuttlefish_flag.erl
Compiled src/cuttlefish_mapping.erl
Compiled src/cuttlefish_rebar_plugin.erl
Compiled src/cuttlefish_schema.erl
Compiled src/cuttlefish_escript.erl
Compiled src/cuttlefish_generator.erl
Compiled src/cuttlefish_translation.erl
Compiled src/cuttlefish_validator.erl
Compiled src/cuttlefish_util.erl
Compiled src/cuttlefish_vmargs.erl
Compiled src/cuttlefish_variable.erl
Compiled src/cuttlefish_unit.erl
Compiled src/lager_stderr_backend.erl
Der Befehl "rebar" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
ERROR: Command [compile] failed!
make[2]: *** [Makefile:17: compile] Fehler 1
make[2]: Verzeichnis „/home/ml/emq-relx/deps/cuttlefish“ wird verlassen
make[1]: *** [../../erlang.mk:313: deps] Fehler 2
make[1]: Verzeichnis „/home/ml/emq-relx/deps/emq_auth_http“ wird verlassen
make: *** [erlang.mk:312: deps] Fehler 2

**Comment by turtleDeng** [comment]
@michaelcplusplus Windows compiler need to rely on erlang.mk detailed installation see https://erlang.mk/guide/installation.html#_on_windows

**Comment by michaelcplusplus** [comment]
Fixed in Release 2.0.6
