### ISSUE TITLE
Running Docker Image Locally: Could not connect through websocket

### ISSUE THREAD

**Issue by jayareddyd** [emqtt/emqttd#833]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 
- Docker

#### Description

*A description of the issue*
- Running Docker Image on Mac, from the dashboard trying to connect though websocket, encountered with the issue : "The client connect failure AMQJS0008I Socket closed.", could you please let me know what's causing the issue.
![screen shot 2016-12-23 at 1 01 23 pm](https://cloud.githubusercontent.com/assets/5160033/21462509/c0889bda-c911-11e6-87e9-149c6489d1ac.png)

**Comment by turtleDeng** [comment]
@jayareddyd You use that version?

**Comment by jayareddyd** [comment]
Thanks! Now it's connected by exporting 8083 port
