### ISSUE TITLE
node not responding to pings

### ISSUE THREAD

**Issue by MuskaWu** [emqtt/emqttd#834]
#### Environment

-Server: AWS
- OS: Centos 7
- Erlang/OTP: 
- EMQ: v2.0.4

#### Description

I have two Server on AWS :+1: 

- OS: Centos 7
- EMQ: v2.0.4

my step:
step1:build aws centos
step2:setup emqttd 2.0.4
step3:edit emqttd/etc/emq.conf 
    ## Node name
    node.name = emqttd@ec2-XXX-XXX-XXX-XXX.us-west-2.compute.amazonaws.com
step4:[emqttd]#./bin/emqttd console
step5:[emqttd]#./bin/emqttd start
step6: open browser http://ec2-XXX-XXX-XXX-XXX.us-west-2.compute.amazonaws.com:18083/ Test OK !
step7:[emqttd]#./bin/emqttd_ctl status
Node 'emqttd@ec2-XXX-XXX-XXX-XXX.us-west-2.compute.amazonaws.com' not responding to pings.
↑↑↑ Q1 why? ↑↑↑ 

then I use the same step build YYY-YYY-YYY-YYY Server
......
........ 
.........
Line7:./bin/emqttd_ctl cluster join emqttd@ec2-XXX-XXX-XXX-XXX.us-west-2.compute.amazonaws.com
Node 'emqttd@ec2-XXX-XXX-XXX-XXX.us-west-2.compute.amazonaws.com' not responding to pings.
↑↑↑ Q2 why? ↑↑↑ 

How can I steup cluster Server please ??? thx

**Comment by MuskaWu** [comment]
I try reference
https://github.com/emqtt/emqttd/issues/108
then result no change

**Comment by turtleDeng** [comment]
@MuskaWu Check your domain mapping ip is the same as the machine ip

**Comment by MuskaWu** [comment]
@turtleDeng 
I apply Godaddy Domain Name : XXXX.com : and mapping AWS Elastic IP 
try open browser  XXXX.com . display => Testing 123... page (httpd) 

I start setup emqttd 
edit emq.conf 
    node.name = emqttd@XXXX.com

[emqttd]#./bin/emqttd console
[emqttd]#./bin/emqttd start
[emqttd]# ./bin/emqttd_ctl status
Node 'emqttd@XXXX.com' not responding to pings.
↑↑↑ Orz ↑↑↑

Is not it my wrong to Check my domain mapping ip & machine ip

**Comment by MuskaWu** [comment]
Erlang MQTT Broker 2.0.4 is running now
Eshell V7.3  (abort with ^G)
(emqttd@127.0.0.1)1> node().
'emqttd@127.0.0.1'
(emqttd@127.0.0.1)2>
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^C[os_mon] memory supervisor port (memsup): Erlang has closed
I change emq.conf
node.name = emqttd@127.0.0.1

command:
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[root@ip-xxx-xxx-xxx-xxx emqttd]# ./bin/emqttd_ctl status
Node 'emqttd@127.0.0.1' not responding to pings.
[root@ip-xxx-xxx-xxx-xxx emqttd]# ./bin/emqttd start
emqttd 2.0.3 is started successfully!
[root@ip-xxx-xxx-xxx-xxx emqttd]# ./bin/emqttd_ctl status
Node 'emqttd@127.0.0.1' is started
emqttd 2.0.4 is running
[root@ip-xxx-xxx-xxx-xxx emqttd]#

look emqttd@127.0.0.1 is responding to pings OK!
Except emq.conf and other file need edit??

**Comment by MuskaWu** [comment]
later I eidt emq.conf
node.name = emqttd@xxx.xxx.xxx.xxx
(note:xxx.xxx.xxx.xxx =>AWS "Private IP") before public IP was node not responding to pings

[etc]# vi emq.conf
[retc]# export EMQ_NODE_NAME=emqttd@xxx.xxx.xxx.xxx
[emqttd]# ./bin/emqttd start
emqttd 2.0.3 is started successfully!
[emqttd]# ./bin/emqttd_ctl status
Node 'emqttd@xxx.xxx.xxx.xxx' is started

**Comment by MuskaWu** [comment]
cluster problem
reference https://github.com/emqtt/emqttd/issues/496
