### ISSUE TITLE
cluster auto switch connect?

### ISSUE THREAD

**Issue by MuskaWu** [emqtt/emqttd#836]
#### Environment

- OS: Centos 7
- Erlang/OTP: 
- EMQ: 2.0.4

#### Description

*A description of the issue*

Excuse me ~ I have two node (A and B)
A node and B node on same one cluster , then topic tree copy to other node
If A node connect close ...

How can I setting emqttd cluster of auto switch B node ??

**Comment by emqplus** [comment]
@MuskaWu Deploy a HAProxy or Load-Balancer sitting in front of the EMQ cluster.
