### ISSUE TITLE
Install EMQ 2.0.5 on FreeBSD 11 (amd64)

### ISSUE THREAD

**Issue by marcoleunghk** [emqtt/emqttd#840]
#### Environment

- OS: FreeBSD 11 (amd64)
- Erlang/OTP: 19.1.1
- EMQ: 2.0.5

#### Description

I would like to install EMQ on my OS FreeBSD 11 (amd64). Can I download the EMQ source to compile it as FreeBSD package. Has any guideline ?

**Comment by emqplus** [comment]
@marcoleunghk Build EMQ from source: http://emqtt.io/docs/v2/install.html#installing-from-source

**Comment by marcoleunghk** [comment]
WoW. work! Thanks a lot  謝謝你

**Comment by miks** [comment]
In FreeBSD you need to use gmake instead of make for building from source
