### ISSUE TITLE
Mongodb ACL for auth failing

### ISSUE THREAD

**Issue by mkj-git** [emqtt/emqttd#845]
I am using mongodb auth plugin. here i am inserting  records

db.mqtt_acl.insert({username: "test10", pubsub: ["t1"]})

db.mqtt_user.insert({username: "test10", password: "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3"})

password is sha256 of '123'

i am getting connected successfully but can'r subscribe to topic:

[error] Client(122884296@127.0.0.1:44929): Cannot SUBSCRIBE [{<<"t1">>,[{qos,0}]}] for ACL Deny

**Comment by emqplus** [comment]
Move to https://github.com/emqtt/emq-auth-mongo/issues/31
