### ISSUE TITLE
Publish EMQ messages to MySQL

### ISSUE THREAD

**Issue by ahmedqadeer1989** [emqtt/emqttd#848]
#### Environment

- OS: Debian 8
- Erlang/OTP: Erlang
- EMQ: EMQTT

#### Description

Store EMQTT messages in MYSQL 

Dear Everyone 

I need to store all the messages being published to be stored in MSYQL database but i am not able to find any module related to this requirement . Can anyone help me in this issue

**Comment by SMekhin** [comment]
Hi @ahmedqadeer1989 
I used [https://nodered.org/](url) for store messages in _MYSQL_ database. It easy to use for me and they have docker image.

**Comment by ahmedqadeer1989** [comment]
Hi @SMekhin 

this link is not accessible. can you please check as its showing 404 not found

Thanks

**Comment by ahmedqadeer1989** [comment]
sorry that doesnt fullfill my requirements but thanks anyways

**Comment by emqplus** [comment]
Please contact hong@emqtt.io to consult the EMQPLUS products we officially released.
