### ISSUE TITLE
emqttd can not startup with regular users

### ISSUE THREAD

**Issue by cgdander** [emqtt/emqttd#850]
#### Environment

- OS: debian 8
- Erlang/OTP: 17
- EMQ: emqttd-debian8-v2.0.5

#### Description

*A description of the issue*
can't startup with regular user

in emqttd dir execute
 ./bin/emqttd start
waiting for about 10+ seconds
finished with nothing  and the emqttd was not started

then exectue
sudo ./bin/emqttd start
waiting for about 3-4 seconds
emqttd started correctly with the prompt message "emqttd 2.0.5 is started successfully!"

**Comment by marriotb** [comment]
This may be the same issue as #842
Try removing the directory: `/tmp/erl_pipes/` and all subdirectories (or changing the owner to the user that you want emqttd to run under)
Brian

**Comment by cgdander** [comment]
Yes! That works!
@marriotb Thanks a lot!

**Comment by emqplus** [comment]
@cgdander Fixed in 2.1.0-rc.1 release. Commit: https://github.com/emqtt/emq-relx/commit/0780606ef9edd2d81dd1625248558de9c3928e4f
