### ISSUE TITLE
What's the meaning of the CHANGE LOG of 2.0.5?

### ISSUE THREAD

**Issue by renwanly** [emqtt/emqttd#853]
Environment

    OS: CentOS 7
    Erlang/OTP:
    EMQ: 2.0.5

Description

English:
I read the following lines on [2.0.5 CHANGE LOGS](http://emqtt.com/changelogs/2050):
> emq-auth-http#9: Disable ACL support
> emq-auth-mongo#29: Disable ACL support

We are using emq-auth-http，and have a plan to use emq-auth-mongo, I'm sorry to here these words.
Although I tested emq-auth-http for version 2.0.5, it seems work well.
Question A: What's the reason for “Disable ACL support”?
Question B: Do you have a update plan? That's good for all of us.

Chinese:
我在 [2.0.5 更新日志](http://emqtt.com/changelogs/2050) 读到下面内容：
> emq-auth-http#9: Disable ACL support
> emq-auth-mongo#29: Disable ACL support

我们正在使用 emq-auth-http，并正在准备换用 emq-auth-mongo，看到这个更新日志很怕人。
针对 2.0.5 我们测试了 emq-auth-http，发现目前还可使用。
①不知道是什么原因需要进行“Disable ACL support”？
②建议给出个更新计划，以方便我们根据该计划规则自己的产品。

**Comment by emqplus** [comment]
@renwanly Pls check PR: https://github.com/emqtt/emq-auth-http/pull/10
