### ISSUE TITLE
use auth plugins with buildin acl

### ISSUE THREAD

**Issue by happyyst** [emqtt/emqttd#858]
#### Environment

- OS: centos6
- Erlang/OTP: 
- EMQ: 2.0.6

#### Description

*A description of the issue*

Hi,   in emq 1.1.3, I use emq http auth plugin without acl and super user config. I use build in acl.config,  it works well
while I'm trying to upgrade emq to 2.0.6.  I got the following error . 
[error] CRASH REPORT Process <0.1127.0> with 0 neighbours exited with reason: no function clause matching emq_acl_http:check_acl

is there any way to resolve this problem? 
I want to use plugin auth interface only.
use http acl may cause performance problems.

**Comment by emqplus** [comment]
@happyyst The issue has been fixed in 2.1.0 release
