### ISSUE TITLE
The message send hook are called very slowly

### ISSUE THREAD

**Issue by jeff-yxj** [emqtt/emqttd#862]
#### Environment

- OS: ubuntu 16.04
- Erlang/OTP: 18
- EMQ: 2.0.6

#### Description

I want to register the message.publish hook to send the message to python using thrift, but I found that the hook was called very slowly. With the emqtt-benchmark in a short time made a million messages, but this hook was only called tens of thousands of times. I would like to know this is a design problem or set up the problem, what I can do to solve this problem ?

**Comment by primantok** [comment]
😂

**Comment by emqplus** [comment]
@primantok Really cool issue😂

**Comment by maituanmte** [comment]
@emqplus Hi Feng Lee, I would like to pushlish messages via thrift. Do you have any suggestions for me?
