### ISSUE TITLE
using `emqtt console` to start emqtt throw error in Win10

### ISSUE THREAD

**Issue by TangMonk** [emqtt/emqttd#865]
#### Environment

- OS:  Win10
- Erlang/OTP:  None
- EMQ:  win10-v2.0.6

#### Description

using `emqtt console` to start emqtt throw error, image below:

![image](https://cloud.githubusercontent.com/assets/3498786/22005068/7a006fd8-dc9b-11e6-913a-d07f0f026200.png)

**Comment by emqplus** [comment]
Invalid issue, closed
