### ISSUE TITLE
The word in Documents is wrong

### ISSUE THREAD

**Issue by Howld** [emqtt/emqttd#870]
#### Description
Link: http://docs.emqtt.com/en/latest/guide.html
Sentence: ' The ACL of EMQ broker is responsbile for authorizing MQTT clients to publish/subscribe topics. '
Word: responsbile

**Comment by emqplus** [comment]
@Howld Fixed in commit: https://github.com/emqtt/emq-docs-en/commit/0b3c767f18b25607caea37f49ca3a8f7d3efb3c3

Thanks.
