### ISSUE TITLE
Documentation: Installing on Windows

### ISSUE THREAD

**Issue by michaelcplusplus** [emqtt/emqttd#871]
#### Environment

OS: Windows 7
Erlang/OTP: 18.3
EMQ: 2.0.6

#### Description

Link: `http://emqtt.io/docs/v2/install.html#installing-on-windows`

What means the sentence: 

Warning
Cannot register EMQ-2.0 as a windows service.

![image](https://cloud.githubusercontent.com/assets/24432169/22097359/fb8e9b48-de20-11e6-84c5-b516ec729ec4.png)

Is a solution planned for the problem?

**Comment by altishchenko** [comment]
Did you try doing it with Admin privileges?

Alexander Tishchenko
mob: +7 (916) 704-61-57
atishch@gmail.com

**Comment by emqplus** [comment]
@michaelcplusplus @altishchenko The EMQ-2.0 cannot be registered as a window service. For we have to translate the etc/emq.conf to data/configs/app.config before the Erlang VM boot, we cannot use the `erlsrv` to register in bin/emqttd :(

**Comment by michaelcplusplus** [comment]
I have no problem to install the service. 

But I'm not able to start the service. 
**Messages from the Windows Eventlog:**
ErlSrv:  emqttd_2.0.6: Not enough parameters for erlang service.
ErlSrv: emqttd_2.0.6: Could not start erlang machine

Registry entry:

![image](https://cloud.githubusercontent.com/assets/24432169/22097230/4b18a358-de20-11e6-83e0-a6b1f82aa7d7.png)

**Comment by emqplus** [comment]
@michaelcplusplus Would you like to check the bin/emqttd.cmd batch file and help fix this issue? Thanks.

**Comment by michaelcplusplus** [comment]
Yes, of course.

The bin/emqttd.cmd file exists. 

I hav eno problems to start the emqttd broker with one of the following commands from the command line:
bin\emqttd console
bin\emqttd start

The stopping works also from the command 
bin\emqttd start

Best regards
Michael

**Comment by emqplus** [comment]
I don't know if we could register the `bin\emqttd start` as a window service like the `init.d` on Linux.

**Comment by michaelcplusplus** [comment]
Please note:
The registration works but the windows service could not be started.

![image](https://cloud.githubusercontent.com/assets/24432169/22100619/9e380f3c-de30-11e6-9154-3dc4661f5944.png)

The emqttd version 1.1.3 could be started as windows service. This version works fine for me.

**Comment by michaelcplusplus** [comment]
I guess the missing starts_erl.cmd script is responsible for the misconduct.

![image](https://cloud.githubusercontent.com/assets/24432169/22103664/57714bc0-de3c-11e6-97eb-f2a598ff6c92.png)

**Comment by michaelcplusplus** [comment]
Tested with emqttd-windows10-v2.1.0-rc.2 on windows 10.

![image](https://cloud.githubusercontent.com/assets/24432169/24693521/3d19172a-19de-11e7-88bf-b02f5abaf9a8.png)
The service can be installed. 

But the service could not be started.

Windows Event viewer:
Entry 1
![image](https://cloud.githubusercontent.com/assets/24432169/24693623/c022ef92-19de-11e7-9f38-d4e1a935228a.png)

Entry 2
![image](https://cloud.githubusercontent.com/assets/24432169/24693633/cd2e22ce-19de-11e7-9859-e1870c8b0e47.png)

**Comment by michaelcplusplus** [comment]
Tested with emqttd-windows10-v2.2-beta.2 on windows 10.

The service can be installed.
But the service could not be started.

*Windows Event viewer:*
Entry 1
![image](https://cloud.githubusercontent.com/assets/24432169/26399971/374d9d26-407f-11e7-9b34-1c38d047ebba.png)

![image](https://cloud.githubusercontent.com/assets/24432169/26399983/4698a776-407f-11e7-89ac-7c503454ad56.png)

**Comment by michaelcplusplus** [comment]
Please see https://github.com/emqtt/emqttd/issues/803

**Comment by sinegole** [comment]
Any solution for this problem, the latest versions are useless. I can't start service. Solution #803 also don't work on my PC.

**Comment by twmarr** [comment]
Is there an ETA or any plans what-so-ever to fix this so it will run as a service on a Windows platform?  Manual work-arounds or manual interventions are NOT acceptable in my particular situation, unfortunately.
