### ISSUE TITLE
Dashboard View - Cluster

### ISSUE THREAD

**Issue by satrox28** [emqtt/emqttd#872]
#### Environment

- OS: Ubuntu 14.0.4
- Erlang/OTP: 19.2
- EMQ: 2.0.6

#### Description

Hi,

Thanks for the emqtt, its working great.

We have a 2node cluster and have a loadbalancer, the traffic is split nicely.

Right now, we see both the client stats on two individual nodes, is it possible to make it show both the stats on 1 server node.

**Comment by emqplus** [comment]
Hi @satrox28 The dashboard only shows the clients, sessions and subscriptions of the current node in the cluster. It's boring when we want to check the global stats. Our team is working on the EMQ Control Center these days to manage the whole cluster on the same dashboard. The ECC product will be released next month, I guess. Thx.

**Comment by satrox28** [comment]
Hi,

Do you have any update on this feature request?. When it will be released?

**Comment by satrox28** [comment]
Any update, as we are planning to setup cluster in our production environment

**Comment by JyothiRavi** [comment]
We are also having the same issue. Any updates on this.

**Comment by HJianBo** [comment]
@JyothiRavi Duplicated https://github.com/emqx/emqx-dashboard/issues/37.  I plan to fix it in the future version
