### ISSUE TITLE
Documentation: installing-from-source

### ISSUE THREAD

**Issue by Howld** [emqtt/emqttd#873]
#### Description
Link: http://docs.emqtt.com/en/latest/getstarted.html#installing-from-source
Issues:
<pre>
$ make dist
make: *** No rule to make target 'dist'.  Stop.
</pre>
Question: It seems that Makefile changed but the documentation not update or some thing I do wrong.

**Comment by emqplus** [comment]
@Howld Thanks. Fixed in 2.0.7 release: https://github.com/emqtt/emq-docs-en/pull/7
