### ISSUE TITLE
cluster only can join 2 emqttd

### ISSUE THREAD

**Issue by okamipride** [emqtt/emqttd#875]
#### Environment

- OS: ubuntu 16.04 TLS on AWS EC2
- Erlang/OTP: 19
- EMQ: 2.0.6

#### Description
I am try to join 3 emqttd in a cluster in AWS EC2s.
I am able to Join ubuntu@ip1 with emqttd@ip2; however; when i join ubuntu@ip1 with ubuntu@ip3, it works but ,  ubuntu@ip2 is kicked from ubuntu@ip1 cluster list nodes; however ubuntu@ip2 keep the ubuntu@ip1 in its node list .It seems  only 2 node can be joined together.

**Comment by emqplus** [comment]
@okamipride Start ubuntu@ip1 first, and then call `./bin/emqttd_ctl cluster join ubuntu@ip1` on `ubuntu@ip2` and `ubuntu@ip3`

**Comment by okamipride** [comment]
Thank you for quick replay.
i did do the procedure as you said. It is document in the emqttd refernce; however it get what i posted previous; however sometimes, it works.  and sometimes emqttd_ctl cluster status report fail.  how do i reset everything in emqttd cluster setting  and restart from a clean state ?

**Comment by okamipride** [comment]
[screen capture of failed cluster join](https://s3.ap-northeast-2.amazonaws.com/emqttd-images/emqttd+cluster+issue.jpg)
