### ISSUE TITLE
emqttd broker not sending out LWT after expected keepalive timeout

### ISSUE THREAD

**Issue by tercanfurkan** [emqtt/emqttd#877]
#### Environment

- OS: 14.04
- Erlang/OTP: 
- EMQ: 1.0.1

#### Description

*A description of the issue*
My mqtt client has a keepAliveInterval of 5 mins. That is sent to the broker when connecting.

However, when the client loses network connection, the broker sends out the LWT only after 19 mins. 

According to specs:
The broker must disconnect a client, which doesn’t send PINGREQ or any other message in one and a half times of the keep alive interval. In our case, it is almost 4 times.

Why is this the case?

**Comment by tercanfurkan** [comment]
I made further tests with keepAliveInterval set to 5mins and to 30sec:

1. keepAliveInterval: 5 mins => lwt sent out: 16mins
2. keepAliveInterval: 5 mins => lwt sent out: 18mins
3. keepAliveInterval: 30 sec => lwt sent out: 2mins

Why is the keepAlive timeout 3 to 4 times of the keepAlive interval? 
Can I change this logic somewhere in the code?

**Comment by arvindr21** [comment]
@emqplus is this issue resolved?

**Comment by emqplus** [comment]
@arvindr21 We added a `mqtt.keepalive_backoff` configuration in 2.3 release to fix the issue:

```
## The Keepalive timeout: Keepalive * backoff * 2
mqtt.keepalive_backoff = 0.75
```

**Comment by arvindr21** [comment]
Thanks @emqplus Will validate and confirm.
