### ISSUE TITLE
upgrade erlang in emqttd directory

### ISSUE THREAD

**Issue by masoud91** [emqtt/emqttd#878]
#### Environment

- OS: Ubuntu14.04
- Erlang/OTP: 
- EMQ: 2.0.6

I have problem with beam.smp memory overload which mentioned in [issue 308](https://github.com/emqtt/emqttd/issues/308).
I could install erlang by apt-get but how can I upgrade the erlang located in local emqttd directory ?

**Comment by emqplus** [comment]
Upgrade Erlang/ OTP to R18.3+
