### ISSUE TITLE
shared subscription - doesn't work

### ISSUE THREAD

**Issue by tomazbracic** [emqtt/emqttd#881]
#### Environment

- OS: Linux - Ubuntu
- Erlang/OTP: 
- EMQ: 2.0

#### Description

Trying to use shared subscription. But it doesn't work. Messages are shown on all subscribers. All the messages. I've tried with both ...  -t ‘$queue/topic’ and -t ‘$share/group/topic’

Best

**Comment by huangdan** [comment]
Two ways to create a shared subscription:

1.  $queue prefix:

```
mosquitto_sub -t '$queue/topic'
mosquitto_pub -t topic -m hello
```
2. $share/\<group\>/ prefix:
```
mosquitto_sub -t '$share/group/topic'
mosquitto_pub -t topic -m hello
```

**Comment by dbonino** [comment]
Sorry to say, but we are still experiencing the same issue:

messages are published in QoS 2 to a certain topic, e.g., /observations/ and a set of 2 subscribers use the shared topic subscription: $share/substrial//observations/ in QoS 2.
Messages are delivered to both clients as if they were "isolated" clients (all clients see all messages)

Same behavior using $queue subscriptions.

Any suggestion / improvements on this?
