### ISSUE TITLE
reload acl changes without restarting emqttd service

### ISSUE THREAD

**Issue by mauroMCW** [emqtt/emqttd#885]
#### Environment
- OS: 
Ubuntu 16.04.1 LTS
- Erlang/OTP: 
19
- EMQ: 
Erlang MQTT Broker	2.0

#### Description
I need reload emqttd configuration when I make changes on acl.conf file. Is there any way to apply acl changes without restarting emqttd service?
Thanks

**Comment by emqplus** [comment]
@turtleDeng Please add a `./bin/emqttc_ctl acl reload` command.
