### ISSUE TITLE
make dist fails

### ISSUE THREAD

**Issue by iveeshal** [emqtt/emqttd#89]
On make dist I get following issue
==> rel (generate)
ERROR: Unable to generate spec: read file info /usr/lib/erlang/man/man1/itweb-settings.1.gz failed
ERROR: Unexpected error: rebar_abort
ERROR: generate failed while processing /home/vishalvaibhav/emqttd/rel: rebar_abort
make: *** [dist] Error 1

**Comment by erylee** [comment]
erlang environment error?

**Comment by erylee** [comment]
closed?

**Comment by iveeshal** [comment]
yes seems like an issue with my erlang distribution..working fine with amazon linux..thanks

**Comment by erylee** [comment]
R17+ required
