### ISSUE TITLE
Full certificate chain transmission

### ISSUE THREAD

**Issue by je-al** [emqtt/emqttd#890]
#### Environment

emq-docker:2.0.7  (image from the releases section)

#### Description

I'm having some issues getting TLS to work (with some client applications). The only thing I can see that's different between EMQ and other software (i.e. HAProxy) is that it seems EMQ isn't (or at least not when catting them into a single `cert.pem` file) sending the whole certificate chain when establishing the TLS session, which makes this: 
```
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 OU = Domain Control Validated, CN = *.example-domain.com
verify error:num=21:unable to verify the first certificate
verify return:1
```
pop-up when verifying the connection through: `openssl s_client -connect mqtt.example-domain.com:8883 -debug`

also, socat (`socat -v tcp4-listen:1883,reuseaddr,fork ssl:mqtt.example-domain.com:8084`) says:
```
2017/02/08 18:22:55 socat[8182] E SSL_connect(): error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
```

Web browsers, however, work ok using the same cert file and the HTTPS listener, I believe the reason is that they actually look in their certificate store for the intermediate and root CAs to complete the chain.

Have you / anyone else, come across this issue?

**Comment by emqplus** [comment]
@je-al Do you use two-way SSL authentication? Please post the `mqtt.listener.ssl` configuration in etc/emq.conf.

**Comment by je-al** [comment]
@emqplus not currently.

**Comment by phanimahesh** [comment]
Can you confirm that your cert.pem is the full chain, and not just the leaf cert? Looks like it, but it wasn't clear from your description. I'll try to repro later and debug this.

**Comment by je-al** [comment]
@phanimahesh well, yeah, I tried both HAProxy's and Nginx's "format", i.e.:
```
server first
CA
intermediate 1
intermediate 2
```
```
CA
intermediate 1
intermediate 2
server first
```
And, for good measure, even:
```
server
intermediate 2
intermediate 1
CA
```

Later it occurred to me that maybe I should try a p12 store, but I see no reference to them, and #933 is also open.

**Comment by phanimahesh** [comment]
Thanks. I'll try to repro and debug. Will respond by monday.

If it turns out to be an issue, it'll be in either esockd or deeper in
dependency chain I guess.

One more question: is this a LE cert? Is the root cert trusted by your
openssl? In other words, are the intermediates not being served or is the
root not trusted? Both cases probably have similar (same?) user facing
errors.

**Comment by je-al** [comment]
@phanimahesh (I had edited the previous comment) To reiterate, valid cert issued by GoDaddy, as I said before, only the "leaf" cert is being served, at least that's what s_client reports (I think I did check using tcpdump, don't quote me on that though). One more thing, it's a wildcard cert, but I wouldn't think that has anything to do with this partircular problem.

**Comment by mbarreca** [comment]
@phanimahesh I fixed this issue by ordering it as follows

cacert.pem
`CA
intermediate
`

cert.pem
`server
CA
intermediate
`

Then I changed enabled the cacert.pem line in the emq.conf file and that did the trick.

**Comment by je-al** [comment]
@phanimahesh oh, thanks for the hint, my mistake was in not including the cacert file, I thought this was used only to verify client certs...

I did not include any intermediates in the cacert file, but besides that, the correct (?) order is as stated:
```
cert
CA
intermediate1
...
```
