### ISSUE TITLE
Flooding exception error: {ssl_error,timeout} in emqttd_sasl.log

### ISSUE THREAD

**Issue by billysz** [emqtt/emqttd#891]
#### Environment

- OS: Ubuntu 14.04 LTS
- Erlang/OTP: 18 [erts-7.3]
- EMQ: 1.1.2

#### Description
The ssl for port 8883 is configured as following:
        {mqtts, 8883, [
            %% Size of acceptor pool
            {acceptors, 16},

            %% Maximum number of concurrent clients
            {max_clients, 100000},

            %% Socket Access Control
            {access, [{allow, all}]},

            %% SSL certificate and key files
            {ssl, [{certfile, "etc/ssl/server.crt"},
                   {keyfile,  "etc/ssl/server.key"}]},

            %% Socket Options
            {sockopts, [
                {backlog, 1024}
                %{buffer, 4096},
            ]}
        ]},

and clients can connect via ssl already.

But there are lot of errors flooding in emqttd_sasl.log, size of this log file could increase over 1GB in a single day...
In the same time, the clients still can connect and pub/sub without problem. 

~/emqttd/bin# ./emqttd_ctl broker stats
clients/count       : 502
clients/max         : 502
retained/count      : 46
retained/max        : 46
routes/count        : 1506
routes/max          : 1506
sessions/count      : 0
sessions/max        : 0
subscribers/count   : 1506
subscribers/max     : 1506
subscriptions/count : 1506
subscriptions/max   : 1506
topics/count        : 1616
topics/max          : 1616

The error info like below (many same errors with different pid):

=CRASH REPORT==== 10-Feb-2017::09:21:51 ===
  crasher:
    initial call: emqttd_client:init/1
    pid: <0.691.0>
    registered_name: []
    exception error: {ssl_error,timeout}
      in function  esockd_connection:upgrade/1 (src/esockd_connection.erl, line 113)
      in call from emqttd_client:init/1 (src/emqttd_client.erl, line 76)
    ancestors: [<0.357.0>,<0.356.0>,esockd_sup,<0.127.0>]
    messages: []
    links: [<0.357.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 3043
  neighbours:

=SUPERVISOR REPORT==== 10-Feb-2017::09:21:51 ===
     Supervisor: 'esockd_connection_sup - <0.357.0>'
     Context:    connection_crashed
     Reason:     {ssl_error,timeout}
     Offender:   [{pid,<0.404.0>},
                  {name,connection},
                  {mfargs,
                      {emqttd_client,start_link,
                          [[{packet,
                                [{max_clientid_len,512},
                                 {max_packet_size,65536}]},
                            {client,[{idle_timeout,30}]},
                            {session,
                                [{max_inflight,100},
                                 {unack_retry_interval,60},
                                 {await_rel_timeout,20},
                                 {max_awaiting_rel,0},
                                 {collect_interval,0},
                                 {expired_after,2880}]},
                            {queue,
                                [{type,simple},
                                 {max_length,infinity},
                                 {low_watermark,0.2},
                                 {high_watermark,0.6},
                                 {queue_qos0,true}]}]]}}]

**Comment by emqplus** [comment]
It seems SSL handshake is timeout, please configure `handshake_timeout` option:

```
      %% SSL certificate and key files
        {ssl, [{handshake_timeout, 15000},
                {certfile, "etc/ssl/server.crt"},
               {keyfile,  "etc/ssl/server.key"}]},
```

**Comment by billysz** [comment]
Thanks for the comment, after adding the handshake_timeout, the frequency of the error reporting is now much lower than before, reduced to around 1/7 for a rough estimation.
But still the problem exists, I think there might be some clients are connecting to the 8883 ports but don't have the valid certification, I'd like to check their IP address and check if those are illegal visitors. Could the logger record the peer IPs when ssl timeout?
