### ISSUE TITLE
paho: client python unable to connect

### ISSUE THREAD

**Issue by hachreak** [emqtt/emqttd#893]
#### Environment

- OS: Debian 8
- Erlang/OTP: 19
- EMQ: 2.0.7
- paho-mqtt: 1.2

#### Description

I was trying to connect with the paho python client to Emqttd.
If I connect without SSL, all it's fine.
But, if I try to connect with SSL (MQTTS), I was not able to publish any message.

```python
import paho.mqtt.publish as publish
publish.single("TopicA", payload='hello', hostname='0.0.0.0', port=8883)
```

It remains in the loop and it doesn't do anything.
I also tried with `emqttc` and, apparently, it works fine at the first attempt also with SSL:

```erlang
{ok, C} = emqttc:start_link([{host, "0.0.0.0"}, {port, 8883}, ssl]).
emqttc:publish(C, <<"TopicA">>, <<"Payload...">>).
receive {publish, Topic, Payload} ->
    io:format("Message Received from ~s: ~p~n", [Topic, Payload]) 
end.
```

Any idea where the problem can be?

**Comment by emqplus** [comment]
@hachreak Please check the SSL Parameters of python client. The EMQ broker uses one-way SSL authentication by default.

**Comment by hachreak** [comment]
@emqplus please, could you give me an example of MQTTS connect with the `paho` library?
