### ISSUE TITLE
Source Build Errors

### ISSUE THREAD

**Issue by srayhunter** [emqtt/emqttd#894]
#### Environment

- OS: macos sierra 10.12.3
- Erlang/OTP: 19.2
- EMQ: 

#### Description

I downloaded the source from here: https://github.com/emqtt/emqttd/archive/v2.0.7.tar.gz and tried to build the source per the README.md file. 

The documentation is a little unclear because it has a reference to this project: https://github.com/emqtt/emq-relx.git along with this command `cd emq-relx && make`. 

In the archive, I tried to run the `make` command and got the following error:

```
make[1]: *** No targets.  Stop.
make: *** [deps] Error 2
```

I can delete the `deps` folder and run the make command and it is successful; however, when the `make dist` command is ran, I get the following error:

```
make: *** No rule to make target 'dist'.  Stop.
```

I am hoping to get some clarification on which source build to use: emqtt or emq-relx and how to get the `make dist` to work.

**Comment by emqplus** [comment]
@srayhunter Installing from source: http://emqtt.io/docs/v2/install.html#installing-from-source

```
git clone https://github.com/emqtt/emq-relx.git

cd emq-relx && make

cd _rel/emqttd && ./bin/emqttd console
```
