### ISSUE TITLE
What's best practice to delegate Auth/ACL correctly to another service

### ISSUE THREAD

**Issue by StarpTech** [emqtt/emqttd#901]
#### Environment

- OS: Windows
- Erlang/OTP: R18/7.3
- EMQ: 2.0.7

#### Description
I can't find any simple example/flow how to use the authentication plugins in emqtt. The documentation is really rare.
I tried `emq-auth-http` but failed with https://github.com/emqtt/emq-auth-http/issues/15
Emqtt promised much and looks great but when it breaks with the basics like authentication its unusable.

Im looking for a solution to delegate the Auth/ACL to another service. HTTP API would be perfect. What are you using in Production? Thanks.

**Comment by turtleDeng** [comment]
@StarpTech Please read the documentation. http://emqtt.io/docs/v2/guide.html#
