### ISSUE TITLE
TLS Connections Not Recovering

### ISSUE THREAD

**Issue by simonmorley** [emqtt/emqttd#904]
Running the latest version of the emqttd broker (emqttd-2.0.7). I have many clients (all c -> libmosquitto) connecting.

If killing the broker with NON SSL connections, the client reconnects without issue when the broker starts again.

If I enable SSL, the clients can connect BUT if I restart the broker, they do not recover. I have to restart the client.

I've tested with multiple clients - same issue. I've just tested these clients with mosquitto and they reconnect just fine.

**Comment by huangdan** [comment]
Can't reproduce the issue, Steps:
1. Configure the MQTT/SSL listener in etc/emq.conf:
```
## SSL Listener: 8883, 127.0.0.1:8883, ::1:8883

mqtt.listener.ssl = 8883

## Size of acceptor pool

mqtt.listener.ssl.acceptors = 4

## Maximum number of concurrent clients

mqtt.listener.ssl.max_clients = 512

## Rate Limit. Format is 'burst,rate', Unit is KB/Sec

## mqtt.listener.ssl.rate_limit = 100,10

## Configuring SSL Options

## See http://erlang.org/doc/man/ssl.html

mqtt.listener.ssl.handshake_timeout = 20

mqtt.listener.ssl.keyfile = etc/certs/key.pem

mqtt.listener.ssl.certfile = etc/certs/cert.pem

mqtt.listener.ssl.cacertfile = etc/certs/cacert.pem

mqtt.listener.ssl.verify = verify_peer

mqtt.listener.ssl.fail_if_no_peer_cert = true
```
2. A mosquitto client connects to the broker with SSL options:
 
```
mosquitto_sub -t topic -p 8883 --cafile etc/certs/cacert.pem --cert etc/certs/client-cert.pem --key etc/certs/client-key.pem  --insecure
```

3. Restart the EMQ broker:

```
./bin/emqttd restart
```
