### ISSUE TITLE
2.1 beta: Build on windows fails because of syslog

### ISSUE THREAD

**Issue by michaelcplusplus** [emqtt/emqttd#914]
#### Environment

- OS: Windows 10
- Erlang/OTP: 7.3
- EMQ: 2.1

#### Description
The build on windows with Msys2 fails.

*A description of the issue*

I seems to be a problem with the syslog dependency:

make[3]: Verzeichnis „/home/ml/emq-relx/deps/syslog“ wird betreten
make -f c_src/Makefile.erlang.mk
make[4]: Verzeichnis „/home/ml/emq-relx/deps/syslog“ wird betreten
/mingw64/bin/gcc -c -o c_src/syslog_drv.o c_src/syslog_drv.c  -finline-functions -Wall -fPIC -I "c:/Program Files/erl7.3/erts-7.3/include" -I "c:/Program Files/erl7.3/lib/erl_interface-3.8.2/include" -fPIC
make[4]: *** [c_src/Makefile.erlang.mk:8: c_src/syslog_drv.o] Fehler 1
make[4]: Verzeichnis „/home/ml/emq-relx/deps/syslog“ wird verlassen
make[3]: *** [Makefile:22: pre-app] Fehler 2
make[3]: Verzeichnis „/home/ml/emq-relx/deps/syslog“ wird verlassen
make[2]: *** [../../erlang.mk:313: deps] Fehler 2
make[2]: Verzeichnis „/home/ml/emq-relx/deps/lager_syslog“ wird verlassen
make[1]: *** [../../erlang.mk:313: deps] Fehler 2
make[1]: Verzeichnis „/home/ml/emq-relx/deps/emqttd“ wird verlassen
make: *** [erlang.mk:312: deps] Fehler 2

**Comment by turtleDeng** [comment]
@michaelcplusplus 
```
RUN git clone -b 'windows' https://github.com/emqtt/emq-relx.git /emq-relx  
RUN cd /emq-relx && make
```

**Comment by michaelcplusplus** [comment]
Build on windows works again.
