### ISSUE TITLE
mqtt_message from 

### ISSUE THREAD

**Issue by obi458** [emqtt/emqttd#916]
#### Environment

- OS: any
- Erlang/OTP:  any
- EMQ: 2.x

#### Description

-record(mqtt_message.....

from            :: {binary(), undefined | binary()}, 
should be 
from            :: atom() | {binary(), undefined | binary()} 
or with type 
-type(msg_from() :: atom() | {binary(), undefined | binary()}).

**Comment by emqplus** [comment]
@obi458 Added a 'mqtt_msg_from()' type.
