### ISSUE TITLE
emqttd_2.1.0 service can not start on service manager of Windows server 2012

### ISSUE THREAD

**Issue by quanfehut** [emqtt/emqttd#924]
#### Environment

- OS: Windows Server 2012
- Erlang/OTP: 19.2
- EMQ: 2.1.0-beta.1

#### Description
Dear all,
I install the newest EMQ broker (2.1.0_beta.1) on my Windows server 2012, after install service, i can start with command: bin\emqttd start, but when i restart my computer, this service not running, and when i click right mouse on service manager then choose "start" to manual start service, it shows error message: "Windows could not start the emqttd_2.1.0 service on local computer. Error 1067: the process terminated unexpectedly"
*A description of the issue*

**Comment by emqplus** [comment]
@quanfehut Deploy EMQ on Linux in production.
