### ISSUE TITLE
can not start emqtt on centos as service

### ISSUE THREAD

**Issue by masoud91** [emqtt/emqttd#925]
#### Environment

- OS: Centos 6.8
- Erlang/OTP: 
- EMQ: 2.0.7

#### Description

hello
I installed emqttd using rpm package on centos server
when I try to start using 
`service emqttd start`
I face this message

> Starting emqttd: vm.args needs to have a -name parameter.
>   -sname is not supported.
>                                                            [FAILED]

what am I missing?

**Comment by turtleDeng** [comment]
@masoud91 download the latest centos6.8 rpm package http://emqtt.com/downloads/2101/centos6-rpm

**Comment by emqplus** [comment]
@masoud91 Fixed in 2.1.0-beta.1 release
