### ISSUE TITLE
observer:start() not working ..

### ISSUE THREAD

**Issue by SumitFlochat** [emqtt/emqttd#926]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*
observer:start() throws 
** exception error: undefined function wx_object:start/3
     in function  observer_wx:start/0 (observer_wx.erl, line 72)

Need help with this?

**Comment by phanimahesh** [comment]
Wx is missing. Does your erlang installation support wx widgets?

Are you running a prebuilt release or have you compiled it yourself?

**Comment by emqplus** [comment]
@SumitFlochat Please clone 'emq-relx' project, uncomment '{wx, load}' in the relx.config, and build EMQ from source. The binary package we released officially does not contain wx library.

**Comment by SumitFlochat** [comment]
@emqplus  .
Thank you for your reply...
It's working .... :+1:
