### ISSUE TITLE
emqttd failed start and can not start anymore

### ISSUE THREAD

**Issue by okamipride** [emqtt/emqttd#928]
#### Environment

- OS: ubuntu 16.04 on AWS
- Erlang/OTP:  release,"Erlang/OTP","19","8.1"
- EMQ:  2.0.7

#### Description

*A description of the issue*

emqttd start only start " emqttd/erts-7.3/bin/epmd -daemon " 
I check error log , i found no error log or crush log. 
Please see attachment,
https://s3.ap-northeast-2.amazonaws.com/emqttd-images/emqttdstartfail.jpg

**Comment by phanimahesh** [comment]
What happens when you try `emqttd console` instead? Can you paste the full output?

**Comment by okamipride** [comment]
Thanks , I found out that was because emq_auth_mysql failed.  I will try console to see if any message shows there.
