### ISSUE TITLE
emq_mod_retainer issue in 2.0

### ISSUE THREAD

**Issue by SumitFlochat** [emqtt/emqttd#929]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

 Running make command prompts

===> Failed to solve release:
 Dependency emq_mod_retainer is specified as a dependency but is not reachable by the system.

**Comment by emqplus** [comment]
```
git clone -b 'v2.0.7p1' https://github.com/emqtt/emq-relx.git emq-relx && cd emq-relx && make
```
