### ISSUE TITLE
centos 7 rpm package conflict with chkconfig-1.3.49.5-1.el6.x86_64

### ISSUE THREAD

**Issue by masoud91** [emqtt/emqttd#937]
#### Environment

- OS: centos 7
- Erlang/OTP: 
- EMQ: 2.1.0-beta

#### Description

I install rpm file for centos 7 
there is a conflict :
`file /etc/init.d from install of emqttd-2.1-1.el6.x86_64 conflicts with file from package chkconfig-1.3.49.5-1.el6.x86_64`
I tried it using --replacefiles option but it was a critical file for OS and the OS faced problems after I remove emqttd.

**Comment by turtleDeng** [comment]
@masoud91  Please provide your installation as well as the conflicts log

**Comment by emqplus** [comment]
@turtleDeng Please create a centos7 node and try to reproduce this issue.

**Comment by turtleDeng** [comment]
@masoud91 
A new centos7, i can not reproduce your issue
![Uploading centos7.png…]()

**Comment by ankitkothana** [comment]
Is this issue fixed? I am getting following errors:

file /etc/rc.d from install of application-0:2.3.0.noarch conflicts with file from package chkconfig-1.7.4-1.el7.x86_64
file /etc/rc.d/init.d from install of application-0:2.3.0.noarch conflicts with file from package chkconfig-1.7.4-1.el7.x86_64
file /usr/local/share from install of application-0:2.3.0.noarch conflicts with file from package filesystem-3.2-25.el7.x86_64
file /etc/rc.d from install of application-0:2.3.0.noarch conflicts with file from package initscripts-9.49.41-1.el7.x86_64
file /etc/rc.d/init.d from install of application-0:2.3.0.noarch conflicts with file from package initscripts-9.49.41-1.el7.x86_64

**Comment by jjavieralv** [comment]
Check when you are coding the package if you are mapping the /rc.d directory. This may cause problems with chkconfig package because this is an OS package which manages this directory in order to manage start services. If you are mapping this dir, try to add the line <directoryIncluded>false</directoryIncluded> after close your </sources> in mapping and rebuild the rpm :)
