### ISSUE TITLE
"Node undefined not responding to pings" on Windows

### ISSUE THREAD

**Issue by chrischandler25** [emqtt/emqttd#939]
#### Environment

- OS: Windows 10 Pro
- Erlang/OTP: 
- EMQ: 2.0.7

#### Description

I have recently started using EMQTT with an IoT project.  I installed and ran it on my Ubuntu machine, with no problems at all.  As a matter of convenience, I'd like to be able to run it on my Windows PC as well during the dev process, however -

I unzip the file structure as per the documents, and launch with "bin\emqttd console", and see the following output before it stops:

C:\Program Files\emqttd>bin\emqttd console

C:\Program Files\emqttd>set args_file=-args_file "C:\Program Files\emqttd\etc\vm.args"

C:\Program Files\emqttd>set sys_config=-config "C:\Program Files\emqttd\etc\sys.config"
Node undefined not responding to pings.
Node undefined not responding to pings.
Usage: C:\Program Files\emqttd\bin\cuttlefish [-h] [-e [<etc_dir>]]
                                              [-d <dest_dir>]
                                              [-f [<dest_file>]]
                                              [-s <schema_dir>]
                                              [-i <schema_file>]
                                              [-c <conf_file>]
                                              [-a <app_config>]
                                              [-l [<log_level>]] [-p]
                                              [-m [<max_history>]]

**Comment by emqplus** [comment]
@chrischandler25 Caused by the 'Program Files' directory which contains a space.

**Comment by chrischandler25** [comment]
Ok, thanks very much for the quick response.  I'll move it to a folder without spaces and try again.

Chris
