### ISSUE TITLE
With java cycle to create a connection after 1000 slow down

### ISSUE THREAD

**Issue by lvlf** [emqtt/emqttd#942]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 
code like：
for(int i=0;i<2000;i++){
            clientid = i+"";
            MqttClient client = new MqttClient();
            client.start();
        }

1000 after a series of unstable, it is possible not to connect, or a long time to connect a successful

**Comment by phanimahesh** [comment]
@lvlf Did you check max connections in emq config? It has a conservative limit of 1024 by default.

**Comment by emqplus** [comment]
Hi @phanimahesh, I'd like to invite you to join the EMQ development team:) Please check the invitation: http://github.com/emqtt. Thanks a lot for you help.
