### ISSUE TITLE
When run: docker exec -it emqtt_xx /bin/bash 

### ISSUE THREAD

**Issue by nb7123** [emqtt/emqttd#945]
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"/bin/bash\\\": stat /bin/bash: no such file or directory\"\n"

this is the official docker image, download from: http://emqtt.com/downloads/latest/docker

**Comment by vowstar** [comment]
Hi Michael, 
This emq docker image is based on alpine linux, so it have not bash. But, you can try ash instead if bash just by remove the letter "b".

```bash
# docker run --rm -ti emqtt:latest ash
```

If you want run bash not ash, just enter image, and run

```bash
# apk update && apk add bash
# bash
```
Then you get bash.

**Comment by nb7123** [comment]
thank you, when i run sh ok ^_^
