### ISSUE TITLE
Can't install latest emqttd 2.1.0

### ISSUE THREAD

**Issue by thechamp** [emqtt/emqttd#947]
#### Environment

- OS: MacOS Sierra 10.12.3
- Erlang/OTP: 19
- EMQ: 2.1.0

#### Description

*A description of the issue*
<img width="405" alt="screen shot 2017-03-14 at 10 50 04 pm" src="https://cloud.githubusercontent.com/assets/2319535/23913422/f7f72dfc-0908-11e7-8164-f0bb424e599c.png">

**Comment by grutabow** [comment]
Please install or compile a rebar in your MacOS. For example:

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
brew install rebar

**Comment by thechamp** [comment]
Yeah. My rebar was broken, reinstalling fixed the issue.
