### ISSUE TITLE
Can do emqttd_protocol:maybe_set_clientid before authenticate? 

### ISSUE THREAD

**Issue by congleetea** [emqtt/emqttd#948]
In https://github.com/emqtt/emqttd/blob/master/src/emqttd_protocol.erl#L185 , if place function **maybe_set_clientid** after authenticate, when we use clientId in authentication plugins, it will differ from other place. 

So , I think it is better that place it before authentication, like this:

````
case validate_connect(Var, State1) of
        ?CONNACK_ACCEPT ->
            %% Generate clientId if null
            State2 = maybe_set_clientid(State1),
            case authenticate(client(State2), Password) of
                {ok, IsSuperuser} ->
    ......
````

**Comment by phanimahesh** [comment]
Yep, sounds good IMO. One catch is that if any authentication plugins handle missing client id as a special case, this will be a breaking change.

**Comment by emqplus** [comment]
@phanimahesh This will be a API breaking change, I think. The authentication is based on original clientId and username.
