### ISSUE TITLE
Unable to copy from /usr/local/emq-relx/rel/conf/plugins to /usr/local/emq-relx/_rel/emqttd/etc because of {copy_failed,enoent}

### ISSUE THREAD

**Issue by denghuimin** [emqtt/emqttd#950]
#### Environment

- OS: centos 6.8
- Erlang/OTP:
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]
Eshell V8.3  (abort with ^G)

- EMQ: emqttd-2.1.0

#### Description

**hello:

when i install it from source files ,it's logs as following ,what's the problem?how can i solve it ?**

===> Starting relx build process ...
===> Resolving OTP Applications from directories:
/usr/local/emq-relx/deps
/usr/local/lib/erlang/lib
/usr/local/emq-relx/apps
/usr/local/emq-relx/_rel
===> Resolved emqttd-2.1.0
===> Including Erts from /usr/local/lib/erlang
===> release successfully created!
**===> Unable to copy from /usr/local/emq-relx/rel/conf/plugins to /usr/local/emq-relx/_rel/emqttd/etc because of {copy_failed,
enoent}
Unable to read template file (/usr/local/emq-relx/rel/conf/emq.conf) for overlay due to: no such file or directory
Unable to copy from /usr/local/emq-relx/rel/conf/acl.conf to /usr/local/emq-relx/_rel/emqttd/etc/acl.conf because of {copy_failed,
enoent}
Unable to copy from /usr/local/emq-relx/rel/schema to /usr/local/emq-relx/_rel/emqttd/releases/2.1.0 because of {copy_failed,
enoent}**

**Comment by emqplus** [comment]
Cool issue.
