### ISSUE TITLE
Certificate Revocation

### ISSUE THREAD

**Issue by baer-devl** [emqtt/emqttd#951]
#### Environment

- OS: Docker version 17.03.0-ce | debian:jessie based
- Erlang/OTP: 17 [erts-6.2]
- EMQ: Version 1.0.1 [Customized]

#### Description

I am trying to use letsencrypt to get certificates for TLS connections. Using the generated certs is pretty easy and works fine!
Unfortunately, the certs have to be renewed every 90 days. I tested what happens when I replace the certificates in the release folder 'rel/emqttd/etc/ssl/' with a new version. All new connections will be served with the new certificate but connections which were established previously stuck with the old certificate even if its already revoked. I know that such connections will be cached but it still is the case after 24 hours which is the default maximum of caching such connections.
Is the connection held in the session of emq? If that's the case it could be that the connections will be hold multiple month's (depending on the settings). Considering security, this should not be possible - what can we do against this behavior?

**Comment by phanimahesh** [comment]
From security perspective, is it an issue if already established connections remain so? What would be possible for an attacker if it is not done? I'm trying to understand this better.

What do you mean by caching here? As far as I know, a connection uses certificates only in the initial handshake. Later a session key is generated which is used for securing all further communication. Any client which is reconnecting will use the new certificates.

Are you proposing that a renegotiation/rekeying should happen in the existing connection? I vaguely recollect reading about ssl renegotiations, but not sure. Or do you propose that the connection should be terminated, new certificate will be used when reconnecting?

**Comment by baer-devl** [comment]
I agree with you!

I was believing that the session key will expire after a certain limit. After a short research this seems not to be the case. Session keys will be valid until one of the peers decides its not. So no certificates will be used at this time.

So no, there are no security issue with that behavior.

Thanks for the quick answer!
