### ISSUE TITLE
Unexpected Info

### ISSUE THREAD

**Issue by huangdan** [emqtt/emqttd#963]
#### Environment

- OS: Ubuntu
- Erlang/OTP: R19.3
- EMQ: v2.1.0-rc.1

#### Description

When two WebSocket clients connect to the broker with the same clientId, the error logs:

```
14:54:24.139 [error] WsClient(127.0.0.1:50205): Unexpected Info: {'EXIT',<0.1371.0>,{shutdown,conflict}}
```

**Comment by emqplus** [comment]
Fixed. @huangdan please verify the issue on emq20 branch.
