### ISSUE TITLE
EMQTTD INFO

### ISSUE THREAD

**Issue by satrox28** [emqtt/emqttd#965]
#### Environment

- OS: Ubuntu 16.10
- Erlang/OTP: 1.91 
- EMQ: 2.1

#### Description

under The messages data Metrics on UI, it shows the below info

The messages data
received	2023218
sent	121949
dropped	3415976

Can we know why dropped shows 3415976, does it mean this mean dropped and not delivered. Clients are using QOS2.

**Comment by congleetea** [comment]
some messages no any subscription may be also dropped message.
