### ISSUE TITLE
Shared subscription cluster

### ISSUE THREAD

**Issue by mruepp** [emqtt/emqttd#967]
I read that shared subscriptions are not working over clustered nodes, but when I connect to emq cluster (over a round robin dns fqdn) with multiple mosquitto_sub I get messages.

Are shared subscriptions working with emq cluster? We use latest docker container.

Also fyi, the node-red mqtt node does not work with the $queue, $local or $share prefixes.

Regards,

Michael

**Comment by emqplus** [comment]
@mruepp
1. Yes. The shared subscriptions cannot be across cluster nodes.
2. The node-red, mqtt.Fx tools have no idea on shared subscriptions which defined in MQTT 5 specifications, they will drop the messages silently.

**Comment by MarcMagnin** [comment]
Hi,

Is shared subscriptions in cluster planned?

Regards,
Marc
