### ISSUE TITLE
How to build only the emq_plugin_template 

### ISSUE THREAD

**Issue by michaelcplusplus** [emqtt/emqttd#978]
#### Environment

- OS: Windows10 
- Erlang/OTP: 18.3
- EMQ: 2.0.7

#### Description

I want to build only the plugin emq_plugin_template from the command line. What is the recommend way.
The build with the make call in the emq-relx directory works but it is very **slow** on windows with msys2. 
It takes up to 4 minutes to get the compiled beam files in the 
_rel\emqttd\lib\emq_plugin_template-2.0.7\ebin directory.

**Comment by emqplus** [comment]
@michaelcplusplus Clone the `emq-plugin-template` project and make.
