### ISSUE TITLE
Debug in project 

### ISSUE THREAD

**Issue by truonglx-56** [emqtt/emqttd#979]
#### Environment

I use intelliJ , please tell me "how to debug project"

**Comment by emqplus** [comment]
@truonglx-56 Cannot debug emqttd in IntelliJ.

**Comment by truonglx-56** [comment]
So can I debug on another ide?and how?

**Comment by emqplus** [comment]
No IDE supports Erlang debug for the language is concurrent and functional, I think.

**Comment by phanimahesh** [comment]
You can debug erlang applications by tracing their execution live. Please checkout module `dbg` from otp or the library `recon`.
