### ISSUE TITLE
emqtt key_exists issue

### ISSUE THREAD

**Issue by loss2profit** [emqtt/emqttd#980]
#### Environment

- OS:  Ubuntu 14.04.5
- Erlang/OTP: R19/8.1
- EMQ: 2.1.0

#### Description

On doing a load test with 10K devices , we observed sudden ram spikes(sudden increase in RAM), on checking up the error logs found out the below.
```
[error] <0.1568.0> CRASH REPORT Process <0.1568.0> with 1 neighbours exited with reason: {key_exists,20481} in gb_trees:insert_1/4 line 318 in gen_server2:terminate/3 line 1157
[error] <0.1131.0> Supervisor emqttd_session_sup had child session started with {emqttd_session,start_link,undefined} at <0.1568.0> exit with reason {key_exists,20481} in gb_trees:insert_1/4 line 318 in context child_terminated
[error] <0.1248.0> Supervisor 'esockd_connection_sup - <0.1248.0>' had child connection started with emqttd_client:start_link([{client_idle_timeout,86400000},{client_enable_stats,true},{max_clientid_len,1024},{max_packet_size,...}]) at <0.2541.0> exit with reason {key_exists,20481} in gb_trees:insert_1/4 line 318 in context connection_crashed
[error] <0.676.272> gen_server <0.676.272> terminated with reason: {key_exists,45018} in gb_trees:insert_1/4 line 318
```

we are using MQTT with ssl connectivity

**Comment by emqplus** [comment]
@loss2profit Could you describe the load test case in more details? Do the 10k devices publish messages to a topic, which consumed by only one subscriber?

**Comment by loss2profit** [comment]
Hi @emqplus  & @turtleDeng ,

Thanks for the reply. 

Yes all the 10K devices are posting to the same topic and there is  a single subscriber to that topic. the subscriber did not crash however. Please find a few lines from crash dump below.

=erl_crash_dump:0.3
Thu Apr  6 01:28:46 2017
Slogan: eheap_alloc: Cannot allocate 1898305688 bytes of memory (of type "old_heap").
System version: Erlang/OTP 19 [erts-8.1] [source-4cc2ce3] [64-bit] [smp:4:4] [async-threads:32] [hipe] [kernel-poll:true]
Compiled: Wed Oct 12 12:28:55 2016
Taints: dyntrace,crypto,asn1rt_nif,erl_tracer
Atoms: 32937
Calling Thread: scheduler:4
=scheduler:1
Scheduler Sleep Info Flags: SLEEPING | TSE_SLEEPING | WAITING
Scheduler Sleep Info Aux Work:
Current Port:
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | HALFTIME_OUT_OF_WORK
Current Process:
=scheduler:2
Scheduler Sleep Info Flags: SLEEPING | TSE_SLEEPING | WAITING
Scheduler Sleep Info Aux Work:
Current Port:
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | HALFTIME_OUT_OF_WORK
Current Process:
=scheduler:3
Scheduler Sleep Info Flags: SLEEPING | POLL_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: THR_PRGR_LATER_OP
Current Port:
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | HALFTIME_OUT_OF_WORK
Current Process:
=scheduler:4
Scheduler Sleep Info Flags:
Scheduler Sleep Info Aux Work:
Current Port:
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | NONEMPTY | UNKNOWN(134217728)
Current Process: <0.4504.374>
Current Process State: Garbing
Current Process Internal State: ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING | GC | ON_HEAP_MSGQ
Current Process Program counter: 0x00007f7a3c471d70 (lager_trunc_io:alist/3 + 8)
Current Process CP: 0x00007f7a3c2f2e30 (lager_format:iolist_to_chars/1 + 168)
Current Process Limited Stack Trace:
0x00007f7965a0e208:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e218:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e228:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e238:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e248:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e258:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e268:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e278:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e288:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e298:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e2a8:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e2b8:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e2c8:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e2d8:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e2e8:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e2f8:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e308:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e318:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e328:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e338:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e348:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e358:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e368:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e378:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e388:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e398:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e3a8:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e3b8:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e3c8:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e3d8:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e3e8:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e3f8:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e408:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e418:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e428:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e438:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e448:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e458:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e468:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e478:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e488:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e498:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)
0x00007f7965a0e4a8:SReturn addr 0x3C2F2E30 (lager_format:iolist_to_chars/1 + 168)

**Comment by emqplus** [comment]
@loss2profit You cannot benchmark the broker like this case:) The subscriber cannot consume messages timely for there are too many publishers, and then all the messages will be accumulated in memory and crash the VM finally.

The shared subscription feature is for the case: http://emqtt.io/docs/v2/advanced.html#shared-subscription

The benchmark report for 2.0 from our partner XMeter: http://emq-xmeter-benchmark-en.readthedocs.io/en/latest/

**Comment by phanimahesh** [comment]
To run such a load test you'll need a server with more RAM, or more subscribers running in shared mode to drain the in memory message queue faster.
>  Slogan: eheap_alloc: Cannot allocate 1898305688 bytes of memory (of type "old_heap").
Erlang VM was trying to allocate approx 1.76GB of additional RAM, inspired by your rapid usage.
