### ISSUE TITLE
Unable to build on OSX 10.12

### ISSUE THREAD

**Issue by pritstift** [emqtt/emqttd#989]
#### Environment

- OS: 10.12.03
- Erlang/OTP: 19.3
- EMQ: 2.1

#### Description

I tried to build from source. At some point this error shows up. Any idea?

```
DEP    eredis
mkdir -p ebin
cp -f -- src/eredis.app.src ebin/eredis.app
sed "s/{{EXTRA_OPTS}}//" Emakefile.src > Emakefile
erl -noinput -eval 'up_to_date = make:all()' -s erlang halt

=PROGRESS REPORT==== 10-Apr-2017::17:25:56 ===
          supervisor: {local,sasl_safe_sup}
             started: [{pid,<0.56.0>},
                       {id,alarm_handler},
                       {mfargs,{alarm_handler,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 10-Apr-2017::17:25:56 ===
          supervisor: {local,sasl_sup}
             started: [{pid,<0.55.0>},
                       {id,sasl_safe_sup},
                       {mfargs,
                           {supervisor,start_link,
                               [{local,sasl_safe_sup},sasl,safe]}},
                       {restart_type,permanent},
                       {shutdown,infinity},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 10-Apr-2017::17:25:56 ===
          supervisor: {local,sasl_sup}
             started: [{pid,<0.57.0>},
                       {id,release_handler},
                       {mfargs,{release_handler,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 10-Apr-2017::17:25:56 ===
         application: sasl
          started_at: nonode@nohost
Recompile: src/eredis_sub_client
include/eredis.hrl:24: type queue() undefined
{"init terminating in do_boot",{{badmatch,error},[{erl_eval,expr,3,[]}]}}
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done
make[2]: *** [compile] Error 1
make[1]: *** [deps] Error 2
make: *** [deps] Error 2
```

**Comment by turtleDeng** [comment]
@pritstift 
![989](https://cloud.githubusercontent.com/assets/1830077/24889654/c73c54d0-1e9d-11e7-8d99-f6612e045a10.png)
I tried to compile in Erlang/OTP R19.3, can not reappear your problem, I suggest you Erlang/OTP downgrade to R19.1 try

**Comment by emqplus** [comment]
@turtleDeng Do you upgrade your MacBook to 10.12?

**Comment by pritstift** [comment]
I tried with Erlang 19.01. Same issue.

I am running on Mac OS 10.12.3

I installed Erlang using the Erlang installer. I will try installing it with homebrew. Problem might be that on Mac OS Sierra `wxmac` will not compile. Therefore i will try `brew install erlang --without-wxmac`.

Is `wxmac` needed to compile EMQ?

**Comment by emqplus** [comment]
@pritstift No need to install `wxmac`

**Comment by pritstift** [comment]
Well unfortunately it still does not work :-(

**Comment by qingchuwudi** [comment]
@pritstift 

It is  `eredis`. Because otp uses `queue:queue()` instead of `queue()` now.
```erlang
... ...
include/eredis.hrl:24: type queue() undefined
... ...
```
You should add `{platform_define, "^[0-9]+", namespaced_types}` into `{erl_opts, [  ]}.` which is in rebar.config.

See [Erlang 17.0: Supporting Deprecated Types Without Removing warnings_as_errors](https://blog.kempkens.io/posts/erlang-17-0-supporting-deprecated-types-without-removing-warnings_as_errors/)
