### ISSUE TITLE
start error: Node not responding to pings

### ISSUE THREAD

**Issue by wang911hehai** [emqtt/emqttd#992]
#### Environment

- OS: 
[root@csh_agw_sgw_2 bin]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- EMQ: 
version is  emqttd-centos7-v2.0.7.zip

#### Description
emqttd start log :
[root@csh_agw_sgw_2 bin]# ./emqttd start
[root@csh_agw_sgw_2 bin]# ./emqttd_ctl status

=ERROR REPORT==== 11-Apr-2017::15:27:52 ===
** System running to use fully qualified hostnames **
** Hostname csh_agw_sgw_2 is illegal **
Node emqttd@csh_agw_sgw_2 not responding to pings.

sub process of emqttd is starting :
[root@csh_agw_sgw_2 ~]# ps -ef|grep emqttd
root      2335     1  0 15:27 ?        00:00:00 /opt/emqttd/erts-7.3/bin/epmd -daemon
root      2343     1  0 15:27 ?        00:00:00 /opt/emqttd/erts-7.3/bin/run_erl -daemon /tmp/erl_pipes/emqttd@csh_agw_sgw_2/ /opt/emqttd/log exec "/opt/emqttd/bin//emqttd" "console"
root      2344  2343  0 15:27 pts/1    00:00:01 /opt/emqttd/erts-7.3/bin/beam -W w -e 256000 -Q 131052 -P 524208 -A 32 -K true -zdbbl 32768 -- -root /opt/emqttd -progname opt/emqttd/bin//emqttd -- -home /root -- -boot /opt/emqttd/releases/2.0.7/emqttd -mode embedded -boot_var ERTS_LIB_DIR /opt/emqttd/erts-7.3/../lib -mnesia dir "/opt/emqttd/data/mnesia/emqttd@csh_agw_sgw_2" -config /opt/emqttd/data/configs/app.2017.04.11.15.27.25.config -kernel net_ticktime 60 -smp auto -setcookie emq_dist_cookie -name emqttd@csh_agw_sgw_2 -vm_args /opt/emqttd/data/configs/vm.2017.04.11.15.27.25.args -- console
root      2508  2344  0 15:27 ?        00:00:00 /opt/emqttd/lib/os_mon-2.4/priv/bin/memsup
root      2510  2344  0 15:27 ?        00:00:00 /opt/emqttd/lib/os_mon-2.4/priv/bin/cpu_sup
root      2889  2265  0 15:30 pts/0    00:00:00 grep --color=auto emqttd

**Comment by vidhill** [comment]
I think I had this issue before, it doesn't like the underscores in your hostname

If you're able to change your hostname swap underscores for dashes

**Comment by emqplus** [comment]
@wang911hehai Add a host in /etc/hosts:

```
127.0.0.1 csh_agw_sgw_2
```
